strapi/strapi

packages/core/content-type-builder/admin/src/components/FormModal/index.js
packages/core/content-type-builder/admin/src/components/Relation/RelationField/RelationTargetPicker/index.js
packages/core/content-type-builder/admin/src/utils/index.js
packages/core/content-type-builder/admin/src/utils/isAllowedContentTypesForRelations.js
packages/core/content-type-builder/admin/src/utils/tests/isAllowedContentTypesForRelations.test.js
packages/core/content-type-builder/server/controllers/validation/relations.js

Fix the content type list in the relation form edit (Content type builder)
https://github.com/strapi/strapi/issues/11456

Fix CT list in relations (content type builder)

---

packages/core/admin/admin/src/components/LeftMenu/index.js

Fixed LinkUserWrapper radius in LeftMenu

[QA] Fixed user links LeftMenu radius

---

packages/plugins/users-permissions/admin/src/components/Permissions/index.js
packages/plugins/users-permissions/admin/src/components/UsersPermissions/index.js
packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js

Fixed AccordionContent radius
Fixed padding between Accordions
Fixed padding between Accordions and title/subtitle

[QA] Fix accordion in U&P Roles

---

packages/core/strapi/lib/core/loaders/plugins/index.js

Use assign to keep keys that are not extended by default. Set password as required in the CM for u&p

Use assign to keep keys that are not extended by default. Set password as required in the CM for u&p

---

packages/cli/create-strapi-app/create-strapi-app.js

Fixes a bug happening when the projectName is not specified in the command, was crashing instead of prompting for a project name

fix: checking if projectName is defined before trying to resolve

---

packages/core/admin/admin/src/content-manager/pages/App/index.js
packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js
packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
packages/core/admin/admin/src/pages/InstalledPluginsPage/index.js
packages/core/content-type-builder/admin/src/pages/App/index.js
packages/core/upload/admin/src/pages/App/index.js
packages/plugins/documentation/admin/src/pages/PluginPage/index.js
packages/plugins/documentation/admin/src/pages/PluginPage/tests/index.test.js

It displays the page title in the navigator tab

[v4] Fix admin helmet

---

packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
packages/core/content-type-builder/server/controllers/validation/types.js
packages/core/strapi/lib/services/entity-service/index.js
packages/core/strapi/lib/services/entity-validator/__tests__/validators.test.js
packages/core/strapi/lib/services/entity-validator/index.js
packages/core/strapi/lib/services/entity-validator/validators.js
packages/core/strapi/tests/migrations/migration-draft-publish.test.e2e.js
packages/core/strapi/tests/migrations/migration-unique-attribute.test.e2e.js

Add `unique` validator. it also removes the possibility to add the unique "constraint" on several types.
This enables the unique constraint on attributes.

[v4] add `unique` validator

---

package.json
packages/admin-test-utils/package.json
packages/cli/create-strapi-app/package.json
packages/cli/create-strapi-starter/package.json
packages/core/admin/package.json
packages/core/content-manager/package.json
packages/core/content-type-builder/package.json
packages/core/database/package.json
packages/core/email/package.json
packages/core/helper-plugin/package.json
packages/core/upload/package.json
packages/core/utils/package.json
packages/generators/app/package.json
packages/generators/generators/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json
packages/providers/email-amazon-ses/package.json
packages/providers/email-mailgun/package.json
packages/providers/email-nodemailer/package.json
packages/providers/email-sendgrid/package.json
packages/providers/email-sendmail/package.json
packages/providers/upload-aws-s3/package.json
packages/providers/upload-cloudinary/package.json
packages/providers/upload-local/package.json
packages/providers/upload-rackspace/package.json
packages/utils/babel-plugin-switch-ee-ce/package.json
packages/utils/logger/package.json

Cleaning up package.json files

Cleanup and normalize package.json files

---

packages/core/content-manager/server/services/entity-manager.js
packages/core/strapi/lib/services/entity-validator/validators.js

PR that fixes unique validation errors on publish

Pass entity down to the validatCreation for publish and handle undefined value

---

packages/core/strapi/bin/strapi.js
packages/core/strapi/lib/commands/controllers/list.js

Add controllers:list command
Consistency

Add controllers:list command

---

packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js
packages/core/admin/admin/src/content-manager/pages/EditView/Header/tests/index.test.js
packages/core/admin/admin/src/pages/AuthPage/components/Login/tests/BaseLogin.test.js
packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/__snapshots__/index.test.js.snap
packages/core/helper-plugin/lib/src/components/PaginationURLQuery/tests/__snapshots__/index.test.js.snap
packages/core/helper-plugin/lib/src/components/PaginationURLQuery/tests/index.test.js
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromComputerForm.test.js
packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/__snapshots__/PendingAssetStep.test.js.snap
packages/core/upload/admin/src/components/UploadAssetDialog/tests/__snapshots__/UploadAssetDialog.test.js.snap
packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
yarn.lock

Run Yarn upgrade to get and updated yarn lock

Yarn upgrade

---

packages/core/admin/package.json
yarn.lock

Bump webpack-cli & webpack-dev-server. No breaking changes on those version

Fix webpack dev version

---

packages/core/admin/admin/src/pages/AuthPage/index.js

- Fixed login error message: The path to the error message was incorrect which led to "Something went wrong" message instead of "Invalid Credentials"
- Improved lodash method import
Try to login with wrong credentials and login
You should see "Invalid credentials" appear
fix #11737

[Admin] Login error message fix

---

packages/providers/upload-aws-s3/README.md

I forgot to end my code block :see_no_evil:

Fix typo in in AWS-S3 Provider ReadMe

---

packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js

It fixes #11908 
To prevent the admin from crashing.
The issue should be fixed.

Fix copy from another locale with DZ

---

README.md
packages/core/strapi/README.md

Based on: https://github.com/strapi/documentation/pull/593
Updates the minimum database versions for MySQL and MariaDB for v4

Update required database versions

---

packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js

Fixed display of error messages in the admin panel. Worth checking out! I proceeded from the error structure described here:
https://docs.strapi.io/developer-docs/latest/developer-resources/error-handling.html#rest-errors
[Describe the issue you are solving.](https://forum.strapi.io/t/error-handling-lifecycles-js/13044)
I was validating data at the middleware layer and submitting an error. The goal is to see the text of the message and not "Bad Request"
I did not find

fix error message in admin panel

---

packages/core/strapi/lib/commands/develop.js

It adds the front-end files to the ignored files of the watch mode.

Remove admin files from watched files

---

packages/generators/app/lib/create-quickstart-project.js

It removes the build step from the installation script.
In order to serve the prebuilt admin panel.

Remove build from install script

---

packages/generators/generators/lib/templates/policy.js.hbs

Minor fix for the policy generator template for V4
Generating a policy in V4 using the CLI will result in creating a policy file with an invalid method signature that causes the server to crash
```javascript
module.exports = (config, { strapi }) => {
return policyCtx => {
```
This PR fixes the policy template to generate a policy file with the correct method signature 
```javascript
module.exports = (policyContext, config, { strapi }) => {
// Add your own logic here.
strapi.log.info('In {{id}} policy.');
```

Fix generator policy template

---

packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/index.js
packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js

Fix menu link without search in CM

---

packages/core/email/admin/src/pages/Settings/utils/api.js
packages/core/email/admin/src/utils/axiosInstance.js

It fixes #12034, wrong axios instance in email plugin.

Fix wrong axios instance in email plugin

---

packages/core/admin/admin/src/components/GuidedTour/index.js
packages/core/admin/admin/src/components/GuidedTour/reducer.js
packages/core/admin/admin/src/components/GuidedTour/tests/reducer.test.js
packages/core/admin/admin/src/components/Providers/index.js
packages/core/helper-plugin/lib/src/contexts/GuidedTourContext.js
packages/core/helper-plugin/lib/src/hooks/useGuidedTour/index.js
packages/core/helper-plugin/lib/src/index.js
packages/core/helper-plugin/lib/src/providers/GuidedTourProvider/index.js

- adds guided tour context, hook and provider to helper-plugin
- in the admin: using helpers + init reducer

Feature(GuidedTour)/ Init helper plugin + admin

---

packages/core/admin/index.html

It removes the hard coded background in the index.html file.
In order to be able to customise the theme.
Fixes #12045

Fixes #12045

---

packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
packages/core/admin/admin/src/pages/AuthPage/utils/forms.js
packages/core/admin/admin/src/translations/en.json
packages/core/helper-plugin/lib/src/utils/translatedErrors/index.js

It fixes #12089 
To highlight the email field.

Add lowercase validation to email for registering admin user.

---

packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/index.js
packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js
packages/core/content-type-builder/admin/src/components/ListRow/index.js
packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap

Add the description to the DZ fields in the CM edit view
- Create a content type with a dynamic zone
- Add a description to this field
- Create a new entry on this new model
- Add components to this dynamic zone
- The description should be visible under the DZ name

Add DZ description

---

packages/plugins/users-permissions/server/services/user.js
packages/plugins/users-permissions/server/services/users-permissions.js

Fix confirmation url missing the api prefix

---

packages/core/admin/admin/src/components/AuthenticatedApp/index.js
packages/core/admin/admin/src/components/AuthenticatedApp/tests/index.test.js
packages/core/admin/admin/src/components/AuthenticatedApp/utils/api.js
packages/core/admin/admin/src/components/GuidedTour/index.js
packages/core/admin/admin/src/components/GuidedTour/reducer.js
packages/core/admin/admin/src/components/GuidedTour/utils/handleGuidedTourVisibility.js
packages/core/admin/admin/src/components/GuidedTour/utils/isGuidedTourComplete.js
packages/core/admin/admin/src/components/GuidedTour/utils/tests/handleGuidedTourVisibility.test.js
packages/core/admin/admin/src/components/GuidedTour/utils/tests/isGuidedTourComplete.test.js
packages/core/admin/admin/src/pages/HomePage/index.js
packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
packages/core/helper-plugin/lib/src/providers/GuidedTourProvider/index.js

- guidedTourVisibility and setGuidedTourVisibility created to handle visibility of guided tour depending on user's role
- show guided tour if guidedTourVisibility true and guided tour not complete

(Feature-GuidedTour)/Add stepper to homepage

---

packages/core/admin/admin/src/components/UpgradePlanModal/index.js

Close the community edition limitation modal (Add new role)
- Start Strapi CE
- Go to Settings > Roles
- Click on "Add new role"
- Click outside the modal to close

Close on click outside CE limitation modal

---

packages/core/admin/index.js

Fixes admin build when removing optional plugins

---

packages/core/admin/admin/src/components/GuidedTour/GuidedTourModal/index.js
packages/core/admin/admin/src/components/GuidedTour/index.js
packages/core/admin/admin/src/components/GuidedTour/reducer.js
packages/core/admin/admin/src/pages/Admin/index.js
packages/core/admin/admin/src/pages/Admin/tests/index.test.js
packages/core/helper-plugin/lib/src/providers/GuidedTourProvider/index.js

- Created modal skeleton
- Added it to admin
- Added setStepState and setCurrentStep logic within the modal

(Feature: Guided tour) Modal skeleton

---

packages/core/admin/admin/src/components/GuidedTour/init.js
packages/core/admin/admin/src/components/GuidedTour/utils/persistStateToLocaleStorage.js

- On reducer initialization, if current step in locale storage, update guided tour state

(Feature: Guided tour) Validate step on reload

---

packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
packages/core/admin/admin/src/content-manager/pages/App/index.js
packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/tests/index.test.js

It triggers the modal according to user interactions in pages:
- /content-manager
- /settings/api-tokens

Guided tour/trigger modal

---

packages/core/admin/admin/src/content-manager/components/InputJSON/FieldWrapper.js
packages/core/admin/admin/src/content-manager/components/InputJSON/Label.js
packages/core/admin/admin/src/content-manager/components/InputJSON/index.js

Fix JSON input required UI

---

packages/core/admin/admin/src/components/GuidedTour/GuidedTourHomepage/index.js
packages/core/admin/admin/src/components/GuidedTour/GuidedTourModal/index.js
packages/core/admin/admin/src/components/GuidedTour/index.js
packages/core/admin/admin/src/components/GuidedTour/init.js
packages/core/admin/admin/src/components/GuidedTour/reducer.js
packages/core/admin/admin/src/components/GuidedTour/utils/persistStateToLocaleStorage.js
packages/core/admin/admin/src/pages/HomePage/index.js
packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
packages/core/helper-plugin/lib/src/providers/GuidedTourProvider/index.js

- Added skipped logic
- Once it's skipped, can't be resumed
- Click on skip button on guided tour modal or guided tour homepage

(Feature: Guided tour) Skip

---

packages/core/content-type-builder/admin/src/components/DataManagerProvider/index.js

- Ensure guided tour step validation occurs on collection-type creation only

fix(guidedTour): trigger modal only at collection-type creation

---

packages/core/admin/admin/src/components/GuidedTour/Stepper/Modal/StepperModal.js
packages/core/admin/admin/src/components/GuidedTour/layout.js

- Handle links in guided tour modals
- Removes cta on API token success modal

feat(guidedTour): handle cta targets + various fixes

---

packages/core/admin/admin/src/components/GuidedTour/Modal/components/Modal.js
packages/core/admin/admin/src/components/GuidedTour/Modal/components/Stepper.js
packages/core/admin/admin/src/components/GuidedTour/Modal/index.js
packages/core/admin/admin/src/components/GuidedTour/Modal/reducer.js
packages/core/admin/admin/src/components/GuidedTour/Modal/tests/index.test.js
packages/core/admin/admin/src/components/GuidedTour/layout.js

- fixes proptype error stepper CTA
- fixes homepage redirection to API token
- hides skip button on lthe last onboarding modal

Guided tour/last step fixes

---

packages/core/admin/admin/src/components/GuidedTour/Homepage/components/Step.js
packages/core/admin/admin/src/components/GuidedTour/Homepage/components/Stepper.js
packages/core/admin/admin/src/components/GuidedTour/Modal/components/Stepper.js
packages/core/admin/admin/src/components/GuidedTour/Modal/tests/index.test.js

- Added Arrow icon to modal CTA's
- Refacto Stepper homepage broken on Safari

(Feature - Guided tour) QA fix + Homepage refacto

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
packages/core/admin/admin/src/translations/en.json

Small product copy enhancement.
Add an entry replaced by Create new API Token"

Product copy API Tokens

---

packages/core/admin/admin/src/components/GuidedTour/index.js
packages/core/admin/admin/src/components/GuidedTour/utils/arePreviousStepsDone.js
packages/core/admin/admin/src/components/GuidedTour/utils/tests/arePreviousSptesDone.test.js

Current step could be updated even if previous steps weren't done yet.
Try to create an entry in CM before completing CTB section
CM success Modal shouldn't appear

(Fix - Guided tour) Step validation order

---

.github/dependabot.yml

Change dependanbot config to only upgrade non major versions

---

packages/core/helper-plugin/lib/src/components/DateTimePicker/index.js
packages/core/helper-plugin/lib/src/components/GenericInput/index.js

Clear datetime or date should set value to null 
if the value is '', new Date(value) will lead 'Invalid Date' and validation will return false.
In CM edit view, choose a date or datetime field, select a date and then clear the date field, press save button
https://github.com/strapi/strapi/issues/12431#issue-1127010602

Clear datetime or date should set value to null

---

packages/core/content-type-builder/admin/src/components/DynamicZoneList/index.js
packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap

Fixes a typo, which lead to the wrong typography being applied.
A beautiful UI.
1. Go to the content type builder
2. Head over to a components list
3. Check the fontsize of the "add a component" cta

DynamicZoneList: fix cta typography

---

packages/core/admin/package.json

Upgrades fp to the latest version

Enhancement: Upgrade fp version to 3.2.2

---

packages/plugins/documentation/server/services/documentation.js

Fixes the settings override in the documentation plugin
Completes the work started on: https://github.com/strapi/strapi/pull/12070 and https://github.com/strapi/strapi/pull/12341
co-authored by: @kayac-chang @roelbeerens 
The settings override doesn't work...
Create a file at `./extensions/documentation/config/settings.json` copy [this](https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings) and edit the fields you want to modify
closes: https://github.com/strapi/strapi/pull/12341
closes: https://github.com/strapi/strapi/pull/12070 
closes: https://github.com/strapi/strapi/issues/12046
closes: https://github.com/strapi/strapi/issues/11840

Fix custom settings override

---

examples/getstarted/.env.example
examples/kitchensink/config/server.js

It allows to start the kitchensink app.

Fix kitchensink

---

packages/plugins/gatsby-preview/README.md

Add Readme for gatsby plugin preview

---

packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
packages/core/admin/admin/src/pages/ProfilePage/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/__snapshots__/index.test.js.snap
packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/tests/index.test.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/__snapshots__/index.test.js.snap
packages/core/admin/package.json
packages/core/email/admin/src/pages/Settings/tests/index.test.js
packages/core/helper-plugin/package.json
packages/core/upload/admin/src/components/AssetCard/tests/DocAssetCard.test.js
packages/core/upload/admin/src/components/AssetCard/tests/ImageAssetCard.test.js
packages/core/upload/admin/src/components/AssetList/tests/AssetList.test.js
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/MediaLibraryInput/tests/__snapshots__/MediaLibraryInput.test.js.snap
packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/__snapshots__/PendingAssetStep.test.js.snap
packages/core/upload/admin/src/pages/SettingsPage/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
yarn.lock

I just realized that updating the design system in branches doesn't work well, because many snapshot tests need to be regenerated. Therefore this PR wants to update the dependency globally.
To stay up-to-date with the latest & greatest changes.
- https://github.com/strapi/strapi/pull/12428
- https://github.com/strapi/strapi/pull/12398

chore: Bump design-system version

---

packages/core/admin/admin/src/pages/MarketplacePage/index.js
packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js
packages/core/admin/admin/src/pages/MarketplacePage/utils/api.js
packages/core/admin/env.js

Fetches plugins from the marketplace API
To build the in app marketplace!
- Update the `.env` in `/packages/core/admin` with `STRAPI_ADMIN_MARKETPLACE_API_URL=<hosted-proxy-api | local-server>` 
- Log `data` from `useQuery`

[MARKET] Fetch plugins

---

packages/core/admin/admin/src/components/GuidedTour/init.js
packages/core/admin/admin/src/components/GuidedTour/reducer.js
packages/core/admin/admin/src/components/GuidedTour/tests/index.test.js
packages/core/admin/admin/src/pages/AuthPage/index.js

If we deploy the guided tour as it is on feature/guided-tour branch, every super admin will see the guided tour
We want to show guided tour only for new super admin
isSkipped is starting true
setSkipped to false during registration if user is super admin

(Feature/GuidedTour) Unskip at register

---

packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/isValidJSONString.test.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/isValidJSONString.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
packages/core/admin/admin/src/content-manager/components/InputJSON/index.js

fix https://github.com/strapi/strapi/issues/12040

Handle direct quotes in JSON field

---

packages/cli/create-strapi-starter/utils/fetch-npm-starter.js
packages/generators/app/lib/utils/fetch-npm-template.js

Uses execa instead of execa.shell and execa.command 
ping me

update execa commands

---

packages/plugins/i18n/server/constants/iso-locales.json
packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap

Add Mongolian language to `iso-locales.json`;  
Add Mongolain as snapshot test
Also related to [#12423](https://github.com/strapi/strapi/pull/12423)

Add Mongolian locale

---

packages/core/admin/admin/src/pages/HomePage/SocialLinks.js
packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
packages/plugins/users-permissions/admin/src/pages/EmailTemplates/components/EmailTable.js
packages/plugins/users-permissions/admin/src/pages/EmailTemplates/tests/index.test.js

Fixes icons not showing up properly

Dark mode/fix icons

---

packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js

For a product test we removed the register checkbox news for one sprint.
We now reintegrate it for the next release
Create new first super admin or create a new user
Register news checkbox should appear in registration page

Register checkbox 

---

packages/generators/generators/lib/plops/__tests__/content-type.test.js
packages/plugins/i18n/server/controllers/__tests__/content-types.test.js
packages/plugins/i18n/server/controllers/content-types.js
packages/plugins/i18n/server/services/__tests__/content-types.test.js
packages/plugins/i18n/server/services/content-types.js

fix issue mentioned there : #12183

Populate nested images for getNonLocalisedFields

---

packages/plugins/users-permissions/admin/src/components/FormModal/Input/index.js
packages/plugins/users-permissions/admin/src/components/FormModal/Input/tests/index.test.js

add missing /api in redirectUrl placeholder

---

packages/core/admin/admin/src/pages/ProfilePage/index.js

Added didChangeMode Amplitude event with NewMode (light/dark) property

[Dark mode] Tracking mode changes

---

packages/core/admin/admin/src/pages/MarketplacePage/index.js
packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js

Adds the submit plugin button to the marketplace page
Makes it easier to submit a plugin
Go to the marketplace page and click the button it should open [market.strapi.io/submit-plugin](https://market.strapi.io/submit-plugin) in a new tab

[Marketplace] Add submit plugin button

---

packages/core/admin/admin/src/pages/MarketplacePage/index.js

Adds tracking to submit button plugin

Add tracking to submit button plugin

---

examples/kitchensink-ts/tsconfig-server.json
packages/core/admin/index.js
packages/core/strapi/lib/commands/builders/typescript.js
packages/core/strapi/lib/commands/develop.js
packages/generators/app/lib/resources/json/ts/tsconfig-server.json.js
packages/generators/generators/lib/files/ts/plugin/strapi-server.js
packages/utils/typescript/lib/compile.js
yarn.lock

- do not use the watch TS compiler
- various minor fixes

[Typescript] Develop rework

---

packages/core/admin/admin/src/pages/AuthPage/index.js

It fixes the redirect URL after registering the first admin.
It makes sure that the user is always redirect to the homepage unless there's a redirectTo query params in the login page.

Fix redirection

---

packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
packages/core/admin/admin/src/content-manager/components/RepeatableComponent/AccordionGroupCustom/index.js

Fixed min error message **from** 
**to**
1 missing component
2 missing components

[Fix bug] Min error repeatable components

---

packages/core/admin/admin/src/pages/HomePage/tests/index.test.js

Fix snapshot from last-minute fix Homepage Reddit's icon made earlier

[Fix] Update snapshot Homepage Reddit's icon

---

packages/core/upload/server/bootstrap.js
packages/core/upload/server/services/provider.js

Fixes https://github.com/strapi/strapi/issues/12809
It implements `uploadStream` wrapping for `actionOptions`.
Thank you @neilpoulin for catching the issue and spotting the cause !

Fix actionOptions not taking into account by the upload provider

---

packages/core/upload/server/bootstrap.js

Reverts strapi/strapi#12838 due to failing tests on master.

Revert "Fix actionOptions not taking into account by the upload provider"

---

packages/admin-test-utils/lib/fixtures/store/index.js
packages/core/admin/admin/src/pages/Admin/index.js
packages/core/admin/admin/src/pages/Admin/tests/index.test.js
packages/core/admin/admin/src/pages/Admin/tests/useTrackUsage.test.js
packages/core/admin/admin/src/pages/App/constants.js
packages/core/admin/admin/src/pages/App/reducer.js
packages/core/admin/admin/src/reducers.js
packages/core/content-type-builder/admin/src/components/DataManagerProvider/index.js
packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/request.js
packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/serverRestartWatcher.js
packages/core/content-type-builder/admin/src/utils/axiosInstance.js

It makes sure to wait for the server to have restarted before displaying the CTB.
To improve the content modelling experience.
Tests should be done in all 3 example apps (getstarted, kitchensink, kitchensink-ts)
1. Go to the ctb and create :
- collection type
- single type
- a component
A make sure it is working correctly
2. Do the same for PUT methods (add some field, edit some...)
3. Test the DELETE method for all created data structure.

Fix CTB reloading state

---

examples/kitchensink-ts/.gitignore
examples/kitchensink-ts/package.json
packages/plugins/documentation/server/controllers/documentation.js

It fixes #12923 
To be able to access the documentation
Create some content types and try to access the documentation.

Fix documenation plugin

---

packages/plugins/i18n/server/constants/iso-locales.json
packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap

Added locales for Kyrgyz and Tajik languages

Add kyrgyz tajik languages

---

packages/generators/generators/lib/plops/plugin.js

Fix the plugin generation instruction message

[TS] Fix plugin instructions message

---

packages/generators/app/lib/resources/templates/env.template

Fix ADMIN_JWT_SECRET being generated with a space

---

packages/core/admin/utils/create-cache-dir.js
yarn.lock

It allows to build the admin panel in a non ts environnement.

Fix default tsconfig file

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/components/Form/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js

Added events:
- didChangeLogo → when a custom logo is added and change is reflected successfully
- didClickResetLogo → when logo ‘Reset' action is clicked

[Logo customization] trackUsage

---

packages/providers/email-nodemailer/package.json

Fixes https://github.com/advisories/GHSA-hwqf-gcqm-7353

Upgrade nodemailer

---

packages/core/strapi/lib/utils/update-notifier/index.js

Fixes minor typo in a function name
Clarity and readability
Not applicable

fix getUpdateMessage typo

---

packages/plugins/i18n/server/services/entity-service-decorator.js
packages/plugins/i18n/tests/content-manager/crud.test.e2e.js

Fix bulk delete for non-default locales

---

packages/core/upload/server/controllers/admin-folder-file.js
packages/core/upload/server/controllers/admin-folder.js
packages/core/upload/server/controllers/index.js
packages/core/upload/server/controllers/validation/admin/folder-file.js
packages/core/upload/server/controllers/validation/admin/folder.js
packages/core/upload/server/routes/admin.js
packages/core/upload/server/services/__tests__/file.test.js
packages/core/upload/server/services/file.js
packages/core/upload/server/services/folder.js
packages/core/upload/tests/admin/file-folder.test.e2e.js
packages/core/upload/tests/admin/folder-structure.test.e2e.js
packages/core/upload/tests/admin/folder.test.e2e.js

Ml folder/bulk delete

---

packages/core/upload/server/bootstrap.js

Fix https://github.com/strapi/strapi/issues/13052

Display error when loading upload provider

---

packages/core/upload/server/controllers/admin-folder.js
packages/core/upload/server/controllers/validation/admin/folder.js
packages/core/upload/server/routes/admin.js
packages/core/upload/server/services/folder.js
packages/core/upload/tests/admin/folder.test.e2e.js

To merge and rebase after ⚠️ https://github.com/strapi/strapi/pull/13181
- Can update the name and location of the folder and its nested folders and files

Ml folder/update folder

---

packages/core/admin/admin/src/content-manager/components/Wysiwyg/Editor.js
packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js

Allowing spellcheck on the Wysiwyg component 
Fix #13160

[Enh] Allow Wysiwyg spellcheck

---

packages/generators/app/package.json
packages/plugins/sentry/package.json

Upgrade Sentry version (both for plugin and internal) to latest

---

packages/core/strapi/lib/services/utils/upload-files.js
packages/core/upload/server/constants.js
packages/core/upload/server/content-types/file/schema.js
packages/core/upload/server/controllers/admin-folder.js
packages/core/upload/server/controllers/content-api.js
packages/core/upload/server/controllers/validation/admin/folder.js
packages/core/upload/server/graphql.js
packages/core/upload/server/services/api-upload-folder.js
packages/core/upload/server/services/folder.js
packages/core/upload/server/services/index.js
packages/core/upload/server/services/upload.js
packages/core/upload/tests/admin/folder-structure.test.e2e.js
packages/core/upload/tests/admin/folder.test.e2e.js
packages/core/upload/tests/content-api/graphql-upload-automatic-folder.test.e2e.js
packages/core/upload/tests/content-api/graphql-upload.test.e2e.js
packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js

⚠️ To merge and rebase after #13221 is merged
- Uploaded files through the content-api are located in a specific folder named "Uploads"

Ml folder/automatic upload folder

---

packages/core/upload/server/routes/admin.js

Ml folder/permissions

---

packages/core/upload/server/controllers/admin-folder.js
packages/core/upload/server/routes/admin.js
packages/core/upload/server/services/folder.js
packages/core/upload/tests/admin/folder.test.e2e.js

⚠️ To merge after #13246
- add findOne route for folders

Ml folder/get one folder

---

packages/core/upload/server/controllers/admin-file.js
packages/core/upload/tests/admin/file.test.e2e.js

⚠️  To merge after #13247 
- automatically populate `folder` for the `GET /upload/files` admin query

Ml folder/populate files

---

packages/core/content-manager/server/controllers/collection-types.js
packages/core/content-manager/server/services/entity-manager.d.ts
packages/core/content-manager/server/services/entity-manager.js
packages/core/database/lib/entity-manager.js
packages/core/strapi/lib/services/entity-service/index.d.ts
packages/core/strapi/lib/services/entity-service/index.js
packages/core/upload/server/controllers/admin-folder.js
packages/core/upload/tests/admin/folder-file.test.e2e.js
packages/core/upload/tests/admin/folder-structure.test.e2e.js
packages/core/upload/tests/admin/folder.test.e2e.js
packages/core/upload/tests/content-api/graphql-upload-automatic-folder.test.e2e.js
packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js

⚠️  to merge after #13312
Remove pagination for folders

Ml folder/folder pagination

---

packages/core/admin/server/services/__tests__/auth.test.js

Add a test case to check for invalidate password
Add more coverage to the test case
Run the test case use WebStorm IDE.

Added test case to check password validity

---

SECURITY.md

Modified to extend v3 security support until end of 2022

Update security doc to reference extended v3 support

---

packages/core/upload/admin/src/utils/getRequestUrl.js
packages/core/upload/admin/src/utils/tests/getRequestUrl.test.js

- Fixed getRequestUrl not checking path format
- added tests

[ML folder] Fix getRequestUrl

---

package.json
packages/strapi-admin/package.json
packages/strapi-plugin-upload/package.json
yarn.lock

Fixes some of the existing security vulnerabilities for the strapi v3.
Some vulnerabilities are critical, others high. See output of `yarn audit`

V3 security updates

---

packages/core/upload/admin/src/components/BulkMoveDialog/BulkMoveDialog.js
packages/core/upload/admin/src/components/BulkMoveDialog/tests/BulkMoveDialog.test.js
packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
packages/core/upload/admin/src/pages/App/components/BulkMoveButton.js
packages/core/upload/admin/src/pages/App/tests/BulkMoveButton.test.js

Moves all validation logic from the `BulkMoveButton` into the `BulkMoveDialog`, to be more self-contained.
Consistency.
I've added an automated test for it.

BulkMoveButton: Move validation into BulkMoveDialog

---

packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
packages/core/upload/admin/src/components/EditAssetDialog/index.js
packages/core/upload/admin/src/components/EditFolderDialog/EditFolderDialog.js
packages/core/upload/admin/src/components/SelectTree/Option.js
packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js

Cleanup to fix most prop-type errors in the media library.
It's obvious.

ML: Fix various prop-types errors

---

examples/getstarted/src/api/country/content-types/country/schema.json
packages/core/content-manager/server/tests/fields/date.test.e2e.js
packages/core/database/lib/metadata/index.js
packages/core/database/lib/query/query-builder.js
packages/core/upload/package.json
packages/core/upload/server/content-types/file/schema.js
packages/core/upload/server/content-types/folder/schema.js
packages/core/upload/server/controllers/admin-folder-file.js
packages/core/upload/server/controllers/validation/admin/folder-file.js
packages/core/upload/server/services/__tests__/file.test.js
packages/core/upload/server/services/__tests__/folder.test.js
packages/core/upload/server/services/folder.js
packages/core/upload/tests/admin/folder-file.test.e2e.js
packages/core/upload/tests/admin/folder.test.e2e.js
packages/core/upload/tests/content-api/graphql-upload-automatic-folder.test.e2e.js
packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js
yarn.lock

- Use `integer` for this `uid` instead of `string`
- Rename `uid` to `pathId`
- Added indexes on some columns
- Add `max` function to the `queryBuilder`

change folder uid for pathId

---

packages/core/upload/admin/src/pages/App/MediaLibrary.js

Small cleanup of the main component to improve its readability.

ML: Improve component readability

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/index.test.js
packages/core/upload/admin/src/constants.js
packages/core/upload/admin/src/hooks/__mocks__/useFolders.js
packages/core/upload/admin/src/pages/App/MediaLibrary.js
packages/core/upload/admin/src/pages/App/tests/MediaLibrary.test.js

Updated folder uid usage with uid format changes

[ML Folder] Fixed uid format usage

---

packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
packages/core/upload/admin/src/components/SelectTree/SelectTree.js
packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap

Disable search functionality on all `SelectTree` components
The way the component was built doesn't support search.

SelectTree: Disable search

---

packages/core/helper-plugin/lib/src/components/ReactSelect/ReactSelect.js
packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
packages/core/upload/admin/src/components/EditFolderDialog/EditFolderDialog.js
packages/core/upload/admin/src/components/EditFolderDialog/tests/EditFolderDialog.test.js
packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
packages/core/upload/admin/src/components/SelectTree/SelectTree.js
packages/core/upload/admin/src/hooks/__mocks__/useEditFolder.js

- Fixed EditFolderDialog form layout
- Fixed error message appearance for moving folder with EditFolderDialog
- Added danger border to React Select component on error
- Added test coverage for moving folder error

[ML Folder] Edit move error fixes

---

packages/plugins/i18n/server/constants/iso-locales.json
packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap

Adding Kara-Kalpak locale to plugin-i18n (according to https://iso639-3.sil.org/code/kaa) 
Support Kara-Kalpak locale
- Open internationalization settings page
- Add new locale
- Check that Kara-Kalpak locale appears in locales select field
none

kara-kalpak locale

---

packages/core/helper-plugin/lib/src/components/ReactSelect/ReactSelect.js

Fixed SelectTree popover overflowing - will be positioned on top of the input if no room

[ML Folder] Fixed SelectTree overflowing

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/FolderCard/FolderCard/FolderCard.js
packages/core/upload/admin/src/components/FolderCard/FolderCardBodyAction/index.js
packages/core/upload/admin/src/components/FolderCard/tests/__snapshots__/FolderCard.test.js.snap

- Added border neutral150 to FolderCard for better accessibility on the dark mode
- Added outline to title/subtitle link

[Ml Folder] Folder card enhancements 

---

packages/core/admin/webpack.alias.js

This PR cleans up the list of webpack resolvers, by adding missing ones (e.g. `formik`, `date-fns`) and removing a few, which are not required anymore (e.g. `object-assign`, `hoist-non-react-statics`). This should fix a couple issues of the type `toggleNotification is undefined`.
> **Note**
> Soupette suggested in [#12678](https://github.com/strapi/strapi/pull/12678) to remove the `whatwg-fetch` dependency. Right now this isn't possible because the polyfill is still being used by the tests. We should move the import from the file in the jest-setup files though with a later PR, to make this clear.
We need to make sure to bundle the `@strapi/helper-plugin` only once and resolve it from the same `node_modules` folder every time, otherwise the application could have different global contexts, …

Webpack: Cleanup resolver configuration

---

packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/Wrapper.js

Fixes styles for tables of the Richtext field in dark-mode. Improves the existing styles by removing hard-coded size values and replacing them with paddings.
|Before|After|
|-|-|
| <img width="1054" alt="Screenshot 2022-07-12 at 10 32 28" src="https://user-images.githubusercontent.com/2244375/178447343-ad477a31-6e94-465f-8857-e706411bd81d.png"> | <img width="1054" alt="Screenshot 2022-07-12 at 10 30 21" src="https://user-images.githubusercontent.com/2244375/178447321-06c26f09-0b60-4cb4-8cde-6581e4aee071.png"> |
|Before|After|
|-|-|
| <img width="1054" alt="Screenshot 2022-07-12 at 10 32 10" src="https://user-images.githubusercontent.com/2244375/178447340-f5613985-be89-4748-ade7-c569b9a5ed1b.png"> | <img width="1054" alt="Screenshot 2022-07-12 at 10 30 36" …

PreviewWysiwyg: Fix and improve styles for tables

---

.github/jest.config.js
jest.config.js
packages/core/admin/server/services/__tests__/user.test.js

Fixing a config with jest that was breaking jest behavior and running tests twice
To fix tests running twice
checkout the repo and try to run the different tests

Fix jest running tests twice because of .github and jest behavior

---

packages/core/admin/package.json
yarn.lock

update koa-passport to fix CVE-2022-25896

---

packages/core/database/lib/schema/diff.js

fixes: https://github.com/strapi/strapi/issues/13654

fix: diff indexes columns

---

packages/core/admin/admin/src/content-manager/components/AttributeFilter/index.js

Localized AttributeFilter
Better user experience for no-English user

update: localized attribute filter

---

packages/core/admin/admin/src/components/LeftMenu/index.js

Reverts strapi/strapi#13951
I've mixed this PR up with another one and @maevalienard and I decided that she wants to explore the possible uses-cases a bit further, before moving forward with this.

Revert "add badgeContent to pluginsSectionsLinks"

---

packages/core/upload/server/services/upload.js

In the upload service, when uploading image, thumbnail, and responsive formats one by one, upload them all together.
As an example, when using cloudinary: 7s before 3s now.
Especially, when using nonlocal upload providers, uploading images (and not even heavy ones) was slow. 
Upload any image in this branch and master and compare timings.

Improve media upload performance

---

.github/workflows/nightly.yml
package.json
scripts/pre-publish.sh
yarn.lock

It makes a release at midnight every week day of the current code on the main
For community testing and CD purposes
Need to be merged to be tested in real conditions
- [ ] Add manual release workflow

Automated nightly releases

---

examples/getstarted/src/plugins/mycustomfields/admin/src/components/ColorPicker/ColorPickerInput/index.js

[Custom fields] Remove extraneous prop

---

examples/getstarted/src/plugins/mycustomfields/admin/src/index.js

Removes the "map" custom field
Confirm color is the only custom field in the ctb

[Custom fields] remove map cf

---

packages/core/strapi/lib/middlewares/body.js
packages/core/strapi/lib/middlewares/security.js

Loading a plugin should always verify its presence

---

examples/getstarted/src/plugins/mycustomfields/admin/src/components/Map/MapInput/index.js
examples/getstarted/src/plugins/mycustomfields/server/register.js

Removes the map components and the server registration

[Custom fields] Remove all traces of map custom field

---

packages/core/helper-plugin/lib/src/components/RelationInput/RelationInput.js
packages/core/helper-plugin/lib/src/components/RelationInput/RelationInput.stories.mdx
packages/core/helper-plugin/lib/src/components/RelationInput/components/Option.js
packages/core/helper-plugin/lib/src/components/RelationInput/components/tests/Option.test.js

Update `ReactQuerySearchResult` and `ReactQueryRelationResult` proptypes

[RelationInput] Proptypes update

---

packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationSingle/index.js
packages/core/admin/admin/src/content-manager/components/SelectOne/SingleValue.js
packages/core/admin/admin/src/content-manager/components/SelectWrapper/Option.js

READ DESCRIPTION OF ISSUE #13399
Fixes #13399
when the realtion value is interger it breaks ui because it returns a 0 which is a false in || operator in javascript so now i have use ?? to give a fallback string if data is null or undefined
[DEMO](https://www.loom.com/share/701e58d877494911bc135716948c55b8)

0 values are not handled correctly in relations

---

packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/index.test.js

Fixes a couple of errors happening, because a component is rendered into `document.body` directly.
Less test errors.

CM: Fix test errors in ListSettingsView

---

.github/workflows/nightly.yml

Run nightlies only on our repo

---

README.md
packages/core/strapi/README.md

- Updates the minimum and recommended database versions in our readme
- Mirrors main readme file to the @strapi/strapi package one (they were out of sync)

Update minimum and recommended database versions

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ActionBoundRoutes/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/reducer.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/__snapshots__/index.test.js.snap
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/utils/transformPermissionsData.js

Displays the routes for every specific action on API token settings
After clicking on the cog, the specific route of an action should appear

Api token v2 show action routes

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ActionBoundRoutes/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/CollapsableContentType/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ContenTypesSection/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/utils/tests/transformPermissionsData.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/utils/transformPermissionsData.js

- Applies some small changes regarding some property names
- removes console.log
- fixes some warnings related to the absence of a key prop
no behavior changes should be present

small fixes and changes

---

packages/core/admin/admin/src/translations/es.json

Fixes #14205.
The translation for `global.users` was wrong.

Fix global.users translation for ES

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationList.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationItem.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationList.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap

- Improve shadows by implementing native scroll event on `react-window`
- Added tests coverage for load more display logic
- Improve list markup

[RelationInput] Native scroll

---

packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/normalizeRelations.js

RelationInputWrapper: Pass down relation pages in reverse order

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/tests/index.test.js
packages/core/admin/admin/src/translations/en.json
packages/core/admin/server/tests/admin-permission.test.e2e.js

User Story description
💬 User story 
As an admin user managing API tokens, I want the alert message “Name already assigned to another token” to be shown when I’m trying to assign to a token a name already assigned to another token, so that I can have a better understanding of the reason why a token is not saved. 
📍 Context 
At the moment, when the admin user try to save a token with a name already assigned to another token a general message of error is displayed. 
☑️ Acceptance criteria 
- As an admin user 
- when I save a token with a name already assigned to another token 
- then I want the alert box to be displayed with the message “Name already assigned to another token”

Manage tokens having the same name

---

packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js

When opening the search for the first time, no result would appear
Fix:
Fire search on open
Open an entity with a relation
Focus on the select
See entities results displayed

[Relations] Search on open

---

packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js

Move connect and disconnect creation in `EditViewDataManagerProvider` reducer from `LOAD_RELATION` to `CONNECT_RELATION`/`DISCONNECT_RELATION`

[Relations] Move connect/disconnect

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
CONTRIBUTING.md
README.md
packages/core/strapi/README.md

Update node 18 support infos in READMEs

Update readme with node 18 support

---

packages/core/upload/package.json

Update to the latest version of sharp in upload plugin.
Some png images I wanted to upload failed because of this issue in sharp: https://github.com/lovell/sharp/issues/3225 With version 0.31.0, it is fixed, so would be awesome if we could upgrade Strapi upload to this version.
-
-

update sharp in upload package

---

packages/core/admin/admin/src/content-manager/components/Inputs/index.js
packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/Relation.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
packages/core/admin/admin/src/content-manager/pages/EditView/index.js
packages/core/helper-plugin/lib/src/components/ReactSelect/ReactSelect.js
packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js

Fix:
- Fix bottom padding 
- Under 50% (configure the view) Select should be 100%
- Select popover stuck on scroll 
- Load more wrap below on small size screen
- Ellipsis on Select placeholder

[RelationInput] UI fixes

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/Relation.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationList.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationList.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap

Fix proptypes issues (`size`, `totalNumberOfRelations`)
Fix loadingMessage log error (`Warning: Functions are not valid as a React child`)

[RelationInput] fix proptypes

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/Relation.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js

Removes the padding and background-color from `RelationInput` as discussed.
To enhance the visual alignment.

RelationInput: Remove background color and padding 

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap

Added a tooltip for Relation link/title

[RelationInput] Tooltip Relation mainField

---

packages/plugins/users-permissions/server/services/permission.js

Fix wrong filter param used with the entityService in UP

---

packages/core/content-manager/server/controllers/relations.js
packages/core/content-manager/server/tests/index.test.e2e.js
packages/core/database/lib/entity-manager/index.js
packages/core/database/lib/entity-manager/regular-relations.js
packages/core/database/lib/entity-manager/utils.js
packages/core/database/lib/metadata/index.js
packages/core/database/lib/metadata/relations.js
packages/core/database/lib/query/query-builder.js
packages/core/strapi/lib/services/entity-service/components.js
packages/plugins/i18n/tests/content-manager/find-existing-relations.test.e2e.js

First base to allow partial update and reordering of relations

add first base for reordering

---

.github/workflows/checks.yml

update `actions/checkout` to `v3` in `checks.yml`
To be up to date with the latest version of this GitHub Action. It's interesting to get the latest security patches and features.
This PR is already using these changes.
No

ci(checks.yml): update actions/checkout to v3

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
packages/core/admin/package.json
packages/core/helper-plugin/package.json
packages/plugins/color-picker/admin/src/components/tests/color-picker-input.test.js
packages/plugins/color-picker/jest.config.front.js
yarn.lock

* updates design-system to latest version
There are two significant fixes in the latest version of the DS
* Table keyboard navigation (especially with input fields)
* Popover placements & rendering
For the full changelog see – https://github.com/strapi/design-system/releases/tag/v1.2.5

chore: update to latest version of design-system

---

packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js

Fix conditions for idsToInclude sending false as param

[Relations] Fix idsToInclude false

---

packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationItem.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationList.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap

[CONTENT-552](https://strapi-inc.atlassian.net/browse/CONTENT-552)
Update padding top and bottom of `RelationItem` to be `8px` instead of `12px`

[Relations] Fix RelationItem padding

---

packages/core/database/lib/entity-manager/index.js
packages/core/database/lib/entity-manager/morph-relations.js
packages/core/database/lib/entity-manager/regular-relations.js
packages/core/strapi/lib/services/entity-service/components.js

Add transaction for `create`, `update` and `delete` function in database entity manager.
To reduce risks of database inconsistency

Add transaction in DB entity manager

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/components/LogoInput/tests/index.test.js

Fixed broken asset used in `LogoInput` tests for `From URL` form

[Fix] LogoInput tests

---

packages/core/database/lib/entity-manager/index.js
packages/core/database/lib/entity-manager/relations/morph-any-to-many.js
packages/core/database/lib/entity-manager/relations/morph-relations.js
packages/core/database/lib/entity-manager/relations/regular-relations.js
packages/core/database/lib/entity-manager/relations/utils.js

Move morph relation logic to new files

move any to many morph relationship to new files

---

packages/core/strapi/package.json

See #14675
See #14675
fix #14675

Fix breaking change introduced by koa/cors patch version bump

---

packages/core/content-manager/server/tests/api/relations.test.e2e.js
packages/core/database/lib/entity-manager/index.js
packages/core/database/lib/entity-manager/regular-relations.js
packages/core/strapi/tests/api/relations.test.e2e.js

Tests the new relational fields edit format.
To ensure there are no regressions
Checks if it's green :)
None

Add content api tests for connect relation format

---

packages/core/upload/admin/src/components/AssetDialog/tests/AssetDialog.test.js
packages/core/upload/admin/src/components/EditFolderDialog/tests/EditFolderDialog.test.js
packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
packages/core/upload/admin/src/constants.js
packages/core/upload/admin/src/hooks/__mocks__/useFolders.js

Found more prop-type errors 👋🏼 and fixed them.
No prop-type errors in tests anymore.

ML: Fix folder prop-types

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/normalizeSearchResults.js
packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/select.js
packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js

* Gracefully fails if there are no search results
* Fixes the `entityId` chaos
* Apps shouldn't "just break"

fix: gracefully fail 404 results from API

---

packages/core/data-transfer/lib/engine/index.ts
packages/core/data-transfer/types/providers.d.ts

- refactor typings
- remove console.log

[DEITS] refactor export schemas

---

packages/plugins/users-permissions/server/controllers/validation/user.js

Fix edit problem on users & permission introduced in 4.5.0

Fix validation on user update

---

packages/core/upload/admin/src/components/AssetCard/tests/AssetCardBase.test.js

Fixes tests for `AssetCardBase`.
Unblocks other PRs. I think this needs a follow-up, because these tests don't make a lot of sense to me. 
- Tests became flaky with https://github.com/strapi/strapi/pull/14861

Chore: Fix AssetCardBase tests

---

packages/core/content-manager/server/tests/api/basic-dp-dz.test.api.js
packages/core/content-manager/server/tests/api/basic-dz.test.api.js
packages/core/strapi/lib/services/entity-service/__tests__/entity-service-events.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/index.test.js
packages/core/strapi/lib/services/entity-validator/index.js
packages/core/strapi/tests/api/basic-dz.test.api.js

Fixed failing API tests by throwing a relevant error message when `uid` is undefined in `buildRelationsStore`

Fix failing API tests

---

.github/actions/install-modules/action.yml
.github/actions/install-modules/script.sh
.github/workflows/tests.yml
test/api.js

Fix flaky / false positive tests due to process.exit timing errors

---

.github/workflows/skipped_tests.yml

Adds a skip workflow like proposed in github's doc. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
This isn't an ideal solution but we will start with this for now to avoid blocking PRs
Doc PRs are current not mergeable because required checks are not executing but github actions still expect them.
We can maybe test it with act. 
Once merged in main we can make doc PR and see if this fixes all the required checks or not.

Add skipped test workflow to avoid required check issues on docs PRs

---

packages/core/upload/admin/src/components/TableList/TableRows.js
packages/core/upload/admin/src/components/TableList/tests/TableList.test.js
packages/core/upload/admin/src/components/TableList/tests/TableRows.test.js
packages/core/upload/admin/src/translations/en.json

click on each rows to test the navigation
using keyboard to navigate through button/link will be fixed by this DS [PR](https://github.com/strapi/design-system/pull/784)

[features][ML listview] Row navigation

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
packages/core/upload/admin/src/components/FolderGridList/FolderGridList.js
packages/core/upload/admin/src/components/FolderGridList/index.js
packages/core/upload/admin/src/components/FolderGridList/tests/FolderGridList.test.js
packages/core/upload/admin/src/components/FolderGridList/tests/__snapshots__/FolderGridList.test.js.snap
packages/core/upload/admin/src/components/FolderList/index.js
packages/core/upload/admin/src/pages/App/MediaLibrary.js

Renames folderlist to foldergrid

[upload] rename folderlist to foldergrid

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/index.test.js
packages/core/upload/admin/src/components/EditFolderDialog/tests/EditFolderDialog.test.js
packages/core/upload/admin/src/pages/App/tests/MediaLibrary.test.js

Adds test coverage on `MediaLibrary`, `BrowseStep` and `EditFolderDialog`

[features][ML listview] Extend tests coverage

---

packages/core/content-manager/server/tests/api/basic-dp-dz.test.api.js
packages/core/content-manager/server/tests/api/basic-dz.test.api.js
packages/core/strapi/lib/services/entity-validator/index.js
packages/core/strapi/tests/api/basic-dz.test.api.js

Improves error messaging in the entity-validator as per  - https://github.com/strapi/strapi/pull/14948#discussion_r1028014544

[entity-validator] Improve error messaging

---

packages/core/data-transfer/lib/providers/local-file-destination-provider/index.ts
packages/core/data-transfer/lib/providers/local-file-source-provider.ts
packages/core/data-transfer/lib/providers/local-strapi-destination-provider/index.ts
packages/core/strapi/bin/strapi.js
packages/core/strapi/lib/commands/transfer/import.js

Automatically detect export file format based on its extensions and provides the right arguments to the local source file provider

[DEITS] Update the local file source provider's logic to decompress/decrypt content

---

docs/docs/core/content-manager/hooks/use-drag-and-drop.mdx
docs/sidebars.js
packages/core/admin/admin/src/content-manager/hooks/useKeyboardDragAndDrop.js

* Adds documentation for the universal hook `useDragAndDrop`

Add useDragAndDrop hook documentation

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/components/Form/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js

Update `trackUsage` events with a payload to reflect which logo was reset or changed
See **CONTENT-778**

[features][authLogo] Update tracking events

---

packages/core/admin/admin/src/content-manager/components/DragLayer/RelationDragPreview.js
packages/core/admin/admin/src/content-manager/components/DragLayer/index.js
packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/RelationItem.test.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/RelationList.test.js
packages/core/admin/admin/src/content-manager/components/RepeatableComponent/components/Component.js
packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.js
packages/core/admin/admin/src/content-manager/utils/ItemTypes.js

* Appends the item type with the name of the field so you can't drag field items into other fields
* Adds RelationItem drag preview to avoid cut-offs
* Fixes issue with scrolling where if you remove an item it would scroll somewhere (it shouldn't have)
* resolves CONTENT-783
* resolves CONTENT-784
* resolves CONTENT-788

[RelationsReordering]: fixes

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
packages/core/email/admin/src/pages/Settings/index.js
packages/core/email/server/bootstrap.js
packages/core/email/server/controllers/email.js

Replace some lodash util to use native code instead
Make less use of lodash

replace some lodash function with native

---

packages/core/admin/admin/src/pages/SettingsPage/pages/AuditLogs/ListView/ModalDialog/index.js

- Added a missing border radius to modal content grid.
Settings > ADMINISTRATION PANEL > Audit Logs

[core: admin] Audit logs modal css change

---

packages/core/email/server/bootstrap.js

in #14996 an attempt to lower case on email provider could throw an unclear error
fixed with conditional access

[Fix] email provider access 

---

packages/core/admin/ee/server/services/audit-logs.js
packages/core/content-type-builder/server/services/components.js
packages/core/content-type-builder/server/services/content-types.js

Emit create, update, delete events in the CTB for content types and components
Modify content types and components in the CTB, see the logged actions

[Audit logs] Emit events for content types and components

---

packages/core/data-transfer/lib/providers/local-strapi-destination-provider/strategies/restore/entities.ts
packages/core/data-transfer/package.json

- Fix repeatable data structures ID mapping on import (repeatable components, dynamic zones)
- ID mapping on data import is broken

Fix repeatable data structures ID mapping on import

---

packages/core/admin/server/services/user.js
packages/core/strapi/lib/services/event-hub.js

- Make a small optimization in the new event hub, [as recommended by Mark](https://github.com/strapi/strapi/pull/15128#discussion_r1047829785)
- Wrap all user events payload for consistency and to make room for new keys in the future

[Audit logs] Small refinements

---

packages/core/data-transfer/lib/providers/remote-strapi-destination-provider/index.ts
packages/core/data-transfer/lib/register.ts
packages/core/data-transfer/types/remote.d.ts

fixes error in transfer command by changing `options` to `data` in the expected init message

[DEITS] Fix transfer push

---

packages/core/data-transfer/lib/providers/local-strapi-destination-provider/strategies/restore/entities.ts

fixes lint error on `features/deits`
Lint check doesn't pass
Lint check should pass

[DEITS] fix lint error

---

docs/docs/core/hooks/use-fetch-client.mdx
docs/sidebars.js

Describes how to use and what it does the useFetchClient hook.
To let others know how to use the useFetchClient hook. 
No need to test this

Document the useFetchClient hook

---

docs/docs/core/content-manager/hooks/use-callback-ref.mdx
docs/sidebars.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/cleanData.test.js

* Adds docs for `useCallbackRef` a new hook in the CM
* Adds `strict:false` to relation API posting
* Docs make people happy
* the false flag avoids reversing the array
* automated testing
* resolves CONTENT-864

[Relations]: add `strict: false` to API post

---

docs/docs/testing/e2e/app-template.md
docs/docs/testing/e2e/data-transfer.md
docs/docs/testing/e2e/setup.md
docs/sidebars.js

* Adds some docs about the e2e setup as is today
* Docs are good for you

[docs]: add docs for e2e

---

docs/docs/core/admin/link-strapi-design-system.md

Fixes an incorrect location for a command

Fix incorrect location for command

---

packages/core/admin/admin/src/content-manager/components/DragLayer/RelationDragPreview.js

* Use a box to contain the ellipse
* Long names shouldn't break the UI drag layer
* resolves CONTENT-938

fix: use box to contain ellipse

---

packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/index.js

* reverse the results from the relation query in DynamicTable
* So relations are in the same order as the EditView
* resolves CONTENT-934

[DynamicTable]: reverse data from BE to show relations in same order

---

packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationList.js
packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/__snapshots__/RelationList.test.js.snap
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap

* Uses updated shadow color provided by design
* changes CSS so it changes opacity to give _fading_ change
* so the shadow is visible in Light and Dark mode
* Block changes look bad and make users cry.
* resolves CONTENT-937

[RelationsList]: add shadow & fade for shadow not being needed

---

packages/core/admin/admin/src/hooks/useSettingsMenu/init.js

Sort audit logs by newest by default

[Audit logs] Sort by newest by default

---

packages/core/admin/admin/src/content-manager/pages/EditView/Information/index.js

* uses `dl/dd/dt` with divs according to spec - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_div_elements
* semantics
* relates to #15443

[Information]: styling with semantics

---

packages/core/admin/admin/src/pages/SettingsPage/pages/AuditLogs/ListView/Modal/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/AuditLogs/ListView/index.js

Manages the opened log ID in the URL query params, instead of doing it with React state
Click on a log, refresh, etc

[Audit logs] Manage opened log in URL params

---

packages/core/data-transfer/package.json
packages/core/strapi/lib/commands/transfer/export.js
packages/core/strapi/lib/commands/transfer/import.js
packages/core/strapi/lib/commands/transfer/transfer.js
packages/core/strapi/lib/commands/transfer/utils.js

- Prevent errors being logged two times
- Remove the stack trace from the logs

[DEITS] Fix diagnostic error format

---

packages/core/strapi/lib/commands/transfer/utils.js

Update and sync the help text with the documentation
[Let us know if this is related to any issue/pull request](https://github.com/strapi/documentation/pull/1450)

[DEITS] fix help text

---

docs/docs/core/helper-plugin/hooks/use-fetch-client.mdx
docs/sidebars.js

* reorganise so it's in alphabetical order
* move the fetch-client stuff into a helper-plugin folder because that's where it lives.
* Clear and good docs are important.

chore: tidy-up contributor docs

---

.github/actions/run-api-tests/script.sh
e2e/app-template/template/src/api/config/controllers/config.js
e2e/app-template/template/src/api/config/routes/config.js
e2e/app-template/template/src/api/config/services/config.js
e2e/app-template/template/src/index.js
package.json
test/helpers/test-app.js
test/scripts/create-test-app.js

- Add route to change rate limit
- Set rate limit to false by default
- Set autoOpen to false by default
- Fix test setup for API tests

Add route to change rate limit + set default config

---

.github/workflows/issues_handleLabel.yml

Just adding the new DEITS label to the automation
N/A
N/A
N/A

Update auto-label workflow to include DEITS label

---

packages/core/content-manager/server/services/entity-manager.js
packages/core/upload/server/register.js
packages/core/upload/server/services/extensions/content-manager/entity-manager.js

Refactor the way that entity manager functions are extended in the upload plugin
Code readability and simplicity
JIRA - CONTENT-797

Refactor entity manager extensions

---

packages/core/content-manager/server/services/entity-manager.js
packages/core/upload/server/controllers/admin-file.js
packages/core/upload/server/register.js
packages/core/upload/server/services/extensions/content-manager/entity-manager.js
packages/core/upload/server/services/file.js

make signing file urls non mutating

feature: S3 Bucket, make file signing non mutating

---

packages/core/admin/admin/src/pages/SettingsPage/pages/Users/components/MagicLink/MagicLinkWrapper.js

* Just use a span instead of an SVG (literally no point for this)
* Windows has a problem with how that SVG is written
* You'll need windows....
* resolves #13259

[Settings]: fix mail icon on windows

---

packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
packages/core/data-transfer/src/strapi/providers/remote-destination/utils.ts
packages/core/data-transfer/src/strapi/remote/flows/default.ts
packages/core/data-transfer/src/strapi/remote/flows/index.ts
packages/core/data-transfer/src/strapi/remote/handlers.ts
packages/core/data-transfer/types/remote/protocol/server/messaging.d.ts

- Implement a transfer flow protocol to restrict what operation can be run by connected clients. 
- Prevent inconsistent states due to missing commands or messages

[DTS] - Remote transfer flow

---

docs/docs/testing/e2e/app-template.md
docs/docs/testing/e2e/data-transfer.md
e2e/authentication/login.spec.js
e2e/authentication/logout.spec.js
e2e/authentication/signup.spec.js
e2e/scripts/dts-import.js

Improve the e2e testing docs to reflect the latest changes

[Docs] Improve e2e testing documentation

---

packages/core/strapi/lib/commands/builders/admin.js

Revert "Call process.exit after successful build"

---

packages/plugins/i18n/server/services/localizations.js

For each async is not working apparently, the methods are not being executed and we missed this during the impleemtnation of this util.

[Fix]: forEach async

---

packages/core/upload/server/services/extensions/content-manager/__tests__/entity-manager.test.js
packages/core/upload/server/services/extensions/content-manager/entity-manager.js

Adds unit tests for the entity manager file signing extension in the upload plugin

test(upload): entity manager file signing extension

---

packages/core/admin/server/middlewares/data-transfer.js
packages/core/admin/server/middlewares/index.js
packages/core/admin/server/routes/transfer.js
packages/core/admin/server/services/transfer/index.js
packages/core/admin/server/services/transfer/token.js
packages/core/admin/server/services/transfer/utils.js

- Disable data transfer feature on manually set variable or missing token salt

[Data Transfer]: Add data transfer checks to disable related features (transfer, tokens)

---

packages/providers/upload-aws-s3/README.md

Improve docs explaining how to configure s3 provider for a s3 bucket.

[Private S3]: Improve docs

---

packages/core/admin/ee/admin/hooks/useLicenseLimitNotification/index.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/ListPage/CreateAction/index.js
packages/core/admin/ee/server/controllers/admin.js
packages/core/admin/ee/server/controllers/user.js
packages/core/admin/ee/server/services/seat-enforcement.js

Fix license seat undefined blocking user creation
If the license doesn't contain seat info it should block the invite user button in the ui 
- ask for a test license 

Fix license seat undefined blocking user creation

---

packages/core/utils/lib/content-types.js

This is a split of https://github.com/strapi/strapi/pull/15839 . Just in case, if the conversation is extended, we have part of the enhancement merged for the next release.
This part of the code actually increases the performance (for big payloads) by 10% or more. 
Improve API performance.
You will need a project with entites that have many relations and fields, make findMany request in the api populating with '*'
Then see the api response differnce.

[enhancement]: Improve remove password sanitization performance

---

packages/core/upload/tests/admin/private-file-signing.test.api.js

[Test] - API private url signing

---

packages/core/admin/server/controllers/api-token.js
packages/core/admin/server/controllers/transfer/runner.js
packages/core/admin/server/services/__tests__/api-token.test.js
packages/core/admin/server/services/__tests__/transfer/token.test.js
packages/core/admin/server/strategies/__tests__/api-token.test.js
packages/core/admin/server/strategies/data-transfer.js
packages/core/data-transfer/src/engine/index.ts
packages/core/email/server/services/email.js
packages/core/strapi/lib/commands/__tests__/data-transfer/export.test.js
packages/core/strapi/lib/commands/__tests__/data-transfer/import.test.js
packages/core/strapi/lib/commands/__tests__/data-transfer/transfer.test.js
packages/core/strapi/lib/commands/transfer/export.js
packages/core/strapi/lib/commands/transfer/import.js
packages/core/strapi/lib/commands/transfer/transfer.js
packages/core/strapi/lib/commands/transfer/utils.js
packages/core/strapi/lib/services/entity-validator/__tests__/biginteger-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/date-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/datetime-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/email-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/enumeration-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/float-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/integer-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/string-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/time-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/timestamp-validators.test.js
packages/core/strapi/lib/services/entity-validator/__tests__/uid-validators.test.js

Fix usage of requires with internal package paths

Fix invalid require using internal paths

---

docs/docs/core/helper-plugin/hooks/use-fetch-client.mdx

Describe the format of the requestURL to use in the useFetchClient hook.
To prevent issues similar to one that already a user had.
Just open the documentation
The issue related to it is https://github.com/strapi/strapi/issues/15844

Prevent url issues in the useFetchClient

---

packages/core/admin/admin/src/content-manager/components/NonRepeatableComponent/index.js
packages/core/admin/admin/src/content-manager/pages/EditView/Header/index.js
packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/GlobalActions/index.js

* fixes some CSS issues
* Bad css
* identified in #16010

Replace spacing with gap

---

packages/core/admin/ee/server/services/review-workflows/review-workflows.js
packages/core/admin/ee/server/tests/review-workflows.test.api.js

Refactors a raw SQL query to use Knex

refactor(review-workflows): use knex for raw sql query

---

.github/workflows/issues_handleLabel.yml

Just adding @Eventyret to the support team automation
New member of the team :)
N/A
N/A

Add Eventyret to support team automation

---

packages/core/data-transfer/src/strapi/providers/remote-source/index.ts

Fix typos when logging errors

---

packages/core/admin/server/tests/admin-transfer-token-crud.test.api.js

fixes a test that randomly fails from array order

[Data transfer] fix test

---

examples/getstarted/src/plugins/myplugin/server/routes.js
examples/getstarted/src/plugins/myplugin/strapi-server.js
packages/core/strapi/lib/core/loaders/plugins/index.js
packages/core/strapi/lib/factories.js
packages/core/strapi/lib/services/server/register-routes.js

Fix core router not working within plugin context
Fix https://github.com/strapi/strapi/issues/14438

Fix core router not working within plugin context

---

packages/utils/logger/package.json

* changes types export to be `.d.ts`
* types we're not found

Fix types export in `@strapi/logger`

---

packages/core/admin/ee/server/services/review-workflows/review-workflows.js

Use correct DB connection for postgres

---

packages/core/admin/ee/server/services/__tests__/stages.test.js
packages/core/admin/ee/server/services/review-workflows/stages.js

Accounts for new stages when finding the nearest stage to move entities to
This covers cases where you add a new stage but delete all existing stages in one operation from the RW settings page
Updated unit test
CONTENT 1252

Account for new stages when finding target stage ID

---

packages/core/content-manager/server/controllers/collection-types.js

Change prohibited Fields error message

fix: prohibited fields error message

---

vercel.json

Remove the forced overrides from vercel so that it can also be used for the contributor docs
Trying to setup vercel for the contrib docs
N/A
N/A

Remove overrides from Vercel

---

api-tests/core/admin/ee/review-workflows.test.api.js
packages/core/admin/ee/server/validation/review-workflows.js

Limit number of stages to 200.

feat (RW): limit number of stages to 200

---

api-tests/core/admin/ee/review-workflows.test.api.js

fix(RW): flaky test

---

packages/core/content-manager/server/services/__tests__/field-sizes.test.js

Remove console log from test suite
console pollution
N/A
log added in #16455

Remove log from tests

---

api-tests/core/strapi/api/basic-compo-repeatable.test.api.js
packages/core/strapi/lib/core-api/controller/collection-type.js
packages/core/strapi/lib/core-api/controller/index.js
packages/core/utils/lib/traverse/query-populate.js

Fix it 
Derrick wanted it
Run the tests
#16530

Sanitize input query for all core controllers

---

packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js

Adds a button to delete a workflow, if it is not the last one. It shows a confirmation dialog.
Will allow admins to delete workflows.

Settings: Implement workflow deletion in list-view

---

packages/core/admin/ee/server/controllers/workflows/index.js

Adds sort attribute to GET /workflows

feat(rw): sort on workflow list

---

api-tests/core/admin/ee/review-workflows-content-types.test.api.js
api-tests/core/admin/ee/review-workflows.test.api.js
packages/core/admin/ee/server/controllers/workflows/index.js

feature(rw): Update contract for POST PUT workflows body

---

packages/core/upload/server/controllers/utils/folders.js
packages/core/upload/server/controllers/validation/admin/folder-file.js
packages/core/upload/server/controllers/validation/admin/folder.js

Very similar to https://github.com/strapi/strapi/issues/16734, folder path match was not done correctly.
Fixes https://github.com/strapi/strapi/issues/16738

fix: Some folders can't be moved inside others

---

.github/workflows/remove-dist-tag.yml

* adds file extension to calling of bash script
* action fails otherwise

chore: add file extension to remove-dist-tag workflow

---

packages/core/admin/admin/src/hooks/useContentTypes/useContentTypes.js

Removes a leftover debug message.
💅🏼

Chore: Remove stray console log

---

packages/core/content-manager/server/services/__tests__/entity-manager.test.js
packages/core/content-manager/server/services/entity-manager.js

Fixes the filters in the bulk publish / unpublish endpoints 
Currently the filters don't work saw all entities are returned and emitted as publish / unpublish events
- Clear your audit logs 
- Go to any content type in the CM
- Create several draft entries
- Publish one of them using bulk publish
- Check audit logs, you should see only 1 audit log for publish
- Go back to your content-type and select your published entry and another draft, then bulk publish
- Back in your audit logs you should see only 1 new log for the published entry (you should not see a log for the entry that was already published)
- Go back to the CM and select both your published entries, unpublish them
- Back in audit log you should see two new audit logs for unpublish

Fix filters causing too many emitted events

---

packages/core/helper-plugin/src/components/FilterPopoverURLQuery/Inputs.js
packages/core/helper-plugin/src/components/GenericInput/index.js
packages/core/upload/admin/src/components/FilterPopover/FilterValueInput.js

* DTP should not pass an empty string
* DTP expects Dates or undefined/null not strings

fix: dtp value should not pass empty string

---

packages/core/admin/admin/src/content-manager/pages/EditView/index.js
packages/core/content-manager/server/controllers/collection-types.js

* Updates error message
* increases error message timeout
* Blitz feedback
* resolves CONTENT-1280
* resolves CONTENT-1474

fix: error message improvements

---

packages/core/admin/admin/src/hooks/useSettingsForm/index.js
packages/core/admin/admin/src/hooks/useSettingsForm/tests/index.test.js
packages/core/admin/admin/src/pages/ProfilePage/components/Preferences/index.js
packages/core/admin/admin/src/pages/ProfilePage/components/UserInfo/index.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/SingleSignOn/utils/schema.js
packages/core/admin/ee/server/validation/authentication.js

Some pieces of code were not styled properly

chore: fix code styling

---

packages/core/admin/ee/server/constants/webhookEvents.js
packages/core/admin/ee/server/services/review-workflows/__tests__/entity-service-decorator.test.js
packages/core/admin/ee/server/services/review-workflows/entity-service-decorator.js
packages/core/admin/ee/server/services/review-workflows/review-workflows.js

Emit review workflow stage change webhook events from the EE entity service decorator
Users can now define webhooks for 'Review workflow stage changes'
CONTENT-1135

Emit workflow stage change webhook event

---

packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/index.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/SingleSignOn/index.js

Fixes rendering bugs for audit-logs and SSO.
Fixes rendering bugs.
- Similar to https://github.com/strapi/strapi/pull/17078
- Broke in https://github.com/strapi/strapi/pull/17035

Fix: Rendering loops for audit-logs and SSO settings pages

---

packages/core/admin/ee/server/controllers/workflows/stages/index.js
packages/core/admin/ee/server/services/passport.js
packages/core/admin/server/services/permission/permissions-manager/sanitize.js

Fix unwanted imports
We should almost never import sub path of packages. This creates unwanted tight coupling.

Fix unwanted imports

---

packages/core/admin/admin/src/pages/ProfilePage/index.js

- Used `dirty` property of Formik to disable the `Save` button if there's no change in form data.
This will improve user experience & also reduces the unnecessary api calls to update profile.
**Before:**
https://github.com/strapi/strapi/assets/40918526/c9d190a5-3e22-414d-967a-1180cd8d7c5c
**Now:**
https://github.com/strapi/strapi/assets/40918526/d26390ab-2e02-4e73-91c7-3bcd6dcbc265
You can login to admin & go to profile section and see the change.
There's not related issue with this PR.

[ADMIN] Prevent unnecessary api calls on profile save

---

packages/core/admin/ee/server/services/review-workflows/__tests__/entity-service-decorator.test.js
packages/core/admin/ee/server/services/review-workflows/entity-service-decorator.js

Adds data to and changes the structure of the payload sent with the review workflow stage change webhook events
Modified tests
By moving content between review stages and inspecting webhook payload
CONTENT-1525
CONTENT-1527

Correct payload structure for review workflows stage change webhook

---

packages/core/helper-plugin/src/components/FilterPopoverURLQuery/Inputs.js
packages/core/helper-plugin/src/components/GenericInput/index.js

* checks if there's a value and returns a `Date` if so 
* is inline with the `DateTimePicker`

fix: remove parseISO and just use native Date instead

---

docs/docs/docs/01-core/utils/async.md

Add examples of async utility functions.

doc: examples of async utils

---

packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js

Very similar bug as [#17102](https://github.com/strapi/strapi/pull/17102) 
Fix bug
You can login to admin and test. easy to reproduce.
No related issue for this.

[ADMIN] fix bug on saving user details

---

packages/core/admin/ee/server/controllers/admin.js

Adding the features array as an array in the `/license-limit-information` route response.
Being able to get the activated featured and appropriate options for them.
GET /license-limit-information with a valid EE licence, you should see an array of features.

feat(admin): add features informations inside the license limit route

---

packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewLocalePicker/index.js

* correctly spells `gap`
* looked bad
* resolves #16379
* resolves CONTENT-1298

fix: i18n CM EditView locale selector flex gap

---

packages/core/admin/ee/admin/hooks/useLicenseLimits/tests/index.test.js

Closes the msw server properly after running the testsuite.
Forgot to close down the server in https://github.com/strapi/strapi/pull/17050

Fix: Close msw server properly after running the testsuite

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
packages/core/upload/admin/src/components/AssetDialog/index.js
packages/core/upload/admin/src/components/Breadcrumbs/Breadcrumbs.js
packages/core/upload/admin/src/components/Breadcrumbs/CrumbSimpleMenuAsync.js
packages/core/upload/admin/src/hooks/tests/useModalQueryParams.test.js
packages/core/upload/admin/src/hooks/useModalQueryParams.js
packages/core/upload/admin/src/utils/getBreadcrumbDataCM.js
packages/core/upload/admin/src/utils/tests/getBreadcrumbDataCM.test.js

* pass the folder path through the CM media-input component
* We changed the query to `folderPath` because it is indexed in the DB #17154
* go to CM EditView
* add a media item
* The folders should show the files in said folder only
* resolves CONTENT-1561
* resolves #17211

fix: CM media-input browsing

---

packages/core/admin/admin/src/hooks/useSettingsMenu/index.js
packages/core/admin/admin/src/pages/SettingsPage/components/SettingsNav/index.js

…
It fixes the bug The settings menu displays items that the user does not have permission to #17179
Because it was needed.

Fix settings menu permissions in CE

---

docs/docs/docs/01-core/admin/01-ee/01-review-workflows.md

Adding information specific to multiple workflows in the contributor documentation.

docs(review-workflows): update contrib doc with multiple workflows info

---

packages/core/strapi/lib/services/server/index.js

Fixes #15267
I believe we didn't have each API in the main router before so we had to do this but that's not the case anymore 

Return routes once only

---

api-tests/core/content-manager/index.test.api.js
packages/core/strapi/lib/services/entity-service/index.js

Fixes #16629
to fix an issue 
Follow the reproduction steps from the initial issue

Fix bulkDelete not found should return a count of 0

---

packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/tests/validateWorkflow.test.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/validateWorkflow.js

Modified the yup schema of the Review workflows settings page to ensure that all stages in a workflow have a unique name
Highlights duplicated stage names in the UI
CONTENT-1259

Validate all stages of a workflow have a unique name

---

packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js

Updates the chargebee entitlement names.
To keep up to date with the latest license changes.

Chore: Update review-workflow chargebee entitlements

---

packages/core/utils/src/convert-query-params.ts
packages/core/utils/src/index.ts

Fixes https://github.com/strapi/strapi/issues/17366

Fix Strapi utils with ts migration

---

packages/core/strapi/lib/commands/actions/routes/list/action.js

Fixes https://github.com/strapi/strapi/issues/17390
To fix a bug

Fix command not mounting the routes correctly

---

CONTRIBUTING.md

This PR is related to grammatical error in CONTRIBUTING.md.
No test is required.
PR is ready to be merged.

fixed grammatical error in CONTRIBUTING.md

---

packages/generators/app/src/resources/dot-files/common/env.example

Modify the example environment variable.
Because .env.example and .env are inconsistent
Initialize the project
No.

fix: Update env.example

---

test/helpers/test-app.js
test/scripts/run-e2e-tests.js

fix linking on api integration tests

Fix generate-test-app always linking packages

---

api-tests/core/admin/ee/review-workflows-content-types.test.api.js
docs/docs/docs/00-intro.md
docs/docs/docs/01-core/admin/02-permissions/01-how-they-work.mdx
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/tests/useLazyComponents.test.js
packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/reducer.js
packages/core/content-type-builder/admin/src/components/FormModal/index.js
packages/plugins/users-permissions/documentation/content-api.yaml

Nothing
Fix some typos and switch from British -> US English for words for which we had mixed usage (sorry @joshuaellis I meant to revert those but it was too late and I didn't want to spend more than two minutes on this)
Read it

Fix some spelling and standardiZe regional usages

---

packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/constants.js

Makes the assignee column in the CM list view sortable on `firstname`
CONTENT-1124

Make assignee sortable from the list view

---

packages/core/strapi/lib/types/core/attributes/common.d.ts
packages/core/strapi/lib/types/core/attributes/relation.d.ts

- Modify how the relational attribute's properties were distributed for different kind of relations
- Fix incorrect typings
- Create multiple relational attributes & check the types of each one of them

[TS] Fix Attribute.Relation type definition

---

packages/core/strapi/lib/types/core-api/controller.d.ts

Deletes the unknown generic to fix the controller types.
To have types on the controller handlers.
Create a custom controller and test that the methods contain the right types

Fix controller types

---

packages/generators/app/src/resources/files/js/README.md
packages/generators/app/src/resources/files/ts/README.md

This PR simply updates the README file generated with some new docs links + Strapi Cloud mentioned in the deployment section.
Give more visibility on Strapi Cloud.

Update: README files with new links + Strapi Cloud option

---

packages/core/admin/server/controllers/role.js
packages/core/admin/server/services/__tests__/role.test.js
packages/core/admin/server/services/role.js

Modify the route for retrieving all roles to allow filters
Filtering roles from the FE settings page

feature(feature): filtering on admin roles

---

packages/plugins/i18n/server/constants/iso-locales.json
packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap

Added support for Valencian locale
Solving the support for locale Valencian and Catalan at the same time

added support for Valencian locale

---

packages/core/admin/server/services/permission/permissions-manager/sanitize.js

Fix typo in sanitize

---

packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/AssigneeSelect.js

To avoid the double "success" here

Update assignee select success messaging

---

packages/core/admin/admin/src/content-manager/pages/ListView/index.js
packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/ReviewWorkflowsAssigneeEE.js
packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/tests/ReviewWorkflowsAssignee.test.js

Consistent way to get the user details across the app
CONTENT-1821

Use getDisplayName for CM list view assignee column

---

packages/core/admin/admin/src/StrapiApp.js
packages/core/admin/admin/src/components/Providers/index.js
packages/core/admin/admin/src/pages/Admin/index.js
packages/core/admin/admin/src/pages/SettingsPage/constants.js
packages/core/admin/admin/src/pages/SettingsPage/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js
packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/tests/index.test.js
packages/core/admin/admin/src/pages/SettingsPage/tests/index.test.js
packages/core/admin/admin/src/tests/StrapiApp.test.js
packages/core/admin/admin/src/utils/createRoute.js
packages/core/admin/admin/src/utils/tests/createRoute.test.js
packages/core/admin/ee/admin/pages/SettingsPage/constants.js
packages/core/content-type-builder/admin/src/index.js
packages/core/email/admin/src/index.js
packages/core/helper-plugin/src/features/StrapiApp.jsx
packages/core/helper-plugin/src/index.js
packages/core/upload/admin/src/index.js
packages/plugins/documentation/admin/src/index.js
packages/plugins/i18n/admin/src/index.js
packages/plugins/users-permissions/admin/src/index.js

Reverts strapi/strapi#17685
Step one to revert https://github.com/strapi/strapi/pull/17674

Revert "Fix: Use sync over async components in admin panel APIs"

---

packages/core/helper-plugin/src/features/GuidedTour.tsx

Migrate GuidedTour context provider to TypeScript
Check the types 
https://github.com/strapi/strapi/issues/17690

Migrate GuideTour context to TypeScript

---

packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/StageSelect.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflowsStages.js

Invalidates stage list when the stage is changed
So we always display the correct list of stages

fix(ee): invalidate stages list when stage is changed

---

packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js

- Allow "Apply to all stages" to grow
- Align context menu bottom-end
- Use red for "Delete"
Fixes papercut issues found during design-review in the blitz session.

fix(review-workflows): fix design papercut issues

---

packages/core/helper-plugin/declarations/global.d.ts

* adds a declaration for styled-components to extend the `StrapiTheme` from the design-system
* the styled-components know now what theme values exist and it comes from the design-system so that will detect breaking changes better.
* needs https://github.com/strapi/design-system/pull/1335 to be merged first

feat: add theme declaration in module

---

api-tests/core/admin/ee/review-workflows.test.api.js
api-tests/core/strapi/api/populate/sanitize.test.api.js

Adds an API test to ensure that no private fields are returned from strapi_assignee relations
Run the new API test
CONTENT-1828

Test content API sanitization of assignees on review workflow content types

---

packages/core/strapi/lib/types/core/strapi/index.d.ts

After having some issues with types and digging into the code I found an import typo.
Fixing Types

fix type imports

---

packages/core/helper-plugin/src/hooks/tests/useFetchClient.test.tsx
packages/core/helper-plugin/src/hooks/useFetchClient.ts

Migrate useFetchClient hook  to typescript 
https://github.com/strapi/strapi/issues/17690

[helper-plugin]: useFetchClient hook typescript

---

api-tests/core/admin/ee/review-workflows.test.api.js

- Ensures we a receiving correctly formatted stage information when populated through the content API
- Turns off draft and publish on the content type in this test suite to fix the assignee sanitization test
Test coverage for review workflows in the content API
Run the modified API test in EE mode
CONTENT-1828

Test the correct return format for strapi_stage attribute in the content API

---

packages/core/helper-plugin/src/components/PageSizeURLQuery.tsx
packages/core/helper-plugin/src/components/tests/PageSizeURLQuery.test.tsx

Relates to https://github.com/strapi/strapi/issues/17690

[Helper Plugin] Migrate PageSizeURLQuery to TS

---

packages/core/helper-plugin/src/components/ReactSelect.tsx
packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap

[Helper Plugin] migrate ReactSelect to TypeScript

---

packages/core/helper-plugin/src/components/SearchURLQuery.tsx
packages/core/helper-plugin/src/components/tests/SearchURLQuery.test.tsx
packages/core/helper-plugin/src/features/Tracking.tsx

Migrate SearchURLQuery.js to Typescript
To migrate the codebase to TypeScript
Check the types
https://github.com/strapi/strapi/issues/17690

Migrate SearchURLQuery to TypeScript

---

packages/core/helper-plugin/package.json
packages/core/helper-plugin/src/components/Table.tsx
packages/core/helper-plugin/src/components/tests/Table.test.tsx
yarn.lock

* converts Table to TS
* part of #17690

refactor(helper-plugin): convert Table to TS

---

packages/core/helper-plugin/src/components/GenericInput.tsx
packages/core/helper-plugin/src/content-manager/CMEditViewDataManager.tsx
packages/core/helper-plugin/src/hooks/useFieldHint.tsx
packages/core/helper-plugin/src/hooks/useFocusInputField.ts
packages/core/helper-plugin/src/types.ts

Migrates GenericInput to TypeScript
TS Migration: https://github.com/strapi/strapi/issues/17690

Migrate GenericInput to TypeScript

---

packages/plugins/users-permissions/server/controllers/auth.js

Added the suggested check for blocked users when login via third party providers.
fixes: https://github.com/strapi/strapi/issues/17494

fix: blocked users can still login via provider

---

README.md
packages/core/strapi/README.md

Updating our main GitHub readme with a video , the latest positioning (CMS more than API framework), and features could help boost acquisition.
To clarify Strapi's value proposition and promote Strpai cloud.

Update main readme with gif and latest positioning

---

packages/core/data-transfer/src/commands/export/action.ts
packages/core/data-transfer/src/commands/import/action.ts
packages/core/data-transfer/src/commands/transfer/action.ts
packages/core/data-transfer/src/engine/index.ts
packages/core/data-transfer/types/transfer-engine.d.ts

[ts-strapi] Allow some dts config options to be optional

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeOption/index.js
packages/core/content-type-builder/admin/src/components/AttributeOptions/tests/__snapshots__/index.test.js.snap
packages/core/content-type-builder/admin/src/components/FormModal/index.js
packages/core/content-type-builder/admin/src/translations/en.json

Add a temporary badge and warning to the CTB and CM to inform users of an alpha feature. 
So users know what they are getting themselves in to...
Check the designs against the implementation

Add alpha badge and warning to ctb and cm

---

.github/workflows/tests.yml
package.json
yarn.lock

chore(deps): upgrade playwright to 1.38.1

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

On save additional image block was getting inserted with empty children
try to add 1 or more images in editor and save, it should save without any error.
https://github.com/strapi/strapi/pull/18167

[Blocks Editor] On save with image block getting success with error occurred message

---

docs/docs/docs/05-utils/_category_.json
docs/docs/docs/05-utils/pack-up/00-intro.mdx
docs/docs/docs/05-utils/pack-up/01-commands/00-overview.mdx
docs/docs/docs/05-utils/pack-up/01-commands/01-init.mdx
docs/docs/docs/05-utils/pack-up/01-commands/02-build.mdx
docs/docs/docs/05-utils/pack-up/01-commands/03-check.mdx
docs/docs/docs/05-utils/pack-up/01-commands/04-watch.mdx
docs/docs/docs/05-utils/pack-up/01-commands/_category_.json
docs/docs/docs/05-utils/pack-up/02-config.mdx
docs/docs/docs/05-utils/pack-up/03-templates.mdx
docs/docs/docs/05-utils/pack-up/_category_.json
packages/utils/pack-up/README.md

* adds README
* adds contributor docs
* Good documentation makes people happy
* resolves CONTENT-1905

docs(pack-up): add readme and contributor docs

---

e2e/app-template/package.json

Sets the correct supported engines for the e2e test project
It was wrong

Update e2e test node engines

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/tests/useBlocksStore.test.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js

Fixed enter on empty list
Hitting enter on an empty list(with 0 items) breaking the app.

[Blocks Editor] Fix enter key on empty list

---

.github/dependabot.yml

* fixes the `commit_message` part of `dependabot.yml`
* i did it wrong first time
* mentioned on slack

fix(tooling): dependabot script

---

packages/core/admin/admin/src/hooks/tests/useAdminRoles.test.tsx
packages/core/admin/admin/src/hooks/useAdminRoles.ts
packages/core/admin/admin/src/hooks/useAdminRoles/__mocks__/index.js
packages/core/admin/admin/src/types/adminAPI.ts
packages/core/admin/package.json
packages/core/admin/shared/entities.ts
yarn.lock

Convert `useAdminRoles` to TS.

chore(admin): convert useAdminRoles to TS

---

packages/utils/pack-up/src/node/core/config.ts
packages/utils/pack-up/src/node/tasks/vite/config.ts

* adds an alpha config option for `preserveModules`
* So in scenarios like `@strapi/strapi` we can preserve the file structure and how it works currently
* unblocks #18339 
* unblocks #18341

feat(pack-up): enable preserve modules

---

packages/core/database/package.json
packages/core/database/packup.config.ts
packages/core/database/tsconfig.build.json
packages/core/database/tsconfig.eslint.json
yarn.lock

* pack-up database
* ESM / CJS <3
* part of #18077

chore: pack-up database

---

.github/workflows/tests.yml

Runs lint and typescript at the same time
Decreases the pipe line time by 5 minutes 
see the tests run for this pr

run lint and typescript at the same time

---

packages/utils/pack-up/src/__tests__/node.test.ts

The log uses a relative path that will change depending on where you run the test from (package or root of repo). Making the test regex more flexible fixes this flaky test

Update test regex to allow arbitrary subpaths

---

.github/actions/run-api-tests/action.yml
.github/actions/run-api-tests/script.sh
.github/workflows/tests.yml

shards the db tests into 2 groups
improves CI time
See CI time improve

add jest shards for db tests.

---

packages/core/admin/admin/custom.d.ts
packages/core/admin/admin/src/hooks/tests/useEnterprise.test.ts
packages/core/admin/admin/src/hooks/useEnterprise.ts
packages/core/admin/admin/src/hooks/useEnterprise/index.js

Convert `useEnterprise` to TS.

chore: convert useEnterprise to TS

---

packages/core/admin/server/controllers/__tests__/transfer/token.test.js

Remove accidental console.log in test

---

packages/core/types/index.js
packages/core/types/package.json
packages/core/types/src/types/__tests__/utils/object.test.ts
packages/generators/app/package.json
packages/generators/app/packup.config.ts
packages/generators/app/src/create-project.ts
packages/generators/app/tsconfig.build.json
packages/generators/app/tsconfig.eslint.json
packages/generators/app/tsconfig.json
packages/generators/generators/package.json
packages/generators/generators/packup.config.ts
packages/generators/generators/tsconfig.build.json
packages/generators/generators/tsconfig.eslint.json
packages/generators/generators/tsconfig.json
packages/utils/logger/package.json
packages/utils/logger/packup.config.ts
packages/utils/logger/src/formats/index.ts
packages/utils/logger/tsconfig.build.json
packages/utils/logger/tsconfig.eslint.json
packages/utils/logger/tsconfig.json
test/helpers/test-app.js
yarn.lock

* converts logger to pack-up
* converts generators/generators to pack-up
* converts generators/app to pack-up
* converts core/types to pack-up
* CJS / ESM <3

chore: convert other packages to pack-up

---

packages/core/admin/server/src/services/auth.ts

Completes the conversion on admin auth service to ts

Complete admin/services/auth ts conversion

---

packages/core/admin/package.json
packages/core/admin/server/src/controllers/transfer/runner.ts
packages/core/admin/server/src/services/transfer/token.ts

Fixes some TS build issues in admin

fix(admin): ts build issues

---

CONTRIBUTING.md

Expands info on tests needed for contributing.
For clarification and to simplify process for future contributors. I contributed, but didn't know there were e2e tests that I needed to pass first since it was not in docs. https://github.com/strapi/strapi/pull/18182#issuecomment-1743749694

docs: update tests that need passing for accepting contributions

---

packages/core/admin/server/src/controllers/authenticated-user.ts
packages/core/admin/server/src/controllers/role.ts
packages/core/admin/server/src/domain/action/provider.ts
packages/core/admin/server/src/domain/condition/index.ts
packages/core/admin/server/src/domain/permission/index.ts
packages/core/admin/server/src/services/permission/queries.ts
packages/core/admin/server/src/services/role.ts

Migrated admin role service to typescript

feat: ts migrate admin role service

---

packages/core/admin/server/src/services/project-settings.ts

Migrated admin project settings service to typescript

feat: ts migrate admin project settings

---

packages/cli/create-strapi-app/package.json
packages/cli/create-strapi-app/packup.config.ts
packages/cli/create-strapi-app/tsconfig.build.json
packages/cli/create-strapi-app/tsconfig.eslint.json
packages/cli/create-strapi-app/tsconfig.json
packages/cli/create-strapi-starter/package.json
packages/cli/create-strapi-starter/packup.config.ts
packages/cli/create-strapi-starter/tsconfig.build.json
packages/cli/create-strapi-starter/tsconfig.eslint.json
packages/cli/create-strapi-starter/tsconfig.json
yarn.lock

* packs the cli packages up
* cjs / esm

chore: packup cli packages

---

packages/core/data-transfer/package.json
packages/core/data-transfer/packup.config.ts
packages/core/data-transfer/src/strapi/remote/handlers/index.ts
packages/core/data-transfer/tsconfig.build.json
packages/core/data-transfer/tsconfig.eslint.json
packages/core/data-transfer/tsconfig.json
yarn.lock

* bundles data-transfer
* esm / cjs <3

chore(data-transfer): packup

---

packages/core/admin/server/src/services/passport/local-strategy.ts

Add further typing to the passport service

Passport services types

---

package.json
packages/core/admin/package.json
packages/core/admin/server/src/domain/permission/index.ts
yarn.lock

- Moves react types resolution to fix the build
- Modifies a permission type that was failing the build for me. @Marc-Roig wdyt of this, I can revert that part if its not correct

Fix: Build issues with types resolution

---

docs/docs/docs/01-core/strapi/commands/plugin/00-overview.md
docs/docs/docs/01-core/strapi/commands/plugin/02-watch.md
docs/docs/docs/05-utils/pack-up/01-commands/02-build.mdx
docs/docs/docs/05-utils/pack-up/01-commands/04-watch.mdx
docs/docs/docs/05-utils/pack-up/02-config.mdx
packages/core/strapi/src/commands/actions/plugin/watch/action.ts
packages/core/strapi/src/commands/actions/plugin/watch/command.ts
packages/core/strapi/src/commands/index.ts
packages/core/strapi/src/commands/utils/helpers.ts
packages/plugins/color-picker/package.json
packages/utils/pack-up/src/node/createTasks.ts
packages/utils/pack-up/src/node/tasks/dts/watch.ts

* adds experimental command for watching plugins
* plugin CLI enhancements in conjunction with our TS migration
* the color-picker plugin uses this CLI
* resolves CONTENT-1749

feat(strapi): add plugin:watch command

---

packages/core/admin/package.json
packages/core/admin/server/src/controllers/authentication.ts
packages/core/admin/shared/contracts/authentication.ts
packages/core/admin/shared/contracts/shared.ts
packages/core/admin/strapi-server.js
yarn.lock

- Creates shared types for the authentication endpoints
- Types authentication controllers

feat: type authentication endpoints

---

packages/core/strapi/src/Strapi.ts
packages/core/strapi/src/container.ts
packages/core/strapi/src/core/loaders/components.ts
packages/core/strapi/src/core/loaders/index.ts
packages/core/strapi/src/core/registries/__tests__/components.test.ts
packages/core/strapi/src/core/registries/components.ts

Move components into their own registry

chore(core/strapi): move components into their own registry

---

packages/core/strapi/src/Strapi.ts
packages/core/strapi/src/core/loaders/index.ts
packages/core/strapi/src/core/loaders/src-index.ts
packages/core/strapi/src/core/registries/index.ts
packages/core/types/src/index.ts

Simplify loader and registries
To follow the v5 plan of minimizing the API Surface 

chore(core/strapi): simplify loader and registries

---

packages/core/admin/server/src/controllers/admin.ts
packages/core/admin/server/src/services/project-settings.ts
packages/core/admin/shared/contracts/admin.ts

Add types for the admin controller

TS: Type admin controller

---

packages/core/admin/server/src/controllers/api-token.ts
packages/core/admin/server/src/services/api-token.ts
packages/core/admin/shared/contracts/api-token.ts

Add types for api token controller

TS: types api token controller

---

packages/core/admin/admin/src/StrapiApp.js
packages/core/admin/admin/src/core/utils/basename.js
packages/core/admin/admin/src/core/utils/basename.ts
packages/core/admin/admin/src/core/utils/createHook.ts
packages/core/admin/admin/src/core/utils/index.js
packages/core/admin/admin/src/core/utils/tests/createHook.test.ts
packages/core/admin/admin/src/pages/SettingsPage/pages/Users/components/MagicLink/index.js
packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/components/MagicLink/index.js

chore(admin): convert core utils to TS

---

packages/core/admin/server/src/controllers/authenticated-user.ts
packages/core/admin/server/src/controllers/authentication.ts
packages/core/admin/server/src/controllers/role.ts
packages/core/admin/server/src/controllers/user.ts
packages/core/admin/server/src/domain/user.ts
packages/core/admin/server/src/services/action.ts
packages/core/admin/server/src/services/auth.ts
packages/core/admin/server/src/services/permission/engine.ts
packages/core/admin/server/src/services/permission/queries.ts
packages/core/admin/server/src/services/role.ts
packages/core/admin/server/src/services/token.ts
packages/core/admin/server/src/services/user.ts
packages/core/admin/shared/contracts/authentication.ts
packages/core/admin/shared/contracts/shared.ts
packages/core/admin/shared/contracts/user.ts

Add types for the user controller

feature(admin): type user controller

---

packages/core/admin/server/src/controllers/webhooks.ts
packages/core/admin/shared/contracts/webhooks.ts
packages/core/types/src/index.ts

Adds types to the webhook controller

[admin]: type webhook controller

---

packages/core/data-transfer/src/strapi/remote/handlers/push.ts

It fixes the memory issue on the Data Transfer.
To get data transfer work with big amounts of data
Do a transfer between to strapi instances with a large amount of data. It should work as expected and the memory shouldn't spike.
https://github.com/strapi/strapi/pull/18557

fix: delete process.nexttick

---

packages/core/admin/server/src/controllers/__tests__/content-api.test.ts
packages/core/admin/server/src/services/__tests__/permissions.section-builder.section.test.ts
packages/core/types/src/modules/webhook-runner.ts

Fixes some build issues with the admin package from ts/admin

chore(admin): fix some admin build issues

---

.github/workflows/adminBundleSize.yml

* runs build in bundle-size workflow
* can't build an example without it!

fix(workflows): admin bundle-size workflow

---

packages/core/admin/server/src/controllers/__tests__/admin.test.ts
packages/core/admin/server/src/services/__tests__/auth.test.ts
packages/core/admin/server/src/services/__tests__/passport.test.ts
packages/core/admin/server/src/services/__tests__/role.test.ts
packages/core/admin/server/src/services/__tests__/user.test.ts

Fix imports in admin tests

---

packages/core/admin/server/src/controllers/transfer/runner.ts
packages/core/admin/server/src/controllers/transfer/token.ts
packages/core/admin/server/src/services/transfer/token.ts
packages/core/admin/shared/contracts/transfer.ts

Add types for the transfer controllers in the admin package

[admin]: type transfer controllers

---

api-tests/core/admin/admin-api-token-crud.test.api.ts
api-tests/core/admin/admin-transfer-token-crud.test.api.ts
api-tests/core/admin/ee/review-workflows-content-types.test.api.ts
api-tests/core/admin/ee/review-workflows-stage-permissions.test.api.ts
api-tests/core/admin/ee/review-workflows.test.api.ts
jest.config.api.js

feat: Migrate admin api tests to typescript

---

packages/core/admin/server/src/services/__tests__/permission.test.ts
packages/core/admin/server/src/services/__tests__/role.test.ts

fix(admin): mock event hub to avoid bad import

---

packages/cli/create-strapi-app/src/index.d.ts
packages/core/admin/package.json
packages/generators/app/src/create-quickstart-project.ts

* adds `index.js` & `index.d.ts` to the files array of `@strapi/admin`
* adds the additionalDeps to quick start projects
* admin was not shipping with a file it required
* experimental version – 0.0.0-experimental.b06a72a02d782efad2a22511763629f1e919fb69

chore(admin): add index files to files list

---

packages/plugins/cloud/package.json

Update the engine to the right version of node

Update node engine of cloud plugin

---

package.json
packages/core/admin/package.json
packages/core/content-type-builder/package.json
packages/core/email/package.json
packages/core/helper-plugin/package.json
packages/core/upload/package.json
packages/plugins/cloud/package.json
packages/plugins/color-picker/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json
yarn.lock

* updates design-system to 1.13.1
* solves an issue with vite

chore: update design-system 1.13.1

---

packages/core/admin/shared/contracts/review-workflows.ts

* adds contracts for Review-workflows
* so we can quickly type the FE

chore(admin): add workflow contracts

---

packages/core/types/src/modules/documents/index.ts
packages/core/types/src/modules/documents/params/document-service.ts

[v5] Document service params updates

---

packages/core/admin/package.json
packages/core/helper-plugin/package.json
packages/core/upload/package.json
yarn.lock

due to https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
* updates axios to 1.6.0
* https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
* cherry picked from `main` – #18768

chore(deps): update axios to 1.6.0 (#18768)

---

.github/workflows/tests.yml
packages/core/admin/admin/src/content-manager/components/InputUID/tests/index.test.js
packages/utils/pack-up/examples/cjs-js/package.json
packages/utils/pack-up/examples/esm-js/package.json

Experimenting with the flaky test this one was a straight forward change to avoi ddepending on timers. 
Fix & experiment flaky test issues
Run the tests on the inputUID 
/

Falky tests experimentation

---

packages/utils/upgrade/package.json
packages/utils/upgrade/src/__tests__/core/format.test.ts
packages/utils/upgrade/src/__tests__/core/logger.test.ts
packages/utils/upgrade/src/__tests__/core/runner.json.test.ts
packages/utils/upgrade/src/__tests__/core/runner.test.ts
packages/utils/upgrade/src/__tests__/core/time.test.ts
packages/utils/upgrade/src/__tests__/core/version.test.ts
packages/utils/upgrade/src/core/runner/index.ts
packages/utils/upgrade/src/core/runner/json.ts
packages/utils/upgrade/src/core/version.ts

Add unit tests for core utils
Improve the overall stability
`yarn test:unit`

[Upgrade Tool] Unit testing

---

packages/core/admin/server/src/services/api-token.ts
packages/core/admin/shared/contracts/api-token.ts

Clean up API token shared contracts

---

packages/core/content-manager/server/src/services/entity-manager.ts
packages/core/content-manager/server/src/services/populate-builder.ts
packages/core/content-manager/server/src/services/utils/__tests__/populate.test.ts
packages/core/content-manager/server/src/services/utils/populate.ts

- Migrates entity manager service to TS
- Migrates populate builderto TS

feat: type content manger entity manager service

---

packages/core/types/src/types/core/attributes/json.ts

I was seeing a build error in the CTB, I think exporting this JSON interface fixes it

fix(type): export JSONObject

---

packages/core/content-manager/server/src/services/__tests__/field-sizes.test.ts
packages/core/content-manager/server/src/services/field-sizes.ts

(content-manager): types for field sizes service

---

packages/core/admin/admin/src/pages/Settings/pages/TransferTokens/EditView.tsx
packages/core/admin/shared/contracts/transfer/token.ts

* Shares the FormValues in an interface
* casts the permission type because we're strict declaring the exact string types so an empty form does not satisfy the contract constraints
* runs prettier
* fixes!

chore(admin): fix transfer-tokens EditView

---

packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/actions.ts
packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/reducer.ts
packages/plugins/i18n/admin/src/middlewares/addCommonFieldsToInitialData.ts
packages/plugins/i18n/admin/src/middlewares/extendCTBAttributeInitialData.ts
packages/plugins/i18n/admin/src/middlewares/extendCTBInitialData.ts
packages/plugins/i18n/admin/src/middlewares/localePermission.ts
packages/plugins/i18n/admin/src/middlewares/tests/extendCTBAttrributeInitialDataMiddleware.test.ts
packages/plugins/i18n/admin/src/middlewares/tests/extendCTBInitialDataMiddleware.test.ts
packages/plugins/i18n/admin/src/middlewares/tests/localePermissionMiddleware.test.ts
packages/plugins/i18n/shared/contracts/content-manager.ts

* converts i18n middlewares to TS
* TS
* resolves CONTENT-2007

chore(i18n): convert middlewares to TS

---

packages/core/admin/admin/src/content-manager/components/BlocksInput/BlocksContent.tsx
packages/core/admin/admin/src/content-manager/components/DynamicZone/DynamicComponent.tsx
packages/core/admin/admin/src/content-manager/components/Relations/RelationInput.tsx
packages/core/admin/admin/src/content-manager/components/RepeatableComponent.tsx
packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.ts
packages/core/admin/admin/src/content-manager/hooks/useKeyboardDragAndDrop.ts

* refactors dnd hook to use a generic for Index
* fixes small CSS syntax issue in BlocksContent (L94)
* we don't have to check everytime which type of index we are using

chore: refactor dnd hook to use generics

---

packages/core/content-manager/server/src/services/permission.ts

[content-manager] types for permissions service

---

packages/core/content-manager/server/src/services/__tests__/uid.test.ts
packages/core/content-manager/server/src/services/uid.ts

[content-manager] types for uid service

---

packages/core/content-manager/server/src/services/__tests__/metrics.test.ts
packages/core/content-manager/server/src/services/metrics.ts

[content-manager] types for metrics service

---

packages/core/helper-plugin/src/utils/tests/wrapAxiosInstance.test.ts

Fixes a failing test in the helper plugin by mocking axios

fix: wrapAxiosInstance.test

---

packages/utils/upgrade/src/cli/index.ts
packages/utils/upgrade/src/modules/version/range.ts

- Adds minor and patch upgrades to the upgrade tool
- Make sure that running `minor` command upgrades to the latest minor of the current major, and executes codemods if any available.
- Make sure that running `patch` command upgrades to latest available patch of the current major and minor, and executes codemods if any available.

Upgrade tool minor and patch commands

---

docs/docs/docs/01-core/strapi/commands/plugin/04-check.md
packages/core/strapi/src/commands/actions/plugin/init/action.ts
packages/core/strapi/src/commands/actions/plugin/verify/action.ts
packages/core/strapi/src/commands/actions/plugin/verify/command.ts
packages/core/strapi/src/commands/index.ts

* adds experimental `plugin:verify` command
* part of the better plugin cli toolkit
* resolves CONTENT-1747

feat(strapi): add experimental plugin:verify command

---

packages/utils/upgrade/src/modules/codemod-repository/__tests__/repository.test.ts
packages/utils/upgrade/src/modules/codemod/__tests__/codemod.test.ts
packages/utils/upgrade/src/modules/logger/__tests__/logger.test.ts
packages/utils/upgrade/src/modules/npm/__tests__/package.test.ts
packages/utils/upgrade/src/modules/requirement/__tests__/requirement.test.ts
packages/utils/upgrade/src/modules/version/__tests__/range.test.ts
packages/utils/upgrade/src/modules/version/__tests__/semver.test.ts

Adds tests for the upgrade tool
To test the upgrade tool

Add unit tests for upgrade tool

---

packages/utils/upgrade/src/tasks/__tests__/upgrade.test.ts

Adds tests for the upgrader task
To test the upgrader

Add tests for the upgrade task

---

packages/core/content-manager/server/src/services/permission-checker.ts

Add type for the permission checker service

(content-manager): types for permission checker service

---

packages/core/content-releases/admin/src/pages/tests/ReleaseDetailsPage.test.tsx

Fix a flaky test for content-releases

fix(content-releases): fix test

---

packages/core/admin/admin/src/content-manager/components/BlocksInput/Blocks/Link.tsx
packages/core/admin/admin/src/translations/en.json

* changes the placeholder in the blocks link popover
* design request
* mentioned in https://github.com/strapi/strapi/pull/19136#issuecomment-1881242950

fix(cm): update placeholder in blocks link popover

---

.github/workflows/contributor-doc.yml
.github/workflows/tests.yml
CONTRIBUTING.md

* updates docs to reflect new Git process

chore: update contribution guide to reflect new git process

---

.github/workflows/skipped_tests.yml
.github/workflows/tests.yml

- Init CLI tests in the github CI

[CLI Tests] Init GitHub CI Workflow

---

e2e/tests/content-manager/editview.spec.js

Disable edit view E2E tests
These will be re written to match V5 publishing UI

chore(e2e): disable edit view tests

---

packages/core/content-releases/server/src/register.ts

- Formats code
- Make the linter happier
- I forgot 🤦‍♂️ 
Automated test

fix(content-releases): format register file

---

packages/core/core/src/Strapi.ts
packages/core/core/src/services/core-store.ts
packages/core/core/src/services/webhook-store.ts
packages/core/core/src/utils/transform-content-types-to-models.ts
packages/core/database/src/entity-manager/index.ts
packages/core/database/src/index.ts
packages/core/database/src/metadata/index.ts
packages/core/database/src/metadata/metadata.ts
packages/core/database/src/types/index.ts
packages/core/database/src/utils/types.ts
packages/core/database/src/validations/relations/bidirectional.ts
packages/utils/pack-up/src/__tests__/cli.test.ts

lift compontent logic out of the db and start exposing models
offer more granularity for internal work
make sure all the tests are passing and you can keep using the core store / webhooks & components / dynamic zones

chore: lift compontent logic out of the db and start exposing models

---

packages/core/core/src/Strapi.ts
packages/core/core/src/registries/index.ts
packages/core/core/src/registries/models.ts
packages/core/core/src/services/core-store.ts
packages/core/database/src/index.ts
packages/core/database/src/metadata/index.ts

Adds a basic models registry to allow registring a low level model. 
For future feature implementation

chore: add a simple model registry

---

packages/core/content-manager/server/src/services/__tests__/uid.test.ts
packages/core/content-manager/server/src/services/uid.ts
packages/core/core/src/services/entity-validator/__tests__/biginteger-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/date-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/datetime-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/float-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/integer-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/string-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/time-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/timestamp-validators.test.ts
packages/core/core/src/services/entity-validator/validators.ts

Modifies validation logic for unique fields and UID fields. Making sure we are querying the document service with the correct parameters to find entries sharing unique values
- Fixes failing API tests related to unique checks
- Unique field functionality

fix unique and UID validation logic

---

api-tests/core/content-manager/api/x-to-many-rf-preview.test.api.js
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/CreatePage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/EditPage.tsx
packages/core/admin/ee/admin/src/services/reviewWorkflows.ts
packages/core/admin/shared/contracts/review-workflows.ts
packages/core/content-manager/server/src/controllers/relations.ts

merge releases/4.20.1 into 4.20.0

---

api-tests/core/strapi/api/validate-body.test.api.js
packages/core/admin/server/src/services/permission/permissions-manager/sanitize.ts
packages/core/admin/server/src/services/permission/permissions-manager/validate.ts
packages/core/utils/src/sanitize/index.ts
packages/core/utils/src/validate/index.ts

- Update API tests
- Make sure to handle edge scenarios during body validation
fix https://github.com/strapi/strapi/issues/19346

Fix input payload validation

---

packages/core/core/src/services/document-service/transform/utils.ts

Fixes API tests by setting [id] to [documentId] on document service outputs

fix(core): switchIdForDocumentId

---

docs/docs/docs/01-core/content-manager/hooks/use-document-actions.mdx
docs/docs/docs/01-core/content-manager/hooks/use-document.mdx
packages/core/admin/admin/src/content-manager/hooks/tests/useDocument.test.tsx
packages/core/admin/admin/src/content-manager/hooks/tests/useDocumentActions.test.ts
packages/core/admin/admin/src/content-manager/hooks/useDocument.ts
packages/core/admin/admin/src/content-manager/hooks/useDocumentActions.ts
packages/core/admin/admin/src/content-manager/pages/EditView/components/DocumentActions.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/Header.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/Panels.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/ListViewPage.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActions/ConfirmBulkActionDialog.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActions/tests/Buttons.test.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/components/TableActions.tsx
packages/core/admin/admin/src/content-manager/services/documents.ts
packages/core/admin/admin/src/core/apis/content-manager.ts
packages/core/admin/admin/src/index.ts
packages/core/admin/admin/tests/server.ts
packages/core/content-manager/server/tsconfig.build.json
packages/core/content-manager/shared/contracts/collection-types.ts
packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/tests/ReleaseActionMenu.test.tsx
packages/core/content-releases/shared/contracts/release-actions.ts
packages/core/helper-plugin/src/components/Table.tsx
packages/core/types/src/modules/documents/result/index.ts
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx
packages/plugins/i18n/admin/src/components/LocaleListCell.tsx
packages/plugins/i18n/admin/src/components/tests/LocaleListCell.test.tsx

* uses documentId instead of id in the content-manager
* updates associated documentation
* resolves CONTENT-2257

chore(content-manager): use documentId over id

---

packages/core/content-releases/admin/src/components/ReleaseModal.tsx

Fixed selected timezone deleting issue
https://strapi-inc.atlassian.net/browse/CS-623
For the scheduled release, you should be delete to the selected timezone value using backspace key.

fix(content-releases): Delete selected timezone value

---

packages/core/admin/admin/src/content-manager/components/ConfigurationForm/Fields.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/ListConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/components/Settings.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/components/SortDisplayedFields.tsx

Fixes a bug where we were unable to remove all fields from the list view config list
@joshuaellis I don't fully understand the implications is this something we can do?

fix(admin): wip allow empty list view configuration

---

packages/plugins/i18n/admin/src/components/CreateLocale.tsx

Close modal after successful locale creation
i18n E2E tests were failing because of this

fix(i18n): close modal after successful locale creation

---

packages/core/admin/admin/src/components/Form.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/EditViewPage.tsx

* resets the form when the tab changes to published
* fixes an issue where validation errors and semi-modified carried between tabs
* create an entry
* publish it
* make a change that will cause a validation error
* navigate to published tab
* should *not* see the error
* resolves CONTENT-2284

fix(cm): errors leaking from draft to published tab

---

examples/getstarted/src/api/category/content-types/category/schema.json
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/BlocksInput/BlocksInput.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Component/Input.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/DynamicZone/Field.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/UID.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Wysiwyg/Field.tsx
packages/plugins/i18n/admin/src/contentManagerHooks/editView.tsx
packages/plugins/i18n/admin/src/index.ts

* adds labelActions too fields in the edit view based on if they're i18n.localized
* resolves CONTENT-2033

feat(i18n): add earth icon to symbolise localised fields

---

api-tests/core/content-manager/find-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-available-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-existing-relations.test.api.js
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/admin/admin/src/content-manager/services/relations.ts
packages/core/content-manager/server/src/controllers/relations.ts

fix: order of cm relations

---

packages/core/content-type-builder/server/src/services/__tests__/__snapshots__/content-types.test.ts.snap
packages/core/utils/src/content-types.ts

test: update d&p snapshot

---

api-tests/core/content-manager/find-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-available-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-existing-relations.test.api.js
examples/getstarted/src/index.js
packages/core/admin/admin/src/components/Form.tsx
packages/core/admin/admin/src/content-manager/pages/ComponentConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/ListConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/services/relations.ts
packages/core/admin/admin/src/translations/en.json
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/content-manager/shared/contracts/relations.ts

* adds drag-and-drop to relations
* resolves CONTENT-2325
* resolves CONTENT-1898

feat: add drag-and-drop to relations

---

packages/core/types/src/modules/entity-service/params/attributes/relation.ts

Fix relational positional arguments type

fix: relation positional arguments

---

packages/core/admin/admin/src/components/PageHelpers.tsx
packages/core/admin/admin/src/services/auth.ts

Fixes access to the CM when using custom permission conditions
CONTENT-2339

fix(admin): CM access when using custom conditions

---

packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/CreatePage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/ListPage.tsx
packages/providers/audit-logs-local/package.json
packages/providers/audit-logs-local/src/index.ts
yarn.lock

- Fix an issue in audit logs & one in review workflows that I found testing some basic navigation
V5

fix: some ee issues

---

packages/core/admin/admin/src/content-manager/pages/EditView/components/DocumentActions.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/content-manager/server/src/middlewares/routing.ts
packages/plugins/users-permissions/server/controllers/content-manager-user.js

- Fix u&p code redirectin not working
- Role relation is still not working. looks like it's not managed correctly in the CM

chore: update u&p

---

packages/core/admin/admin/src/content-manager/services/documents.ts
packages/core/admin/admin/src/content-manager/services/relations.ts
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/core/src/services/document-service/transform/relations/utils/i18n.ts

Fix some relational bugs.
- Send pagination for xToOne relations
- Proper locale and status validation

fix: cm relation bugs

---

packages/cli/create-strapi/LICENSE
packages/cli/create-strapi/README.md
packages/cli/create-strapi/bin/index.js
packages/cli/create-strapi/package.json
yarn.lock

Add a create-strapi pkg to have an even simpler cli cmd

feat: add create-strapi package

---

packages/core/content-manager/server/src/history/services/utils.ts

- Fixes a type
- It breaks everything
- Strapi should build

fix(history): update type

---

docs/docs/api/Strapi.mdx
packages/core/content-type-builder/server/src/controllers/content-types.ts
packages/core/core/src/Strapi.ts
packages/core/core/src/services/__tests__/content-api-permissions.test.ts
packages/core/core/src/services/content-api/index.ts
packages/core/core/src/services/content-api/permissions/index.ts
packages/core/core/src/services/server/register-routes.ts
packages/core/types/src/core/strapi.ts
packages/plugins/documentation/server/src/services/__mocks__/mock-strapi-data.ts
packages/plugins/documentation/server/src/services/__tests__/build-component-schema.test.ts
packages/plugins/documentation/server/src/services/__tests__/documentation.test.ts
packages/plugins/documentation/server/src/services/documentation.ts
packages/plugins/documentation/server/src/services/helpers/utils/loop-content-type-names.ts
packages/plugins/users-permissions/server/services/users-permissions.js
test/setup/unit.setup.js

Refactor api registry & accessors

chore: refactor api registry

---

packages/core/upload/server/services/__tests__/upload/formatFileInfo.test.js
packages/core/upload/server/services/image-manipulation.js
packages/core/upload/server/services/upload.js

Sanitizes filename so it does not contain null characters

fix: sanitize file name when uploading image

---

packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/pages/ReleasesPage.tsx
packages/core/content-releases/package.json
packages/core/strapi/src/commands/actions/plugin/init/action.ts
packages/generators/generators/src/templates/ts/plugin-package.json.hbs
yarn.lock

- It fixes the issues of capitalising the first letter of Hours/Days/Weeks etc.
- StyledComponents dependency upgraded to fix : defaultProps circularly references error.
Please check releases page and check if scheduling info, eg: In 2 days, 6 hours, days/hours/week should not be capitalized.

fix(releases): Scheduling info capitalization

---

CONTRIBUTING.md

chore: fix #19349

---

packages/core/admin/ee/admin/src/content-manager/pages/ListView/constants.ts
packages/core/helper-plugin/src/components/FilterListURLQuery.tsx
packages/core/helper-plugin/src/components/FilterPopoverURLQuery.tsx
packages/core/helper-plugin/src/components/tests/FilterListURLQuery.test.tsx
packages/core/helper-plugin/src/types.ts

- Fixes invalid mainField type & data structure not matching with the right filters

fix issue #19532

---

.github/workflows/issues_handleLabel.yml

- Add Dennis + Nick to round-robin
- Fix project assignment with new domain ownership
Removal of a squad
Create an issue and label it
N/A

chore: update github issue label workflow

---

packages/utils/upgrade/resources/codemods/5.0.0/entity-service-document-service.code.ts
packages/utils/upgrade/resources/codemods/5.0.0/strapi-public-interface.code.ts
packages/utils/upgrade/resources/codemods/5.0.0/utils-public-interface.code.ts

codemod for the new strapi factory interface
```
npx jscodeshift -t transformer-file.ts -d -p file-to-transform.js
```

Add multiple v5 codemods

---

tests/cli/tests/strapi/version/version.test.cli.js

adds the same semver fix to the other version test

tests: use semver for both version tests

---

packages/core/content-manager/package.json
packages/core/review-workflows/package.json
yarn.lock

* fixes peer deps (i broke em)
* you can't install a beta with strict deps without this string

chore(cm): fix peer-deps

---

docs/docs/guides/05-type-system/01-philosophy.md

formatting, I just ran `yarn prettier:write`
make prettier check happy

chore: run prettier:write script

---

tests/api/core/content-manager/api/number-of-draft-relations.test.api.js

Fixes the current api tests for counting draft relations in V5
This is needed as a base for https://github.com/strapi/strapi/pull/20046 but I thought it made sense to get the initial fix into v5/main first

fix(api-test): number of draft relations

---

packages/core/content-manager/admin/src/history/components/VersionHeader.tsx
packages/core/content-manager/admin/src/history/components/VersionsList.tsx

Small changes requested by @lucasboilly to match the designs

fix: history design details

---

packages/utils/upgrade/resources/codemods/5.0.0/entity-service-document-service.code.ts

Updates codemod to match new function format

chore: update codemod to match new format

---

docs/docs/guides/05-type-system/02-concepts/01-schema.mdx
docs/docs/guides/05-type-system/02-concepts/02-uid.mdx
docs/docs/guides/05-type-system/02-concepts/03-public-registry.mdx

Fix https://github.com/strapi/strapi/actions/runs/8783613024/job/24100130448?pr=20169

docs: fix formatting in contributor docs

---

SECURITY.md

Adds information related to Strapi 5 Beta
Questions from community members about security/vulnerability reports on the beta
N/A
N/A

Update SECURITY.md with changes related to Strapi 5 Beta

---

packages/generators/app/package.json
packages/generators/app/src/utils/usage.ts
packages/plugins/sentry/package.json
yarn.lock

Upgrades sentry. No public API breaking changes.

chore: upgrade sentry

---

packages/core/content-manager/server/src/services/document-manager.ts
packages/core/core/src/core-api/service/__tests__/index.test.ts
packages/core/core/src/core-api/service/collection-type.ts
packages/core/core/src/core-api/service/single-type.ts
packages/core/core/src/services/document-service/repository.ts
packages/core/types/src/modules/documents/result/document-engine.ts
packages/core/types/src/modules/documents/service-instance.ts
packages/plugins/i18n/server/src/bootstrap.ts
tests/api/core/content-manager/find-relations.test.api.js
tests/api/core/strapi/document-service/clone.test.api.ts
tests/api/core/strapi/document-service/discard-draft.test.api.ts
tests/api/core/strapi/document-service/relations/basic.test.api.ts

chore: make document service api more consistent
v5

chore: make document service api more consistent

---

packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts

Part of the document id migration was failing for mysql:
Instead of developing a complex query with joins or multiple queries for each database, I splitted the update into two queries:
1. Streams the entries to update 
2. Makes the update individually
This is very similar as the first approach alex proposed, but the .stream() batches the request so it's more performant.
Next step could be to use a temporary table to store a map of id->documentId and do batch updates too.
kudos to @innerdvations for spotting this

fix: doc id migration for mysql

---

packages/providers/email-mailgun/package.json
packages/providers/email-mailgun/src/__tests__/convert-provider-options.test.ts
packages/providers/email-mailgun/src/index.ts
yarn.lock

Upgrade mailgun provider and remove deprecated options

chore: upgrade mailgun provider and remove deprecated options

---

packages/core/database/src/query/helpers/where.ts
tests/api/core/strapi/deep-filtering.test.api.js
tests/api/core/strapi/filtering.test.api.js

Fix https://github.com/strapi/strapi/issues/20138

fix: issue 20138

---

packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActions/PublishAction.tsx

~This pull request fixes a bug with the Content Manager's Bulk Publish button based on two premises:~
1. ~All logic related to displaying data in the Bulk Publish modal should reside in the `SelectedEntriesModalContent` and not outside of it. `PublishAction` should contain only logic related to when to show or hide the Bulk Publish button.~
2. ~Since all data related to the ListView is already present in the listView table, it is unnecessary to make another request.~
* Simplifies the Publish Modal by reducing the amount of times we use `setState`, the state is derived originally from the ListView selected items that the action receives. It then queries for *just* these items from the API, so everything is updated originally from the ListView reducing the amount of different times we set …

fix(content-manager): bulk publish would only ever show first entry to be published

---

packages/core/admin/admin/src/components/GuidedTour/Homepage.tsx
packages/core/admin/admin/src/components/GuidedTour/Modal.tsx
packages/core/admin/admin/src/components/Pagination.tsx
packages/core/admin/admin/src/features/Notifications.tsx
packages/core/admin/admin/src/pages/Auth/components/ForgotPassword.tsx
packages/core/admin/admin/src/pages/Auth/components/ForgotPasswordSuccess.tsx
packages/core/admin/admin/src/pages/Auth/components/Login.tsx
packages/core/admin/admin/src/pages/Auth/components/Oops.tsx
packages/core/admin/admin/src/pages/Auth/components/Register.tsx
packages/core/admin/admin/src/pages/Auth/components/ResetPassword.tsx
packages/core/admin/admin/src/pages/Marketplace/components/PageHeader.tsx
packages/core/admin/admin/src/pages/Settings/components/Tokens/Table.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/components/ConditionsModal.tsx
packages/core/admin/admin/src/pages/Settings/pages/Users/components/NewUserForm.tsx
packages/core/admin/ee/admin/src/pages/AuthPage/components/Providers.tsx
packages/core/content-manager/admin/src/components/ConfigurationForm/Fields.tsx
packages/core/content-manager/admin/src/components/LeftMenu.tsx
packages/core/content-manager/admin/src/history/components/VersionHeader.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx
packages/core/content-manager/admin/src/pages/ListConfiguration/components/SortDisplayedFields.tsx
packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx
packages/core/content-manager/admin/src/pages/ListView/components/TableCells/Components.tsx
packages/core/content-manager/admin/src/pages/ListView/components/TableCells/Relations.tsx
packages/core/content-type-builder/admin/src/components/AttributeOptions/CustomFieldsList.tsx
packages/core/content-type-builder/admin/src/components/AutoReloadOverlayBlocker.tsx
packages/core/review-workflows/admin/src/components/LimitsModal.tsx

Ran `yarn lint:fix` at the root of the repo.
Gets rid of a bunch of warnings

chore: run lint fix

---

packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.jsx
packages/plugins/users-permissions/server/config.js

The back button is not working, and I need it to facilitate easy back history.
The back button does not work when configuring the view of any collection or single type on ListSettingsView.
There is no related issue

fix back button on ListSettingsView

---

packages/core/admin/admin/src/components/FormInputs/Boolean.tsx
packages/core/admin/admin/src/components/FormInputs/Checkbox.tsx
packages/core/admin/admin/src/components/FormInputs/Date.tsx
packages/core/admin/admin/src/components/FormInputs/DateTime.tsx
packages/core/admin/admin/src/components/FormInputs/Email.tsx
packages/core/admin/admin/src/components/FormInputs/Enumeration.tsx
packages/core/admin/admin/src/components/FormInputs/Json.tsx
packages/core/admin/admin/src/components/FormInputs/Number.tsx
packages/core/admin/admin/src/components/FormInputs/Password.tsx
packages/core/admin/admin/src/components/FormInputs/Renderer.tsx
packages/core/admin/admin/src/components/FormInputs/String.tsx
packages/core/admin/admin/src/components/FormInputs/Textarea.tsx
packages/core/admin/admin/src/components/FormInputs/Time.tsx
packages/core/content-manager/admin/src/features/DocumentRBAC.tsx
packages/core/content-manager/admin/src/hooks/useContentTypeSchema.ts
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksInput.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Input.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/NotAllowed.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/UID.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Wysiwyg/Field.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx

* fixes how component permissions are found, they didn't account for nested components
* fixes performance issues in nested components where redux was running a calculation too often
* You couldn't see fields in nested components, and if you could, they were laggy
* resolves #20159

fix(cm): nested components never have permission

---

packages/core/content-manager/server/src/history/services/lifecycles.ts

Fix https://github.com/strapi/strapi/issues/20086

fix: issue 20086, avoid preloading services during init lifecycles

---

packages/core/core/src/Strapi.ts
packages/core/database/package.json
packages/core/database/src/index.ts
packages/core/database/src/migrations/internal.ts
packages/core/database/src/migrations/logger.ts
packages/core/database/src/migrations/users.ts
yarn.lock

- Add ajv as a direct dep to fix https://github.com/strapi/strapi/issues/20504 for now.
- Improve migration logging so internal migration only appear in debug mode & improve logging
v5 RC
- delete some rows in strapi_migrations & restart the getstarted app, logs should appear in debug for internal migration
- try creating a user migration in database/migrations (a simple sql file with SELECT 1) and restart and see the info log

chore: upgrade umzug & improve db migration logging

---

packages/core/upload/admin/src/components/MediaLibraryInput/index.jsx

Fix https://github.com/strapi/strapi/issues/20083

fix: multiple is only available in attribute now

---

packages/core/core/src/Strapi.ts
packages/core/types/src/core/strapi.ts

Fix https://github.com/strapi/strapi/issues/20253

fix: lifecycle order, provider 1st during bootstrap

---

packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeOption.tsx
packages/core/content-type-builder/admin/src/components/AttributeOptions/tests/__snapshots__/AttributeOptions.test.tsx.snap
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/ContentTypeBuilderNav.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.tsx.snap
packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/content-type-builder/admin/src/components/IconPicker/IconPicker.tsx

Fix several UI issues in CTB
- field type color
- component icon picker 
Closes https://github.com/strapi/strapi/issues/20508

fix: ctb ui & state issues

---

packages/core/database/src/entity-manager/regular-relations.ts

Fixes an issue only reproducible in Postgres and on new Strapi apps (not in the monorepo itself)
The database relation stealing was failing, and was due to the knex connection being "reused" to create subqueries.
```ts
// Before
connection
.from(tableName)
.where(
'column', 
connection.select(...)  // Reused same connection
) 
// After
connection
.from(tableName)
.where(
'column', 
(con) => con.select(...)  // New connection reference
) 
```
Aparently the former created a self reference inside the connection query

fix: self referencing relations

---

packages/core/content-manager/admin/src/hooks/useDocument.ts
packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx
packages/core/content-releases/admin/src/services/release.ts
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx
packages/plugins/i18n/admin/src/components/LocaleListCell.tsx
packages/plugins/i18n/admin/src/hooks/useI18n.ts

- Prevent over fetching unecessary information
- Avoid using outdated RTK data when fetching new data

Fix multiple CM/i18N/admin state loading issues

---

packages/core/admin/admin/src/components/ConfirmDialog.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/ListPage.tsx
packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx
packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.jsx.snap
packages/core/upload/admin/src/components/AssetDialog/index.jsx
packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/CroppingActions.jsx
packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/components.jsx
packages/core/upload/admin/src/components/EditAssetDialog/RemoveAssetDialog.jsx
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.jsx.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.jsx.snap
packages/core/upload/admin/src/components/MediaLibraryInput/index.jsx
packages/core/upload/admin/src/components/SelectTree/SelectTree.jsx
packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.jsx
packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.jsx
packages/core/upload/admin/src/pages/App/ConfigureTheView/index.jsx
packages/core/upload/admin/src/pages/App/MediaLibrary/components/Header.jsx
packages/core/upload/admin/src/pages/App/MediaLibrary/components/tests/__snapshots__/Header.test.jsx.snap
packages/core/upload/admin/src/pages/App/MediaLibrary/index.jsx
tests/api/core/content-manager/api/number-of-draft-relations.test.api.js

- Fix https://github.com/strapi/strapi/issues/20539
- Fix https://github.com/strapi/strapi/issues/20456
- Fix media lib config confirm not closing
- Fix move/select folder not working
- Fix scrolling in all media lib modals
- Fix theme issues
- Fix invalid modal states because they remained mounted without clearing internal state
- Fix Delete from Edit modal
- Fix cropping

fix: several media lib ui issues

---

packages/cli/cloud/src/create-project/command.ts
packages/cli/cloud/src/deploy-project/command.ts
packages/cli/cloud/src/index.ts
packages/cli/cloud/src/login/command.ts
packages/cli/cloud/src/logout/command.ts
packages/cli/cloud/src/types.ts
packages/core/strapi/src/cli/commands/index.ts
packages/core/strapi/src/cli/index.ts
packages/core/strapi/src/cli/types.ts

fix(cloud-cli): update types and structure for v5

---

packages/cli/create-strapi-app/src/create-strapi-app.ts
packages/cli/create-strapi-app/src/types.ts
packages/generators/app/src/create-project.ts
packages/generators/app/src/index.ts
packages/generators/app/src/types.ts

Disable template option in the CLI until we rebuild them

chore: disable --templates while we rework them

---

packages/generators/app/src/create-project.ts

Re-add programmatic use for templates for e2e

fix: e2e template programmaticaly

---

packages/core/admin/admin/src/components/MainNav/NavBrand.tsx
packages/core/admin/admin/src/components/MainNav/NavLink.tsx
packages/core/admin/admin/src/components/MainNav/NavUser.tsx
packages/core/content-manager/admin/src/components/LeftMenu.tsx

Fixes on the main nav:
- empty space at the bottom
- logo not vertically aligned
- show tooltips instantly
- fix a defaultMessage not matching the value in the translation files
Polishing for RC

fix: main nav fixes

---

packages/core/admin/admin/src/components/Form.tsx
packages/core/admin/admin/src/components/tests/Form.test.tsx
packages/core/admin/admin/src/hooks/useAPIErrorHandler.ts
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/Events.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/HeadersInput.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/AuditLogs/ListPage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/AuditLogs/tests/ListPage.test.tsx
packages/core/content-manager/admin/src/hooks/tests/useDocument.test.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Initializer.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/Field.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx
packages/core/content-manager/admin/src/utils/validation.ts
packages/core/content-type-builder/admin/src/components/CheckboxWithNumberField.tsx
packages/core/content-type-builder/admin/src/components/FormModal/attributes/validation/common.ts
packages/core/content-type-builder/admin/src/components/TabForm.tsx
packages/core/content-type-builder/admin/src/translations/en.json
packages/plugins/users-permissions/admin/src/components/Permissions/PermissionRow/SubCategory.jsx
packages/plugins/users-permissions/admin/src/pages/Providers/index.jsx
packages/plugins/users-permissions/admin/src/pages/Roles/pages/ListPage/components/TableBody.jsx

Fixes several UI issues & the CM validations

fix: several UI issues a typos

---

packages/core/content-manager/admin/src/pages/ListConfiguration/components/DraggableCard.tsx

Fixed displayed fields DND in configure views.
Fixes https://github.com/strapi/strapi/issues/20222

fix: displayed fields dnd not working

---

packages/core/strapi/src/middlewares/cors.ts

Put string array support back into cors for compatbility 
Closes https://github.com/strapi/strapi/issues/20544

fix: support string array

---

packages/core/admin/admin/src/pages/HomePage.tsx
packages/core/admin/admin/src/pages/tests/HomePage.test.tsx
packages/core/admin/admin/src/translations/en.json

Change the Cloud message in the homepage
From this
To this
Open the CMS and go to the home page and check the message
CS-940

Change the Cloud message in Homepage

---

packages/core/content-releases/admin/src/components/ReleaseModal.tsx
packages/core/content-releases/admin/src/pages/ReleasesPage.tsx
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/admin/src/validation/schemas.ts

Fix bugs on Releases modal when creating a release with scheduling & also show again translated error messages in release modal. 
Try to create a new release with scheduling enabled trying with different times.

fix(content-releases): check time has not passed if date is today

---

packages/plugins/cloud/admin/src/components/ContentBox.tsx
packages/plugins/cloud/admin/src/pages/Home.tsx
packages/plugins/cloud/admin/src/translations/en.json

feat: add cloud plugin marketing ui

---

packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx
packages/core/content-type-builder/server/src/services/architect.ts

- Just hardcodes some schema values to ensure the schema is saveable

fix: allow saving ai generated content type

---

packages/core/core/src/loaders/plugins/get-enabled-plugins.ts

Tentative fix for https://github.com/strapi/strapi/issues/20298
Create a new app with the experiemental linked below
Closes https://github.com/strapi/strapi/issues/20298

fix: resolve internal plugins from the strapi pkg

---

.github/workflows/tests.yml

Fixes that platform works and add sharding
See CI logs

shard ee tests+ fix broken platform

---

.github/workflows/tests.yml

Duplicate of https://github.com/strapi/strapi/pull/20942 for v5

chore: add aggregate test result to v5

---

.github/workflows/tests.yml

flatten the test structure
To decrease wait time on tests with this down from 17 min to [11 min](https://github.com/strapi/strapi/actions/runs/10296893677)
see test pipeline

flatten tests

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/ConfirmBulkActionDialog.tsx
packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/tests/ConfirmBulkActionDialog.test.tsx
tests/e2e/tests/content-manager/editview.spec.ts

Temporarily disables all draft relation counts
There is known issue with the logic that needs to be worked on separately

chore: Disable draft relation counts

---

packages/core/upload/admin/src/hooks/useSelectionState.ts

Fix https://github.com/strapi/strapi/issues/20748

fix: uncheck files on Media Library

---

packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

Fix https://github.com/strapi/strapi/issues/20747

fix: release errors not parsing nested errors

---

packages/core/content-manager/admin/src/components/ConfigurationForm/Fields.tsx
packages/core/content-manager/admin/src/layout.tsx
packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromUrlForm.jsx

- Fix https://github.com/strapi/strapi/issues/20749 
- Fix the edit button didn't work and the modal would not open
- Fix https://github.com/strapi/strapi/issues/20591
- Fix https://github.com/strapi/strapi/issues/20899

fix: multiple v5 issues

---

packages/core/admin/admin/src/content-manager/pages/ListView/components/AdminUsersFilter.tsx
packages/core/admin/shared/contracts/user.ts

Fix https://github.com/strapi/strapi/issues/21079

fix: issue 21079

---

packages/core/admin/shared/contracts/user.ts
packages/core/content-manager/admin/src/pages/ListView/components/Filters.tsx

Fix https://github.com/strapi/strapi/issues/21079

fix: issue 21079 on v5

---

packages/core/admin/admin/src/content-manager/components/BlocksInput/BlocksContent.tsx

Fix https://github.com/strapi/strapi/issues/20943
- Go on firefox and try doing selection like described in the issue and replace or delete and see no more errors

fix: rich text selection & deletion issues

---

packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/content-type-builder/admin/src/components/FormModalNavigationProvider/FormModalNavigationProvider.tsx
packages/core/content-type-builder/admin/src/components/FormModalNavigationProvider/constants.ts
packages/core/content-type-builder/admin/src/contexts/FormModalNavigationContext.ts
packages/core/content-type-builder/admin/src/pages/ListView/LinkToCMSettingsView.tsx
tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts

- Fix ctb missing configure view button because of invalid permission check
- Fix https://github.com/strapi/strapi/issues/20584

fix: ctb configure view invalid permission check

---

packages/core/content-type-builder/server/src/services/schema-builder/content-type-builder.ts
packages/core/database/src/metadata/__tests__/resources/expected-hashed-metadata.ts
packages/core/database/src/metadata/__tests__/resources/expected-metadata.ts
packages/core/database/src/metadata/__tests__/resources/models.ts
packages/core/database/src/metadata/relations.ts
packages/core/database/src/types/index.ts
tests/api/core/database/v4-self-ref-compat.test.api.js

Fix https://github.com/strapi/strapi/issues/20948
- This only ensure the v4 behavior still exists to avoid any data loss. The app is already logging a warning for the user to change their config. 
- It also fixes the ctb behavior for new relations
- This will need another refactoring at a later time
Implements DX-1512
#20948

fix: reproduce v4 behavior for data compatibility

---

packages/core/types/package.json
packages/core/types/src/core/controller.ts
yarn.lock

Tentative fix for https://github.com/strapi/strapi/issues/20430

chore: import koa-body type to have request.body work

---

packages/core/content-manager/admin/src/pages/ListView/components/TableCells/CellContent.tsx
packages/core/content-manager/admin/src/pages/ListView/components/TableCells/Relations.tsx

Fixes https://github.com/strapi/strapi/issues/20604

fix: list view populated data not managed  

---

packages/cli/create-strapi-app/src/create-strapi.ts
packages/cli/create-strapi-app/src/utils/logger.ts

fix: potential negative repeat and typo

---

packages/core/admin/admin/src/components/tests/PrivateRoute.test.tsx

clear sessionStorage between tests
fixes the issue where test wouldn't clear state between tests
run it
fixes issue with test found in https://github.com/strapi/strapi/pull/21141

test: clear sessionStorage between tests

---

packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/HeadersInput.tsx

Fix webhook header input submitting the form when removing a row and not allowing to clear the 1st row easily

fix: webhook button submitting and remove row clearing

---

packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/HeadersInput.tsx

Improves the styling of the header delete button in the webhook edit view

chore(admin): improve webhook delete button style

---

packages/core/admin/admin/src/components/Context.tsx
packages/core/admin/admin/src/components/GuidedTour/Homepage.tsx
packages/core/admin/admin/src/components/GuidedTour/Modal.tsx
packages/core/admin/admin/src/components/GuidedTour/Provider.tsx
packages/core/admin/admin/src/pages/Auth/components/tests/Register.test.tsx
packages/core/admin/admin/src/pages/Settings/pages/ApiTokens/EditView/tests/EditViewPage.test.tsx
packages/core/admin/admin/src/pages/Settings/pages/TransferTokens/EditView.tsx
packages/core/admin/admin/src/pages/tests/HomePage.test.tsx
packages/core/admin/admin/tests/utils.tsx
packages/core/content-manager/admin/src/hooks/useDocumentActions.ts
packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx

Fix https://github.com/strapi/strapi/issues/20825

fix: guided tour

---

packages/cli/create-strapi-app/templates/example-js/src/bootstrap.js
templates/website/src/bootstrap.ts

Fix js example template not using the write doc service method

fix: js example templat

---

packages/cli/create-strapi-app/templates/example/src/admin/vite.config.example.ts
packages/cli/create-strapi-app/templates/vanilla/src/admin/vite.config.example.ts
templates/website/src/admin/vite.config.example.ts

Updates vite config example template for ts to be actual ts

fix: template vite config example

---

packages/cli/create-strapi-app/templates/example-js/src/bootstrap.js
packages/cli/create-strapi-app/templates/example/src/bootstrap.ts

With this PR, media files uploaded with the example data are unique. 
Previously, media files where created multiple time, the check on their uniqueness was not working good.
Create a new project with the example data and check the files in the media library.

Fix example data, media files uniqueness

---

packages/plugins/users-permissions/server/controllers/auth.js
packages/plugins/users-permissions/server/services/user.js

Fix https://github.com/strapi/strapi/issues/20955

fix: emailConfirmation broken

---

packages/core/admin/admin/src/pages/Settings/pages/Users/components/MagicLinkWrapper.tsx

Copy to clipboard was re-submiting the form and getting email already exist warning

fix: warning user creation

---

packages/core/review-workflows/admin/src/routes/content-manager/[model]/[id]/components/AssigneeSelect.tsx
packages/core/review-workflows/admin/src/routes/content-manager/[model]/[id]/components/Panel.tsx
packages/core/review-workflows/admin/src/routes/content-manager/[model]/[id]/components/StageSelect.tsx

- Fix https://github.com/strapi/strapi/issues/21293
- Might have fixed https://github.com/strapi/strapi/issues/21292 as I cannot reproduce it on my branch

fix: review workflow issues

---

packages/core/content-releases/admin/src/services/release.ts
packages/core/content-releases/server/src/services/release-action.ts

- Fix missing await breaking status update.  Clear cache correctly
- Fix https://github.com/strapi/strapi/issues/21289

fix: releases status update

---

packages/core/content-manager/server/src/controllers/relations.ts

Fix relation findAvalaible 
Fix https://github.com/strapi/strapi/issues/21287
Fix https://github.com/strapi/strapi/issues/21286

fix: relations filtering on locales

---

examples/getstarted/src/api/restaurant/content-types/restaurant/schema.json
packages/core/admin/admin/src/components/Form.tsx
packages/core/admin/admin/src/pages/Auth/components/ForgotPassword.tsx
packages/core/admin/admin/src/pages/Auth/components/Login.tsx
packages/core/admin/admin/src/pages/Auth/components/Register.tsx
packages/core/admin/admin/src/pages/Auth/components/ResetPassword.tsx
packages/core/admin/admin/src/pages/ProfilePage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/CreatePage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/components/RoleForm.tsx
packages/core/admin/admin/src/pages/Settings/pages/Users/components/NewUserForm.tsx
packages/core/admin/admin/src/pages/Settings/pages/Users/utils/validation.ts
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/WebhookForm.tsx
packages/core/content-manager/admin/src/components/ConfigurationForm/EditFieldForm.tsx
packages/core/content-manager/admin/src/hooks/tests/useDocument.test.tsx
packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Repeatable.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx
packages/core/content-manager/admin/src/utils/validation.ts
packages/core/content-releases/admin/src/validation/schemas.ts
packages/core/core/src/services/entity-validator/index.ts
packages/core/review-workflows/admin/src/routes/settings/:id.tsx
packages/plugins/i18n/admin/src/components/CreateLocale.tsx

Fix https://github.com/strapi/strapi/issues/21285
More general fix based on https://github.com/strapi/strapi/pull/21312

fix: cm validation logic is broken

---

templates/website/package.json
templates/website/yarn.lock

website template uses strapi 5
it's using strapi rc
template should be generated with correct dependendies
DX-1620

fix: use strapi v5 for template

---

packages/core/review-workflows/admin/src/routes/settings/:id.tsx
packages/core/review-workflows/admin/src/routes/settings/components/Stages.tsx
packages/core/review-workflows/admin/src/routes/settings/components/WorkflowAttributes.tsx
packages/core/review-workflows/admin/src/routes/settings/components/tests/Stages.test.tsx
packages/core/review-workflows/admin/src/routes/settings/hooks/useReviewWorkflows.ts
packages/core/review-workflows/admin/src/translations/en.json
packages/core/review-workflows/server/src/constants/workflows.ts
packages/core/review-workflows/server/src/content-types/workflow/index.ts
packages/core/review-workflows/server/src/services/workflows.ts
packages/core/review-workflows/server/src/validation/review-workflows.ts
packages/core/review-workflows/shared/contracts/review-workflows.ts
tests/e2e/tests/review-workflows/settings.spec.ts

Adds "Required stage for publishing" to the Review Workflow settings page. This PR **don't** add publishing validation yet. Only is responsible to add the new field to Workflows in both backend/frontend.
Go to an existing workflow or create a new one.
1. Try to set one of the stages as the required one for publishing
2. It should keep the value without problems

feat(review-workflows): adding required stage for publishing

---

.github/workflows/adminBundleSize.yml

- dash should also be stripped
- increase min threshold so minor changes don't trigger it
fix for https://github.com/strapi/strapi/pull/21440 which didn't include dash

fix(tooling): strip dashes and change min threshhold

---

packages/core/content-manager/admin/src/history/components/VersionHeader.tsx
packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx

I changed the color of the subtitle of the Content History page.
It has to be a little less visible as it contains secondary informations.
Open any entry and check its content history.
https://github.com/strapi/strapi/issues/20778

fix: Changed the color of the subtitle

---

.github/workflows/checks.yml
.github/workflows/tests.yml
packages/utils/upgrade/README.md

use new branch setup in checks workflow
to work on v4 branches
CI should work on v4 branches
DX-1641

chore: workflow for v4 branch

---

packages/cli/create-strapi-app/src/utils/template.ts

Fix missing return in the cli template code. When specifying a branch it tried installing both with and with the branch. breaking the process.

fix: template missing return

---

tests/api/core/content-manager/index.test.api.js

updates the content-manager relations tests to work for v5 API formats
they had been disabled
they should pass
DX-1657

test(api): enable relations tests

---

README.md

Hi, I've noticed the Readme.md needs the Strapi 5 link.

Update README.md with Strapi 5

---

packages/core/content-releases/server/src/migrations/database/5.0.0-document-id-in-actions.ts

- check if table exists
- create table if it doesn't exist already
issues described here https://github.com/strapi/strapi/issues/21471
- create a strapi 5 app with mysql or mariadb
- set an EE license key before starting it up the first time
- start up strapi, project should be launched without seeing errors.
#21471 
DX-1651

fix: Create table if it doesn't exist

---

packages/core/content-manager/server/src/controllers/index.ts
packages/core/content-manager/server/src/preview/controllers/index.ts
packages/core/content-manager/server/src/preview/controllers/preview.ts
packages/core/content-manager/server/src/preview/index.ts
packages/core/content-manager/server/src/preview/routes/index.ts
packages/core/content-manager/server/src/preview/routes/preview.ts
packages/core/content-manager/server/src/preview/services/index.ts
packages/core/content-manager/server/src/preview/services/preview.ts
packages/core/content-manager/server/src/preview/utils.ts
packages/core/content-manager/server/src/routes/index.ts
packages/core/content-manager/server/src/services/index.ts

Create basic outline of controllers/services/routes for static preview.
Next PR will introduce the preview config validation

feat: base files for static preview

---

packages/plugins/users-permissions/admin/src/pages/EmailTemplates/tests/schema.test.js
packages/plugins/users-permissions/admin/src/pages/Providers/tests/schema.test.js
packages/plugins/users-permissions/admin/src/pages/Providers/utils/forms.js

- Fixed validation issue for callback and subdomain in providers
- Added unit tests for the email template schema and provider schema
- Fixes issues with validation in the provider, which was causing the subdomain and URL fields to be filled with invalid values
- Log in to Strapi
- Navigate to the Settings > Users & Permissions plugin
- Test the new fixes by filling out the provider section
- Issue #17536
- Pr #21127

fix: validation issues in the Users & Permissions plugin

---

packages/core/core/src/services/cron.ts

v5 equivalent of https://github.com/strapi/strapi/pull/21266
This area of the code has not changed from v4-5 so I was able to cherry pick the commit from that PR here

fix: wrong jobs value after removing a task

---

packages/utils/upgrade/src/modules/error/utils.ts
packages/utils/upgrade/src/modules/format/formats.ts
packages/utils/upgrade/src/modules/upgrader/upgrader.ts
packages/utils/upgrade/src/tasks/upgrade/requirements/major.ts
packages/utils/upgrade/src/tasks/upgrade/upgrade.ts

- Adds a debug log statement to log the application and Strapi versions at the beginning of the upgrade process.
- Includes additional error handling for missing NPM version candidates and corrects minor log typos.
- Display information about the project being already up to date if necessary
QoL improvements.
1. Run the upgrade command with different tasks (`to`, `patch`, `minor`, `major`) in a project with different versions
2. Make sure the logs display correct and informative messages
fix #21750

Upgrade Tool - Enhanced Logging, and Improved Error Handling

---

packages/core/strapi/src/admin.ts
packages/core/strapi/src/types/index.d.ts

added types for @strapi/strapi module
build the strapi project for windows
run: `yarn` && `yarn setup` on windows
https://github.com/strapi/strapi/issues/21628

fix(typescript): declare modules used in @strapi/strapi

---

tests/e2e/tests/content-manager/blocks.spec.ts

Update e2e tests to handle changes made in https://github.com/strapi/strapi/pull/21430
The tests are broken
The tests should pass
https://github.com/strapi/strapi/pull/21430

fix(e2e): update blocks e2e tests

---

packages/core/admin/admin/src/translations/languageNativeNames.ts

Add Uzbek and Romania to the languageNativeNames
To show the language selection options in the Admin panel
Already implemented in v5 https://github.com/strapi/strapi/pull/21910

enhancement: include Uzbek and Romania as language native names

---

packages/core/core/src/services/document-service/utils/populate.ts

Change Media population logic in the document service so webhooks receive full media info
Fixes https://github.com/strapi/strapi/issues/21546

fix: populate media in document service

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/preview/components/PreviewSidePanel.tsx

replace `willOpenPreview` for `willNavigate` event.

feat: will navigate event

---

tests/e2e/tests/i18n/editview.spec.ts

Turn on and adjust the i18n e2e tests
To test stuff
CI tests should pass

chore(e2e): turn on the i18n editview.spec.ts tests

---

packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
tests/e2e/tests/content-manager/editview.spec.ts

Adds command shortcuts that trigger a save on the edit view:
- cmd+enter
- ctrl+enter

enhancement: cmd+enter and ctrl+enter to save entry

---

package.json
packages/plugins/i18n/server/src/services/__tests__/__snapshots__/iso-locales.test.ts.snap

fixes snapshot
for tests to pass

test(unit): fix locales snapshot

---

packages/core/admin/admin/src/translations/en.json
packages/core/admin/admin/src/translations/fr.json
packages/core/upload/admin/src/components/AssetCard/AudioAssetCard.tsx
packages/core/upload/admin/src/components/AssetCard/DocAssetCard.tsx
packages/core/upload/admin/src/components/AssetCard/tests/__snapshots__/DocAssetCard.test.tsx.snap
packages/core/upload/admin/src/components/AssetGridList/tests/__snapshots__/AssetGridList.test.tsx.snap
packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.tsx
packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/PreviewComponents.tsx
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetContent.test.tsx.snap
packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.tsx.snap

fix: cleaner fallback for files preview (22100)

---

tests/api/core/content-manager/api/relations-cross-entity-ordering.test.api.ts

Enables and updates the relations ordering api test
To test the feature

chore(tests): enable and update relations ordering test

---

packages/core/review-workflows/package.json
packages/utils/upgrade/src/modules/codemod-repository/constants.ts
yarn.lock

- Fix wrong dep version breaking validation instance of checks
- Fix invalid resource path after rollup build chunking

fix: issue in 5.10.0

---

package.json
packages/generators/generators/package.json

makes sure we run copy-files during the build:code step

chore: fix build:code not including copy-files step

---

examples/getstarted/config/features.js
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/RelationModal.test.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/Relations.test.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx
packages/core/types/src/modules/features.ts
tests/e2e/app-template/config/features.js
tests/e2e/tests/content-manager/edit-view/collection-type-edit-view.spec.ts
tests/e2e/tests/content-manager/history.spec.ts
tests/e2e/tests/content-manager/relations.spec.ts

Remove the future flag and fix tests
we are using a future branch

feat(relations-on-the-fly): remove future flag

---

docs/docs/docs/01-core/admin/02-permissions/00-intro.mdx
docs/docs/docs/01-core/permissions/00-intro.md
docs/docs/docs/01-core/permissions/01-engine.md
docs/docs/docs/01-core/permissions/_category_.json
docs/package.json
docs/yarn.lock

Add documentation for the `@strapi/permissions` package in the contributor documentation
Improve knowledge sharing and collaboration overall 
Run the contributor documentation and heads to http://localhost:3000/permissions

docs: add strapi/permissions documentation

---

packages/core/core/src/services/document-service/utils/bidirectional-relations.ts
tests/api/core/strapi/api/relations.test.api.ts

Apply this PR to do an hotfix on 5.11

fix: bidirectional relations sync

---

examples/experimental-dev/package.json
packages/core/admin/package.json
packages/core/strapi/package.json
yarn.lock

chore: bump vite from 5.4.13 to 5.4.15

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx

Small tweaks to the relation modal UI based on user feedback:
- move go to entry button into the modal header
- delete modal footer

enhancement: move relation modal expand button and remove footer

---

packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.tsx.snap

fix(upload): update snapshot

---

packages/core/admin/admin/src/tests/reducer.test.ts
packages/core/admin/ee/admin/src/pages/tests/AuthResponse.test.tsx

- Adds some frontend unit test, for login logic in the admin
- Adds some tests for AuthReponse for SSO
- Frontend unit tests should pass

test(admin): add tests for reducer auth actions and Login SSO

---

docs/docs/docs/01-core/openapi/01-technologies.md
packages/cli/cloud/src/login/action.ts
packages/cli/cloud/src/types.ts
packages/cli/create-strapi-app/src/cloud.ts

This PR modifies the Cloud CLI to allow different prompts originating from the Cloud CLI API

chore: update cli cloud

---

packages/core/content-type-builder/server/src/controllers/validation/schema.ts

Fix new CTB not allowing unknown configs in custom fields 
Fix https://github.com/strapi/strapi/issues/23633
Fix CTB issue and get back to previous behavior
Test to use a custom field with option and see they were not persisted, checkout the fix and see they are now persisted

fix: ctb custom field need to allow extra configs

---

packages/core/admin/admin/src/components/UnstableGuidedTour/tests/reducer.test.ts

Update reducer tests 
Other test:ts:front fails
Run yarn test:ts:front should pass

fix: guided tour test types

---

packages/core/admin/admin/src/components/UnstableGuidedTour/tests/reducer.test.ts

Fixes types again 🤦‍♂️ 
yarn test:ts:front throws an error
run yarn test:ts:front all should pass

future: update types in reducer test

---

packages/core/admin/admin/src/components/UnstableGuidedTour/Tours.tsx

- Add the Got It button for all tours
- Adjust when conditions
Designs
Enable the future flag
Look at the designs, do the tour

future: update guided tour got it button and when conditions

---

packages/core/core/src/services/__tests__/session-manager.test.ts
packages/core/core/src/services/session-manager.ts
tests/api/core/admin/session-manager.test.api.ts

fixes deleteMany bug and adds a bunch of api tests

fix: deleteMany in jwt feat

---

.github/workflows/close_stale_issues.yml
.github/workflows/label_stale_issues.yml

Rinse and repeat: updated script to target issues before 2024. 
Then we change strategy 👍

 chore: label and close issues before 2024

---

packages/core/admin/admin/src/components/SubNav.tsx
packages/core/admin/admin/src/pages/Settings/components/SettingsNav.tsx
packages/core/content-manager/admin/src/components/LeftMenu.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/ContentTypeBuilderNav.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.tsx.snap

Fix the scrollbar missing in CTB after working on responsiveness. Unifying by creating a component on SubNav level to avoid making the mistake again.
The scroll is not working anymore on the CTB side nav.
- Go to the Content Type Builder
- Scroll in the left side navigation (if the window is too high, resize it to make the scroll appear)
🚀

fix: scroll in sidenav
