strapi/strapi

- package.json
Add strapi-generate-email and strapi-generate-upload dependencies
> Add strapi-generate-email and strapi-generate-upload dependencies

- lib/configuration/hooks/defaultHooks.js
- lib/configuration/hooks/passport/index.js
passport is now a hook, and is well initialized as a koa middleware.
> passport is now a hook

- lib/configuration/hooks/dashboard/index.js
> Fix dashboard update route

- bin/strapi-link.js
- bin/strapi-new.js
- lib/configuration/hooks/_api/index.js
- lib/configuration/hooks/_config/index.js
@pierreburgy: feel free to merge this breaking change when you are ready on the Dashboard.
> Load config from API and specific environment

- lib/configuration/hooks/dashboard/policies/dashboardToken.js
DashboardToken used in headers
> DashboardToken used in headers

- lib/configuration/hooks/dashboard/config/config.js
- restrict config access
- add `connected` boolean
> Restrict config access

- lib/configuration/hooks/dashboard/index.js
Add addDataCreate and addDataUpdate policies for dashboard routes
> Add addDataCreate and addDataUpdate policies for dashboard routes

- lib/configuration/hooks/router/index.js
Improve router for user permissions
> Improve router for user permissions

- lib/configuration/hooks/studio/index.js
Update path to be compatible with Windows and posix platform. Fixes #55.
> Fix path for Windows

- lib/configuration/hooks/blueprints/actions/add.js
- lib/configuration/hooks/blueprints/actions/findOne.js
Not a big change, but more consistency ;)
> fix function names

- mkdocs.yml
- website/documentation/architecture/logging.md
Since the logging documentation seems to be still valid I added it to the new docs of v2 :)
> added logging documentation from Strapi v1

- packages/strapi-generate-api/templates/mongoose/service.template
- packages/strapi-mongoose/lib/index.js
Fixed service template to add the capital letter and fixed issue that was preventing the usage of mongoose
> Template and mongoose fix

- .gitignore
- packages/strapi-admin/.gitignore
- packages/strapi-bookshelf/.gitignore
- packages/strapi-ejs/.gitignore
- packages/strapi-generate-admin/.gitignore
- packages/strapi-generate-api/.gitignore
- packages/strapi-generate-controller/.gitignore
- packages/strapi-generate-migrations/.gitignore
- packages/strapi-generate-model/.gitignore
- packages/strapi-generate-new/.gitignore
- packages/strapi-generate-plugin/.gitignore
- packages/strapi-generate-policy/.gitignore
- packages/strapi-generate-service/.gitignore
- packages/strapi-generate/.gitignore
- packages/strapi-helper-plugin/.gitignore
- packages/strapi-knex/.gitignore
- packages/strapi-mongoose/.gitignore
- packages/strapi-plugin-content-manager/.gitignore
- packages/strapi-redis/.gitignore
- packages/strapi-utils/.gitignore
- packages/strapi-views/.gitignore
- packages/strapi/.gitignore
- Add `package-lock.json` in `.gitignore` files.
> Add package-lock.json in gitignore files

- bin/strapi-link.js
- bin/strapi-login.js
- bin/strapi-new.js
issue #245 describes the problem this fixes.
> WIP fix #245 dns.lookup on strapi.studio.io in cli

- packages/strapi-plugin-content-type-builder/admin/src/components/Input/index.js
- Fix type number options translations (in "Add New Field modal").
> Fix type number options translations

- packages/strapi-plugin-content-manager/admin/src/components/EditForm/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/Edit/index.js
- Fix number type format issue in content manager.
> Fix number type format issue in content manager

- packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js
> Fix table values display

- packages/strapi-helper-plugin/lib/src/components/Button/index.js
- packages/strapi-helper-plugin/lib/src/components/Button/styles.scss
- packages/strapi-helper-plugin/lib/src/components/PluginHeaderActions/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/Edit/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/List/index.js
- packages/strapi-plugin-settings-manager/admin/src/utils/request.js
- packages/strapi/lib/core/configurations.js
- Improve `Button` component in `strapi-helper-plugin`
- Fix hook load
> Improve button library and fix db connector

- packages/strapi-generate-new/lib/after.js
- Install `settings-manager`, `content-type-builder` and `content-manager` on project creation.
> Install every plugins on project creation

- packages/strapi-plugin-content-type-builder/admin/src/components/InputCheckboxWithNestedInputs/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/attributeValidations.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/sagas.js
Fix attribute params `minLength`and `maxLength` if disabled
> Fix attribute minLength bug

- packages/strapi-knex/lib/index.js
> Don't set schema on MySQL connection

- docs/1.x.x/book.json
- docs/3.x.x/book.json
> Fix edit link

- docs/3.x.x/en/plugins/advanced.md
- docs/3.x.x/en/plugins/ui-components.md
- Fix errors in ui-components code example
> Fix errors in ui-components code examples

- packages/strapi/lib/core/configurations.js
- packages/strapi/lib/middlewares/language/index.js
Fixed https://github.com/strapi/strapi/issues/314
> Ensure server start where there are no locales

- docs/3.x.x/en/README.md
- docs/3.x.x/en/SUMMARY.md
- docs/3.x.x/en/plugins/development.md
- Add authentification guide link in the documentation menu
> Add authentification link in doc menu

- package.json
- packages/strapi-admin/package.json
- packages/strapi-bookshelf/package.json
- packages/strapi-ejs/package.json
- packages/strapi-generate-admin/package.json
- packages/strapi-generate-api/package.json
- packages/strapi-generate-controller/package.json
- packages/strapi-generate-model/package.json
- packages/strapi-generate-new/package.json
- packages/strapi-generate-plugin/package.json
- packages/strapi-generate-policy/package.json
- packages/strapi-generate-service/package.json
- packages/strapi-generate/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-knex/package.json
- packages/strapi-middleware-views/package.json
- packages/strapi-mongoose/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-email/package.json
- packages/strapi-plugin-settings-manager/package.json
- packages/strapi-plugin-users-permissions/package.json
- packages/strapi-redis/package.json
- packages/strapi-utils/package.json
- packages/strapi/package.json
- Change packages version to publish on npm
> 3.0.0-alpha.7.1

- packages/strapi-plugin-settings-manager/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-settings-manager/admin/src/containers/HomePage/sagas.js
- Fix issue https://github.com/strapi/strapi/issues/371
> Fix stm add language bug

- packages/strapi-plugin-content-manager/admin/src/containers/Edit/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/List/index.js
- Bugs
- Fix back button in content manager Edit view
- Redirect user to HomePage after editing an entry
> Fix ctm editview backheader

- packages/strapi-generate-api/templates/mongoose/service.template
🐛 Bug Fix
- Fix findOne service available where params (https://github.com/strapi/strapi/issues/395)
> Fix filter findOne params

- packages/strapi-plugin-users-permissions/admin/src/components/InputSearch/index.js
- Fix user associated with a role display
> Fix EditRole page InputSearch label number display

- packages/strapi-helper-plugin/lib/src/utils/request.js
Change redirect route if `jwtToken` is expired with `strapi.remoteURL`
> Fix redirect route

- package.json
- packages/strapi-admin/package.json
- packages/strapi-bookshelf/package.json
- packages/strapi-ejs/package.json
- packages/strapi-generate-admin/package.json
- packages/strapi-generate-api/package.json
- packages/strapi-generate-controller/package.json
- packages/strapi-generate-model/package.json
- packages/strapi-generate-new/package.json
- packages/strapi-generate-plugin/package.json
- packages/strapi-generate-policy/package.json
- packages/strapi-generate-service/package.json
- packages/strapi-generate/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-knex/package.json
- packages/strapi-middleware-views/package.json
- packages/strapi-mongoose/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-email/package.json
- packages/strapi-plugin-settings-manager/package.json
- packages/strapi-plugin-users-permissions/package.json
- packages/strapi-redis/package.json
- packages/strapi-utils/package.json
- packages/strapi/package.json
* [Plugin] Add endpoint to fetch authenticated user model (https://github.com/strapi/strapi/pull/435)
* [Framework] Create form to set database connection on strapi new (https://github.com/strapi/strapi/pull/420)
* [Framework] Fix yarn (https://github.com/strapi/strapi/pull/422)
* [Admin] Fix user associated with a role display (https://github.com/strapi/strapi/pull/427)
* [Framework] Authorize config files name as API (https://github.com/strapi/strapi/pull/428)
* [Framework] Fix deployment process (https://github.com/strapi/strapi/pull/431)
* [Plugin] Fix bug when trying to install a new plugin (https://github.com/strapi/strapi/pull/448)
* [Framework] SSL option for strapi-knex connections (https://github.com/strapi/strapi/pull/424)
* [Framework] Support one-way relationship …
> 3.0.0-alpha.8

- packages/strapi-generate-new/lib/before.js
I maked a condition to launch the correct command on windows.
fix to this issue : https://github.com/strapi/strapi/issues/468
> Fix package 'strapi-generate-new' on Windows

- .github/ISSUE_TEMPLATE.md
💅 Enhancement
Felt like we needed some structure for issues..
> Improve template issue github

- docs/3.x.x/en/advanced/middlewares.md
noticed the defaults object was not being merged with the config, as a work around I've added the settings manually
> moved config out of middleware and into app config

- docs/3.x.x/en/SUMMARY.md
- docs/3.x.x/en/migration/migration-guide-alpha-8-to-alpha-9.md
> Create migration guide from alpha.8 to alpha.9

- package.json
- packages/strapi-admin/package.json
- packages/strapi-bookshelf/package.json
- packages/strapi-ejs/package.json
- packages/strapi-generate-admin/package.json
- packages/strapi-generate-api/package.json
- packages/strapi-generate-controller/package.json
- packages/strapi-generate-model/package.json
- packages/strapi-generate-new/lib/after.js
- packages/strapi-generate-new/package.json
- packages/strapi-generate-plugin/package.json
- packages/strapi-generate-policy/package.json
- packages/strapi-generate-service/package.json
- packages/strapi-generate/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-knex/package.json
- packages/strapi-middleware-views/package.json
- packages/strapi-mongoose/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-email/package.json
- packages/strapi-plugin-settings-manager/package.json
- packages/strapi-plugin-users-permissions/package.json
- packages/strapi-redis/package.json
- packages/strapi-utils/package.json
- packages/strapi/package.json
💅 Enhancement
- Handle no core plugins installation on strapi new
> Install analytics plugin by default on strapi new project

- packages/strapi-plugin-users-permissions/config/policies/permissions.js
- packages/strapi-plugin-users-permissions/services/Jwt.js
Motivation: Seperation of concerns.
I want to use the JWT service in my own plugin.
> Moved user validation logic from Jwt service to permissions policy

- docs/3.x.x/en/plugin-development/ui-components.md
- packages/strapi-helper-plugin/lib/src/components/InputAddon/index.js
- packages/strapi-helper-plugin/lib/src/components/InputAddon/styles.scss
- packages/strapi-helper-plugin/lib/src/components/InputAddonWithErrors/index.js
- packages/strapi-helper-plugin/lib/src/components/InputAddonWithErrors/styles.scss
- packages/strapi-helper-plugin/lib/src/components/InputsIndex/index.js
Created `InputAddon`and `InputAddonWithErrors`components.
Created documentation accordingly
> Created InputAddon and InputAddonWithErrors

- packages/strapi-helper-plugin/lib/src/components/Input/index.js
- packages/strapi-helper-plugin/lib/src/components/InputPassword/index.js
- packages/strapi-helper-plugin/lib/src/components/InputsIndex/index.js
- packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js
Disable autocomplete in login form.
Ensure the new input library only renders controlled components
> Remove autoComplete on password field

- packages/strapi-bookshelf/lib/utils/connectivity.js
> Remove user key from generated databases.json file

- packages/strapi-generate-new/lib/before.js
> Hide password database cli

- packages/strapi-plugin-users-permissions/controllers/Auth.js
Just set user id in auth jwt
fix #528
> Update user info in JWT

- packages/strapi-generate-api/templates/mongoose/controller.template
Verify if _id params has mongoose ObjectId format
> Fix fetch error mongoose

- README.md
- Add Heroku deploy button in README.md
> Add Heroku deploy button in README.md

- README.md
Move Heroku button in README.md
> Move Heroku button in README.md

- packages/strapi-helper-plugin/lib/src/components/InputPassword/styles.scss
- packages/strapi-helper-plugin/lib/src/components/InputPasswordWithErrors/index.js
- packages/strapi-plugin-users-permissions/admin/src/containers/HomePage/saga.js
- packages/strapi-plugin-users-permissions/admin/src/translations/en.json
- packages/strapi-plugin-users-permissions/admin/src/translations/fr.json
- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
- packages/strapi-plugin-users-permissions/controllers/Auth.js
- packages/strapi-plugin-users-permissions/controllers/User.js
- packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
- packages/strapi-plugin-users-permissions/services/Providers.js
> Fix config user and front things

- packages/strapi-plugin-users-permissions/services/Providers.js
Co-authored-by: soupette <cyril.lpz@gmail.com>
> Hot fix provider login

- packages/strapi/lib/core/store.js
> Fix logs table creation

- packages/strapi-generate-new/lib/index.js
> fix(generate-new): prevent delete the node_modules dir

- packages/strapi-plugin-users-permissions/admin/src/containers/HomePage/checkFormValidity.js
- packages/strapi-plugin-users-permissions/admin/src/containers/HomePage/index.js
It's actually impossible to switch off then on email provider
> Fix update email provider

- packages/strapi-plugin-content-manager/admin/src/translations/en.json
Helps clarify what the button actually does. Otherwise it seems like nothing is happening.
> Renaming 'Cancel' to 'Reset'

- docs/3.x.x/en/concepts/concepts.md
- docs/3.x.x/en/guides/authentication.md
- docs/3.x.x/en/guides/models.md
Hey Guys, I did some minor improvements to english sentences. Please accept.
**Important**: at the beginning of the model section, I added a note to point new devs to start with the admin interface, this seems simple but not obvious. This helped me a lot at the beginning, since the admin interface is asserting many things right away.
**Question**: since the model and controller generators do not work and wont be fixed soon, as you said yourself, how about we clean up the doc just to be with generate:api?
> Some minor doc improvements on english level

- packages/strapi-plugin-upload/admin/src/components/Li/index.js
- packages/strapi-plugin-upload/admin/src/components/PluginInputFile/index.js
The issue was due to the ref I was using
> Fix upload plugin build

- packages/strapi-admin/admin/src/translations/zh.json
- packages/strapi-plugin-content-manager/admin/src/translations/zh.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/zh.json
- packages/strapi-plugin-settings-manager/admin/src/translations/zh.json
> add some chinese translation fix

- packages/strapi-helper-plugin/lib/src/components/InputSearch/styles.scss
- packages/strapi-helper-plugin/lib/src/components/InputSelectWithErrors/index.js
- packages/strapi-plugin-content-manager/admin/src/utils/formValidations.js
- packages/strapi-plugin-upload/admin/src/components/Li/styles.scss
- packages/strapi-plugin-upload/admin/src/translations/en.json
- Fix ctm formValidations
- Fix InputSearch focus transition
- Add a logic in the Inputselect that automatically selects the first option if the value is required and initially empty
- Fix upload translation
> Fix upload front

- docs/3.x.x/en/cli/CLI.md
Please see for more information: https://github.com/strapi/strapi/issues/732
> Changed syntax for strapi new database arguments

- docs/3.x.x/en/guides/models.md
- packages/strapi-generate-api/templates/bookshelf/model.template
- packages/strapi-generate-api/templates/mongoose/model.template
- Update the docs for model in bookshelf (indent + remove useless line)
- Fix typo in model.template for mongoose
- Fix type in model.template for bookshel + change to async function (as with mongoose template)
> Update model.template for generate api

- packages/strapi-helper-plugin/lib/src/components/Wysiwyg/componentsStyles.scss
- packages/strapi-helper-plugin/lib/src/components/Wysiwyg/constants.js
- packages/strapi-helper-plugin/lib/src/components/Wysiwyg/index.js
- packages/strapi-helper-plugin/lib/src/components/Wysiwyg/styles.scss
- packages/strapi-helper-plugin/lib/src/components/Wysiwyg/utils.js
- packages/strapi-helper-plugin/package.json
- Fix bug when hitting space key on a new empty line (it was due to the `pre-line` css property)
- Add tab behavior
> Fix spaces & tab bug

- .github/ISSUE_TEMPLATE.md
Add a new section in the issue template
> Add suggested solutions in issue template

- packages/strapi-generate-new/files/config/environments/development/server.json
- packages/strapi-generate-new/files/config/environments/production/server.json
- packages/strapi-generate-new/files/config/environments/staging/server.json
> Replace server host by localhost

- package.json
- packages/strapi-admin/package.json
- packages/strapi-bookshelf/package.json
- packages/strapi-ejs/package.json
- packages/strapi-generate-admin/package.json
- packages/strapi-generate-api/package.json
- packages/strapi-generate-controller/package.json
- packages/strapi-generate-model/package.json
- packages/strapi-generate-new/package.json
- packages/strapi-generate-plugin/package.json
- packages/strapi-generate-policy/package.json
- packages/strapi-generate-service/package.json
- packages/strapi-generate/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-knex/package.json
- packages/strapi-middleware-views/package.json
- packages/strapi-mongoose/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-email/package.json
- packages/strapi-plugin-settings-manager/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-users-permissions/package.json
- packages/strapi-redis/package.json
- packages/strapi-upload-aws-s3/package.json
- packages/strapi-upload-cloudinary/package.json
- packages/strapi-upload-local/package.json
- packages/strapi-utils/package.json
- packages/strapi/package.json
> 3.0.0-alpha.11.3

- packages/strapi-generate-new/files/config/environments/staging/request.json
Feel free to close the PR if you are not okay with have the same config.
> Staging config as production config

- packages/strapi-admin/controllers/Admin.js
> Fix exec command when the path has spaces

- packages/strapi-generate-new/lib/after.js
Fix https://github.com/strapi/strapi/issues/971
> Fix symlinks during project generation

- packages/strapi-generate-new/files/config/environments/production/security.json
- packages/strapi-generate-new/files/config/environments/staging/security.json
> Disable CSRF in production & harmonize allowed headers

- packages/strapi-plugin-graphql/services/GraphQL.js
Fix https://github.com/strapi/strapi/issues/976
> Snakecase attribute in GraphQL when there is a dash

- packages/strapi-bookshelf/lib/index.js
- packages/strapi-generate-api/templates/mongoose/service.template
- packages/strapi-mongoose/lib/index.js
> Update Mongoose template & support one-way in generated API

- docs/3.x.x/en/README.md
> Update v12 Readme.md

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
My PR is a:
🐛 Bug fix
GitHub
Fix the issue templates with the right names.
> Fix the issue templates

- package.json
Add prettier to `pre-commit`hook
My PR is a:
💅 Enhancement
Framework
> Add prettier to `pre-commit` hook

- packages/strapi-bookshelf/lib/index.js
My PR is a:
💅 Enhancement
Framework
Added a case for strapi bookshelf to create a varchar(255) column for enumeration values, inline to match how string columns are made.
> Update Strapi-Bookshelf to create enumeration columns

- packages/strapi-admin/controllers/Admin.js
My PR is a:
💅 Enhancement
Admin
Corrected spelling of "occurred"
> Fix spelling

- packages/strapi-generate-api/templates/bookshelf/controller.template
- packages/strapi-generate-api/templates/bookshelf/service.template
My PR is an: 💅 Enhancement 
Adds count function to bookshelf controller and service templates. Fixes #1303
> Added count to api template for bookshelf

- packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/setAttribute.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/actions.js
My PR is a:
🐛 Bug fix
Plugin
Fix bug when creating 1-N relation with the same content type
> Fixes 1-N relations with the same content type

- packages/strapi-bookshelf/lib/index.js
- packages/strapi-knex/lib/index.js
My PR is a: 🐛 Bug fix
Fix #1273 issue, decimal are received as string on pg and mysql decimal are stored as integer.
> Fix decimal on pg and mysql

- packages/strapi-helper-plugin/lib/src/app.js
My PR is a: 🐛 Bug fix -->
Main update on the:  Admin
> Fix build assets url

- packages/strapi-plugin-graphql/package.json
My PR is a:
🐛 Bug fix
Plugin
A little change to update the minimal version of the Playground to fix a bug with the history.
Thanks @Huvik for the help 👍
> Upgrade version to fix history bug on GraphQL Playground

- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
My PR is a:
💅 Enhancement
Admin
Remove the settings-manager from the plugins section and move it to the configuration one.
> Move settings-manager to configuration section

- .travis.yml
My PR is a:
💅 Enhancement
Test against current LTS and stable releases of Node.js.
> chore: test against Node.js 9 and 10

- packages/strapi-plugin-users-permissions/controllers/User.js
- packages/strapi-plugin-users-permissions/services/Providers.js
Main update on the:  Plugin
This issue fix default role apply to provider login. And set default role when user are create via the user API or via the content manager.
Related issue: https://github.com/strapi/strapi/issues/1212
> Fix default role provider and for create user

- packages/strapi-bookshelf/lib/index.js
My PR is a:
🐛 Bug fix
Framework
Added a case to allow creation of oneWay columns.
> Add oneWay relation type to Bookshelf

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- CONTRIBUTING.md
> Update contributing guide

- docs/3.x.x/en/guides/authentication.md
My PR is a:  💅 Enhancement
Add examples links in the "Authentication with providers" section
> Add examples in the "Authentication with providers" section

- docs/3.x.x/en/advanced/customize-admin.md
My PR is a:
🐛 Bug fix
Documentation
Fix `CONTRIBUTING.md` file  path
> Fix `CONTRIBUTING.md` path

- packages/strapi-plugin-users-permissions/models/Permission.settings.json
> Fix empty string not require for policy

- docs/3.x.x/en/plugin-development/frontend-use-cases.md
My PR is a:
💅 Enhancement
Documentation
Fixes the incorrect sample code for import of utils/request in the documentation
> Fixed incorrect import for utils/request

- packages/strapi-generate-api/templates/bookshelf/controller.template
- packages/strapi-generate-api/templates/bookshelf/service.template
- packages/strapi-generate-api/templates/mongoose/controller.template
- packages/strapi-generate-api/templates/mongoose/service.template
- packages/strapi-generate/lib/helpers/template/index.js
My PR is a: 🚀 New feature
Main update on the:  Framework 
Let you search in your content via API.
We add new filter `_q` : https://my.api.com/article?_q=searchTerm
Fix #1177
> Add search in generated API

- packages/strapi-admin/admin/src/translations/ko.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/ko.json
- packages/strapi-plugin-users-permissions/admin/src/translations/ko.json
My PR is a:
💅 Enhancement
* Admin
* Plugin
Corrected the found typos.
> Fixed typos in Korean language

- packages/strapi-generate-new/lib/before.js
- packages/strapi-utils/lib/packageManager.js
My PR is a:
🐛 Bug fix
Framework
Fix logic detecting installation with Yarn and the creation of the temporary directory when this is the case.
Also, fix minor linter errors.
related #1548 & #1463
> Fix temp directory reference for Yarn

- docs/3.x.x/en/guides/email.md
- docs/3.x.x/en/guides/upload.md
My PR is a: Documentation update
I spent a minute trying to find the /admin/plugins/email/configurations/development path in my folder structure before figuring out it's meant for the web browser.
> Clarified path for plugins providers configs

- packages/strapi-plugin-upload/services/Upload.js
Main update on the:  Plugin
Related issue #1459
> Fix delete uploaded file SQL

- packages/strapi-hook-bookshelf/lib/relations.js
My PR is a: 🐛 Bug fix
Related issue: #1461
> Fix udpate file SQL via content manager

- docs/3.x.x/en/README.md
> updated version from  alpha 12 to 13 

- packages/strapi-plugin-content-manager/admin/src/translations/ko.json
My PR is a:
💅 Enhancement
Documentation
I hope you all doing well. I added translation of some missing keys noted on this issue: https://github.com/strapi/strapi/issues/1631
In addition to this, just a little bit of grammatical fixes.
I tried to make it as identical as possible to English version, but maybe there are some missing parts.
Also, I asked @KOZ39 to review the translation so that he will leave a comment if he found any typos or missing stuff.
> Update KO translations

- docs/3.x.x/en/guides/policies.md
My PR is a:
💅 Enhancement
Documentation
> Update sessions documentation - access auth user data

- test/start.js
> Fix JSDOM jest tests

- packages/strapi-plugin-content-manager/package.json
> Add missing pluralize dependency

- packages/strapi-helper-plugin/lib/src/components/InputToggle/index.js
My PR is a:
🐛 Bug fix
Framework
Fix input toggle ON/OFF
> Fix input toggle true false

- packages/strapi-helper-plugin/lib/src/utils/inputsValidations.js
My PR is a:
🐛 Bug fix 
Plugin 
If textarea is emty that value is null. But in validation checked length property. App is crashed with message "null is not have length property"
> Add check for length property may not exist

- docs/3.x.x/en/guides/authentication.md
Related to: https://github.com/strapi/strapi/issues/891
My PR is a:
💅 Enhancement
Documentation
Document how to add a new auth provider.
> Document how to add a new auth provider

- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
My PR is a:
💅 Enhancement
Plugin
Per @lauriejim https://github.com/strapi/strapi/commit/e8b7bd478a62462addc3247404c8a7d80d79dae2#r30299789
Updating the English on the template response
> Update register email template

- docs/3.x.x/en/README.md
My PR is a:  💅 Enhancement
Main update on the:  Documentation
> Update alpha.14 in doc

- packages/strapi-plugin-content-type-builder/admin/src/containers/Form/forms.json
My PR is a:
🐛 Bug fix
Content-Type-Builder-Plugin
This PR fixes the issue references here: #1848
> Add validation for attribute name of enumeration field

- packages/strapi-generate-new/lib/before.js
My PR is a:
💅 Enhancement
Framework
It is a tiny and proposal pull request. Please give me some advice 🙏
I added a default value to auth DB in generating new app.
I think most users use "admin" DB as an auth DB.
But it may cause confusion to the user unfamiliar for Mongo DB if we don't offer a default value.
So I think it is more good for user experience that suggesting it as a default value.
> Improve user experience when generating new app

- packages/strapi-plugin-users-permissions/controllers/Auth.js
> Fix unique_email with providers

- packages/strapi-plugin-content-manager/admin/src/containers/ListPage/saga.js
My PR is a:
🐛 Bug fix
Plugin
* mark two or more entries on any type
* click "remove all 2 entries"
* success notification not display
> Add notification for delete all types

- packages/strapi-helper-plugin/lib/src/components/ImgPreview/index.js
- packages/strapi-helper-plugin/lib/src/components/InputFileWithErrors/index.js
My PR is a:
🐛 Bug fix
Plugin
Reproduce bug:
* attach pdf file to any type
* click on "reset"
* confirm action
* Pdf icon still display
> Reset image preview - clear label and icon preview

- packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
Main update on the:  Framework
Related issue #1579
> Fix saved date format content manager

- packages/strapi/lib/core/plugins.js
My PR is a:
🐛 Bug fix
Plugin
This PR make sure that the plugins without an admin (no `containers/App`) are not registered.
> Fixes #1938

- packages/strapi-utils/lib/models.js
My PR is a:
🐛 Bug fix of #1484 
strapi-utils package
Update isNumeric function in strapi-utils in order to make filter request working on nested GraphQL object
> Fix nested objects returns null in GraphQL

- packages/strapi-plugin-email/controllers/Email.js
Main update on the: Plugin (Email)
Fix #1858 issue. Incorrect service reference.
> Fix send email service

- scripts/lint.js
My PR is a:
💅 Enhancement
Plugin
Just seen the opportunity of reduce repeated code 🤷‍♂️
Note: Possibly the noise can be reduced if the dependency is managed on the repository (the main `package.json` file) instead of a package.
> Refactor eslint commands

- packages/strapi-admin/admin/src/translations/es.json
close #1621
My PR is a:
💅 Enhancement
Framework
> Add missing keys in ES translation

- docs/3.x.x/advanced/hooks.md
My PR is a:  💅 Enhancement
Main update on the:  Documentation
The way to active a hook was not in the doc so I added it.
I also update the **structure** section to made it clearer. Distinction between **node_modules** and **custom** hook structure.
> Update hook documentation

- README.md
> Add roadmap section to the readme

- docs/3.x.x/getting-started/quick-start.md
change "your using" to "you're using"
My PR is a:
💅 Enhancement
Documentation
> Fix typo getting started

- docs/3.x.x/cli/CLI.md
> Fix typo on CLI.md

- docs/1.x.x/users.md
Change "his/he" when referring to a user to "their/they"
My PR is a:
💅 Enhancement 
Documentation
> Gender neutral terms

- docs/3.x.x/guides/models.md
My PR is an:
💅 Enhancement 
Documentation
A modification to a note about model keys to improve sentence syntax.
> Rephrase "NoSQL databases only" models note

- packages/strapi-admin/admin/src/components/FullStory/index.js
- packages/strapi-admin/admin/src/containers/AdminPage/index.js
- packages/strapi-admin/admin/src/containers/AdminPage/reducer.js
- packages/strapi-admin/admin/src/containers/AdminPage/saga.js
- packages/strapi-admin/admin/src/containers/App/index.js
- packages/strapi-admin/controllers/Admin.js
- packages/strapi-admin/doc/disable-tracking.md
My PR is a:  💅 Enhancement
Main update on the: Admin
I've just created a new React component called `FullStory` which is injected at the root of the admin app. It allows us to use [FullStory.com](fullstory.com). We're using it only for product enhancement purpose. We're compliant with the GDPR and FullStory as well. We don't retrieve or record critical information. It means that all the inputs in the Content Manager are excluded like the password inputs are already excluded by FullStory (see [more](https://help.fullstory.com/technical-questions/exclude-elements)).
You can easily disable it and the others tools we use to improve the experience by removing the `uuid` field in the `package.json` file at the root of the project.
> Add fullstory

- packages/strapi-plugin-users-permissions/package.json
My PR is a:
🐛 Bug fix
Plugin
Fixes #2338
> Update grant-koa version

- packages/strapi-hook-bookshelf/lib/relations.js
- packages/strapi-plugin-users-permissions/services/Providers.js
My PR is a:
On bookshelf the query to find user during provider auth received bad params format.
> Fix bookshelf query params fetch data

- docs/3.x.x/getting-started/quick-start.md
My PR is a:
- [✓] 💅 Enhancement
- [✓] Documentation
> Fix typos/grammar in quick-start.md

- packages/strapi-plugin-upload/models/File.settings.json
- packages/strapi-provider-upload-cloudinary/README.md
- packages/strapi-provider-upload-cloudinary/lib/index.js
My PR is a:
Fixes Cloudinary upload plugin "delete" method and install steps added to the README.
Closes #2005
> Fixes Cloudinary upload plugin "delete"

- docs/3.x.x/guides/api-documentation.md
- packages/strapi-plugin-users-permissions/documentation/1.0.0/overrides/users-permissions-User.json
My PR is a:
Please merge this first before you merge the following PR: https://github.com/strapi/strapi/pull/2442
This PR is only an addition to @soupette 's branch to help with changes and vuepress doc updates
> Plugin Documentation Part 2

- .travis.yml
My PR is a:
I remove `snyk` from Travis test.
Follow this issue https://github.com/travis-ci/travis-ci/issues/1946
> Remove snyk from Travis

- docs/3.x.x/guides/i18n.md
> Fix anchor in link from i18n guide to concepts

- docs/3.x.x/advanced/middlewares.md
My PR is a:
Make the example clearer to how enable middleware.
> Update middleware documentation enable

- docs/3.x.x/concepts/concepts.md
> Fix a typo in concepts documentation

- LICENSE.md
- README.md
- packages/strapi-admin/LICENSE.md
- packages/strapi-generate-admin/LICENSE.md
- packages/strapi-generate-api/LICENSE.md
- packages/strapi-generate-controller/LICENSE.md
- packages/strapi-generate-model/LICENSE.md
- packages/strapi-generate-new/LICENSE.md
- packages/strapi-generate-plugin/LICENSE.md
- packages/strapi-generate-policy/LICENSE.md
- packages/strapi-generate-service/LICENSE.md
- packages/strapi-hook-bookshelf/LICENSE.md
- packages/strapi-hook-ejs/LICENSE.md
- packages/strapi-hook-knex/LICENSE.md
- packages/strapi-hook-mongoose/LICENSE.md
- packages/strapi-hook-redis/LICENSE.md
- packages/strapi-middleware-views/LICENSE.md
- packages/strapi-provider-email-amazon-ses/LICENSE.md
- packages/strapi-provider-email-mailgun/LICENSE.md
- packages/strapi-provider-email-sendgrid/LICENSE.md
- packages/strapi-provider-email-sendmail/LICENSE.md
- packages/strapi-provider-upload-aws-s3/LICENSE.md
- packages/strapi-provider-upload-local/LICENSE.md
- packages/strapi-provider-upload-rackspace/LICENSE.md
- packages/strapi-utils/LICENSE.md
- packages/strapi/LICENSE.md
Update all `2018` reference to `2019`
And have a Happy New Year all Strapi community!
> Update to 2019

- docs/3.x.x/getting-started/quick-start.md
My PR is a:
An update for documentation based on #1281, The problem should be clearly mentioned, also see [this comment](https://github.com/strapi/strapi/issues/1444#issuecomment-414317406)
> Update quick start documentation

- docs/3.x.x/guides/models.md
My PR is a:
I saw many question about adding/update relations via generated APIs.
Si I add few examples with vanilla JS code block.
Hope it will help to understand how it works.
> Add JS query example in relation documentation

- CONTRIBUTING.md
Trying to carry out the steps here in fish shell will result in the symlinks being incorrectly interpreted by Strapi at run time. Added a message here to make sure fish shell users don't spend a bunch of time trying to debug their setup (as I did).
My PR is a:
> Add note for fish shell users

- packages/strapi-plugin-documentation/admin/src/assets/images/logo.svg
My PR is a:
I've just added an SVG logo to the Documentation plugin.
> Add logo to documentation plugin

- docs/3.x.x/migration-guide/migration-guide-alpha.10-to-alpha.11.md
- docs/3.x.x/migration-guide/migration-guide-alpha.11-to-alpha.12.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.1-to-alpha.12.2.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.2-to-alpha.12.3.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.3-to-alpha.12.4.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.4-to-alpha.12.5.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.5-to-alpha.12.6.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.6-to-alpha.12.7.md
- docs/3.x.x/migration-guide/migration-guide-alpha.12.7-to-alpha.13.md
- docs/3.x.x/migration-guide/migration-guide-alpha.13-to-alpha.13.1.md
- docs/3.x.x/migration-guide/migration-guide-alpha.13.1-to-alpha.14.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14-to-alpha.14.1.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14.1-to-alpha.14.2.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14.2-to-alpha.14.3.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14.3-to-alpha.14.4.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14.4-to-alpha.14.5.md
- docs/3.x.x/migration-guide/migration-guide-alpha.14.5-to-alpha.15.md
- docs/3.x.x/migration-guide/migration-guide-alpha.15-to-alpha.16.md
- docs/3.x.x/migration-guide/migration-guide-alpha.16-to-alpha.17.md
- docs/3.x.x/migration-guide/migration-guide-alpha.17-to-alpha.18.md
- docs/3.x.x/migration-guide/migration-guide-alpha.8-to-alpha.9.md
- docs/3.x.x/migration-guide/migration-guide-alpha.9-to-alpha.10.md
- packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/saga.js
Just adding migration of `jwt.json` file in migration guide.
Was not critical if you never did it. It just broke existing jwt token you generate before the migration of you Strapi application.
> Add migration of jwt.json file

- packages/strapi-generate-api/json/routes.json.js
- packages/strapi-generate-api/templates/bookshelf/controller.template
We remove services to manage relations but forgot to remove routes and controller. So we fix it.
Here is the documentation to manage relations https://strapi.io/documentation/3.x.x/guides/models.html#relations
> Remove relations route from bookshelf template

- docs/3.x.x/guides/filters.md
My PR is a:
Fixed small grammatical error in the documentation
> Small grammatical fix

- packages/strapi-plugin-users-permissions/config/routes.json
My PR is a:
The issue is coming from a route that is missing in the `users-permissions` plugin. Adding it back fixes the problem. 😉
Fixes #2555
> Fix Create new role bug related to permissions missing

- docs/3.x.x/guides/deployment.md
Deployment guide enhanced for helpful hint for production environment setup.
My PR is a:
> Update deployment guide with helpful hint

- packages/strapi-generate-new/files/config/environments/production/server.json
- packages/strapi-generate-new/files/config/environments/staging/server.json
- packages/strapi-plugin-graphql/services/Schema.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
- packages/strapi/lib/core/plugins.js
> Avoid write files if not development environment

- .github/PULL_REQUEST_TEMPLATE.md
My PR is a:
Adds a check on if the PR has been tested with all 3 core databases before merging. As all new features should be confirmed working on both bookshelf and mongoose.
> Update PR Template with database testing checks

- packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
- packages/strapi-admin/admin/src/components/LeftMenuFooter/messages.json
- packages/strapi-admin/admin/src/components/LeftMenuFooter/styles.scss
- packages/strapi-admin/admin/src/components/LeftMenuLink/index.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/styles.scss
- packages/strapi-admin/admin/src/containers/AdminPage/index.js
- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-admin/admin/src/translations/fr.json
My PR is a:
Add Documentation and Help links in left menu:
> Add Documentation and Help links

- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
- packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Just added a few more events to enhance the product.
> Complete funnel

- docs/3.x.x/guides/filters.md
- [ x] Documentation
Hello, just simple documentation update. adding query _in example (since I can't find it anywhere)
> Add _in array query example

- packages/strapi-generate-new/json/database.json.js
I don't know why coma was eject!
> Hot fix database host

- packages/strapi-provider-upload-aws-s3/lib/index.js
Add eu-north-1 (Stockholm) as selectable region
> Added missing region eu-north-1 (Stockholm) to AWS S3 upload

- packages/strapi-generate-new/lib/after.js
- packages/strapi-generate-new/lib/before.js
- packages/strapi-generate-new/lib/success.js
- packages/strapi/lib/utils/success.js
- packages/strapi/package.json
I added a new event to improve product installation in the future.
> Add new installation event

- packages/strapi-generate-new/json/database.json.js
> Hotfix database name variable

- packages/strapi-hook-bookshelf/lib/utils/connectivity.js
After the SQLite PR was merge it was not able to create project using mysql and postgres.
> Fix mysql and pg test connection

- packages/strapi-generate-new/lib/before.js
After adding quickstart option we break the skip form for arguments usage.
> Fix type form if command line config for tests

- README.md
- [] Documentation
I changed the URL of the Getting Started to redirect to the right page in the readme.
> Getting Started URL change

- packages/strapi-generate-new/json/database.json.js
I have found them in the git diff during an update to the new version.
I have found them in the git diff during an update to the new version.
> Remove unneeded whitespaces

- packages/strapi-generate-new/lib/success.js
- packages/strapi-generate-new/package.json
The PR title speaks to itself.
> Associate machine id to user

- packages/strapi-generate-new/lib/after.js
- packages/strapi-generate-new/lib/success.js
Add errors events during the project generation
> Add error events during project generation

- packages/strapi/bin/strapi-new.js
Catch errors during the process generation
> Catch errors during the process generation

- packages/strapi-plugin-graphql/services/Query.js
Fix findOne query for GraphQL. Related to #2771.
> Fix findOne query for GraphQL

- packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js
> Fix plugin id content manager build

- packages/strapi-admin/scripts/preSetup.js
> Fix typo in admin generation cli.

- .github/PULL_REQUEST_TEMPLATE.md
Add SQLite to PR template for testing
> Add SQLite to PR Template

- packages/strapi-plugin-users-permissions/config/queries/mongoose.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
The count value of users per role was wrong on SQL database due to wrong count function on users and permission plugin.
> Fix user count per role on SQL database

- docs/3.x.x/getting-started/installation.md
Corrected a minor grammar issue that didn't quite make sense regarding having access to the Strapi command line commands once Strapi has been installed.
> Updated minor grammar defect on  Installation documentation

- packages/strapi-plugin-email/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/functions/bootstrap.js
Know you can install provider from a npm organisation.
This fix #2723 issue.
> Manage email and upload providers from an npm organisation

- packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
- packages/strapi/lib/utils/index.js
Send the events in a more synchronous way to restart when the events have been sent.
> Fix events in content type builder

- packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
Revert synchronous way of sending events in the CTB.
> Remove synchronous way of sending event

- README.md
Small update to the ReadMe to clarify that github issues should only be used for bug reports and feature requests. Questions and such should be directed towards other channels
> Update README to remove confusion on GitHub issues

- docs/3.x.x/guides/filters.md
- packages/strapi-hook-mongoose/lib/utils/index.js
- packages/strapi-plugin-graphql/services/Aggregator.js
Fixes for some of the PR Feedback on: https://github.com/strapi/strapi/pull/2961
> Deep Filtering PR Feedback

- packages/strapi-helper-plugin/package.json
- packages/strapi-plugin-content-type-builder/admin/src/components/TableListRow/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/App/actions.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/App/reducer.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/reducer.test.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/App/tests/saga.test.js
Draft-js was broken due to the update of the Immutable package.
This PR fixes this bug
> Fix CTB feedback

- docs/3.x.x/guides/deployment.md
Add `.gitignore` step in Heroku tutorial to prevent issues during deployment.
> Add gitignore step in Heroku tutorial

- README.md
Remove hiring banner from readme
> Remove hiring banner from readme

- docs/3.x.x/guides/deployment.md
There we three sections of content that is planned labelled "TBD".  I removed the "TBD" as it created a bad impression. We will update each section as the content is written and published.
> Removed empty "TBD" sections from deployment.md

- packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ModelForm/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
This PR fixes the redirect in the new content type builder when the user is renaming a CT.
> Fix redirect when editing a model

- packages/strapi-plugin-graphql/services/Loaders.js
Fix Issue with graphql loaders doing to much optimization.
> Fix issue with graphql loaders

- packages/strapi-hook-bookshelf/lib/relations.js
- packages/strapi-hook-mongoose/lib/relations.js
> Fix one to many update

- package.json
- packages/strapi-hook-bookshelf/lib/buildQuery.js
- packages/strapi-hook-bookshelf/lib/index.js
- packages/strapi-plugin-users-permissions/models/User.settings.json
- test/e2e.js
Fix join when model are on different datatabases.
> Fix join multi database

- packages/strapi-utils/lib/buildQuery.js
> Cast non nil values and not only truthy ones

- packages/strapi-hook-mongoose/lib/buildQuery.js
- packages/strapi-utils/lib/buildQuery.js
> Cast arrays and build mongo where match with a $and

- examples/getstarted/exports/graphql/schema.graphql
- packages/strapi/bin/strapi.js
- packages/strapi/package.json
- yarn.lock
> Load local commands when necessary with strapi cli

- packages/strapi-plugin-content-manager/admin/src/containers/ListPage/index.js
> Fix wrong input import

- packages/strapi-plugin-email/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/functions/bootstrap.js
> Fix missing default providers

- packages/strapi/lib/core/bootstrap.js
> Fix missing identity in controllers without models

- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/package.json
- packages/strapi-admin/webpack.config.js
- packages/strapi/lib/commands/build.js
- packages/strapi/lib/commands/dev.js
- yarn.lock
Builds with the correct params and only load `server.(js|json)` file from the env to know where to build
> Apply updates to build process

- packages/strapi-hook-bookshelf/lib/index.js
> Add dbSchema support for pg

- packages/strapi-admin/config/queries/bookshelf.js
- packages/strapi-admin/controllers/Admin.js
> Fix administrator edition

- packages/strapi-admin/controllers/Admin.js
- packages/strapi/bin/strapi.js
- packages/strapi/lib/commands/uninstall.js
- packages/strapi/package.json
> Delete files on strapi uninstall

- packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js
- packages/strapi-admin/admin/src/containers/PluginDispatcher/index.js
- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-plugin-content-manager/admin/src/containers/SettingsPage/index.js
Several fixes in the beta UI:
- Modal not closing
- Wording
- Link not working
> Fix UI issues

- packages/strapi-plugin-users-permissions/admin/src/containers/EditPage/index.js
- packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
- packages/strapi-plugin-users-permissions/test/roles-api.test.e2e.js
- packages/strapi-plugin-users-permissions/test/users-api.test.e2e.js
Fix Role CRUD when adding users directly in the UI
> Fix crud role with users

- packages/strapi-plugin-content-type-builder/admin/src/translations/ar.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/de.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/es.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/it.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/ja.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/ko.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/nl.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/pl.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/pt-BR.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/pt.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/ru.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/tr.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/zh-Hans.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/zh.json
> Fix enumeration placholder

- examples/getstarted/package.json
- packages/strapi-generate-new/json/package.json.js
- packages/strapi-generate-new/lib/after.js
- packages/strapi-helper-plugin/lib/src/components/BlockerComponent/index.js
- packages/strapi/bin/strapi.js
- packages/strapi/lib/commands/develop.js
- packages/strapi/lib/commands/new.js
- test/helpers/testAppGenerator.js
Rename `strapi dev` to `strapi develop`
> Strapi develop cmd

- docs/3.0.0-beta.x/advanced/customize-admin.md
- packages/strapi-admin/index.js
Adds basic admin customization feature with file overriding
> Add admin panel basic customization

- docs/3.0.0-beta.x/advanced/customize-admin.md
- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/index.js
Minor admin build and doc updates
> Admin build cleanup

- packages/strapi-admin/index.js
> Refactor admin build script for futur updates

- packages/strapi/lib/core-api/queries/bookshelf.js
Fix invalid filter name and cleanup some search query
> Fix invalid filter name and cleanup some search query

- packages/strapi/bin/strapi.js
- packages/strapi/lib/Strapi.js
- packages/strapi/lib/commands/build.js
- packages/strapi/lib/commands/console.js
- packages/strapi/lib/commands/develop.js
- packages/strapi/lib/commands/start.js
- packages/strapi/lib/core/load-extensions.js
- packages/strapi/lib/middlewares/public/index.js
Clean up commands
- [] MongoDB
> Clean up commands

- packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
> Fix missing history in saga

- packages/strapi-admin/admin/src/plugins.js
- packages/strapi-admin/index.js
- packages/strapi-admin/package.json
- packages/strapi-admin/webpack.config.dev.js
- packages/strapi-admin/webpack.config.js
- yarn.lock
Add a dev cmd in strapi-admin to run a strapi admin panel on localhost:4000 for dev purpose
```sh
yarn setup
```
```sh
cd packages/strapi-admin
```
```sh
yarn dev
```
Run any strapi app on the 1337 port to have a backend to test. 
ex:
```sh
cd examples/getstarted && yarn develop
```
> Strapi admin dev cmd

- docs/3.x.x/guides/deployment.md
- docs/package-lock.json
Docs for installing Strapi on a Digital Ocean Droplet / VPS.
These docs show the complete steps to install, configure and host a Strapi project on a Digital Ocean Droplet / VPS.
> Docs - Install Strapi on a Digital Ocean Droplet/VPS 

- examples/getstarted/api/articles/documentation/1.0.0/articles.json
- examples/getstarted/api/articles/models/Articles.settings.json
- examples/getstarted/api/post/documentation/1.0.0/post.json
- examples/getstarted/exports/graphql/schema.graphql
- examples/getstarted/extensions/documentation/documentation/1.0.0/full_documentation.json
- packages/strapi-hook-bookshelf/lib/relations.js
- packages/strapi-plugin-upload/services/Upload.js
> Fix Add image upload in content type and add image in example app

- .github/FUNDING.yml
Add Open Collective as GH funding
> Add Open Collective as GH funding

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/advanced/customize-admin.md
- docs/3.0.0-beta.x/advanced/hooks.md
- docs/3.0.0-beta.x/advanced/middlewares.md
- docs/3.0.0-beta.x/api-reference/reference.md
- docs/3.0.0-beta.x/cli/CLI.md
- docs/3.0.0-beta.x/concepts/concepts.md
- docs/3.0.0-beta.x/configurations/configurations.md
- docs/3.0.0-beta.x/getting-started/install-requirements.md
- docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
- docs/3.0.0-beta.x/guides/api-documentation.md
- docs/3.0.0-beta.x/guides/authentication.md
- docs/3.0.0-beta.x/guides/controllers.md
- docs/3.0.0-beta.x/guides/databases.md
- docs/3.0.0-beta.x/guides/deployment.md
- docs/3.0.0-beta.x/guides/email.md
- docs/3.0.0-beta.x/guides/graphql.md
- docs/3.0.0-beta.x/guides/policies.md
- docs/3.0.0-beta.x/guides/queries.md
- docs/3.0.0-beta.x/guides/services.md
- docs/3.0.0-beta.x/guides/upload.md
- docs/3.0.0-beta.x/plugin-development/backend-development.md
- docs/3.0.0-beta.x/plugin-development/frontend-development.md
- docs/3.0.0-beta.x/plugin-development/plugin-architecture.md
- docs/3.0.0-beta.x/plugin-development/quick-start.md
- packages/strapi-generate-api/templates/bookshelf/controller.template
- packages/strapi-generate-api/templates/bookshelf/service.template
- packages/strapi/lib/Strapi.js
Add documentation related to the beta
> Beta documentation

- docs/3.x.x/guides/deployment.md
Updated deployment guide for Digital Ocean
I corrected various issues in the guide to reflect better coding standards and ensure a better development experience.
I updated the docs to reflect and fix various permission errors, and to remove --watch from pm2 as not suitable in production. Various other changes and …
> Updated deployment guide for Digital Ocean

- CONTRIBUTING.md
Beta contributing guide revisions
Corrected typos and made other clarifications to the text.
Fixed typos and grammar in several places.
Added or removed content to clarify or make valid.
> Beta contributing guide revisions

- docs/3.0.0-beta.x/guides/deployment.md
- docs/3.x.x/guides/deployment.md
Update digital ocean deployment with beta updates
> Update digital ocean deployment with beta updates

- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
- docs/3.x.x/migration-guide/README.md
- examples/getstarted/ecosystem.config.js
> Create beta migration guide

- docs/3.0.0-beta.x/advanced/traceability.md
[WIP]: Documentation/traceability --> ./usage-information
I propose the following for the new wording of this page.  Along with additional clarifying comments within the text, typos have been fixed.  I have rearranged the order of the paragraphs to better suit the message as intended.
Strapi has a feature to …
> [WIP]: Documentation/traceability --> ./usage-information

- README.md
**BETA:** Additional revisions to README.md 
Additional revisions to the BETA version of the Strapi README.md.  Clarifies, edits, add and removes different sections.
- This corrects minor typos and grammar.
- Adds versions to support OSes 
- Ensure all references to BETA are removed.
- Rearranged content to move …
> Additional revisions to README.md 

- docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Add instruction to remove `yarn.lock` or `package-lock.json` before migrating
> Update migration guide steps

- docs/3.0.0-beta.x/README.md
Add migration guide link on beta doc homepage
> Add migration guide link on beta doc homepage

- .github/PULL_REQUEST_TEMPLATE.md
Update PR template to allow new PRs
> Update PR template to allow new PRs

- docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Clarified and fixed instructions regarding plugin and admin folders.
> Clarified and fixed instructions

- docs/3.0.0-alpha.x/guides/deployment.md
- docs/3.0.0-beta.x/guides/deployment.md
Updated the Alpha and Beta Deployment guides to Digital Ocean to conform to best practices with regards database variables.  Fixed typos and grammatical errors.
> Digital ocean deployment UPDATES 

- packages/strapi-admin/services/auth.js
- packages/strapi-plugin-users-permissions/config/policies/permissions.js
Fix permission policy mixing users jwt and admin jwt
- []  Framework
> Fix permission policy mixing users jwt and admin jwt

- docs/3.0.0-beta.x/plugin-development/plugin-architecture.md
Improved language clarity in plugin-architecture.md
> Improved clarity in plugin-architecture.md

- examples/getstarted/extensions/graphql/config/settings.json
- packages/strapi-plugin-graphql/services/Query.js
Fix amountLimit in graphql queries
Fix #3420
> Fix amountLimit in graphql queries

- packages/strapi-plugin-graphql/services/Query.js
Fix primaryKey not found for custom resolvers
- [] Not applicable
> Fix primaryKey not found for custom resolvers

- packages/strapi-plugin-content-type-builder/admin/src/containers/App/saga.js
Fixes the  update of a plugin's content type. The bug was due to the source that wasn't updated.
> Fixes #3224

- examples/getstarted/exports/graphql/schema.graphql
- examples/getstarted/extensions/users-permissions/config/schema.graphql.js
- packages/strapi-plugin-graphql/hooks/graphql/index.js
- packages/strapi-plugin-graphql/hooks/graphql/load-config.js
Load extensions in graphql schemas fix #3411
> Load extensions in graphql schemas

- packages/strapi/lib/middlewares/index.js
Fix 403 on /documentation page
> Fix beforeInitialize middlewares can modify order or middlewares

- examples/getstarted/package.json
- packages/strapi-generate-new/lib/after.js
- packages/strapi/lib/commands/develop.js
- packages/strapi/lib/utils/index.js
- packages/strapi/package.json
Remove build step on strapi new. The idea is to let people create an app without waiting too much and get the progress bar on strapi develop. This will also simplify the process for those using CI tools
> Remove strapi build on new

- docs/3.0.0-beta.x/guides/services.md
> Fix typo in documentation

- docs/3.0.0-beta.x/cli/CLI.md
Minor editorial changes to the CLI docs only (missing periods, minor rephrasing, typo correction).
> Improve CLI documentation

- docs/3.0.0-beta.x/guides/models.md
Fixed a minor documentation error within the code example in Concepts -> Models -> One To Many
> Improve example in the documentation

- README.md
Updating the NPM badge to show the beta version instead of the Alpha Version
> Update NPM Badge on Readme to Beta

- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-helper-plugin/lib/src/testUtils/commonTrads.json
- test/config/front/testUtils/commonTrads.json
The wording here is important as it's one of the first things the user
sees of the Strapi project having set it up, and it didn't quite make
sense (though everyone will understand what's meant to be said).
Tweaking this will improve the initial user experience of Strapi.
*Ready to be merged*.
> Fix wording of welcome text

- packages/strapi/lib/Strapi.js
Call the requireBootstrap function in Strapi constructor
> Call requireBootstrap on init

- README.md
I update the Slack badge in the README.md file to make it redirect to the Slackin from the website and not from an old heroku instance.
> Update Slack badge URL

- packages/strapi-admin/controllers/Admin.js
Fix admin pwd persisted in plaintext on edit
fixes #3518
> Fix admin pwd persisted in plaintext on edit

- docs/.vuepress/config.js
- docs/.vuepress/theme/AlgoliaSearchBox.vue
- docs/.vuepress/theme/Navbar.vue
Algolia Search added to Strapi Documentation for easier Search.
Now users can search and the search is powered by Algolia.  
Previously, the default search in Vuepress was inadequate.  Now Algolia indexes the documentation and provides a better search experience.
> Use algolia docsearch in documentation search

- docs/3.0.0-beta.x/guides/deployment.md
Fix a typo in the deployment documentation
> Fix deployment typo fix

- docs/3.0.0-alpha.x/advanced/hooks.md
- docs/3.0.0-beta.x/advanced/hooks.md
- packages/strapi-hook-ejs/README.md
In the documentation and in the readme, the file `hooks.json` is mentioned instead of `hook.json`
So this PR update to the correct file name.
> Fix hook.json file name

- docs/1.x.x/README.md
- docs/3.0.0-alpha.x/README.md
- docs/3.0.0-beta.x/README.md
- packages/strapi-generate-api/README.md
- packages/strapi-generate-controller/README.md
- packages/strapi-generate-model/README.md
- packages/strapi-generate-new/README.md
- packages/strapi-generate-plugin/README.md
- packages/strapi-generate-policy/README.md
- packages/strapi-generate-service/README.md
- packages/strapi-generate/README.md
- packages/strapi-hook-bookshelf/README.md
- packages/strapi-hook-ejs/README.md
- packages/strapi-hook-knex/README.md
- packages/strapi-hook-mongoose/README.md
- packages/strapi-hook-redis/README.md
- packages/strapi-middleware-views/README.md
- packages/strapi-utils/README.md
- packages/strapi/README.md
In my last PR I updated the mono repo README for the Slack badge.
This action also has to be done for other README and in the documentation.
Previous PR https://github.com/strapi/strapi/pull/3511
> Update all packages Slack badge

- docs/3.0.0-beta.x/plugin-development/backend-development.md
By trying to debug an issue. I did copy and paste the route object and the structure was wrong.
So I updated the object to make it work correctly.
> Fix plugin route object

- packages/strapi-hook-mongoose/lib/mount-models.js
- packages/strapi/lib/core-api/queries/bookshelf.js
- packages/strapi/lib/core-api/queries/mongoose.js
> CRUD Group mongoose

- .travis.yml
- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/lib/index.js
- test/createTestApp.js
- test/e2e.js
- test/helpers/testAppGenerator.js
Use generateNew directly and disable dep install for tests
> Use generateNew directly and disable dep install for tests

- packages/strapi-hook-bookshelf/package.json
- packages/strapi-hook-knex/package.json
Testing out updating bookshelf and knex to latest versions to ensure ease of development for default values, foreign keys, and ect that are planned to be added.
> Updating bookshelf and knex packages

- packages/strapi-plugin-users-permissions/package.json
- packages/strapi/package.json
- yarn.lock
~~This PR is a WIP as testing needs to be done with `purest` Based on the changelog there are breaking changes (however the documentation related to them is currently offline): https://github.com/simov/purest/blob/master/CHANGELOG.md#v300-20160717~~
Changed to only update koa-ip, purest will come later.
> Update koa-ip version

- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-content-manager/controllers/Groups.js
- packages/strapi-plugin-content-manager/controllers/validation/model-configuration.js
- packages/strapi-plugin-content-manager/services/ContentTypes.js
- packages/strapi-plugin-content-manager/services/Groups.js
- packages/strapi-plugin-content-manager/services/utils/configuration/__tests__/attributes.test.js
- packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js
- packages/strapi-plugin-content-manager/services/utils/configuration/index.js
- packages/strapi-plugin-content-manager/services/utils/configuration/layouts.js
- packages/strapi-plugin-content-manager/services/utils/configuration/metadatas.js
- packages/strapi-plugin-content-manager/services/utils/configuration/settings.js
- packages/strapi/lib/core/bootstrap.js
Update content-manager schemas
> Update content-manager schemas

- examples/getstarted/api/article/models/Article.settings.json
- packages/strapi-plugin-content-manager/services/ContentTypes.js
- packages/strapi-plugin-content-manager/services/Groups.js
- packages/strapi-plugin-content-manager/services/utils/store.js
- packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
- packages/strapi-plugin-content-type-builder/services/Groups.js
- packages/strapi-plugin-content-type-builder/services/__tests__/groups.test.js
Rename content manager configuration key an model uid changes
> Rename content manager configuration key on model uid changes

- examples/getstarted/groups/ingredients.json
- packages/strapi-hook-bookshelf/lib/mount-models.js
- packages/strapi-hook-bookshelf/lib/queries.js
- packages/strapi-hook-bookshelf/lib/relations.js
- packages/strapi-hook-mongoose/lib/queries.js
- packages/strapi-hook-mongoose/lib/relations.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
- packages/strapi/lib/core/bootstrap.js
Handle relations in groups:
- creation of releations inside a group
- update of relations inside a group with deletion when necessary
- delete a group in cascade
> Handle relations in groups

- packages/strapi-hook-bookshelf/lib/generate-group-relations.js
- packages/strapi-hook-bookshelf/lib/mount-models.js
- packages/strapi-hook-bookshelf/lib/queries.js
Rename slice by group in group feature
> Rename slice by group in group feature

- packages/strapi-plugin-content-manager/config/policies/routing.js
- packages/strapi-plugin-content-manager/config/routes.json
- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/test/index.test.e2e.js
- test/helpers/request.js
Add content manager upload route and remove formdata in favor of JSON only
> Add content manager upload route and remove formdata in favor of JSON only

- packages/strapi-plugin-upload/controllers/Upload.js
- packages/strapi/package.json
- yarn.lock
Upgrade koa-body dependency and update code according the the changelog
> Upgrade koa-body version to latest

- packages/strapi-plugin-content-type-builder/controllers/validation/common.js
- packages/strapi-plugin-content-type-builder/controllers/validation/relations.js
- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
> update group validations

- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/utils/parse-multipart.js
- packages/strapi-plugin-content-manager/utils/upload-files.js
- packages/strapi/lib/core-api/controller.js
- packages/strapi/lib/core-api/service.js
- packages/strapi/lib/core-api/utils/parse-multipart.js
- packages/strapi/lib/core-api/utils/upload-files.js
- packages/strapi/lib/middlewares/router/utils/routerChecker.js
Enable file upload in core apis
> Enable file upload in core apis

- packages/create-strapi-app/README.md
- packages/strapi-plugin-documentation/README.md
I replaced the paths which said "my-app" to "my-project" in order to keep this consistent in the documentation.
> Edited my-app to be my-project to keep it consistent with docs

- examples/getstarted/extensions/users-permissions/models/Role.settings.json
- examples/getstarted/extensions/users-permissions/models/User.settings.json
- packages/strapi-plugin-content-manager/config/policies/routing.js
- packages/strapi-plugin-content-manager/utils/upload-files.js
- packages/strapi-plugin-users-permissions/controllers/User.js
Add image upload in routing policy of the content manager
> Add image upload in routing policy of the content manager

- packages/strapi-admin/admin/src/containers/HomePage/index.js
Change the URL for Reddit in the Strapi Dashboard. We now have a dedicated Strapi Chanel in Reddit. [Strapi Reddit Channel](https://www.reddit.com/r/Strapi/)
> Update reddit link to target strapi subreddit

- .travis.yml
- examples/getstarted/api/tag/models/Tag.settings.json
- packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
- packages/strapi-hook-bookshelf/lib/mount-models.js
- packages/strapi-hook-bookshelf/lib/queries.js
- packages/strapi-hook-bookshelf/package.json
- packages/strapi-plugin-content-manager/test/index.test.e2e.js
- test/helpers/generators.js
- yarn.lock
Handle date with iso format in input and output to simplify processing
> Handle date with iso format in input and output to simplify processing

- packages/strapi-plugin-upload/admin/src/components/Li/index.js
Depending on the database the `updatedAt` field can be different (`updated_at`). This PR fixes the wrong display in the view.
> Fix the Updated column in the uploaded files view

- packages/strapi-plugin-content-manager/admin/src/components/Group/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/formatData.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/schema.js
> Fix bug when editing an existing entry that did not have a group

- examples/getstarted/plugins/myplugin/models/Test.settings.json
- packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
- packages/strapi-hook-mongoose/lib/mount-models.js
Support unique indexes with clean error messages
> Support unique indexes with clean error messages

- docs/3.0.0-beta.x/configurations/configurations.md
- examples/getstarted/config/functions/bootstrap.js
- packages/strapi-generate-new/lib/resources/files/config/functions/bootstrap.js
- packages/strapi-plugin-content-manager/config/functions/bootstrap.js
- packages/strapi-plugin-documentation/config/functions/bootstrap.js
- packages/strapi-plugin-email/config/functions/bootstrap.js
- packages/strapi-plugin-settings-manager/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/functions/bootstrap.js
- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
- packages/strapi/lib/Strapi.js
make boostrap functions async only.
Users will need to update there boostrap.js file
> make boostrap functions async only

- docs/3.0.0-beta.x/api-reference/reference.md
- docs/3.0.0-beta.x/guides/controllers.md
- docs/3.0.0-beta.x/guides/queries.md
- docs/3.0.0-beta.x/guides/services.md
- packages/strapi/lib/Strapi.js
> Documentation updates

- packages/strapi-admin/services/auth.js
- packages/strapi-generate-api/json/routes.json.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-plugin-users-permissions/config/policies/permissions.js
- packages/strapi-plugin-users-permissions/config/schema.graphql
- packages/strapi-plugin-users-permissions/controllers/Auth.js
- packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
- packages/strapi-plugin-users-permissions/services/Providers.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Clear _id now that queries return an id everytime
> Clear _id now that queries return an id everytime

- packages/strapi/lib/core-api/controller.js
Move the parseMutlipart function to the controller prototype to avoid it appearing in the permissions because it is based on the controller keys instead of the routes for now
> Make parseMultipart part of the controller prototype

- examples/getstarted/config/hook.json
- examples/getstarted/hooks/test-hook/index.js
- examples/getstarted/plugins/myplugin/hooks/some-hook/index.js
- packages/strapi-hook-bookshelf/lib/index.js
- packages/strapi-hook-ejs/lib/index.js
- packages/strapi-hook-knex/lib/index.js
- packages/strapi-hook-mongoose/lib/index.js
- packages/strapi-hook-redis/lib/index.js
- packages/strapi-plugin-graphql/hooks/graphql/index.js
- packages/strapi-utils/lib/buildQuery.js
- packages/strapi-utils/lib/models.js
- packages/strapi/lib/Strapi.js
- packages/strapi/lib/core/load-hooks.js
- packages/strapi/lib/hooks/index.js
- packages/strapi/lib/middlewares/index.js
Users will have to update there hooks
> Make hook loading async

- packages/strapi-hook-mongoose/lib/buildQuery.js
Refactor mongoose deepfiltering to populate infos correctly
> Refactor mongoose deepfiltering to populate infos correctly

- packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
- packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
> Test graphql delete returns the entity

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/api-endpoints.md
> Docs api endpoints

- docs/3.0.0-beta.x/guides/queries.md
- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.md
Add migration guide for beta.16
> Add migration guide to beta.16

- packages/strapi-plugin-content-type-builder/admin/src/containers/GroupPage/index.js
> Groups & repeatable QA

- docs/3.0.0-beta.x/guides/deployment.md
Fixes invalid JSON in doc example.
> Fix comma in JSON example

- packages/strapi-hook-mongoose/lib/relations.js
> Use kind when provided on morph relation

- packages/strapi-hook-bookshelf/lib/queries.js
- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
> Fix permission deletion on start + default transaction for create and update query

- packages/strapi/lib/middlewares/cors/index.js
> Allow multiple origins to be provided to the cors middleware

- packages/strapi-helper-plugin/lib/src/components/InputDate/index.js
- packages/strapi-helper-plugin/lib/src/components/InputToggleWithErrors/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/schema.js
Fix the date field bug that caused a blank screen when trying to submit an "empty" date.
> Fix buggy date field, and toggle field size

- packages/strapi-plugin-documentation/services/Documentation.js
Fix for https://github.com/strapi/strapi/issues/4027
> Pass group associations as second param

- examples/getstarted/api/menusection/models/Menusection.settings.json
- examples/getstarted/groups/dish.json
- packages/strapi-hook-mongoose/lib/mount-models.js
Fix https://github.com/strapi/strapi/issues/3999
> Populate groups relations on mongo

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
I changed `filterOption` in `SelectMany` component because currently, it makes multiple select's autocomplete doesn't work.
It might related to https://github.com/strapi/strapi/issues/4025
> Fix filterOption of SelectMany to enable searching in multiple select

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.md
For someone who wrote no bootstrap functions, my code looks like: 
```js
module.exports = () => {};
```
I had to start a new Strapi project to understand how to solve my "cb is not a function" and "fn is not a function" typeerrors. I think it would be useful for future basic Strapi users like me!
> Update Bootstrap function documentation

- packages/strapi-plugin-content-manager/admin/src/components/MediaPreviewList/index.js
> fix media preview list image count

- packages/strapi-admin/index.js
- packages/strapi/lib/commands/build.js
- yarn.lock
This PR copies plugins front-end files for easier customisation.
> Allow to customise plugins front-end files

- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/lib/create-quickstart-project.js
- packages/strapi-generate-new/lib/index.js
- packages/strapi-generate-new/lib/utils/usage.js
- packages/strapi-generate-new/package.json
- yarn.lock
> Add sentry in strapi new

- docs/3.0.0-beta.x/getting-started/quick-start.md
Replaced category name "Convenient" with "French Food."
> Update quick-start documentation

- CONTRIBUTING.md
I simply added RFC in contributing guide and add some comment about the respect of a well-templated message in the issue body.
> Add rfc in contributing guide and add some comment

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
This PR fixes #4127 where the link had the incorrect source.
> Fix links in the content manager

- packages/strapi-provider-email-sendmail/lib/index.js
Solving no attachments in sendmail plugin
> Fix on no attachments in mails

- packages/strapi-utils/lib/sanitize-entity.js
- packages/strapi/lib/Strapi.js
> Fix sanitize bug with mongo objectid and use lower-case for getModel

- packages/strapi-plugin-upload/controllers/Upload.js
> Fix image url when using a third party

- packages/strapi-plugin-upload/README.md
Changed header of README to `strapi-plugin-upload`.
> Update README.md header for strapi-plugin-upload

- packages/strapi-plugin-graphql/services/Loaders.js
Fix https://github.com/strapi/strapi/issues/4199
The dataloader wasn't instanciated if there was no relation to it from another content-type
> Create a dataloader for every model

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/models.md
- docs/3.0.0-beta.x/guides/parameters.md
- docs/3.0.0-beta.x/plugins/upload.md
Move the upload doc in plugin section and add available endpoints
> Move the upload doc in plugin section and add available endpoints

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/plugins/email.md
Move the email doc in plugin section
> Move the email doc in plugin section

- docs/3.0.0-beta.x/community/contribute-with-docs.md
- docs/3.0.0-beta.x/community/contributing-guide.md
Each return in the comments was addressed:
1. Grammar and any typos were fixed
2. Clarifications were made to a few paragraphs
3. Broken links fixed and edited
4. Other changes
- [X ] Not applicable
> Docs/Community GuidelinesCorrect Returns

- examples/getstarted/extensions/users-permissions/config/schema.graphql.js
- packages/strapi-plugin-graphql/services/Schema.js
Fix issue explained in https://github.com/strapi/strapi/pull/4206
> Fix mutation resolver name selecter

- packages/strapi-admin/package.json
- yarn.lock
The `webpack-dev-server` was in the `devDepencies` instead of the `dependencies` which made the admin development impossible.
> Fix webpack-dev-server dependency

- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
> Fix startup race condition by disabling reload when writing jwt.json

- packages/strapi-plugin-graphql/config/settings.json
- packages/strapi-plugin-graphql/hooks/graphql/index.js
This pull request adds the possibility to enable the share playground feature .
Fix #4048
> Add graphql share playground option

- packages/strapi-admin/webpack.config.js
This PR disables the `mozjpeg` as it causes errors in some Linux environments.
> Update image-webpack-loader configuration

- packages/create-strapi-app/index.js
- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/lib/create-quickstart-project.js
- packages/strapi-generate-new/lib/generate-new.js
- packages/strapi-generate-new/lib/index.js
- packages/strapi-generate-new/lib/resources/json/package.json.js
- packages/strapi-generate-new/lib/utils/check-requirements.js
- packages/strapi-generate-new/lib/utils/usage.js
- packages/strapi-generate-new/package.json
- packages/strapi/lib/Strapi.js
- packages/strapi/package.json
- yarn.lock
> Improve project creation error diagnostic

- packages/strapi-generate-new/lib/create-quickstart-project.js
> Fix err.stderr not defined in quickstart

- packages/strapi-hook-bookshelf/lib/queries.js
- packages/strapi-hook-mongoose/lib/queries.js
Fix #https://github.com/strapi/strapi/issues/4265
> Fix groups creation/update not working with null groups

- docs/3.0.0-beta.x/concepts/customization.md
flies -> files
constomization -> customization
> Correct minor docs typos.

- packages/strapi-hook-mongoose/package.json
- yarn.lock
Fix https://github.com/strapi/strapi/issues/4322
> Lock mongoose version to be 5.7.4

- packages/strapi-hook-bookshelf/lib/mount-models.js
> Fix graphql nested groups returning null

- docs/3.0.0-beta.x/admin-panel/customization.md
Update outdated Styles section.
> Update Admin panel customization documentation

- packages/strapi-plugin-content-manager/admin/src/containers/EditView/utils/formatData.js
> Fix multiple media upload in group

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- examples/getstarted/components/closingperiod.json
- packages/strapi-connector-bookshelf/lib/generate-component-relations.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-bookshelf/lib/queries.js
- packages/strapi-connector-bookshelf/lib/utils/attributes.js
- packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js
- packages/strapi-plugin-content-manager/services/utils/configuration/layouts.js
> Add dynamic zone type queries to bookshelf

- packages/strapi-plugin-content-manager/controllers/Components.js
- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-content-manager/services/Components.js
- packages/strapi-plugin-content-manager/services/ContentTypes.js
Add components schemas directly with the content types and compos schemas to avoid too many calls
> Update CTM schemas response

- examples/getstarted/components/dish.json
- packages/strapi-connector-bookshelf/lib/generate-component-relations.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-bookshelf/lib/populate.js
- packages/strapi-connector-bookshelf/lib/utils/associations.js
- packages/strapi-connector-bookshelf/lib/utils/attributes.js
- packages/strapi-utils/lib/models.js
Implements new population algorithm for default populates on bookshelf
> Implement nested populates

- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/lib/utils/stop-process.js
- packages/strapi-generate-new/package.json
…api-app
Improve the error message for dep install errors in strapi new like commands
> Improve the error message on install dependencies error 

- docs/3.0.0-beta.x/concepts/configurations.md
One day, @alexandrebodin asked me about the way that Strapi manage the CRON tasks.
So I updated the documentation to let everyone know about the node module that is used to power this feature.
> Add cron feature details in the documentation

- docs/3.0.0-beta.x/content-api/api-endpoints.md
Remove confusing examples. Strapi doesn't manage only restaurants.
> Change examples of API endpoints

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.16-to-beta.17.4.md
> Update migration-guide-beta.16-to-beta.17.4.md (typo)

- packages/strapi-plugin-users-permissions/controllers/Auth.js
Add validation to the users-permission plugin for email
> Add Email validation on user register

- .github/ISSUE_TEMPLATE/SECURITY.md
- SECURITY.md
> Fix typo on security.md

- packages/strapi/lib/middlewares/public/index.js
…/admin
Serve index.html in a simpler way for the / and /admin routes
> Serve index.html in a simpler way

- docs/3.0.0-beta.x/guides/error-catching.md
_and a reminder to actually install the package_
> Add Strapi environment to Sentry error

- packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
Check if autoMigration equals false before calling createOrUpdateTable method.
- [X ] 🐛 Bug fix
- [X ] Plugin
- [ X] Postgres
> Do not create manyRelation tables if autoMigration is false.

- packages/strapi-plugin-graphql/services/Resolvers.js
> Support private associations in GraphQL resolvers

- packages/strapi-admin/package.json
- packages/strapi-admin/webpack.config.dev.js
- yarn.lock
This PR removes a package that caused vulnerability issue (`open-browser-webpack-plugin`)
Fixes #4456
> Remove unneeded Webpack plugin

- examples/getstarted/public/index.html
- examples/getstarted/public/production.html
- packages/strapi-generate-new/lib/resources/files/public/index.html
- packages/strapi-generate-new/lib/resources/files/public/production.html
- packages/strapi/lib/middlewares/public/index.js
I've updated the server homepage to make it more dynamic. The UI has also been updated.
> New design for the server homepage

- packages/strapi-plugin-graphql/services/Aggregator.js
> Use plugin in the GraphQL aggregation queries

- packages/strapi-connector-bookshelf/lib/queries.js
> Use where instead of forge to make queries

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/external-data.md
Add a guide to fetch and insert external data.
In this example, we see how to use CRON task, execute functions programmatically and also how to sue `query` to create entries.
> Add guide to fetch and insert external data

- docs/3.0.0-beta.x/concepts/controllers.md
When you copy/paste the code from the docs, the `model` in the sanitize function is not define and it's hard to know what it is and how to access it.
By adding the example with the `restaurant` model, it makes more sense.
Related issue https://github.com/strapi/strapi/issues/4494
> Add the model value in the core controller docs

- docs/3.0.0-beta.x/content-api/parameters.md
This PR correct a typo inside the documentation.
> Correct typo in content-api documentation

- docs/3.0.0-beta.x/plugins/documentation.md
The JSON was not valid so the documentation would not generate.
> valid JSON makes a working example

- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
I updated a bit the `emitEvent` parameters in the CTM to send more details about the administrators.
> Send details about administrator in events

- packages/strapi-admin/admin/src/containers/App/index.js
It sends the UUID of the project when the admin is loaded.
> Send UUID when the admin is loaded

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/process-manager.md
Many times we have questions about starting the app using `server.json` file.
Here is an example.
> Add process manager guide

- docs/3.0.0-beta.x/guides/databases.md
> docs: update doc

- packages/strapi-plugin-content-type-builder/controllers/validation/relations.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/component-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/index.js
- packages/strapi-plugin-content-type-builder/utils/attributes.js
> Allow self referencing content type creation

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- examples/getstarted/components/default/closingperiod.json
- examples/getstarted/components/default/restaurantservice.json
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/queries.js
- packages/strapi-connector-mongoose/lib/utils/helpers.js
- packages/strapi-plugin-content-manager/config/policies/routing.js
- packages/strapi-plugin-content-manager/test/components/repeatable-not-required-min-max.test.e2e.js
- packages/strapi-plugin-content-manager/utils/upload-files.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-utils/lib/buildQuery.js
- packages/strapi/lib/core-api/utils/upload-files.js
> Dynamic zone/mongoose support

- packages/strapi-plugin-users-permissions/controllers/Auth.js
In all Auth functions from the **User & Permissions** plugin we `lowercase` the email.
But it was not done for the forgot password function.
In this PR I fix it to be consistent.
> Fix lowercase the email in the forgot password function

- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/relations.js
> Dynamic zone/mongo fix morph relations

- docs/3.0.0-beta.x/guides/deployment.md
In the search, we have no result for `Docker`.
I just added a link from the docs to the `strapi/strapi-docker` repo to let the community find this repo.
> Add a docker ref in the docs

- docs/.vuepress/theme/components/Navbar.vue
Display a deprecated message docs alpha.
> Display a deprecated message docs alpha

- docs/.vuepress/theme/components/Navbar.vue
> Fix docs build

- docs/.vuepress/theme/components/Navbar.vue
> Revert docs update

- docs/.vuepress/config.js
Fix #4576 - the website link in the top menu was broken.
> Fix docs website link in the top menu

- docs/.vuepress/theme/components/Navbar.vue
Reverts strapi/strapi#4614
I had a cache issue on my browser, so I thought an issue happened. 
Sorry for that PR flood.
> Revert "Revert docs update"

- docs/.vuepress/config.js
- docs/package.json
- docs/yarn.lock
During the migration to VuePress 1, the Google Analytics was moved in a plugin.
So I forgot to update this part.
> Add GA in the docs

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-plugin-graphql/package.json
- packages/strapi-plugin-graphql/services/Resolvers.js
- packages/strapi-plugin-graphql/services/Schema.js
- packages/strapi-plugin-graphql/services/Types.js
- packages/strapi-plugin-graphql/types/dynamiczoneScalar.js
- yarn.lock
> Support dynamic zones in graphql

- packages/strapi-plugin-graphql/services/Aggregator.js
- packages/strapi-plugin-graphql/services/Resolvers.js
> Hotfix mongo aggregate policy verifications

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-plugin-documentation/services/Documentation.js
> Support dynamic zones in documentation plugin

- packages/strapi-plugin-documentation/package.json
Updating to Swagger-UI 3.24.3 that addresses a CSS-based input field value exfiltration vulnerability
https://github.com/swagger-api/swagger-ui/releases/tag/v3.23.11
Also updated a few other depends to stem legacy depends
> Update Swagger-UI for Documentation plugin

- packages/strapi-plugin-users-permissions/services/UsersPermissions.js
- Add timeout to fix no response issue
- Fix the function input parameters
> #4625 No response when get user permission role with internal network
> Fix no response when get user permission role with internal network

- packages/strapi-plugin-content-type-builder/services/schema-builder/component-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/schema-handler.js
- packages/strapi-plugin-content-type-builder/utils/attributes.js
> Dynamic zone support configurable prop on attributes

- docs/3.0.0-beta.x/guides/deployment.md
> Added missed comma in ecosystem.config.js example

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/draft.md
Here is a simple way to restrict the data we fetch by forcing a specific filter.
For this example - fetch by an enum value.
> Add guide to create a draft system

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/secure-your-app.md
Here is a guide to protecting your application.
In this case, I used Sqreen but can be applied to any other tool.
> Add sqreen guide

- docs/3.0.0-beta.x/guides/draft.md
> Fix typo draft guide

- docs/3.0.0-beta.x/concepts/queries.md
- docs/3.0.0-beta.x/content-api/api-endpoints.md
- docs/3.0.0-beta.x/plugins/upload.md
> Update documentation with dynamic zone feature

- packages/strapi/lib/commands/build.js
> Fix environment typo

- packages/strapi-plugin-users-permissions/config/policies/permissions.js
Remove populate role on non existing relation breaking mongoose
> Remove populate role on non existing relation breaking mongoose

- examples/getstarted/api/post/models/Post.settings.json
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-database/lib/database-manager.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-type-builder/controllers/validation/constants.js
- packages/strapi-plugin-content-type-builder/controllers/validation/model-schema.js
- packages/strapi-plugin-graphql/services/Loaders.js
- packages/strapi-plugin-graphql/services/Resolvers.js
- packages/strapi-plugin-graphql/services/Schema.js
- packages/strapi-plugin-graphql/services/Types.js
> graphql use model uid

- packages/strapi-connector-mongoose/package.json
- yarn.lock
> Upgrade mongoose version

- docs/3.0.0-beta.x/admin-panel/customization.md
- packages/strapi-admin/index.js
- packages/strapi/lib/commands/watchAdmin.js
Add admin host config
- Fixes #4707
> Fixes admin host in development

- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
> Init migration guide

- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/cleanData.js
> Fix json input

- examples/getstarted/extensions/users-permissions/models/User.config.js
- packages/strapi-admin/models/Administrator.config.js
- packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js
- packages/strapi-plugin-users-permissions/models/User.config.js
> Fix ctm hidden fields

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row.js
> Fix ctm wrong usage of useGlobalContext

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
> Add database migration guides for components

- packages/strapi-generate-new/lib/create-customized-project.js
> Fix db test on strapi new

- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-helper-plugin/lib/src/utils/translatedErrors.js
- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
- packages/strapi-plugin-content-type-builder/admin/src/components/CustomCheckbox/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
> Fixes #4752

- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/attributesRegexes.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
The component's category regex to match the back-end requirements
> Update ctb's category regex

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
- packages/strapi-plugin-content-type-builder/controllers/validation/common.js
- packages/strapi-plugin-content-type-builder/controllers/validation/component-category.js
- packages/strapi-plugin-content-type-builder/controllers/validation/component.js
Fix https://github.com/strapi/strapi/issues/4756 partially. We need the front regex to change too.
> Allow - in component category name regex

- packages/strapi-plugin-content-type-builder/admin/src/assets/images/logo.svg
The logo of the content type builder was deleted by mistake... This PR adds it back
> Fix content type builder logo

- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-plugin-documentation/services/utils/parametersOptions.json
Fix https://github.com/strapi/strapi/issues/4762
Fix https://github.com/strapi/strapi/issues/4766
> Fix multiple issues in beta.18

- packages/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
This PR fix the min requirement that prevented from editing an entry when setting a min value on a repeatable component that is not required.
> Fix edit component with min value when not required

- packages/strapi-generate-new/lib/create-customized-project.js
Fix https://github.com/strapi/strapi/issues/4781
> Fix typo in install command

- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/Search.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/SearchWrapper.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/Wrapper.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/index.js
This PR adds the option to search for an icon when creating a component.
> [CTB] Add search for component's icon

- packages/strapi-connector-bookshelf/lib/populate.js
Fix https://github.com/strapi/strapi/issues/4795
> Add morph rel on populate compo relation

- packages/strapi-utils/lib/parse-multipart.js
> logs(strapi-utills/parse-multipart.js): typo fix

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/auth-request.md
Add guide to request as authenticated user
> Add guide to request as authenticated user

- docs/3.0.0-beta.x/plugins/email.md
There is a recurrent report about this issue.
Email can't be sent because of the IP address of the local machine.
So here is the explanation in the docs.
> Add email trouble shooting

- packages/strapi-plugin-content-manager/admin/src/containers/ListSettingsView/DragWrapper.js
On the page to customize the fileds displayed in the entry list.
The dopdown to display available fields doesn't scroll.
> Fix scroll content type fields

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Update the path of component file for the database collection update.
close #4866
> Fix compo file path

- packages/strapi-provider-upload-cloudinary/README.md
Update strapi-provider-upload-cloudinary installation instructions
> Update strapi-provider-upload-cloudinary installation instructions

- packages/strapi-admin/admin/src/containers/AuthPage/index.js
> Fix Forgot password error

- docs/3.0.0-beta.x/plugins/users-permissions.md
Mention option to set jwt secret code via `JWT_SECRET` environment variable
> Add Security configuration paragraph

- packages/strapi-connector-mongoose/lib/mount-models.js
Fix https://github.com/strapi/strapi/issues/4831
> Do not overwritten morphAssoc populates

- packages/strapi-admin/admin/src/components/PluginCard/index.js
I have removed the settings button from the marketplace since there is no "list view" matching the content manager's settings.
Fixes #4908
> Fixes #4908

- docs/3.0.0-beta.x/plugins/users-permissions.md
Fix a typo in User Permission plugin documentation. Word 'function' was spelled as 'fonction'
> Typo fixed in user-permissions plugin documentation

- packages/strapi/lib/core/bootstrap.js
This updates the `strapi.config.admin.url` to match `strapi.config.url` with the added `/admin` used in the index.html change as well as showing the correct admin URL when starting the server.
> Update admin path variable if proxy is enabled

- packages/strapi-connector-mongoose/lib/buildQuery.js
- packages/strapi-connector-mongoose/lib/utils/index.js
- packages/strapi-utils/lib/buildQuery.js
…or mongoose match
Fixes issues with deep filtering on mongoose _id not being convert to ObjectId before matching 
Fix https://github.com/strapi/strapi/issues/4912
> fix(mongoose): Add manyWay match expr and fix conversion of id and _id to ObjectId

- packages/strapi-admin/controllers/Admin.js
Use a better plugin name validator
> chore(admin): Improve plugin name validator in install/uninstall plugin

- docs/3.0.0-beta.x/plugins/graphql.md
Following the issue #4849 - I add an example about the query to do to fetch DZ data.
> Add example GraphQL query dynamic zone

- docs/3.0.0-beta.x/guides/slug.md
Since we removed the Content Manager link - I have to update the path to access to this page.
Following the comment from @jmchza in #4910PR
> Udpate steps to access to the view config page

- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
> Add datetime and time validators in ctb

- packages/strapi-plugin-content-type-builder/admin/src/utils/getAttributeDisplayedType.js
This PR fixes the wrong modal that was being opened when editing a date field.
> Fix edit date types

- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/package.json
> package.json name property must be in lowercase

- packages/strapi-plugin-content-manager/controllers/Components.js
- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-content-type-builder/controllers/ComponentCategories.js
- packages/strapi-plugin-content-type-builder/controllers/Components.js
- packages/strapi-plugin-content-type-builder/controllers/ContentTypes.js
Fix https://github.com/strapi/strapi/issues/4935
> Use strapi.services instead of requires to allow overrides

- packages/strapi/lib/Strapi.js
- packages/strapi/lib/services/webhook-runner.js
Add defaultHeaders to webhooks
> Add defaultHeaders option to webhooks

- docs/3.0.0-beta.x/plugins/users-permissions.md
The documentation for user permission had a bug where the wrong attribute for user id is in an example. I changed from the incorrect `_id` to the correct `id`.
> Update user permission docs to use correct user id attribute

- docs/3.0.0-beta.x/guides/deployment.md
By following feedback on a [Spectrum question](https://spectrum.chat/strapi/general/deploy-to-heroku-failing-postgres~fcf4a25f-030f-48ca-89bd-7cf8a70f0f26), I updated the way to create the strapi app to respect the best practice.
It will prevent global version issue.
> Update way to create strapi app in deployment guide

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
corrected new components path to include category and be understandable
> corrected new components path to include category and be understandable

- packages/strapi-plugin-users-permissions/controllers/Auth.js
minor edit in error reply text
> Improve error messages

- docs/3.0.0-beta.x/plugins/users-permissions.md
> Patch doc providers

- docs/3.0.0-beta.x/plugins/users-permissions.md
I made some copy/past mistakes.
> Fix providers login URLs

- .travis.yml
- jest.config.e2e.js
- jest.config.js
- package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/jest.config.unit.js
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-utils/package.json
- packages/strapi/lib/core/__tests__/fs.test.js
- packages/strapi/package.json
- scripts/publish.sh
> Refactor tests and add codecov

- packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
- packages/strapi-connector-bookshelf/lib/index.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/index.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi/lib/core/bootstrap.js
- packages/strapi/lib/core/load-components.js
> Remove model globals

- docs/3.0.0-beta.x/plugins/users-permissions.md
> Fixe documentation typo provider

- docs/3.0.0-beta.x/guides/slug.md
Referts to @abdonrd comment on PR #4398
> Fix slug guide

- packages/strapi-plugin-users-permissions/config/schema.graphql
Find one role issue due to params sharing in the GraphQL schema.
Related issue #5013
> Fix get role via GraphQL

- examples/getstarted/api/homepage/models/homepage.settings.json
- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-content-manager/controllers/validation/index.js
- packages/strapi-plugin-content-manager/services/ContentTypes.js
- packages/strapi/lib/services/__tests__/entity-service.test.js
- packages/strapi/lib/services/entity-service.js
Adding support for singleTypes in entityservice => defacto support in CTM and core apis now.
> Single type support in entity-service

- packages/strapi-utils/lib/parse-type.js
Fixed a small typo (changed `compatble` to `compatible`)
> Fix typo invalide date format

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/DATE_FORMATS.js
> Fix timestamp display

- packages/strapi-generate-api/json/routes.json.js
- packages/strapi-generate-api/lib/before.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
> generate single type api routes

- packages/strapi-connector-mongoose/lib/queries.js
Fix https://github.com/strapi/strapi/issues/5056
> Fix mongoose dz delete query

- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/admin/src/containers/Admin/tests/index.test.js
- packages/strapi-plugin-content-manager/admin/src/index.js
- packages/strapi-plugin-content-type-builder/admin/src/index.js
- packages/strapi-plugin-documentation/admin/src/index.js
- packages/strapi-plugin-email/admin/src/index.js
- packages/strapi-plugin-upload/admin/src/index.js
- packages/strapi-plugin-users-permissions/admin/src/index.js
This PR changes a bit the way we load the plugins. The plugin used to be an `Object` where now it exports a function. This is the first step towards the internal API.
> Change the way we load plugins in the admin

- packages/strapi-admin/admin/src/components/Notification/Li.js
- packages/strapi-admin/admin/src/components/Notification/index.js
- packages/strapi-admin/admin/src/themes/colors.js
Signed-off-by: Virginie Ky <virginie.ky@gmail.com>
- Colored border-left 
- Icon size
- Padding-right
- New Close icon
> Notifications UI fix

- packages/strapi-plugin-content-manager/services/utils/configuration/metadatas.js
Fix https://github.com/strapi/strapi/issues/3968
> Fix main field set to id on mongo

- docs/3.0.0-beta.x/concepts/webhooks.md
> [Docs] Fix typo in webhooks

- packages/strapi-admin/admin/src/containers/AuthPage/Wrapper.js
- packages/strapi-admin/admin/src/containers/AuthPage/index.js
- yarn.lock
Use buffetjs buttons and fix alignments for
- Login
- Register
- Forget password
> Auth forms UI

- packages/strapi-admin/admin/src/translations/pt-BR.json
> adding pt-br missing keys for form validation

- packages/strapi-connector-bookshelf/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-hook-redis/package.json
- packages/strapi-plugin-email/package.json
- packages/strapi-plugin-graphql/package.json
- yarn.lock
> Upgrade rimraf

- packages/strapi-admin/admin/src/components/Logout/index.js
- yarn.lock
Change the back button path from administrator Editview to administrators Listview to avoid error.
> CTM back button - Administrator panel

- packages/strapi-plugin-content-manager/admin/src/components/FilterPickerOption/Input.js
Align add button which was too close to a select or date input
> CTM filters btn ui

- packages/strapi-helper-plugin/lib/src/components/LeftMenuList/List.js
- packages/strapi-helper-plugin/lib/src/components/LeftMenuList/index.js
- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationFormNaturePicker/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/attributes.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/index.js
This PR adds a restriction to relations attribute for single types and reduce the max height of the menu list to display only 5 elements.
> Single types/relations restriction

- docs/3.0.0-beta.x/guides/client.md
> Fix typos in third party client doc

- examples/getstarted/api/homepage/models/homepage.settings.json
- packages/strapi-plugin-content-manager/services/ContentTypes.js
- packages/strapi-plugin-content-manager/test/index.test.e2e.js
- packages/strapi-plugin-content-manager/test/single-type.test.e2e.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
- packages/strapi-plugin-content-type-builder/services/api-handler.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/schema-handler.js
- packages/strapi-plugin-content-type-builder/test/content-types.test.e2e.js
Depends on https://github.com/strapi/strapi/pull/5219
> Single types/kind switch

- packages/strapi-plugin-content-type-builder/admin/src/components/BooleanBox/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
- packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
- packages/strapi-plugin-content-type-builder/admin/src/translations/fr.json
This PR adds a notification on content type kind edition.
> Single types/fix edition

- packages/strapi-admin/admin/src/components/ListRow/index.js
- packages/strapi-admin/admin/src/components/Row/index.js
- packages/strapi-helper-plugin/lib/src/components/TrashButton/index.js
- packages/strapi-helper-plugin/lib/src/index.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/styledComponents.js
- packages/strapi-plugin-content-manager/admin/src/components/DynamicZone/index.js
- packages/strapi-plugin-content-manager/admin/src/components/FieldComponent/ComponentIcon.js
- packages/strapi-plugin-content-manager/admin/src/components/FieldComponent/ResetComponent.js
- packages/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/Banner.js
- packages/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/BannerWrapper.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/index.js
- packages/strapi-plugin-upload/admin/src/components/Li/index.js
- packages/strapi-plugin-users-permissions/admin/src/components/ListRow/index.js
Generalize trash icon and sizes
> Generalize all trash icon

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/utils/index.js
- packages/strapi-plugin-content-manager/test/fields/uid.test.e2e.js
Adds support for uids in database schemas
> UID field database schema

- packages/strapi-admin/index.js
fix #5234
ready to be merged
Modified how the development watcher script compute the destination path in the .cache folder to copy a file when it is updated or created. 
Instead of splitting the path using 'admin' or 'extensions' keywords, that may return confused value if absolute path contains those keywords, now the script split the path using absolute path of the admin or extensions folders.
> admin watcher improvement

- .prettierrc.js
- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-plugin-content-manager/test/fields/boolean.test.e2e.js
- packages/strapi-plugin-content-manager/test/fields/email.test.e2e.js
- packages/strapi-plugin-content-manager/test/fields/enumeration.test.e2e.js
- packages/strapi-plugin-content-manager/test/fields/json.test.e2e.js
- packages/strapi-plugin-content-manager/test/fields/password.test.e2e.js
- packages/strapi-utils/lib/__tests__/convertRestQueryParams.test.js
- packages/strapi-utils/lib/validators.js
- packages/strapi/lib/Strapi.js
- packages/strapi/lib/middlewares/boom/index.js
- packages/strapi/lib/services/__tests__/entity-validator.test.js
- packages/strapi/lib/services/entity-service.js
- packages/strapi/lib/services/entity-validator/index.js
- packages/strapi/lib/services/entity-validator/validators.js
This PR adds a new layer to validate input data for entry creation and update. This layer is taking a compatibility approach by allowing extra keys to be sent and adding some basic validations. 
We will be able to build from this foundation to make it even more robust in the futur.
> Init entity validator layer

- packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
> Fixes WYISIWYG update when used in a dynamic zone

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-plugin-content-manager/config/routes.json
- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-manager/controllers/validation/index.js
- packages/strapi-plugin-content-manager/controllers/validation/model-configuration.js
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-manager/services/ContentTypes.js
- packages/strapi-plugin-content-manager/services/__tests__/uid.test.js
- packages/strapi-plugin-content-manager/services/uid.js
- packages/strapi-plugin-content-manager/test/content-manager/uid.test.e2e.js
- packages/strapi-plugin-content-manager/test/single-type.test.e2e.js
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-content-type-builder/services/Components.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
- packages/strapi-plugin-content-type-builder/services/__tests__/__snapshots__/content-types.test.js.snap
- packages/strapi-plugin-content-type-builder/services/__tests__/content-types.test.js
- packages/strapi-plugin-content-type-builder/test/__snapshots__/content-types.test.e2e.js.snap
- yarn.lock
Adds routes to generate or check if a UID field value is available
> Add UID validation routes for CTM livechecks

- .github/PULL_REQUEST_TEMPLATE.md
I'm removing the labels checkbox from the PR body, not useful anymore.
> Delete labels from the PR body

- packages/strapi-admin/admin/src/components/LeftMenuLinkSection/index.js
- packages/strapi-helper-plugin/lib/src/components/LeftMenuList/index.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeRecursivePath/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/reducer.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/Initializer/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/Main/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeRecursivePath/index.js
- packages/strapi-plugin-content-manager/admin/src/translations/en.json
- packages/strapi-plugin-content-type-builder/admin/src/components/List/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ModalHeader/Icon.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ListView/index.js
Add a level to the recursive path. Now, the path to a content type will be : `/collectionType/:uid` and `/singleType/:uid`. Adapt the EditView (edit, create, delete, reset) to the single type case.
> Single types/content manager

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/guides/is-owner.md
Created a guide to restrict entry update for the author only.
> Add guide for isOwner policy

- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/reducer.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/ListView/index.js
- packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
- packages/strapi-plugin-content-type-builder/admin/src/utils/getAttributeDisplayedType.js
This PR fixes some small bugs regarding the `uid` feature.
> CTB small fixes

- packages/strapi-plugin-upload/admin/src/components/ModalHeader/BackButton.js
> Use theme in backbutton

- docs/3.0.0-beta.x/cli/CLI.md
edited some minor typos. Not a big deal, but this was the only thing I can contribute for now :)
> edited some minor typos

- docs/3.0.0-beta.x/concepts/policies.md
- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.md
- docs/3.0.0-beta.x/plugin-development/backend-development.md
- examples/getstarted/api/address/controllers/Address.js
> Single types migration guide and policy doc update

- docs/3.0.0-beta.x/content-api/api-endpoints.md
> Add single type endpoint doc

- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
This PR disabled the relation input in case of a polymorphic relation
Fixes #3247
> Fix polymorphic relations in the content manager

- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
This PR fixes the wrong `redirectUrl` when navigating between views in the content manager
> Fixes the wrong redirection in content manager

- packages/strapi-plugin-content-manager/admin/src/components/InputUID/Options/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
- packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
- packages/strapi-plugin-content-type-builder/controllers/validation/common.js
- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
> Add validations for duplicate enums

- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
Fixed bug #5266
When adding new content, select field was incorrectly wrapped
Signed-off-by: James Alvarez <jp [@] domainwink.com>
> Update div wrapper for SelectWrapper

- packages/strapi-plugin-content-manager/admin/src/components/InputUID/Options/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/index.js
- packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
Fixes #3864 
This PRs fixes the display of the polymorphic relations in the content type builder. However, it doesn't allow a user to create one. Furthermore, after manually creating a polymorphic relation a user cannot save the content type therefore all modifications will have to be made manually.
> Fixes #3864

- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
This PR prevents the browser from auto filling the password and username inputs.
Fixes #5053
> Fixes #5053

- packages/strapi-admin/admin/src/containers/Webhooks/EditView/tests/__snapshots__/index.test.js.snap
- packages/strapi-admin/admin/src/containers/Webhooks/ListView/tests/__snapshots__/index.test.js.snap
Signed-off-by: helabbassi <helabbassi@kilix.fr>
> Fix snapshot tests

- docs/3.0.0-beta.x/plugins/upload.md
- examples/getstarted/extensions/upload/config/settings.js
- examples/getstarted/package.json
- packages/strapi-plugin-upload/config/config.json
- packages/strapi-plugin-upload/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/schema.graphql.js
- packages/strapi-plugin-upload/controllers/Upload.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-plugin-upload/test/__tests__/bootstrap.test.js
- packages/strapi-plugin-upload/test/upload.test.e2e.js
- packages/strapi-provider-upload-aws-s3/.snyk
- packages/strapi-provider-upload-aws-s3/README.md
- packages/strapi-provider-upload-aws-s3/lib/index.js
- packages/strapi-provider-upload-cloudinary/.snyk
- packages/strapi-provider-upload-cloudinary/README.md
- packages/strapi-provider-upload-cloudinary/lib/index.js
- packages/strapi-provider-upload-local/.snyk
- packages/strapi-provider-upload-local/README.md
- packages/strapi-provider-upload-local/lib/index.js
- packages/strapi-provider-upload-rackspace/.snyk
- packages/strapi-provider-upload-rackspace/README.md
- packages/strapi-provider-upload-rackspace/lib/index.js
- packages/strapi-provider-upload-rackspace/package.json
This PR moves the upload provider config to a file. 
Right now you need to edit the config in the extensions folder `./extensions/upload/config/settings.json`. (doc is updated in the PR)
> Media lib/provider settings

- docs/3.0.0-beta.x/installation/platformsh.md
All is said in the title, there was an issue on the title format.
> Fix platform.sh steps titles

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row.js
> Fix uid display

- packages/strapi/lib/core/load-components.js
Fix missing schema error on beta.19 migration from mongo
> Fix component globalId

- packages/strapi/lib/services/entity-validator/index.js
Fix https://github.com/strapi/strapi/issues/5410
> Fix entity validator for media

- docs/3.0.0-beta.x/admin-panel/customization.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.md
- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
- packages/strapi-admin/admin/src/containers/Admin/index.js
Update the migration guide with the new admin configuration.
> Update migration guide

- packages/strapi-plugin-content-manager/utils/upload-files.js
- packages/strapi-plugin-upload/config/schema.graphql.js
- packages/strapi-plugin-upload/controllers/Upload.js
- packages/strapi-plugin-upload/models/File.settings.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-plugin-upload/services/__tests__/upload.test.js
- packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js
- packages/strapi-plugin-upload/test/upload.test.e2e.js
- packages/strapi/lib/services/utils/upload-files.js
- yarn.lock
Add fileInfo option to set a custom name / alternativeText and caption for a media
> Media lib/upload with infos

- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/utils/form.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/RowItem.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/tests/reducer.test.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/utils/createNewFilesToUploadArray.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/utils/tests/createNewFilesToUploadArray.test.js
This PR adds the file info to the edit modal
> Add file info

- packages/strapi-plugin-content-manager/admin/src/containers/ListSettingsView/index.js
> Fixes #5424

- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/MenuSection.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/Wrapper.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkHeader/SearchWrapper.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkSection/EmptyLinksListWrapper.js
- packages/strapi-admin/admin/src/components/LeftMenuLinkSection/LeftMenuListLink.js
- packages/strapi-admin/admin/src/containers/LeftMenu/Wrapper.js
This PR fixes some feedback regarding the left menu scrollbars.
> Fix menu scrollbar feedback from designer

- packages/strapi-generate-plugin/files/admin/src/index.js
This PR fixes the plugin generator for the front-end files.
> Fix plugin generator

- packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/types.test.js
- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/index.js
- packages/strapi-plugin-upload/config/config.json
- packages/strapi-plugin-upload/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/routes.json
- packages/strapi-plugin-upload/config/schema.graphql.js
- packages/strapi-plugin-upload/controllers/Upload.js
- packages/strapi-plugin-upload/controllers/media-types.js
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-upload/services/Upload.js
- yarn.lock
Add Upload allowed type parameter and option to replace an image
> Add Upload allowed type parameter and option to replace an image

- packages/strapi-utils/package.json
Update lodash depends in strapi-utils to fix https://www.npmjs.com/advisories/1065
> Update lodash to fix security issues

- docs/.vuepress/config.js
This PR adds the front-end settings API to the local plugins section of the documentation.
> Add front-end settings API to documentation

- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-plugin-upload/services/image-manipulation.js
This PR adds responsive formats to the upload plugin
Needs this PR to be merged first https://github.com/strapi/strapi/pull/5472
> Add responsive formats to the upload plugin

- packages/strapi-plugin-upload/controllers/Upload.js
- packages/strapi-plugin-upload/models/File.settings.json
- packages/strapi-plugin-upload/services/Upload.js
Some simple cleanups in the upload plugin
> Media lib/refactoring

- packages/strapi-plugin-upload/config/functions/bootstrap.js
- packages/strapi-plugin-upload/controllers/validation/settings.js
- packages/strapi-plugin-upload/test/__tests__/bootstrap.test.js
- packages/strapi-plugin-upload/test/upload.test.e2e.js
Remove videoPreview setting option. As we cannot preinstall a software to encode/decode video on the user system directly we will just open a way to add it programmaticaly for the users.
> Remove video preview setting

- docs/3.0.0-beta.x/installation/platformsh.md
> Correct Platform.sh name

- examples/getstarted/config/functions/bootstrap.js
- packages/strapi-plugin-upload/config/functions/bootstrap.js
- packages/strapi-plugin-upload/middlewares/upload/defaults.json
- packages/strapi-plugin-upload/middlewares/upload/index.js
- packages/strapi-plugin-upload/models/File.settings.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-provider-upload-cloudinary/lib/index.js
- packages/strapi/lib/Strapi.js
- packages/strapi/lib/middlewares/public/index.js
- yarn.lock
Media lib improvements for video preview
> Media lib improvements

- docs/3.0.0-beta.x/installation/digitalocean-one-click.md
Making the warning about the load up time on one-click deployments easier to see. Fixed a typo.
> Minor fixes to DO one-click docs

- packages/strapi-plugin-graphql/services/utils.js
When checking for diff in resolvers leave custom resolvers alone
> Fix: don't diff custom resolvers

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-bookshelf/lib/queries.js
- packages/strapi-connector-bookshelf/lib/relations.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/queries.js
- packages/strapi-connector-mongoose/lib/relations.js
- packages/strapi-database/lib/database-manager.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-utils/lib/__tests__/models.test.js
- packages/strapi-utils/lib/models.js
- packages/strapi/lib/Strapi.js
> Keep media order set on creation

- packages/strapi-connector-bookshelf/lib/buildQuery.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-utils/lib/convertRestQueryParams.js
> Treat mime ncontains as AND params in files list

- packages/strapi-plugin-upload/admin/src/components/CardControl/Wrapper.js
This PR needs to be merged after #5594
> Add hover state to controls

- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
This PR allows to download an uploaded file.
> Add download file option

- packages/strapi-connector-bookshelf/lib/generate-component-relations.js
> Fix bad singular form of column name

- packages/strapi-plugin-users-permissions/config/layout.js
Fix routing of user-permissions routes in content manager
> Fix rerouting of destroy route in user-perm

- packages/strapi-plugin-upload/admin/src/components/EditForm/FileWrapper.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/SizeBox.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/components/List/index.js
- packages/strapi-plugin-upload/admin/src/components/SelectedAssets/DraggableCard.js
- packages/strapi-plugin-upload/admin/src/components/VideoPreview/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-upload/admin/src/utils/formatBytes.js
- packages/strapi-plugin-upload/admin/src/utils/tests/formatBytes.test.js
This PRs fixes the img src by using the thumbnail when available.
> ML front improvements

- packages/strapi-plugin-graphql/services/build-aggregation.js
- packages/strapi-plugin-graphql/services/type-definitions.js
Implement Graphql Aggregation Feature for Bookshelf
> Implement Graphql Aggregation Feature for Bookshelf

- packages/strapi-connector-mongoose/lib/mount-models.js
> Fix ability to update unique constraints in mongoose

- packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/init.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/reducer.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPickerOption/Input.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPickerOption/index.js
This PR improves the content manager filter by replacing the text field with a select for the enumeration field.
> Fixes #5570

- packages/strapi-plugin-upload/admin/src/components/BrowseAssets/index.js
- packages/strapi-plugin-upload/admin/src/components/ListEmpty/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
This PR adds an empty result view to the plugin upload and the input media when there is no search result.
> Add empty view with filters

- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
> Fix fetch error

- packages/strapi-plugin-upload/admin/src/components/EditForm/FileDetailsBox.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/RowItem.js
Fix sizes for non uploaded files
> Fix sizes for non uploaded files (Edit file and Upload list)

- examples/getstarted/config/environments/development/server.json
- examples/getstarted/config/environments/production/server.json
- examples/getstarted/config/environments/staging/server.json
- packages/strapi-generate-new/lib/resources/files/config/environments/development/server.json
- packages/strapi-generate-new/lib/resources/files/config/environments/production/server.json
- packages/strapi-generate-new/lib/resources/files/config/environments/staging/server.json
- packages/strapi/lib/core/bootstrap.js
Fix host using lcoalhost not working on a lot of envs. I also added default env vars usage in all envs. 
Fix https://github.com/strapi/strapi-docker/issues/191
Fix https://github.com/strapi/strapi/issues/5652
> Fix host using localhost not working on a lot of envs

- packages/strapi-plugin-upload/admin/src/components/InputUploadURL/index.js
- packages/strapi-plugin-upload/admin/src/components/UploadForm/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
- packages/strapi-plugin-upload/admin/src/utils/getYupError.js
- packages/strapi-plugin-upload/admin/src/utils/index.js
- packages/strapi-plugin-upload/admin/src/utils/urlYupSchema.js
> Add url validation

- packages/strapi-helper-plugin/lib/src/utils/getFilterType.js
- packages/strapi-helper-plugin/lib/src/utils/tests/getFilterType.test.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
> ML small fixes

- packages/strapi-plugin-content-manager/controllers/ContentTypes.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/index.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/reducer.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/tests/reducer.test.js
Custom timestamps names for filters
> Custom timestamps

- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
> Fix refetch files on toggle

- docs/3.0.0-beta.x/concepts/controllers.md
- docs/3.0.0-beta.x/concepts/services.md
- docs/3.0.0-beta.x/guides/is-owner.md
Closes https://github.com/strapi/strapi/issues/5688 by update the docs.
> extract params from ctx before calling services

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
The BUG_REPORT.md issue template still had Node v10 as the LTS version, while the LTS version is now v12.
This PR updates it.
This is ready to be merged and does not contain any changes to the code.
> Update Node LTS version on BUG_REPORT.md to v12

- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/DateTime.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/FilterInput.js
> Fix date filter

- packages/strapi-helper-plugin/lib/src/components/HeaderSearch/index.js
- packages/strapi-plugin-upload/admin/src/components/CardControl/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/CardControl/index.js
- packages/strapi-plugin-upload/admin/src/components/CheckControl/CustomDropdownSection.js
- packages/strapi-plugin-upload/admin/src/components/CheckControl/index.js
- packages/strapi-plugin-upload/admin/src/components/DropdownSection/index.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/EmptyInputMedia.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/ModalHeader/BackButton.js
- packages/strapi-plugin-upload/admin/src/components/ModalNavWrapper/Hr.js
- packages/strapi-plugin-upload/admin/src/components/ModalTab/Count/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/ModalTab/Count/index.js
- packages/strapi-plugin-upload/admin/src/components/ModalTab/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/HeaderSearch.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/Search.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
Fix some UI issue in the media library
> Fix some UI issue in the media library
