- packages/plugins/sentry/server/middlewares/sentry.js
Since in Sentry the transaction name is used for grouping similar events, using `request.url` will create a new event for every unique path, so `/users/1` and `/users/2` will be different transactions.
This change will use the [matched route path](https://github.com/koajs/router/blob/1aead99e0e0fdb8666e9c6fa2f52b0463c622025/API.md?plain=1#L83), which could look sth like `/users/:id` making the transactions grouped together properly (i.e. per route).
> Use `ctx._matchedRoute` instead of `ctx.request.url` for Sentry transaction name

- packages/core/upload/admin/src/components/SelectTree/SelectTree.js
- packages/core/upload/admin/src/components/SelectTree/utils/getOpenValues.js
- packages/core/upload/admin/src/components/SelectTree/utils/getValuesToClose.js
- packages/core/upload/admin/src/components/SelectTree/utils/tests/getOpenvalues.test.js
- packages/core/upload/admin/src/components/SelectTree/utils/tests/getValuesToClose.test.js
Fixes the way the `SelectTree` component handles expanding/ collapsing its options. The previous implementation had various problems:
- `null` (root) could not be expanded
- options appeared in the wrong nesting order
- only children at the lowest depth level were opened
This PR reworks the overall logic and fixes all of the above errors.
https://user-images.githubusercontent.com/2244375/174140837-566c7c64-f152-4a11-bbf2-d46d5967a5f4.mp4
To properly support the tree select component.
> SelectTree: Fix collapsing/ expanding options with proper order

- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/hooks/tests/useAssets.test.js
- packages/core/upload/admin/src/hooks/tests/useFolders.test.js
- packages/core/upload/admin/src/hooks/useAssets.js
- packages/core/upload/admin/src/hooks/useFolders.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- Removed folder filter when searching to allow nested search
- Removed search param when clicking on a FolderCard to allow navigating in a folder after a search - if not the search query will always send the same result even after entering a new folder
Create nested folders with assets
Go to ML root and search for an asset in a nested folder
Without manually removing the search, navigate to a folder
See the folder result
> [ML folder] Search nested elements

- packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorStylesContainer.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js
> **Warning**
> To merge after [#13618](https://github.com/strapi/strapi/pull/13618).
Corresponding PR for https://github.com/strapi/design-system/pull/630. At the moment we are using the wrong system font identifier on apple devices. This PR fixes that for the richtext editor component.
To properly render the UI.
- https://github.com/strapi/design-system/pull/630
- https://github.com/strapi/design-system/issues/629
- Refs #13618
> Wysiwyg: Update system font-family

- packages/core/admin/package.json
- packages/core/admin/webpack.config.js
- Integrate `react-refresh` to `core/admin`. We do not need a full reload after updating the source code.
- It applies both for contributors (`cd packages/core/admin && yarn develop --watch-admin`) and plugins developers (build their own plugin)
- In saves us time after we hit the `Save` button.
=> Increase productivity of the developers => Make developers happy
- A table of comparison tested on my machine (Macbook 2019) after hitting Save in VSCode and when I see the change on Chrome:
|                        | Time to see updated UI | Preserve state |
| ---------------------- | ---------------------- | -------------- |
| Full Refresh (Current) | 4.01s                  | No             |
| Fast Refresh (This PR) | 1.02s                  | Yes            |
1.  Start the admin
```bash
cd …
```
> Integrate react-refresh to increase productivity

- jest.base-config.front.js
- jest.base-config.js
- package.json
- yarn.lock
-  This PR brings the following features when running Jest in pattern mode:
- Search a jest test file by their filename. 
- Navigate between search results.
- Before:
- After:
- This addition increases productivity while developing and testing.
- CI, please help me 😬
- Use `jest-watch-typeahead` version `0.6.5` since newest version `1.0.0` does not support `jest@26` (our current version). We can upgrade `jest-watch-typeahead` to `^1.0.0` after we upgrade `jest` to `^27`
Reference: https://github.com/jest-community/jest-watch-typeahead/releases/tag/v1.0.0
> [Jest] Add ability to search and navigate test file on watch mode

- packages/plugins/graphql/server/services/builders/filters/content-type.js
- packages/plugins/graphql/server/services/utils/mappers/graphql-filters-to-strapi-query.js
_Based on an original idea from @reimertz in #13267_
Adds support for filters on nested components in the GraphQL content API
Entity
```json
{
"kind": "collectionType",
"collectionName": "entities",
"info": {
"singularName": "entity",
"pluralName": "entities",
"displayName": "Entity"
},
"options": {
"draftAndPublish": false
},
"pluginOptions": {},
"attributes": {
"comp1": {
"type": "component",
"repeatable": false,
"component": "basic.comp1"
}
}
}
```
Comp1
```json
{
"collectionName": "components_basic_comp1s",
"info": {
"displayName": "Comp1",
"icon": "align-center"
},
"options": {},
"attributes": {
"comp2": {
"displayName": "Comp2",
"type": "component",
"repeatable": true,
"component": "basic.comp2"
}
}
}
```
Comp2
```json
{
"collectionName": "components_basic_comp2s",
"info": { …
```
> [GraphQL] Enable filtering on nested components

- packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeOption/BoxWrapper.js
Aligns the content within the AttributeOption component to the left.
While working on polish translations for the Admin panel I noticed that there's a problem with alignment for longer descriptions inside the component box (AttributeOption).
> fix(content-type-builder/attribute-option): align text to the left

- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/admin/src/translations/zh-Hans.json
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/index.js
- packages/core/helper-plugin/lib/src/components/SearchURLQuery/index.js
Adds tooltip functionality to the content-type builder's search button.
This is a missing feature, because in content-manager, the search button has tooltip. The code function is the same in both places, so it should be there in both, or neither.
You can see the tooltip on the button by passing the mouse over it.
> fix: content-types builder search button tooltip

- packages/core/admin/package.json
- yarn.lock
Currently all of our `webpack-*` dependencies are pinned. The project itself is pretty stable, widely used and follows semver. Therefore I don't see a reason why we should pin down the version. Keeping `webpack` and `webpack-dev-server` in sync also helps us, to reduce the total number of dependencies.
I've briefly tested the performance impact and it looks like as if the update would help safe users even more (~ 50MB on my machine) memory as before, aswell as ~0.5s of total time to build:
| before | after |
|-|-|
| ![before_upgrade](https://user-images.githubusercontent.com/2244375/177320003-5ccd6301-0dff-4e26-8cde-040101840603.png) | ![after_upgrade](https://user-images.githubusercontent.com/2244375/177319999-4cc253af-3974-46ad-bc86-53abf1f0c153.png) |
To keep dependencies up-to-date. …
> chore: Upgrade & unpin webpack dependencies

- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
- Fixed wrong color token for focused state
- Added box-shadow to error and focused state (to match DS inputs style)
> [ML Folder] SelectTree box shadow

- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/EmptyStateAsset.js
Fixes dropping files into media library input fields.
To properly support dragging and dropping files.
1. Use the "User" content type of the getstarted example
2. Drag & drop a file onto the picture field
- Fixes https://github.com/strapi/strapi/issues/13061
> MediaLibraryInput: Fix drag & drop events

- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
Similar to https://github.com/strapi/strapi/pull/13696 this PR fixes dropping files into the media library "From Computer" field.
To properly support dragging and dropping files.
1. Use the "User" content type of the getstarted example
2. Drag & drop a file onto the picture field
- Refs https://github.com/strapi/strapi/issues/13061
> FromComputerForm: Fix drag & drop events

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/hasContent.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/tests/hasContent.test.js
Fixes a bug, where relational cells without read permissions would crash the admin app, because an attribute that doesn't exist (`count`) was accessed without checking upfront.
To not crash the admin interface.
2. Create new role
3. Remove read permissions from `categories` field of the `Address` content-type for the custom role
4. Invite new user and assign them the new role
5. Login and navigate to the content-manager list-view
6. Before: The app would crash; After: the cell reports itself as empty
- Fixes https://github.com/strapi/strapi/issues/13413
> CellContent: Fix relations, if a user does not have read permissions

- packages/plugins/users-permissions/server/services/users-permissions.js
Fixes invalid default users-permissions permissions.
Default users-permissions permissions were invalid until now.
Without this PR drop the db and restart. Check invalid permissions are checked. Then restart and check some permissions got unchecked
On this PR. Drop the db and restart. Check  all permissions are valid and persist on the second restart
> Fix users-permissions default permissions

- packages/plugins/i18n/admin/src/components/LocalePicker/index.js
After changing the locale in the content-manager listview we currently preserve the current page, which could lead to problems, if that page does not exist in the selected locale.
This PR aims to fix that bug, by resetting the current page to 1, when the locale was changed.
Fixes the attached bug.
- Fixes https://github.com/strapi/strapi/issues/13673
> LocalePicker: Always set page to 1 after updating a locale

- packages/plugins/documentation/README.md
Remove text about the docs plugin not being published on npm
Because the docs plugin is published on npm
> Remove npm warning from documentation plugin readme

- packages/plugins/i18n/server/constants/iso-locales.json
- packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap
I've just added two new Individual Kurdish Languages
We need this two new languages since there were only Central Kurdish (CKB) available
The current test already cover the file I've changed so no other steps are needed
> Add two new kurdish languages

- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js
- packages/core/content-manager/server/controllers/content-types.js
This PR fixes the issue #13675 
The Content-type controller returns the same response object as the "findConfiguration" now.
This PR changes the response of the `PUT /content-types/:uid/configuration` to be the same as `GET /content-types/:uid/configuration`.
*In general it is a good practice for the REST APIs to have the same response object for `GET` and `PUT` for the same route with the `PUT` returning modified resource.*
As described in the linked issue, attempting to change view configuration for a single-type entry will fail if the entry contains components.
What happens is that the `PUT /content-types/:uid/configuration` responds with only half of the data that the "Admin" UI package needs for correct behaviour. And the `updateLayout` method simply hardcodes the missing piece with …
> Make updateContentTypeConfiguration endpoint return full data

- packages/core/database/lib/migrations/index.js
Fix the error `Original error: db.getConnection(...).transaction is not a function` on adding any migration(.js, .sql) file under `database/migrations` folder. Verified on postgres.
On adding any sql or js file under `database/migrations`, the error `Original error: db.getConnection(...).transaction is not a function` display and migration doesn't takes place. This will fix the error and make the migration successful.
https://forum.strapi.io/t/database-migration-deployment-questions/434/42
> fix: knex transaction error on adding the migrations in migration folder 

- packages/core/admin/admin/src/pages/App/index.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/index.js
Adds `environment` property to admin telemetry calls so that we can establish in what environment admin telemetry calls happen
At the moment we only send environment with server telemetry calls, but not the admin. Hence, there are a lot of events that we see that don't have an environment associated with them. Having an environment on all calls will allow us to filter them better.
> Add environment property to admin telemetry calls

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
- packages/core/admin/admin/src/content-manager/utils/removeKeyInObject.js
- packages/core/admin/admin/src/content-manager/utils/tests/removeKeyInObject.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/index.test.js
- packages/core/admin/package.json
- packages/core/admin/webpack.alias.js
- packages/core/admin/webpack.config.js
- packages/core/helper-plugin/package.json
- yarn.lock
https://github.com/strapi/strapi/pull/13579 made me curious why we do have `moment-js` next to `date-fns` in our codebase. Turns out: only because of one call that can easily be replaced by `date-fns`. This should [remove approx. 290kb / 70kb (gzipped) from the frontend bundle](https://bundlephobia.com/package/moment@2.29.4) and makes it clear that we are using `date-fns` primarily for handle dates.
|Before|After|
|-|-|
| <img width="1512" alt="Screenshot 2022-07-08 at 13 36 45" src="https://user-images.githubusercontent.com/2244375/177984952-fadf193a-19e0-4b1a-aac2-191de992e466.png"> | <img width="1512" alt="Screenshot 2022-07-08 at 13 37 00" src="https://user-images.githubusercontent.com/2244375/177984982-cc7072a4-5cc2-45f3-8de4-64cff4a2bc0c.png"> |
I think it is safe to remove the …
> Replace remaining moment-js calls with date-fns

- packages/core/upload/server/middlewares/upload.js
https://github.com/strapi/strapi/issues/13737 mentioned a typo in the upload middleware, which is fixed by this PR.
To properly support the `localeServer` option: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration
🤷🏼 
- Refs https://github.com/strapi/strapi/issues/13737
> Upload: Fix typo in upload middleware

- packages/providers/upload-aws-s3/README.md
Added information, that this upload provider works also with S3 compatible services. I tested it with scaleway.com
Adds information, that this upload provider works also with S3 compatible services. I tested it with scaleway.com
Make clear, that this provider is also working with S3 compatible services, not only AWS S3
Uploaded images to, and deleted from scaleway.com S3 service
> Added config info about S3 compatible services

- packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
- packages/core/upload/admin/src/translations/en.json
If a file upload fails we currently display a generic error message which is not helpful to the user and doesn't support custom error messages thrown by controllers in the API.
This PR displays the error message thrown in the API and makes it translateable.
To properly give feedback to our users, on what went wrong and to allow developers to display custom error messages.
1. Limit the filesize of uploads using https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration
2. Upload a file with a larger size than configured
3. See the proper error message
- Fixes https://github.com/strapi/strapi/issues/13767
> ML: Display proper error message thrown by the API

- packages/core/content-type-builder/admin/src/components/FormModal/attributes/types.js
- packages/core/content-type-builder/admin/src/translations/en.json
- packages/core/strapi/lib/core/domain/content-type/validator.js
Builds on top of https://github.com/strapi/strapi/pull/13503, to improve the enum values validation in the admin UI. Instead of testing each value directly this PR tests the `regressed` value. This will allow more values and only fail on the ones that GraphQL can not deal with.
It helps to prevent crashing Strapi at the bootstrap phase, after a new invalid value has been added to an enum field in the admin UI.
1. Navigate to CTB
2. Add a new enum field to a content-type
3. Add invalid values (such as `--1`)
4. Validate a frontend validation error is shown
- Refs https://github.com/strapi/strapi/pull/13503
- Fixes https://github.com/strapi/strapi/issues/13428
> CTB: Improve UI validation for enum values

- .github/workflows/adminBundleSize.yml
This PR adds a new check/ report to PRs, which modified either:
- files on which the admin build depends
- dependencies
All PRs, which only modify backend code, won't see the report. It will report the final gzipped bundle size to the PR and is based on the [compressed-size-action](https://github.com/preactjs/compressed-size-action) maintained by the preact team. It doesn't require any data to store, because it runs twice: the PR branch and the master branch and compares both results. [Example output](https://github.com/preactjs/preact/pull/3603#issuecomment-1173062288).
This will help us to monitor the impact of e.g. dependency updates on the bundle size of the frontend. @alexandrebodin and I briefly discussed whether we should setup a new test-app for each run, but I don't think it is …
> Github: Add admin bundle-size PR reporter

- packages/core/admin/webpack.config.js
- packages/core/helper-plugin/webpack.config.js
Currently sourcemaps are disabled even in the development environment, which makes debugging sometimes very hard. This PR:
- enables sourcemaps for development environments in `admin`
- fixes sourcemaps for the helper-plugin
|-|-|
| <img width="1256" alt="Screenshot 2022-07-19 at 14 39 25" src="https://user-images.githubusercontent.com/2244375/179752905-1d3122a9-cae2-466c-a714-003e189fc0b2.png"> | <img width="1256" alt="Screenshot 2022-07-19 at 14 38 32" src="https://user-images.githubusercontent.com/2244375/179752922-96f12c57-73a1-4226-ba60-8bd63dc29d3a.png"> |
Sourcemaps are very valuable for every developer, to understand where an error occurred. 
Run the development enviroment and make a mistake somewhere: you will see the proper files being referenced in the error …
> Fix sourcemaps for development environments

- packages/core/admin/admin/src/pages/App/index.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/index.js
Adds environment property to the admin analytics calls the correct way. Previously I have passed `process.env.NODE_ENV` to the analytics calls, but due to how we build our admin panel, `NODE_ENV` will always be `production`. This fix changes the behavior to the correct one.
Fixes this PR https://github.com/strapi/strapi/pull/13765
> Add environment to the admin analytics calls the correct way

- packages/plugins/documentation/README.md
Some file paths in the Readme of the Documentation Plugin seem to use the old v3 file structure. I updated the entries that initially confused me, but there might be other stuff which needs to be updated in the Readme. Feel free to extend it if needed :)
> Documentation Plugin: update file paths in Readme to v4 structure

- packages/core/admin/admin/src/index.js
- packages/core/admin/admin/src/pages/Admin/index.js
- packages/core/admin/webpack.config.js
- packages/core/content-type-builder/admin/src/pages/App/index.js
- packages/core/content-type-builder/admin/src/pages/RecursivePath/index.js
- packages/generators/generators/lib/files/plugin/admin/src/index.js
In https://github.com/strapi/strapi/pull/13785, where I wanted to setup a admin bundle-size reporter, I realized that we have many unnamed chunks.
1. Which is bad for long-term caching
The name of the chunks might change, based on the overall chunk configuration and therefore be different on each deployment. That means users may need to download these over and over again, eventhough nothing has changed with their content.
2. Which makes it impossible to track the bundle-size
Renamed chunks are being reported twice: deleted and added, which makes the report unusable. To track the size of a file over time, it should not be renamed.
This PR should fix all cases missing from the admin bundle. However: there are more unnamed chunks. I don't fully understand yet, where there are coming from - I …
> Admin: add missing webpack chunk-names

- packages/core/database/lib/query/helpers/where.js
- packages/core/strapi/tests/filtering.test.e2e.js
- packages/plugins/graphql/server/services/builders/filters/operators/eqi.js
- packages/plugins/graphql/server/services/builders/filters/operators/index.js
- packages/plugins/graphql/server/services/constants.js
- packages/plugins/graphql/tests/crud.test.e2e.js
This PR will add a new operator `$eqi` to perform an case insensitive equal comparison.
Currently in strapi, we have equal(`$eq`) - case sensitive and $constainsi as contains(case insensitive) operator. However in some of the scenarios, we need the equal operator with case insensitive(Specially to compare the url names or parameters). 
To  filter using case insensitive equal operator.
Add the `$eqi` to any filter query - similar to `$eq`
Provide information about the environment and the path to verify the behavior.
> fix: added new eqi operator for case insensitive equal search

- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/ModalForm.js
Fixes a bug, where the label and description of dynamiczones couldn't be edited any longer. 
To support adding a custom label + description to dynamiczone fields.
1. Navigation to "configure the view" in the content-manager
2. Edit a dynamiczone field and validate "label" and "description" are displayed
- Fixes https://github.com/strapi/strapi/issues/13407
> CM: Fix edit form for dynamiczones (allow label + description)

- jest.base-config.front.js
- package.json
- yarn.lock
With Alex we recently discovered: the frontend tests are setup using the swc/node transform. The recommended setup is using [`swc/jest`](https://swc.rs/docs/usage/jest) instead. This might help us fixing the jest snapshot bugs we recently discovered.
It also unifies the `jest-*` version numbers, which has been forgotten in https://github.com/strapi/strapi/pull/13787.
🔥 This PR get's rid of the explicity `typescript` dependency.
Properly setup tests.
It tests itself running `yarn test:front`
> Jest: Replace @swc/node-jest with @swc/jest transform

- packages/core/utils/lib/__tests__/visitors.test.js
- packages/core/utils/lib/sanitize/visitors/remove-restricted-relations.js
`removeRestrictedRelations` now uses the value of `populateCreatorFields` to determine if `createdBy` and `updatedBy` should be removed, rather than checking the `'admin::user'` permission for those creator fields.
Creator fields were available in v3, but in v4 `createdBy`and `updatedBy` fields are no longer available in the API when `populateCreatorFields` is true, because they are being removed when the user does not have `'admin::user'` permissions (which cannot be granted in the admin)
- Create a content type 
- create an item of that type
- set the content type config `options.populateCreatorFields` to `true`
- without this PR, the REST API still does not return the createdBy user
- with this PR, the REST API will return the createdBy user (same functionality as v3)
Unit tests for …
> Fix creator fields in REST API

- packages/plugins/users-permissions/package.json
- yarn.lock
The hunt for moment-js continues. After we removed our explicit dependency on it in https://github.com/strapi/strapi/pull/13728 I wanted to know why we are installing sequelize, redis, mongoose, moment and moment-timezone ..., which are heavy dependencies. Turns out: they call come from `koa2-ratelimit`.
In version 1.0 they have moved these dependencies into peerDependencies, which helps us to remove a lot of implicit dependencies and therefore reduce installation size.
🔥  This PR reduces the installation size of the users-permissions plugin by about 2MB / 360kb (minified + gzipped).
[Before 754.3kB (minified + gzipped)](https://bundlephobia.com/scan-results?packages=@strapi/helper-plugin@4.2.3,@strapi/utils@4.2.3,bcryptjs@2.4.3,grant-koa@5.4.8,jsonwebtoken@8.1.0,koa2-ratelimit@0.9.0,lodas …
> chore: Update koa2-ratelimit to 1.1.1

- package.json
- yarn.lock
We are using `jest@28.x` now and are able to update the version of `jest-watch-typeahead` too. It still works with the new version of jest, but creates a peer dependency warning.
Run `yarn test:front:watch` and use the file pattern matcher.
> chore: Bump jest-watch-typeahead to 2.0.0

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
I forgot to properly pass down `getTrad` for all `getAPIInnerErrors` calls - this PR fixes that.
Otherwise we'd see errors.
- Fixes https://github.com/strapi/strapi/issues/13853
> EditViewDataManagerProvider: Fix missing params getAPIInnerErrors

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
Currently we convert `0` to `null`, when a field of type `number` is saved. This PR excludes `0` from the conversion. I'll try to open a follow-up PR to add more tests for these cases.
Bug was introduced in https://github.com/strapi/strapi/pull/13313
To properly support `0` for number fields.
See issue attached.
- Fixes https://github.com/strapi/strapi/issues/13859
> EditViewDataManagerProvider: Ensure 0 is not converted to null

- packages/core/upload/server/services/folder.js
- packages/core/upload/tests/admin/folder-file.test.e2e.js
It allows the user to delete files.
Fix https://github.com/strapi/strapi/issues/13870
To fix the deleting issue
1. Select a file in the ML
2. Click _delete_
3. See the file correctly been delete
+ there is a test now
https://github.com/strapi/strapi/issues/13870
> Fix the bulk delete of files in the Media Library

- packages/core/admin/admin/src/content-manager/components/SelectOne/SingleValue.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/Option.js
Adds `flex-shrink: 0` to draft/ publish bullet indicators in relations and unifies their colors (might be a leftover from v3).
Proper styling of relations.
Use the kitchensink example, if has everything you need
|Before|After|
|-|-|
| <img width="240" alt="Screenshot 2022-07-28 at 12 25 24" src="https://user-images.githubusercontent.com/2244375/181483952-567ab87c-2566-4dc9-8ab0-0b340148e253.png"> | <img width="240" alt="Screenshot 2022-07-28 at 12 24 54" src="https://user-images.githubusercontent.com/2244375/181483954-2d02c517-4488-47d1-8dd8-8e9e7bb1ef9f.png"> |
> **Note**
> Please ignore the background-color, which will be fixed [by another PR](https://github.com/strapi/strapi/pull/13878).
|Before|After|
|-|-|
| <img width="240" alt="Screenshot 2022-07-28 at 12 25 57" …
> Relation: Fix skewed draft/ publish bullet indicator

- packages/core/admin/admin/src/content-manager/components/SelectOne/index.js
- packages/core/admin/package.json
In https://github.com/strapi/strapi/pull/13073 I forgot to apply the new `ReactSelect` component to `SelectOne` and did it only for `SelectMany`, which leads to missing styles.
This PR:
- uses `ReactSelect` as base component for `SelectOne` instead the the default from `react-select`
- removes `react-select` from `admin` dependencies, since it is now only a dependecy for the `helper-plugin`
- removes the `styles` prop; I could not find any instance on where this would get passed on
Styling regressed in 4.3.
You can use use the kitchen-sink example in dark-mode.
- Refs: https://github.com/strapi/strapi/issues/13868
> SelectOne: Fix component styles

- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/core/upload/admin/src/pages/App/tests/MediaLibrary.test.js
While testing https://github.com/strapi/strapi/issues/13892 I've realized we display the bulk select checkbox, eventhough there are not assets or folders, which looks odd.
To have a clean initial interface.
> ML: Hide bulk actions if not assets or folders exist

- packages/core/admin/package.json
- packages/core/admin/webpack.alias.js
- packages/core/content-type-builder/admin/src/components/ComponentIconPicker/index.js
- packages/core/content-type-builder/admin/src/components/ComponentIconPicker/utils/getIndexFromColAndRow.js
- packages/core/content-type-builder/admin/src/components/ComponentIconPicker/utils/tests/getIndexFromColAndRow.test.js
- yarn.lock
This PR replaces the one instance of `react-virtualized` we have with `react-window`. Why?
- `react-virtualized` is not maintained any longer
- `react-virtualized` won't work with react@18 and creates a peer dependency warning for react 17 already
- `react-virtualized` has a much larger bundlesize ([118kB/ 27.4kB](https://bundlephobia.com/package/react-virtualized@9.22.3) vs [24.4kB/ 6.3kB](https://bundlephobia.com/package/react-window@1.8.7))
I've increased the number of icons per row a bit and reduced their size, so that they fit better (imo).
|Before|After|
|-|-|
| <img width="849" alt="Screenshot 2022-07-29 at 12 09 16" src="https://user-images.githubusercontent.com/2244375/181737133-1e828a46-9f34-414e-aeb6-c473ccf73916.png"> | <img width="849" alt="Screenshot 2022-07-29 at 12 07 48" …
> ComponentIconPicker: Replace react-virtualized with react-window

- packages/core/upload/admin/src/components/AssetDialog/DialogHeader.js
- packages/core/upload/admin/src/components/AssetDialog/index.js
- packages/core/upload/admin/src/components/AssetDialog/tests/DialogHeader.test.js
Currently loading the folder structure in the `AssetDialog` does not properly take the `canRead` permission into account, which leads to request retries, if the user does not have the permissions, as reported in https://github.com/strapi/strapi/issues/13892
To properly support `canRead` permissions.
- Remove read permissions for a user
- Try to open the asset modal in the content manager
- Refs https://github.com/strapi/strapi/issues/13892
> AssetDialog: Properly take canRead permissions into account

- packages/core/content-manager/server/tests/api/basic-dz.test.e2e.js
- packages/core/content-manager/server/tests/api/populate-dz.test.e2e.js
- packages/core/utils/lib/convert-query-params.js
- packages/plugins/graphql/server/services/builders/dynamic-zones.js
It changes the populate process for dynamic-zones.
Instead of assigning the attributes in a fake schema, it does the populate for each component of the dz and then depp merge the results together.
It is better but still not perfect as there is no granularity on which component to populate exactly (ie if 2 components have the same field names, we cannot populate only one, the 2 would be populated). That seems however reasonable to not address this issue for the moment
To fix this issue : https://github.com/strapi/strapi/issues/11955
A test was added
fix https://github.com/strapi/strapi/issues/11955
https://github.com/strapi/strapi/issues/11909
> Better handle populating of dynamic-zones

- examples/getstarted/src/plugins/mycustomfields/admin/src/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/index.js
- packages/core/content-type-builder/admin/src/utils/formAPI.js
- Creates a `makeCustomFieldValidator` to build the yup schema object from user registered validation
- Run examples/getstarted with `--watch-admin` 
- Go to any content type, choose add another field, go to the custom tab, click the color custom field
- Don't fill the form and hit finish, you should get a validation error on both inputs. The error message on the custom field should be what's registered in examples/getstarted
- Name the field something that already exists on the content type, you should get a validation error
> [Custom Field] Add validation

- packages/generators/app/lib/resources/templates/js/admin-config.template
- packages/generators/app/lib/resources/templates/ts/admin-config.template
**What it does?**
It modifies the config file of the newly created project.
**Why is it needed?**
To avoid the warning message when creating a strapi app:
The config should point to the env var from the beginning.
> Add apiToken.salt directly in the config of created projects

- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/index.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.js.snap
- yarn.lock
Updates the `SubNav` component in the CTB, to make use out of [recently introduced props](https://github.com/strapi/design-system/pull/635), which aim to improve the overall vertial rhythm and properly indents components.
Improves the UI.
|-|-|
| <img width="868" alt="Screenshot 2022-08-02 at 13 12 10" src="https://user-images.githubusercontent.com/2244375/182362007-9ae7833b-3be4-4c06-aa3f-353a33dd9476.png"> | <img width="868" alt="Screenshot 2022-08-02 at 13 12 00" src="https://user-images.githubusercontent.com/2244375/182362026-417509eb-9b47-4afb-af8f-e620f2923bbb.png"> |
- Fixes https://github.com/strapi/design-system/issues/637
- Builds on top of https://github.com/strapi/strapi/pull/13799
> CTB: Update SubNav styles using improved DS properties

- packages/utils/typescript/lib/utils/get-config-path.js
- packages/utils/typescript/lib/utils/is-using-typescript-sync.js
- packages/utils/typescript/lib/utils/is-using-typescript.js
Make sure getConfigPath does not check ancestors when searching for the typescript configuration file
Because ts.findConfigFile looks in the given directory's ancestors to find the configuration file, Strapi projects can incorrectly detect JS project as TS projects.  
- Create a tsconfig.json file in a directory
- Run yarn create strapi-app app --quickstart
- It should detect the project is a JavaScript one and start normally
fix https://github.com/strapi/strapi/issues/13866
> Fix false positive results for ts utils' getConfigPath

- packages/utils/typescript/lib/utils/get-config-path.js
Update the return value of the ts `getConfigPath` util.
getConfigPath should always return a string or undefined, but it was possibly returning a boolean.
fix https://github.com/strapi/strapi/pull/13937
> Fix invalid return for ts get-config-path

- packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
- packages/core/upload/admin/src/translations/en.json
Currently the UI crashes if the `UploadingAssetCard` does not receive a standard strapi error, if e.g. a proxy returns an early error. The issue was reported in https://github.com/strapi/strapi/issues/13867 and introduced by https://github.com/strapi/strapi/pull/13768.
This PR handles error messages more gracefully and displays a generic error message instead of crashing the UI.
To not crash the UI, if a proxy is used in front of a strapi instance.
- Fixes https://github.com/strapi/strapi/issues/13867
> Upload: Handle file upload errors gracefully

- packages/plugins/graphql/package.json
- yarn.lock
While looking at https://github.com/strapi/strapi/pull/13954 I realized we are not using `@apollo/federation` anywhere. This PR removes the dependency.
Keep dependencies clean.
- https://github.com/strapi/strapi/pull/13954
> GraphQL: Remove unused @apollo/federation dependency

- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/tests/formatLayouts.test.js
- packages/core/admin/admin/src/content-manager/utils/formatLayoutToApi.js
With https://github.com/strapi/strapi/pull/13979 `editRelations` were removed, which breaks parts of the CM. This PR removes more code for the special treatment of relations in the content-manager.
This will unblock QA for https://strapi-inc.atlassian.net/browse/CONTENT-208
- https://github.com/strapi/strapi/pull/13979
- https://github.com/strapi/strapi/pull/13821
> CM: Remove editrelations from useFetchContentTypeLayout

- _travis/mysql.cnf
Since @alexandrebodin is doing some repo cleanup, it might be a good chance to get rid of this legacy travis config file. It is the second file after the `.github` directory on the github overpage page and annoys me a lot.
To have a clean repository, file structure.
> Chore: Remove legacy travis config file

- packages/core/upload/server/controllers/content-api.js
- packages/core/upload/tests/content-api/upload-automatic-folder.test.e2e.js
Fixes #13999.
Uploading multiple files via API only moves the first file to the _API Uploads_ folder instead of all of them.
Try uploading multiple files via API and notice that all end up in the appropriate folder.
#13999
> Generate fileInfo for every file when uploading in bulk

- packages/core/admin/admin/src/components/LeftMenu/index.js
add badge to link in plugins sections so plugin developers can add  badge near link. like in settings if new strapi release is available 
it is cool to have the available to add this badge
to use and test it you need to add `badge` key to `app.addMenuLink` in register function:
`path: plugins/{your-plugin-name}/admin/src/index.js`
```javascript
//....
register(app) {
app.addMenuLink({
to: `/plugins/${pluginId}`,
badge: "v4.3.2", <--- this what you need to add cool badge 
icon: PluginIcon,
intlLabel: {
id: `${pluginId}.plugin.name`,
defaultMessage: 'Documentation',
},
//...
```
> add badgeContent to pluginsSectionsLinks

- examples/getstarted/package.json
- examples/kitchensink-ts/package.json
- examples/kitchensink/package.json
- yarn.lock
1. Updates @strapi/strapi dependency in the kitchensink-ts example
2. Remove @strapi/admin dependency from examples/* (it is now a dependency of @strapi/strapi
Our current lockfile contains a reference to @strapi/admin@4.2.2, which was introduced as part of the [Typescript feature branch](https://github.com/strapi/strapi/pull/12789). This is because, the kitchensink-ts example had a dependency on @strapi/strapi@4.2.
Check the lockfile changes.
- https://github.com/strapi/strapi/pull/12789
> Chore: Update @strapi/* dependencies in examples

- packages/core/helper-plugin/lib/src/components/ReactSelect/Async/Async.js
- packages/core/helper-plugin/lib/src/components/ReactSelect/Async/index.js
- packages/core/helper-plugin/lib/src/components/ReactSelect/index.js
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
- packages/core/helper-plugin/lib/src/index.js
Exports the `react-select/async` component from `react-select` and applies our default styles.
To support `react-select/async` to relation components at some point.
> ReactSelect: Export styled async component from react-select

- packages/core/admin/server/routes/webhooks.js
Fixes #13970 by adding missing policies to the affected route.
Admins can trigger webhooks even if they don't have permission to do so.
Replicate the process outlined in #13970 and notice that you get a policy error.
> Add missing permissions to webhook triggering endpoint

- packages/core/content-manager/server/services/entity-manager.js
It populates the folder field for media
To fix #13887
1. upload a file inside a folder
2. create a content-type entry with this file
3. open this entry, edit the file
4. see the correct location displayed
#13887
Congrats @ronronscelestes for spotting the cause of the issue
> Fix wrong file location when editing a file from the content-manager

- packages/core/upload/admin/src/components/AssetDialog/index.js
when investigating this issue #13887 I found that:
`parentFolderId` wasn't properly given to `EditFolderDialog` in `AssetDialog` causing not showing the current folder location when editing a folder in the content-manager modal
#14040 will fix the edit asset issue.
**before:**
**after:**
- Browse folders/assets in the content-manager
- Edit a folder
- See current folder location as default value in the location select
> [Fix] Folder location AssetDialog

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/CollapsableContentType/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ContenTypesSection/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/Permissions/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ProtectedEditView/index.js
- When the user has read permissions on Api token, they can view the edit page of Api token but with disabled inputs if they don't have the update permission.
- When the user has read permissions and create permissions, they will see the tokens page after creating a token and not be redirected to Admin panel main page
Should satisfy the following criterias:
> make user able to see token details if they have read permissions

- packages/core/strapi/lib/middlewares/cors.js
It fixes invalid CORS headers returned by default by strapi middleware.
Because the combination of `Access-Control-Allow-Credentials: true` and
`Access-Control-Allow-Origin: *` is illegal and requests can be blocked by browsers.
https://stackoverflow.com/questions/70639958/strapi-v4-throwing-cors-exception
> Fix CORS response headers.

- packages/plugins/users-permissions/server/controllers/auth.js
Put missing code back that got drop in a merge conflict probably
Fixes https://github.com/strapi/strapi/issues/14069
> Put missing code back

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/utils/connect.js
Adapts the `ADD_RELATION` and `REMOVE_RELATION` reducers to the new data-structure, where we only want to send the diff (added and removed relations).
We only want to send added and removed relations to the backend. 
No real world usage yet - will be possible once the component is ready.
> EditViewDataManagerProvider: Implement new relation data structure

- packages/core/content-manager/server/tests/api/populate-dz.test.e2e.js
- packages/core/database/lib/query/helpers/populate.js
Ignore instead of throwing an error when a query tried to populate a scalar attributes
NB: it is already this behavior when trying to populate an attribute that doesn't exist
To avoid error 500 in certain usecases.
Example : 
When 2 components in a dynamic zone have the same field name but one is a relation and the other is a string.
The test was updated
> Ignore if populating a scalar attribute

- package.json
- packages/admin-test-utils/lib/setup/test-bundler.js
- packages/admin-test-utils/package.json
- packages/core/admin/admin/src/components/LanguageProvider/tests/index.test.js
- packages/core/admin/package.json
- packages/core/admin/webpack.config.js
- packages/core/content-type-builder/package.json
- packages/core/email/package.json
- packages/core/helper-plugin/package.json
- packages/core/helper-plugin/webpack.config.js
- packages/core/strapi/package.json
- packages/core/upload/package.json
- packages/plugins/documentation/package.json
- packages/plugins/i18n/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
- Needs  https://github.com/strapi/strapi/pull/14017 to be merged 1st
- Does a bunch of dependencies changes and cleanups to fix warnings and errors
- Very obvious :D 
you can try the experimental release of these changes with `npx create-strapi-app@experimental my-app`
> chore: dependency updates

- packages/core/strapi/lib/services/entity-service/__tests__/entity-service-events.test.js
- packages/core/strapi/lib/services/entity-service/index.js
- packages/core/upload/server/services/upload.js
- packages/providers/upload-cloudinary/lib/index.js
- Properly reject and throw an error when there is an issue uploading a file to cloudinary.
@gvocale provided the [solution](https://github.com/strapi/strapi/issues/13316#issuecomment-1183230884) for the issue already.
Cloudinary errors were not handled properly, and the server was crashing.
- Have a Cloudinary account for the provider options ( ask me if you need some and feel lazy ). Add them to the plugin configuration.
- Upload a pdf bigger than 10Mb in the media folder (Cloudinary free tier limit) ([PDF I used](https://cartographicperspectives.org/index.php/journal/article/view/cp13-full/pdf))
You should see this error when trying to upload it:
- When rejecting the promise with the `PayloadTooLargeError` error (or any other) I see this log on the console:
```
info: In application …
```
> properly reject promise in cloudinary provider

- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
With the `editRelations` cleanup done in https://github.com/strapi/strapi/pull/14013 and https://github.com/strapi/strapi/pull/13982 `queryInfos` were no longer passed to relational fields in the `EditView`. This information is needed to properly fetch data from the internal content API.
Relation fields need `queryInfos` to perform requests.
> CM: Pass queryInfos to Inputs, to have it available for relations

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/components/LogoInput/tests/index.test.js
Adds a timeout for logo update tests that failed because of waitFor timeouts due to axios.get being called.
A future approach would be to mock axios for those tests instead.
`yarn test:front`
/
> Setup timeout for logo update page due to slow image fetching

- .eslintrc.back.js
Every PR has now a list of attached eslint warnings, which clutters them quite a bit. This PR adds eslint-ignore comments to each call to reduce that cluttering.
An alternative would be to disable the warnings globally, but I think it is a good idea to leave it on.
Less warnings. They were introduced by https://github.com/strapi/strapi/pull/14017
> Chore: Ignore process.exit eslint warnings

- examples/getstarted/src/plugins/mycustomfields/admin/src/components/ColorPicker/ColorPickerInput/index.js
- examples/getstarted/src/plugins/mycustomfields/admin/src/index.js
- examples/getstarted/src/plugins/mycustomfields/admin/src/translations/en.json
- examples/getstarted/src/plugins/mycustomfields/server/register.js
- packages/core/admin/admin/src/content-manager/components/FieldTypeIcon/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FormModal.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
Apply custom-field defined settings in the Edit view.
- Show custom field icon on the edit attribute modal in the "edit the view" page
- Display attribute options on custom field component to make sure they're accessible via the props
- Update the example color custom field to use string instead of text
To make custom fields behave like other fields in the content manager
- Edit an attribute using the color custom field to try both hex and rgba options. The format should be displayed on the edit view input component
- Use the CM "edit view" button to add a description and move or resize the field
To be reviewed/merged after #14130
> [Custom fields] Apply content manager settings on custom fields

- README.md
adds the badge to the readme on the nightly build status
Looks Pretty :)
Look at the readme of this branch
N/A
> Add Nightly Release build status badge

- packages/core/admin/admin/src/content-manager/hooks/useRelation/index.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
This PR implements a new `useRelation()` hook, which can be used to fetch and search relations for a given field. It leverages [`useInfiniteQuery()`](https://tanstack.com/query/v4/docs/guides/infinite-queries), to avoid re-renders because of internal state changes.
To create an utility which allowes us to fetch remote relations. By isolating it, we make it testable and re-usable, in case the community needs access to it one day.
Rely on the automated tests.
This builds the data-fetching foundation for https://github.com/strapi/strapi/pull/14092 and on top of a previous POC https://github.com/strapi/strapi/pull/14082
> CM: Implement useRelation hook to fetch relation data asynchronous

- examples/getstarted/src/api/kitchensink/content-types/kitchensink/schema.json
- examples/getstarted/src/plugins/mycustomfields/admin/src/components/ColorPicker/ColorPickerInput/index.js
- examples/getstarted/src/plugins/mycustomfields/admin/src/index.js
- examples/getstarted/src/plugins/mycustomfields/admin/src/translations/en.json
- examples/getstarted/src/plugins/mycustomfields/server/register.js
- packages/core/admin/admin/src/content-manager/components/FieldTypeIcon/index.js
- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FormModal.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
- Lazy loads a custom field's input component in the content manager's edit view
- Updates the sample color picker component as a POC
- Show custom field icon on the edit attribute modal in the "edit the view" page
- Display attribute options on custom field component to make sure they're accessible via the props
To integrate custom fields in the content manager
- Run the getstarted example app using `yarn develop --watch-admin`
- Open the app on port 8000: `http://localhost:8000/admin`
- Go to `/admin/content-manager/collectionType/api::kitchensink.kitchensink/create`
- See the `custom_field` attribute which uses a custom field, try the input, change the color, save, refresh, the data should persist with the new color
- Click on "configure the view"
- Make "custom_field" the title of the …
> [Custom fields] Display custom field Input component in the CM edit view

- examples/getstarted/src/plugins/mycustomfields/admin/src/components/ColorPicker/ColorPickerInput/index.js
Display labelAction next to the label of the example color picker plugin
To allow i18n to inject the 🌐  icon next to a custom field input, to let the user know if it's localized or not
- Add a color attribute to a content type that has i18n turned on. Make sure the attribute is localized.
- On the content manager edit view, you should now see the 🌐 icon next to your custom field
- Turn off localization for that attribute in the CTB, then on the edit view you should see a 🌐 ❌ icon
> [Custom fields] Display labelAction on example custom field

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationSingle/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationSingle/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/tests/index.test.js
- packages/core/admin/admin/src/pages/UseCasePage/tests/index.test.js
- packages/core/upload/admin/src/components/Breadcrumbs/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/Breadcrumbs/tests/index.test.js
- packages/core/upload/admin/src/constants.js
- packages/core/upload/admin/src/hooks/__mocks__/useFolder.js
- packages/core/upload/admin/src/pages/App/tests/Header.test.js
This PR fixes some common prop-type and fixture issues in our tests.
To have a cleaner test output.
> chore: Fix some test errors

- packages/plugins/documentation/server/services/helpers/build-component-schema.js
- packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js
Fixes an eslint warning, which causes test failures on `main`.
Let's not state the obvious.
> Documentation: Fix eslint errors

- packages/generators/app/lib/index.js
- packages/generators/app/lib/utils/usage.js
Following an internal discussion about our current support of M1 processors I got curious to find some numbers on Amplitude / Sentry, but had to learn we are currently not tracking the CPU architecture. I think for the installation this might be an interesting information and therefore I'd like to propse to track it.
`os_arch` could contain the following architectures: 'arm', 'arm64', 'ia32', 'mips', 'mipsel', 'ppc', 'ppc64', 's390', 's390x', and 'x64'.
Node documentation: https://nodejs.org/api/os.html#osarch
This PR adds the current CPU architecture to Amplitude and Sentry when projects are created.
I'd like to understand if users with `arm64` CPU architectures have more problems installing Strapi than others.
> Add tracking property for os.arch() to Amplitude / Sentry (project creation)

- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/index.test.js
Resolves console.error messages when running the tests.
Cleaner test output.
> CM: Fix test errors for EditSettingsView

- packages/plugins/i18n/admin/src/components/ModalEdit/BaseForm.js
When editing or adding languages, the display name and language code should not be displayed as the same text.
The language code and the language display name, both of which are shown as the language display name, do not make sense.
When you edit a language or add a new language
**Now it is all displayed as language names**
**I want to see the language code and the language name**
> show language code

- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/admin/admin/src/content-manager/components/Inputs/utils/getStep.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/ModalForm.js
- packages/core/content-manager/server/controllers/validation/model-configuration.js
With this PR It will allow to pass the step for time and datetime fields through [Model].json 
There's some use cases where we don't need every minute to be an option in datetime/time fields
Adding `step` inside a datetime/time field of a [Model].json component should allow to override the number of minutes to be displayed in the content-manager.
https://github.com/strapi/strapi/issues/12175
https://github.com/strapi/strapi/pull/5099
> Allow to pass `step` to datetime/time fields

- examples/getstarted/src/plugins/mycustomfields/admin/src/components/ColorPicker/ColorPickerInput/index.js
- examples/getstarted/src/plugins/mycustomfields/admin/src/index.js
- Fixes the error message in the ColorPickerInput component. GenericInput already formats the message so we should return a string
- Adds a unique checkbox to the advanced form of the colorpicker custom field for testing
Required
- Add the colorpicker custom field to any content type, mark it as required in the advanced form
- Go to the content manager to create a new entity
- Don't touch the colorpicker, edit something else, try to save (if draft and publish it will save, then try to publish), it should throw an error on the input saying it is required
Unique
- Add the colorpicker custom field to any content type, mark it as unique in the advanced form
- Go to the content manager to create a new entity
- Create a color and copy the hex value, save (and publish)
- Create another entity
- …
> [Custom fields] Fix content manager field validations

- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
@petersg83 and I briefly discussed how we'd use pagination for existing relations and relations to search and settled on using the default pagination in both cases.
This PR changes the way properties are grouped for the `useRelation` hook, so that search and relation and be configured as a group. It allows to pass `pageParams` to `react-query` directly (e.g. to include `idsToOmit` or `_component`) and now operates on the default pagination returned.
Less custom options and an API much closer to the internal content API. No custom pagination behavior any longer.
> useRelation: Update interface and group relation / search props together

- packages/core/admin/server/services/api-token.js
It uses the correct API_TOKEN_TYPES enum values to assert if we're changing the token type to custom
Right now, it considers we're trying to update the token to the custom type on every call.
- Create a custom token
- Try to run a query on the content API using this token
- It shouldn't throw the following error
```json
{
"data": null,
"error": {
"status": 400,
"name": "ValidationError",
"message": "Missing permissions attribute for custom token",
"details": {}
}
}
```
> Fix API tokens' update due to wrong enum values

- packages/core/admin/server/strategies/__tests__/api-token.test.js
- packages/core/admin/server/strategies/api-token.js
Fix checks regarding expiration date in the API token strategy
Currently, the code is trying to make a comparison between a date as an ISO string and a time as a number. The token is thus never considered expired.
- Create a token with a short lifespan
- Try to make an authenticated request -> You should get back your data
- Wait until the token expiration date is reached
- Try to make the same request as in step 2. This time you should get a 401 error with a "Token Expired" message.
> Fix expiration date checks

- CONTRIBUTING.md
Adds documentation for the e2e test script:
- it takes an optional path for run e.g. a single test
- how to pass down arguments for jest
It wasn't clear for me how I could update the snapshot tests for e2e tests and neither that the script receives a path as optional argument, which makes running the e2e much easier locally.
- https://github.com/strapi/strapi/pull/14221
> Docs: Expand on how to use e2e snapshot tests with jest arguments

- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
It prevents duplicates on permissions when updating or creating a custom API token.
Without this fix, it's possible to have duplicates in the token's permissions array + it prevents the user to remove duplicates.
Also fixed the fact we were computing the list of permissions to add based on a difference on a undefined value (`originalToken.permissions`)
- Create a custom token with duplicate permissions
- The token should be created with only one instance of each permission, without duplicates
- Update your token by sending a request multiple time with the same permissions, it shouldn't add multiple time the same permission
> Fix permissions update for custom API tokens

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/utils/schema.js
As a user who has access to the API tokens settings, when I generate a new token or when I edit an existing token, I want to save the token with the chosen expiration time and permissions.
👨🏼‍🎨 Design
[https://www.figma.com/file/lADY9wlnGvOX1blL19UYcG/%5BWIP%5D-DX---API-Tokens?node-id=1485%3A10299 - Connect to preview](https://www.figma.com/file/lADY9wlnGvOX1blL19UYcG/%5BWIP%5D-DX---API-Tokens?node-id=1485%3A10299)
☑️ Acceptance criteria
- As an admin who has access to the API tokens settings
- when I create or edit a token, specifying some permissions and an expiration time
- and when I save successfully
- then I want the UI to show a confirmation message and the token to reflect the edits applied
- The confirmation messages are:
- edit view: API Token successfully edited
- creation …
> [FE] Integrate the BE to Save a Token in Creation and Update

- .github/workflows/tests.yml
Add `concurrency` and `paths-ignore` settings to limit the amount of time the GitHub Actions runner is used.
It should make so consecutive pushes on a PR will not all lead to a full run of tests.
Also, you can notice that I have removed the `push` trigger on `main` as I don't think it's needed since this branch should be protected and it would lead to unnecessary runs.
One thing that is worth mentioning is that GitHub Actions does not provide a long grace period when canceling runs, so if our `tests` workflow needs time to clean up stuff, then this PR shouldn't go through as is with this `concurrency` setting.
Computation power and GitHub Actions time are wasted unnecessarily,
> Limit the amount of GitHub Actions time consumed by tests

- packages/core/admin/server/controllers/__tests__/api-token.test.js
Add controller tests for regenerate
They were missing. There were only tests for the service
Run the tests
> Api Token v2/add regenerate controller tests

- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/tests/admin-api-token-crud.test.e2e.js
Allows an empty permissions array to be sent when creating a custom token
To allow creating a token with no permissions
Create a custom token with an empty permissions array and it should work
Created token should not have permission to perform any action
lastUsedAt should still be updated on each attempt
> allow empty array of permissions

- packages/core/admin/server/content-types/api-token-permission.js
- packages/core/admin/server/content-types/api-token.js
- packages/core/admin/server/content-types/index.js
- packages/core/admin/server/services/api-token.js
Rename 'token-permission' to 'api-token-permission'
For consistency and clarity. Since they are called 'api-tokens' their permissions should be 'api-token-permissions'
Everything regarding api-tokens should still work
> rename token-permission to api-token-permission

- packages/core/database/lib/query/helpers/populate.js
- packages/core/strapi/tests/api/populate/filtering/index.test.e2e.js
- packages/core/utils/lib/convert-query-params.js
To populate a field, we can now do:
```js
populate: {
image: 'true', // same with 't', 'false', 'f', '1', '0' and '*'
}
```
Before we could only do `image: '*'` which may not be explicit about what it does :
- does it populate everything in the image like `{ populate: '*' }` would do
- does it populate only with the scalar attributes (it's this one)
Using `true` may be more explicit that it doesn't populate relation under `image`
A test was added
fix #13945
> Allow the use of 'true', 't', 'false', 'f', '1', '0' in addition to '*' when populating a field in REST API

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/tests/formatLayouts.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
As part of https://github.com/strapi/strapi/issues/14217 we discussed that we store the loaded relations in `initialData` to allow plugin authors to access this data. It seems to be broken currently and we want to make sure we fix this with the next relation implementation.
To support plugin-authors.
tbd
Builds on top of https://github.com/strapi/strapi/pull/14092
> EditViewDataManagerProvider: Store loaded relations in initialData

- packages/core/admin/server/bootstrap.js
- packages/core/strapi/lib/Strapi.js
On application startup, check if some permissions in the database do not match the allowed ones (from the content API action provider). If this is the case, delete the obsolete ones.
Handle the scenario where an API token's permissions reference an old controller's method that has been deleted (particularly useful to cleanup the permissions when deleting a content type)
- Create a custom API token that references CRUD actions from a specific content type
- Delete the content type
- Check that the token does not reference those permissions anymore
> Automatically synchronize and cleanup API tokens' permissions in database

- packages/core/admin/admin/src/translations/en.json
- packages/core/helper-plugin/lib/src/components/ReactSelect/ReactSelect.js
- packages/core/helper-plugin/lib/src/components/RelationInput/RelationInput.js
- packages/core/helper-plugin/lib/src/components/RelationInput/RelationInput.stories.mdx
- packages/core/helper-plugin/lib/src/components/RelationInput/components/RelationItem.js
- packages/core/helper-plugin/lib/src/components/RelationInput/components/tests/__snapshots__/RelationItem.test.js.snap
- packages/core/helper-plugin/lib/src/components/RelationInput/components/tests/__snapshots__/RelationList.test.js.snap
- **Loading state for searchResults on ReactSelect:** Default style from the component but added translated `loadingMessage`
- **Loading state for relations:** Integrated it as last item of `RelationList` from `RelationInput`. Will allow us to keep previous items visible while the next relations are loading. Used `RelationItem` to easily track it's height needed when we'll integrate `react-window` 
- Check with design for approval/changes
- Since loading state is mainly handled in `RelationInput` directly, tests will be added when creating all other `RelationInput` tests (will be the next PR)
- **Ellipsis on RelationItem label:** Handled in `RelationInput` since `RelationItem` doesn't provide the granularity to access only the label (without impacting other components passed as …
> [RelationInput] Loading state and label ellipsis

- packages/core/admin/server/controllers/__tests__/api-token.test.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/tests/admin-api-token-crud.test.e2e.js
Validate that permissions are valid when creating or updating a token
Prevent storing invalid permissions in database for API tokens
1. Run the tests (unit or e2e)
2. Try creating a custom token with permissions both from the admin API and from the code
> Validate & throw on unknown permissions for API tokens

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/server/routes/api-tokens.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- fixes a broken unit test
- fixes a snapshot for a broken front-end test
- removes unused broken route /api-token-layout
- fixes a broken unit test
- fixes a snapshot for a broken front-end test
- removes unused broken route /api-token-layout
Run tests - should pass
GET /api-token-layout - should return 404
> Api token v2/Cleanup

- packages/core/strapi/lib/Strapi.js
- packages/core/strapi/lib/services/content-api/index.js
- packages/core/strapi/lib/services/content-api/permissions/index.js
- packages/core/upload/admin/src/hooks/useCropImg.js
- Move core content-API's permission logic into its own file.
- Add precise JSDoc with types and explanations
Make the code more readable and maintainable
Purely architectural changes, nothing should have changed in terms of behavior.
> Core Content API service cleanup 

- packages/core/admin/server/validation/api-tokens.js
Prevents lifespan from being updated in controller validation
I didn't prevent at the service level because it doesn't do any harm to change lifespan, and we will probably revert this change when we add the refresh feature.
Changing lifespan has no purpose because we don't have the refresh feature.
Try updating the lifespan field, it should give a validation error.
> Prevent updating an API token's lifespan from the admin API

- packages/plugins/users-permissions/documentation/content-api.yaml
The OpenAPI specification for the `users-permissions` plugin contained several errors.
This MR fixes all of the errors so that the OpenAPI spec is valid.
Most OpenAPI Generators are quite strict meaning that generating automated API clients for Strapi won't work if the specification(s) aren't valid.
Run OpenAPI validator.
N/a
> Fix several issues in the users-permissions OpenAPI specification

- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/tests/normalizeRelations.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/tests/select.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
Removes the data fixture introduced to make testing easier and fixes the broken frontend tests.
To have full test-runs on the backend PRs.
> RelationInputWrapper: Remove data fixture and fix frontend tests

- packages/core/content-manager/server/controllers/collection-types.js
- packages/core/content-manager/server/services/entity-manager.js
- packages/core/content-manager/server/tests/api/basic-relations.test.e2e.js
- packages/core/content-manager/server/tests/index.test.e2e.js
- packages/core/strapi/lib/services/entity-service/index.js
- The `findOne` of the CM API will not return the relations anymore. For the `xToMany` relations it will return the count.
- Some refactoring around the function `getDeepPopulate`
To avoid performance issue in the CM when the entity has many relations.
There are tests.
> Relations main view/get entity with count

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/cleanData.test.js
Properly cleans up relational fields, before they are submitted.
It allows the user to send the new partial data structure to the internal content API.
> EditViewDataManagerProvider: Cleanup new relations data-structure

- packages/core/database/lib/schema/builder.js
Improve pk management in schema builder
- When adding id columns to link tables it was missing notNullable. Thus trying to update an increment later when a user changes any field in the CTB. This PR makes sure users will get the right id column directly for and that the increments column can be updated if necessary
- You can go back to v4.3.6. recreate a db. then move to main and restart it should had the wrongly set id column. then add a field and see the startup error. 
- Now do the same steps but instead of going to main go to this PR.
> Improve pk management in schema builder

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/TableRows/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/constants.js
- Fixes fetching existing relations in the list-view
- Stores count and actual results next to each other in initialState
- renders count as part of the label
> Relations: Fix list-view, store count and results, render count as part of the label

- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
Invalidate the `relation-*` queries, after an entity was saved.
> FormWrapper: Invalidate relation-queries after submit

- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/normalizeRelations.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
As discussed the content API may send empty 204 responses, which currently breaks the frontend. This PR gracefully handles the case where the response does: 1) not contain a pagination 2) does not contain a values array.
> useRelation/ normalizeRelations: Handle empty 204 API responses

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/components/Option.js
Render id instead of `-` in case the mainField of a relation is not set.
> RelationInput: Render id as fallback, if no mainField was set

- packages/core/admin/admin/src/pages/AuthPage/utils/forms.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/utils/schema.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/utils/validations/users/profile.js
- packages/core/admin/server/validation/common-validators.js
- packages/core/strapi/lib/commands/admin-create.js
Fixes #13648.
At the moment, the schema used to validate objects during admin creation/update does not trim `firstname`, allowing empty strings to be used as the admin's first name.
Try creating/updating an admin using "   " as their first name.
> Trim admin's first name when validating

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/normalizeRelations.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/tests/normalizeRelations.test.js
Previously it was not possible to add new relations, if an entity is created / if the paginated response was empty. This PR fixes that and improves the way relations are normalized.
To support the creation of an entity and to make the code more readable.
> RelationInputWrapper: Fix normalization of relations, if results are empty

- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/RelationInputWrapper.js
Passes down the current locale when querying for relations.
To properly support i18n.
> RelationInputWrapper: Pass down the current locale as query parameter

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/cleanData.test.js
Instead of overwriting the whole Edit View CM state, we now progressively enhance it, so that client-side computed state for relations is preserved, eventhough it is decoupled from the format of the API response.
We need to:
- preserve the computed state for e.g. `results` in relational fields for `initialData`
- cleanup `connect`/`disconnect` in `modifiedData`
> EditViewDataManagerProvider: Progressively enhance relations state

- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/select.js
- packages/core/admin/admin/src/content-manager/components/RelationInputWrapper/utils/tests/select.test.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/tests/formatLayouts.test.js
1. the name of the component parameter was changed from `_component` to `component`
2. for fields within components we need to extract field field-name, hence the last of the name
It fixes loading of existing relations within components.
> RelationInputWrapper: Fix and properly transform query params for components

- packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
Fixes #14395 
With #14111, improving content-manager list view headers labels traduction, custom labels (configurable in the configure the view page) ended up being ignored
This PR reintegrates the usage of `metadatas.label` 
- Customize a field label in list view Configure the view
- It should appear in the Table header
> [Fix] CM LV custom labels

- packages/core/content-type-builder/admin/src/components/AttributeOptions/CustomFieldsList/index.js
This URL will have to be changed again after the stable release
(docs-next.strapi.io will become docs.strapi.io)
It updates the link to the documentation introduced in PR #13823 
***
_Note:_ 
This link will have to be updated again for the stable release, changing the base URL:  `docs-next.strapi.io` → `docs.strapi.io`. I can handle this change if you want ^^
> Update documentation link for custom fields

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/normalizeRelations.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/tests/normalizeRelations.test.js
- Refactoring of filtering disconnected relations in `normalizeRelations`
- UI fixes:
- removed scrolling bottom every time (it caused scrolling bottom after removing a relation)
- fixed shadows still showing after deleting enough items to not be in a scrolling list
Add/remove relations to test filtering is working the way it is intended
> [Relations] Filter refacto & UI fixes

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/normalizeRelations.js
Removes a leftover of a previous experiment, which caused newly added relations to appear at the top of the list, instead of the bottom, if an entity with existing relations is being edited.
Order!
> RelationInputDataManager: Fix position of newly connected relations

- packages/core/content-type-builder/admin/src/components/FormModal/contentType/createContentTypeSchema.js
Fixes #13058 by adding an additional test similar to the one applied to `displayName` to `singularName` and `pluralName`.
> Do not allow reserved names for singular/plural API names

- packages/core/admin/admin/src/content-manager/components/InputJSON/index.js
Prevents  `InputJSON` from crashing when field value is `0` by stringifying the integer before render.
The `InputJSON` displays an error when the field value is set to `0` due to CodeMirror possibly seeing it as a falsy value.
Set a JSON field to `0` and notice how it displays an error before the PR and doesn't afterwards.
> Prevent `InputJSON` from crashing when field value is `0`

- packages/core/admin/admin/src/components/ThemeToggleProvider/index.js
Fixes #14364 
Store STRAPI_THEME in locale storage if it doesn't exist
Before it was only stored if the theme was changed on the Profile page
This will allow developers to always access the user theme and apply customization depending on the theme
It also fixes an eslint warning:
1. test that it doesn't break or change anything for the existing accounts
2. test that it stores the theme in locale storage if it wasn't set or for new accounts
> [Enh] Store app theme 

- packages/core/admin/admin/src/components/AuthenticatedApp/index.js
- packages/core/admin/admin/src/components/AuthenticatedApp/tests/index.test.js
Fixed guided tour visible even on production mode 
Used `autoReload` as for CTB
`autoReload` is false when using `strapi start` command which means that we are in a production environment 
`yarn setup` at strapi root
`yarn build` on getstarted
`yarn start` on `getstarted` while being a super admin
Guided tour shouldn't appear in homepage or any other places
> [Fix] Guided tour visibility on prod mode

- packages/plugins/i18n/server/constants/iso-locales.json
- packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap
Fixes #14427
Added `en-PA` English (Panama) locale to i18n constants
Go to Internationalization global settings
Add English (Panama) as a new locale
> [Enh] en-PA locale

- packages/core/strapi/lib/core/loaders/apis.js
Fixes #14160.
When `sourceMap` is true in `tsconfig.json`, the API loader makes the app crash.
This is caused by `.map.js` having an `extname` of `.map`, which implies [this check](https://github.com/strapi/strapi/blob/e1e4071cf0d0afa8365dbff5659c5c76edf25600/packages/core/strapi/lib/core/loaders/apis.js#L145-L156) returns an empty object for all `.map.js`, which happen to have the same name as valid APIs, which get therefore overridden.
Repeat the steps in #14160 and notice how the app does not crash anymore.
The components loader specifies a glob of `*/*.*(js|json)` which does not exclude `.map.js` files either, but I believe there is no way to create components that are not in JSON format.
> Exclude source maps when loading APIs

- packages/plugins/documentation/server/services/helpers/utils/query-params.js
Add the `filters` query parameter to the generated OpenAPI spec.
Tested with the Swagger UI in the Strapi admin and seems to work.
When using an OpenAPI generator it's not possible to add filters as they weren't included in the query parameters list.
- Regenerate documentation
- Test with the Swagger UI
N/a
> Add free-form filters to the query parameters

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/FormApiToken/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/FormApiTokenContainer/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/FormBody/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/FormHead/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/tests/__snapshots__/index.test.js.snap
Refactor and split the code of the Edit and Create pages in the Api Token Settings.
Because the code was huge in just one component, we need to split it and have a more readable code.
We need to test all the possible combinations and possibilities with Api token to check some regression errors.
> Refactoring API tokens v2 frontend code

- packages/core/content-type-builder/admin/src/components/AttributeOptions/CustomFieldsList/index.js
It updates the documentation link used in `CustomFieldsList/index.js` to the production documentation instead of using docs-next.
**Please don't merge before getting ready for the General Availability of custom fields, the link will only be active on the release day.
This is a follow-up to #14232, now updating the link for the final release.
> Update documentation link in CustomFieldsList for the stable release

- packages/core/strapi/lib/types/core/attributes/common.d.ts
- packages/utils/typescript/lib/__tests__/generators/schemas/attributes.test.js
- packages/utils/typescript/lib/generators/schemas/attributes.js
Updates the command that generates TS types for a content type so that it handles custom fields properly.
Custom fields were being treated like they were the underlying type. So the key `customField`, as well as the optional `options` object were missing from the types for a custom field attribute.
- Run `yarn strapi ts:generate-types` in a Strapi application that uses a custom field (like getstarted)
- View the generated `schema.d.ts` file. The type for the custom field attribute should combine the underlying type attribute, as well as the custom field one with the custom field uid as a parameter. For example:  
```ts
field: StringAttribute & CustomField<'plugin::color-picker.color'>;
```
made with @Convly in peer programming
> Add custom fields to Typescript generators

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/content-manager/server/controllers/relations.js
- packages/core/content-manager/server/tests/find-existing-relations.test.e2e.js
- packages/core/content-manager/server/tests/index.test.e2e.js
There is a difference in the response format for when it is a xToMany relation or a xToOne relations.
```
xToMany :
{
results: [],
pagination: {
page: 1,
pageSize: 5,
total: 10,
}
}
```
```
xToOne :
{
data: {}
}
```
Frontend did not know about it and only implemented the first format so it is not equipped today to handle the second one.
As a temporary fix for the alpha, we implemented the first format for the xToOne too in the backend. 
Later we will need to revert that and change the frontend instead as a pagination is not relevant for a xToOne.
Create xToOne relation
Save
Relation should show up
> [Fix] xToOne relations not showing

- packages/core/admin/admin/src/content-manager/components/NonRepeatableComponent/index.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
Relations didn't appear for relations inside a component (single, rep, dz)
It was caused by data being nested making `modifiedData?.[name]` with `name` syntax being `openingTimes.0.dishrep.1.categories`
Fixed by using `get` from `lodash` allowing to easily get nested data 
Also fix some `proptypes` error with size passed to component `Inputs`
⚠️ this PR doesn't fix entirely relations in component since we don't query the right `id` for component yet
This fix needs to be tested by pulling `relations-main-view/QA` branch into this one
Create a Restaurant entity with openingTimes/dishrep/categories relation
See categories relations displayed
> [Relations] Fix nested data for relations in component

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/Component/index.js
- packages/core/admin/admin/src/translations/en.json
Wraps the form of a dynamic zone's component inside a suspense boundary.
You can see it in [this video](https://www.loom.com/share/6823b4d0e2a94c3b8d64cb3627f24528) around 3:30
It ensures that when opening a DZ's component that uses a custom field, the loader is contained within the accordion, instead of hiding the entire page
- Create a content type
- Add dynamic zone inside
- Inside the dz, add a component with an attribute that uses a custom field
- In the edit view for that content type, open the DZ accordion and open the component
- Watch the loading state (you may need to turn on throttling in your devtools to see it)
Issue identified by @soupette [there](https://github.com/strapi/strapi/pull/14163#discussion_r980828686)
> Add suspense boundary in dynamic zones

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
Fix Load more button loading state
- Refactor by using TextButton latest API
- use isFetchingNextPage boolean to get loading state
To test the behaviour you will need to pull `relations-main-view/QA` into this branch
Add more than 5 relations
Reload the page
Click on Load more button
See loading state appearing
https://user-images.githubusercontent.com/71838159/192989741-d6eea3e6-1b8c-446f-8574-fff1c1a4b6cf.mov
> [RelationInput] Fix Load more button loading state

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
This forces the react-select component to open and close the menu when the `options` prop changes to enable a recalculation in menu positioning so the dropdown is always in the viewport.
`react-select` currently has a bug where when the `options` change, the menu isn't recalculated leading to the menu to show offscreen.
Realistically this is a hack to solve an issue in the library, an alternative approach could be to replace `react-select` with a low level primitive and recreate it. The downfall of this is we most likely would need to create separate components for types of selects we have in the codebase which would then incur a development time cost.
> [fix][RelationInput]: menu placement on options changed

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
- packages/core/admin/ee/server/controllers/user.js
- packages/core/admin/server/controllers/__tests__/user.test.js
- packages/core/admin/server/controllers/user.js
- packages/core/admin/server/tests/admin-user.test.e2e.js
- Fixes an issue where inviting an admin user with a camel cased email address would cause an API error (failing the Yup email validation logic)
- `POST /users` now transforms all email addresses to lower case
Emails should be assumed to be lower case as discussed on the related issue
1. Go to Settings / Users
2. Click on "Invite new user"
3. Fill the form with an email like "ExamPle@example.com"
4. Click on "Invite user"
Fixes #13360
> Treat email as lowercase when creating a user

- packages/core/database/lib/entity-manager/index.js
Fixes [Content-505](https://strapi-inc.atlassian.net/browse/CONTENT-505)
Files are stored as a morphToMany relationship in the entity. We were not checking if the `set` was empty.
So it crashed when updating any entry with a file attribute
> check if set is empty

- packages/plugins/users-permissions/tests/content-api/auth.test.e2e.js
Fix unauthenticated request error following the changes made during API Token V2 development
Fix a failing e2e test which has a wrong behavior
`node test/e2e.js -- packages/plugins/users-permissions/tests/content-api/auth.test.e2e.js`
> Update UP e2e test following API token V2 release

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
Fixes a bug where infinite scrolling wasn't possible when the menu first mounted (related to #14493) and also avoids re-opening the menu when the options change, instead we re-open when the menu _gets_ it's options.
Because when you activate infinite scrolling the menu open and closes and your position in the menu is lost.
* CONTENT-504
> [fix][RelationInput]: infinite scrolling should be runnable on first mount of menu

- packages/core/content-type-builder/admin/src/components/FormModalSubHeader/index.js
Adds the attributes description to the SubHeader of the modal
* Go to Content Builder
* Add a field
* Select an attribute
* View the modal and see the attribute description
* resolves CONTENT-239
> [feat][AttributeModal]: add attribute description to field modal in content builder

- packages/utils/typescript/lib/utils/get-config-path.js
Resolves path on Windows OS If tsconfig file is provided. 
It doesn't affect strapi if tsconfig is not provided, but if it does it changes the path with correct backslashes
People with Windows machines also want to use strapi ts.
Before : C:/Users/currentUser/project/server/tsconfig.json
After:  C:\Users\currentUser\project\server\tsconfig.json
[issue link](https://github.com/strapi/strapi/issues/13237)
> fix: Unknown Dialect Windows issue

- packages/core/admin/admin/src/content-manager/pages/ListView/utils/buildQueryString.js
- packages/core/admin/admin/src/content-manager/pages/ListView/utils/tests/buildQueryString.test.js
- packages/core/helper-plugin/lib/src/components/SearchURLQuery/index.js
- packages/core/upload/admin/src/hooks/tests/useAssets.test.js
- packages/core/upload/admin/src/hooks/useAssets.js
- The helper plugin now encodes queries made through `SearchURLQuery` - this ensures the whole query is passed back to the admin package and not split at `&`
- The relevant parts of the `admin` package encode the query before making API calls (e.g. `/upload/files?sort=updatedAt:DESC&page=1&pageSize=10&_q=this%26that`)
Previously a search containing `&` would be split, resulting in a search only being performed for the query before the first `&` (e.g. `this&that` would result in a search for `this`)
- Media Library: upload a file with an `&` in the name and perform a search
- Content Manager: create `category` entries with `&` in the name and perform a search
Fixes #10780
> Fix search query encoding

- packages/core/admin/admin/src/content-manager/components/DynamicTable/TableRows/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
* Refactors IconButtons in `DynamicTable` to use `Link` from `react-router-dom` underneath so links are accessible as anchors as opposed to `button`
* Refactors the main `create entry` button in `ListView` to use `Link` from `react-router-dom`
Because it's semantically incorrect to use a button to route somewhere (anchors can have `onClick` events therefore allowing the tracking events to still occur)
Go to content manager and view table of content
* resolves #10356
> [fix]: use router link for actions that route places in Content Manager ListView & DynamicTable

- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/strategies/__tests__/api-token.test.js
- packages/core/admin/server/strategies/api-token.js
- `lastUpdatedAt` is updated directly without querying an additional time for the token [solves the performance issue caused on all requests]
- Removes the populate relation from the API Token v2 service update method. Permissions links are handled manually in a later separate step, so the update does not need to worry about populating the relations. [increases performance on token update]
API Token v2 greatly increased the number of DB requests because of these unnecessary calls.
- Use a DB monitor to view queries with and without this PR
- Make content API calls using an API token
- DB calls should be greatly reduced with this PR
https://github.com/strapi/strapi/issues/14512
> Improve API token v2 db performance by removing update population

- packages/core/strapi/package.json
- yarn.lock
Updating koa/cors to 3.4.2 in order to fix cors filter origin problem  #14357
There was a bug that is fixed on koa/cors 3.4.2 version.
Fixes #14357
In order to fix #14357 I had to fix another bug on koa/cors, as my PR was merged -> https://github.com/koajs/cors/pull/87 I'm creating this PR in order to update the lib
Koa/cors was not calling origin middleware when the origin header was not present. Hence, even when you set credentials as false, the middleware was not called and people could not get Access-Control-Allow-Origin as '*'.
Set credentials as false on config/middlewares.js, call any API in order to retrive Access-Control-Allow-Origin as '*' as DEFAULT.
```
{
name: 'strapi::cors',
config: {
credentials: false,
},
},
```
Fix  #14357
Please, could you add https://hacktoberfest.com/ …
> Updating koa/cors to 3.4.2 in order to fix cors filter origin problem #14357

- packages/plugins/users-permissions/server/controllers/validation/user.js
You could not create user from the content manager now.
user-permissions plugin was not expecting the connect / disconnect format.
Create a user from the content manager.
> Fix role assign on user collection type

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/index.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/normalizeRelations.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/normalizeSearchResults.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/tests/normalizeRelations.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/tests/normalizeSearchResults.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
The front receives:
```
[
{
results: [
{ id: 1, label: 'newest' },
{ id: 2, label: 'second' },
],
},
{
results: [
{ id: 3, label: 'third' },
{ id: 4, label: 'oldest' },
],
},
]
```
and needs to display it like this:
```
[
{
results: [
{ id: 4, label: 'oldest' },
{ id: 3, label: 'third' },
],
},
{
results: [
{ id: 2, label: 'second' },
{ id: 1, label: 'newest' },
],
},
];
```
Updated `normalizeRelations` to reverse arrays of relations and relations inside those arrays
We don't want to reverse relations in `connect` 
Add at least 7 relations from oldest to newest added
Save
Load relations
See them displayed from latest to newest
Add a new relation
See it displayed at the bottom
> [Relations - Front] Reverse order of relations

- packages/core/upload/admin/src/components/EditAssetDialog/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/translations/en.json
- Upload a file
- Check right side in the file attributes to see `File ID` and the internal integer ID
> Add file ID to Asset Edit View in Upload plugin

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- Adds a hover/ focus state to the remove icon of a `RelationItem`
- fixes the prop-type when passing an ID to the tooltip (needs to be string)
- fixes the prop-type for `labelLoadMore` (can only be a string or null, but not `false`)
Cleanup dev console and improve UX.
> Relations: Hover state and prop-type fixes

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/plugins/i18n/admin/src/contentManagerHooks/mutateEditViewLayout.js
- packages/plugins/i18n/admin/src/contentManagerHooks/tests/mutateEditViewLayout.test.js
Currently, the i18n plugin does not inject `queryInfos` for relational fields in the main layout if they are not part of a component. This PR adds the required properties to the i18n plugin.
To properly support i18n and to not hard-code knowledge about the i18n plugin in the CM. Plugins inject their properties into the main app and the main app shouldn't have any knowledge about the plugins.
- https://strapi-inc.atlassian.net/browse/CONTENT-538
> i18n: Inject i18n queryInfos for relations

- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
Disables the query cache when fetching relations.
Every load of an entity should give the user a fresh set of data, which we can achieve by disabling the cache.
1. Create more than 10 relations
2. Navigate to list view
3. Navigate back to the entity
4. Validate the `RelationInput` component is in the default state
- https://strapi-inc.atlassian.net/browse/CONTENT-551
> useRelation: Disable query cache for relations

- packages/core/content-manager/server/controllers/collection-types.js
- packages/core/content-manager/server/controllers/single-types.js
- packages/core/content-manager/server/routes/admin.js
- packages/core/content-manager/server/services/entity-manager.js
- packages/core/content-manager/server/services/utils/draft.js
- packages/core/content-manager/server/services/utils/populate.js
- packages/core/content-manager/server/tests/api/number-of-draft-relations.test.e2e.js
- packages/core/database/lib/query/helpers/populate/apply.js
Add a Content-Manager route to get the number of draft relations an entity has.
To display a warning message to the user in case they wants to publish an entity that is still linked to draft entities
Tests will be added later
> add getNumberOfDraftRelations route

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js
- packages/core/admin/admin/src/content-manager/components/SelectOne/SingleValue.js
fixes #13719
shows the whole text which are truncated
Titles too long do not render properly in content manager
step1: create a content-builder => with type of any string => add text on the contentmanager and  check it out on the table it will be truncated but when hovering it will show thw whole text both for relation single type select and dynamic table 
[DEMO_link](https://www.loom.com/share/e221b54ec4294d9dbe148e47b1bd120e)
#13719
> Titles too long do not render properly in content manager

- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
Normalizes xToOne relations early on (as part of the `useRelation()` hook), so that they later can be treated as a any other relation.
We receive different results from the API dependending on the relation type:
xToMany
```json
{
"data": {
"results": [
// data
]
}
}
```
xToOne
```json
{
"data": {
// data
}
}
```
The `useRelation()` hook normalizes this early on, so all components depend on a unified relation format. This should help to keep the complexity further down lower.
I've added more unit tests. Until the backend is ready, there is no way to test this in the CM.
- https://strapi-inc.atlassian.net/browse/CONTENT-475
> useRelation: Handle and normalize xToOne relations

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/tests/select.test.js
Adds a test for generating component IDs in select.
You know ... tests.
> RelationInputDataManager: Add tests for component id in select

- packages/core/data-transfer/LICENSE
- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/index.ts
- packages/core/data-transfer/package.json
- packages/core/data-transfer/tsconfig.json
- packages/core/data-transfer/types/common-entities.d.ts
- packages/core/data-transfer/types/index.d.ts
- packages/core/data-transfer/types/providers.d.ts
- packages/core/data-transfer/types/transfer-engine.d.ts
- packages/core/data-transfer/types/utils.d.ts
- yarn.lock
- Init the strapi/data-transfer core package
- Add the backbone for the transfer engine
- Lay down the foundation for the new Data Import Export feature
> Init strapi/data-transfer package and its transfer engine

- packages/cli/create-strapi-app/create-strapi-app.js
Solves #14114 by exiting the app creation process when the `--template` flag is immediately followed by another of the allowed flags.
At the moment launching something like `create-strapi-app --template --ts` parses `--ts` as the template name the users wants to use when creating the app, which implies that the `--ts` flag is completely omitted and the creation fails because there is no `--ts` template.
Try creating an app with `create-strapi-app --template <OTHER SUPPORTED FLAG>` and notice how an error is shown and the process exists.
#14114
Is there a regex that template names must follow? If so, it would probably be better to check whether the argument is matching such regex rather than simply excluding the other flags.
> Throw if --template flag is immediately followed by another flag when creating app via CLI

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/tests/RelationInputDataManger.test.js
Adds integration tests for `RelationInputDataManager` to test if all integrations with `RelationInput` are working well.
Tests.
> RelationInputDataManager: Add integration tests

- packages/core/content-manager/server/services/entity-manager.js
- packages/core/content-manager/server/services/utils/populate.js
- packages/core/content-manager/server/tests/api/basic-relations.test.e2e.js
- packages/core/content-manager/server/tests/index.test.e2e.js
Content-Manager findOne route : It counts the number of relations for the xToOne relations
The xToOne relations were not populated neither counted.
Counting is helpful for the admin panel so that all fields are present + to know if there is 0 or 1 relation.
e2e tests were updated.
none
> Relations main view/count one relations

- packages/core/admin/admin/src/pages/App/index.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/index.js
It properly awaits `fetch()` and `axios.post()` calls, when sending tracking requests. If an error was thrown previously, we did not wait for the promise to be rejected, which caused a bug where the error was not being watched by the `try {} catch {}` blocks.
A good read on the topic: https://jakearchibald.com/2017/await-vs-return-vs-return-await/
There are many reasons why the tracking request might fail: 1) Network Error 2) Ad blockers 3) Service outage ... In these cases, there is a good chance the Strapi app crashes currently, which we should avoid by any means.
> **Warning**
>  Do not forget to rebuild or to watch for changes in `@strapi/helper-plugin`.
1. Open Strapi in development mode
2. Block either: 1) the URL https://analytics.strapi.io/track or the full domain in your browser …
> Fix: Catch all errors when sending tracking requests

- .husky/pre-commit
- package.json
- yarn.lock
upgrade husky to v8 and lint-staged to v13
Getting rid of really old transitive husky@3 dependencies.
Husky v8:
- Zero dependencies and lightweight (6 kB)
- Powered by modern new Git feature (core.hooksPath)
- Follows [npm](https://docs.npmjs.com/cli/v8/using-npm/scripts#best-practices) and [Yarn](https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall) best practices regarding autoinstall
Verified git hooks locally with new husky@8
> chore: upgrade husky to v8 and lint-staged to v13

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/DraggableCard.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/Settings.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/SortDisplayedFields.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/index.test.js
Use the custom labels for fields in the `ListSettingsView` component, the component where the headers of the list view can be adjusted. This changes to use the user specified labels in the following components:
- "Default sort attribute" dropdown (1)
- "Add a field" dropdown (2)
- Aria labels for the DraggableCard components (3)
From a UX perspective, the custom labels are sometimes used, e.g. in the `AttributeFilter` or the `FieldPicker` component, but sometimes it's using the raw field names, as it was the case for the three places listed above.
In my case, I usually write my internal field names in camelCase and in English, while I want the end user using the admin panel to see a nicely formatted label in perhaps a different language.
Add an example collection, add a field to it and …
> Use custom field labels in ListSettingsView component

- packages/providers/upload-aws-s3/README.md
Modifies the README of the `upload-aws-s3` provider by adding a *Bucket CORS Configuration* section outlining what users should do to properly display videos and GIFs in the admin panel.
Due to S3's default CORS policies, videos and GIFs are not preview-able in the admin panel unless the domain of the admin panel is added to the `AllowedOrigins` list.
Upload a video to a bucket and notice how the preview is not shown.
Then, edit the bucket's CORS policies and refresh the admin panel to notice that the preview is showing.
> Add details about amending S3 bucket CORS policies to properly show GIFs and videos in the admin panel

- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/data-transfer/lib/providers/local-strapi-destination-provider.ts
Adds the local file and strapi destination providers.
WIP - they don't necessarily work yet, they have only been copied from the `deits/poc` branch, updated with the latest structure.
So we have all the pieces in place and can start making it work together.
.
.
> [DEITS] add destination provider backbone

- packages/core/admin/admin/src/index.js
- packages/core/admin/env.js
- packages/core/admin/scripts/build.js
- packages/core/admin/webpack.config.dev.js
- packages/core/helper-plugin/lib/src/hooks/useAppInfos/__mocks__/index.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/index.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/tests/index.test.js
- packages/core/strapi/lib/commands/builders/admin.js
Currently frontend tracking events are sent, regardless if the telemetry is disabled. There are at least two ways to disable tracking:
- through an environment variable called `STRAPI_TELEMETRY_DISABLED`
- through a property `telemetryDisabled` in the package.json https://docs.strapi.io/developer-docs/latest/getting-started/usage-information.html
This PR passes down the environment variable and the setting and stores the preference on `window.strapi`, so that the `useTracking()` hook can check the user preference before sending the request.
For the development environment an easier solution, which only looks at the environment variable, was implemented to make it testable (see the comment in the code).
To respect if a user has opted out from tracking.
1. Run `yarn develop` in the …
> useTracking: Respect the users choice when sending telemetry events in the admin app

- packages/core/helper-plugin/package.json
- yarn.lock
* removes `@strapi/design-system` from the helper plugin deps
* Because I accidentally introduced it in e84eb506b892774e48f967be3a72c214fbfa1c85 when I should have updated the `devDeps`
> chore: remove design-system from helper deps

- packages/core/content-manager/server/controllers/relations.js
- packages/core/content-manager/server/tests/find-available-relations.test.e2e.js
- packages/core/content-manager/server/tests/find-existing-relations.test.e2e.js
Add tests to findExisting and findAvailable relations routes.
It tests when the route fails (not found, bad field name)
It should not be needed, testing is doubting
see the green colors at the end of the PR
> add validation tests on findAvailable and findExisting relations

- packages/providers/upload-aws-s3/jest.config.js
- packages/providers/upload-aws-s3/lib/__tests__/upload-aws-s3.test.js
- packages/providers/upload-aws-s3/lib/index.js
Adding https:// to url that doesn't have any.
Also adding unit tests to this provider.
Digital Ocean only gives the URI without protocol in response to the upload.
The steps to reproduce are defined in the issue #14288 
Steps to reproduce the behavior
- Add an S3 provider to a Strapi project (AWS or community DO for example).
- Connect to a DO spaces account
- Add a video to the media library
- Inspect the uploaded video with the browser dev tools and see the incorrect address.
Fix #14288
> fix(aws-provider): add https protocol when missing in file url

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/components/RoleRow/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/ListPage/index.js
This fixes the ✨ last two remaining prop-type errors ✨ which the frontend tests are throwing.
We are down to zero errors and want to introduce stricter prop-type checking.
In automated tests we trust.
> Chore: Fix prop-type errors in setting list views

- packages/core/data-transfer/.npmignore
- packages/core/data-transfer/package.json
- packages/core/data-transfer/tsconfig.json
Emit an index.d.ts along with the source files when compiling.
Export typings for the library
- `cd packages/core/data-transfer`
- `yarn build`
- Check that the `index.d.ts` file has been created in the generated `dist` folder.
> [DEITS] Emit a definition file on package build

- jest.base-config.js
- package.json
- packages/core/data-transfer/jest.config.js
- packages/core/data-transfer/package.json
- yarn.lock
- Configures jest to be able to run Typescript test files for the `data-transfer` package 
- we want to be able to run unit tests when we are working on the package, the package is a typescript package
create a typescript test file and add a test, and run the `yarn test:unit` the file would be run properly
> Configure typescript tests

- examples/kitchensink-ts/config/server.ts
Add default APP_KEYS to the kitchensink-ts project
Before it was not possible to launch the kitchensink-ts project without providing the APP_KEYS through a .env file.
Launch the kitchensink-ts project and see that it works without providing APP_KEYS through a .env file.
> Add default app keys to the server config

- packages/core/strapi/lib/Strapi.js
It fixes the problem of reading the license.txt file in the EE edition using Typescript. 
Because before this fix, using the license in the license.txt file was not possible
At the moment there isn't any tests on this.
https://github.com/strapi/strapi/issues/14328
> Replace directory to be able to get license.txt using a typescript project

- packages/core/content-manager/oas.yml
Add OPEN API documentation for 
- getAvailable
- getExisting
- numberOFDraftRelations
Run `yarn doc:api core/content-manager` and check the documentation
> Update OPEN API documentation with new relations routes

- packages/core/data-transfer/lib/encryption/__tests__/encrypt.test.ts
- packages/core/data-transfer/lib/encryption/encrypt.ts
- packages/core/data-transfer/types/encryption.d.ts
- packages/core/data-transfer/types/index.d.ts
- Add Encryption module to the data-transfer package
- Allows for the ability to encrypt data using the crypto node package
- So we are able to encrypt the data that we export
- follow the examples in the test files and see if your data gets encrypted
- run the ts tests (when we integrate that)
> [DEITS] data-transfer encryption

- packages/core/admin/admin/src/pages/MarketplacePage/components/NpmPackageCard/index.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/translations/en.json
Changed marketplace card “Learn more” button text to “More”.
When the main navigation is extended in Strapi, the button text in English version is on a double line which is not really aesthetic. This won’t solve the issue for every language, but will solve the issue in the default language of the admin: English. [Reference](https://strapi-inc.atlassian.net/browse/EXPANSION-320)
Go to Marketplace > plugins/providers tab
> [Marketplace] Exp-320 Change wording in marketplace card

- jest.base-config.front.js
- packages/admin-test-utils/lib/setup/prop-types.js
> **Note**
> This PR is meant to be a discussion starter.
The PR extends the jest setup so that every thrown prop-type error would result in a 💥  test failure 💥 .
@simotae14 and I are currently cleaning up the frontend tests, which contain many prop-type errors. Once these are cleaned, I'd like to ensure we do not regress on this.
What does everybody think about that?
Jest will test itself.
> Jest: Fail tests on failing prop-types

- packages/core/strapi/lib/load/load-files.js
- packages/core/utils/jest.config.js
- packages/core/utils/lib/__tests__/import-default/cjs.js
- packages/core/utils/lib/__tests__/import-default/esm.js
- packages/core/utils/lib/__tests__/import-default/index.test.js
Fix load-files (bad import)
- Currently, it's not possible to run a strapi application as it will break on the load-files
- Go to `examples/getstarted`
- Run `yarn develop`
- The application should start normally
> Fix load-files import

- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider.ts
- packages/core/database/lib/index.d.ts
- packages/core/database/lib/query/helpers/index.js
- packages/core/database/lib/query/helpers/streams/index.js
- packages/core/database/lib/query/helpers/streams/readable.js
- packages/core/database/lib/query/query-builder.js
- Add a stream method to the Strapi query-builder
- Only handles 'select' requests for now (it'll returns a Readable stream)
- Use this stream API to query the database in the Local Strapi Source Provider
We need to integrate streaming capabilities into the Strapi DB layer to match data export requirements for big data.
However, we don't want to expose this streaming API to the entity service as it doesn't make sense for the moment.
- Replace the content of your getstarted/src/index.js file with the following
```js
'use strict';
const {
createTransferEngine,
createLocalStrapiSourceProvider,
createLocalFileDestinationProvider,
} = require('@strapi/data-transfer');
/**
* An asynchronous register function that runs before
* your application is initialized.
*
* This gives …
```
> [DEITS] Readable query stream API for the query-builder

- packages/plugins/users-permissions/package.json
- yarn.lock
Updates koa2-ratelimit to fix missing peer-dependency errors. Thanks to Alex's [upstream PR](https://github.com/ysocorp/koa2-ratelimit/pull/49), these are now marked optional. No other important changes were made.
At the moment a fresh Strapi installation prints 3 missing peer-dependency warnings:
```
warning "workspace-aggregator-061f547c-e56e-4bc8-8635-b4be31336e69 > @strapi/plugin-users-permissions > koa2-ratelimit@1.1.1" has unmet peer dependency "mongoose@>= 5".
warning "workspace-aggregator-061f547c-e56e-4bc8-8635-b4be31336e69 > @strapi/plugin-users-permissions > koa2-ratelimit@1.1.1" has unmet peer dependency "redis@>= 4.0.0".
warning "workspace-aggregator-061f547c-e56e-4bc8-8635-b4be31336e69 > @strapi/plugin-users-permissions > koa2-ratelimit@1.1.1" has unmet peer dependency …
```
> chore: Update koa2-ratelimit to 1.1.2

- packages/plugins/color-picker/package.json
Adds `react` and `react-dom` to the dependencies of the color-picker plugin.
Currently a fresh installation prints two warnings:
```
warning "workspace-aggregator-5ad7b7e4-8ed7-4fdf-992b-a09d5f97db46 > @strapi/plugin-color-picker > react-colorful@5.6.1" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-5ad7b7e4-8ed7-4fdf-992b-a09d5f97db46 > @strapi/plugin-color-picker > react-colorful@5.6.1" has unmet peer dependency "react-dom@>=16.8.0".
```
which can be resolved by adding `react` and `react-dom` as dependencies.
Run a fresh installation and verify no warnings are thrown.
> Color-Picker: Add react and react-dom dependencies

- packages/core/strapi/lib/middlewares/favicon.js
Makes the switch to png favicons in https://github.com/strapi/strapi/pull/14655 backward compatible. In case the `.png` doesn't exist in the app it falls back to use the `.ico` version.
Ensures backward compatibility.
1. Rename the `favicon.png` to `favicon.ico` from the getstarted example
2. Restart the server
3. Validate it does not crash or log an error.
- Fixes https://github.com/strapi/strapi/issues/14693
> Fix: Make favicon middleware backwards compatible with pngs

- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/index.ts
- packages/core/data-transfer/package.json
- packages/core/strapi/lib/commands/transfer/export.js
- improves logs
- adds a `clean` and `build:clean` to help fix cases where old build files are causing problems
to make things nicer
Run clean or build:clean from the data-transfer directory.
> [DEITS] Cleanup (tooling & error handling)

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/EditView/Header/tests/index.test.js
Fixes prop-types for some FE tests. There is still one failing test which will be fixed by https://github.com/strapi/strapi/pull/14659
Tests now fail if prop-types fail, which proves to be helpful already.
> Chore: Fix prop-type errors

- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/entities.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/index.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/test-utils.ts
Fix the failing unit tests
Unit tests were broken because they were defining the entityService.stream API although the source code is using the new query builder stream API
- Run `yarn test:unit data-transfer`
- Every test should pass
> [DEITS] Fix local file source provider unit tests

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/tests/formatLayouts.test.js
We can stop passing down `defaultParams` from the layout.
Simplifies the code.
> CM: Stop passing defaultParams down (not needed any longer)

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/tests/RelationInputDataManger.test.js
* re-adds the `count` value that I broke during #14352 
* makes this count dynamic i.e. we know the server has 10 and if we remove one on the browser it will show 9 🥳
I haven't added any tests yet, I wasn't sure if it was worth it... @gu-stav wdyt?
* CONTENT-546
* CONTENT-654
#14765 should be merged first as this branch branches off that to avoid ESLINT errors from a hotfix 👀
> feat: re-add the count & make it dynamic

- packages/core/admin/admin/src/pages/MarketplacePage/components/NpmPackageCard/PackageStats.js
- packages/core/admin/admin/src/pages/MarketplacePage/components/NpmPackageCard/index.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/server.js
Marketplace card - github stars and npm downloads fields are mapped.
Go to marketplace > plugins/providers tab
> [Marketplace] Exp-381 github stars and npm download fields mapping

- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/configuration.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/links.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/configuration.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/index.ts
- Add the Strapi configuration export from the local strapi source provider (& handle its data in the local file destination provider)
- Add export capability for the configuration
- Either run the associated unit test or yarn strapi export --encrypt=false --compress=false and check the exported file
> Add configuration export

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
Overwrites the default message from react-select "No options" with "No relations available". It also hides the fact that react-select expects functions as props, which is an implementation detail we want to abstract away.
Users are dealing with relations and since there is a good chance for this message to be visible, it should be as precise as possible.
Type something into a relational field that can not be found.
> RelationInput: Overwrite default react-select no-options message

- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
- packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
- packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap
Adds a subtle box-shadow around the react-select menu, to better differentiate it from `RelationItem`s.
|-|-|
| <img width="426" alt="Screenshot 2022-11-04 at 13 58 40" src="https://user-images.githubusercontent.com/2244375/199978600-160e830e-e023-41f0-915d-3811ffecc4e8.png"> | <img width="426" alt="Screenshot 2022-11-04 at 13 56 52" src="https://user-images.githubusercontent.com/2244375/199978605-22c43b4f-0428-4112-ace2-eab6291cddeb.png"> |
Matches the design & improves readability.
> ReactSelect: Add missing box-shadow

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
- packages/core/admin/admin/src/translations/ca.json
- packages/core/admin/admin/src/translations/de.json
- packages/core/admin/admin/src/translations/dk.json
- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/admin/src/translations/es.json
- packages/core/admin/admin/src/translations/fr.json
- packages/core/admin/admin/src/translations/gu.json
- packages/core/admin/admin/src/translations/he.json
- packages/core/admin/admin/src/translations/hi.json
- packages/core/admin/admin/src/translations/hu.json
- packages/core/admin/admin/src/translations/id.json
- packages/core/admin/admin/src/translations/it.json
- packages/core/admin/admin/src/translations/ja.json
- packages/core/admin/admin/src/translations/ko.json
- packages/core/admin/admin/src/translations/ml.json
- packages/core/admin/admin/src/translations/nl.json
- packages/core/admin/admin/src/translations/no.json
- packages/core/admin/admin/src/translations/pl.json
- packages/core/admin/admin/src/translations/pt-BR.json
- packages/core/admin/admin/src/translations/ru.json
- packages/core/admin/admin/src/translations/sa.json
- packages/core/admin/admin/src/translations/sk.json
- packages/core/admin/admin/src/translations/sv.json
- packages/core/admin/admin/src/translations/th.json
- packages/core/admin/admin/src/translations/zh-Hans.json
- packages/core/admin/admin/src/translations/zh.json
Fixes the conditions modal:
- Adds a missing translation to the header
- Removes the duplicated headline
- Fixes the modal padding
|-|-|
| <img width="935" alt="Screenshot 2022-11-04 at 11 19 49" src="https://user-images.githubusercontent.com/2244375/199951070-b0ea1e16-3cc6-42e5-a1f6-8fa434a53598.png"> | <img width="935" alt="Screenshot 2022-11-04 at 11 19 33" src="https://user-images.githubusercontent.com/2244375/199951078-1b076a88-365f-4119-ba48-3e91a90efb86.png"> |
While looking into https://github.com/strapi/strapi/issues/14763 @maevalienard and I realized neither the padding of the `ModalBody` matches, nor has the header the proper translation.
2. Navigate to http://localhost:4000/admin/settings/roles/2
3. Open settings for one …
> ConditionsModal: Fix modal component structure and add missing translations

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/ActionRow/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/ActionRow/utils/options.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/ActionRow/utils/tests/options.test.js
Fixes the selection of multiple conditions across different categories.
Fixes the attached issue. The actual change is quite small, but I had to write a couple tests to understand the data structure 🤯 .
Instead of using one category only
Before
```js
const [[, values]] = arrayOfOptionsGroupedByCategory;
const formattedValues = values.reduce(
(acc, curr) => ({ [curr.id]: val.includes(curr.id), ...acc }),
{}
);
);
```
we need to iterate over all categories.
After
```js
arrayOfOptionsGroupedByCategory
.map(([, values]) => values)
.flat()
.reduce((acc, curr) => ({ [curr.id]: changedValues.includes(curr.id), ...acc }), {});
```
1. Create a new condition:
```js
// examples/getstarted/src/index.js
'use strict';
// ...
async bootstrap({ strapi }) {
await …
```
> ConditionsModal: Fix selection of multiple items in different categories

- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/utils/commander.js
- Adds the `strapi import` command to CLI
- import+export: now accept the filename without an `--input` or `--output` option
- pass through `maxSize` and `maxSizeJsonl` to file destination provider so it's ready once implemented
- local-file-destination-provider links+entities updated to use `options.maxSizeJsonl`
- local-file-destination-provider links updated to use received options instead of hard-coded [will conflict with #14766 but I'll handle it once that is merged]
- pass through `exclude` option to transfer engine so it's ready once implemented [PR for this will come next week]
- refactor a lot of the CLI code
To run the DEITS features from the CLI
Run variations of the `strapi import ` and `strapi export` command.  See `strapi help export` and `strapi help import` for full list …
> [DEITS] CLI command updates

- .github/dependabot.yml
Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>
This PR includes GitHub Actions in dependabot config.
Currently, dependabot is not notifying about GitHub Actions updates.
By updating the dependabot config file, it would auto notify about GitHub Actions updates going forward.
Once the PR is merged, dependabot will create upgrade PRs for GitHub Actions going forward.
> Update dependabot config to include github actions

- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
Makes file destination provider `key` optional in the type definition
`key` is only required if encryption is true and isn't otherwise needed
create a local file destination provider without a key and it should work without type errors
> [DEITS] Make encryption key type optional

- package.json
- yarn.lock
Removes the dependency `instanbul`. It doesn't appear to be used and cleans up quite a few dependencies.
Keep dependencies clean.
> Chore: Remove istanbul dependency

- packages/core/admin/package.json
- packages/core/upload/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
Updates @testing-library/dom to 8.19.0 and unifies all versions, so that dependabot can run updates on all of them at the same time.
- Reduces dependencies and keeps our test infrastructure up-to-date.
> Chore: Update @testing-library/dom to 8.19.0

- packages/core/admin/package.json
- packages/core/helper-plugin/package.json
- packages/core/upload/package.json
- yarn.lock
- Update @testing-library/react-hooks to 8.0.1 and unifies the versions used
- Reduce dependencies and keep our test infrastructure up-to-date
> Chore: Update @testing-library/react-hooks to 8.0.1

- packages/plugins/graphql/server/services/builders/mutations/single-type.js
It passes the find parameters and arguments in the right way to the findMany function
To allow filtering the right entity with the specified locale in the request
1. Activate the GraphQL and the i18n plugins
2. Create 2 locales
3. Create a Single Type and enable 2 locales for it
4. Try to update the non-default locale with a GraphQL mutation
5. Create a GraphQL query to retrieve the updated locale
6. Check that it was updated
[#14662](https://github.com/strapi/strapi/issues/14662)
> Fix the findParams argument to be passed correctly

- packages/core/database/lib/entity-manager/regular-relations.js
- packages/core/database/lib/index.js
We received a bug report with v4.5.0 for Postgres DBs that are using the `schema` option in `config/database.js`
fixes #14832
Follow instructions in #14832 
#14832
closes #14887 - Thank you for the work @zodman 🙏, I just had to make a couple of tweaks
Note: we have decided to not handle multiple PG schemas in this fix to avoid inconsistency. Theres are other places in the codebase where a similar fix will be required. They will all be handled together
<!--
1. We seem to have been using withSchema wrong in `getConnection`.
2. according to the knex docs we should have been using `connection['schema'].withSchema(schema)` not `connection.withSchema(schema)`
3. However even if used correctly that would return a `SchemaBuilder` object as documented at - …
> Fix: knex withSchema.raw error

- packages/core/database/lib/index.d.ts
- packages/core/database/lib/schema/index.d.ts
Renamed all instances of the "SchemaProvideer" interface in the core/database to correct spelling "SchemaProvider"
Minor spelling correction, not remotely important, but I saw it and felt it needed to be corrected
All references of "SchemaProvideer" were renamed, shouldn't be any issues, all tests passed locally
> Chore: fix spelling of SchemaProvideer to SchemaProvider

- packages/core/strapi/bin/strapi.js
CLI commands for import and export will check that the user is in a local Strapi directory before running
We were allowing the commands to be run anywhere which would cause a strapi-updater.json to be created since we attempt to load an instance of Strapi.
Run import + export in a Strapi project and it should still work
Run import + export in a non-Strapi folder and it should give an error instead of attempting import/export
> [DEITS] import / export should require being in local Strapi folder

- packages/core/admin/ee/server/services/__tests__/sso.test.js
- packages/core/admin/ee/server/services/passport/provider-registry.js
- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/index.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/index.ts
- packages/core/data-transfer/types/providers.d.ts
- packages/core/data-transfer/types/transfer-engine.d.ts
- yarn.lock
When using the file destination provider during a transfer process, export the metadata from the source provider (if defined) in a metadata.json file in the final archive.
This is needed to match the excepted archive structure as we will need those metadata when importing data from a file.
- `yarn strapi export`
- The metadata.json file should be created
- For now, we're using the strapi version as the version for each plugin, but it'll have to change when we'll store the plugins' versions in their state. Currently, it's not accessible.
> [DEITS] Metadata export from the local file destination provider

- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/utils/commander.js
Fixes the functionality of the --key option. It adds the following fixes:
- if encrypt is false but a key is provided, it should give an error and halt
- if encrypt is true...
- ...and empty key is provided, it should prompt
- ...and no key is provided, it should prompt
- ...and a key is provided, it should use that as the key and not prompt
Key option was broken and not working as intended
Test these scenarios:
- if encrypt is false but a key is provided, it should give an error and halt
- if encrypt is true...
- ...and empty key is provided, it should prompt
- ...and no key is provided, it should prompt
- ...and a key is provided, it should use that as the key and not prompt
> [DEITS] fix cli key

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/RelationMultiple/tests/__snapshots__/index.test.js.snap
With the upgrade to @strapi/design-system displaying multiple relations in the content-manager list-view are broken.
|-|-|
| <img width="1155" alt="Screenshot 2022-11-18 at 13 49 56" src="https://user-images.githubusercontent.com/2244375/202709076-a6367907-1f43-401b-965c-0582615ba71e.png"> | <img width="1155" alt="Screenshot 2022-11-18 at 13 49 40" src="https://user-images.githubusercontent.com/2244375/202709104-37e1c949-7eb6-48d5-9b8f-d5a0b30d7232.png"> |
Fixes a styling regression. I'm not sure where this started though.
- Builds on top of https://github.com/strapi/strapi/pull/14925
> CM: Fix RelationMultiple text wrapping

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/Settings.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/__snapshots__/index.test.js.snap
Since https://github.com/strapi/design-system/pull/720 the `ToggleInput` component in configure the view of the content-manager were visually broken:
|-|-|
| <img width="1155" alt="Screenshot 2022-11-18 at 13 38 11" src="https://user-images.githubusercontent.com/2244375/202707343-030fd55a-0c25-423b-9981-39ba844a65f7.png"> | <img width="1155" alt="Screenshot 2022-11-18 at 13 38 02" src="https://user-images.githubusercontent.com/2244375/202707351-d0a3fefa-313d-4634-bd15-dfd89dafd6eb.png"> |
Fixes a visual regression.
- http://localhost:4000/admin/content-manager/collectionType/api::address.address/configurations/list
- Refs https://github.com/strapi/design-system/pull/720
> CM: Fix ToggleInput wrapping for configure the view

- .github/actions/install-modules/action.yml
- .github/actions/install-modules/script.sh
- .github/workflows/tests.yml
- jest.config.js
- packages/core/admin/jest.config.front.js
- packages/core/helper-plugin/jest.config.front.js
This PR replaces the codecov node package with a GitHub action.
The codecov node-package is deprecated and it is recommended to use the codecov GitHub action instead.
- https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
> Chore: Update codecov uploader

- packages/core/strapi/lib/core/domain/content-type/index.js
Improve the quality of the error thrown when a new content type is registered with an invalid uid.
The code is checking that uid starts with `api`, `plugin` or `admin` but is throwing a message with a incorrect message.
Register a contentType with a no valid uid prefix.
Resolves #14869
> Rewrite invalid uid prefix error message

- packages/core/upload/admin/src/components/TableList/index.js
- packages/core/upload/admin/src/components/TableList/tests/TableList.test.js
- packages/core/upload/admin/src/constants.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/core/upload/admin/src/translations/en.json
Make `name`, `createdAt` and `updatedAt` columns sortable
Sort on any of those attributes
Should be accessible through keyboard + voice reader tools
> [features][ML listview] Sort on table headers

- .github/workflows/addToProject.yml
- .github/workflows/contributor-doc.yml
- .github/workflows/nightly.yml
- .github/workflows/tests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows.
This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- packages/core/upload/admin/src/components/TableList/TableRows.js
- packages/core/upload/admin/src/components/TableList/index.js
- packages/core/upload/admin/src/components/TableList/tests/TableList.test.js
- packages/core/upload/admin/src/components/TableList/tests/TableRows.test.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
When a user doesn't have permission to update for the Media Library:
Because selecting an asset or a folder is only useful if you have the permission to move or delete
Create a user with a role that doesn't have the permission to update on the Media Library
Check that all checkboxes to select an element is disabled
> [features][ML listview] Permissions checboxes

- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- Changes the CLI to use a `--file` or `-f` option to get the import/export filename
- Changes `--key` option to require a string value
- On import, change `--file` to be required
- On import, if file has .enc extension, prompt for --key if it's not provided
- Fixes the table at the end of export
- the file destination provider `close()` stage is now awaiting the closing of the correct stream
It matches the behaviour of other Strapi commands and of our discussions
Run `yarn strapi export --file filename` and `yarn strapi import --file filename` and it should use the filename provided.
Run `yarn strapi export --encrypt false --key anything` and you should get an error for trying to use a key without encryption
Run `yarn strapi export --key` and you should get an error about not providing a …
> [DEITS] CLI updates and fixes

- packages/core/upload/admin/src/components/AssetCard/AssetCard.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/index.test.js
- packages/core/upload/admin/src/components/Breadcrumbs/CrumbSimpleMenuAsync.js
- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
- packages/core/upload/admin/src/components/FolderGridList/tests/__snapshots__/FolderGridList.test.js.snap
- packages/core/upload/admin/src/components/FolderList/FolderList.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAsset.js
- packages/core/upload/admin/src/components/TableList/TableRows.js
- packages/core/upload/admin/src/components/TableList/index.js
- packages/core/upload/admin/src/components/TableList/tests/TableList.test.js
- packages/core/upload/admin/src/components/TableList/tests/TableRows.test.js
- packages/core/upload/admin/src/components/TableList/utils/isSelectable.js
- packages/core/upload/admin/src/components/TableList/utils/tests/isSelectable.test.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/core/upload/admin/src/utils/createAssetUrl.js
- packages/core/upload/admin/src/utils/getBreadcrumbDataML.js
- packages/core/upload/admin/src/utils/getFolderURL.js
- packages/core/upload/admin/src/utils/index.js
- packages/core/upload/admin/src/utils/tests/getFolderURL.test.js
- after discussing with design, user should be able to access edit folder/asset in ML modals
- should be added to grid view
- should fix fields not disabled in list view
- checkboxes disabled or not will be refactored to fix grid view at the same time (see `isSelectable`) 
=> refactor on this PR #14998
- deeper tests for ML / BrowseStep
> [features][ML listview] Modals

- packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/plugins.test.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/providers.test.js
This is a followup to #14935 to apply the feedback from @madhurisandbhor
It improves performance by using `getByTestId` instead of `getByRole` wherever possible.
|                   | Before | After |
|-------------------|--------|-------|
| index.test.js     | 5.4s  | 5.4s  |
| providers.test.js   | 34.9  | 30.5s |
| plugins.test.js | 66.2s  | 58.1s |
| Total             | 66.8s  | 59.4s |
> Improve marketplace tests performance

- .github/workflows/contributor-doc.yml
- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- packages/core/admin/server/tests/admin-api-token-crud.test.api.js
- packages/core/upload/tests/content-api/graphql-upload-automatic-folder.test.api.js
- packages/core/upload/tests/content-api/upload-automatic-folder.test.api.js
We thought MySQL 5 was used in Github API tests but because of some bugs it never did.
To fix that and properly us MySQL 5, I replaced the docker image `mysql` by `bitnami/mysql`.
Some options like `default-authentication-plugin`, `charset`, `collation` cannot be set properly when using `mysql` image.
A workaround for that was causing syntax issues that made "MySQL 5 tests" using MySQL 8 instead of 5.
`bitnami/mysql` image allow to pass `default-authentication-plugin` option properly and uses `utf8` by default for MySQL 5.
> Add MySQL 5.7 to Github API tests

- packages/cli/create-strapi-app/package.json
- packages/cli/create-strapi-starter/package.json
- packages/core/strapi/package.json
- yarn.lock
Upgrades the commander package from `7.2.0` to `9.4.1`
7.2.0 doesn't have the `command.hook` method that we need and use, so I'm not even sure how it was working the past few months.
Test all the Strapi commands and they should still work exactly as before.
From their [changelog](https://github.com/tj/commander.js/blob/master/CHANGELOG.md), the only breaking changes in between that seem like they might be a concern is the one about default values for boolean options.
> [deits] Upgrade commander package

- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
Use max size jsonl instead of max size for the file destination provider
Being able to use the max size jsonl option correctly
Run `yarn strapi export --max-size-jsonl=1` in an app that have more than 1MB of entities, configuration or links
> [DEITS] Use max size jsonl instead of max size for the file destination provider

- packages/core/strapi/lib/commands/transfer/export.js
- Set the Strapi instances log level to error (instances used by the strapi source provider)
- Change the table header from red to blue in the CLI (make it less look like an error)
- Remove debug prints regarding stage start & finish
> [DEITS] CLI output enhancement

- packages/cli/create-strapi-app/package.json
- packages/cli/create-strapi-starter/package.json
- packages/core/strapi/package.json
- yarn.lock
Sets the version of `commmander` package to `8.2.0` everywhere it's used.
1) A [commit by dependabot](https://github.com/strapi/strapi/commit/c16f5b9ebb45eed7fa3d6da50b218309bc0f3205) incorrectly downgraded the strapi CLI to 7.2.0 from 8.2.0 and this reverts that change
2) Use the same version of commander everywhere to reduce complexity and size of dependencies 
`create-strapi-app`
Updated from 6.1.0(previous)/7.2.0(bot last week) -> 8.2.0, and should work as before.
`create-strapi-project`
Updated from 7.1.0(previous)/7.2.0(bot last week) -> 8.2.0, and should work as before.
`strapi` command should work the same as it did last week, since 8.2.0 is the version it was previously using before the bot downgraded it.
[Commander Changelog](https://github.com/tj/commander.js/blob/master/CHANGEL …
> Use commander to 8.2.0 everywhere

- packages/cli/create-strapi-app/package.json
- packages/cli/create-strapi-starter/package.json
- packages/core/data-transfer/lib/providers/local-file-destination-provider.ts
- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/utils/commander.js
- packages/core/strapi/package.json
Replace `--encrypt <bool>` and `--compress <bool>` with `--no-encrypt` and `--no-compress`
Remove `--max-size` option for now because it hasn't been implemented yet
Allows `--max-size-jsonl` to accept a decimal value
None of the other Strapi CLI commands use booleans, they all use default values that can be turned off with a `--no-` prefixed option.
`yarn strapi export --no-compress` should now disable the compression (and `yarn strapi export --compress false` should give an error because it no longer exists as an option)
`yarn strapi export --no-encrypt` disables the key prompt and the encryption (and `yarn strapi export --encrypt false` should give an error because it no longer exists as an option)
`yarn strapi export --no-encrypt --key some_string` should still give an error about key …
> [DEITS] CLI: use --no prefix and fix max-size options

- packages/core/database/lib/metadata/relations.js
Inverse Order column name was not properly set when relationship pointed to the same content type.
To have many to many relationships pointing to the same content type. 
Use this schema in User content-type
```
"managers": {
"type": "relation",
"relation": "manyToMany",
"target": "plugin::users-permissions.user",
"inversedBy": "users"
},
"users": {
"type": "relation",
"relation": "manyToMany",
"target": "plugin::users-permissions.user",
"mappedBy": "managers"
}
```
fix #14918
> Fix: many to many relationship to the same content type gives error on save

- packages/core/database/lib/entity-manager/index.js
- packages/core/strapi/tests/api/relations.test.api.js
When trying to connect the same relations multiple times like:
```js
connect: [
{ id: 1, end: true },
{ id: 1, before: 3 }
]
```
We were inserting that same id multiple times in the database:
```js
insertDBArr = [{ id: 1 }, { id: 1 }]
```
This PR filters the insert array so we are not inserting the same id more than once in DB.
See added test.
> [relations]: Fix connect same relation id multiple times

- packages/core/data-transfer/lib/providers/local-file-destination-provider/__tests__/index.test.ts
Tests file now mocks 'fs-extra' so that the tests don't actually write a file
Currently our tests are writing an output file
Run unit tests and they should pass without writing any files to disk
> [DEITS] fix tests that are creating output files

- packages/cli/create-strapi-app/create-strapi-app.js
Updates the create-strapi-app command to work with commander v8.2.0 (it was previously written using commander v6.1.0)
There was a breaking change between commander 6.x -> 7.x that caused the options flags to not be passed through
Run `create-strapi-app --quickstart testProjName` and it should now generate a quickstart app without prompting for input
Issue: https://github.com/strapi/strapi/issues/15056
Original PR that introduced the error: https://github.com/strapi/strapi/pull/15043
> Fix create-strapi-app for commander 8.2.0

- packages/core/admin/admin/src/content-manager/components/NonRepeatableComponent/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
- packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js
- packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/tests/useLazyComponents.test.js
* Adds global cache for custom components
* Adds cleanup function to clear cache if required
* Because we don't want to pass the components all the way from the root of the page down 10 levels of components
* Allows components that require the data to access it without the need for suspense
* Automated test has been added
* resolves #15053
> [CustomInputs]: add global cache to useLazyComponents

- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/tests/RelationInputDataManger.test.js
Adds an empty array fallback for `modifiedData` to prevent a crash, if the relational field is inside a component.
Fixes a crash.
1. Use the Restaurant content-type
2. Open a dish
> RelationInputDataManager: Fix crash when relation is inside a component

- packages/core/content-manager/server/services/entity-manager.js
- packages/core/content-manager/server/services/utils/__tests__/populate.test.js
- packages/core/content-manager/server/services/utils/populate.js
It split the getDeepPopulate function into smaller ones and clean unused parameter.
Reduce maintenance cost
As getDeepPopulate is used everywhere in the Entity manager, you can test pretty much any functionality about entities in the admin panel.
> refactor(entity-manager): getDeepPopulate

- packages/admin-test-utils/lib/fixtures/store/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/actions.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/constants.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/reducer.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/tests/crudReducer.test.js
- packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewCopyLocale/index.js
* Adds `setModifiedDataOnly` to the `CRUDReducer`
* Passes this flag to `INIT_FORM` in `EditViewDataManager`
The way the CMS works is that the save button is only activated when theres a diff between modifiedData and initialData, because i18n can only load data and have the CM initialise it, it assumes this is data from the server, which is not the case for i18n. Therefore i've added a flag to imply this behaviour and then remove the flag to avoid contamination.
We also now compare initialValues from what it used to be to avoid the effect being fired too soon.
* resolves #13988
I do recognise this is a bit "hacky" IMO whether the save button can be used or not should be a side effect to updates to the store but that requires a rewrite of our redux store. I also think this highlights a …
> [CRUDReducer]: Add flag to only set modified data

- examples/getstarted/src/api/category/content-types/category/schema.json
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssets.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/tests/CarouselAssets.test.js
- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
- Displays `labelAction` for `MediaLibraryInput` component to homogenize localized fields UI
- Adds test coverage to `CarouselAssets` component
Add a media field to a localized CT
See localized icon displayed in the CM edit view of this CT
> [Fix] MediaLibraryInput localized icon

- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
* fix the styling
* Because the input grows infinitely
* resolves CONTENT-787
> fix: reset `gridTemplateColumns` otherwise component breaks out of grid

- packages/core/database/lib/entity-manager/index.js
- packages/core/database/lib/entity-manager/regular-relations.js
- packages/core/strapi/lib/services/entity-service/components.js
- packages/plugins/i18n/tests/content-manager/crud.test.api.js
Wraps in a transaction only `relation updates` instead of `entry update + relation updates`.
Since recently, relations management is done using transactions. When updating different relations simultaneously it can lead to dead locks. It's most likely to happen when handling repeatable components/dynamic zones as they are all updated independently in their own transaction and as the updates are run in parallel.
Same when updating localizations of all locales of an entry when a new locale is added (see https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/290).
The deadlock is happening only on MySQL and MariaDB because of a foreign key contraint deadlock (see this example https://gist.github.com/roustem/db2398aa38be0cc88364)
To fix that, the chosen solution is to remove …
> Fix some usecases where deadlocks can happen

- packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js
Put `inversedBy` only on one side of the many to many relations
`inversedBy` was put in both relation sides whereas it should be `inversedBy` and `mappedBy`.
It was creating 2 join tables 
Create a many to many relation with the CTB and check the 2 schemas.
Fix #14428
> Put inversedBy only once for manyToMany and oneToOne relations

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/recursivelyFindPathsBasedOnCondition.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/recursivelyFindPathsBasedOnCondition.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
* avoids undefined sections of paths in the recursive finding functions that have something like `path.undefined` with dynamic zones
* dynamic zone indicies are components but the path to the component would just be `dynamiczone.0` but we don't want the index in these paths so it thinks it should just be `dynamiczone.undefined` when looking for components, however this should actually be captured by the dynamic zone findings. It's a bit confusing.
* related to #14968
* related to CONTENT-766
> fix: filter path because a dynamic zone is a component but it should be classified as a dynamic zone

- packages/core/admin/utils/get-plugins-path.js
* if windows is the platform, split the path and rejoin with linux path separator.
* `glob` does not support the windows separator as documented [here](https://github.com/isaacs/node-glob/#windows) and you can see the recommended fix [here](https://github.com/isaacs/node-glob/issues/467#issuecomment-1114240501). This seemed to be a big thing for v8.
* run the build on a windows device (not WSL)
* resolves Ryma's issue that she spoke about internally
* resolves #14982
> [build-script]: use / as the path separator for glob.sync

- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/tests/index.test.js
- packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.js
* Turns out the indicies were passed the wrong way round, this didnt cause an issue with moving by one, but when you move a greater number, it gets very confused
* Solves re-ordering issues
Move a relation around a lot, put it at the end then move it to the top by **not** moving it all the way up through the order, it should replace itself correctly.
* resolves CONTENT-779
* resolves CONTENT-786
> [Reordering]: fix indicies order

- docs/docs/core/content-manager/hooks/use-drag-and-drop.mdx
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/components/Component.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/components/Preview.js
* removes passing the preview ref to a react component.
* breaks the empty image and renders a duplicate image on second usage.
* Drag a relation to one location
* Move the same relation after dropping
* should be no duplicate preview
* resolves CONTENT-805
> [DND]: Preview images

- packages/core/data-transfer/lib/engine/__tests__/engine.test.ts
- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-file-destination-provider/index.ts
- packages/core/data-transfer/lib/providers/local-file-destination-provider/utils.ts
- packages/core/data-transfer/lib/providers/local-file-source-provider.ts
- packages/core/data-transfer/lib/providers/local-strapi-destination-provider/__tests__/restore.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/assets.ts
- packages/core/data-transfer/types/encryption.d.ts
- packages/core/data-transfer/types/providers.d.ts
- packages/core/data-transfer/types/transfer-engine.d.ts
- only import what is needed from 'fs-extra' and 'path'
- replace some usage of *sync methods with async
- check access to the file rather than if it exists
- fix `import type` where applicable
Fixes a few minor errors
import and export should still work, tests should still pass.
> [DEITS] Fix imports and misc cleanup

- packages/core/database/lib/entity-manager/regular-relations.js
The same query than the one used for MySQL 5 (using a temporary table) is now used also for MySQL 8 and MariaDB
Deadlock issues found with the custom code for MySQL 5 were also found on the code used for MySQL 8 and MariaDB.
The custom code for MySQL 5 was recently fixed in https://github.com/strapi/strapi/pull/15034.
Since the custom code for MySQL 5 also works for MySQL 8 and MariaDB, it becomes now the default code for MySQL 5, MySQL 8 and MariaDB
Follow the steps described in https://github.com/strapi/strapi/issues/14937 by using MySQL 8 or MariaDB
fix #14937
> Fix all usecases where deadlocks can happen (for MySQL versions above 5 and MariaDB)

- package.json
`package.json`
```diff
"scripts": {
"prepare": "husky install",
-   "setup": "yarn clean && yarn && yarn build",
+   "setup": "yarn && yarn clean && yarn build",
"clean": "lerna run --stream clean --no-private",
"watch": "lerna run --stream watch --no-private",
"build": "lerna run --stream build --no-private",
```
`yarn clean` implementation in the monorepository packages assumes they have access to their dependencies. When running yarn clean before yarn install in the yarn setup, we're not fulfilling this promise & yarn clean fails.
> [DEITS] Run yarn install before yarn clean

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js
Fixes a bug in `content-manager/components/EditViewDataManagerProvider/reducer.js` that was causing the UI to error with deeply nest content structures
- Through new test added
- Follow system setup in https://github.com/strapi/strapi/issues/15038 and test through the Admin UI
fixes https://github.com/strapi/strapi/issues/15038
> Content-manager: handle complex component nesting in the UI

- docs/docs/core/content-manager/hooks/use-drag-and-drop.mdx
- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
- packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.js
* uses `isDragging` prop if an id is passed to the hook to force boolean value and not rely on monitor (useful if the component re-renders in the case of a virtualised list)
* Adds `dropSensitivity` prop to alter when an item is recognised to have changed drop zones
* To help users be able to scroll up while dragging we need a more sensitive dropzone so native browser behaviour works
* resolves CONTENT-760
> [DnD]: reordering and scrolling at the same time

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
- packages/core/admin/admin/src/translations/en.json
- packages/plugins/users-permissions/tests/content-api/auth.test.api.js
* change `confirmation` to `confirm`
* confirmation password is not correct english
> [Auth]: change confirmation to confirm

- .github/workflows/issues_dailyCron.yml
I set the wrong label :see_no_evil:
It was closing the wrong issues
N/A
https://github.com/strapi/strapi/pull/14565
> Fix typo in inactive issue cron workflow

- packages/core/database/lib/entity-manager/regular-relations.js
Remove the use of temporary tables for mysql dialect for the inverse order usecase
It was forgotten in this PR : #15143
Run the test `packages/plugins/i18n/tests/content-manager/crud.test.api.js` multiple times with mysql and see that it always passes.
#15143
> Avoid deadlocks for mysql and mariadb when creating a Nth locale

- packages/core/upload/server/services/upload.js
Add a little `.normalize();` function call to avoid problem with combined unicode.
See documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#description
Combine unicode leads to an error in the Mysql database that doesn't use `utf8mb4` charset. We may introduce the use of `utf8mb4` in the future, but for now, it seems to be too big change for little added value.
Please follow the instruction on the issue:
https://github.com/strapi/strapi/issues/14793
https://github.com/strapi/strapi/issues/14793
> fix(upload): normalize the string used as basename

- packages/core/upload/server/content-types/file/schema.js
Add indexes for sortable columns of files
When files are retrieved, they are sorted by a field like `created_at`. When there are many files, like 300k, the API response becomes slower (~1 to 2 sec). Adding an index improve the speed of the sort operation.
1. Upload a file to the ML
2. Go to your database, in the files table
3. Copy the file row (without the ID) and paste it 200k times (it's a bit long to do but you can copy several rows at the same time. You can also do an SQL loop but not on SQLite)
4. Go to the ML and check the request time before and after the fix.
Fix #14954
> Improve ML reactivity when there are many files

- packages/core/admin/admin/src/components/LeftMenu/index.js
- packages/core/admin/ee/server/services/audit-logs.js
- packages/core/admin/server/controllers/authentication.js
- packages/core/admin/server/routes/authentication.js
Logs logout events in audit logs. To do that, I had to add a new logout route, as the logout used to be frontend-only, and we only have access to the event hub in the backend.
Log out, check out your logs
> [Audit logs] Emit logout event

- packages/core/data-transfer/lib/providers/local-strapi-destination-provider/strategies/restore/entities.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/entities.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/__tests__/index.test.ts
- packages/core/data-transfer/lib/providers/local-strapi-source-provider/entities.ts
- packages/core/data-transfer/lib/providers/shared/strapi/entity.ts
- packages/core/data-transfer/package.json
Update the local strapi destination provider's ID mapping table with the components' ID.
It enables links to or from components to be imported correctly.
- Create data with relational fields in components
- Run an export
- Try to import the exported file
- The component's relations should be imported as well
> [DEITS] Fix component with relation import

- packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js
Put inversedBy only once for manyToMany and oneToOne relations when creating a content-type
A fix was already done [here](https://github.com/strapi/strapi/pull/15037) but it was partial (only fixing the issue when updating a content-type, not when creating it)
1. Create a content-type with a many-to-many relation.
2. Check the schemas
#15037
> Put inversedBy only once for manyToMany and oneToOne relations when creating a content-type

- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/index.test.js
- packages/core/upload/admin/src/components/TableList/index.js
- packages/core/upload/admin/src/components/TableList/tests/TableList.test.js
- packages/core/upload/admin/src/pages/App/MediaLibrary/index.js
- packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.js
- Fixed table headers missing some tooltip - to match CM table UI)
- Fixed wrong asset count displayed - we now display total asset count instead of current page asset count
> [fix] ML table headers and asset count

- packages/core/admin/admin/src/components/GlobalStyle/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
Moves the cropperjs CSS import from the main bundle into the upload plugin.
- it belongs in the plugin, because it is only used as part the edit asset dialog
- decreases size of the main bundle by about ~30kb because the upload plugin is code-splitted
1. Navigate to the media library
2. Edit an asset
3. Crop the asset
4. Verify everything works as expected
- Follow up of https://github.com/strapi/strapi/pull/15133
> Move cropper CSS import from main bundle to upload plugin

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
Add support for using a Numeric field as the `Entry title` for a dynamic zone display.
We call the `.trim()` method on the dynamic zone display's `Entry title` which works fine when the field is of `String` type. The `Entry Title` could be a number in some cases as highlighted in the related issue. These cases would cause a crash since the `.trim()` method is not available in type `Number`.
- Add a dynamic zone as content type to a collection type.
- Add a component containing a field of type number.
- Configure the view of the component and use that field as entry title.
- Go back to the content manager.
- Add the component, and add type values within the numeric field.
- Notice there are no errors or crash 🎉
Fixes https://github.com/strapi/strapi/issues/15210 …
> fix: Content manager crashing when dynamic zone entry field is not of type string

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findLeafByPathAndReplace.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/findLeafByPathAndReplace.test.js
fixes #14968 
When a path to relations included direct duplicate keys as
```js
['units', 'units', 'units']
```
`findLeafAndReplace` would replace the first leaf instead of making sure it is the last item in the array of paths - as recommended in the comment:
> If this is the last item in the array of paths
e.g. for a relation inside a repeatable component, it would cause the repeatable component to not be renderer as the state would reflect
```js
units: []
```
instead of 
```js
units: {
units: [{
units: []
}]
}
```
I think this fix needs a thorough QA with relations in:
- components
- repeatable components
- dynamic zones 
**example:** 
CTB:
- create a Unit content-type with a `text` field named _name_ 
- create a component Test with a `relation` field to Unit and name this relation field …
> [fix] Relation path setup 

- package.json
- packages/core/data-transfer/package.json
- Run lerna watch commands in parallel from the root scripts
- Prevent tsc from clearing the output on watch mode
- Running yarn watch at the monorepository level is not working as expected
- Run `yarn watch` at the monorepository root. Both the helper plugin & data transfer should start their watch mode in parallel
> [DEITS] Fix watch mode

- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssetActions.js
when hovering on this button, currently always shows `edit` (the `defaultMessage`) regardless of the language setting, this PR is to fix the issue.
change to a non-EN language, hover on abovementioned button, you should see the correct text
NIL
> fix: translations of CarouselAssetActions

- packages/core/data-transfer/lib/engine/index.ts
- packages/core/data-transfer/lib/providers/local-file-source-provider/index.ts
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
Strapi File Source Provider `bootstrap` now requires that metadata.json can be read from the file rather than just checking the file is accessible. That ensures that the file can be decompressed and decrypted properly, and if not, throw an error.
This allows (among other things) aborting the transfer before getting to the preTransfer stage, so a "restore" won't be done if the source can't be read.
Currently, entering an incorrect password or importing an invalid file doesn't throw an error until the transfer starts, which means the pretransfer stage is run and local Strapi destination deletes all data.
Try importing with an incorrect password and it should now abort before deleting a database.
[Alternate method to check directly in CLI](https://github.com/strapi/strapi/pull/15236) …
> [DEITS] Strapi File Source Provider bootstrap checks that file can be opened

- packages/core/admin/admin/src/components/GuidedTour/Modal/components/Content.js
fixes #15146 
| light mode  | dark mode  |  
|---|---|
| <img width="739" alt="Screenshot 2022-12-28 at 14 50 47" src="https://user-images.githubusercontent.com/71838159/209834475-d8703583-1379-4d5a-b4b9-fac16e852fda.png">  | <img width="728" alt="Screenshot 2022-12-28 at 14 51 28" src="https://user-images.githubusercontent.com/71838159/209834502-ba0b384e-50a0-41a4-a93d-020577a12b9e.png">  |
> [fix] Guided tour documentation link

- packages/core/admin/admin/src/translations/zh.json
Fix the zh translation of `content-manager.containers.Edit.information.by`
Change language to zh, the mentioned text should display `操作人`
NIL
> fix: zh translations of content-manager.containers.Edit.information.by

- .github/workflows/contributor-doc.yml
Adds the CNAME file via a config option of the GH action according to: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname
The GH Action seems to overwrite all files in the `gh-pages` branch on every deployment, which caused the `CNAME` file to get lost. Alex committed the CNAME file already twice (I guess because it was lost):
but the file still is not present in the latest version of the branch: https://github.com/strapi/strapi/tree/0cc83d7b02a7411a2df20693b5c2d2eb52a96275
https://contributor.strapi.io should be assigned again and not return a 404.
> Fix: Prevent CNAME file from being overwritten by the GH action

- .github/actions/run-api-tests/script.sh
- packages/core/strapi/package.json
Adds a `yarn build:ts` step in the API test script.
API tests are failing because they use `@strapi/data-transfer` which isn't built
API tests should pass on Github workflow
> [DEITS] Build ts files before API tests in Github workflow

- docs/package.json
- docs/yarn.lock
Bumps some minor dependencies in the `docs` folder to create a new GH pages deployment.
In https://github.com/strapi/strapi/pull/15330 I tried to fix the CNAME issue, but it did not create a new docs deployment. Why not bump a few minor dependencies to trigger it? According to https://github.com/strapi/strapi/blob/65515928a1546d884a5c287da0820cded7ca7ebe/.github/workflows/contributor-doc.yml#L3-L8 a new deployment is only triggered if something inside of `docs/` is changed.
> Chore: Bump docs dependencies

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.js
- Fixes an issue where using the 'esc' key to close `content-manager/pages/ListSettingsView/components/EditFieldForm.js` would cause a blank screen in the admin panel
- EditFieldForm would be mounted with `fieldToEdit` set to 'empty string' causing the error.
Follow linked issues
fixes https://github.com/strapi/strapi/issues/14942
fixes https://github.com/strapi/strapi/issues/14981
> fix(content-manager): close ListSettingsView/EditFieldForm with escape

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/components/RelationItem.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
⚠️ UI of disabled state (read-only) need to be discussed and approved by design before merging
do not merge before design review
When a relational field was read-only, we disabled the entire component
**With read-only permission**
the user should be able to:
- load more relations
- access the link to the relation entry
the user should not be able to:
- select new relation
- remove relation
- reorder relations
when only read permission on relational field you should see:
when no read permission on relational field you should see:
Relational field permissions need more discussion about permissions
(e.g. what happens if the user has permission to read the field but not to read the Content-type linked to this relational field)
This will be fixed later
> [fix] RelationInput read-only

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
fixes #15270 
When we generate a new component in the CM, `modifiedData` state will look like this:
```js
componentField: {}
```
Making the value of the `boolean` field, `undefined` 
When publishing we don't only need to check if the value is `null` but also `undefined` when the field is required
We will need to create `createYupSchema` tests for every use-cases
> [fix] Boolean field validation in component

- packages/core/strapi/bin/strapi.js
Force the usage of `STRAPI_EXPERIMENTAL=true` in the env variables in order to use the `yarn strapi transfer` command.
The remote transfer command is meant to be released in 4.7 and should be as experimental in the meantime.
- `yarn strapi transfer` Should fail saying transfer is an invalid command name
- `STRAPI_EXPERIMENTAL=true yarn strapi transfer` Should invoke the remote data transfer command
> [DEITS] Make remote transfer experimental

- CODE_OF_CONDUCT.md
- packages/plugins/sentry/README.md
- packages/providers/email-nodemailer/README.md
Cleans up .md files that needed to have prettier run on them.
They don't follow the `prettier` configuration standards
Run `yarn format:other` and nothing should change because now they pass.
> Clean markdown files with prettier

- package.json
Use eslint and prettier cache on the lint-staged scripts
It will save nearly a minute of time avoiding re-linting for every commit to Strapi
Commits should still run fine with no problems.
Files that have been modified should be linted again.
[Caching was added to scripts but not lint-staged in this PR](https://github.com/strapi/strapi/pull/15213)
> Use cache for lint-staged scripts

- packages/core/content-type-builder/admin/src/components/FormModal/index.js
* Adds window confirmation when the user tries to close a CTB modal with unsaved changes
* Because users loose data
Looking in the future (v5) I think we should address how modals are handled across the application and draw up rules – should they be routed or not and then come up with a powerful modal hook to be used across the app and plugins. Whilst we _could_ do this now, I think we'd run the risk of bugs.
This would hopefully be part of the DS going forward.
* resolves #13044
> [Modals]: add in prompt to CTB modals to avoid premature closing and data loss

- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/index.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.js
Apply `matchSorter` only if searching, otherwise leave the items the default ordering. 
This affects Content-Type Builder and Content Manager
fixes https://github.com/strapi/strapi/issues/15030
> [admin] fix left menu sorting behaviour

- packages/core/admin/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
Related CVE information: https://auth0.com/docs/secure/security-guidance/security-bulletins/2022-12-21-jsonwebtoken
jsonwebtoken changelog: https://github.com/auth0/node-jsonwebtoken/blob/master/CHANGELOG.md
Migration docs for v8 -> v9: https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9
Breaking changes don't appear to impact us
> Fix CVE-2022-23539 / CVE-2022-23541 / CVE-2022-23540 / CVE-2022-23529

- .github/actions/run-api-tests/script.sh
Set the STRAPI_DISABLE_LICENSE_PING env variable if the API tests are bein run with EE
Lower the useless stressing of the license server.
> Prevent license ping for api tests

- packages/core/admin/server/controllers/__tests__/admin.test.js
- packages/core/admin/server/controllers/admin.js
- packages/core/admin/server/services/__tests__/project-settings.test.js
- packages/core/admin/server/services/project-settings.js
- packages/core/admin/server/validation/project-settings.js
It adds a setting for `authLogo` (back-end)
It's needed to allow uploading and setting a custom auth logo like it's done currently for the menu logo
The easiest way to test is to start the backend from this branch, start the fronetend from the `authLogo/frontend` branch, and test the auth logo customization feature.
> feat: added authLogo setting

- packages/core/strapi/lib/core-api/service/__tests__/index.test.js
- packages/core/strapi/lib/core-api/service/single-type.js
- packages/core/strapi/tests/single-type.test.api.js
Signed-off-by: iifawzi <iifawzie@gmail.com>
Hi, this PR is addressing #14719, which mainly had two issues: 
1- Creating a single type entry using API results in the type not being published (draft):
To handle this, I've added a check as we do in the collection types, that will publish based on the config
```JS
if (hasDraftAndPublish(contentType)) {
setPublishedAt(data);
}
```
2- The second issue is that, if the type is draft, it can't be updated using the API: 
This is caused because of the query filters
https://github.com/strapi/strapi/blob/788ea22ba6fc367f4d260e21e04e345bda0a12d9/packages/core/utils/lib/convert-query-params.js#L384-L388
I've fixed it with a `onlyPublished` parameter, that will be propagated to the function, to set the `$notNull` operator to false. 
I feel like this's …
> Fix: Publishing single-type if config is true, and allow updating the drafts - api

- examples/getstarted/src/api/kitchensink/content-types/kitchensink/schema.json
- examples/getstarted/src/components/basic/relation.json
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/tests/RelationInputDataManger.test.js
- packages/core/admin/admin/src/content-manager/hooks/useCallbackRef.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
- packages/core/admin/admin/src/content-manager/utils/getMaxTempKey.js
- packages/core/admin/admin/src/content-manager/utils/paths.js
> [Relations/DynamicZones]: manage refetching and cleanData

- packages/core/admin/server/register.js
- packages/core/strapi/bin/strapi.js
Disables the remote transfer route when environment has `STRAPI_DISABLE_REMOTE_TRANSFER=true` (and, for now, when `STRAPI_EXPERIMENTAL` is not set)
Note that this also changes the required value of `STRAPI_EXPERIMENTAL` to `'true'` in line with other env in Strapi such as `STRAPI_DISABLE_EE`
To allow completely disabling the websocket for remote transfers.
Try starting strapi with variations of the environment variables `STRAPI_DISABLE_REMOTE_TRANSFER` and `STRAPI_EXPERIMENTAL` and see if the transfer route exists as expected.
> [DEITS] disable remote transfer with environment variable

- docs/docs/core/admin/link-strapi-design-system.md
- docs/sidebars.js
Adds documentation for linking the design system to complement https://github.com/strapi/design-system/pull/836
Making it easier to test DS component and inspect the bundle
Run the docs, and follow the steps
https://github.com/strapi/design-system/pull/836
> [docs] Add linking the design system docs

- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/utils/commander.js
NOTE: I accidentally based this off of https://github.com/strapi/strapi/pull/15406 so that should be reviewed and merged before this one so I don't have to rebase 😆
Adds the --force option to `strapi import`
To allow the command to be run non-interactively
run `strapi import -f ...` and the restore process should be automatically accepted without interaction
run `strapi import ...` without -f and the restore process should prompt before deleting the database
> [DEITS] Add force option

- packages/core/admin/admin/src/pages/SettingsPage/pages/AuditLogs/ListView/Modal/ActionBody.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/AuditLogs/ListView/TableRows/index.js
- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/package.json
- packages/core/helper-plugin/package.json
- yarn.lock
Adds the new JSON component from the design system in the audit logs modal
To visualize the payload
- Go to the audit logs page and open the modal, you should see the JSON component, make sure it matches the designs
> [audit logs] Add JSON component to modal

- packages/core/admin/admin/src/hooks/useFetchMarketplacePlugins/utils/api.js
- packages/core/admin/admin/src/hooks/useFetchMarketplaceProviders/utils/api.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/MarketplacePage/tests/mocks/plugins.js
- Fix axios data fetching after they introduced a breaking change in a minor release
- Remove the code to filter out v3 plugins
- axios was updated in the main branch at some point, the error popped up when merging main into the feature branch
- we don't have v3 plugins anymore
https://github.com/axios/axios/pull/5113
> Fix marketplace data fetching

- packages/core/upload/admin/src/components/AssetCard/VideoAssetCard.js
- packages/core/upload/admin/src/components/AssetGridList/tests/__snapshots__/AssetGridList.test.js.snap
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/__snapshots__/PendingAssetStep.test.js.snap
Fix #15275 
Remove pointer events on the video preview element
Cannot select or de-select a video in the content manager, this issue only appears when the canvas does not replace the video element due to being unable to load the preview. 
1- Create content with media with video enabled
2- Upload video to media in wmv format 
3- Go to the content manager
4- Create a new entry with a media field
5- Click on click to add an asset
#15275
> fix(VideoAssetCard): dissalow pointer-events on videoPreview

- packages/core/admin/package.json
- packages/core/helper-plugin/package.json
- yarn.lock
Bumps axios to 1.2.2.
[Axios 1.2.1 contains a bug](https://github.com/axios/axios/issues/5346) which is fixed in 1.2.2.
- Resolves https://github.com/strapi/strapi/issues/15398
> Chore: Update axios to 1.2.2

- packages/core/admin/admin/src/components/Notifications/Notification/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
- packages/core/upload/admin/src/translations/en.json
* Stops users being able to upload files into inputs where the input does not allow the type e.g. the input allows "image" and i try upload a "file"
* Shows notification if the file cannot be uploaded.
* In response to a community PR (#15328)
* Add a media field and set allowedTypes to "image"
* Try upload a PDF in that field
* It should show you a notification
* Closes #15328 in favour of this.
> fix: filter dropped files before trying to upload

- packages/core/admin/admin/src/content-manager/hooks/tests/useKeyboardDragAndDrop.test.js
- packages/core/admin/admin/src/content-manager/hooks/useDragAndDrop.js
- packages/core/admin/admin/src/content-manager/hooks/useKeyboardDragAndDrop.js
* Passes the active flag to the keyboard hook to stop keyboard events from firing when it's not active 
* Because when the field is disabled because of roles you shouldn't be able to use keyboard reordering
* resolves CONTENT-940
> [useKeyboardDragAndDrop]: add active to keyboard hook to stop it working when not active

- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
* uses 100% as the second column to obey the parent's width
* because if you don't do something it grows with the inner content looking dumb
* resolves CONTENT-936
> [ReactSelect]: use grids but not min-content, just 100%

- packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/helper-plugin/lib/src/components/ReactSelect/components/DropdownIndicator.js
- packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
- packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap
* removes the focus ability from the DropdownIndicator component
* This shouldn't be a button, if you look at their original version you cannot focus it, this is why the menu doesn't autoclose when you blur from the button.
* resolves CONTENT-943
> [ReactSelect]: the indicator should not be a dropdown according to their spec

- packages/core/strapi/bin/strapi.js
Adds the missing warning about "restore" for transfer
To warn users before deleting their remote db
Transfer command should now warn before running a restore
> [DEITS] Add missing confirm message to transfer

- docs/docs/core/content-manager/relations.mdx
Adds a few words of documentation about how and why the components for relations are structured the way they are.
Completes documentation.
https://strapi-inc.atlassian.net/browse/CONTENT-661
> Add tiny piece of documentation around the relation component structure

- packages/core/data-transfer/src/engine/index.ts
- packages/core/strapi/lib/commands/transfer/utils.js
Always includes schemas when --only option is used, so that schema checks can be performed.
Without the schema stage, import and transfer will throw an error because the schema checks cannot be performed.
Run export with the --only option and ensure that schemas are present. Then import the file and it should still succeed.
> [DEITS] Always include schemas when --only option is used

- packages/core/strapi/lib/commands/utils/commander.js
Removes the -f shortcut for --force because -f is for --file
It was added by mistake and shouldn't be there.
strapi export/import/transfer --help should only show --force for the force option. -f should only appear as a shortcut for --file.
> [DEITS] remove -f shortcut for force

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/components/LogoModalStepper/tests/__snapshots__/AddLogoDialog.test.js.snap
Update snapshots failing on `AddLogoDialog`
> [Fix] AddLogoDialog snapshots

- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/index.js
- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/utils/index.js
- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/utils/matchByTitle.js
- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/utils/tests/matchByTitle.test.js
Sorts collection type names in the CM the same way as the CTB (see `packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/cleanData.js`)
The order of content types in Content Manager was not alphabetical. It puts special letters like Č, Š, ... at the end. On the other hand, Content type builder have correct order.
Fixes https://github.com/strapi/strapi/issues/15342
> [FIX] LeftMenu collection type name sorting

- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customGlobalLinks.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/utils/customRoutes.js
- packages/core/admin/ee/admin/permissions/customPermissions.js
Creates a new settings page for review-workflows.
This page will be used to configure the feature.
ℹ️ Tests will follow once the state management is setup.
1. Navigate to settings
2. Verify "Review Workflow" shows up in the navigation
3. Verify you can open the page and see the feature title rendered
4. Verify the page is only visible in EE mode
> Setup review-workflows settings page

- packages/core/data-transfer/src/file/providers/source/index.ts
Fixes our tar processing so that if a tar stores a file such as "metadata.json" with the internal path "./metadata.json" we recognize it as the same file path as without the "./"
Currently, our export process creates tars with paths stored internally like "metadata.json" at the root of the tar. However, other tools such as the `tar` command store the internal path as "./metadata.json".  Since we were simply doing a string comparison on the path, it was failing to recognize they were the same file.
With this change, Strapi export files created with the `tar` command should now work with `strapi import`
- Create a valid Strapi backup folder (by running an export, then unarchiving it into a folder)
- Use a tar command such as `tar -czvf backup.tar.gz -C yourFolderName .` to archive the …
> [DEITS] process tar files that use ./ path prefixes

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
Adds a new hook `useReviewWorkflows()` which will be used to interact with the admin API for review-workflows.
It builds the data-fetching foundations.
Follow the ~white rabbit~ jest.
> Add useReviewWorkflows() data fetching hook

- packages/core/strapi/lib/utils/startup-logger.js
Added the dialect to the startup log.
Helpful when running the same Strapi app on multiple databases
NA
> add db dialect to startup info log

- packages/core/strapi/lib/core/loaders/plugins/index.js
Wraps the plugin loader in a try/catch to return a more human friendly error when a user uninstalls a plugin but does not remove it's configuration
A lot of users ask questions in Discord/Forum on how to properly uninstall a plugin and they forget to remove the configuration
Install a plugin, configure it, run Strapi, then uninstall the plugin without removing the configuration.
Before:
After:
N/A
> Fix: handle missing plugin with proper error message

- packages/core/admin/ee/server/routes/features-routes.js
Ensure only admin users with the `admin::audit-logs.read` can query audit log API routes
Security reasons, to complete the RBAC implementation
First see the problem on the `feature/audit-logs` branch:
- Log in as a non-super admin user
- Get the JWT for that user
- Using that JWT, make a get request to `/admin/audit-logs`, and `/admin/audit-logs/1`
- You get the response (you shouldn't)
Now do the same thing on this branch. You should get a 403 error with the "policy failed" error.
Uses the action defined in #15315
> [Audit logs] Fix route policy

- packages/core/strapi/lib/services/entity-service/__tests__/entity-service-events.test.js
Fix the tests for entity service failing
Because I added the UID to the events payload in #15489 (see why in the PR notes), and hadn't checked these tests. 
Run "yarn test:unit" from the root of the monorepo. On the feature branch it fails, here it should work
> [Audit logs] Fix entity service events tests

- packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/Wrapper.js
Improves (fixes) the styles for the WYSIWYG Preview panel.
|-|-|
| <img width="1108" alt="Screenshot 2023-01-24 at 15 04 49" src="https://user-images.githubusercontent.com/2244375/214315545-36a2452d-9572-4610-b2ca-89eb6e53b19d.png"> | <img width="1108" alt="Screenshot 2023-01-24 at 15 04 20" src="https://user-images.githubusercontent.com/2244375/214315554-ed293984-8182-4cb1-91a4-2907b7001fc4.png"> |
Display the preview in the same way the editor is displayed.
1. Navigate to the kitchen-sink content-type in the CM
2. Add content to a WYSIWYG field
3. Toggle the preview (expanded and not expanded)
- Refs https://github.com/strapi/strapi/issues/15407
> WYSIWYG: Fix preview pane styles 

- packages/core/upload/admin/src/components/TableList/PreviewCell.js
Update `VideoPreviewWrapper` to have the same `width` and `height` as the Avatar
Following the [DS update](https://github.com/strapi/strapi/pull/15547)
|-|-|
| <img width="576" alt="image" src="https://user-images.githubusercontent.com/71838159/214343176-bfacc375-228a-4241-8105-fdc75e59d8d8.png"> | <img width="570" alt="image" src="https://user-images.githubusercontent.com/71838159/214343088-6aa8d647-c6ea-44ef-9a17-e1f810963750.png">|
> [fix] ML Video preview size

- packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
re-creates `.gitkeep` in uploads directory during the import process
to make sure that the uploads folder is not empty 
perform an import, `.gitkeep` should exist in the uploads folder
> re-creating .gitkeep

- README.md
- packages/core/strapi/README.md
Matches the order of columns for recommended database version with recommended strapi version (Recommended first, followed by minimum)
It's confusing that the two tables have different ordering of columns
N/A
> Consistent ordering of recommended versions table in README

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
Renders a list of stages on the review workflows settings page.
| Light mode | Dark mode |
|-|-|
| <img width="1511" alt="Screenshot 2023-01-24 at 16 36 23" src="https://user-images.githubusercontent.com/2244375/214337833-39262422-ad7c-4d0f-9670-6629db1ecb24.png"> | <img width="1511" alt="Screenshot 2023-01-24 at 16 36 41" src="https://user-images.githubusercontent.com/2244375/214337906-7011f2f4-0e96-407b-aa10-cb85842ca4e3.png"> |
Right now the view relies on static data.
ℹ️ I'll add tests once the UI is connected to the store.
2. Navigate to http://localhost:4000/admin/settings/review-workflows
> ReviewWorkflows: Render list of stages on settings page

- packages/core/database/lib/tests/transactions.test.api.js
Adds some integration tests for transactions
We don't have any integration tests that try the transactions against real databases
Run packages/core/database/lib/tests/transactions.test.api.js
> Add integration tests for transactions

- packages/core/admin/admin/src/core/store/configureStore.js
- packages/core/admin/admin/src/core/store/createReducer.js
- packages/core/admin/admin/src/core/store/tests/configureStore.test.js
Registers a new method `injectReducer()` on the redux-store which allows us to dynamically inject reducers.
Review Workflows will use redux as state management. Currently it is impossible to extend the core-store without writing our own strapi-plugin and [extending reducers in the bootstrap phase](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/admin-panel.html#reducers-api).
This allows us to extend the store for individual views (such as any EE view) and follows a recommended pattern for code splitting from the redux documentation: https://redux.js.org/usage/code-splitting
```js
import { useEffect } from 'react';
import reducer from './reducer';
export function Component() {
useEffect(() => {
store.injectReducer('NS', reducer);
}, [])
return null;
} …
```
> Admin: Allow reducers to be injected async into the store

- packages/core/strapi/lib/services/entity-service/components.js
- packages/core/upload/server/services/upload.js
- packages/plugins/i18n/server/services/localizations.js
It uses sequential updates instead of Promise.all to avoid deadlocks
Because otherwise it can prevent to create a new locale for an entity or to save an entry with components
It's very difficult to test it as the deadlocks are random. Contact @Marc-Roig so he can show you how to :p
#15202
> Prevent deadlocks on components and locale updates

- test/api.js
Simply removes the `--detectOpenHandles` from the "api" tests.
Taken from the documentation:
> Remove --detectOpenHandles from "api" tests

- packages/core/admin/admin/src/hooks/useInjectReducer/index.js
- packages/core/admin/admin/src/hooks/useInjectReducer/tests/useInjectReducer.test.js
- packages/core/admin/admin/src/hooks/useInjectReducer/useInjectReducer.js
Adds a new hook called `useInjectReducer()` which is a small abstraction around `store.injectReducer`. It can be used to extend the redux store from anywhere in the codebase.
It will allow us to introduce a consistent way to extend the redux store. Right now this is is an internal hook, but it can easily be exposed and opened up to e.g. plugin developers.
Follow 🐰 jest.
- Builds on top of https://github.com/strapi/strapi/pull/15517
> Add new useInjectReducer() hook

- examples/getstarted/package.json
- examples/kitchensink-ts/package.json
- packages/generators/app/lib/utils/db-client-dependencies.js
- yarn.lock
Bumped:
- **better-sqlite3** from `7.4.6` to `8.0.1` ([change logs](https://github.com/WiseLibs/better-sqlite3/releases))
- **pg** from `8.6.0` to `8.8.0` ([change logs](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md))
> Bump database client versions

- packages/core/admin/.browserslistrc
- packages/core/helper-plugin/.browserslistrc
Excludes dead browser from the compilation target.
It ensures we are not compiling the codebase for dead browsers, such as Internet Explorer.
Overview: https://browsersl.ist/#q=last+3+major+versions%2CFirefox+ESR%2Clast+2+Opera+versions
- Based on https://github.com/strapi/strapi/pull/15369#issuecomment-1404264337
> Browserslist: exclude dead browsers

- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/Modal/ActionBody.js
- Removes the fixed on on the JSONInput
_Note_:
_The height and overflow of the Modal are defined in the DS (max-height: 60vh and overflow: auto)_
- To make reading audit logs payload easier
- Create an entity that is really big, like Address
- Go to the audit logs and open the created entry, the modal should be scrollable.
> [Audit logs] Make JSON input the size of its content

- packages/core/data-transfer/src/file/providers/source/index.ts
- packages/core/strapi/bin/strapi.js
- Prevents importing a file that does not have a valid Strapi data file extension (`.tar[.gz][.enc]`)
- Improves error message when file cannot be opened
Improve user experience with the `strapi import` command
Attempt to import a file with an invalid extension and the import should halt with an error.
Attempt to import an invalid file with an accepted extension (`.tar[.gz][.enc]`) and a more informative error message should be output.
> [DEITS] Import: Add specific error messages and only allow importing valid extensions

- packages/core/admin/package.json
- packages/core/content-type-builder/package.json
- packages/core/helper-plugin/package.json
- packages/core/upload/package.json
- packages/plugins/documentation/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
Updates react-intl from `5.25.1` to `6.2.7`
> Chore: Bump react-intl from v5 to 6.2.7

- package.json
- packages/core/admin/package.json
- packages/utils/babel-plugin-switch-ee-ce/package.json
- yarn.lock
Updates and unpins babel-dependencies.
Keep dependencies up-to-date. I think babel is in a stable state so that we don't have to pin the dependencies and can change it to use the minor release range instead.
> Chore: Update and unpin babel dependencies

- packages/core/admin/package.json
- packages/core/helper-plugin/package.json
- yarn.lock
Updates webpack dependencies:
- `webpack`: `5.74.0` -> `5.75.0`
- `webpack-cli`:  `webpack-cli` -> `5.0.1`
- `webpack-dev-server`: `4.9.3` -> `4.11.1`
Keep dependencies up to date.
> Chore: Update webpack dependencies

- packages/utils/babel-plugin-switch-ee-ce/package.json
- yarn.lock
Updates `@babel/template`.
It was forgotten in https://github.com/strapi/strapi/pull/15627.
> Chore: Update and unpin @babel/template

- packages/core/data-transfer/src/engine/index.ts
- packages/core/data-transfer/src/engine/validation/schemas/index.ts
- packages/core/data-transfer/src/utils/json.ts
- Adds a check for loose equality to the diff method and adds a message for it
- Improves messaging for diff validation errors
- 'strict' schema now allows for the case where a field is not present in one schema, and has a falsey value in the other schema <-- this one I'm not 100% sure we want, but seems reasonable. I'm looking for opinions, I'd be fine removing this until we add additional strategySchemas
The current error messages are confusing to the user.
Adding data type improves the messaging, and will also help with future enhancements when adding additional schemaStrategies.
Attempt to import a file with a mismatched schema and see the improved errors for added, removed, modified, and data type [the new one]
> [DEITS] Improve error messaging on import schema validation

- packages/plugins/color-picker/README.md
- packages/plugins/color-picker/admin/src/translations/cs.json
- packages/plugins/color-picker/admin/src/translations/en.json
- packages/plugins/color-picker/admin/src/translations/ru.json
- packages/plugins/color-picker/admin/src/translations/sv.json
- packages/plugins/color-picker/admin/src/translations/tr.json
- packages/plugins/color-picker/admin/src/translations/zh.json
1. Fixed typo with key "color-picke**t**.input.format" to "color-picke**r**.input.format". This problem was in all current translations. So I fixed it at all.
2. Added two strings (see below). Now this plugin has description as other plugins.
```
"plugin.description.long": "A Strapi-maintained color picker custom field. Use saturation and hue sliders to select a color and save the value as a HEX string.",
"plugin.description.short": "A Strapi-maintained color picker custom field."
```
3. Created translation into Russian.
4. Fixed typo in readme.md.
This plugin for now has +1 language, fixed strings with typo, added strings with description.
No need to test, this is json files with strings. You may just look into changes to see it all.
> Fix and updates for plugin translations

- packages/core/admin/admin/src/index.js
- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customAdminLinks.js
- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customGlobalLinks.js
Instead of checking whether strapi is in EE mode we need to check if the feature is enabled according to the license. It also makes it explicit `strapi` refers to `window.strapi`.
Properly support the new licensing system.
> Settings: wrap check to display review workflows in a feature flag

- yarn.lock
Bumps caniuse-lite to the latest version.
We were referencing an old database version from about 6 - 10months ago, which led to a warning in Strapi:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
This PR resolves that warning and updates the database.
> Chore: Update caniuse database

- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
This PR wires up a few things:
- `useInjectReducer`: https://github.com/strapi/strapi/pull/15570
- `useReviewWorkflows`: https://github.com/strapi/strapi/pull/15528
- the UI
With this PR we have a working implementation of the various pieces and can glue together data-fetching, state-management and the UI.
I will add more tests in a follow-up PR.
> Settings: Connect Review Workflow UI, data loader and redux

- packages/core/upload/server/services/image-manipulation.js
Support avif and heif formats in upload plugin. Specially avif is commonly used in web dev because of the compression rate it gives.
Fixes https://github.com/strapi/strapi/issues/14857
Upload [avif image ](https://libre-software.net/wp-content/uploads/AVIF/AVIF%20test%20file%20-%20Your%20browser%20%28software%29%20supports%20AVIF%20%28Quality%2025%29.avif) . 
And you should see the dimensions of the image.
https://github.com/strapi/strapi/issues/14857
> [Fix]: Support avif and heif image formats in upload plugin

- packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/transfer/transfer.js
- Turns the transfer commands back on without STRAPI_EXPERIMENTAL
- Adds --to-token (and hidden --from-token) and passes them to remote provider
- Adds a prompt for transfer tokens that are not sent in the CLI
- Tokens are always required for remote transfers, unless someone can provide a use-case where it shouldn't be. Unlimited lifespan tokens exist, so there should be no reason to ever need unrestricted transfer access outside of that.
So the transfer command accepts and sends transfer tokens
Run `yarn strapi transfer --to=http://strapiurl/admin --to-token=someToken` and the token should be sent to the websocket as a Bearer token (although it currently won't work and that part will likely change once we develop the actual transfer token system)
Run `yarn strapi transfer …
> [DEITS] Transfer: Pass tokens from CLI to remote provider

- packages/core/strapi/lib/commands/__tests__/data-transfer/export.test.js
- packages/core/strapi/lib/commands/__tests__/data-transfer/import.test.js
- packages/core/strapi/lib/commands/__tests__/data-transfer/transfer.test.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/transfer/transfer.js
- packages/core/strapi/lib/commands/utils/helpers.js
- Improves exiting and error handling for import, export, and transfer commands
- if there is an error in the data reporting, a transfer/import/export is now still reported as successful
- import now uses console.log instead of console.info to be consistent with the other commands
- improves tests for import and export
- adds tests for transfer that actually work
- removes the useless `logger = console` at the top of each command; if we actually switch to using a logger, we can add it back in later but for now it was only complicating things
To improve testing, refactoring, and fix minor messaging issues for import, export, and transfer
Tests should still pass
Import, export, and transfer commands should still work
Now if there is an error in the printing of the results table, the …
> [DEITS] Clean up import,export,transfer commands and tests

- packages/core/strapi/bin/strapi.js
removed some broken code
fix broken transfer command
run `strapi transfer --help` and there should not be an error anymore
> [DEITS] fix broken transfer command

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findLeafByPathAndReplace.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/findLeafByPathAndReplace.test.js
* Convert tests to use `inlineSnapshot` (tests were converted first and then the code changes applied to ensure accidental breaking of test)
* Set even a relation to empty array even if it's undefined because `required` fields (components) will fail.
* Jest struggles to compare an object with arrays inside efficiently so snapshot is better
* Solves issues with required components failing.
* Unit testing
* resolves #15680
* resolves CONTENT-1014
> [relations]: we should always try and apply the relation paths if they exist

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/AddStage/AddStage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/AddStage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/AddStage/tests/AddStage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/AddStage/tests/__snapshots__/AddStage.test.js.snap
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/getWorkflowValidationSchema.js
Adds the following abilities to the workflow management settings page:
- Allows to add new stages
- Allows the edit the name of existing stages
- Allows to save the current workflow
- Allows to delete stages (except the last one): we will have a confirmation dialog if the user has deleted stages - this is not part of this PR and will be done in a follow-up.
> **Note**
> The admin API is not ready yet.
The state has the following structure:
```
clientState                         // copy of the fetched state for FE comparisons
currentWorkflow: {          // copy of the default workflow (which is the first one fetched for the MVP)
data: {}                          // workflow data
isDirty: false                 // boolean flag that indicates whether the current workflow has been edited
} …
```
> Settings: Add workflow management to settings page

- packages/core/database/lib/validations/relations/bidirectional.js
Fix #15603 
Users using postgres with a schema and having the double inverseBy bug (#14428) cannot start Strapi.
1. Create a schema in your postgres DB:
```SQL
CREATE SCHEMA myschema;
```
2. Set the schema in the database config `./config/database.js`: 
```JS
client: 'postgres',
connection: {
// ...
schema: 'myschema',
// ...
},
});
```
3. Create a many-many relation between 2 content-types through the content-type builder
4. Identify the content-type schema where the previously created relation has the key `mappedBy`
5. Modify this schema file by replacing the key `mappedBy` by `inversedBy`
6. Restart the app
7. See that there is no error anymore
#15603
> Fix `hasTable` is undefined for schema postgres users

- jest.base-config.front.js
Adds `ee/admin` directory for jest to collect coverage from.
Right now we don't get a coverage report about this directory structure. Adding this directory will help us to keep track of code coverage.
The coverage report of the PR lists `ee/admin` files now: https://app.codecov.io/gh/strapi/strapi/pull/15695
> Jest: Collect coverage for ee admin folders

- packages/core/content-type-builder/admin/src/components/AttributeOptions/EmptyAttributes/index.js
From the CTB field type picker, if there was no custom field added, we had a link to the marketplace. Now we preselect the custom fields category in that link
Avoids a few clicks for the users
- go to the content type builder in a Strapi app that doesn't have a custom field installed
- click add new field, select the "custom" tab
- click on "add custom field"
- it should redirect you to the marketplace, with the custom fields category selected
> Point CTB to the marketplace custom field category

- packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js
- packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/tests/useLazyComponents.test.js
* ignore if we're loading in the effect and instead depend on newUids existing to trigger it.
* when the hook rerenders with new arguments, the effect was not triggered
* i've specifically added a new test to highlight it works
* resolves #15273
* closes #15623
> [CustomInputs]: handle the hook being re-rendered

- packages/core/admin/server/controllers/transfer/runner.js
- packages/core/admin/server/strategies/data-transfer.js
- packages/core/data-transfer/src/strapi/remote/constants.ts
- packages/core/data-transfer/src/strapi/remote/handlers.ts
- packages/core/strapi/lib/services/auth/index.js
- Add a generic `verify` option for the remote strapi handler, that's meant to be used to verify permission at a given time
- Implement a `verify` function in the transfer runner controller using the data-transfer auth strategy
- Implement scope-based authorization for transfers
- Generate a valid token & try to execute a transfer, it should work well
- Update the permission attached to your token in the database & replace 'push' by something else, then try again to transfer. You should have a forbidden error.
> [DTS] - WS Authorization 

- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
It adds a confirmation dialog that is displayed if: 1) the user saves the current workflow 2) stages that exist on the server have been deleted.
This helps to prevent accidental data loss.
1. Open the settings page http://localhost:4000/admin/settings/review-workflows
2. Delete a stage
3. Confirm the dialog is displayed
1. Open the settings page http://localhost:4000/admin/settings/review-workflows
2. Create a stage and delete it again
3. Confirm the dialog is NOT displayed
> Settings: Review Workflow: Confirm saving if a user has deleted stages

- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customGlobalLinks.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
- packages/core/admin/ee/admin/permissions/customPermissions.js
Adds a read permission check for the review workflows settings page.
Protects the page from being accessible if a user doesn't have the permissions.
1. Validate the page is not visible in the menu
2. Validate it is not possible to access http://localhost:4000/admin/settings/review-workflows
> Settings: Protect review workflows page with read permissions

- .github/actions/check-pr-status/package.json
- yarn.lock
Updates `@actions/core` and `@actions/github` dependencies.
> Chore: Update gh actions dependencies

- packages/core/admin/package.json
- packages/core/upload/package.json
- packages/plugins/documentation/package.json
- packages/plugins/i18n/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
- Updates `msw` to 1.0.0
- Move `msw` from dependencies to devDependencies
> Chore: Update msw to 1.0.0

- package.json
- packages/core/strapi/package.json
- yarn.lock
Updates the `supertest` dependency.
The new version comes with an updated `formidable` sub-dependency, which leads to a user-facing deprecation warning:
```
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
```
This is a test-only dependency and therefore the risk is very low.
- https://github.com/strapi/strapi/issues/14420
> Chore: Update supertest

- packages/core/strapi/package.json
- yarn.lock
Updates `koa-session` to v6.4.0.
Currently users see a depreaction warning:
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
The update didn't do much else than updating dependencies: https://github.com/koajs/session/commits/master so the warning during the installation goes away.
- https://github.com/strapi/strapi/issues/14420
> Chore: Update koa-session to 6.4.0

- packages/core/admin/package.json
- packages/core/admin/webpack.config.js
- yarn.lock
Removes the `node-polyfill-webpack-plugin` dependency.
Imo this is not needed anymore and stems from a time when [the admin application was still using `require`](https://github.com/strapi/strapi/pull/10219). None of the polyfilled APIs are used by the FE, but the plugin adds ~200kb to the bundle: https://www.npmjs.com/package/node-polyfill-webpack-plugin
The plugin is also responsible for a deprecation warning our users can see:
```
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```
Besides all of that this is a good cleanup of our dependencies.
- https://github.com/strapi/strapi/issues/14420
> Chore: Remove node-polyfill-webpack-plugin

- packages/core/upload/admin/src/hooks/useEditAsset.js
Fixes changing the location of a media when editing the media attributes by passing in the correct `FormData folder property` using `asset.folder`.
Currently we try to update `FormData folder property` using `asset.folder?.id` (wrong way).
1. Go to Media Library
2. Click on any image you have uploaded
3. Attempt to change the directory of the image asset
4. Confirm that the location was changed successfully
* Fixes https://github.com/strapi/strapi/issues/15722
* resolves CONTENT-1038
https://user-images.githubusercontent.com/7220167/217487251-6480408b-4a9e-4bbc-bd0a-c708854cef85.mov
> fix: Can not update media folder

- docs/sidebars.js
Fixes the doc sidebar structure.
I've made a mistake with the merge in https://github.com/strapi/strapi/pull/15321 and the docs don't build anymore.
> Docs: Fix sidebar structure

- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
It prevents admin panel users from uploading different file types than the allowed types.
Ex: A user trying to upload a pdf while the field restricts uploads to only images.
Instead, it shows a notification telling the user that the file type isn't allowed.
I tried the same issue after the latest release version(4.6.0) and found it fixed in dropped files but still exists in the normal upload flow(when someone select a file). So, I have added the validation to the normal flow too.
The `handleAssetDrop` only works whet files are dragged and dropped in the field and it doesn't get invoked when someone uploads a file by selecting it. I used `handleAddToPendingAssets` to validate the uploaded file on the normal flow.
- Start a new project.
- Create a single-type (ex: about-us) that has a media …
> Prevent uploading files that have unallowed file type

- packages/core/utils/lib/convert-query-params.js
- packages/plugins/graphql/tests/dp-relations.test.api.js
publicationState argument was not being handled when using the load function.
To filter by publicationState in graphql relations.
Using categories & countries Content type ( in getstarted), activating D&P for both:
```graphql
query Addresses($publicationState: PublicationState) {
categories() {
data {
id
attributes {
countries(publicationState: $publicationState) {
data {
id
attributes {
name
publishedAt
}
}
}
name
}
}
}
}
```
```json
{
"publicationState": "LIVE"
}
```
Fix: https://github.com/strapi/strapi/issues/15682
> [Fix]: Graphql accept publication state argument in relations

- packages/core/admin/ee/server/bootstrap.js
- packages/core/admin/ee/server/config/admin-actions.js
- packages/core/admin/ee/server/routes/index.js
Adding permissions to review workflow routes.
Now the user will need permission `admin::review-workflows.read` to access to the routes of the feature.
To be able to activate/deactivate access to users on this feature.
Try to request routes without appropriate permissions, you should end up with 403 errors.
> feat(review-workflow): add permissions

- packages/plugins/i18n/server/bootstrap.js
- packages/plugins/i18n/server/services/__tests__/localizations.test.js
- packages/plugins/i18n/server/services/localizations.js
Fix #13393
So the function `create` and `createMany` have a consistent behavior of setting the default locale when it is undefined
1. In the getStarted app, set the boostrap function as :
```js
async bootstrap({ strapi }) {
await strapi.db.query('api::country.country').createMany({ data: [{ name: 'I will have a locale' }] });
},
```
2. See that the created country does have the default locale.
#13393
> Set default locale when using Query Engine function createMany

- packages/core/database/lib/dialects/postgresql/index.js
Fix #15496
On Postgres, when the JSON value was a simple string, the value was parsed twice instead of once.
1. In the getStarted example, add a JSON field named "myjson"
2. Use this following bootstrap function
```js
async bootstrap({ strapi }) {
await strapi.entityService.create('api::country.country', { data: { name: 'Imagine the people', myjson: "coucou" } });
},
```
3. See no error
* resolves #15496
* closes #15672
> Fix JSON field for postgres when the value is a simple string

- packages/core/strapi/lib/middlewares/public/index.js
Fixes two different bugs I encountered while adding support for my plugin [strapi-middleware-upload-plugin-cache](https://github.com/alexkainzinger/strapi-middleware-upload-plugin-cache)
1. Fixes a typo, changing ``localeServer`` to ``localServer`` as described in [the docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#local-server)
2. Uses a negative lookahead regex for the public middleware to handle all fallback GET-routes except the "/uploads/(.*)". With the current implementation, the route defined in ``packages/core/upload/server/middlewares/upload.js`` never is called (I literally was able to just remove it without any errors)
If the negative lookahead regex should not make it into the codebase, the typo fix also does not matter because the route won't be called …
> Upload middleware route & typo fix

- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/tests/review-workflows.test.api.js
- packages/core/admin/server/tests/admin-permission.test.api.js
Add a check to throw an error if the user tries to delete all the stages from a workflow.
We need to have at least one stage in a workflow.
You can do the same as the integration test and tries to send a PUT request to `/admin/review-workflows/workflows/:workflow_id/stages` with an empty array `{ body: { data: [] } }`.
> feat(review-workflow): add assert on workflow deletion

- packages/core/admin/admin/src/permissions/defaultPermissions.js
- packages/core/admin/ee/admin/permissions/customPermissions.js
Moves the audit logs permissions code from CE to EE
To make sure audit logs is entirely in the EE folder (well, except translations). It was spotted by @gu-stav on Slack.
The behavior should stay the same as it was before. On the `/admin/settings/roles/1` page, you should see the audit logs section while using EE, not while using CE.
Should have been part of #15568
> Move audit logs permissions to EE

- packages/providers/upload-aws-s3/README.md
Multiple users working with TypeScript have had issues because the README specifies adding `./config/plugins.js` and does not mention adding a `.ts` config file.
Mention the `.ts` config file for TypeScript projects
Several users have reported trouble with the provider until they added the correct file extension. 
n/a
> Update the AWS S3 provider README

- packages/core/content-manager/server/services/entity-manager.js
We have to execute mapEntity before returning the relations count. (See code)
I changed the format a little bit for some methods of the entity manager, let me know what you think
To see images when saving an entity.
> [Private s3 bucket]: Fix show images when updating entity

- packages/admin-test-utils/lib/fixtures/permissions/admin-permissions.js
- packages/core/admin/admin/src/hooks/useMenu/utils/tests/getGeneralLinks.test.js
- packages/core/admin/admin/src/pages/Admin/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/Permissions/utils/tests/data.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/Permissions/utils/tests/formatLayoutForSettingsAndPlugins.test.js
- packages/core/admin/admin/src/permissions/defaultPermissions.js
- packages/core/admin/server/config/admin-actions.js
- packages/core/admin/server/controllers/admin.js
- packages/core/admin/server/routes/admin.js
- packages/core/admin/server/tests/admin-permission.test.api.js
- packages/core/helper-plugin/lib/src/utils/hasPermissions/tests/hasPermissions.test.js
- packages/core/helper-plugin/lib/src/utils/hasPermissions/tests/hasPermissionsTestData.js
- Removes the admin endpoints to install and uninstall a plugin
- Removes the actions/permissions about installing and uninstalling a plugin
- These actions were used as examples in some tests, so I replaced them by some webhook actions instead
This code is from the v3 marketplace when the marketplace allowed installing and uninstalling plugins via the admin UI. This is something that was not ported to the v4 marketplace, and that we have no plans to implement. So I'm removing all this dead code as it is not used.
The permissions about adding/removing a plugin are also misleading, since to install or uninstall a plugin you need to have terminal/git access, it has nothing to do with your Strapi role.
You shouldn't be able to see the install & uninstall plugin checkboxes in the edit role …
> Remove dead code for the install and uninstall plugin actions

- jest.base-config.front.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/cleanData.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/cleanData.test.js
- packages/core/admin/package.json
- yarn.lock
* introduces the package `fractional-indexing` (you wouldn't want to write this // maintain it yourself)
* adds `__temp_key__` to relation items on load & on connect
* mutates the `__temp_key__` when relation items are reordered.
* Diffs to see if the `__temp_key__` has changed indicating the item moved and therefore should be in the `connect` array.
* Makes the payload smaller – consider this extreme case: A user has 100 cities in their country, they move city at index 99 to index 0, _every_ relation will be sent in the API request because in the eyes of array indexing, they all moved. This is bad. Although, if we rethink how the CM works e.g. pushing PATCHES to the server instead of the whole entity, this would be redundant.
* There are unit tests 👍🏼 
* resolves CONTENT-1064
> [Relations]: Introduce fractional indexing for better diffing

- jest.base-config.front.js
Updates the compile target for swc within jest to `es2020`.
node@14 supports the full es2020 set and the less swc has to transform the smaller the output is and the faster the transpilation. This chops-off ~2min from the FE tests and will bring considerable performance boosts when running the tests locally.
Trust jest.
> Chore: Bump swc jsc.target to es2020

- .github/workflows/adminBundleSize.yml
Optimizes the GH bundle-size reporter:
- Exclude unnamed chunks for now: we still have 4 chunks with unstable names that will be reported as removed + added on every run; we know where the problem comes from (webpack.alias.js), but not yet how to fix it. I'd like to keep the action because a little insight is better than no insight
- Fixes comment permissions on PRs
Makes the bundle-size action work properly.
- https://github.com/strapi/strapi/pull/15832
> GH: Optimize GH bundle-size report setup

- packages/core/strapi/lib/commands/builders/admin.js
* calls `process.exit` after a successful admin build
* Users are experiencing node hanging after successful admin panel builds
* resolves #13614
> Call process.exit after successful build

- packages/core/upload/server/services/extensions/content-manager/entity-manager.js
- packages/core/upload/server/services/file.js
- packages/providers/upload-aws-s3/README.md
- packages/providers/upload-aws-s3/lib/index.js
- Cleanup of s3 provider.
- Added ability to set ACL
- Added ability to configure signedURL expiration time
- Added docs
- await `isProvider()`
- This method was async (it's wrapped to be async in [here](https://github.com/strapi/strapi/blob/a663322c3312a5d387d48d0605e431d4e797b3e7/packages/core/upload/server/register.js#L70-L71)) and we were not awaiting it.
I think we are reaching a point where everything works, and we could share this with Derrick and rest of the team.
In the meantime we could be adding the tests :)
> [Private s3 bucket]: Clean up s3 provider file

- packages/generators/app/lib/resources/templates/database-templates/ts/database.template
As the title says...
`ＥＸＰＲＥＳＳＩＯＮ ＥＸＰＥＣＴＥＤ． ＴＳ（１１０９）`
```ts
export default () => {}
```
[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28AUBKOAXgD44BvAXyA)
```ts
export default = () => {}
```
[Playground Link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28C8cAUAlHDgHxwDeAvkA)
None...
> Fix a tiny syntax error in `config/database.ts` of the template

- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/index.test.js
- packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap
- packages/core/content-type-builder/admin/src/pages/ListView/tests/index.test.js
* removes admin imports from CTB tests
* Technically it would mean `@strapi/admin` has to be installed in the CTB plugin – typically a weird thing to do at the moment and even weirder for tests
* Automated tests were updated, note that the strings were changed because it didn't have the default admin translations anymore (doesn't matter too much imo)
* relates to #15848 
* relates to #15855
> chore: remove admin imports from tests

- jest.base-config.front.js
- packages/admin-test-utils/lib/mocks/fetch.js
- packages/admin-test-utils/package.json
- packages/core/admin/webpack.alias.js
- packages/core/helper-plugin/lib/src/utils/request/index.js
- packages/core/helper-plugin/package.json
- yarn.lock
Drops `whatwg-fetch` dependency.
`fetch` is supported by all browsers we support according to our https://github.com/strapi/strapi/blob/main/packages/core/admin/.browserslistrc configuration.
https://caniuse.com/fetch
- https://github.com/strapi/strapi/pull/15855
> Chore: Remove whatwg-fetch polyfill

- packages/providers/upload-aws-s3/lib/__tests__/getBucketFromUrl.test.js
- packages/providers/upload-aws-s3/lib/index.js
- packages/providers/upload-aws-s3/lib/utils.js
When going to sign a url, it checks if the bucket is the same as in the provider config.
- If it is the same, it signs the url as before.
- If it is **not**, it returns the same file url.
So assets uploaded through another s3 provider are not signed. 
- Upload assets using a public s3 provider. 
- Change provider to a different one, that is private.
- See that the previous assets are broken.
> [Private S3 bucket]: Do not sign file if it comes from a different bucket

- packages/core/admin/admin/src/content-manager/pages/App/utils/generateModelsLinks.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/Permissions/utils/formatLayoutForSettingsAndPlugins.js
Remove the usage of lodash.chain from the admin FE app.
It is not possible to correctly tree-shake `chain` and once we move all lodash imports to use the optimized deep-imports these two places are not as easy as the others. I didn't want to bury this refactoring in another (bigger) PR.
Luckily both methods have tests that were very helpful.
> Chore: Remove usage of lodash chain from admin/src

- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
Updates the usage of `useEditAsset` when cropping an asset to only send the folder id.
In https://github.com/strapi/strapi/pull/15771 `useEditAsset` was updated to work with the folder-id instead of the whole folder object.
1. Upload an image to the ML in a folder
2. Crop this image and save it as duplocate
3. Verify the cropped image has been placed in the same folder
Unfortunately, I don't see a good way to test this automatically.
> EditAssetDialog: Only send the folderId when saving the cropped asset

- packages/core/upload/admin/src/hooks/tests/useConfig.test.js
- packages/core/upload/admin/src/hooks/useConfig.js
* always returns an `object` for `data`
* we assume we're always going to get an `object` so we don't do `?` checks
* automated testing!
* resolves #15751
* resolves CONTENT-1070
> fix: always return an object if data is falsey

- packages/core/upload/server/controllers/admin-upload.js
- packages/core/upload/server/services/extensions/content-manager/entity-manager.js
Use the traverse entity util instead of reimplementing the logic to map through all the entity recursively.
Simplify code.
> [Private S3]: Use traverse entity method for signing file

- packages/generators/app/lib/resources/templates/database-templates/ts/database.template
In typescript project, we need to go up two directories (relative path) in order to create the database file (otherwise it'll end up in the dist directory and will be deleted on every TS compilation)
- Creates a typescript project
- Start the server and create a content type, wait for the server to restart
- Your data (entities, admin user) should still be there (the database file too)
#15732
> Fix the relative path for sqlite database in the default database connection

- packages/core/admin/ee/server/middlewares/review-workflows.js
- packages/core/admin/ee/server/register.js
- packages/core/content-type-builder/server/controllers/validation/content-type.js
- packages/core/content-type-builder/server/controllers/validation/model-schema.js
- packages/core/content-type-builder/server/services/content-types.js
- packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js
- packages/core/utils/lib/content-types.js
Previously, we were having an "options" object inside the content-type. Still, it was created on content-type creation or update by taking the draftAndPublish attribute (sent at the root level of content-type) and then moving to the options object.
As we do not want CE to be aware of EE features, I had to let the admin panel send top level options attributesthen in BE we move those in the options object. This way, FE avoid a massive refactorization and CE is agnostic from EE features options.
We need to be able to put a new option in content-type called "reviewWorkflows" that is an EE feature, not really a plugin (that's why we didn't store this option under `pluginOptions` object in the content-type.
Now you can use POST and PUT routes on content-type builder to store a `options` object …
> feat(review-workflows): add options in content type builder

- packages/core/data-transfer/src/engine/index.ts
- packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
- packages/core/data-transfer/src/strapi/providers/remote-destination/utils.ts
- packages/core/data-transfer/src/strapi/remote/handlers.ts
- packages/core/data-transfer/types/utils.d.ts
- packages/core/strapi/lib/commands/__tests__/data-transfer/export.test.js
- packages/core/strapi/lib/commands/__tests__/data-transfer/import.test.js
- packages/core/strapi/lib/commands/__tests__/data-transfer/transfer.test.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/transfer/transfer.js
- packages/core/strapi/lib/commands/transfer/utils.js
It shows the progress of the transfer, import, and export commands to know at which stage and how advanced it is of the data transfer. 
To be conscious of the stage of the data transfer.
Run the following commands: 
`yarn strapi import -f <name-of-an-archive.tar>`
`yarn strapi transfer --to <strapi-url> --to-token <transfer-token>`
`yarn strapi export -f export --no-encrypt --no-compress`
And watch how the progress is being shown like in this loom video:
https://www.loom.com/share/0b5b451dde64462a97b595e1403e45fe
> [Data Transfer] Show the progress of the transfer

- packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
Send an "end" command upon closing the remote destination provider.
The server's transfer runner was never stopping the transfer process.
> [Data Transfer] Gracefully exit the transfer process

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/index.js
Refetches the ee license-data query, after a user has been invited or deleted.
In case an invite and deletions leads to there being more users than permitted by the license (or less), the UI needs to reflect that state.
It is not ideal, but we can discuss how we want to handle it next week.
1. Set yourself a seat-limit
```diff
diff --git a/packages/core/strapi/ee/index.js b/packages/core/strapi/ee/index.js
index d3e34b1291..f7b6e2f24c 100644
--- a/packages/core/strapi/ee/index.js
+++ b/packages/core/strapi/ee/index.js
@@ -129,6 +129,7 @@ const validateInfo = () => {
};
const checkLicense = async ({ strapi }) => {
+  return;
const shouldStayOffline =
ee.licenseInfo.type === 'gold' &&
// This env variable support is temporarily used to ease the migration between online vs offline
@@ -165,7 …
```
> Refetch the ee license-dat, after a user has been invited or deleted

- packages/core/data-transfer/src/strapi/remote/handlers.ts
Allows sending errors to client without a UUID
To be able to send results back to user even if a uuid couldn't be retrieved from the original message
Sending an invalid message should no longer throw an uncaught asnyc error on the server and instead should be returned to the websocket client as a message.
> [Data Transfer] allow ws to send error responses without uuid

- packages/generators/app/lib/resources/templates/database-templates/js/database.template
PG port was wrong when generating the database.js config it was using 3306 instead of 5432 as the default
Wrong default port
Generate a new project and see proper port in generated database config
N/A
> Fix db generated config - pg port

- packages/core/upload/server/services/extensions/content-manager/entity-manager.js
We were decorating the `mapEntity` method but we were not calling the method that was wrapped.
EntityManager mapEntity was not called before (we did not notice because it does not do anything).
> [Private S3]: Call entity manager mapEntity

- packages/core/admin/admin/src/content-manager/pages/EditView/Information/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/Information/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/EditView/InformationBox/InformationBoxCE.js
- packages/core/admin/admin/src/content-manager/pages/EditView/InformationBox/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/InformationBox/tests/InformationBoxCe.test.js
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/index.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
This PR allows EE mode to render a different information element in the CM edit view. In EE mode it will contain the current workflow stage, that is selected for an entity.
Allows users to see (not to change yet) the current workflow stage of an entity.
> CM: Display current workflow stage in the edit-view

- packages/core/content-manager/server/services/__tests__/components.test.js
- packages/core/content-manager/server/services/components.js
Fixes a bug where we were incorrectly returning `component.categoru`
Added unit test
Closes https://github.com/strapi/strapi/pull/15873
@campmedia thank you for your fix, I've only extended it slightly, adding a test to make sure we're selecting the category correctly
> [Fix] typo when returning a component category

- packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
* changes `align-items` to `center`
* it didn't want to be `flex-start`
* related to #15967
> Alignment should be center not flex-start

- docs/docs/core/content-manager/relations.mdx
- examples/getstarted/src/api/category/content-types/category/schema.json
- examples/getstarted/src/api/relation-locale/content-types/relation-locale/schema.json
- examples/getstarted/src/api/relation-locale/controllers/relation-locale.js
- examples/getstarted/src/api/relation-locale/routes/relation-locale.js
- examples/getstarted/src/api/relation-locale/services/relation-locale.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/RelationInput.test.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/tests/RelationInputDataManger.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
* Merge the existing data with new data only if the entity ids are the same
* relations are cached between locales which is typically undesired.
* Create a localised content type
* Add a relation field
* Set the relation in one locale & save
* refresh the page
* see this relation correctly there
* swap locale
* the relation field should be empty
There's also an automated test.
* resolves #15743
* resolves #15638
* resolves CONTENT-1032
* ~Is there a way to pass this string to both places so we dont rely on spelling? 🤔  cc @gu-stav~
* ~Who's responsibility is this? It feels over eager for the content-manager to dismiss the cache when any part of the URL changes? But then if someone else creates a plugin _similar_ to how i18n works then they'll need to add this code too...~
> [Relations]: solve swapping entity ids without unmounting components

- packages/core/upload/admin/src/hooks/tests/useAssets.test.js
- packages/core/upload/admin/src/hooks/useAssets.js
* Checks if the name of an asset is present and removes it from the list if not
* Checks if either `mime` or `ext` are nullish after fetching from the server and replaces with empty strings
* Having no `name` errors the admin panel
* `mime` or `ext` not being a string causes a complete crash as we run `includes` on the strings.
* You'll need to set mime to `null` in your DB and fetch your images
* There are automated tests simulating server response and what the hook now does
* partially resolves #16005
CC @gu-stav for visibility as he looked into the original issue.
> Check Mime or Ext are not nullish in useAsset hook

- packages/core/strapi/lib/services/cron.js
Add `remove()` function to allow users to remove cron jobs when they set the `name` property in the `options` config
Unable to remove a cron job programmatically
Strapi --quickstart
```js
// this will allow users to cancel the myJob cron job by doing strapi.cron.remove('myJob');
myJob: {
task: ({ strapi }) => {/* Add your own logic here */ },
options: {
rule: '0 0 1 * * 1',
},
// This will not allow removals
'0 0 1 * * 1': ({ strapi }) => {/* Add your own logic here */ },
},
};
```
`strapi.cron.remove("myJob");`
```js
//list cron jobs
strapi.cron.jobs
```
returns
```js
[
{
job: Job {
pendingInvocations: [Array],
job: [Function: fnWithStrapi],
callback: false,
running: 0,
name: '<Anonymous Job 2 2023-03-02T22:20:27.506Z>',
trackInvocation: [Function (anonymous)], …
```
> add ability to list and remove cron jobs

- .github/workflows/tests.yml
* remove running the `unit_front` tests in node matrix
* adds build check in all node versions we support
* the unit tests run in `jsdom` they don't use node APIs therefore the node version has no impact, we can reduce time.
* the build however, does need to work across all node versions
* mentioned in the FE sync
* resolves CONTENT-1129
We'll need the required checks to be changed on the branches before merging this, cc @alexandrebodin
> Only run FE unit on 18 & run build in matrix

- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/utils/commander.js
When a user doesn't enter data for a prompt, the error message works as described below.
As a shipper
- when I run the transfer
- when I don’t put any transfer token
- then I want the message No token entered, aborting transfer to be in red, and no information about the process's completion time
- when I select “N” (no) to the question The transfer will delete all data in the remote database and media files. Are you sure you want to proceed?
- then I want the error message in red Transfer process aborted
see above
> [Data transfer] aborting prompts displays as error

- packages/core/upload/admin/src/components/AssetGridList/index.js
It does fix the issue in media Library on selected tab that the was missing a key prop on return element of AssetGridList
it shows warning: Warning: Each child in a list should have a unique "key" prop.
open a collection with input for images. Select an image and switch to selected Files. check console for warning
not related
> Fix Warning: Each child in a list should have a unique "key" prop in AssetGridList

- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/transfer/transfer.js
- fixes the typings (and comments) for import/export/transfer commands
- enables only/exclude options for transfer command
--
Use `strapi transfer` with the --only and --exclude options
> [Data transfer] Add transfer command filters

- packages/core/data-transfer/src/engine/index.ts
- packages/core/data-transfer/types/transfer-engine.d.ts
- packages/core/strapi/bin/strapi.js
- packages/core/strapi/lib/commands/transfer/export.js
- packages/core/strapi/lib/commands/transfer/import.js
- packages/core/strapi/lib/commands/transfer/transfer.js
- packages/core/strapi/lib/commands/transfer/utils.js
- packages/core/strapi/lib/commands/utils/commander.js
[super low priority by the way]
Adds a hidden --throttle option to the transfer/export/import CLI to add a delay between each entity
To slow down transfers either for debugging purposes or (if documented in the future) to reduce server load.
Run a transfer/export/import and add `--throttle 1000` to add a 1000ms delay between each entity transferred.
> [Data transfer] Add throttle option (delays) to data transfers

- packages/core/helper-plugin/lib/src/components/GenericInput/index.js
The GenericInput component does not currently pass the disabled attribute to the JSONInput component, so for advanced use cases, it is not possible to achieve a readonly JSON field
Add a new GenericInput to a wiew with ``type="json"`` and ``disabled={true}`` 
FIXES #16030
> Disabled property for JSONInput (GenericInput)

- packages/core/admin/admin/src/content-manager/pages/EditView/Information/index.js
- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
- Improves the alignment of the items in the CM information sidebar
- Fixes the text-color of the active option in a react-select
- Adds a visible label to the information box stage select input
Papercut fixes.
> CM Information: Add rw stage label and improve alignment

- packages/core/content-type-builder/admin/src/components/FormModal/contentType/createContentTypeSchema.js
- packages/core/content-type-builder/admin/src/components/FormModal/index.js
- packages/core/content-type-builder/server/controllers/validation/model-schema.js
Ensures the value returned from the admin API about whether the feature is turned on or off for a given content-type is set as default value for the feature checkbox.
Otherwise users would loose the setting whether the feature is enabled/ disabled every time they save.
1. Go to the CTB
2. Enable RW on a content-type
3. Wait for restart
4. Open the content-type edit modal again
5. Verify the checkbox is set to checked
> CTB: Set default review-workflow value from admin API as input value

- packages/core/content-type-builder/server/utils/attributes.js
Returns the private configuration of media attributes on the CTB. Before , when you set a media field to be private and reload the CTB, you would see the private field was not checked.
1. Create a content-type with a media field
2. Set the media-field to private
3. Reload the page and edit the content-type
4. See the private field is checked
https://github.com/strapi/strapi/issues/10105
> [Fix] CTB return private config on media types

- docs/sidebars.js
Forgot to add sidebar links in our contributor docs, caused the build to fail.
To fix docs deploy.
> [Fix]: add links for database docs

- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/index.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.js.snap
Fixes the plus icon size in the content-type builder navigation:
|-|-|
| <img width="229" alt="Screenshot 2023-03-15 at 12 10 40" src="https://user-images.githubusercontent.com/2244375/225292333-17637566-328e-4f21-845e-b938972b3ddc.png"> | <img width="229" alt="Screenshot 2023-03-15 at 12 10 23" src="https://user-images.githubusercontent.com/2244375/225292341-5d54e6a3-69ca-4f1b-8dde-f8e26b4afed6.png"> |
I am not sure how and when this broke.
Visual regression.
> ContentTypeBuilderNav: Fix plus icon size

- packages/core/admin/server/controllers/__tests__/user.test.js
- packages/core/admin/server/tests/admin-user.test.api.js
- packages/core/content-manager/server/controllers/__tests__/single-types.test.js
- packages/core/content-manager/server/services/permission-checker.js
- packages/core/strapi/tests/api/fields/fields.test.api.js
- packages/plugins/graphql/server/services/builders/utils.js
- Fix https://github.com/strapi/strapi/issues/16095
- Revert https://github.com/strapi/strapi/pull/15877
> Fix invalid action mapping using unknow action

- packages/core/strapi/tests/api/sanitize/resources/fixtures/document.js
- packages/core/strapi/tests/api/sanitize/resources/schemas/component-b.js
- packages/core/strapi/tests/api/sanitize/resources/schemas/document.js
- packages/core/strapi/tests/api/sanitize/resources/schemas/index.js
- packages/core/strapi/tests/api/sanitize/sanitize-query.test.api.js
- packages/core/utils/lib/traverse/query-populate.js
Actual fix [here](https://github.com/strapi/strapi/pull/16109/files#diff-704f2d82e92aac3f6a5b36b9167b57cf4c255ed15d137f5816d7f4207eedf929), the rest of the changes are tests added to check we don't have this regression in the future
Prevent recursion on undefined populate fragment values upon populate traversal (during query sanitization)
Null & undefined values for the populate fragment upon query traversal cause the traversal to throw due to an unexpected Object.entries operation on an undefined value.
Using the API integration tests:
`yarn test:api packages/core/strapi/tests/api/sanitize/sanitize-query.test.api.js`
Or by starting the getstarted app, creating a new restaurant entity from the content manager, then heading to the content API and trying to access this URL …
> Fix broken populate traversal with no fragment

- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customGlobalLinks.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/AddStage/tests/__snapshots__/AddStage.test.js.snap
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- Resolve design-system TODOs
- Improve test-mocking
- Update redux-store onChange instead of onBlur
- Change menu title to use plural
Pierre reported an issue, where he typed something into a stage-name field and hit enter. The expectation is that the current value is sent, but it would use the old value, because it is only updated on blur. I don't like it either, but I think we have to update the state onChange like everywhere else.
> Review Workflows Settings: Fix papercut issues

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
Adds the onChange handler to the stage select in the CM edit view for entities.
> **Note**
> Right now this is broken, because the route is not yet implemented by the admin API and `useAPIErrorHandler()` does not handle `AxiosError`s yet. This capability is being added in https://github.com/strapi/strapi/pull/16090.
This will allow users to change the stage of an entity. This is missing tests at the moment - I will add them in a follow-up PR once the BE is working.
1. Enable Review-Workflows on a content-type in the CTB
2. Create an entity
3. Change the stage and reload the page; the stage should be persisted
> CM: Add onChange handler to entity stage select

- packages/core/admin/server/services/permission/permissions-manager/sanitize.js
Fixes sorting an filtering by publishedAt attribute.
https://github.com/strapi/strapi/issues/16099
So people can sort by `publishedAt`
Follow issue thread and replicate what is described there.
Fix https://github.com/strapi/strapi/issues/16099
> [Fix] add published at attribute to be filterable and sortable

- packages/plugins/documentation/server/config/default-plugin-config.js
- packages/plugins/documentation/server/services/__tests__/documentation.test.js
- packages/plugins/documentation/server/services/documentation.js
- packages/plugins/documentation/server/services/utils/default-openapi-components.js
- packages/plugins/users-permissions/server/register.js
The documentation plugin has a key on the config to set which plugins to generate documentation for. By default it was settings email, upload, and users-permissions. The defaults were always being applied no matter what was specified on the config.
This PR:
- Fixes the issues where defaults are always applied
- Handles the case where overrides are still applied for plugins not specified for generation
- Removes email from the defaults since it has no content-types, the documentation plugin currently can't generate documentation without a content type.
- Users can't specify which plugins they want documentation generated for. Even if they do overrides will still place
Run the automated tests: 
```
yarn test:unit packages/plugins/documentation/server/services/__tests__/
```
and/or test …
> Fix plugins generating documentation the user doesn't want

- packages/core/admin/ee/server/bootstrap.js
- packages/core/admin/ee/server/utils/persisted-tables.js
- packages/core/admin/ee/server/utils/reserved-tables.js
- packages/core/database/lib/schema/__tests__/schema-diff.test.js
- packages/core/database/lib/schema/diff.js
- packages/core/database/lib/schema/index.js
Audit logs and Review Workflows have the need to persist feature settings while the user switches between CE and EE
This way once each feature is enabled once, it's tables will be saved to the DB
> Persist DB tables for EE features

- packages/providers/upload-local/jest.config.js
- packages/providers/upload-local/lib/__tests__/upload-local.test.js
- packages/providers/upload-local/lib/index.js
> **Warning**
> Was decided to not add this feature (see discussions). Instead, a custom local upload provider or a library patch can be created to allow this feature.
> PR will add only the test to make sure the File URL is always relative
<details>
<summary>Patch to enable this feature</summary>
Create this file `patches/@strapi+provider-upload-local+4.7.1.patch` with the content below
Use [patch-package](https://github.com/ds300/patch-package) to apply it.
```diff
diff --git a/node_modules/@strapi/provider-upload-local/lib/index.js b/node_modules/@strapi/provider-upload-local/lib/index.js
index 230d920..4588eeb 100644
--- a/node_modules/@strapi/provider-upload-local/lib/index.js
+++ b/node_modules/@strapi/provider-upload-local/lib/index.js
@@ -17,7 +17,7 @@ const {
const …
```
> test(upload-local): make sure file url is always relative

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
This adds the FE event tracking for the review workflow settings page:
To understand the usage of the feature for future improvements.
> Review Workflow Settings: track events

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
- Moves the stage update mutation from the hook into the settings page
- Extend integration tests for the RW settings page
- Simplifies the data fetching hook and brings it in line with the other components
- Makes testing of the page easier, less mocking
> Settings: Inline update stage mutation, refactor tests

- packages/core/admin/admin/src/content-manager/components/InputUID/endActionStyle.js
- packages/core/admin/admin/src/content-manager/components/InputUID/index.js
- packages/core/admin/admin/src/content-manager/components/InputUID/tests/index.test.js
- Hides the regenerate button, when the field is disabled 
- Adds tests
It doesn't make sense to display the regenerate button when the field is disabled and tests are always good to have, especially when a field is as complicated as this one.
> **Note**
> It is not straight forward to get rid of the eslint ignore comments. I am open to work on these, but it needs to be a follow-up.
1. Create a content-type using a UID field
2. Set the UID field to disabled in CTB -> Configure the view -> Field
3. Verify the regenerate button is gone
- Fixes https://github.com/strapi/strapi/issues/16101
> InputUID: Hide re-generate button when field is disabled

- examples/getstarted/src/api/relation-locale/content-types/relation-locale/schema.json
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/findAllAndReplace.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/tests/findAllAndReplace.test.js
* Checks if the component exists in the `initialData` we receive
* Adds some new schema patterns to the `relations` entry so we can easier manually test relation changes
* Fixes parent on the `predicate` function to pass the `attributes` parent not the `data` parent as it should in the replacement function.
* Single components are _always_ rendered and added to the entity's schema regardless of it's required or not
* Automated tests were fixed
* resolves #16111 
* resolves CONTENT-1190
> Single components should not populate if they're not required

- packages/core/strapi/bin/strapi.js
Displays a confirmation message before deleting local data
Do a pull transfer and you should be prompted before deleting data.
If --force is used, the prompt should be bypassed
> [Data transfer] Confirm delete of local data on 'pull' transfer

- packages/core/database/lib/entity-manager/entity-repository.js
- packages/core/database/lib/entity-manager/index.js
- packages/core/database/lib/entity-manager/regular-relations.js
- packages/core/database/lib/entity-manager/relations/cloning/regular-relations.js
- packages/core/database/package.json
First step towards being able to clone entity relations.
This implements the `cloneRelations` method in the `entity-manager` db layer, which takes
```js
/**
*
* @param {*} uid - uid of the entity to clone
* @param {*} id - id of the entity to clone
* @param {*} cloneId - id of the cloned entity
* @param {object} opt
* @param {object} opt.cloneAttrs - key value pair of attributes to clone
* @param {object} opt.transaction - transaction to use
* @example cloneRelations('article', 1, 2, { cloneAttrs: { categories: true } })
*/
async cloneRelations(uid, id, cloneId, { cloneAttrs = {}, transaction }) {
```
The clone attributes will receive the list of all attributes that should be cloned.
It's an object because in further iterations, each attribute will be able to specify some specific …
> [Clone Entity Relations]: add entity-repository cloneRelations method

- packages/core/database/lib/entity-manager/entity-repository.js
- packages/core/database/lib/entity-manager/index.js
- packages/core/database/lib/entity-manager/relations/cloning/regular-relations.js
- packages/core/database/lib/metadata/relations.js
- packages/core/strapi/lib/services/entity-service/index.d.ts
- packages/core/strapi/lib/services/entity-service/index.js
Clone a single entity via the entity service.
This will:
- Clone the entity itself
- Clone entity relations
- Adds the possibility to override data from the original entity
- ⚠️ Will not clone components. Component cloning will be in another PR.
So we can clone from the CM.
In the `bootstrap.js` file, using the `getstarted` project, and with some `kitchensinks` and `tags` created:
```js
// Clones kitchensink with entity 1 and replaces some fields
await strapi.entityService.clone('api::kitchensink.kitchensink', 1, {
data: {
short_text: 'My new name',
boolean: null,
many_to_many_tags: [2],
// Overriding compos will not work in this pr
single_compo: {
id: 3,
name: 'My new name',
},
},
});
```
> [Clone Entity Relations]: Entity service clone

- packages/core/database/lib/entity-manager/relations/cloning/regular-relations.js
- packages/core/strapi/lib/services/entity-service/components.js
- packages/core/strapi/lib/services/entity-service/index.js
Follow up of https://github.com/strapi/strapi/pull/16150.
Clone a single entity and its components via the entity service.
So we can clone from the CM, including the entity components and dynamic zones.
In the `bootstrap.js` file, using the `getstarted` project, and with some `kitchensinks` and `tags` created:
```js
// Clones kitchensink with id 1 and replaces some fields
await strapi.entityService.clone('api::kitchensink.kitchensink', 1, {
data: {
short_text: 'My new name',
boolean: null,
many_to_many_tags: [2],
single_compo: {
id: 3, // <-- This will clone the original component, use the corersponding id
name: 'My new name',
category: 2,
},
repeatable_compo: [
{
id: 11, // <-- This will clone the original component, use the corersponding id
test: 'My new test',
category: 1,
},
{ // <-- …
```
> [Clone Entity Relations]: Entity service clone components

- .github/workflows/tests.yml
Fix back unit test not working because nx affected isn't doing what I want.
> Run build:ts before unit-test back

- packages/core/admin/admin/src/components/LocalesProvider/__mocks__/useLocalesProvider.js
- packages/core/admin/admin/src/hooks/useConfigurations/__mocks__/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
- Trims whitespace from registration form fields (except password fields)
- Adds tests for registration form
It fixes a bug and eases the registration process. 
1. Delete your `.tmp` folder and reload admin app
2. Enter a firstname which contains whitespace around
3. Verify you can register
- Fixes https://github.com/strapi/strapi/issues/15456
> Auth: Trim whitespace from fields 

- .github/workflows/experimental.yml
* removes the ability to dispatch the `nightly` workflow
* adds `experimental` workflow that you can dispatch
* changes `nightly` to be `next`
* `next` will now always be "main" so we can suggest users who want fixes faster to update with `strapi@next`
* `experimental` releases are now just for devs to try / test solutions
> Separate Experimental & Nightly releases

- packages/core/admin/ee/server/bootstrap.js
Review Workflows have the need to persist feature settings while the user switches between CE and EE
This way once each feature is enabled once, it's tables will be saved to the DB
> Persist RW db tables when feature is enabled

- .github/actions/run-api-tests/script.sh
- .github/workflows/tests.yml
- vercel.json
* adds `--skip-nx-cache` argument when we `build:ts` in the CI in `lint` `unit_back` & `actions/run-api-tests`
* There was a cache issue in the CI where it (fairly) assumed that the `build:ts` action did not need to run again because no files were changed, however it didn't then seem to populate the correct folders with said cache which meant the CI couldn't find the packages `logger` and `data-transfer`.
> Skip cache on `build:ts` in CI

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
* Adds a getMaxKey function that looks at the current list of workflows stages ids/_temp_key_ to calculate the next one
* Fixes the test for InformationBoxEE
* Using the length of the array assumes your stages' ids are in sequential order which isn't true
* FE unit tests will fail otherwise
* I've added an automated test & corrected another test because imo it should default to 0 if there are no stages 😓 
- resolves CONTENT-1225
> TempKeys should be calculated based on Ids & TempKeys not array length

- packages/core/data-transfer/src/strapi/providers/remote-destination/__tests__/index.test.ts
- packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
- packages/core/data-transfer/src/strapi/providers/remote-source/index.ts
- packages/core/data-transfer/src/strapi/providers/utils.ts
- packages/core/data-transfer/src/utils/providers.ts
Strips a single trailing slash, if present, from the admin url path provided by the user for a remote transfer
Some users may enter a URL such as `http://localhost/admin` and others may enter `http://localhost/admin/` and both are valid admin url paths
Entering more than a single slash is indicative of an error however, and could lead to unexpected behavior if we allowed it.
Run a transfer (push and pull) with a URL that contains a trailing slash, and that does not contain a trailing slash
> [Data transfer] Allow trailing slash from admin url in remote transfer

- packages/core/upload/package.json
- yarn.lock
Upgrade `sharp` from `0.31.1` to `0.32.0` to fix the issue described with uploading PNGs in #16227.
PNGs are uploading incorrectly as described in #16227.
Replication behavior description provided in #16227.
#16227.
> upgrade sharp to 0.32.0 to fix #16227

- packages/core/admin/ee/server/controllers/workflows/stages/index.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/tests/review-workflows.test.api.js
Moves entities related to a stage to the nearest available stage when that stage is deleted. Prioritising earlier stages in the workflow
Entities must always be in a valid stage
Added Unit test and API test
CONTENT-1221
> When deleting a stage move entities to the nearest available stage

- packages/core/strapi/lib/Strapi.js
- packages/core/strapi/lib/services/server/index.js
…llRoutes is a normal one
Set registerAllRoutes(packages/core/strapi/lib/Strapi.js)/initRouting(packages/core/strapi/lib/services/server/index.js) to ordinary function.
Make the code more elegant.
No need to test, as no effect introduced.
None
> chore: make initRouting synchronous

- packages/plugins/i18n/server/services/localizations.js
When you try to update an entity that not exists and has internationalization enabled, Strapi will throw a 500 error.
Example: [PUT] api/collection-name/id-that-not-exists.
So you receive a 400 Not found error.
Fixes: #16306
> [Fix]: Do not throw if localizations entry is empty

- packages/core/admin/package.json
Fixes the packages/core/admin `build:measure` script which was previously called `build:mesure` and sending an env variable that was similarly misspelled, so it wasn't working.
Makes the build:measure script work
Run `yarn build:measure` from packages/core/admin
> Fix typo in build:measure script

- packages/core/admin/admin/src/content-manager/pages/App/index.js
- packages/core/admin/admin/src/pages/MarketplacePage/components/EmptyNpmPackageSearch/index.js
- packages/core/content-type-builder/admin/src/components/AttributeOptions/EmptyAttributes/index.js
- packages/core/upload/admin/src/components/EmptyAssets/index.js
- packages/generators/generators/lib/files/js/plugin/admin/src/pages/App/index.js
- packages/generators/generators/lib/files/ts/plugin/admin/src/pages/App/index.tsx
- packages/plugins/users-permissions/admin/src/pages/Roles/index.js
There are two components being used that don't actually exist. NotFound from the helper-plugin and EmptyStateDocument. This PR replaces them with components that do exist.
Putting this up for review since it uses components that do exist. However I'm not sure `AnErrorOcurred` is the correct component to use for the catch-all routes. Also I'm not sure the catch-all routes are even being reached, as far as I can tell so far we are stuck with a loader or blank page. We could merge this to resolve the issue of not found components quicker and fix the rest in a second PR, either way I'm still looking into it.
A component needs to exist for it to be used
There should be no errors in the console when running yarn develop in the admin
Fixes https://github.com/strapi/strapi/issues/16266
> Fix components not found

- packages/providers/upload-aws-s3/lib/index.js
- packages/providers/upload-aws-s3/package.json
- yarn.lock
Updated aws-sdk package and ignores deprecation warning, which might be confusing for the users.
New versions of the v2 sdk log this:
```
The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
```
We also have this PR open https://github.com/strapi/strapi/pull/16319 to migrate the sdk to v3.
Run strapi and see no warning message.
Closes https://github.com/strapi/strapi/pull/16045
> chore: update aws sdk

- packages/core/content-type-builder/package.json
- packages/core/email/package.json
- packages/core/helper-plugin/package.json
- packages/core/upload/package.json
- packages/plugins/color-picker/package.json
- packages/plugins/documentation/package.json
- packages/plugins/graphql/package.json
- packages/plugins/i18n/package.json
- packages/plugins/sentry/package.json
- packages/plugins/users-permissions/package.json
- yarn.lock
Using `^` range to release the version constraints of the peerDependencies.
The original peer constraints are way too strict. We have `styled-components@5.3.6` in our project and the version can't be accepted because it's not `5.3.3`.
> chore: release peer version constraint using ^

- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/hooks/useAuditLogsData.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/tests/getDisplayedFilters.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/utils/getDisplayedFilters.js
Audit logs currently throws a 403 forbidden error when a user has the permissions to access audit logs but not the permissions to access users.
The request to users is only made for the filters
This PR proposes only displaying the filter by "user" option if the current role has permissions to users, otherwise a user will only be able to filter by "action" and "date"
- It creates an unhandled error that is not clear to the user
Run the tests in: 
```
packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/tests/getDisplayedFilters.test.js
```
Test manually:
Can read audit logs and users
- As a super admin user create a new user with the Editor role
- Go to roles -> editor -> settings
- Grant the Editor role read permissions on Audit Logs and Users (under Users and Roles)
- …
> Fix audit logs permissions error

- packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js
- packages/core/upload/admin/src/components/BulkMoveDialog/tests/__snapshots__/BulkMoveDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap
- packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap
Fixes several bugs in the admin app for review-workflows such as:
- Add loading state to Save button
- Add loading state to Confirm button
- Display Save button as disabled after changes have been saved
- Fix border-overflow on Stage component
- Fix background-color (white -> transparent) of Stage delete button
- Reset `hasDeletedServerStages` after a workflow has been saved
- Display stage empty, if no stage has been assigned (instead of crashing)
- Add loading state to Select component
- Add error message in case no stage has been assigned
- Fix assigning stages for single-types
- Add success toast message
> **Note**
> If you want to review these bugs one-by-one you can review them by commit.
Who likes 🐛 s?
See above.
> Review Workflows: Fix various bugs found by QA

- packages/providers/audit-logs-local/src/content-types/audit-log/index.ts
- packages/providers/audit-logs-local/src/index.ts
* correctly exports the `audit-logs` content type schema
* there was a regression caused by #16323 where we converted it to a named export, this is not the same as what was happening before, where we were exporting an object by default that had the key "schema"
* run `yarn develop` in the examples folder and it should work
> Don't use a named export, export an object for audit-logs content-type

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.js
Fixes https://github.com/strapi/strapi/issues/16282
Resolves the error that comes up based on the order of parameters passed to `generateNKeysBetween` function during list re-ordering
App crashes whenever a multi related item input is re-orderd.
- Create a multiple relation entry fields (1 to many).
- Add a number of related inputs to it.
- Re-order the input such that thesame item is dragged from same index and dropped in same index multiple times.
- Notice that the app does not break as a result.
https://user-images.githubusercontent.com/45232708/230404829-f6fed6dd-ec62-4892-9a0d-42bfc3b916e4.mov
https://user-images.githubusercontent.com/45232708/230402426-66176cfc-019b-4249-bc1f-871d4b65ec50.mov
> fix: Reorder relations in dynamic components crashes page

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
Fixes updating the initial state of the CM with the updated response format from https://github.com/strapi/strapi/pull/16357
In https://github.com/strapi/strapi/pull/16357 the response format was updated to be wrapped in a `data` attribute to follow the rest of the CM.
- https://github.com/strapi/strapi/pull/16357
> CM: EditView - Update API response structure

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
Displays a more user friendly error when selecting a non existing Stage.
<table border="0">
<tr>
<td><b style="font-size:30px">Before</b></td>
<td><b style="font-size:30px">After</b></td>
</tr>
<tr>
<td>
</td>
<td><img src="https://user-images.githubusercontent.com/20578351/231213355-717a6c92-f795-4316-b419-a5b10b57bb7c.png"/></td>
</tr>
</table>
- Open the edit view of one entity with RW activated
- On another tab, delete one of the RW stages
- On the original tab, try to assign the deleted RW stage without refreshing the page.
> fix(RW): Validate stage id exists when updating entity

- packages/core/content-type-builder/admin/src/components/ReviewWorkflowsToggle/index.js
Emits events when a workflow will be enabled/ disabled.
To understand how the feature is being used.
1. Toggle review-workflows on a content-type
2. Watch the network panel and validate both events are being sent at the right time
> CTB: Emit enable/disable workflow events

- packages/core/database/lib/index.js
- packages/core/database/lib/transaction-context.js
Not awaited async functions that used transactions had a weird behaviour.
If you tried , in a straipi bootsrap:
```js
const insertTag = async (strapi) => {
await strapi.entityService.create('api::tag.tag', {
data: {
name: 'tag4',
},
});
};
await strapi.db.transaction(async (trx) => {
// Without awaiting
insertTag(strapi);
});
```
Would result in the following error:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Transaction query already complete, run with DEBUG=knex:tx for more info
```
TLDR: Any async code running inside a transaction	will throw an error.
This edge case happens for any event like subscriber there is in strapi (audit …
> Fix(transactions): Do not return completed transactions

- packages/core/strapi/lib/Strapi.js
Admin code should not be related to anything related to admin, so at first this change doesn't seem necessary.
But we do have EE code that might interact with things outside Admin. In Review Workflows we want to decorate the entity service `create` to add parameters, the same we do in i18n.
User lifecycles were prioritized so if you tried to use the entityService `create` in a bootstrap method, the RW decorator was not executed. 
Impact analysis:
- Admin register/bootsrap/destroy lifecycles will be executed before user ones.
- 	Admin bootsraps:
- Admin User DB hooks
- Add permissions and other permissions
- AuditLogs Provider
- SSO Provider
-  Admin registers: 
- passportMiddleware
- add adminAuthStrategy and apiTokenAuthStrategy
- AuditLogs migrations and add register audit logs services …
> fix: Prioritize admin bootstrap

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/ReviewWorkflowsStageEE.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/index.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/tests/ReviewWorkflowsStage.test.js
Moves the `ReviewWorkflowsStage` component and column definition into the `ee` folder.
Nathan mentioned rightfully yesterday that it shouldn't be in the CE code. The main problem is that because review-workflows is not a plugin it is not possible to inject it. As a plugin this would be done using the `registerHook` function (see i18n).
> CM: DynamicTable - Move review workflow column code into ee folder

- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/actions.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/constants.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/reducer.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/tests/crudReducer.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
Updates the action executed after a stage has been changed.
The stage update response contains an entity, but it is not the same entity as the CM returns (e.g. components are missing). Therefore we can only take the partial data about the stage information to update the redux state. I've made the action name very generic because otherwise, we'd have to extend the CM reducers from the EE `InformationBox` component, which I find confusing.
> CM: Apply partial entity update after a stage has been updated

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
Updates `ReactSelect` to use `value` over `defaultValue`.
`defaultValue` is only applied once, whereas `value` is every time. When switching locales the value of the Select was properly send, but the component did not re-render and therefore didn't show the updated value.
1. Create a localized CT with RW enabled
2. Create 2 localized entities and switch between them
3. Validate the stage information is set properly on every switch
> CM: Set value instead of defaultValue to account for i18n re-renders

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
Changes the dependency array of the `didViewWorkflow` tracking event, so that it only runs when the component mounts and not on every render.
The component re-renders when e.g. new stages are added, but the event should only be send once.
2. Navigate to http://localhost:4000/admin/settings/review-workflows
3. Confirm the event it sent
4. Add a new stage
5. Confirm the event is not send again
> Settings: Track didViewWorkflow event only when component mounts

- .github/workflows/tests.yml
* only uses node 18 for lint
* Eslint doesn't behave differently on different node versions
* reduce load on GH actions
> chore: only use node 18 for lint

- packages/core/database/lib/index.js
Follow up of https://github.com/strapi/strapi/pull/16341
In some concurrent cases , during the await trx.commit() another async process picked up the transacion.
This. PR makes sure the transaction Context is cleared just before committing.
> fix: Clear transaction context just before committing

- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/DeleteLink/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
Removes the `onDeleteSucceeded` prop from the `DeleteLink` in the CM edit view.
I don't see the need to pass down the `onDeleteSucceeded` callback, when we can execute it directly as part of the `onDelete` handler which is already passed around. It only complicates things.
Create a collection-type and single-type entry and delete them. Everything should work the same way as before.
> CM: Cleanup props for CollectionType and SingleType form wrapper

- packages/core/admin/package.json
- packages/core/admin/webpack.config.js
- yarn.lock
Make running `yarn strapi build` actually use the .browserslistrc in `node_modules/@strapi/admin`. Previously, it would just look in the project directory and its parents.
Conflicting .browserslistrc in parent directories can cause Strapi to fail to build. To reproduce:
1. In a directory (say `~/parent`), create a .browserlistrc with these contents:
```
>0.5% in US
ios_saf >=9
```
2. Create a new project within parent
```sh
yarn create strapi-app test --dbclient mysql --dbhost localhost --dbport 3306 --dbname strapi --dbusername strapi --dbpassword test --dbssl false --typescript
```
3. Try running `yarn strapi build`
**Previously:** It'll fail with a message like "Transforming destructuring to the configured target environment ("chrome109", "edge109", "firefox108", "ios9") is not …
> Fix `yarn strapi build` to use admin package .browserslistrc

- packages/core/admin/ee/server/bootstrap.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/utils/persisted-tables.js
- packages/core/database/lib/schema/diff.js
Persisted tables are now removed if you remove their dependent tables.
Meaning, review workflow stage persisted table is removed if you remove it's Content Type.
> feat: Remove orphaned persisted tables when deleting CT

- packages/plugins/documentation/server/services/__mocks__/mock-content-types.js
- packages/plugins/documentation/server/services/__mocks__/mock-strapi-data.js
- packages/plugins/documentation/server/services/__tests__/documentation.test.js
- packages/plugins/documentation/server/services/helpers/build-api-endpoint-path.js
- packages/plugins/documentation/server/services/helpers/utils/loop-content-type-names.js
Check the "kind" property on the schema to determine if the response should be a list or not
Single types are using a schema component that references is a list of entities but it should just be a single entity
- Run yarn develop
- Go to swagger UI
- http://localhost:1337/documentation/v1.0.0#/Kitchensink/get%2Fkitchensinks should have 200 with an array value for data
- http://localhost:1337/documentation/v1.0.0#/Homepage/get%2Fhomepage should have 200 with an object value for data
https://github.com/strapi/strapi/issues/16409
> [plugin documentation] Fix single types using wrong response schema component

- packages/plugins/documentation/admin/src/pages/PluginPage/index.js
If you have several version of your documentation, every link on the documentation plugin page http://localhost:4000/admin/plugins/documentation will always open the current version.
To easily access every version of generated documentation
Generate a new documentation version by updating the plugins config
```
config: {
info: {version: 'x.x.x'}
}
```
Run 4000 or build the admin on 1337
Go to http://localhost:4000/admin/plugins/documentation
Click the links and confirm it opens the correct version in the Swagger UI
https://github.com/strapi/strapi/issues/16263
> Fix links always opening current version instead of selected version

- packages/core/strapi/lib/core/registries/policies.d.ts
Use [ExtendableContext](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L720) instead of BaseContext
Aligns the type with the functionality
Confirm the type is fixed by using `PolicyContext` and you can use `request` and `response` without Typescript throwing an error
Fix #16423
> Extend ExtendableContext instead of BaseContext for PolicyContext

- packages/core/admin/ee/server/services/review-workflows/__tests__/entity-service-decorator.test.js
- packages/core/admin/ee/server/services/review-workflows/entity-service-decorator.js
When updating an entity, it ignores the stage attribute if it is set to null.
To enforce the business rule of "no entity stage should be null".
See tests.
> fix: Prevent null stage on entity update

- packages/core/admin/admin/src/content-manager/pages/EditViewLayoutManager/reducer.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/actions.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/constants.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/reducer.js
- packages/core/admin/admin/src/content-manager/sharedReducers/crudReducer/tests/crudReducer.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
Update the entity stage using context.
When updating a stage on an entity which has modified (unsaved) fields the changes would be lost. Why? Because updating redux resets the entity context to the initial state from the CRUD redux reducer.
The only good part about this PR is that it is less code.
See https://strapi-inc.atlassian.net/browse/CONTENT-1271
Reverts https://github.com/strapi/strapi/pull/16415
> CM: EditView - persist stage changes in context instead of redux

- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
Updates the stage was deleted confirmation text.
The previous version was not accurate.
> Settings: Update stage delete confirmation modal text

- packages/core/helper-plugin/lib/src/components/FilterPopoverURLQuery/Inputs.js
- packages/core/helper-plugin/lib/src/components/GenericInput/index.js
- packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js
- packages/core/upload/admin/src/components/FilterPopover/FilterValueInput.js
This PR tries to fix a problem inside the Helper Plugin when we use the DateTimePicker component. 
When you try to delete the date content in a DateTimePicker field in the Content manager you have an error.
1. Create an entity schema in the Content Builder with a date+time field.  Do not make it required.
2. Go to Content Manager and use the date+time picker to select values and save it.
3. Go to Content Manager for that saved record and try to remove the datetime by clicking the "x" to the right of the field.
4. Observe nothing happens and you receive a console error.
The issue related to this PR is this one https://github.com/strapi/strapi/issues/16337
> fix "Uncaught error trying to nullify/remove a date field in Content Manager"

- packages/plugins/users-permissions/server/controllers/auth.js
Updates the users-permissions registration field blacklist during register
Making sure that certain fields cannot be set during register
Try to register a new user and set the ID during register and ensure that it cannot
Related to: https://github.com/strapi/strapi/pull/16333
> Update users-permissions registration field blacklist

- packages/admin-test-utils/lib/mocks/LocalStorageMock.js
* Converts localStorage to a Map because it's better imo and it has all the methods we want
* use Object.defineProperty instead of `=`.
* to stop this madness
* I'm hoping the FE test suite "just passes"
> use Object.defineProperty to redefine localStorage

- packages/core/content-type-builder/admin/src/components/FormModal/attributes/baseForm.js
- packages/core/content-type-builder/admin/src/translations/de.json
- packages/core/content-type-builder/admin/src/translations/dk.json
- packages/core/content-type-builder/admin/src/translations/en.json
- packages/core/content-type-builder/admin/src/translations/es.json
- packages/core/content-type-builder/admin/src/translations/fr.json
- packages/core/content-type-builder/admin/src/translations/id.json
- packages/core/content-type-builder/admin/src/translations/it.json
- packages/core/content-type-builder/admin/src/translations/ko.json
- packages/core/content-type-builder/admin/src/translations/ms.json
- packages/core/content-type-builder/admin/src/translations/nl.json
- packages/core/content-type-builder/admin/src/translations/pl.json
- packages/core/content-type-builder/admin/src/translations/pt-BR.json
- packages/core/content-type-builder/admin/src/translations/ru.json
- packages/core/content-type-builder/admin/src/translations/sk.json
- packages/core/content-type-builder/admin/src/translations/sv.json
- packages/core/content-type-builder/admin/src/translations/th.json
- packages/core/content-type-builder/admin/src/translations/tr.json
- packages/core/content-type-builder/admin/src/translations/uk.json
- packages/core/content-type-builder/admin/src/translations/zh.json
I have changed the placeholder content of the UID to follow a camel case format
UID Field component in Content builder in admin shows field naming examples that won't be possible because no space are allowed
Create a UID field and test the different language translations.
The issue related to it is https://github.com/strapi/strapi/issues/16349
> Fix "UID placeholder not meeting naming requirements"

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
Checks if the review-workflow feature is enabled rather than relying on `isEE`.
While writing the documentation I realized I made a mistake here. Even in EE mode the feature can be disabled. This should be the only part which is still executed when the feature is disabled manually via https://github.com/strapi/strapi/pull/16458
- https://github.com/strapi/strapi/pull/16458
> CM: ListView - Check if review-workflows are enabled instead of relying on isEE

- docs/docs/core/content-manager/review-workflows.mdx
- docs/docs/core/content-type-builder/review-workflows.mdx
- docs/docs/core/settings/intro.mdx
- docs/docs/core/settings/review-workflows.mdx
- docs/sidebars.js
Extends the contributor documentation with review workflows.
To allow everyone to have a good understanding about how the feature works technically and what the building blocks are.
> Docs: Extend contributor documention with review workflows (frontend)

- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/components/Component.js
* changes the `type` we pass to `useDragAndDrop` to use the full componentFieldName par the last item (the index of the path)
* Nested repeatable components would use the initial parent name (foolishly forgetting they could be nested) therefore using the full `fieldName` par the `index` of the individual component re-isolates the components drag and drop bounds
* Have a nested repeatable component
* Move an item in the "outer level"
* Move an item in the "lower level" while dragging it to the space the "outer-level" occupies
* the "outer level" items should not reorder then
* resolves #15764
> [RepeatableComponents]: Use the full key par the index for the type

- packages/providers/upload-aws-s3/src/index.ts
This [PR](https://github.com/strapi/strapi/pull/16285) work was lost in a git merge during the TS migration of upload providers.
This reverts back the change.
> fix: S3 Upload Provider "baseUrl" for Video uploads on DO spaces 

- docs/docs/core/admin/link-strapi-design-system.md
Updates the yarn link instructions for linking the design system
yarn link works differently with yarn 3
Make a change in a local copy of the design system
Follow the instructions and verify your local ds is being used
> Update ds yarn link docs

- CONTRIBUTING.md
Add instructions about running `yarn install` before `yarn setup` in order to setup Strapi for development.
Yarn 3 requires running a first yarn install before being able to use custom package.json scripts. (which is verified by the existence of node_modules).
- Remove the node_modules from your strapi repository
- Follow the contributing.md instruction to setup your project.
- You shouldn't encounter any error
> Update the contribution guidelines based on the yarn 3 requirements

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/select.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/utils/tests/select.test.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/TableRows/index.js
* uses the `originId` to fetch the relations and _only_ add them to the `modifiedData` via `useRouteMatch` hook
* When you clone an entity and it cannot be automatically done because of prohibited fields we should show all the values from the original entity, in the case of relations we were only ever using the id from `modifiedData` to pre-populate the field, when cloning it want's to use the origin Id so you get the whole "cloning" experience.
* resolves CONTENT-984
* completes this iteration of the feature 🤝🏼
> Find the origin & only load to modified data under the clone route

- packages/core/admin/ee/server/services/review-workflows/stages.js
Metrics method name was not correct, and one test was failing.
> fix(RW): change metrics method name

- packages/core/admin/ee/server/controllers/authentication/middlewares.js
Adds a new configuration option to the admin config to allow setting the cookie domain used as a transmit method for SSO authentication between different admin/backend domains.
Example configuration:
```js
auth: {
// ...
domain: env("SSO_DOMAIN", ".example.com"),
providers: [
// ...
],
},
url: env("ADMIN_URL"),
serveAdminPanel: env.bool("SERVE_ADMIN", true),
// ...
});
```
Currently we set the cookie to the backend domain which is not valid for the admin to pull the JWT from.
Complicated, see internal slack threads on the issue: https://strapihq.slack.com/archives/CEN0F9WF6/p1682085852948869
Was validated by me, @Convly, @christiancp100, @simotae14, @alexandrebodin, and @marcoautiero in Discord
fixes #16468
> Allow configuration of SSO Cookie Domain

- packages/utils/typescript/lib/generators/schemas/schema.js
It adds the correct typing to the collectionName of a content type.
To get better autocompletion when using typescript
Create a content type in a strapi typescript project, generate the types and go to the index.ts of your project, to the bootstrap function and create the next constant: 
```
import '@strapi/strapi';
...
async bootstrap({ strapi }: { strapi: Strapi.Strapi }) {
const toy = {} as Strapi.Schemas['api::toy.toy'];
toy.collectionName == "toys" // should be OK 
toy.collectionName == "food" // should highlight an error
},
...
```
> Add correct typing to collectionName

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/OptionColor/OptionColor.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/OptionColor/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/SingleValueColor/SingleValueColor.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/SingleValueColor/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stages.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/tests/ReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/colors.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/getWorkflowValidationSchema.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/tests/colors.test.js
Implements the color select input on the review workflows settings page.
Users want to be able to better differentiate stages and colors might help.
2. Navigate to `/admin/settings/review-workflows`
The backend PR is: https://github.com/strapi/strapi/pull/16482
Figma: https://www.figma.com/file/kUc57IY8AV40L5qaoZDXxv/%5B%E2%9C%85DONE%5D-Content-squad---Review-workflows?node-id=768-18744&t=eAlbGL2qT3O7x8wV-4
> Settings: Implement color select for stages

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/Permissions/utils/tests/updateValues.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/Permissions/utils/updateValues.js
Fixes https://github.com/strapi/strapi/issues/16176
Handles the edge case where it's not possible to update the role of a field named `conditions` 
Based on existing logic, any field named `conditions` would not be updated whenever we attempt to update the field role from parent checkbox
- Steps to reproduce the behavior
- Create a new Strapi project
- Create a new Collection Type and add a text field named as "conditions"
- Go to the Settings -> Roles page and select any role to edit
- Click the checkbox next to the name of the previously created Collection Type to check/uncheck all permissions
- Notice that everything is working as expected.
https://user-images.githubusercontent.com/45232708/232027924-d87a3ea8-3714-4bc6-8214-2f8c48d3915c.mov
---
This code was written and reviewed by …
> STRAP-481 - Field named "conditions" break the checkboxes on the "Edit a role" screen

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/content-types/workflow-stage/index.js
- packages/core/admin/ee/server/validation/review-workflows.js
Modified `PUT /review-workflows/workflows/:workflow_id/stages`
To send the stage color
```js
{
[
{
id: number;
name: string;
color: string;
},
]
}
``` 
- Added color attribute in Stage Content Type.
- Default color is “blue“ (`#4945FF`).
- Added regex validation  `^#(?:[0-9a-fA-F]{3}){1,2}$`
Right now front is sending a null value for the `stage` `color` attribute, and so the validation is failing. 
@gu-stav maybe the frontend work can continue on top of this PR.
> feat(RW): add stage color attribute

- docs/docs/core/admin/ee/intro.md
- docs/docs/core/admin/ee/review-workflows.md
- docs/docs/core/admin/intro.md
- docs/sidebars.js
Adding the technical design part to the contributor documentation
Open a terminal inside the Strapi project:
- `cd ./docs`
- `yarn`
- `yarn start`
- Open browser
- Navigate to Admin/Enterprise Edition/Review Workflows
> docs(contrib): add review workflows tech design

- packages/core/helper-plugin/src/features/AutoReloadOverlayBlocker.js
* Changes the property names for AutoReloadOverlayBlockerContextValue to what they _should_ have been
* It was a breaking change in the `helper-plugin` and subsequently broke the CTB 
* add a new field to a content-type in the CTB
* save
* no errors 🪄 
* resolves #16542
> fix: AutoReload context value had incorrect names for object properties

- packages/core/strapi/lib/core/loaders/apis.js
Strapi outputs a server error message when a schema fails to load on startup
To prevent confusion when a developer accidentally leaves an empty content type directory structure in a Strapi project.
Currently when a Strapi project has an empty content type directory structure and the project is started, an error is thrown in `validateContentTypesUnicity` because schema.info doesn't exist because it was never loaded:
This PR adds an actual error check for an empty schema before it gets to that point, so that the user knows exactly what is causing the error instead of it appearing to be a general strapi error that is difficult to solve:
Create a content type in the CTB and then delete the schema files without removing the directory structure and try to start Strapi. You should get a nicer …
> Add error message when empty content type directory exists in project

- packages/generators/app/src/create-project.ts
- packages/generators/app/src/utils/git.ts
Automatically init a Git repository in any newly created Strapi project.
It avoids users having to do this manually.
- Clone this repository
- Run `yarn`.
- Run `yarn setup`.
- In `test/helpers/test-app-generator.js`, replace `rootPath: path.resolve(appName),` with `rootPath: path.resolve('..', appName),` so the new project will be created outside of the `strapi` folder (which already has Git initiated).
-  Run `yarn test:generate-app sqlite`.
None.
> Init Git on project creation

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/helper-plugin/src/components/DynamicTable/TableHead/index.js
Allows the CM list view to be sorted by relational fields. Since relations are currently not setup properly (they are lacking at least the `mainField` attribute and are all set to `sortable=false`) this only applies to stages.
Will help users to sort the list according to their needs.
> CM: Allow list-view to be sorted by stages

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/ReviewWorkflowsStageEE.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/tests/ReviewWorkflowsStage.test.js
Renders the stage color in the CM list-view next to the stage.
It may help users to differentiate stages better.
> CM: Render stage color in the list-view

- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/utils/persisted-tables.js
- packages/core/database/lib/schema/diff.js
Depends on persisted tables should be an array not an object
When deleting a CT you now get 
```
[2023-04-27 18:08:01.490] error: table?.dependsOn?.some is not a function
TypeError: table?.dependsOn?.some is not a function
at /Users/marcroig/Documents/strapi/strapi/packages/core/database/lib/schema/diff.js:367:38
at Array.filter (<anonymous>)
at Object.diffSchemas [as diff] (/Users/marcroig/Documents/strapi/strapi/packages/core/database/lib/schema/diff.js:366:12)
at async Object.syncSchema (/Users/marcroig/Documents/strapi/strapi/packages/core/database/lib/schema/index.js:53:32)
at async Strapi.bootstrap (/Users/marcroig/Documents/strapi/strapi/packages/core/strapi/lib/Strapi.js:457:5)
at async Strapi.load (/Users/marcroig/Documents/strapi/strapi/packages/core/strapi/lib/Strapi.js:491:5) …
```
> fix: rw depends on should be an array

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/ReviewWorkflows.js
Updates the error handling when editing stages.
Before in case the content API threw an error both success and error notifications were shown. Now only one can be visible.
To make testing easier you can set the limit in https://github.com/strapi/strapi/blob/09e21070815dd1fad10071ca69f7fe2239a25a14/packages/core/admin/ee/server/validation/review-workflows.js#L10-L14
to a very low value.
> Settings: Improve error handling for stage update errors

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
RW stage color was not being updated if the stage name was not also updated at the same time.
> fix(RW): update stage if only color changes 

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/OptionColor/OptionColor.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/SingleValueColor/SingleValueColor.js
Makes the color badges for the stage select `flex-shrink: 0`.
Long stage names caused the color dot to shrink.
1. Create a stage using a very long name.
2. Make sure the color dot does not shrink and keeps it shape.
> Settings: Fix color badge with long stage names

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/ReviewWorkflowsStageEE.js
Adds a max-length for stage names.
Long stage names are cut off everywhere but can still exceed the CM list view.
> CM: Add max length for stage names in the list-view

- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js
- packages/core/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js
* Posts to `/clone/origin` if we're "cloning" (I should have done this before, I misunderstood)
* removes the workaround for relations, because we're creating an entity the save button is active regardless, this also fixes a bug I introduced 👍🏼 
* Posting to `clone/origin` is important because that's where we clone relations not loaded in the entity
* Fixes a bug with relations count & loading but also ensures our data-packet that we send is slim af
* make an entity with more than 5 relations
* clone that entity
* you should see "load more" (don't click it)
* save the clone
* your new entity should have the same clone even though you didn't send them all 🥳 
* resolves CONTENT-1292
> Cloning entities FE fixes

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
Updates the success notification text after a stage for an entity has been updated.
Makes it clearer for users what has been saved.
> Chore: Update success notification text

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
Wraps the stage action buttons in a new DOM element.
`AccordionToggle` applies a `gap` of `12px`, which is not wanted here. The buttons should be close together.
> Fix: Reset gap between stage action buttons

- jest-preset.unit.js
- package.json
- test/helpers/test-app.js
- test/scripts/generate-test-app.js
- yarn.lock
Changes necessary, because on `main` the way API tests run were changed and generators are now based on TS.
This is an attempt to merge work from https://github.com/strapi/strapi/pull/16242, https://github.com/strapi/strapi/pull/16392 and https://github.com/strapi/strapi/pull/14807.
> Chore: Update e2e tests with recent TS and API test changes

- packages/providers/upload-aws-s3/package.json
- yarn.lock
bumps aws-sdk to 2.1372.0
Fixes https://github.com/strapi/strapi/issues/16461
> chore: bump aws-sdk version

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/controllers/content-api/workflows/index.js
- packages/core/admin/ee/server/controllers/content-api/workflows/stages/index.js
- packages/core/admin/ee/server/controllers/index.js
- packages/core/admin/ee/server/routes/review-workflows.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/services/review-workflows/workflows.js
- packages/core/admin/ee/server/validation/review-workflows.js
- packages/core/strapi/lib/services/server/register-routes.js
Adding routes available from the content-api to manipulate the review workflow feature.
- Run your project in Enterprise edition
- Use an API-Token (permissions are not part of this PR but we need a valid token)
There is a set of routes that you can use:
- GET `/api/strapi-workflows` -> Get all workflows
- GET `/api/strapi-workflows/:workflow_id` -> Get one workflow
- GET `/api/strapi-workflows/:workflow_id/stages/:id` -> Get a specific stage 
- PUT `/api/strapi-workflows/:workflow_id/stages` -> Replace all stages for a specific workflow
```json
{
"data": [ { "id": 3, "name": "todo" } ]
}
```
- PUT `/api/strapi-workflows/:workflow_id/stages/:id` -> Update a specific stage
```json
{
"data":  { "name": "review" }
}
```
- POST `/api/strapi-workflows/:workflow_id/stages` -> Create a new stage …
> feat(review-workflow): content api

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
Updates the css property 'alignItems' of auth logo container on register page to 'center'.
The auth logo on the register page was being stretched due to incorrect css. This stretched the logo which looked unpleasant. 
Navigate to the url: <strapi url>/admin/auth/register
Previous:
Now:
Fixes #16624
> fix: change alignment from stretch to center

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/ReviewWorkflowsStageEE.js
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/tests/ReviewWorkflowsStage.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/OptionColor/OptionColor.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/components/SingleValueColor/SingleValueColor.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/colors.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/tests/colors.test.js
Adds a border to stage color badges.
|-|-|
| <img width="1001" alt="Screenshot 2023-05-04 at 14 56 00" src="https://user-images.githubusercontent.com/2244375/236211045-c7d12eac-bc77-41fc-930b-7df7329f5de3.png"> | <img width="1001" alt="Screenshot 2023-05-04 at 14 55 47" src="https://user-images.githubusercontent.com/2244375/236211051-bc312eff-4766-40af-888e-d2b59f3b0aca.png"> |
Design requirement. Came up during QA.
> Fix: Add border to stage color badges

- packages/core/helper-plugin/src/components/DynamicTable/index.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/PaginationFooter/Pagination.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.js.snap
Replaces a styled overwrite for the DynamicTable component in the helper-plugin.
- the same CSS can be described using `gap`
- `pullRight` does not exist (anymore)
> Chore: Remove unnecessary styled overwrites

- packages/plugins/documentation/admin/src/pages/PluginPage/index.js
- packages/plugins/documentation/admin/src/pages/utils/useReactQuery.js
- Passes the current version when click open documentation
- Currently it's broken
Go to the documentation plugin, click open documentation. It should open the current version set in the config. For examples/getstarted that's 1.0.0
closes #16617
> Fix broken open documentation link

- packages/core/strapi/package.json
- yarn.lock
The `koa-helmet` 7.0.1v has the `helmet` 6.0.0v, and its `helmet.expectCt` is no longer set by default.
- `koa-helmet` 7.0.1: https://github.com/venables/koa-helmet/releases/tag/v7.0.1
- `helmet` 6.0.0: https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#600---2022-08-26
<br class="Apple-interchange-newline">
The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018. (source: https://pagespeed.web.dev/)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT
```
Deprecated: This feature is no longer recommended. 
Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or …
```
> [fix] remove Expect-CT response header

- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/database/package.json
- yarn.lock
* changes the check for `origin` to see if it'll be a `string`
* turns out it can be `string | null | undefined` – I wasn't prepared for `null`
* With an Editor user
* Create a new entity
* It should save and not attempt to `clone`
* resolves CONTENT-1384
> `origin` will be type `string` if present

- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/helper-plugin/src/components/DynamicTable/TableHead/index.js
Fixes sorting by `xToOne` relations in the CM list-view by using the full main field schema configuration instead of a string.
In https://github.com/strapi/strapi/pull/16548 I had introduced sorting by review-stage, which is a relation under the hood. I had assumed that would not affect other relations, but it turns out that `xToOne` relations are already setting the main-field. Instead of using a plain string they are using the full schema part, which is an object. That broken filtering by `xToOne` relations.
Display every kitchen-sink field in the CM list-view and sort by them.
- Fixes https://github.com/strapi/strapi/issues/16661
> Fix: Fix toOne sorting in CM list-view

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/tests/EditView.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/tests/ListView.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/utils/customRoutes.js
Changes the default review-workflow settings page to display the list-view and splits list-view and edit-view into separate views.
| List view | Edit view |
|-|-|
| <img width="1295" alt="Screenshot 2023-05-10 at 13 44 31" src="https://github.com/strapi/strapi/assets/2244375/292daea5-740a-4010-ab07-a5b9a82692ef"> | <img width="1295" alt="Screenshot 2023-05-10 at 13 44 36" src="https://github.com/strapi/strapi/assets/2244375/a88fc795-9ab7-423b-8f55-9db2cb0108a7"> |
First step to display multiple workflows in the FE.
> Settings: Split review workflows into list and edit-view

- packages/core/strapi/lib/services/metrics/admin-user-hash.js
Ensure the admin user's email is defined when trying to create an anonymous hash from it (telemetry)
If the email field has been manually disabled, it will cause the application to crash whenever it tries to create a hash
- Disable the admin email attribute
- Try to authenticated requests to the admin API
- The server shouldn't crash
fix #16699
> Make sure the admin user email is defined before trying to use it

- .github/workflows/tests.yml
- examples/getstarted/package.json
- yarn.lock
As per discovery on CI time, see https://github.com/strapi/strapi/pull/16638#issuecomment-1544412101
I'd like to propose to remove the @vscode/sqlite from the getting-started example. @vscode/sqlite looks to be a compatible fork of sqlite3 (node-sqlite) which is already supported by strapi and won't be touched in this pr. Diff 
https://github.com/TryGhost/node-sqlite3/compare/master...microsoft:vscode-node-sqlite3:release/vscode
The context
- the getting started install by default 3 drivers for sqlite (better-sqlite, sqlite3 and  @vscode/sqlite).
- @vscode/sqlite is a slightly modified fork of sqlite3. They should be compatible. 
- strapi prioritize the better-sqlite3 if present https://github.com/strapi/strapi/blob/main/packages/core/database/lib/connection.js#L38. Then @vscode/sqlite. …
> Remove @vscode/sqlite3 from example and CI matrix

- packages/core/strapi/lib/Strapi.js
Since v4.4 (or v4.5) the environment property in the tracking system is no more tracked.
With this pull request, I'm reintroducing it on the `didStartServer` event of the tracking system.
Data per environment.
- edit in `/packages/core/strapi/lib/services/metrics/sender.js` the `ANALYTICS_URI` constant with`'http://localhost`
- in another terminal run `npx http-echo-server 80`
- start the getstarted example or any example
- check the didStartServer event logged with the environment property matching the current environment
> Reintroduce the environment property in the tracking system

- api-tests/core/admin/admin-permission.test.api.js
- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/config/admin-actions.js
- packages/core/admin/ee/server/controllers/workflows/index.js
- packages/core/admin/ee/server/routes/review-workflows.js
- packages/core/admin/ee/server/services/__tests__/review-workflows.test.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/services/review-workflows/workflows.js
- packages/core/admin/ee/server/validation/review-workflows.js
Admin workflow create route, it also allows to create and populate stages.
POST `/admin/strapi-workflows/workflows?populate=stages` 
Example body:
```js
{
name: "Workflow Name", 
stages: [
{ name: "Stage1", color: ... }
]
}
```
Some comments:
- Workflows is now responsible of the lifecycles of stages. Meaning, the workflow service is the one responsible to create, update and delete stages (similar as how we deal components)
- replaceWorkflowStages should be deleted when this multiple workflows iteration is working.
So we can create workflows.
> feature(rw): create workflow

- api-tests/core/admin/admin-permission.test.api.js
- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/config/admin-actions.js
- packages/core/admin/ee/server/controllers/workflows/index.js
- packages/core/admin/ee/server/controllers/workflows/stages/index.js
- packages/core/admin/ee/server/routes/review-workflows.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/services/review-workflows/workflows.js
- packages/core/admin/ee/server/validation/review-workflows.js
Admin workflow update route, it also allows to create/update/delete and populate stages.
PUT `/admin/strapi-workflows/workflows/:id?populate=stages` 
Example body:
```js
{
name: "Workflow Name", 
stages: [
{ name: "Stage1", color: ... }
]
}
```
Some comments:
- Removed old replace stages route PUT `/review-workflows/workflows/:workflow_id/stage` (it will not be necessary anymore), so currently the Settings page update is broken.
So we can update workflows.
> feature(rw): update workflow

- packages/core/strapi/lib/core-api/controller/index.d.ts
- packages/core/strapi/lib/core-api/service/index.d.ts
- packages/core/strapi/lib/types/factories.d.ts
It merges the default types for a collection type controller and the new created methods for it. 
To have more flexibility on the factory types
- Go to a content type controller and write: 
```
export default factories.createCoreController('api::toy.toy', ({ strapi }) => ({
// here you should have autocompletion for all the collection methods: find, findOne, update,delete... and you can create 	 
//any other methods e.g
hello(){}
})).hello() // this should be allowed + find, update, delete or any other you declared on the config object;
```
- Go to a content type (single or collection, it should make the distinguish automatically and provide the types accordingly) service and do the same as with the controller
- Go to a content type routes directory, to the typescript file inside, then …
> Add more flexibility to factory types

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/index.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Login/index.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Providers/SSOProviders.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Providers/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/ListPage/ModalForm/utils/formDataModel.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/ListPage/ModalForm/utils/roleSettingsForm.js
- packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/serverRestartWatcher.js
- packages/plugins/documentation/admin/src/utils/openWithNewTab.js
- packages/plugins/users-permissions/admin/src/components/FormModal/Input/index.js
- packages/plugins/users-permissions/admin/src/components/FormModal/Input/tests/index.test.js
- packages/utils/eslint-config-custom/front.js
Adds a new eslint rule forbidding access to `strapi` as a global variable.
Right now the codebase contains a mix of `strapi` and `window.strapi`. Since the strapi global is also used by the backend and will be faded out, it has some ambiguity. Once we make it clear we mean `window.strapi` it becomes easier to grep for it and remove any ambiguity about what this variable refers to (e.g. the BE main class, FE main class, a global variable within a module ...).
Eslint will help you.
> Chore: Add eslint rule to forbid access to the strapi global

- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js
- packages/core/admin/admin/src/content-manager/components/FieldComponent/index.js
- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/DeleteLink/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/Header/index.js
- packages/core/admin/admin/src/content-manager/pages/EditViewLayoutManager/Permissions.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/package.json
- packages/core/admin/webpack.alias.js
- yarn.lock
* removes react-fast-compare and replace with `lodash/isEqual`
* reduce dependencies footprint inline with the v5 initiatives
> chore: remove react-fast-compare

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- Uses a nested multi select instead of a multi select for content-types
- Fixes PUT requests when editing a content type (send whole CT instead of ID and stages only)
> Settings: Use nested multiple select for content-types

- api-tests/core/upload/admin/folder-file.test.api.js
- packages/core/upload/server/services/folder.js
Delete folder logic was doing something like:
```js
await strapi.db.query(FILE_MODEL_UID).findMany({
where: { folderPath: { $startsWith: path } },
});
```
And we were missing an edge case. In a list of folder paths like:
```
/1
/2
/3
/10
```
If you want to delete `/1`, and you match by doing `{ $startsWith: "/1" }`, you would get `/1` but also `/10`.
This PR improves the query to prevent this behaviour.
Fixes https://github.com/strapi/strapi/issues/16734
> fix: Media library folders and files can get unintentionally deleted

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/getWorkflowValidationSchema.js
- packages/core/admin/ee/server/controllers/workflows/index.js
> Settings: Improve setting pages for multiple workflows

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Closes the confirmation modal after a workflow has been deleted.
Because otherwise the UX is not great.
> Settings: Close delete confirmation modal after deletion

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Displays `info.displayName` instead of the plain content-type uid in the settings list-view.
Better ux.
> Settings: Display content-type display names over uids

- packages/core/content-type-builder/admin/src/components/FormModal/forms/index.js
I fixed a wrong check that we had in the Edit of a Collection Type, there was a problem with the validation of the plural name based on the collection names array
Because we have the same check in Create and Edit and in edit you can't save an update of the Collection
Go to a collection Type in the CTB and try to Edit for example the name of the collection type, you can't save
> fix collection names check for plural names in edit

- docs/docs/docs/01-core/helper-plugin/hooks/use-callback-ref.mdx
- docs/docs/docs/01-core/helper-plugin/hooks/use-clipboard.mdx
- packages/admin-test-utils/src/environment.ts
- packages/core/admin/admin/src/pages/MarketplacePage/components/NpmPackageCard/InstallPluginButton.js
- packages/core/admin/admin/src/pages/SettingsPage/components/Tokens/TokenBox/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/components/MagicLink/MagicLinkWrapper.js
- packages/core/admin/package.json
- packages/core/admin/webpack.alias.js
- packages/core/helper-plugin/src/hooks/tests/useClipboard.test.js
- packages/core/helper-plugin/src/hooks/useClipboard.js
- packages/core/helper-plugin/src/index.js
- packages/core/upload/admin/src/components/CopyLinkButton/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/EditAssetDialog.test.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/index.test.js
- packages/core/upload/package.json
- packages/plugins/documentation/package.json
- yarn.lock
* Adds `useClipboard` hook utilising `navigator.clipboard` which is supported in all the browsers we support
* Removes `react-copy-to-clipboard` as a dependency – no need for it
* Automated testing 🪄
> feat: introduce useClipboard hook to remove dependency

- packages/generators/app/src/resources/templates/database-templates/js/database.template
- packages/generators/app/src/resources/templates/database-templates/ts/database.template
Fix the location where sql database file gets created.
Since the current defualt is wrong.
Remove DATABASE_FILENAME from env and see that it now defaults to `.tmp/data.db` instad of `data.db`
fixes https://github.com/strapi/strapi/issues/16774
> fix template data.db location

- docs/docs/docs/01-core/content-manager/hooks/use-content-types.mdx
- jest-preset.front.js
- packages/core/admin/admin/src/hooks/useContentTypes/__mocks__/index.js
- packages/core/admin/admin/src/hooks/useContentTypes/tests/index.test.js
- packages/core/admin/admin/src/hooks/useContentTypes/useContentTypes.js
- packages/core/admin/admin/src/pages/HomePage/index.js
- packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
- Adds docs use `useContentTypes()`
- Adds an auto-mock for `useContentTypes()`
Better tests, more docs.
> Chore: Add docs and auto-mock for useContentTypes()

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
Instead of loading all workflows, with this PR only the one workflow mapped to the current content-type will be loaded (through the `filters` URL param).
Because every content-type can only have one workflow mapped.
Can not yet be tested, because the filtering is not implemented. Implementation follow the contract in https://strapi-inc.atlassian.net/browse/CONTENT-1378
> CM: Load workflow mapped to the current content-type

- package.json
- yarn.lock
Removes `typedoc` from devDependencies
Because it's not used by anything anywhere in Strapi. If a dev wants to use it they should use `npx typedoc`
@pwizla @Convly Can you confirm that we don't use this for any documentation generation? If we do, can we add a note to the dev docs about why and how and then I'll close this?
n/a
Closes https://github.com/strapi/strapi/pull/16658
> Remove typedoc dev dependency

- packages/core/admin/admin/src/translations/en.json
- packages/core/helper-plugin/src/features/Notifications.js
Replace a static string with a proper translation for the `Notification` component.
Makes the close label translateable.
> Chore: Notification - Add missing translation

- packages/generators/app/src/index.ts
Initializes sentry when generating an app and not in runtime.
> fix: init sentry only when generating an app

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/AssigneeSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/index.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/tests/AssigneeSelect.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/StageSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/index.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/tests/StageSelect.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/constants.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
Renders a new select for admin users. It will be disabled if the admin users can not be fetched.
It also splits up the `InformationboxEE` component into smaller chunks that are easier to test.
Implements the bulk of the work needed to assign admin users to entities in the CM edit view.
I will add tests once the API is ready and we know this is how everything is going to work.
> Enhancement: Allow admin users to be assigned to an entity in the CM edit view

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/index.js
Fixes refetching admin users, after a new invite has been sent. The method is now called `refetch`.
Describe the issue you are solving. I haven't added a milestone because it doesn't have to show up in the release notes.
1. Invite a new user /admin/settings/users
2. See no error
Broke in https://github.com/strapi/strapi/pull/16816
> Fix: Fix refetching users

- api-tests/core/admin/ee/review-workflows-content-types.test.api.js
- api-tests/core/content-manager/search.test.api.js
- packages/core/admin/ee/server/services/__tests__/review-workflows.test.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/utils/review-workflows.js
- packages/core/admin/ee/server/validation/review-workflows.js
Before injecting the new review workflow attribute inside any content-type, the length of the future join table will be calculated and it should not exceed 63 characters.
PostgreSQL doesn't handle tables with names longer than 63 characters
Create a content-type with >30 characters name and see a warning inside the console at the initialisation of the Strapi instance.
The review workflow will not be possible to use on this one.
> feat(review workflow): Prevent too long table name for rw join table attributes

- packages/core/admin/ee/server/constants/default-stages.json
When upgrading strapi to a version with RW we generate, some default stages. They all had "blue" color, which imo could be better if the default ones had colors.
<table>
<tr>
<td>Before
<td>After
<tr>
<td> <img src=https://github.com/strapi/strapi/assets/20578351/f11304b6-d1f1-4761-9fa2-3476cf3a6d31/>
<td> <img src=https://github.com/strapi/strapi/assets/20578351/2019de27-1108-4903-aa4d-158e3893e547/>
</table>
> feat(rw): Colors to the default stages

- packages/core/strapi/lib/types/core/attributes/dynamic-zone.d.ts
- Use component uid instead of content-type uid for the generic inference.
- `Attribute.DynamicZone` are using a `uid[]` generic to customize which component it can hold, but the current type is referring to content-types uid instead of components.
```ts
import type { Attribute } from '@strapi/strapi';
type DZ = Attribute.DynamicZone<['default.c1', 'default.c2', 'default.c3']>;
declare const val: Attribute.GetValue<DZ>;
val.filter(comp => comp.__component === 'default.c1');
```
> [TS] Fix GetDynamicAttributeValue type

- docs/docs/docs/01-core/content-manager/02-review-workflows.mdx
- packages/core/admin/ee/admin/content-manager/components/DynamicTable/CellContent/ReviewWorkflowsStage/getTableColumn.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/server/constants/workflows.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/review-workflows/__tests__/entity-service-decorator.test.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/strapi/lib/commands/utils/data-transfer.js
It replaces all `strapi_reviewWorkflows_stage` names with `strapi_stage` as the Content Platform squad decided.
Reduce the impact of a too long database table name that can happen when the name of the table is longer than 63 characters. We are, for now, computing the database table name by concatenating the content type name + attribute name + _links for the join tables, so it can happen very often with an attribute as long as `strapi_reviewWorkflows_stage`.
Run your strapi project with EE and assign a workflow to a content-type, then you will be able to retrieve any entity with a stage assigned stored in `strapi_stage` field.
⚠️ For previous users of the Review Workflow feature, all stage assignments will be lost. Another PR is coming to propose a script to migrate the data from the old …
> refactor(review-workflow): shorten the stage attribute name on entities

- packages/core/database/lib/index.d.ts
- packages/core/strapi/lib/services/entity-service/index.d.ts
`strapi.db.query(uid).createMany()` returns:
https://github.com/strapi/strapi/blob/e3bb9a99942a8373355fdf88259ebddfa28a2108/packages/core/database/lib/entity-manager/index.js#L273-L276
But our current types were defined as if it only returned the count.
https://github.com/strapi/strapi/blob/e3bb9a99942a8373355fdf88259ebddfa28a2108/packages/core/database/lib/index.d.ts#L122
This PRs updates those types.
Fixes #16877
> fix: ids in query.createMany return type

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Extends the review-workflows list-view by a table footer that allows adding new workflows.
I missed this obvious piece, when checking figma.
> Chore: Extend review-workflow list-view by a table footer

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/constants/workflows.js
- packages/core/admin/ee/server/controllers/index.js
- packages/core/admin/ee/server/controllers/workflows/assignees/index.js
- packages/core/admin/ee/server/routes/review-workflows.js
- packages/core/admin/ee/server/services/__tests__/review-workflows.test.js
- packages/core/admin/ee/server/services/index.js
- packages/core/admin/ee/server/services/review-workflows/assignees.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/validation/review-workflows.js
https://github.com/strapi/strapi/assets/20578351/69447ff2-f40b-4873-970e-61620ce9801c
- Assign a user in a RW activated Content Type.
- Unassign a user in a RW activated Content Type.
- It sanitizes the assignee data so it does not filter sensitive data.
> Feature: Allow admin users to be assigned to entities

- api-tests/core/content-manager/api/relations.test.api.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/TableRows/index.js
- packages/core/content-manager/server/controllers/collection-types.js
- packages/core/content-manager/server/controllers/utils/clone.js
- packages/core/content-manager/server/routes/admin.js
Create new route to automatically clone entities. 
We were relying on the body payload before, if it was empty we agreed the intent was to auto clone, but that was not possible on i18n enabled Content Types, as the backend always injects a `locale` and a `localizations` fields.
### Related issues
* resolves CONTENT-1476
* resolves CONTENT-1453
> feat: mark uid as a prohibited field & separate auto-clone route

- packages/core/admin/ee/admin/pages/SettingsPage/pages/Webhooks/EditView/components/EventTable/EventTableEE.js
Re-enables the review workflow webhook events in the FE when in EE mode
Allows enabling of webhook events on stage change
> Add review workflow webhook events in FE

- packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/tests/index.test.js
* Passes every component schema to the context reducer instead of the ones listed for dynamic components
* You can have a component listed in the dynamic zone component choice that contains a component not in that former list leading to a crash.
* resolves #16966
> fix: dynamic zone component data

- packages/core/utils/lib/index.js
- packages/core/utils/lib/webhook.js
Recently, webhooks were refactored => (https://github.com/strapi/strapi/pull/16835). Now the list of emitable events are extendable from any package. 
Unfortunately we removed a package that was exposed through @strapi/utils/webhooks which was used in many other plugins.
This PR brings back that file, but also adds a log that warns the file will be removed and deprecated in the future. So anyone importing this file or using a package that imports it will have this warning error.
Fixes: https://github.com/strapi/strapi/issues/16955
> fix: Reintroduce webhook events utils

- packages/providers/upload-aws-s3/README.md
Default expiration time of signed s3 bucket files is 15 minutes, not 7 days.
> docs: Fix default expire time of private assets

- api-tests/core/admin/ee/review-workflows-content-types.test.api.js
- examples/getstarted/src/api/address/content-types/address/schema.json
- examples/getstarted/src/api/category/content-types/category/schema.json
- packages/core/admin/admin/src/content-manager/utils/mergeMetasWithSchema.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- packages/core/admin/ee/server/services/__tests__/workflows.test.js
- packages/core/admin/ee/server/services/review-workflows/workflows/__tests__/content-types.test.js
- packages/core/admin/ee/server/services/review-workflows/workflows/content-types.js
- packages/core/admin/ee/server/services/review-workflows/workflows/index.js
- packages/core/content-manager/server/controllers/validation/model-configuration.js
- packages/core/content-manager/server/services/__tests__/content-types.test.js
- packages/core/content-manager/server/services/configuration.js
This PR adds the possibility to inject any options in the content-manager configuration.
It also enables the review workflow feature to inject an options `options.reviewWorkflows = true;` in the configuration if a content-type is linked to any workflows, and false if it has been unlinked.
Also, it fixes a bug in the frontend where the content-types were overwriting the information coming from the configuration endpoint.
The front needs to have the information if the content-type has review workflows enabled or not prior to displaying the column for stage information in the list view and the edit view.
As Review Workflows is now activated on every content-type, we now have a null value in the stage attribute on every content-type that is not linked to a workflow. We do not want to show the …
> fix(review-workflows): display review workflows informations in content-manager when needed

- packages/core/admin/admin/src/pages/MarketplacePage/components/NpmPackageCard/PackageStats.js
- packages/core/admin/admin/src/pages/MarketplacePage/tests/__snapshots__/index.test.js.snap
Fixes a spacing issue on the Marketplace cards
It looks like this:
When it should look like this:
Go to the Marketplace page and take a look
> Fix lineHeight breaking card spacing

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/Modal/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/AuditLogs/ListView/tests/index.test.js
- packages/core/content-type-builder/admin/src/components/FormModalHeader/index.js
- packages/plugins/users-permissions/admin/src/components/FormModal/index.js
- packages/plugins/users-permissions/admin/src/pages/EmailTemplates/components/EmailForm.js
* Changes the use of `Breadcrumbs` to v2 component from the design-system
* We'll be deprecating and removing the v1 component
* Part of CONTENT-1484
> refactor: use version 2 of breadcrumbs in anticipation of deprecation

- packages/utils/eslint-config-custom/front.js
Cleanup eslint config and remove unused attributes.
Keep the setup small and close to what we need.
> Chore: Cleanup eslint/front configuration

- packages/core/strapi/lib/types/core/common/service.d.ts
- packages/core/strapi/lib/types/core/strapi/index.d.ts
Replace `unknown` with `any` for the `Common.Service` value type. This allows unsafe references to services' values.
This is a temporary fix while waiting for the next iteration of type generation (including services) that will remove this need.
**However this shouldn't be changed back (and shouldn't have been changed in the first place) until V5 as it's considered as a breaking change.**
The current vision for 4.11.1 and newer (and the TS System V1) was to force users to provide type safety through a generic parameter (e.g. from the `strapi.service` getter) or by casting the service property before using it.
It was also a change made anticipating the release of better type generation tooling that would remove those issues. 
**This obviously wasn't a good idea as it broke current users' …
> [TS] Allow unsafe calls for abstract services

- examples/getstarted/src/api/address/content-types/address/schema.json
- examples/getstarted/src/api/category/content-types/category/schema.json
- packages/core/admin/ee/server/content-types/workflow-stage/index.js
- packages/core/admin/ee/server/migrations/review-workflows-stage-attribute.js
- packages/core/admin/ee/server/register.js
Rename the tables of review workflow stages link to match the new attribute name.
Smooth migration for users already using Review Workflow 1.0, content-types should change the attribute name from `strapi_reviewWorkflows_stage` to `strapi_stage`.
- Use Strapi main version to enable review workflow on some content-types
- Change the stages of some entities
- Stop your Strapi project
- Switch to this branch
- Your content-types should still be working and the table name should have changed in your DB
> feat(review-workflows): migrate old to new stage attribute name

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/WebhookForm/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/WebhookForm/tests/index.test.js
Correctly disables the save button on the webhook edit view
@Marc-Roig spotted the bug here https://github.com/strapi/strapi/pull/16956#issuecomment-1596815498
So you are able to save a webhook when modified
Updated FE tests
> FIX - Detect is webhook form is dirty

- packages/core/content-manager/server/services/entity-manager.js
Passes the same arguments to the validator as the publish action so draft is false by default
This PR imitates the behavior of the EditView but there is maybe a bigger discussion to be had around how we should be handling the required validations for relations. 
To maintain a consistent publishing behavior between EditVIew and ListView.
I do not believe required relations are officially supported by Strapi. 
https://feedback.strapi.io/customization/p/specify-relation-column-as-required.
Read the issue below for instructions on how to test
#17022
> Maintain consistent backend validation for publish and bulk publish

- .github/actions/yarn-nm-install/action.yml
lints the github actions file
lint was giving a warning for it
it should still run exactly the same but now it should pass the linter
> Fix lint warning in the github yarn-nm-install file

- api-tests/core/content-manager/search.test.api.js
- packages/core/admin/ee/server/utils/review-workflows.js
- packages/core/content-type-builder/admin/src/components/FormModal/index.js
Remove the old way to create a content type with review workflow option set to false.
We want all the content-type to have review workflow enabled by default.
Create a new CT
Try assign it to a workflow
> fix(review-workflow): the feature shouldn't be deactivated on content type creation

- packages/core/strapi/lib/services/entity-service/types/params/fields.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/sort.d.ts
Adds the fields parameter for the entity service with all different notations: string, array.
Part of the entity-service params typings feature.
> [TS][Entity-Service] Add the fields param for the entity service

- packages/core/helper-plugin/src/components/DynamicTable/index.js
- Fixes the spacing of the bulk actions bar
- https://github.com/strapi/strapi/pull/17069 added bulk publish back after a bad rebase but I moved too quick and didn't notice there was extra padding now
Please QA against the designs for bulk publish v1
> Fix bulk publish padding

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ProtectedEditPage/index.js
Memoize permissions before handing them to useRBAC.
This is a quickfix to fix an infinite rendering loop on a edit role page. The problem here is really the useRBAC hook, but refactoring it will take a bit longer.
Validate `/admin/settings/roles/2` only renders once.
- Introduced in https://github.com/strapi/strapi/pull/17035
> Fix: Fix infinite rendering loop of role edit page

- packages/core/admin/ee/server/migrations/review-workflows-deleted-ct-in-workflows.js
- packages/core/admin/ee/server/register.js
- packages/core/admin/ee/server/services/review-workflows/workflows/index.js
- packages/core/admin/ee/server/utils/review-workflows.js
- packages/core/utils/lib/operators.js
If a content type is deleted, this code will check if it is part of any workflow and if so, delete the uid from the content-types array in the workflow.
Having a clean data and really remove all occurrence of all deleted content types
- Assign a content-type to any workflow
- Delete the content-type that have been assigned
- The workflow should be up to date without the deleted uid
> feat(review-workflows): remove deleted content-types in assigned workflows

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/Events/index.js
Fixes a linting error
It's invalid CSS and I can't commit because of the lint hook because of this line
Should still work fine and now `yarn lint` should work
> Fix linting error in CSS

- packages/plugins/documentation/admin/src/pages/SettingsPage/index.js
- packages/plugins/documentation/admin/src/pages/SettingsPage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/index.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/index.test.js
Fix the same bug as this [PR](https://github.com/strapi/strapi/pull/17102) for two more pages
- Settings > Documentation
- Settings > Advanced settings
As a bug fix. Please refer below screen recording after fix:
https://github.com/strapi/strapi/assets/40918526/65f216c1-6b12-4f05-9f3e-90bd9c87dd86
Please login to admin and navigate to these two sections `Settings > Documentation` & `Settings > Advanced settings`. Save button on top right going to be disabled by default.
No related issue for this PR.
> fix bug on Settings > Documentation & Advanced setting tab while saving

- api-tests/core/content-manager/api/basic-dp-compo.test.api.js
- packages/core/content-manager/server/controllers/collection-types.js
In the content-manager publish service we were validating the entry creation like:
https://github.com/strapi/strapi/blob/553217bd1cd9b63a2c144e1aee7543810a478fc1/packages/core/content-manager/server/services/entity-manager.js
This required all components and dynamic zones to be populated. But we broke that functionality https://github.com/strapi/strapi/pull/16814 not populating those relations. Those relations were not automaticallly populated and so "validateEntityCreation" always received empty components.
So required compos and dynamic zones work on publish.
Fixes https://github.com/strapi/strapi/issues/17071
> fix: Cannot save "required" dynamic-zone or component

- packages/core/content-manager/server/controllers/collection-types.js
We were not awaiting an async method and so it returned a 404 error when cloning entities without relations&unique fields in the content manager. 
API tests seems to not fail because of luck and even if the method was not awaited , the event loop executed it first.
So you can clone entities properly.
Clone a relation without relations or unique fields.
> fix: Clone entities Not Found Error

- docs/docs/docs/01-core/admin/01-ee/01-review-workflows.md
- docs/docs/docs/01-core/admin/02-permissions/02-frontend/fetching-permissions.mdx
- docs/docs/docs/01-core/admin/02-permissions/02-frontend/using-permissions.mdx
- docs/docs/docs/01-core/admin/03-settings/01-review-workflows.mdx
- docs/docs/docs/01-core/content-manager/02-review-workflows.mdx
- docs/docs/docs/01-core/content-manager/hooks/use-drag-and-drop.mdx
- docs/docs/docs/01-core/utils/async.md
Fixes broken links in contributor docs
Links should not be broken
in /docs, run `yarn build` and there should not be any broken link warnings
> Fix broken links in contributor docs

- packages/providers/upload-aws-s3/README.md
- packages/providers/upload-aws-s3/src/__tests__/is-url-from-bucket.test.ts
- packages/providers/upload-aws-s3/src/__tests__/upload-aws-s3.test.ts
- packages/providers/upload-aws-s3/src/index.ts
- packages/providers/upload-aws-s3/src/utils.ts
From the [PR](https://github.com/strapi/strapi/issues/17144) conv we had with @travisdieckmann:
When setting the S3 Plugin ACL property to private and utilizing a CDN, the plugin generated a signed S3 URL instead of utilizing the CDN URL. This proved to be incorrect.
An example of why this is incorrect:
CloudFront accesses the S3 object as an authenticated identity. This allows S3 objects to be private yet the CloudFront URL can be used to access the object in S3. Files should not be signed in this case.
There could be cases where a CDN needs signed files, in those cases, users should extend the s3 provider implementation and implement the signing with the appropiate libraries. As each CDN has a different package or methods to sign files.
So CDN URLs are not signed when ACL is set to …
> fix[S3-Provider]: Do not sign files if using baseURL

- packages/core/upload/admin/src/components/Breadcrumbs/CrumbSimpleMenuAsync.js
- packages/core/upload/admin/src/hooks/tests/useAssets.test.js
- packages/core/upload/admin/src/hooks/useAssets.js
- packages/core/upload/admin/src/pages/App/MediaLibrary/components/Header.js
- packages/core/upload/admin/src/pages/App/MediaLibrary/components/tests/__snapshots__/Header.test.js.snap
- packages/core/upload/admin/src/pages/App/MediaLibrary/index.js
- packages/core/upload/admin/src/utils/getBreadcrumbDataML.js
- packages/core/upload/admin/src/utils/getFolderURL.js
- packages/core/upload/admin/src/utils/tests/getFolderURL.test.js
* refactors the useAsset hook to fetch using `folderPath` instead of `folder`
* refactors getFolderURL to supply both `folder` and `folderPath`
* `folder` is just the id and is not indexed in the DB so using this can be a very slow query
* resolves #16710
> refactor: useAsset query to use folderPath

- packages/core/admin/admin/src/components/AuthenticatedApp/index.js
The change ensures that the content manager displays the loader until `admin-users-permission` data is fetched (among other APIs). As a result of this change, the content display logic kicks in only after the `admin-user-permissions` response is available.
This ensures that the 403 page isn't incorrectly displayed when reloading content-manager links (eg : `/dashboard/content-manager/collectionType/api::subscriber.subscriber/3`)
Currently, within `core/admin/admin/src/components/AuthenticatedApp/index.js`, we fetch data via API call `admin-users-permission` through `react-query`. We use `isFetched` and `isFetching` to know if this API data is fetched. But, the logic to determine if the loader should be displayed (pasted below) is incorrect. Note that `(isFetching && isFetched)` will …
> Fix : Content manager shows 403 (permissions error) on page reload

- packages/plugins/i18n/server/services/__tests__/entity-service-decorator.test.js
- packages/plugins/i18n/server/services/entity-service-decorator.js
transformParamsToQuery added back for local all so you an populate it correctly
to stop it from erroring if you have local all and populate
check if it errors when local all and populate are both pressent
fixes https://github.com/strapi/strapi/issues/17116
> add transformParamsToQuery back to fix error

- packages/core/utils/src/__tests__/convert-query-params.test.ts
- packages/core/utils/src/convert-query-params.ts
Fixes entity service `$between` operator which is currently broken when given Date objects for the between values
When the filters sanitization was added in a recent security fix, we had to reorder the isPlainObject check to after the Array check, but that meant that Date objects were filtered out when they came inside an array (which only happens with the $between operator)
GraphQL passes Date objects directly to the entity service so between stopped working.
without this PR:
- use entity service filters with `$between: [new Date(), new Date()]` and you will receive an error because they are filtered out and we attempt to do a between query with an empty array
with this PR:
- use entity service filters with `$between: [new Date(), new Date()]` and it should now work
Unit tests have been …
> Fix entity-service filter $between operator to allow Date objects

- api-tests/plugins/graphql/crud.test.api.js
- packages/plugins/graphql/server/services/internals/types/response-collection-meta.js
Fixes the GraphQL pagination query sanitization, which was previously sanitizing against a content type of `undefined` instead of the actual content type.
GraphQL pagination counts are wrong
GraphQL pagination should report the correct count for a query
An API pagination test has been provided that fails on the previous code and passes with the changes in this PR.
Based on branch (and pending acceptance of) https://github.com/strapi/strapi/pull/17139
Fixes #16170
> Fix GraphQL pagination results

- .github/dependabot.yml
Groups a few dependencies together for dependabot, which need to be updated in parallel.
It will reduce the amount of open PRs and reduce a manual labor step e.g. for jest or babel dependencies.
More: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
> Chore: Group dependabot updates

- packages/core/admin/admin/src/pages/SettingsPage/components/Tokens/TokenBox/index.js
It fixes the bug #17187 .
For copying the API token there is a function in the location [packages/core/admin/admin/src/pages/SettingsPage/components/Tokens/TokenBox/index.js](https://github.com/strapi/strapi/blob/670f4a65e1a27e0235200bfca9df54d6dda91161/packages/core/admin/admin/src/pages/SettingsPage/components/Tokens/TokenBox/index.js#L20)
```js
trackUsage.current.('didCopyTokenKey', {
tokenType,
});
```
but trackUsage is a function and doesn't have 'current' property instead of this the implmentation should be
```js
trackUsage.('didCopyTokenKey', {
tokenType,
});
```
> Fix bug #17187: updated the handleClick function

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/controllers/workflows/index.js
- packages/core/admin/ee/server/controllers/workflows/stages/index.js
Returns count of workflows in `/review-workflows/workflows/:id` inside meta
the format of the response will now be:
```ts
interface findById {
data: Workflow
meta: { workflowCount: number }
}
```
So frontend knows the number of workflows in the workflow edit view.
> feat (Review Workflow): Return meta in workflow findById

- docs/docs/docs/01-core/admin/01-ee/02-hooks/use-license-limits.mdx
- packages/core/admin/ee/admin/hooks/useLicenseLimits/tests/index.test.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/useLicenseLimits.js
> **Note**
> Tests are failing because of the base branch and will be fixed there. This PR is ready to review.
Returns a new method called `getFeature(name: string)` from the useLicenseLimit hook. This method allows accessing the options object for each feature.
The data-structure for a license looks like:
```js
{
data: {
features: [
{ name: 'sso' },
{ name: 'review-workflows', options: { something: true } }
]
}
}
```
To avoid having to filter the `features` array in many different ways in different places, I think it makes sense to add this convenience method.
It always returns an object, to avoid having to have bullish checks every time an option is being accessed.
In https://github.com/strapi/strapi/pull/17101 I had introduced a new hook `useReviewWorkflowLicenseLimits()`, but I think …
> Enhancement: Add a getFeature convenience method to the useLicenseLimit hook

- packages/core/database/lib/fields/shared/parsers.js
If the provided value is a date, it formats it to yyyy-MM-dd
To fix the filtering in the entity service when passing a date object
Create a content type with a date value and customize the controller to filter the response by the date filter using date objects:
```
module.exports = createCoreController('api::temp.temp', ({ strapi }) => ({
async find(ctx) {
const entries = await strapi.entityService.findMany('api::temp.temp', {
filters: {
from: { $between: [new Date('2023-07-04T07:00:29.492Z'), new Date('2024')] }, 
},
});
return entries;
},
}));
```
> Fix date parser

- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/ModalForm.js
- packages/core/content-manager/server/controllers/validation/model-configuration.js
- packages/core/helper-plugin/src/components/GenericInput/index.js
* Removes the ability to set step with time fields in admin UI
* Removes checking for metadata.step because it was only used for time, instead we set defaults based on attribute.type
* Removes step check from metadatas schema
* Since we released the ability to type a time in the TimePicker theres no need for a step & performance degrades when there are 1000s of items in the dropdown
* resolves CONTENT-1530
> chore: remove step from time configure view modal

- packages/core/strapi/lib/types/core/strapi/index.d.ts
It adds an `any` type for `strapi.admin`.
Because right now I am unable to use `strapi.admin` in a typescript file.
1. Pull PR
2. Install it in a project
3. Use `strapi.admin.*` in a typescript file.
This should now only give a warning instead of an error.
None that I know of.
> feat: Add an any type for strapi.admin

- api-tests/core/admin/ee/review-workflows-content-types.test.api.js
- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/constants/workflows.js
- packages/core/admin/ee/server/register.js
- packages/core/admin/ee/server/services/__tests__/review-workflows-validation.test.js
- packages/core/admin/ee/server/services/__tests__/review-workflows.test.js
- packages/core/admin/ee/server/services/__tests__/stages.test.js
- packages/core/admin/ee/server/services/__tests__/workflows.test.js
- packages/core/admin/ee/server/services/index.js
- packages/core/admin/ee/server/services/review-workflows/review-workflows.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
- packages/core/admin/ee/server/services/review-workflows/validation.js
- packages/core/admin/ee/server/services/review-workflows/workflows/__tests__/content-types.test.js
- packages/core/admin/ee/server/services/review-workflows/workflows/content-types.js
- packages/core/admin/ee/server/services/review-workflows/workflows/index.js
- packages/core/admin/ee/server/utils/review-workflows.js
- packages/core/strapi/ee/license.js
Adding EE licenses limits options to multiple workflows.
Depending on the plan, the number of available workflows and a number of stages per workflow can be restricted.
Also adding a hard limit to mitigate potential issues (e.g. infinite loop on workflow creation)
As Review Workflows is an EE feature, we need to be able to limit how users can use the feature on Cloud plans.
Self-hosted EE is not impacted by those limitations.
- Create workflows and try to bypass the limit of workflows available for your license.
- Create stages on a workflow and try to bypass the limit of stagesPerWorkflow available for your license.
> feat(review-workflows): apply license restrictions

- packages/core/admin/admin/src/content-manager/pages/ListView/components/TableRows/index.js
- packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/ReviewWorkflowsStageEE.js
Applies the default stage color to the review workflow cm list-view badge.
Simplifies the setup in the cm list-view table.
> Chore: Apply default color to ReviewWorkflowsColumn

- packages/core/admin/ee/server/controllers/workflows/index.js
In case we add pagination in the future, we are adding the workflow count inside the meta attribute into the `http://localhost:1337/admin/review-workflows/workflows`, to keep it consistent with the workflows find by id.
Response body:
```
interface Find {
data: Workflow[]
meta: {
workflowCount: number
},
}
```
> feat(rw): return workflow count in find workflow

- packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/index.test.ts
- packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
It deletes 'merge' as a valid strategy and removes its presence in the tests, since we are not supporting it at the moment.
To avoid misleading the users and because it wasn't allowed in other parts of the code base, causing syntax errors in the tests.
Check that all tests pass and there aren't any merge mentions in the data transfer package nor in the commands
> Delete merge presence in data transfer strategies

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflowLicenseLimits.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Updates the license limit checks on the create, edit and list-views setting pages and CM edit view:
- use `meta.workflowCount` instead of `pagination.total`
Changes have been introduced in:
- https://github.com/strapi/strapi/pull/17222
- https://github.com/strapi/strapi/pull/17221
- https://github.com/strapi/strapi/pull/17123
> Chore: Update license limits in create, edit and list-views

- docs/docs/docs/01-core/admin/01-ee/02-hooks/_category_.json
- docs/docs/docs/01-core/admin/01-ee/02-hooks/use-license-limits.mdx
- packages/core/admin/ee/admin/hooks/useLicenseLimitNotification/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimitNotification/tests/index.test.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/tests/index.test.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/useLicenseLimits.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ApplicationInfosPage/components/AdminSeatInfo/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ApplicationInfosPage/components/AdminSeatInfo/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/ListPage/CreateAction/index.js
Simplifies the `useLicenseLimits()` hook
- by returning an object always we can simplify the destructuring
- by flattening the `license` object the consuming code becomes easier to read
- by returning `isLoading` components can handle that state
- by returning `isError` components can handle that state
> Chore: Refactor useLicenseLimits() hook

- .github/dependabot.yml
Extends the existing dependabot groups:
- new group for eslint related dependencies
- new group for redux related dependencies
- new groups for react-dnd related dependencies
- extended jest group to also match https://github.com/strapi/strapi/pull/17240
Less PRs and less manual labor, when updating dependencies.
Dependabot will do the job for us.
- https://github.com/strapi/strapi/pull/17184
> Chore: Improve and extend dependabot groups

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/tests/WorkflowAttributes.test.js
Wraps an element-exists check in `waitFor`.
Resolves a "... is not wrapped in act" error in jest.
> Fix: Improve test setup for workflow attributes

- packages/core/admin/admin/src/pages/ProfilePage/index.js
- packages/core/admin/admin/src/pages/ProfilePage/tests/index.test.js
* sets the enabled flag on the query for `isSSOLocked` to be true if the product is EE & sso is enabled as a feature
* sets a fallback for `dataSSO?.isSSOLocked` to `false` which is the default
* long wait times if the feature isn't enabled
* resolves #17216
NGL i still find it weird that it hangs for so long considering we have middleware on the BE to check if the feature is enabled, but tbf we shouldn't fire this query if its not!
> fix: only run the query if sso is enabled

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Updates the license limits checks:
- chargebee returns strings always, so until we've fixed the underlying problem we should parse the limits to be integers (follow up Jira task)
- fix some conditionals after real world testing
- `CreateView`: all good - on submit we can display the modal again already if the user is at limit, because the intent is to create a new workflow, which would then exceed the limit.
- `EditView`: changed the onload condition from `>=` to `>`, because otherwise a user sees the modal every time, even if they are within limits. They already see it on the list-view, which is annoying enough. Added onsubmit conditions, which trigger the modal.
> Fix: Fix license limits for workflow settings pages

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Implement tracking events for multiple workflows:
- `willCreateWorkflow` for create workflow actions
- Move `didViewWorkflow` from edit to list-view
> **Note**
> Needs to be merged after https://github.com/strapi/strapi/pull/17244
To understand the usage of the feature.
> Chore: Implement multiple workflow tracking events 

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/server/constants/default-stages.json
- Update default stage color for "In progress" to be a valid theme color
- Make FE code for the retrieval of the theme color name more defensive. The function `getStageColorByHex` can return null and previously, this has let to a destructuring of `themeColorName` from `null` which leads to 💥 
Fixes a bug.
@pwizla found a bug using multiple review workflows, which I could replicate using a fresh instance.
> Fix: Make stage theme color retrieval more defensive

- packages/core/admin/ee/admin/pages/SettingsPage/pages/Users/ListPage/index.js
Uses a named export for the user settings page
The `useEnterprise` call was not expecting a default export and therefore the users list page was blank
> fix(ee): use named export for user settings page

- examples/getstarted/src/extensions/myplugin/content-types/test/schema.json
- packages/plugins/i18n/server/services/core-api.js
Fixes #10120
Allow plugin content-types to use i18N
> Do not try to add API endpoint for content type plugins using i18N

- packages/core/admin/admin/src/content-manager/pages/ListView/components/TableRows/index.js
An enhancement based on the ongoing work in the target branch
Uses the `getDisplayName` util to display the users full name in the CM list view
> feature(content-manager): display full user names in list view

- packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
* Changes the publish / unpublish & delete network calls to use the `params` object built by `buildValidGetParams` as opposed to the querystring from the URL
A small regression in #17074 meant we were sending the query `{ plugins: { i18n: { locale: 'es' } } }` when in actuality we just wanted to send `{ locale: 'es' }`, this meant publish / unpublish & delete would not work.
* resolves #17314
* resolves CONTENT-1591
> fix(i18n): entity locale actions were aimed at default locale

- packages/core/admin/admin/src/content-manager/components/RelationInput/components/Option.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js
Stringify `mainField ?? id` before using because `ComboboxOption` is expecting `string` in `textValue` prop.
Users were unable to add content for tables who have relations with tables containing only numbers or relations
Create a table Table 1 with only `Number` or `Relations` fields.
Add some content in Table 1.
Create an other table Table 2 and add relation of `Table 1` in it.
Now add content in Table 2. Notice when you select `Table 1` dropdown it will give error.
* resolves #17260
* closes #17315
> Fix error on adding relations

- packages/core/admin/admin/src/content-manager/pages/ListView/components/TableRows/index.js
Adds the cellFormatter back since we removed in favor of composition.
Even if internally in the content-manager we are moving away from this API we still need to support the cellFormatter since plugins like i18n use it: 
https://github.com/strapi/strapi/blob/489927e8e161dd5c3d48f0c97ab4efade802c3e3/packages/plugins/i18n/admin/src/index.js#L52
Go to any content-type in the content manager that has i18n enabled. You should have the following column.
> Add cellFormatter support

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/server/constants/workflows.js
- packages/core/admin/ee/server/services/__tests__/review-workflows-validation.test.js
- packages/core/admin/ee/server/services/review-workflows/validation.js
- packages/core/admin/ee/server/validation/review-workflows.js
- packages/core/utils/src/validators.ts
Throws an error if a workflow stage names are duplicated.
> feat: throw ValidationError if stage has a duplicated name

- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/populate.d.ts
- Add string and array notation types 
- add populate as a possible param
- To complete entity service typings
> String and Array notation types for entity service populate Param

- packages/providers/upload-cloudinary/src/index.ts
@Marc-Roig turns out that your [suggestion](https://github.com/strapi/strapi/pull/16621#discussion_r1185726369)
> What do you think if , based on the file.size available here, we use one or another. 
actually does yield significant performance improvements! .)
See the commit message for details.
> Chunk Cloudinary uploads only for large files

- docs/docs/docs/01-core/admin/01-ee/02-hooks/use-license-limits.mdx
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/hooks/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimitNotification/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimitNotification/tests/index.test.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/__mocks__/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/index.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/tests/index.test.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/useLicenseLimits.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ApplicationInfosPage/components/AdminSeatInfo/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ApplicationInfosPage/components/AdminSeatInfo/tests/index.test.js
1. Make `useLicenseLimits` more atomic
Previously it was coupled with user permissions, which doesn't work well for e.g. review-workflows because it assumes a user needs access to other admin users.
The affected code was extracted and inlined into `ApplicationInfo`.
2. Allow to programmatically enabled/ disable license checks
Now `useLicenseLimits` can receive options, which (similar to react-query) allows to pass in an `enabled: boolean` flag. This is helpful to not run a query e.g. if a previous RBAC check did not succeed.
3. Add a manual mock for `useLicenseLimits`
Makes testing easier.
4. Export `useLicenseLimits` as a named export.
Application infos can be tested in CE and EE here: http://localhost:4000/admin/settings/application-infos
> Chore: Split user RBAC permissions from useLicenseLimits hook

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/tests/WorkflowAttributes.test.js
Removes either `Single Types` or `Collection Types` from the workflow attributes, when one of the groups does not contain items.
1. The group renders as `selected` if it doesn't contain items, which is debatable.
2. It leads to a weird looking UI state, when the user starts with a fresh project, because it does not have a any single-types. It is not possible to run Strapi without neither of them, so that case does not need covering.
> Fix: Remove content-type groups from workflow attrs conditionally

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
Sets the default value of admin lastname as undefined instead of empty string
Fix #17287 
Run the example project, register an admin with empty last name, and validate that the lastname is retrieved at the endpoint /admin/me as null
Fix #17287
> admin lastname defaults to undefined

- packages/core/helper-plugin/src/hooks/useAPIErrorHandler/utils/formatAPIError/index.js
- packages/core/helper-plugin/src/hooks/useAPIErrorHandler/utils/formatAPIError/tests/index.test.js
- packages/core/helper-plugin/src/hooks/useAPIErrorHandler/utils/normalizeAPIError/index.js
- packages/core/helper-plugin/src/hooks/useAPIErrorHandler/utils/normalizeAPIError/tests/index.test.js
Gives precedence to `error.message` over concatenating `error.details`.
Concatenating error message from the `details` object should be a last resort. This became a problem for multiple review-workflows, because at least two stages can have a is-duplicated error message, which would then print the message several times.
This response:
```
{
data: {
error: {
name: "ValidationError",
message: "Main error message",
details: {
errors: [
{ /**/ }
]
}
}
}
}
```
should give precedence to `Main error message`, since it can be provided the admin API and is much better than concatenating.
Automated tests
- https://github.com/strapi/strapi/pull/17332
> Chore: Give precedence to error.message over error.details

- packages/core/database/lib/query/helpers/where.js
- packages/core/utils/src/operators.ts
Marks json superset of operator as experimental.
Note: this operator has not been yet released (comes from review workflow multiple workflows).
> chore: mark jsonSuperSetOf as experimental and for internal use

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
Fixes various UI bugs for review workflows that came up during QA:
- center the loader
- only display number of stages once they have been loaded
- render accordion in an error state if a subfield contains an error
- prevent an previously visited workflow from the edit view to show once the create view mounts
QA!
> Fix: Fixes various review-workflow UI bugs

- api-tests/core/admin/ee/provider-options.test.api.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/SingleSignOn/utils/schema.js
- packages/core/admin/ee/server/validation/authentication.js
Allows provider options defaultRole to be null if autoRegister is true
Currently, if you make a change on the provider form on a Strapi that has never set a defaultRole before (ie, try setting an sso locked role) and click save, there is a generic "error" toast message because defaultRole isn't allowed to be null.
- Start a new instance of EE Strapi that has not previously selected a default role in SSO settings
- Go to the SSO settings page and add an sso locked role to enable to "save" button
- Do not touch the default role; it should be empty
- auto-registration should be false
- click Save
- the sso locked role should be saved and defaultRole should remain empty
API tests for the backend request have also been included.
Branched from https://github.com/strapi/strapi/pull/17341 which …
> [SSO] Allow defaultRole to be null while autoRegister is false

- api-tests/core/admin/ee/review-workflows-content-types.test.api.js
- packages/core/admin/ee/server/services/review-workflows/workflows/__tests__/content-types.test.js
- packages/core/admin/ee/server/services/review-workflows/workflows/content-types.js
- packages/core/admin/ee/server/services/review-workflows/workflows/index.js
When you tried to assign multiple content types in a workflow, and those CT were previously assigned to another workflow, those Content Types were not removed  from the original workflow.
This resulted in users seeing the content types assigned in two different workflows.
This was a concurrency issue that was  handled by removing the concurrency of some operations. Ideally, I would like to introduce more json operators in the database queries so we can make this operations async again. 
As this operations are quite quick , this shouldn't impact performance that much, nevertheless I will do some perf checks.
> fix: Assigning multiple content types in a workflow

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Removes the delete button from the list-view if: 1) the user does not have permission 2) it is the last workflow.
This solves several issues:
- the disabled button doesn't receive any events and therefore clicking on the disabled button would take you to the edit-view (which is a problem of the `onRowClick` click helper)
- the disabled button looks more prominent than it should
Delete all but the last workflow or take away delete permissions from role.
> Fix: Remove delete button from the list-view instead of disabling it

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Removes the license limits overlay when a user is __at__ workflow limit and visits the workflow list view. Displays the license overlay when a user clicks "create" in the list-view and is at limit.
This creates less frictions for users using the feature and being perfectly within license limits.
> Fix: Remove limits overlay if a user is at limit

- api-tests/core/admin/ee/provider-options.test.api.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/SingleSignOn/index.js
- packages/core/admin/ee/server/validation/authentication.js
On the Single-Sign On settings page in the admin, allows defaultRole to be nullable when autoRegister is false
Currently if a user who does not use auto-register and hasn't selected a default role chooses SSO Locked Roles and clicks 'save' a generic error message appears because the back-end is expecting to receive a valid role ID for the default role (previously this couldn't happen because the form was unsaveable until we added sso locked roles)
This change allows the field to be nullable, but only when autoRegister is false.
On the SSO settings page, with a fresh database (or where defaultRole starts as null):
- do not touch auto register, it should be on false
- do not touch default role, it should be blank
- set an sso locked role
- click save
- the form should save correctly …
> [SSO] allow defaultRole to be nullable when autoRegister is false

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/tests/WorkflowAttributes.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/helper-plugin/src/components/ConfirmDialog/index.js
- packages/core/helper-plugin/src/components/ConfirmDialog/tests/index.test.js
- packages/core/helper-plugin/src/components/DynamicTable/index.js
- packages/core/helper-plugin/src/components/Table/index.js
- packages/core/helper-plugin/src/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/RemoveAssetDialog.test.js.snap
1. Adds a new prompt that is displayed if assigning a content-type to a workflow would 'steal' this content-type from another workflow
2. Display a notice about which workflows are already assigned in the content-types select
3. Combine the above prompt with the existing prompt of deleted server stages
4. Refactor the `ConfirmDialog` component to be more composable
This will make sure users understand the impact of selecting a specific content-type for a workflow.
1. Create 2 workflows
5. Assign an already assigned content-type to the other workflow: expect a prompt to be displayed when saving
6. Delete an already existing stage: expect a prompt to be displayed when saving, which contains two questions
- Alternative for https://github.com/strapi/strapi/pull/17392
- Closes …
> Enhancement: Show confirmation modal if a workflow would 'steal' a content-type

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/tests/WorkflowAttributes.test.js
Emphasizes the workflow name in the workflow attributes content-type select.
Differentiates the name visually from the other elements.
> Enhancement: Emphasize workflow name

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/index.js
Sets the page size to the length of the entries being fetched
Currently if you select multiple entries across pages in the ListView or you select more than 10 from a single page in the list view only 10 will show up in the modal, however all will be published.
We need to support selecting as many entries as the user wants across multiple pages.
This is a fix but the ideal solution would include some sort of paginated list in the validation modal as well. It's a bit more complex and will likely need to handle it in a follow up PR to fix this issue before the release
Go to a contentType where you have a lot of entries
Select more than 10 entries across several pages 
You should see all of your selected items in the validation modal
Publish, all the valid entries should publish
Go back to …
> [bulk publish] Set page size to the number of selected entries

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/index.js
- It deselects from the list view the entries that were successfully published
- To improve the user experience. A user should only have entries that were not published selected when returning to this list view. 
- Select a bunch of entries in the ListView
- In the modal deselect some and publish some
- The deselected entry should remain in the modal as deselected
- Return to the list view, the entries that were published should no longer be selected but the entries that were not publish should be selected
> [bulk publish] Deselect the entries that were published from the list view

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Updates the copy for the review workflows settings page.
Requested by design.
> Chore: Update review workflows copy

- packages/core/admin/ee/server/services/auth.js
Awaits for the promise returned by the `isSsoLocked` function.
Without `await`, the condition will always be true and an error will always be thrown when calling the `resetPassword` function.
Just try resetting your password with an EE edition, it should work fine now.
#17409
> Await for `isSsoLocked` promise, fix #17409

- api-tests/core/content-manager/api/relations-cross-entity-ordering.test.api.js
- api-tests/core/content-manager/api/relations.test.api.js
- packages/core/database/lib/entity-manager/regular-relations.js
When removing or adding a relation in an entity, other entities from the same Content Type were having that same relation reordered.
**Cause**: We were updating the order of the other entities when we should only be updating the inverse order.
**Context**: Given a bidirectional  relation between Author -> Article, the join table:
| author_id | article_id | article_order | author_order
- `article_order` is the order of articles in author entities
- `author_order` is the order of authors in article entities
We keep both orders because both sides of the relation. So when updating an author and adding article relations, we update both the `article_order` but also the `author_order` (the inverse side).
Before the SQL query to update the order values was:
```sql
UPDATE
:joinTable: as a,
( …
```
> fix: relations are not returned in the correct order

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/index.js
It fixes the problem we had inside the Confirm Publish All Modal when you try to select/deselect all the entries
Like you can see in this video
https://www.loom.com/share/47fb5ce7c2fd48988c6ece8ad939ac44 
Because inside the SelectedEntriesModal component we have a different response, with a entity property wrapping every entries selected and it was not in line with the definition of the rows inside the Table handleSelectAll handler https://github.com/strapi/strapi/blob/2aee20a2172832c866e397b68364bfc5fad2c535/packages/core/helper-plugin/src/components/Table/index.js#L156
Go to a Collection and select some entries in the content manager and click Publish, then inside the Modal try to select and deselect all the entries, the checkboxes need to work correctly now
CX-130
> Bulk Publish: fix Select All not working inside the Modal

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/ConfirmBulkActionDialog/index.js
It fixes the problem we had inside the Confirm Publish All Modal when you deselect all the entries, because every time we pick or unpick one entry the countManyEntriesDraftRelations was called
Because otherwise we call the API with no ids, which gives an error (also a Warning with the "Internal server error" in the CMS)
Go to a Collection and select some entries in the content manager and click Publish, then inside the Modal try to deselect all the entries, you don't have to see a Warning popup and you can check in the Network if the countManyEntriesDraftRelations will be called or not
Related issue(s)/PR(s)
CX-128
> Bulk publish: fix, enable countManyEntriesDraftRelations API only when you have selected entries in the modal

- packages/core/helper-plugin/src/components/Table/index.js
- remove the sorting icon from the Name column
- because we have the sorting icon that doesn't work and we don't want to sort the rows in the modal
- Select a bunch of entries in the ListView
- click Publish
- you can now see the bulk publish modal without sorting in the Name column
Bug related CS-124
> [bulk publish] Remove sorting from the bulk publish modal

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/ListView/ListView.js
Improves the alignment of design and implementation for RBAC on the settings pages:
- hide create button on the list-view instead of disabling
- hide drag button on a stage instead of disabling
- hide save button on the edit view instead of disabling
Align design and implementation.
> Fix: Better align review workflows design and implementation of RBAC

- packages/core/permissions/.eslintrc.js
Fix eslint config for the permission package 
the ts-color-picker change move the ts config to back/typescript but this PR was merge in between the changes.
yarn lint should work
> Migrate permission back eslint after color-picker changes. merge issues

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/EditFieldForm.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/Settings.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/SortDisplayedFields.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.js
- Use `Flex` over paddings
- Use named exports
Makes the DOM structure lighter and the component easier to extend.
> Chore: Cleanup configure the view styles

- packages/core/admin/package.json
- packages/core/data-transfer/package.json
- packages/core/database/package.json
- packages/core/strapi/package.json
- packages/generators/app/package.json
- yarn.lock
Upgrade `semver` from 7.5.2 to 7.5.4 due to https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
Fixing and audit warning, Strapi itself is not vulnerable to this issue
Run `yarn npm audit` and see that the audit warnings have disappeared
N/A
> Update semver to remove audit warnings

- packages/core/upload/admin/src/components/EditFolderDialog/EditFolderDialog.js
The commit fixes the issue of not being able to delete folders in the media library 
**Earlier Behaviour**
- Go to media library
- Create a folder
- Click on "pen" icon to edit then click "Delete folder"
- A modal will appear click "Confirm" on it
- You will see nothing happens
**Wanted behaviour**
- Folder gets deleted when clicking "Confirm"
Because we want to delete folders using the above steps.
> fixed: Media Library - Can`t delete empty folder #17263

- packages/core/upload/admin/src/components/AssetCard/AssetCard.js
- packages/core/upload/admin/src/components/AssetGridList/tests/__snapshots__/AssetGridList.test.js.snap
- Provides the `updatedAt` prop to ImageAssetCard
- This ensures that the FE gets the latest image when media is replaced using https://github.com/strapi/strapi/blob/0c20c6cea2c856b7725787549e1ba887d9a06afc/packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js#L11
Fixes https://github.com/strapi/strapi/issues/17283
> Update media thumbnails on replace

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
Reverts strapi/strapi#17319
Reopens https://github.com/strapi/strapi/issues/17287
This introduces a bug where new admin users can not be registered anymore.
> Revert 17319 fix/default admin lastname

- packages/core/admin/admin/src/components/AuthenticatedApp/index.js
- packages/core/admin/admin/src/components/NpsSurvey/index.js
- packages/core/admin/admin/src/components/NpsSurvey/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
This PR manages the logic to determine when the NPS survey should be shown. The acceptance rules are:
- Only enable the feature is the admin user subscribed to the newsletter when signing up
- If a user responds to the survey, we should not show it again before 90 days
- If a user does not respond to the survey for the first time, we should show it again 7 days later
- If a user does not respond to the survey for the second time, we should not show it again before 90 days
Still left to do, hence the draft PR:
edit by @markkaylor I believe the outstanding task is done ^
I would appreciate feedback on 2 aspects in particular that I'm not sure of:
- Where to load this component. Since it's app-wide and only for authenticated users, I currently have it in `AuthenticatedApp`.
- Whether the …
> NPS survey frontend logic

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/Settings.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.js
- packages/core/admin/ee/admin/content-manager/pages/ListSettingsView/constants.js
Add the review workflow stage column as default sort option in configure the view.
Will allow users to use the stage column with a default sorting.
- Needs https://github.com/strapi/strapi/pull/17438
- Needs https://github.com/strapi/strapi/pull/17440
- Needs https://github.com/strapi/strapi/pull/17205
- Needs https://github.com/strapi/strapi/pull/17444
> Feature: Allow review workflow stage column as default sort option

- packages/core/admin/ee/server/config/admin-actions.js
Review workflows settings page were showing in the incorrect order:
Before:
After:
> fix: reorder rw permissions so they appear as CRUD

- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/constants.js
- packages/core/admin/server/validation/authentication/register.js
Make `lastname` field required for registrations AND admin registrations.
> **Note**
> The registration components need a bigger refactoring as well as more tests. I'll track this in follow-up tickets.
The field is not required. The bug had been addressed in https://github.com/strapi/strapi/pull/17319, but new admin users with an empty lastname couldn't be registered any longer.
1. Delete .tmp .cache build
2. Run `yarn build && yarn develop`
3. Register an admin user with an empty lastname
This is an alternative to https://github.com/strapi/strapi/pull/17461 which reverts the previous PR.
Closes https://github.com/strapi/strapi/issues/17287
> Fix: Registration - Send null for lastname instead of empty string

- packages/core/data-transfer/src/strapi/remote/handlers/utils.ts
Adds more detail to the error when invalid Upgrade headers are sent
Some users have proxies modifying their headers (such as to prevent websocket connections) but we do not provide adequate error messaging for them to debug the problem.
Try to connect to the transfer websocket server without a 'websocket' Upgrade header and there is now a server log detailing the problem.
Relates to the `500` response in [this issue](https://github.com/strapi/strapi/issues/16296)
> [DTS] Add detail to ws upgrade error

- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/Settings.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/ee/admin/content-manager/pages/ListSettingsView/constants.js
- packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/ReviewWorkflowsAssigneeEE.js
- packages/core/admin/ee/admin/content-manager/pages/ListView/ReviewWorkflowsColumn/tests/ReviewWorkflowsAssignee.test.js
Replaces RW stage sort with assignee as that is what is relevant to this branch
I thought it was best to replace the stage stuff rather than add to it so we keep the branches separate during development. wdyt?
This PR is FE only
Adding default sort ability on RW assignee
> Enhancement: Add RW assignee as default sort option

- packages/core/admin/ee/server/services/review-workflows/__tests__/entity-service-decorator.test.js
- packages/core/admin/ee/server/services/review-workflows/entity-service-decorator.js
Partial Content API updates were broken if not populating `strapi_reviewWorkflow_stage` attribute.
To prevent this error when doing partial updates in the content api:
> fix: Content API partial update fails when not populating stage field 

- packages/core/strapi/lib/services/entity-service/types/index.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
- Add the type definition for the entity service's findOne method
> [TS][Entity-Service] Add type definition for the findOne method

- packages/core/strapi/lib/services/entity-service/types/index.d.ts
Adds the typings for the `findMany` method in the EntityService
To help developers & improve type safetiness.
1. Add the EntityService type here: https://github.com/strapi/strapi/blob/c41c3e715d9316fbf2d9179b8167cc845b7b028b/packages/core/strapi/lib/types/core/strapi/index.d.ts#L415
2. Generate types in one of the example projects with `yarn strapi ts:generate-types`
3. Play with the `strapi.entityService` in one of the controllers (for example):
```
import { factories } from '@strapi/strapi';
export default factories.createCoreController('admin::user', ({ strapi }) => ({
async find(ctx) {
console.log('findingMany');
strapi.entityService.;
const res = await strapi.entityService.findMany('api::test.test', {
limit: 3,
start: 1,
populate: {
createdBy: {
fields: ['firstname'],
},
},
}); …
```
> [TS][Entity Service] Add findMany types

- packages/core/strapi/lib/services/entity-service/types/index.d.ts
Adds types for the update method in the entity service.
To help developers & improve type safeness.
1. Go to [this file](https://github.com/strapi/strapi/blob/af8847e9441f15f426b6bca36e34c4391f3cc3d1/packages/core/strapi/lib/services/entity-service/types/index.d.ts) and rename it to index.ts.
2. Write the following code and play around with the `o.update` params
```
const o: EntityService = {
update: (uid, id, params) => {
return new Promise({});
},
};
o.update('api::test.test', 2, {
data: {
name: 'John',
},
fields: ['*'],
populate: 'user',
});
```
> [TS][Entity Service] Add update types 

- packages/core/upload/admin/src/utils/downloadFile.js
- packages/core/upload/admin/src/utils/tests/downloadFile.test.js
Uses native `fetch` API over the API client.
Fixes https://github.com/strapi/strapi/issues/17454
The automated tests covers at least a part of it. It would be nice if e.g. @Marc-Roig could test this on an actual S3 setup.
> fix(upload): Use native fetch over API client for downloadFile

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/tests/index.test.js
- packages/core/admin/admin/src/translations/en.json
Inside the Bulk Publish we can now show the count of already published entries selected and the count of the entries ready to be published
In the current implementation, we also count the entries already published in the message for entries ready to publish.
With this fix, we will show two separate messages for entries ready to publish and those already published.
Inside the List view of a collection select some entries already published and some ready to be published, you should see a message like this in the Bulk publish modal
CS-129
> [Fix] Bulk publish: show the count of already published entries

- packages/core/admin/index.js
- packages/core/admin/scripts/build.js
- packages/core/admin/webpack.config.js
This adds a new environment variable, which is read during the build step by webpack to enable source-maps: `STRAPI_ENFORCE_SOURCEMAPS`.
I have also changed to source map type from 'eval-source-map' to 'source-map' because the content security policy does not allow `eval`.
We receive a lot of bug reports where users reference minified errors from the browser console. Because the admin app is always built in production mode these errors are cryptic and often not actionable unless users overwrite their webpack configuration, which is heavy, and there is a chance they are not changing it back. [Example](https://github.com/strapi/strapi/issues/17457#issuecomment-1651829759).
This will make it easier for us to get the information we need in order to fix these bugs.
This is an idea for now I'd …
> Chore: Enforce build sourcemaps with an environment variable

- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/ee/admin/content-manager/components/Filter/CustomInputs/ReviewWorkflows/AssigneeFilter.js
- packages/core/admin/ee/admin/content-manager/components/Filter/CustomInputs/ReviewWorkflows/StageFilter.js
- packages/core/admin/ee/admin/content-manager/components/Filter/CustomInputs/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/content-manager/components/Filter/CustomInputs/ReviewWorkflows/tests/AssigneeFilter.test.js
- packages/core/admin/ee/admin/content-manager/components/Filter/CustomInputs/ReviewWorkflows/tests/StageFilter.test.js
Adds review workflow assignees to the list of filters in the CM filter view.
Support more use-cases for users who want to use advanced filtering.
> Feature: Add review workflow assignee to CM filter options

- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
Adds the cellFormatter back (must have been removed in a messy merge)
Even if internally in the content-manager we are moving away from this API we still need to support the cellFormatter since plugins like i18n use it: 
https://github.com/strapi/strapi/blob/489927e8e161dd5c3d48f0c97ab4efade802c3e3/packages/plugins/i18n/admin/src/index.js#L52
Go to any content-type in the content manager that has i18n enabled. You should have the following column.
https://github.com/strapi/strapi/pull/17347
> Support cellformatter in ListView table

- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
Allows to save a view configuration for a component.
Fixes a bug in the content-manager where a PUT request to save component's view configuration is sent to a wrong endpoint, resulting in a 405 HTTP error.
1. In a Content Type Builder, create a component
1. Click on "Configure the view"
1. Change a title of any text field
1. Click "Save"
Fixes #17575 , #17577
> fix: save component's view configuration

- packages/core/strapi/lib/services/entity-service/types/index.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/populate.d.ts
- packages/core/strapi/lib/services/entity-service/types/params/search.d.ts
- packages/core/strapi/lib/services/entity-service/types/result.d.ts
- packages/core/strapi/lib/types/core/attributes/utils.d.ts
- packages/core/strapi/lib/types/utils/object.d.ts
Add type definitions for:
- wrapParams
- wrapResult
- emitEvent
- findMany
- findPage
- findWithRelationCountsPage
- findWithRelationCounts
- findOne
- count
- create
- update
- delete
- clone
- deleteMany
- load
- loadPages
All methods QA'd by:
- @Convly 
- @innerdvations
> [TS] Add basic type definition for remaining entity-service methods

- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
Change MatchAlIntersect to MatchAll, cause the former doesn't exist
Param typings are not working 
make sure that the params are typing of entityService methods are working properly
> Fix params pick

- examples/getstarted/package.json
- examples/kitchensink/package.json
- packages/generators/app/src/utils/db-client-dependencies.ts
- yarn.lock
- Upgrade mysql2 client version from 3.5.1 -> 3.6.0 for CI
- Upgrade mysql2 client from 3.2.0 -> 3.6.0 for generated api and e2e test apps
It's not, but we should at least be generating projects with our recommended and tested version
- All CI tests should pass
- Strapi projects should work with mysql2 3.6.0 
Note: I thought that we could generate mysql2 projects with create-strapi-app but it only generates with the mysql client, so nothing to test there.
> Upgrade mysql2 client to 3.6.0 for CI

- packages/core/content-type-builder/admin/src/components/FormModal/utils/customFieldDefaultOptionsReducer.js
- packages/core/helper-plugin/src/components/GenericInput.jsx
- packages/core/helper-plugin/src/components/tests/GenericInput.test.jsx
When a date field is cleared we pass `null` as the onChange value, however we weren't checking this before trying to use `formatISO`, we now do this. It also fixes a rogue `module.exports` declaration we have in the codebase.
* Users were unable to clear date fields
* Go to entry with date field & date time field
* clear the date
* see no errors
* resolves #16493
* partially resolves CONTENT-1639
> fix: cannot clear date-field

- packages/core/admin/admin/src/content-manager/components/AttributeFilter/Filters.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/FieldPicker/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/FieldPicker/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/ViewSettingsMenu/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/ViewSettingsMenu/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/admin/src/translations/en.json
On the List View page, we would like to free up some space above the table, in the top right corner, to show only a Cog Icon that can open a menu with a link to the List View settings and checkboxes for selecting the columns to display in the List View.
Additionally, we want to add a reset button that selects the default columns of the collection.
In the list view, there are 2 elements in the top right corner of the table:
- The columns that are currently selected
- The cog icon that redirects to the settings of the list view (Configure the view)
We’d like to merge them to free some space in the list view.
- Go the content manager and select a collection
- On the list view you can see a Cog icon on the top right corner of the table
- click the cog icon
- you can click on the "Configure …
> List view: new cog button icon with the view settings in the list view page

- packages/core/admin/admin/src/hooks/useAdminRoles/index.js
- packages/core/admin/admin/src/hooks/useAdminUsers/useAdminUsers.js
- packages/core/admin/admin/src/hooks/useContentTypes/useContentTypes.js
- packages/core/admin/ee/admin/hooks/useLicenseLimits/useLicenseLimits.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/tests/Stages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/WorkflowAttributes.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/WorkflowAttributes/tests/WorkflowAttributes.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/CreateView/CreateView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/selectors.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/tests/validateWorkflow.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/validateWorkflow.js
- Move content-types and roles into the redux state to avoid prop-drilling
- Refactor the state and move `isDirty` and `hasDeletedServerStages` into selectors
- Refactor usage of `useSelector`: now that the application grows it makes sense to split up the different parts
- Render the `permissions` field for each stage; if no changes have been made the field should submit `undefined` in the edit-view to allow partial updates
- Make return values of involved data fetching hooks stable
Implements the FE part to assign roles which are allowed to change a stage.
> Enhancement: Render permissions for each review workflow stage

- packages/core/admin/admin/src/hooks/useAdminUsers/useAdminUsers.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflows.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
Renders a new button for each stage: "Apply to all stages", which will copy the current set of permissions to all other stages.
UX requiremet.
> Feature: Add an "apply to all stages" action for stage permissions

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/actions/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/constants.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
- Moves stage delete into a menu
- Adds "Duplicate stage"
> **Note**
> Styling is currently broken - same as for dynamic zones. I will investigate in a follow-up design-system PR what broke.
UX improvements.
> Feature: Add "Duplicate stage" menu for stages

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/InformationBoxEE.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
Changes the condition we use to determine whether the edit view EE info box should be displayed
Previously it was being displayed even for content types without review workflows enabled. e.g. 
https://github.com/strapi/strapi/assets/48524071/6eee873c-2f24-46ce-8644-08e8a04d5d5b
Updated tests
> fix(ee): condition for displaying edit view info box

- packages/admin-test-utils/src/environment.ts
- packages/admin-test-utils/tsconfig.json
* adds `@ts-expect-error` to the mock for `range.getClientRects` because we don't need to mock all the methods i.e. the fact it is iterable
* fixes build:ts
> fix: use ts-expect-error on admin test mock

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/TransferTokens/ListView/index.js
Updated the `ContentLayout` in both `ApiTokens` and `TransferTokens` to show `NoContent` and Call to action button in case the data fetch returns an empty list of tokens.  
There is a bug if the data fetching returns an empty list of tokens, the page will render an empty table, instead of the `NoContent` component with the CTA to create a first token. 
Since the data fetching will return an empty list of there is no token, `apiTokens` will always be boolean true (i.e. `!apiTokens` or `!!apiTokens`), so added an extra boolean to check if the list exists and if the list is empty.
Didn't find related tests and I wasn't sure if I should create some. 
n/a
> fix: ListView in ApiTokens and TransferTokens shows empty content table

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/index.js
Adds `cache-time: 0` for list and edit-views of API-tokens and users.
As a user I never want to see stale data, but always the latest state. https://github.com/strapi/strapi/pull/17630 proposed to use `refetch`, but I think it is actually better to always fetch (e.g. because another user has updated something in the meantime) when accessing thes pages.
- Closes https://github.com/strapi/strapi/pull/17630
- Fixes https://github.com/strapi/strapi/issues/17397
> Fix: Ensure fresh data for list and edit-views (api-tokens, users)

- packages/utils/typescript/package.json
Adding repository info in `package.json`.
Helps bots like renovate to group update prs
Check out https://www.npmjs.com/package/@strapi/typescript-utils after publishing a new package.
> chore(@​strapi/typescript-utils): add repository info to package.json

- packages/core/strapi/README.md
use picture with a media selector rather than rely on github decorators
fix the light/dark mode strapi logo
see if it works on github by viewing the file directly
> Fix Strapi dark and light mode images on readme

- api-tests/core/content-manager/content-manager/configuration.test.api.js
- packages/core/content-manager/package.json
- packages/core/content-manager/server/controllers/validation/model-configuration.js
- packages/core/content-manager/server/services/utils/configuration/__tests__/settings.test.js
- packages/core/content-manager/server/services/utils/configuration/attributes.js
- packages/core/content-manager/server/services/utils/configuration/settings.js
- yarn.lock
We only allowed `defaultSort` attributes to be top level ones. But Strapi allows you to sort by relational fields and other nested structures.
This PR modifies the yup validation so we can set the default sort by `strapi_stage[name]` and `strapi_assignee[name]`.
> feat: default sort by relational fields

- packages/core/admin/webpack.config.dev.js
* fixes the webpack dev server check of a plugin
* the webpack dev server can't accept undefined in replacement of a plugin but it can accept `false`
* run `yarn develop` in the admin package
> fix: webpack dev server wants false not undefined for a non-enabled plugins

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/StageSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/tests/StageSelect.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflows.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/tests/useReviewWorkflowsStages.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/hooks/useReviewWorkflowsStages.js
Refactors the data-fetching part for review-workflows in the content-manager:
Admin app should support RBAC for stages.
> Enhancement: Refactor stage data fetching in the CM edit view

- packages/core/strapi/lib/types/core/attributes/common.d.ts
- packages/core/strapi/lib/types/core/attributes/uid.d.ts
- packages/core/strapi/lib/types/utils/expression.d.ts
- packages/core/strapi/lib/types/utils/guard.d.ts
- Remove the type narrowing made in `Attribute.UID` to get a list of possible string-like attribute for `targetField`
- Having such narrowing meant that in the case of application types not being available (e.g. not generated), the narrowing was done on `Common.UID.Schema`. Which caused a circular dependency when looking at its keys.
- `Attribute.Any `=> `Attribute.UID<Common.UID.Schema>` => `KeysByType<Common.UID.Schema>` => `GetAll<Common.UID.Schema>` => `Shared.ContentTypes[Common.UID.ContentTypes]` => `Attribute.Any `
- Don't generate types & try to use `Attribute.Any`. Autocomplete should be available
> Fix circular dependency caused by Attribute.UID in Attribute.Any

- packages/core/helper-plugin/src/hooks/tests/usePersistentState.test.ts
- packages/core/helper-plugin/src/hooks/usePersistentState.ts
Migrate helper-plugin/hooks/usePersistentState to typescript.
Added test case.
You can check if any value in the local storage getting set properly or not, for eg: `key: navbar-condensed`(i.e. dashboard left menu)
https://github.com/strapi/strapi/issues/17690
> [helper-plugin]: migrate use-persistent-state hook to typescript 

- packages/core/strapi/lib/services/entity-service/types/params/index.d.ts
- packages/core/strapi/lib/types/utils/expression.d.ts
- Replace `MatchAll` by `MatchAllUnion` and `MatchAllIntersect` in `utils/expression`
- Use MatchAllIntersect in the EntityService Params Pick
- Using a match all union-like for the params pick was creating a union of possible object with single params props thus creating a wrong representation of the final params object.
- On top of that, having a union meant that we were introducing an infinite recursion when using the params (eg. when using entity service methods)
> [TS] Fix the EntityService Params Pick

- packages/core/upload/server/controllers/content-api.js
- packages/plugins/users-permissions/server/controllers/user.js
use strapi.contentType(uid) instead of strapi.getModel(uid) when sanitizing in controllers that were using it.
strapi.getModel only returns the base model, not including fields that were added dynamically (such as creator fields, review workflows fields, etc)
Everything should still work as before, except now fields that were updated after Strapi init will be recognized.
For example, if you create a content type with a public attribute, but then update it to private after Strapi init, it should now be kept in sanitization instead of removed (and vice versa).
> Use full model instead of base schemas for sanitization

- packages/core/strapi/lib/commands/utils/data-transfer.js
Review workflow assignee (to be released next week) includes a new column into content types, `strapi_assignee`. In a similar fashion as what happened with `strapi_stage` , data transfer , when transfering from EE->CE (or the other way around) , notices there are different fields for content types.
This excludes the strapi_assignee field from the transfer schema check.
> fix: include strapi_assignee as a known feature in data transfer

- packages/plugins/users-permissions/server/bootstrap/index.js
- packages/plugins/users-permissions/server/controllers/auth.js
Adds the allowedFields feature that [was previously stalled](https://github.com/strapi/strapi/pull/16333) for being a breaking change
To allow users to choose which fields are accepted or not during user registration
- Add a field called 'newField' (for example) to your u&p user schema
- Configure the plugin like the following:
```js
// path: ./config/plugins.js
'users-permissions': {
config: {
register: {
allowedFields: [ 'newField' ]
}
}
}
}
```
- newField should be accepted on registration
- 
- Configure the plugin like the following:
```js
// path: ./config/plugins.js
'users-permissions': {
config: {
register: {
allowedFields: [  ]
}
}
}
}
```
- newFIeld should no longer be accepted on registration
[Documentation …
> [U&P] Add allowedFields configuration option

- packages/core/content-manager/package.json
- yarn.lock
Adds `qs` as dependency to the CM.
Currently the CI is failing, because eslint found the problem.
> fix(cm): add missing qs dependency

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/AssigneeSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/tests/AssigneeSelect.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/StageSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
- Use `Combobox` over react-select
- Check user permissions before loading them
- Add missing key attribute to stage options
- Uses `getDisplayName` to format user names to be consistent with the list-view
- Removes tech-debt
- Fixes a bug, where users would load forever
- Fixes a console error
> fix(cm): check permissions before loading users

- packages/core/data-transfer/src/__tests__/test-utils.ts
- packages/core/data-transfer/src/engine/__tests__/engine.test.ts
- packages/core/data-transfer/src/engine/index.ts
- packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/assets.test.ts
- packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/index.test.ts
- packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
- packages/core/data-transfer/src/strapi/providers/local-destination/strategies/restore/index.ts
- packages/core/strapi/lib/commands/actions/import/__tests__/import.test.js
- packages/core/strapi/lib/commands/actions/import/action.js
- packages/core/strapi/lib/commands/actions/import/command.js
- packages/core/strapi/lib/commands/actions/transfer/__tests__/transfer.test.js
- packages/core/strapi/lib/commands/actions/transfer/action.js
- packages/core/strapi/lib/commands/actions/transfer/command.js
- packages/core/strapi/lib/commands/utils/data-transfer.js
Update the import and transfer commands to generate the correct restore object
TODO:
* I think we first need a discussion about if it would make more sense to make local-source a wrapper for a local-restore-source rather than local-source using strategies, since the strategies are/will be so tightly integrated it may be difficult to abstract them
The initial functionality of the restore strategy causing a global reset of Strapi data caused too many users to be confused. 
The updated functionality of only touching data included in a transfer matches user expectations to not touch files that are excluded in a transfer or import.
Using exclude or only with transfer or import should now only delete the files that are included in the process.
Closes …
> [DTS] Only delete types of data that are being transferred

- api-tests/core/content-manager/api/relations-permissions.test.api.js
- packages/core/content-manager/server/controllers/relations.js
Recently, we implemented a security fix that restricts users from visualizing a relation mainfield if they don't have permissions to read the targeted content type field.
For example, consider a relation `Address → Category`, where the main field of Category is `name`. The address relation should only display the category ID if the user doesn't have permission to read the category name.
This implementation has been successful so far. However, we have encountered an issue ([[see reported issue](https://github.com/strapi/strapi/issues/17561)](https://github.com/strapi/strapi/issues/17561)) where the User roles are always empty after this fix.
<table>
<tr>
<td>BEFORE
<td>AFTER
<tr>
<td><img src="https://github.com/strapi/strapi/assets/20578351/b786126f-34c7-499d-9815-b27e5ddb8889" /> …
> fix: display role names

- packages/core/helper-plugin/src/hooks/useLockScroll.ts
Migrate useLockScroll from helper-plugin to typescript.
Relates to [#17690](https://github.com/strapi/strapi/issues/17690)
> [helper-plugin]: move useLockScroll.js to TypeScript

- packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
- packages/core/strapi/lib/commands/actions/import/action.js
The assets metadata holds the URLs for the assets, so this check doesn't make sense for any provider.
To be more permissive in the data transfer.
Run an import with different `--exclude` and `--only` options that only contain assets, or the content, or the links.
#17730
> Remove check for excluding non-local providers

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/pages/EditView/EditView.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/tests/validateWorkflow.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/utils/validateWorkflow.js
- Display error message around each stage also if an error occurred for stage permissions
- Allow empty arrays to be sent
- Fixes a case where removing a role would send `undefined`, because so far only additive updates worked
Fixes the issues above.
> fix(rw): allow subtractive partial updates

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
Hides the chevron down icon on the stage context menu.
To properly overwrite the icon we need to pass in `null` over `undefined`.
> fix(rw): hide endIcon on stage context menu

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
Currently the context menu of a dynamic zone component renders the more icon and a huge chevron next to it. This PR removes the chevron.
To properly overwrite the icon we need to pass in null over undefined.
- Similar to https://github.com/strapi/strapi/pull/17863
> fix(cm): remove chevron-down on context menus of dynamic-zone components

- packages/core/strapi/lib/types/core/config/api.d.ts
- packages/core/strapi/lib/types/core/config/index.d.ts
Adds types for the API configuration file.
To simplify users' lifes
Go to the `kitchensink-ts` example project and in the `config/api.js` write:
```
import { Api } from '@strapi/strapi/lib/types/core/config';
export default {
rest: {
defaultLimit: 3,
maxLimit: 10,
withCount: true,
prefix: '/api',
port: 1337,
},
responses: {
privateAttributes: ['createdBy', 'updatedBy'],
},
} as Api;
```
> Create types for Api Config

- packages/core/admin/admin/src/components/AuthenticatedApp/index.js
It adds the NpsSurvey back to the CMS
It was removed on accident.
Build and start the app, wait 5 minutes, the survey should appear.
https://github.com/strapi/strapi/commit/bc6c5b005869dd00db37a3942c0e30f9e955be3d#diff-dbb33815cda57c3b4c530539db1260835457b6ed58d033a1ef02a288586fb568L222
> Add NpsSurvey back to AuthenticatedApp

- packages/core/strapi/lib/types/core/config/database.d.ts
- packages/core/strapi/lib/types/core/config/index.d.ts
Adds Database configuration type
in kitchensink-ts DB config you can add the following and play around
```
import { DBConfig } from '@strapi/strapi/lib/types/core/config';
export default ({ env }) =>
({
connection: {
client: 'postgres',
connection: {
database: env('DATABASE_NAME', 'strapi'),
password: env('DATABASE_PASSWORD', 'strapi'),
host: env('DATABASE_HOST', 'localhost'),
user: env('DATABASE_USERNAME', 'strapi'),
port: env('DATABASE_PORT', 5432),
ssl: true,
},
acquireConnectionTimeout: 10000,
},
} as DBConfig<'postgres'>);
```
> DB configuration type

- packages/plugins/graphql/server/services/builders/resolvers/association.js
There's a typo, causing validateQuery to fail for queries containing media file references.
Fix the error `Missing schema in validateQuery`.
Query for any entity that has a media file relation field and include the file in the attributes.
fixes #17875
> Fix #17875 - Missing schema in validateQuery after upgrading to v4.13.1

- packages/core/helper-plugin/src/utils/request.ts
- packages/core/helper-plugin/src/utils/tests/request.test.ts
Migrates the request util to TS.
I'm not super familiar with TS generics yet so I'd appreciate if you could look into how I implemented them here.
Part of the helper plugin migration to TS: #17690
#17690
> [helper-plugin] Migrate request util to TypeScript

- examples/getstarted/src/api/kitchensink/content-types/kitchensink/schema.json
- packages/core/content-manager/server/services/field-sizes.js
- packages/core/content-type-builder/server/controllers/validation/types.js
- packages/core/content-type-builder/server/services/constants.js
- packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js
Adds the type "blocks" to the CM and CTB server
So the CM and CTB are aware of the type "blocks"
- The server should start with {"type": "blocks"} in a schema.json
- The content manager should display "not supported" for the input
- The CTB should save a newly added blocks type and write to the schema.json for that content-type
https://github.com/strapi/strapi/pull/17877
> [Rich Text Editor] Add type blocks to server

- packages/core/strapi/lib/types/core/config/database.d.ts
- packages/core/strapi/lib/types/core/config/index.d.ts
Match the name of the export with the config file name
Match the name of the export with the config file name
> [TS] Rename dbconfig to database

- packages/core/database/lib/lifecycles/subscribers/index.d.ts
The `Subscriber` union type of which `SubscriberMap` is a component was missing the optional `models` parameter document here at [#declarative-and-programmatic-usage](https://docs.strapi.io/dev-docs/backend-customization/models#declarative-and-programmatic-usage).
I added the optional field by intersecting it with the original type formulation, and also made the `Action` keys optional, since not all of the 18 individual actions should necessarily be specified when making a `SubscriberMap`.
---
This is just a simple fix to one of the types conflicting with how it's used in the official documentation.
> Added missing `models` key to `SubscriberMap` and made actions optional.

- packages/core/data-transfer/src/file/providers/source/index.ts
Fixes a failure when running `strapi import` to import a`.tar.gz` backup file.
When I ran `strapi import -f database/local/export_20230825142140.tar.gz`, it failed with the message:
```
error: [ERROR] Error while uploading asset featured_image_28dc07b76a.png TypeError: Cannot set properties of null (setting 'url')
```
I traced this to a mistake in `LocalFileSourceProvider` in the way it parsed asset metadata files; the `ReadEntry.collect()` method from the `tar` library returns `Buffer[]`, so if there is more than one Buffer in the array, the call to `[].toString()` inserts `,` characters in the string. In my case, this led to metadata containing this:
```json
"has,h": "featured_image_28dc07b76a",
```
Which caused a crash in `LocalStrapiDestinationProvider`: …
> Fix `strapi import` failure caused by corrupted asset metadata

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/admin/admin/src/content-manager/components/Inputs/utils/getInputType.js
- packages/core/admin/admin/src/content-manager/utils/schema.js
- packages/core/admin/package.json
- packages/core/content-type-builder/admin/src/components/AttributeIcon/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
- yarn.lock
Render basic Blocks input with Slate. 
- Added basic blocks editor(using Slate)
https://strapi-inc.atlassian.net/browse/CS-190
1. Go to CTB, add new field "Blocks" and save it.
2. Go to CM for respective collection type, you should be able to see newly added Blocks type with default value.
For now there are no event handlers or renderers added it the block input.
> [CM]: Add basic blocks(Slate) editor input 

- packages/admin-test-utils/src/environment.ts
Adds a condition to ignore styled-components errors about transient props.
Until we have migrated to styled-components v6 there is nothing we can do about these errors and they are cluttering the test logs.
> chore(admin-test-utils): swallow styled-components transient errors

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/reducer/tests/index.test.js
Also searches for stages via `__temp_key__` rather than `id` only when cloning a stage.
Right now stages that don't have an id (because they weren't saved yet) couldn't be cloned. This PR fixes that.
> fix(review-workflows): fix cloning for temporary stages

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js
- packages/core/admin/package.json
- yarn.lock
Sets up the container of the new block editor's toolbar.
Also sets the global stylings for the blocks editor (everything excluding the Editable component which @madhurisandbhor is working on)
It's exported from its own component because it will likely be reused for the popover feature.
It will allow us to start building the different sections in parallel.
> [Blocks editor] Setup toolbar container

- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/AssigneeSelect.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/AssigneeSelect/tests/AssigneeSelect.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/components/StageSelect/tests/StageSelect.test.js
- packages/core/admin/ee/admin/content-manager/pages/EditView/InformationBox/tests/InformationBoxEE.test.js
Enables the test-suite for review-workflow assignees again and fixes the outstanding problems. The main issue was, which has been an oversight during review, is that `Combobox` doesn't receive a `customizeContent` callback. Instead is has a `loading` prop and stores the selected value instead of customizing how it is being displayed.
Loading states between stages and assignee is not consistent anymore; the loading state for assignee is displayed in the popover. Are we ok with that?
The tests for `StageSelect` and `InformationBox` keep throwing `act()` errors, but I can't figure out why. Would appreciate of someone has an idea on how to fix them.
Enables FE tests for these three components.
> chore(review-workflow): enable assignee test-suite

- packages/core/admin/ee/server/routes/review-workflows.js
Allow users to update stage even if they don't have Review Workflow Settings update permissions. The permission is handled by the stage permission itself.
> Feature: don't require update permissions to change stage

- packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js
- packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js
- packages/core/upload/admin/src/utils/tests/appendSearchParamsToUrl.test.js
* branches from #17955 – thanks @itsramiel for getting this started
* uses `window.strapi.backendURL` as a the baseURL for `URL` constructor
* `URL` cannot take relative urls without a `baseUrl` argument
* imo I think this direction is perhaps better because we're not doing string manipulation and we're using web APIs still, there's also less code branches compared to the former PR
* automated test
* resolves #17931
* resolves CONTENT-1487
* closes #17955
> fix: relativeURLs fail with appendSearchParamsToUrl

- api-tests/core/admin/ee/review-workflows.test.api.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
When creating a workflow, stage color attribute was ignored.
> fix: pick color attribute on create workflow

- packages/core/admin/ee/server/migrations/review-workflows-workflow-name.js
Workflow name was reseted to 'Default' when upgrading to EE.
A migration file was setting the workflow names to 'Default. The workflow content type does not exist on CE , but the workflow data is persisted. So when updating to EE, the migration file always detected the new Workflow content type and so updated all workflow names to use the "Default" name.
> fix: prevent workflow name to be reseted when CE -> EE

- packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js
- packages/core/upload/admin/src/utils/tests/appendSearchParamsToUrl.test.js
* uses a fallback if `window.strapi.backendURL` is not defined
* if you don't provide it, the upload plugin still crashes
* there's an automated test added
* relates to #17975
> fix: fallback to window.location.href if backendURL is not defined

- packages/core/helper-plugin/src/components/Form.tsx
Migrate Form.jsx helper-plugin component to Typescript
[#17690](https://github.com/strapi/strapi/issues/17690)
> [helper-plugin]: migrate Form to TypeScript

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Adds the `STRAPI_ENFORCE_SOURCEMAPS` var reference and `yarn strapi report` cli command call out
Make bug reports better
Try creating a new bug report
n/a
> Update GH bug report template

- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/ConfirmBulkActionDialog/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/ConfirmBulkActionDialog/tests/index.test.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActionButtons/SelectedEntriesModal/tests/index.test.js
- packages/core/content-manager/server/controllers/collection-types.js
- packages/core/content-manager/server/services/entity-manager.d.ts
- packages/core/content-manager/server/services/entity-manager.js
It fixes our bug when we try to publish/unpublish entities with a locale that is not the default one. Now the locale is passed as param
Because otherwise we had a problem when we called the API to publish the entities
- Go to Settings > Internationalization .
- Create additional locale e.g. Italian. Make sure it's not default locale.
- Confirm that the content type has enabled "Draft & Publish" feature.
- Create an item for the content type in locale Italian. It should be in Draft status.
- Go to the content type list view
- Select the item using checkbox, then click "Publish" button.
- You need to see the item in the list.
- Click "Publish" on the modal shows with success.
you can also test if it works with the draft and publish relations, you had to create a entity with a Relation and …
> [Bugfix] Bulk publish/unpublish for non-default locale entities

- packages/core/admin/admin/src/index.js
- packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js
- packages/core/upload/admin/src/utils/tests/appendSearchParamsToUrl.test.js
* Sets the fallback for `backendURL` at the very top where it's defined.
The env key `STRAPI_ADMIN_BACKEND_URL` is passed as an `option` to the building script, typically this comes from the strapi instance `serverURL` from it's `sever` config, if none is set we default to an empty string to support relative URLs  – I assume, there's no documentation and the [PR](https://github.com/strapi/strapi/pull/5833) is lacking any information:
https://github.com/strapi/strapi/blob/c03a0a4a281f64796eba9ffaad88ad2bad154492/packages/core/utils/src/config.ts#L14 This is then still passed to the admin panel build (even though to support relative URLs you'd expect `undefined`).
Passing `undefined` only however then breaks `prefixFileUrlWithBackendUrl` because we "just use string concatenation" so …
> fix: set a fallback where we define `window.strapi.backendURL`

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/tests/Stage.test.js
Replace the "Apply to all stages" button with an `IconButton`.
Came up during the blitz-session design review. This is only possible since the DS@1.10.1 was released, which added support for `variant` props on `IconButton`s.
> fix(review-workflows): make apply to all stages an iconbutton

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
- packages/core/helper-plugin/src/components/ConfirmDialog.jsx
- Uses the `primary` variant for the confirm button
- Removes the default icon on the confirm button
Came up during design-review during the blitz session.
> fix(review-workflows): update confirm button styles for apply all action

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
- packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
Updates the DOM structure of relation input fields and rework flex-handling.
Prevents fields from wrapping: Without relation items would sometimes start next to the relation input field (see attached issue)
This is how relations are supposed to look:
You can use the kitchen-sink example, which already contains two many-to-many relations with tags. You have to create more than 10 tags and add them as relations.
Edit the layout of the content-type to make sure one field is displayed at 50% and the other one at 100% width.
- Closes https://github.com/strapi/strapi/pull/17842
- Refs https://github.com/strapi/strapi/issues/17391
> fix(CM): fix relation layout

- docs/docs/docs/01-core/admin/01-ee/01-review-workflows.md
- docs/docs/docs/01-core/admin/03-settings/01-review-workflows.mdx
- docs/docs/docs/01-core/content-manager/02-review-workflows.mdx
Extends contributor docs by RBAC for stages.
Having complete docs is good.
> chore(docs): extend contributor docs by RBAC for stages

- packages/core/admin/ee/admin/pages/SettingsPage/pages/ReviewWorkflows/components/Stages/Stage/Stage.js
Fixes a few minor alignment issues of the action menu of a stage:
|-|-|
|<img width="150" alt="Screenshot 2023-09-13 at 11 14 14" src="https://github.com/strapi/strapi/assets/2244375/aacdb4ac-eb0b-4f5e-9a52-3f34b7e2066b">|<img width="150" alt="Screenshot 2023-09-13 at 11 14 02" src="https://github.com/strapi/strapi/assets/2244375/e9b0b719-7f54-4124-a187-e67d30a986e4">|
Unifies the hover background-color of the context menu and drag and drop button.
Fixes design releated blitz session bugs.
> fix(review-workflows): improve stage action alignment

- packages/plugins/users-permissions/admin/src/pages/Roles/pages/CreatePage.js
- packages/plugins/users-permissions/admin/src/pages/Roles/pages/EditPage.js
* Adds default messages to the form errors.
* We currently don't supply any messages to our IntlProvider in tests so when there's no defaultMessage it warns us the id will be used instead polluting the console.
* part of #17924
> tests(user-permissions): add default messages for form errors

- packages/core/admin/admin/src/components/RBACProvider/index.js
Adds a fragment in the RBACProvider
The provider expects a single child:
```
react.development.js:209 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `RBACProvider`, expected a single ReactElement.
at RBACProvider
```
- Go to a page like: /admin/settings/application-infos
There should be no error in the console for the invalid prop
> Fix RBAC provider single child expectation

- packages/core/admin/ee/server/migrations/review-workflows-stages-roles.js
- packages/core/admin/ee/server/register.js
- packages/core/admin/ee/server/services/review-workflows/stage-permissions.js
- packages/core/admin/ee/server/services/review-workflows/stages.js
Adds a migration that migrates all existing review workflow stages to have RBAC permissions for all admin roles.
So that if you're coming from a version before RBAC for review workflow stages the apps behaviour is consistent. e.g. any role can still update any stage of any workflow.
- Roll back to a version pre RW RBAC stages (e.g. currently `main`)
- Build and run the app
- Set up some workflows and stages etc
- Roll forward to this branch
- Build and run the app
- Verify that the migration is run (see logs) and that all stages of every workflow in the UI have every role applied to their RBAC permissions
e.g.
CONTENT-1856
> Migrate stages into RBAC versions

- packages/core/data-transfer/src/strapi/queries/link.ts
Uses schema names for custom queries in DTS
Using a postgres db with a custom schema and deleted 'public' schema:
- without this PR: import, export, and transfer all fail due to invalid schema reference
Using a postgres db with a custom schema and deleted 'public' schema:
- with this PR: import, export, and transfer should now all work normally
Using any other database:
- with this PR: import, export, and transfer should still all work normally
Fixes #16836
Specific alternate solution to the more general #18042
> [DTS] Use schema names in custom queries

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js
Inheriting font size for the modifier elements
Modifiers are not working on headings and some other blocks
https://strapi-inc.atlassian.net/browse/CS-237
Try to apply some modifiers(italic/strikethrough etc) to headings and it should work.
> [Blocks] Modifiers are not working on headings and some other blocks

- packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
* adds optional chaining to `listRef.current` because the ref will not always have a node attached.
* avoids accessing a function on `undefined | null`
* resolves #18025
> fix(content-manager): add optional chaining because listRef may not have a node attached

- packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeList/index.js
- packages/core/content-type-builder/admin/src/components/AttributeOptions/tests/__snapshots__/index.test.js.snap
It removes an inline style that gave some problems in Safari, in the Dialog of the Content Type Builder.
Because there is a wrong height of the last two grid elements in the grid as you can see in this picture
https://user-images.githubusercontent.com/9023312/258780045-09354681-e9be-49c2-a3e9-70f2e74fa994.png
And this cause a problem with the Relation and UID content type buttons, they are not clickable
- Use Safari browser
- Go to Content Type Builder plugin
- Click on Add another field button of existing CT
- Scroll down to the end of the content type list
- Try to click on either Relation or UID
https://github.com/strapi/strapi/issues/17591
> [Fix] Fix the content Type Dialog problem with the Grid elements in Safari

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js
- packages/core/admin/admin/src/translations/en.json
Quote option added with test case
User should be able to select a quote option from the dropdown to convert text to block quote
> [blocks]: Quote option added

- packages/core/strapi/lib/types/core/strapi/index.d.ts
PR #17747 renamed the property `plugin` to `pluginId` on `CustomFieldServerOptions` types on the core lib.
https://github.com/strapi/strapi/blob/9756cafa000a3cb2e15702b1f73ccaf1af22bf82/packages/core/strapi/lib/types/core/strapi/index.d.ts#L5-L15
While `strapi.customFields.register(...)` on `server/register.ts` still expects the property `plugin`.
https://github.com/strapi/strapi/blob/41e2d2ccf25f13d47b90c2f8a0cd3b1bd8930b22/packages/core/strapi/lib/core/registries/custom-fields.js#L47
This causes the build of typescript plugins to fail if it still has the `plugin` property
If it's being replaced to `pluginId` typescript will accept it and build it.
But after building the Strapi app and running `strapi develop`, the plugin will fail the registration due to missing `plugin` prop.
``` …
```
> fix(core): Revert plugin property on CustomFieldServerOptions

- packages/core/admin/admin/src/content-manager/components/InputUID/index.js
- packages/core/admin/admin/src/content-manager/components/InputUID/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
* refactors `InputUID`'s data-fetching to stop using callback refs & use `react-query`
* tweaks to tests parallel to #18113 so they're in sync (it doesn't matter whos merged first)
* It avoids as many confusing `useEffect` calls as there were
* refs for data-fetching links rendering to data-fetching, we know this is bad
* cleans up a lot of noise in the component
* automated tests should pass 🪄 
* nope, just irritated me
> refactor(content-manager): convert InputUIDs data-fetching to use react-query

- packages/core/email/shared/types.ts
Defines shared types to be used throughout the email package
Type consistency across BE and FE of email package
Defined as per https://github.com/strapi/strapi/pull/18117#discussion_r1331915646
I plan to import and use these types where relevant in 
https://github.com/strapi/strapi/pull/18117 & https://github.com/strapi/strapi/pull/18127
> [Email] define shared types for email package

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/tests/useBlocksStore.test.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js
When hitting the enter key inside a list:
- If the currently selected list item is not empty, create a list item below
- If the currently selected list item is empty, create a paragraph block below outside of the list
The behavior should be the same for both ordered and unordered lists.
Known issue: if you have an empty list item that is not the last one and you hit enter, the paragraph will be created, but the list items after your cursor will be deleted.
Follow-up to #18112
> [Blocks editor] Handle enter key behavior in lists

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js
- packages/core/admin/package.json
- yarn.lock
added slate history
User can undo redo typing in editor using cmd+z, cmd+shift+z
> [blocks]: Add slate history

- packages/core/admin/admin/src/content-manager/components/RelationInput/components/tests/Option.test.js
- packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/tests/useLazyComponents.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
- packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js
- packages/core/helper-plugin/src/components/tests/DateTimePicker.test.tsx
- packages/core/helper-plugin/src/utils/tests/request.test.ts
* mocks `once` in helper-plugin tests for `DateTimePicker` & `request`
* fixes `act` warnings in `useLazyComponents`, `useRelation` and `InputUID`
* fixes `keys` warning in `Options`
* Stops erroneous console messages in FE tests
* automated testing
* part of #17924
> test(content-manager): fix console pollution in tests

- packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/baseForm.js
- Removes the default input
- Moves the blocks method to the file to respect alphabetical order
- Remove commented code from 2 years ago
A plain text default value doesn't make sense for JSON content. It created errors when it was provided.
Create a new blocks attribute.
> [Blocks editor] Remove default value input from advanced CTB form

- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js
- packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js
Adding a new line(Para) below end Code block or Image block
Currently user is not able to type or add new block below code or image block, [Issue](https://strapi-inc.atlassian.net/browse/CS-261) 
User can now add new block or type below the end code/image block.
> [Blocks Editor]: Can’t create a block below an image or code block

- packages/core/admin/server/validation/permission.js
Fixes validation bug in admin user panel (upload plugin author role)
EDIT: by updating the validation schema to allow a subject to be `null`
Lets author admin user access the upload plugin panel.
EDIT: the FE sends `null` but the server does not accept it even though this is valid.
When author user uploads a file, the upload panel should list the uploaded files of the author.
* resolves #17840
> fix: make permission subject nullable in schema.
