packages/utils/typescript/lib/generators/common/models/mappers.js

Add blocks to the TypeScript namespace mapper
Otherwise it throws a warning/error in the console:
`"blocks" attribute from "api::kitchensink.kitchensink" has an invalid type: "blocks"`
Go to the getstarted start the app and you should see no warning in the console
https://github.com/strapi/strapi/pull/18166

Add blocks to namespace mapper

---

examples/getstarted/types/generated/components.d.ts
examples/getstarted/types/generated/contentTypes.d.ts
packages/core/types/src/modules/entity-service/params/attributes.ts
packages/core/types/src/types/core/attributes/base.ts
packages/core/types/src/types/core/attributes/blocks.ts
packages/core/types/src/types/core/attributes/common.ts
packages/core/types/src/types/core/attributes/index.ts
packages/core/types/src/types/core/attributes/utils.ts
packages/core/types/src/types/core/common/schema.ts
packages/core/utils/src/types.ts

- Add the `blocks` attribute type and its related definition
- Fix the Common.Schemas type (fix the broken link to dynamic type registries)

Add missing blocks attribute types

---

.github/workflows/tests.yml
package.json

* updates workflow to run `yarn test:ts:packages` & `yarn test:ts:back` 
* If you add a package e.g. `@strapi/helper-plugin` and include the script `yarn test:ts` then it will be caught under the `yarn test:ts:packages` command and we can check the types correctly – the helper-plugin is already broken due to #17960, where the CI was not checking it correctly.

chore: add tsc for packages and back to workflow

---

packages/core/admin/package.json
yarn.lock

Restore @radix-ui/react-toolbar dependency
Looks like it was deleted during a merge when resolving conflicts.

Restore radix toolbar dependency

---

.github/workflows/tests.yml
playwright.base.config.js

- Stores traces for failed e2e tests
- Uploads traces as GH Action artifact
I am pretty lost why https://github.com/strapi/strapi/pull/18065 keeps failing and hope traces give me some hints.

chore(e2e): store test traces for failed tests as GH action artifacts

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js

Shows the i18n 🌍 icon next to a field label when it's localized
Create a new blocks field in a localized content type, make sure that you see the icon, and that you don't see it when the field is not localized.
replaces #18160 that had a messed up git history. also narrows the scope, to have 1 PR per problem

[Blocks editor] Show i18n icon on localized blocks fields

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/BlocksInput/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/tests/index.test.js

Disables blocks fields when the user marked them as non editable in the configure the view page.
Feature parity with other types of fields.
Make a blocks field non-editable in the configure the view page. Go back to the edit view and try to edit things.

[Blocks editor] Fix disabled state

---

.github/workflows/tests.yml
packages/utils/pack-up/package.json
packages/utils/pack-up/src/__tests__/cli.test.ts
packages/utils/pack-up/src/node/check.ts

* fixes upstream issues similar to #18133 
* adds `check` command
* reintroduces the CLI tests in the CI
* A check command is very helpful for post build resolution to ensure everything worked as expected & the code you're exporting actually works in a dev env. It uses esbuild for simplicity and speed to validate.
* CLI testing reintroduced covers the check command
* Should be merged after #18133 as there are some more important refactors in the aforementioned PR.
* resolves CONTENT-1879
* resolves CONTENT-1925

feat(pack-up): add check command

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js

Add a withImages plugin to Slate so images are truly void elements
- Currently you can edit the text on an image element. It also means if your cursor is above the image and you select a new block it will delete the image
- Add an image
- Put your cursor above the image and start typing, it should be whatever block you have selected
- Change the block and the image should stay
- Hit enter and you should be on a new line under the image

[RTE] Make images truly void

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

- Resolves the strange behavior we encountered when selecting content with mixed block types in the RTE block editor.
Because the Blocks dropdown continuously changes its selected option between the block types in the selection.
- Create a new blocks field inside a Collection.
- Create different content such as an h1, a paragraph, and a quote.
- Use the mouse to select all the created content.
- The option selected in the Dropdown will be the one related to the block type where you positioned the cursor to start the selection.
This PR is the new version of this Pr https://github.com/strapi/strapi/pull/18162 so we need to manage all the comments received in the old one (https://github.com/strapi/strapi/pull/18162#discussion_r1336740789)

[Blocks editor] Manage mixed blocks selection

---

.github/workflows/tests.yml
package.json
packages/admin-test-utils/package.json
packages/admin-test-utils/tsconfig.json
packages/core/admin/package.json
packages/core/helper-plugin/.eslintrc.js
packages/core/helper-plugin/package.json
packages/core/helper-plugin/src/content-manager/utils/tests/contentManagementUtilRemoveFieldsFromData.test.ts
packages/core/helper-plugin/src/content-manager/utils/tests/formatContentTypeData.test.ts
packages/core/helper-plugin/src/content-manager/utils/tests/testData.ts
packages/core/helper-plugin/src/utils/request.ts
packages/core/helper-plugin/tests/utils.tsx
packages/core/helper-plugin/tsconfig.build.json
packages/core/helper-plugin/tsconfig.eslint.json
packages/core/helper-plugin/tsconfig.json
packages/core/helper-plugin/webpack.config.js
packages/plugins/color-picker/admin/.eslintrc.js
packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx
packages/plugins/color-picker/admin/src/global.d.ts
packages/utils/tsconfig/client.json
yarn.lock

* uses a yarn alias at the monorepo root to always install the TS version of the DS
* fixes the helper-plugin types & adds `test:ts` command so we can ensure the package types don't break
* Uses `Bundler` as the default client config because all conversions with admin code should be using a bundler
* fixes color-picker types & removes the global dts to override the libs that did not previously have types
* ensures we build packages with DTS=true (for the helper-plugin) in the CI 
* Updates `ForkTsCheckerPlugin`
* We keep breaking the helper-plugin types
* We need the DS types so we can work faster

chore: use yarn resolution for design-system

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/BlocksInput/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js

Sets a fixed height of 512px for the whole editor (toolbar + content). It's both the min and max height.
In the current implementation 512px was only for the content and not the toolbar, and it was a max-height, so when you had no content the editor was tiny.
It's what's in the designs

[Blocks] Set fixed height for the whole editor

---

packages/core/admin/admin/src/content-manager/pages/ListView/index.js

The changes fix the issue faced when selecting a 'relation' type field.
The issue: 
In the following code:
We are overwriting the mainfield object, with single property and are not preserving any other previously held properties that we are accessing here:
I added a single line to preserve the object's previous property, while adding a new property.
The users are not able to use the relation type filter.
- Go to Content Manager > Choose any collection
- Click on Filters button
- Choose createdBy/ or any other relation field
- See error in console
closes #18174

fix: undefined error for relation type filter field

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js

This PR adds the list ordered and list unordered options to the Dropdown, change the options order and fix a small issue we had when we selected a list with the cursor (the Dropdown remains empty)
We need the list options in the dropdown because in future we want to show a popover when you selected a portion of text in the editor with all the options in the Dropdown plus the list options
Create a new block field and try to create a new list from the dropdown
- the related modifier needs to be toggled and also the option in the dropdown needs to be selected
- when you select a list with the cursor in the list the related option in the dropdown needs to be selected

[Blocks editor] Add the list ordered and list unordered options in the block selector

---

packages/utils/pack-up/README.md
packages/utils/pack-up/package.json
packages/utils/pack-up/src/node/core/config.ts
packages/utils/pack-up/src/node/createBuildContext.ts
packages/utils/pack-up/src/node/createTasks.ts

* adds `exports` property to `pack-up` config
* adds `types` to a bundle config
* with a plugin like `email` we have a server & client package and each one needs their own runtime, we don't want to use the exports in the package.json instead we want to just use the bundles we've specified

feat: add exports to pack-up config

---

e2e/tests/content-manager/listview.spec.js
packages/core/admin/admin/src/content-manager/pages/ListView/index.js

Fixes #18251, by fixing a typo
To fix action button from not showing in empty lists
1. Go to 'Content Manager'
1. Click on a Collection that current has **0 entries**
1. Scroll down to List View
1. Action button should now be visible

fix: typo causing action button to not show in empty list

---

packages/core/upload/admin/src/hooks/useEditAsset.js

When the user tries to replace the media file and upload, the file isn't updated because it isn't uploaded.
This PR fixes the issue.
It is needed because when the user replaces their media file and uploads, it isn't uploading. 
1. Go to the media library directory
2. Click on assets
3. Click replace
4. Click Finish
Fixes #18250

fix: upload replaced media file

---

.github/workflows/tests.yml
packages/core/helper-plugin/declarations/@strapi/permissions.d.ts
packages/core/helper-plugin/src/components/CheckPagePermissions.tsx
packages/core/helper-plugin/src/components/CheckPermissions.tsx
packages/core/helper-plugin/src/features/RBAC.tsx
packages/core/helper-plugin/src/features/StrapiApp.tsx
packages/core/helper-plugin/src/hooks/useQueryParams.ts
packages/core/helper-plugin/src/hooks/useRBAC.ts
packages/core/helper-plugin/src/utils/hasPermissions.ts
packages/core/helper-plugin/src/utils/tests/hasPermissions.test.ts
packages/core/permissions/package.json
packages/core/permissions/packup.config.ts
packages/core/permissions/src/__tests__/permissions.engine.test.ts
packages/core/permissions/src/index.ts
packages/core/permissions/tsconfig.build.json
packages/core/permissions/tsconfig.eslint.json
packages/core/utils/package.json
packages/core/utils/packup.config.ts
yarn.lock

* uses `pack-up` to bundle `@strapi/permissions`
* remove `build:ts` from workflow because everytime we call build straight after which is the same command.
* makes it ESM / CJS and fixes the type exports 🥳
* automated testing should all pass still as we mix CJS & ESM already

chore: build strapi permissions with pack-up

---

.github/dependabot.yml

* adds `commit_message` settings to dependabot
* semantic commits are easier to scan a codebase for

chore: force dependabot to do semantic style commits

---

packages/core/admin/admin/src/hooks/index.js
packages/core/admin/admin/src/pages/SettingsPage/components/Tokens/Regenerate/index.js
packages/core/admin/admin/src/pages/SettingsPage/hooks/tests/useRegenerate.test.tsx
packages/core/admin/admin/src/pages/SettingsPage/hooks/useRegenerate.ts
packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/Regenerate/index.js
packages/core/helper-plugin/src/features/Notifications.tsx

Convert `useRegenerate` hook to TS. I've also moved the util from the global folder into the settings NS. In addition I had to update the return type of `useNotification`, because otherwise `toggleNotification` could be `undefined` and this would lead to a lot of unnecessary checks.

chore(admin): convert useRegenerate to TS

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js

Disables the toolbar's link button when the whole editor is disabled
Disable the editor in configure the view, then try to click the link button

[Blocks] Disable link button when editor is disabled

---

packages/core/strapi/src/core-api/service/collection-type.ts
packages/core/types/src/modules/entity-service/params/attributes.ts
packages/core/types/src/types/core-api/service.ts
packages/core/types/src/types/core/attributes/utils.ts
packages/core/types/src/types/core/entity/index.ts
packages/core/types/src/types/core/index.ts
packages/core/utils/src/types.ts

Add an Entity ID type, so it can be reused everywhere
```ts
import { Entity } from '@strapi/types'
type ID = Entity.ID
```

feat: add Entity Id type

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useModifiersStore.js

- Fixes the links relying on the browser's default color for <a> tags instead of using a value from the design system
- Fixes the blue color disappearing when using modifiers inside of a link
The new blue, even with modifiers inside:

[Blocks] Fix links colors

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js

Prevents code blocks from shrinking when there's a lot of content
Create a multi-line code block.
Add lots of empty lines below.
The code block should not be scrollable, it should retain its height

[Blocks] Fix code blocks shrinking

---

packages/core/admin/admin/src/content-manager/utils/schema.js

Fix the issue we had when we tried to save with empty Blocks field, we had the error : “This doesn't match the JSON format” 
Because otherwise we can't save the entry
Create new Blocks in CT, create new entry, try to save with empty Blocks field : “This doesn't match the JSON format”

[Blocks editor] Fix error message "This doesn't match the JSON format" when we click Save with an empty Block field

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/tests/useBlocksStore.test.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js
packages/core/admin/admin/src/translations/en.json

- Added Link popover save button disabled state
- Updated link text field placeholder after discussing with UX(Lucas)
There was no validation for empty state of link text and url fields, so save button disabled state added
When user do not enter link text or url in links popover, save button should be disabled.

[Blocks Editor] Link popover save button disabled state

---

packages/core/data-transfer/src/strapi/providers/local-source/assets.ts

Switches protocol based on url
Currently export is broken in some cases (can't reproduce when) because the `https` module is throwing an error on urls that start with "http:"
Run an export with files and it should work.
Note: I couldn't reproduce the original error, but the [reported issue](https://github.com/strapi/strapi/issues/17481) makes sense. So if someone can reproduce and then test that this PR fixes it, that would be great :)
Fixes https://github.com/strapi/strapi/issues/17481

[Data Transfer] Select http/https module based on protocol in local provider

---

packages/admin-test-utils/.eslintrc.js
packages/admin-test-utils/package.json
packages/admin-test-utils/src/fixtures/collection-types/index.ts
packages/admin-test-utils/src/fixtures/meta-data/index.ts
packages/admin-test-utils/src/fixtures/permissions/index.ts
packages/admin-test-utils/tsconfig.build.json
packages/admin-test-utils/tsconfig.eslint.json
packages/admin-test-utils/tsconfig.json
packages/core/helper-plugin/tests/utils.tsx
yarn.lock

* converts admin test-utils to use pack-up
* CJS / ESM & now we can export a universal test harness 👀

chore: pack-up admin-test-utils

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

Remove a screen debug inside a unit test
Because it is not needed, I forgot about it during the unit test implementation.

[RTE] remove screen debug

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

A few things to fix the issues with tests and make them easier to maintain. I think it's easier to review if you review the PR commit per commit. The first 3 are the most important:
Before we used a mix of `Transforms.select` and `Transforms.setSelection`. They're not exactly the same though, as [setSelection can only merge an update to an existing selection](https://docs.slatejs.org/api/transforms#transforms.setselection-editor-editor-props-partial-less-than-range-greater-than). It doesn't work if there wasn't a selection before, so it used to only work thanks to the side effects. `Transforms.select` works regardless of what is in other tests, so it's the one we should be using.
Note that `Transforms.select` requires _both_ the anchor and focus points every time (most of the time they're …

Remove side effects and warnings in Blocks editor tests

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useModifiersStore.js

Updated modifiers style 
Modifiers is using typography element which has its  own styling which gets applied, its overriding required styles
If selected block is heading and user tries to apply bold/italic/underline/strikethrough, no line height changes should be observed.

[Blocks Editor] Updated modifiers style

---

examples/getstarted/config/admin.js
examples/kitchensink-ts/config/admin.ts
examples/kitchensink/config/admin.js
packages/admin-test-utils/custom.d.ts
packages/admin-test-utils/src/environment.ts
packages/core/admin/admin/src/components/NpsSurvey/index.js
packages/core/admin/admin/src/index.js
packages/core/admin/server/controllers/admin.js
packages/generators/app/src/resources/files/js/config/admin.js
packages/generators/app/src/resources/files/ts/config/admin.ts

adds config option named *isNpsEnabled* what you can set to false what would disable it
So people can disable NPS for the whole strapi instance and not just for 1 browser.
Not having any config will make it pop up.
Having the config set to false will disable it.
fixes https://github.com/strapi/strapi/issues/17978

Allows users to disable NPS in strapi config.

---

packages/core/types/src/types/core/attributes/common.ts
packages/core/types/src/types/core/attributes/relation.ts

Replace the `Common.UID.Schema` constraint for `Attribute.Relation` target parameter with `Common.UID.ContentType`
Relations' target can only be a content type (components' UID are not allowed)

Types - Only allow content types as relation target (cannot target component)

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/tests/useBlocksStore.test.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useBlocksStore.js

Small UI fixes:
- Removes the default underline style that would be added by the browser on links by default
- Makes the link text the same size of the other text in a link's read-only the read-only popover
- Fix the colors of the blockquote component (text + border)
Unrelated to design: removes the Headings component that is no longer needed give the structure of useBlocksStore.
To match the designs

[Blocks] Multiple UI fixes to match the designs

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

Disables the link button when multiple block nodes are selected
Creating a link that spanned over multiple blocks created issues
Select mulitple blocks, the link button should be disabled
Keep your selection within the same block, the link button should be enabled

[Blocks] Disable link button when multiple blocks are selected

---

packages/core/helper-plugin/src/features/Notifications.tsx

* removes the default value for `title` from `Notification`
* _all_ messages no matter what said "success" which is a lie
* reported on Discord

fix(helper-plugin): notifications should not have a default for "success"

---

packages/core/admin/admin/src/components/GuidedTour/Homepage/tests/index.test.js
packages/core/admin/admin/src/content-manager/pages/EditView/Header/tests/index.test.js
packages/core/admin/admin/src/content-manager/pages/NoContentType/tests/index.test.js
packages/core/admin/admin/src/pages/AuthPage/components/Login/tests/BaseLogin.test.js
packages/core/admin/admin/src/pages/AuthPage/components/Oops/tests/index.test.js
packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
packages/core/admin/admin/src/pages/InternalErrorPage/tests/index.test.js
packages/core/admin/admin/src/pages/NotFoundPage/tests/index.test.js
packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/pages/App/ConfigureTheView/tests/__snapshots__/ConfigureTheView.test.js.snap
packages/utils/pack-up/src/node/tasks/vite/config.ts

* changes the `external` property in the vite config from a passed array to a function so it works better with `preserveModules`
* doesn't override `fileName` when we use `preserveModules` because that breaks the point of the config option.
* preserveModules either renamed everything to `indexXX` or had the folders nested according to where you called the command from
* unblocks #18341 
* unblocks #18339

fix(pack-up): redefine `external` to work better with presereModules and omit changing the fileName

---

packages/utils/pack-up/jest.config.js
packages/utils/pack-up/src/__tests__/cli.test.ts
packages/utils/pack-up/src/__tests__/node.test.ts
packages/utils/pack-up/tests/teardown.ts

* uses a global teardown to clean up `tmp` instead of `afterAll`
* it was cleaning up the entire `tmp` folder even if a test was running if `node` and `cli` started at the same time but finished at different times.
* unit tests should work at the same time
* reported on slack

test(pack-up): fix unit tests by using a global-teardown

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

Disable the modifier buttons when an image is selected and also the Link button.
Because bold, italic, underline and other styles are not needed for images and also the image can't be a link.
Create an image in the Block Rich Text Editor and select it, the bold, underline, strikethrough, italic buttons need to be disabled

[Blocks editor] Fix - When a image is selected we want to disable the modifier buttons

---

packages/core/admin/package.json
packages/core/admin/server/src/controllers/authentication.ts
packages/core/admin/server/src/controllers/permission.ts
packages/core/admin/server/src/domain/permission/index.ts
packages/core/admin/server/src/services/passport.ts
packages/core/admin/server/src/services/passport/local-strategy.ts
packages/core/admin/server/src/services/permission/engine.ts
packages/core/admin/server/src/services/permission/sections-builder/builder.ts
packages/core/admin/server/src/services/permission/sections-builder/handlers.ts
packages/core/admin/server/src/services/permission/sections-builder/section.ts
packages/core/admin/server/src/utils/index.d.ts
packages/core/permissions/src/domain/permission/index.ts
yarn.lock

Migrates passport and permission service to typescript.
I have found many type inconsistencies in the permission service, I think for now is best to omit them and see if it's really important for the other packages to handle have all the type variations handled.

feat: ts migrate admin permissions

---

packages/core/admin/scripts/build.js
packages/core/admin/webpack.config.dev.js

* Aliases helper-plugin in our dev mode
* uses `tsconfig.build` so it doesn't typecheck any of the tests when building e.g in the CI for experimental releases
* Admin could not build in experimental CI process
* Aren't you tired of rebuilding the helper-plugin for every change? 🥱 
* reported on slack

fix(admin): use tsconfig.build to build & alias helper-plugin in dev mode

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/hooks/useModifiersStore.js

Fix the case when you click on a modifier at the first rendering of the edit view
Because otherwise if you click directly one modifier button the app crashes
Open a new instance of a collection and then click the Bold button, now the app doesn't crash

[Blocks editor] Fix - Click on a Modifier when the editor selection is null crashes the app

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/BlocksInput/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/index.js

Blocks Static id removed, used ref instead on the wrapper
When scrollbar activated inside blocks, pressing enter should not shift main layout.

fix: blocks static id removed

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

Disable the modifier buttons and the link button when a code block is selected.
Because bold, italic, underline and other styles are not needed for code blocks and also the code block can't be a link.
Create a code block in the Block Rich Text Editor and select it, the bold, underline, strikethrough, italic and link buttons need to be disabled

[Blocks editor] Fix - When a code block is selected we want to disable the modifier buttons and the link button

---

nx.json
packages/core/admin/package.json
packages/core/helper-plugin/package.json

Run `nx repair` to correct nx configuration.
My purpose here is to reduce the differences with my personal fork, but I see no reason not to run this upstream as well. I don't see any major reason to run it at this point either... 🤷‍♂️
Testing with a CI should be enough.
None.

Run `nx repair` to correct nx configuration

---

CONTRIBUTING.md
packages/core/admin/admin/src/content-manager/pages/ListView/components/Body/index.js
packages/core/admin/admin/src/content-manager/pages/ListView/index.js

1. Wraps Checkbox and  Action Buttons components in a direct `<Td>` to correctly handle click events, seems that's the direct nesting it expects. 
3. Fixes incorrect `key` for mapped component (was displaying warning)
To solve bugs reported in https://github.com/strapi/strapi/issues/17880, https://github.com/strapi/strapi/issues/17942
1. In Content Manager, add a collection type that will cause horizontal scroll in Listing table
1. Attempt to delete or duplicate an entry by clicking the corresponding action buttons it should duplicate or prompt delete when corresponding buttons are clicked on
1. In Content Manager, Add enough items (maybe 10) or resize window to be short in height, scroll to bottom
2. Attempt to add a check to an item of the bottom, it should not scroll to top
Fixes …

fix: content manager action buttons not triggering and checkbox causing scroll

---

docs/docs/docs/05-utils/pack-up/02-config.mdx
packages/utils/pack-up/README.md
packages/utils/pack-up/src/node/core/config.ts
packages/utils/pack-up/src/node/createBuildContext.ts
packages/utils/pack-up/src/node/tasks/vite/config.ts

* adds `plugins` to pack-up config
* for the admin package we're moving from JS -> TSX but esbuild doesn't recognise JSX in JS, a plugin solves this, but this is the problem of the admin package, not pack-up & therefore having the option to pass a plugin would solve this 👍🏼

feat(pack-up): add the ability to pass plugins via the config

---

packages/core/strapi/src/index.ts

enforce module.exports = exports = strapiFactory so pack-up build will mix named and default exports in a backward compatible manner.
This is the only way to force the named and default exports to live together while using pack-up for now.  @joshuaellis if you have better I'll take it but search trough rollup issue I couldn't find an option for this.

Make named and default exports live together with ts migration

---

packages/core/content-type-builder/admin/src/components/TabForm/index.js

* replaces the default get with explicitly undefined not an empty string
* not every input wants a string
* AdvancedSettings in the CTB for DatePicker crashes because it receives an empty string
* Go to the CTB
* Edit a DateTimePicker field
* Click on advanced settings
* App should not crash
* resolves #18123
* resolves CONTENT-2000

fix(ctb): advanced settings DatePickers crash with empty string

---

.github/workflows/tests.yml

add needs: [build] to lint
to not build 2 times
run CI
#18489

chore(tooling): lint needs build

---

packages/core/admin/admin/src/components/Theme.tsx
packages/core/admin/admin/src/components/ThemeToggleProvider.tsx
packages/core/admin/admin/src/contexts/themeToggle.ts
packages/core/admin/admin/src/pages/ProfilePage/components/Preferences/index.js
packages/core/admin/admin/src/translations/en.json

Adds a third option to the theme picker, in addition to light and dark: "sync with system settings" (wording picked by @lucasboilly).
That option is picked by default, so the experience won't change for new Strapi users, except that if they later change their OS theme, they won't be stuck with the old one in Strapi.
It won't affect existing users, as they already have either light or dark in the localStorage. They have to go and save system settings on their profile page to get this functionality.
Demo time:
https://github.com/strapi/strapi/assets/8087692/6ebfedd8-b84a-46c7-b9fb-cef71e2699b2
Syncing with system theme has become a standard feature for web apps (Notion, GitHub, Google... even Jira). It enables you to toggle the theme for all your apps and websites at the same time. This …

feature(admin): sync theme with system theme

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js
packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/tests/index.test.js

Fixes the conversion of a list item to an image. The list is now split in 2, and the image is created outside of the list.
Images were created inside lists when converting list items. Therefore users could not save their content as the validations failed.
- convert a list item to an image
- do it from the end or the middle of a list
- do it inside a list item with links and modifiers
- add several images at once
- click on cancel in the media library

fix(blocks): prevent creating images inside a list

---

packages/core/admin/scripts/build.js
packages/core/content-releases/package.json
packages/core/strapi/src/core/loaders/plugins/get-enabled-plugins.ts
yarn.lock

* uses an ENV flag in node to decide whether or not it should include the plugin
* includes `@strapi/strapi` as a devDep because it's a peer dep
* allows us to merge into main without it affecting users
* I think in the future it would be great if we had a global `strapi.config` because you could just add a flag that way which is a bit nicer, but for now i think this works, I tried to keep the name clear and basic af, I think the format for most things could just be `FEATURE_FLAG_XXX` 🤷🏼‍♀️ but I mean we're not going to document this so I don't think it matters _too_ much.

core(content-releases): add env flag to include plugin

---

packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeList/index.js
packages/core/content-type-builder/admin/src/components/AttributeOptions/CustomFieldsList/index.js
packages/core/content-type-builder/admin/src/components/AttributeOptions/index.js
packages/core/content-type-builder/admin/src/components/AttributeOptions/tests/__snapshots__/index.test.js.snap
packages/core/content-type-builder/admin/src/components/AttributeOptions/utils/getPadding.js
packages/core/content-type-builder/admin/src/components/FormModal/utils/getAttributesToDisplay.js

2 design changes on the CTB attribute type picker modal:
- **Harmonize the grid spacings**. The current/previous version makes the items very close vertically, and far apart horizontally. It doesn't look balanced, and looks like the grid is meant to be read by columns instead of read row by row.
- **Change attributes order**. The live version didn't match the designs before, which were organized to have icons of the same color on the same rows. The markdown field is also moved to the last item as it will be deprecated in v5 and the blocks field is now stable.
All the changes were checked by @lucasboilly ([see figma file](https://www.figma.com/file/PICiE8O4NLrHO1lhJftLdE/Strapi-CMS---UI-Kit-%F0%9F%A7%A9?type=design&node-id=16466%3A34126&mode=design&t=e7hjzGC9UY1iJo12-1))
Users creating an …

fix(ctb): update attribute picker spacings

---

packages/core/strapi/src/Strapi.ts

Reintroduced deleted strapi.hooks ( content-types.afterSync )   that was removed during a merge conflict.

fix: re add deleted afterSync hook

---

package.json
yarn.lock

Add react type resolution on root package json to fix:

fix: add react resolutions into root package json

---

packages/core/types/src/types/__tests__/definitions/utils/object.d.ts
packages/core/types/src/types/__tests__/utils/object.test.ts
packages/core/types/src/types/utils/object.ts

Adds a replace type utility.
```
type X = Replace<{ foo: number, bar: number}, { foo: string }>
^?  { foo: string, bar: number }
```

feat: Replace type

---

packages/utils/pack-up/src/node/build.ts

* pack-up now by default sets `NODE_ENV` to production _unless_ it's set already
* vite doesn't set process.env.NODE_ENV, it does set values on `import.meta.env`, but `react` doesn't look at those 🙃 
* build the color-picker without this PR and you'll see we're trying to import the dev jsx files
* with this pr we correctly import the non-dev jsx file
* resolves #18575

fix(pack-up): set NODE_ENV if it's not already set

---

examples/getstarted/config/admin.js
packages/core/admin/server/services/role.js

Replace fast-deep-equal with lodash/fp isEqual
fast-deep-equal isn't needed
RBAC permissions updates (adding/removing permissions) should still work exactly as before

[v5] Replace fast-deep-equal with lodash/fp isEqual

---

.github/workflows/skipped_tests.yml
.github/workflows/tests.yml
README.md
packages/core/database/src/dialects/dialect.ts
packages/core/database/src/dialects/mysql/index.ts
packages/core/database/src/entity-manager/regular-relations.ts
packages/core/strapi/README.md
packages/core/strapi/src/Strapi.ts

Removes support for mysql v5 in CI and documentation.
Mysql v5 is EOL Oct 2023 and starting in Strapi v5 we will only support Mysql v8+
The only code I changed was removing `supportsWindowFunctions` from the mysql dialect because it was just a check for mysql5. So test that mysql dialect didn't somehow break, but otherwise if tests pass I think it's good.
Docs PR: https://github.com/strapi/documentation/pull/1887

[v5] Remove support for MySQL v5

---

packages/core/admin/admin/src/content-manager/components/BlocksEditor/Toolbar/index.js

- Changed the top and bottom padding of the _SingleSelect_
- Removed the margin-left on the _ToggleGroup_
To match the mockups

Fixed padding issues in the toolbar

---

packages/core/content-releases/admin/src/index.ts
packages/core/content-releases/admin/src/pages/Releases.tsx
packages/core/content-releases/admin/src/pluginId.ts
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/admin/src/translations/tests/plural.test.ts
packages/core/types/src/types/core/plugins/config/strapi-admin/index.ts

Create the Link in the Sidebar in the plugin section and also the two Routes to the
- /admin/plugins/content-releases the ListView page
- /admin/plugins/content-releases/:releaseId the Detail Page
You need to have an Enterprise License
In the sidebar you can see in the Plugins section the "Releases" link that links to the admin/plugins/content-releases page
You can also navigate the two pages directly from the browser url
In the two different pages we want to show just the strings
TODO: This is the ListPage
TODO: This is the DetailsPage

feat(content-releases): Add sidebar link and routes to the ListView page and the detail page

---

packages/cli/create-strapi-app/src/index.d.ts
packages/core/admin/admin/src/hooks/useSettingsMenu/index.js
packages/core/admin/package.json
packages/generators/app/src/create-quickstart-project.ts

* adds `index.js` & `index.d.ts` to the files array of `@strapi/admin`
* adds the additionalDeps to quick start projects
* ensures we always unwrap the CE settings links for settings otherwise they're undefined
* admin was not shipping with a file it required
* the `main` aim counterpart to #18623

chore(admin): fix exports & settings links in CE

---

packages/core/admin/_internal/node/core/plugins.ts

* passes `env` from `@strapi/utils` to plugin configuration functions
* preserves existing functionality
* fixes https://github.com/strapi/strapi/issues/18649

fix(core/admin): missing env utilities

---

packages/core/admin/_internal/node/core/dependencies.ts
packages/core/admin/_internal/node/core/plugins.ts
packages/core/admin/_internal/node/staticFiles.ts
packages/core/admin/package.json
packages/core/content-type-builder/package.json
packages/core/data-transfer/src/commands/data-transfer.ts
packages/core/email/package.json
packages/core/helper-plugin/package.json
packages/core/strapi/package.json
packages/core/strapi/packup.config.ts
packages/core/strapi/src/admin.ts
packages/core/strapi/src/commands/actions/plugin/build-command/action.ts
packages/core/upload/package.json
packages/generators/generators/src/templates/js/plugin-package.json.hbs
packages/generators/generators/src/templates/ts/plugin-package.json.hbs
packages/plugins/cloud/package.json
packages/plugins/color-picker/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json
yarn.lock

* adds `esbuild` as a dep to the `admin` package
* sets peerDeps to match the `design-system` which is lower than what we were targeting incl. on templates so all packages are aligned
* re-exports admin from the strapi package and no longer tries to include the core plugins on a user app level
* upgrading projects couldn't resolve esbuild
* peer dep issues in npm projects
* it's NPM specific but the admin package is not at the same level in the node_modules so you can't import it. Because a user has `@strapi/strapi` declared, we might as well use that and re-export it. We can also import the core plugins there meaning we're another step closer to PNPM working.
* install a project at `4.15.0`
* upgrade to experimental manually
* experimental build –> …

fix(admin): build pipeline & deps

---

packages/core/admin/_internal/node/develop.ts
packages/core/admin/_internal/node/webpack/watch.ts

* Closes webpack watcher on reloads
* Avoid having background rebuild slowing down the app because the compiler / dev-middleware was not being terminated by the parent process
* resolves CONTENT-2036

fix(admin): close webpack watch on reload

---

packages/core/admin/_internal/node/webpack/config.ts

* set up webpack config to separately handle tsx & jsx code
* CKEditor custom field plugin doesn't work without it

fix(admin): use appropriate loader between jsx and tsx

---

examples/getstarted/config/server.js
packages/core/strapi/src/services/server/http-server.ts

Allows user to set http server configuration options
The specific issue is that Strapi can no longer accept any file uploads that take longer than the default Node 18+ http server requestTimeout, which is 5 minutes.
This allows users to configure that setting to be whatever value they wish.
In addition to that, users will now be able to configure any option available in http.ServerOptions
Try setting some values in config/server.ts http.serverOptions and see that they are passed through to the http.createServer
Fixes https://github.com/strapi/strapi/issues/18543
[Documentation PR](https://github.com/strapi/documentation/pull/1903)

feat: allow passing http serverOptions from config

---

packages/core/admin/_internal/cli/index.ts
packages/core/admin/_internal/node/createBuildContext.ts
packages/core/admin/_internal/node/develop.ts
packages/core/admin/_internal/node/webpack/watch.ts

* adds `watch-admin` flag to trigger the watching middleware attaching process
* only lower powered machines the current reload set up is very slow due to webpack re-compiling, this is intended to be a patch until we solve the issue.

refactor(admin): add watch-admin flag

---

packages/core/types/src/types/core/attributes/blocks.ts

Provides precise types for blocks attributes, instead of just using the object type
We'll need these types in 2 places:
- the blocks editor, as we're starting to convert it to TS
- the blocks renderer

chore: add precise types to blocks attribute

---

packages/core/admin/admin/src/pages/SettingsPage/pages/ReviewWorkflows/SalesPage.js

Fix the link to our website pricing page which was incorrect due to an extra letter :/
To make the link work as expected (redirecting to our pricing page instead of 404)
Click on the link, it should redirect you to the pricing page of our website :)

Fix: website link containing a typo

---

packages/admin-test-utils/package.json
packages/core/content-type-builder/package.json
packages/core/upload/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json

Adds a missing prepublish script in some packages
To publish experimental correctly

fix: add missing prepublish script

---

packages/core/types/src/modules/documents/document-service.ts
packages/core/types/src/modules/documents/index.ts
packages/core/types/src/modules/documents/middleware.ts
packages/core/types/src/modules/documents/params/attributes.ts
packages/core/types/src/modules/documents/params/data.ts
packages/core/types/src/modules/documents/params/document-service.ts
packages/core/types/src/modules/documents/params/fields.ts
packages/core/types/src/modules/documents/params/filters/index.ts
packages/core/types/src/modules/documents/params/filters/operators.ts
packages/core/types/src/modules/documents/params/index.ts
packages/core/types/src/modules/documents/params/pagination.ts
packages/core/types/src/modules/documents/params/populate.ts
packages/core/types/src/modules/documents/params/search.ts
packages/core/types/src/modules/documents/params/sort.ts
packages/core/types/src/modules/documents/params/status.ts
packages/core/types/src/modules/documents/plugin.ts
packages/core/types/src/modules/documents/result.ts
packages/core/types/src/modules/documents/result/document-service.ts
packages/core/types/src/modules/documents/result/index.ts
packages/core/types/src/types/shared/document-service.d.ts
packages/core/types/src/types/shared/index.ts

Document Service types were mostly reused from the entity service before, we now need to add new parameters (locale and status) and so it became necessary to duplicate the typings and adapt them to work for the document service.
@innerdvations @Convly we will need to be careful if we refactor the entity service types, and make sure the changes are also reflected into the document service :)
TLDR: This PR allows the use of locale and status paraameters in all the strapi.documents methods:
```ts
strapi.documents(ARTICLE_UID).create({
locale: 'fr',
status: 'draft',
data: { title: 'Article' },
});
```
It also provides the return types of the document repository methods

feat: strongly type document repository and add status and locale params

---

packages/plugins/i18n/server/constants/iso-locales.json
packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap

Added Dhivehi (Maldives) to the iso-locales.json
Add Dhivehi language to Strapi localization. Country code taken from [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#:~:text=Divehi%2C-,Dhivehi,-%2C%20Maldivian)
Same as other locales

feat: add dhivehi localization to strapi

---

packages/core/admin/package.json
packages/core/helper-plugin/package.json
packages/core/upload/package.json
yarn.lock

due to https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
* updates axios to 1.6.0
* https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
* closes #18744
* closes #18767
* closes #18766
* closes #18765

chore(deps): update axios to 1.6.0

---

docs/docs/docs/01-core/admin/06-commands/01-build.md
docs/docs/docs/01-core/admin/06-commands/02-develop.md
examples/getstarted/src/admin/app.example.js
examples/getstarted/src/admin/app.js
packages/core/admin/_internal/node/core/admin-customisations.ts
packages/core/admin/_internal/node/core/plugins.ts
packages/core/admin/_internal/node/createBuildContext.ts
packages/core/admin/_internal/node/staticFiles.ts
packages/core/admin/_internal/node/webpack/config.ts
packages/core/admin/admin/src/render.ts
packages/core/strapi/src/admin.ts

* adds `app.js` as an import argument to the `renderAdmin` function
* checks that the user webpack config is a typeof function otherwise show an error explaining
* converts system paths to node_module paths so local plugins work on windows
* App customisations were not applied to user apps
* users were reporting that their `webpack user config` was not a function but being called as such
* local plugin paths on windows were broken
* resolves #18758
* resolves #18762
* resolves #18723
* resolves #18719
* resolves #18742
* resolves #18752

fix(admin): admin build errors

---

docs/docs/docs/01-core/admin/06-commands/01-build.md
docs/docs/docs/01-core/admin/06-commands/02-develop.md
examples/getstarted/src/admin/app.example.js
examples/getstarted/src/admin/app.js
packages/core/admin/_internal/node/core/admin-customisations.ts
packages/core/admin/_internal/node/core/plugins.ts
packages/core/admin/_internal/node/createBuildContext.ts
packages/core/admin/_internal/node/staticFiles.ts
packages/core/admin/_internal/node/webpack/config.ts
packages/core/admin/admin/src/render.ts
packages/core/strapi/src/admin.ts

* fixes admin build errors
* mirrors #18764 
* cherry picked from `main`

fix(admin): admin build errors (#18764)

---

examples/getstarted/jsconfig.json
examples/getstarted/src/admin/app.js
packages/core/admin/_internal/node/core/admin-customisations.ts
packages/core/admin/_internal/node/core/files.ts
packages/core/admin/_internal/node/staticFiles.ts

Upgrade the laodFile util to support required feature.
Fix an issue with custom app code
create a src/admin/app.(ts|tsx|js|jsx) file with jsx code in it

fix(admin): load app custom with jsx and allow more extensions

---

packages/core/admin/admin/src/pages/ProfilePage.tsx
packages/core/admin/admin/src/pages/tests/ProfilePage.test.tsx
packages/core/admin/shared/contracts/users.ts

Changes on the profile page:
- restores the current password input, as it it needed by the backend to change password
- avoids passing an empty password string if the user didn't touch the password input. This is what prevented users from saving
To allow users to save their changes on the profile page.
Go to the profile page, make changes (both with and without password changes), then try to save.
fixes #18678

fix(admin): restore current password input on profile page

---

packages/providers/upload-aws-s3/src/__tests__/utils.test.ts
packages/providers/upload-aws-s3/src/index.ts
packages/providers/upload-aws-s3/src/utils.ts

It makes the accessKeyId and secretKeyId optional in the AWS S3 provider because these credentials can be omitted when strapi is deployed on and EC2 instance or on another AWS service that supports IAM Profiles instead of accessKeyId and secretAccessKey.
To support other types of authentication in the AWS provider
Check that if you don't pass the credentials and have an EC2 instance with another type of authentication configured, the provider works as expected
https://github.com/strapi/strapi/issues/18718

Make AWS Credentials optional

---

packages/core/admin/_internal/node/core/admin-customisations.ts
packages/core/admin/_internal/node/core/files.ts
packages/core/admin/_internal/node/core/plugins.ts
packages/core/admin/_internal/node/createBuildContext.ts
packages/core/admin/_internal/node/staticFiles.ts

* creates some utility functions for handling windows system vs module paths since they need to be handled especially unlike macos/linux
* on windows, the `app.js` file was not being imported correctly
* closes #18795

fix(admin): windows files paths do not make for module paths

---

.github/workflows/changeFreeze.yml

Adds a workflow that checks all PR authors to see if they belong to the `@strapi/team` org team, if they aren't it will post a message on the PR asking for the reason why this should be merged before we close it.
Change Freeze for v5 but coded so that we can simply turn it on or off using a repo variable
Need to create the following:
- a PAT under repo secrets called `CHECK_OWNERSHIP_TOKEN` with at minimum the admin:org -> read:org permission (to read the team membership since not everyone on our team has public membership enabled)
- a repo var called: `CHANGE_FREEZE_ENABLED` set to `true`
#18618

chore(repo): Add Change Freeze workflow

---

api-tests/core/strapi/document-service/create.test.api.ts
api-tests/core/strapi/document-service/delete.test.api.ts
api-tests/core/strapi/document-service/find-first.test.api.ts
api-tests/core/strapi/document-service/find-many.test.api.ts
api-tests/core/strapi/document-service/find-one.test.api.ts
api-tests/core/strapi/document-service/middlewares.test.api.ts
api-tests/core/strapi/document-service/update.test.api.ts
packages/core/strapi/src/services/document-service/document-repository.ts
packages/core/strapi/src/services/document-service/index.ts
packages/core/strapi/src/services/document-service/middlewares.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/draft-and-publish.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/index.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/locales.ts
packages/core/strapi/src/services/document-service/middlewares/index.ts
packages/core/types/src/modules/documents/index.ts
packages/core/types/src/modules/documents/middleware.ts
packages/core/types/src/modules/documents/params/document-service.ts
packages/core/types/src/modules/documents/params/index.ts
packages/core/types/src/modules/documents/params/populate.ts

Run doc service middlewares with a priority, the higher the number the earlier it will be executed.
```ts
strapi.documents(ARTICLE_UID).use(
'findMany',
(ctx, next) => { },
// Runs last
{ priority: strapi.documents.middlewares.priority.LAST }
);
strapi.documents(ARTICLE_UID).use(
'findMany',
(ctx, next) => {},
// Runs first
{ priority: strapi.documents.middlewares.priority.FIRST }
);
```

feat: add priority to middlewares

---

.github/workflows/checks.yml

* sets up the checks workflow to run against `develop` branches
* since this is our default working branch, i think we should continue to enforce the checks (which are still required in GH)

chore(actions): run checks workflow on develop branches

---

.github/workflows/tests.yml
package.json
packages/utils/pack-up/tests/spawn.ts

* adds `YARN_ENABLE_IMMUTABLE_INSTALLS` to env of workflow under `test:unit` – NOTE, including it here will ensure it's still caught for unintended issues e.g. in the build step
* lets pack-up tests run correctly

test(pack-up): add ENV to allow immutable installs in yarn 4

---

docs/docs/docs/01-core/content-releases/00-intro.md
docs/docs/docs/01-core/content-releases/01-backend.md
docs/docs/docs/01-core/content-releases/_category_.json

Initialize the contributor documentation and documents everything for the backend currently on the feature branch
So we can continue documenting the feature as we develop
Just give it a read

chore(docs): initialize contributor docs for content releases

---

packages/core/content-type-builder/admin/src/components/SelectComponents/index.js

It adds protection for possibly undefined values in SelectComponents since the default value given in [packages/core/content-type-builder/admin/src/components/TabForm/index.js](https://github.com/strapi/strapi/blob/44fafdc341f0100dd2c63261c252c0ecb67bc939/packages/core/content-type-builder/admin/src/components/TabForm/index.js#L38-L41):
```
/**
* Use undefined as the default value because not every input wants a string e.g. Date pickers
*/
const value = get(modifiedData, input.name, undefined);
```
Right now the CTB throws an error when creating a component inside a Dynamic Zone.
Try to create a component inside a dynamic zone in the CTB.
Closes https://github.com/strapi/strapi/issues/18633
Closes https://github.com/strapi/strapi/issues/18665

fix: protect undefined values on SelectComponents

---

api-tests/core/strapi/document-service/clone.test.api.ts
api-tests/core/strapi/document-service/create.test.api.ts
api-tests/core/strapi/document-service/discard-draft.test.api.ts
api-tests/core/strapi/document-service/update.test.api.ts
packages/core/strapi/src/services/document-service/document-repository.ts
packages/core/strapi/src/services/document-service/index.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/draft-and-publish.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/index.ts
packages/core/strapi/src/services/document-service/middlewares/defaults/locales.ts
packages/core/types/src/modules/documents/document-service.ts
packages/core/types/src/modules/documents/index.ts
packages/core/types/src/modules/documents/middleware.ts
packages/core/types/src/modules/documents/params/document-service.ts
packages/core/types/src/modules/documents/result/document-service.ts

Return affected documents on clone/publish/unpublish
Created this in the meantime, we might want to discuss this more

feat: return affected documents on document service

---

packages/core/admin/admin/src/content-manager/components/BlocksInput/Blocks/tests/Wrapper.tsx

Puts modifiers on the Blocks context in a Wrapper component 
To fix the build
CI should pass
No idea why this didn't make #18802 fail

fix(blocks): add modifiers to test provider

---

packages/core/strapi/src/Strapi.ts
packages/utils/logger/src/constants.ts

Sets the default log level for strapi.log to 'info'
'info' is a more sensible default for logging; if someone wants to add debug info, they can still set the logger config parameter.
I can manage these as later tasks if we just want to merge and get the annoying logs out of the way.
- debug logs should no longer appear in the server log by default
- debug logs should still be available if you create a config/logger.js that exports { level: 'debug' }

[v5] ] Set default log level to 'info'

---

packages/utils/upgrade/src/__tests__/core/version.test.ts
packages/utils/upgrade/src/cli/commands/upgrade.ts
packages/utils/upgrade/src/cli/index.ts
packages/utils/upgrade/src/core/transforms-loader.ts
packages/utils/upgrade/src/core/version-parser.ts
packages/utils/upgrade/src/core/version.ts
packages/utils/upgrade/src/tasks/upgrade.ts
packages/utils/upgrade/src/types.ts

- Default the CLI's target to `next`
- Add the `exact` mode, which allows targeting a single upgrade when specifying a target in the form "x.x.x"
- Accept versions lower than the current one in `exact` mode
- Add the `current` and `next` target options
- Modify the behavior of `major`, `minor` and `patch` upgrades
- `major` now targets the current or next `major` (current +1), + its latest `minor` and`patch`
- `minor` now targets the current major, the current or next `minor` (current +1), + its latest `patch`
- `patch` now targets the current major, the current minor and the current patch + 1
- Making the targeting strategy more consistent and user friendly
- Allow running atomic upgrades
- Allow running previous upgrades

[Upgrade Tool] Version Targeting Strategy V2

---

packages/plugins/documentation/server/services/helpers/utils/clean-schema-attributes.js

The generated `full_documentation.json` contains an error in the `localizations` property. The `localizations` property only shows up when [strapi-plugin-populate-deep](https://www.npmjs.com/package/strapi-plugin-populate-deep) is also installed, but the issue is in the documentation plugin, not [strapi-plugin-populate-deep](https://www.npmjs.com/package/strapi-plugin-populate-deep).
The edited line is only hit once in the debugger and patching it seems to do exactly what I want and nothing else. It's used in production at our company.
Without this, the localization field in the schema doesn't match the actual api response. The api response contains an id & attributes, which then contain the actual data. The schema makes it seem like the localization field already contains the data.
Api …

fix(documentation): use correct localization schema

---

packages/utils/upgrade/README.md
packages/utils/upgrade/resources/transforms/4.16.0/console.error-to-console.debug.code.ts

Adds contributor documentation for writing transforms for the ugprade tool
In Strapi v5, the developers who create PRs for breaking changes are required to write their own accompanying code migrations to ease the transition, know as Transforms or Codemods. These are their stories.
Read it
None

[Upgrade tool] Add documentation

---

packages/core/admin/_internal/node/webpack/config.ts
yarn.lock

Removes 381 duplicates (semver) compatible dependencies with highest strategy. This is a follow-up of https://github.com/strapi/strapi/pull/16764 (see explanation). It was done with the built-in `yarn dedupe`command.
<details>
<summary>Expand the list of duplicates</summary>
```
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ @babel/compat-data@npm:^7.19.0 can be deduped from @babel/compat-data@npm:7.19.0 to @babel/compat-data@npm:7.22.9
➤ YN0000: │ @babel/compat-data@npm:^7.20.5 can be deduped from @babel/compat-data@npm:7.20.14 to @babel/compat-data@npm:7.22.9
➤ YN0000: │ @babel/helper-environment-visitor@npm:^7.16.7 can be deduped from @babel/helper-environment-visitor@npm:7.16.7 to @babel/helper-environment-visitor@npm:7.22.20
➤ YN0000: │ @babel/helper-environment-visitor@npm:^7.18.9 can …
```

chore(lock): deduplicate dependencies

---

packages/core/content-manager/shared/contracts/collection-types.ts
packages/core/content-manager/shared/contracts/single-types.ts

- Adds metadata type to the content manager collection-type & single types endpoints
- Change `Entity` response to `Document` response.

feat: D&P Admin contracts with metadata

---

packages/core/content-manager/server/src/controllers/collection-types.ts
packages/core/content-manager/server/src/services/document-metadata.ts
packages/core/content-manager/server/src/services/entity-manager.ts
packages/core/content-manager/server/src/services/index.ts

Returns metadata information as described in our admin [API contracts](https://github.com/strapi/strapi/blob/v5/draft-and-publish/packages/core/content-manager/shared/contracts/single-types.ts).
To not break the content-manager, instead of returning 
```ts
type Response =  {
data: Document,
meta: DocumentMetadata
}
```
I am returning
```ts
type Response =   Document & { __meta__:  DocumentMetadata}
```
I will remove this once @joshuaellis starts working on the ui.

feat: Content manager document metadata

---

.github/workflows/tests.yml

* changes `unit_front` workflow to use `node20`
* turns out there were performance issues in node with jest – this could explain why both sets have been "poor", `20.10` supposedly fixes this

chore(workflows): update unit_front to use node 20

---

docs/docs/docs/01-core/content-releases/01-backend.md
packages/core/content-releases/server/src/constants.ts
packages/core/content-releases/server/src/controllers/release-action.ts
packages/core/content-releases/server/src/routes/release-action.ts
packages/core/content-releases/server/src/services/release.ts
packages/core/content-releases/shared/contracts/release-actions.ts

- Add the endpoint to delete a release-action
- To remove release actions from a release
- Make sure you have a release with some release actions
- Make sure you have the id for the release and the action you want to delete
- Make a DELETE request to `/content-releases/:releaseId/actions/:actionId
- It should return the release action that was deleted
- Confirm it was deleted in the db
- Check a role that doesn't have permissions cannot make the request and that permissions can be given

feat(content-releases): add endpoint to remove release action from release

---

packages/core/utils/package.json
packages/core/utils/src/__tests__/query-populate.test.ts
packages/core/utils/src/__tests__/test-utils.ts
packages/core/utils/src/traverse/query-populate.ts
yarn.lock

Fixes deep populate issue with a wildcard notation
It's a regression introduced by a previous PR
- Create a dynamic zone with at least two components, add relational field in at least one of the components
- attempt to fetch with following query `http://localhost:1337/api/countries?populate[dynamiczone][populate]=*`
- relational fields should be populated
fixes #17654

fix deep query populate issue on dynamic zone

---

packages/core/permissions/src/engine/abilities/casl-ability.ts
packages/core/permissions/src/engine/hooks.ts
packages/core/permissions/src/engine/index.ts
packages/core/permissions/src/types.ts
packages/core/types/src/index.ts
packages/core/types/src/types/core/permissions/index.ts

* stops `@strapi/permissions` from importing from `@strapi/types` but keeps the types the latter was exporting.
* circular dependency caused NX to fail the build – see [this](https://github.com/strapi/strapi/actions/runs/7106214568/job/19345298823#step:5:484)
* the CI should actually build

fix(permissions): circular dependency

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseActionOptions.tsx
packages/core/content-releases/admin/src/components/tests/CMReleasesContainer.test.tsx
packages/core/content-releases/admin/src/services/release.ts
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/server/src/services/release.ts

- Lists all Releases that have the content type entry
- To see all the releases containing a specific entry
- Go to the CM edit view with permissions to read releases
- Make sure you have multiple releases with the same entry attached (or use the add to release button)
- You should see the releases containing the entry to are on and it should say what type of action will be performed

feat(content-releases): list releases containing content type entry

---

packages/core/content-releases/server/src/controllers/release.ts
packages/core/content-releases/server/src/routes/release.ts
packages/core/content-releases/server/src/services/__tests__/release.test.ts
packages/core/content-releases/server/src/services/release.ts
packages/core/content-releases/shared/contracts/releases.ts

Add a new `/content-releases/:id/` delete endpoint to delete a release.
Make sure you have the content-releases feature enabled with a EE project.
1. Make a request to DELETE `/content-releases/:releaseId`
2. Release should exists, if not it should throw an error
3. Release should not be published, if not it should throw an error
4. If all good, it should return the details of the release

feat(content-releases): Delete a Release

---

packages/utils/pack-up/README.md

Makes some changes to the pack-up readme about the name of the config file
I think it was wrong. `packup.config.ts` is the file name used throughout the monorepo. And I tried on another repo using pack-up (the renderer), the config wasn't picked up unless I called it `packup.config.ts`

doc(pack-up): fix config file name in readme

---

packages/generators/app/src/resources/dot-files/common/gitignore

* adds the runtime directory for strapi apps to the generated gitignore
* nicer DX – they don't need to commit this
* raised on slack

chore(generator): add runtime dir to gitignore

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseActionOptions.tsx
packages/core/content-releases/admin/src/components/tests/ReleasActionOptions.test.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/pages/tests/ReleaseDetailsPage.test.tsx
packages/core/content-releases/admin/src/services/release.ts
packages/core/content-releases/admin/src/translations/en.json

⚠️ Wait for Simone's PR to be merged first, and then we can merge his last updated work here and change this PR to point into feature branch
This PR add the action column to the details view, in this column you can change the type of the action (publish or unpublish)
You should have an EE license and the feature enabled by setting contentReleases as enabled on the feature file.
```
// myproject/config/features.js
future: {
contentReleases: true
},
});
```
1. Then go to a release with actions (Create one and assign actions to it)
2. You should see a new column with the action 
3. You can change the action and the change should be reflect on the UI

feat(content-releases): Add action column to details view

---

test/.eslintrc
test/scripts/run-e2e-tests.js

adds an eslintrc to the /tests directory
Test scripts weren't having code formatting applied

chore: lint test scripts

---

packages/core/content-releases/server/src/constants.ts

Change permissions wording to use "entry" instead of "action"
It's confusing
Test the permissions work the same. Give read and add entry to release to an Editor for example

chore(content-releases): update permissions wording

---

packages/providers/upload-local/package.json
packages/providers/upload-local/src/__tests__/upload-local.test.ts
packages/utils/upgrade/src/cli/commands/upgrade.ts
packages/utils/upgrade/src/cli/index.ts
packages/utils/upgrade/src/cli/types.ts
packages/utils/upgrade/src/modules/format/formats.ts
packages/utils/upgrade/src/modules/upgrader/upgrader.ts
packages/utils/upgrade/src/tasks/upgrade/requirements/common.ts
packages/utils/upgrade/src/tasks/upgrade/upgrade.ts
yarn.lock

- Update logs to display more information about the upgrade process
- Add a `-y, --yes` CLI option for `major`, `minor`, and `patch` commands (cc @pwizla)
- Default to `false`, automatically answers `yes` to every prompt (_for now, it'll basically ignore optional requirements and proceed anyway_)
- Make `major` upgrade requirements required (were optional up until now)
- Various small improvements around the code quality
- Update some logs to make them more user-friendly
Quality of life improvements
- The `yes` should ignore prompts & answer yes anyway (easy to test with the GIT_CLEAN requirement, the warning should be prompted but the process should continue)
- The major requirements should now be required, and the `upgrade major` process should fail (as there are no V5 to upgrade to …

[Upgrade Tool] Chores / Quality of Life Improvements

---

packages/core/admin/admin/src/content-manager/components/Relations/RelationInput.tsx
packages/core/admin/admin/src/content-manager/components/Relations/tests/__snapshots__/RelationInput.test.tsx.snap
packages/core/admin/admin/src/content-manager/components/Relations/tests/useRelation.test.tsx
packages/core/admin/admin/src/content-manager/components/Relations/useRelation.ts

This PR addresses and fixes two specific issues: #17391 and #18257. The main focus is on resolving the problem related to searching within a relational input. 
The changes include using `"none"` for autocomplete and updating the filter logic to `_filter: '$containsi'`
Additionally, it enhances the functionality by passing the `textValue` to the `onSearch` function in the `handleMenuOpen` handler, ensuring proper search results when the menu is opened with typing.
The issues #17391 and #18257 highlighted a problem with searching in a relational input. This PR aims to solve this issue by making necessary changes and further improves the user experience by passing the text value to the `onSearch` function.
To verify the behavior of this fix, follow these steps:
1. Set up the environment with …

fix(content-manager): search relations with contains not startsWith

---

packages/core/admin/admin/src/content-manager/components/RelationInput/RelationInput.js
packages/core/admin/admin/src/content-manager/components/RelationInput/tests/__snapshots__/RelationInput.test.js.snap
packages/core/admin/admin/src/content-manager/hooks/useRelation/tests/useRelation.test.js
packages/core/admin/admin/src/content-manager/hooks/useRelation/useRelation.js

actual PR – #19043
* backports the fix made in [#19043](https://github.com/strapi/strapi/issues/19043)

chore: backport relations search fix

---

packages/core/admin/server/services/__tests__/user.test.js
packages/core/admin/server/services/user.js

Use a case-insensitive lookup for admin users in the findOneByEmail method of the user service.
See #16982
- Manually by executing `yarn strapi console` and then making a manual query to the admin user service.
- Or just by running the unit tests
fix https://github.com/strapi/strapi/issues/16982

Fix issues with case sensitive email addresses sent by some SSO providers

---

packages/core/admin/admin/src/content-manager/contexts/models.ts
packages/core/admin/admin/src/content-manager/hooks/useContentManagerInitData.ts
packages/core/admin/admin/src/content-manager/pages/App.tsx
packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.jsx
packages/core/admin/admin/src/tests/StrapiApp.test.tsx
packages/core/admin/admin/tests/utils.tsx

Refactor useContentManagerInitData to use react query and remove ModelsContext

[Content manager] Refactor useContentManagerInitData to remove ModelsContext

---

packages/core/strapi/src/Strapi.ts
packages/core/strapi/src/factories.ts

Flag custom core controller to keep track of them
Update the sent telemetry group properties on server's start to include the number of custom controllers
Customize the controller of an API endpoint (adding the second parameter to the createCoreController() function)
Check that the number of customized controllers passed to didStartServer is increased by one unit
close https://github.com/strapi/strapi/pull/17640

[Telemetry] Custom Controllers Count

---

packages/core/types/src/modules/entity-service/params/attributes/index.ts
packages/core/types/src/modules/entity-service/params/filters/index.ts
packages/core/types/src/modules/entity-service/params/sort.ts
packages/core/types/src/types/utils/array.ts
packages/core/utils/package.json

Fixed the `sort` and `filters` object notations for the entity service causing invalid inference, thus breaking the resulting types.
[ #18263 - Populate generated types doesn't work with filter on entityService](https://github.com/strapi/strapi/issues/18263)
`findMany` in the entity-service is defined as (simplified version):
```ts
findMany<
TContentTypeUID extends Common.UID.ContentType,
TParams extends Params.Pick<
TContentTypeUID,
| 'filters'
| 'sort'
| 'populate'
// | etc...
>
>(uid: TContentTypeUID, params?: TParams): Promise<Result<TContentTypeUID, TParams>[]>
```
**When using the entity-service's `findMany` method with a `sort` object notation, it breaks the parameters type inference.
This is caused by the usage of generics (inferred upon usage) in mapped types with loose index …

[Types] Fix entity-service's parameters inference for generic mapped types with deep literal intersections

---

packages/core/content-releases/admin/src/pages/ReleasesPage.tsx

Added a divider below the tabs 
In the list of releases the bottom border is missing below the tabs
Go to the Releases page and check below the tabs

fix(content-releases): add a bottom border below tabs

---

packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

- Adds the hover state for delete
- Adjusts the popover placement to match the designs
- Adds the menu to the Release page
So it is easier to delete ReleaseActions
Go to the release page
Click the 3 dots
Click delete
Originally I wanted to take care of CS-465 and refactor this component so we can use it for all our popover menus but I don't have the time before going on vacation. I should however be able to open a PR to fix the positioning in the DS for the Simple Menu.
I've also created CS-476 to handle this when I get back

feat(content-releases): delete release action on release page

---

packages/core/strapi/src/Strapi.ts
packages/core/strapi/src/factories.ts

Add an `!== undefined` filtering before calling isCustomController when computing startup telemetry.
This situation is highly unlikely but arises when the controller container is corrupted such as in https://github.com/strapi/strapi/issues/19135#issuecomment-1875202454.
The long-term solution will be to better validate controllers' format at a higher level (e.g. during the register step).
This PR aims to be a quick fix to unblock users.
We don't have tests for the telemetry at the moment (we have to rely on manual testing) + this has to be changed anyway & shouldn't be something that we aim to support. I thus don't see the point in adding tests to this in particular.
close #19135

Filter out undefined controllers in startup telemetry checks

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/ListPage.tsx
packages/core/admin/ee/admin/src/content-manager/pages/ListView/components/StageFilter.tsx
packages/core/types/src/modules/entity-service/params/filters/index.ts
packages/core/types/src/types/core/common/index.ts
packages/core/types/src/types/utils/expression.ts

- Improved the schema registries detection strategy (ended up being unreliable in edge scenarios)
- Added a check to the attributes filtering to allow any filter when schema registries are not extended.
- Ease the development when registries are not extended (e.g. when working in the mono-repository on internal packages)
- With types not generated, head to the kitchensink-ts example project and make an entity service query to any entity. You should be able to pass filters (while still having full IntelliSense for them)
- When types are generated, it should only accept valid fields as filters, and the return type for the result should be typed accordingly (entity + fields + populate)
made obvious since https://github.com/strapi/strapi/pull/19093
remove the need for …

[Types] Fix Attributes Filtering when no registries are extended

---

examples/getstarted/src/api/kitchensink/content-types/kitchensink/schema.json
packages/core/admin/admin/src/content-manager/components/FieldComponent.tsx

- Fixes an issue where nested components weren't displayed in the edit view. The data would be in the context, but you didn't get the input, it was stuck on the add an entry button
- Adds a component to the kitchensink DZ that has a nested component to make this error easier to spot
[A previous version of the code](https://github.com/strapi/strapi/blob/29255bc953ad5e2ca1458e157bdf55819b15696f/packages/core/admin/admin/src/content-manager/components/FieldComponent/utils/select.js#L38C13-L38C13) use Lodash get to retrieve the value for this reason. This was lost at some point in the migrations.
- go to the kitchensink editview
- add a "closing period" component to the dynamic zone
- you should be able to add entries to the `dish` repeatable component
You can also check the release branch if …

fix: display nested components in edit view

---

packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

It handles the case the lastname of the Release creator is null, to show only the firstname in the created by content.
It is needed because otherwise we showed the null string in the created by content.
- Step 1: Go to the Release Details view
- Step 2: Click on the 3 dots at the top
- Step 3: Look at the person who created the release if they don’t have a last name
CS-517

fix(content-releases): handle the lastname null in the createdBy content

---

packages/core/helper-plugin/src/components/GenericInput.tsx

* memoizes GenericInput
* we were having user input performance issues that grew with the complexity of the content-type
* mentioned on slack

fix(helper-plugin): memoize GenericInput for performance issues

---

packages/core/strapi/src/node/create-build-context.ts
packages/core/strapi/tsconfig.json

- changes the tsconfig to fix dynamic import errors asking for file extensions
- enforce base options types to avoid a fully unknown option object 
- Considering we will be using vite for everything I would like to change the base config eventually for v5
fixes unseen typescript issues (yarn build logs them but it doesn't errors the build process, @joshuaellis packup isn't throwing if one of the entry fails we probably need to change this)

chore: fix minor ts issues in cli

---

packages/core/admin/package.json
yarn.lock

* sets the `@strapi/data-transfer` peerDep in `@strapi/admin` to be `^4.16.0` which is looser and won't need changing
* moves the dep to be a devDep because it's supposed to be using a peer-dep and we don't want it downloading it's own version.
* package safety

chore(admin): data-transfer should be dev dep & peer dep loose

---

api-tests/core/strapi/document-service/create.test.api.ts
api-tests/core/strapi/document-service/find-one.test.api.ts
api-tests/core/strapi/document-service/resources/fixtures/author.json
api-tests/core/strapi/document-service/resources/fixtures/index.js
api-tests/core/strapi/document-service/resources/schemas/author.js
api-tests/core/strapi/document-service/resources/schemas/index.js
api-tests/core/strapi/document-service/resources/types/contentTypes.d.ts
api-tests/core/strapi/document-service/utils/index.ts
packages/core/core/src/services/document-service/middlewares/defaults/locales.ts

Follow up of https://github.com/strapi/strapi/pull/19058 
On content types without i18n enabled, document service will ignore the locale parameter. So you can not look for any specific locale of a document, or create/update such a document locale
See api tests

feat: ignore locale parameter on non localized content types

---

scripts/pre-publish.sh
scripts/publish.sh

- Adds `--skip-nx-cache` flag to the publish and pre-publish script
- Otherwise the release can end up having build errors

fix(scripts): add skip cache flag

---

packages/core/content-releases/server/src/bootstrap.ts
packages/core/content-releases/server/src/index.ts

I'm using lifecycle hooks on Content-Releases plugins to listen to delete entries events and use them to delete release-actions if there is one related to the entries deleted.
1. Create a release and add entries to the release.
2. Delete the entries you just added.
3. They should be deleted also from the release with no errors

fix(content-releases): using lifecycle hooks for delete actions

---

packages/utils/upgrade/src/cli/commands/codemods.ts
packages/utils/upgrade/src/cli/commands/upgrade.ts
packages/utils/upgrade/src/cli/errors.ts
packages/utils/upgrade/src/cli/index.ts
packages/utils/upgrade/src/cli/types.ts
packages/utils/upgrade/src/modules/codemod-runner/__tests__/codemod-runner.test.ts
packages/utils/upgrade/src/modules/codemod-runner/codemod-runner.ts
packages/utils/upgrade/src/modules/npm/__tests__/package.test.ts
packages/utils/upgrade/src/modules/npm/package.ts
packages/utils/upgrade/src/modules/npm/types.ts
packages/utils/upgrade/src/modules/project/constants.ts
packages/utils/upgrade/src/modules/project/project.ts
packages/utils/upgrade/src/modules/upgrader/types.ts
packages/utils/upgrade/src/modules/upgrader/upgrader.ts
packages/utils/upgrade/src/modules/version/__tests__/semver.test.ts
packages/utils/upgrade/src/modules/version/range.ts
packages/utils/upgrade/src/modules/version/semver.ts
packages/utils/upgrade/src/tasks/codemods/codemods.ts
packages/utils/upgrade/src/tasks/upgrade/types.ts
packages/utils/upgrade/src/tasks/upgrade/upgrade.ts

- Added a hidden `to` command
- It takes a `<target>` parameter (should be any valid semver, including prerelease / builds)
- It accepts an optional `-c, --codemodsTarget <codemodsTarget>` option to target codemods different than those inferred by `<target>`
- Made the project and upgrader helpers accept complex semver (instead of `x.x.x` only) 
- Added more logs
- Updated unit tests when needed
- This is necessary to allow using the upgrade tool on experimental, alphas, betas and rc versions
- `cd examples/getstarted`
- `../../packages/utils/upgrade/bin/upgrade.js help to`
or
- `../../packages/utils/upgrade/bin/upgrade.js to --help`
**Note:** executing `../../packages/utils/upgrade/bin/upgrade.js --help` should not leak the `to` command
- `../../packages/utils/upgrade/bin/upgrade.js to …

[Upgrade Tool] Add internal support for upgrading to any version

---

packages/core/admin/admin/src/content-manager/components/ContentTypeFormWrapper.tsx
packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/Provider.tsx
packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents.tsx
packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx
packages/plugins/i18n/admin/src/utils/data.ts

* removes the calls of directly setting state to whether we're creating an entry or not in the CM & instead derives the state value from the URL params
* Primarily to handle singleTypes we were originally check if there's an ID present to see if we're creating an entry, single types dont have IDs so when we've done the call to fetch the data we manually flipped this. In the case of switching locales e.g. i have an EN entry and I need to make a DE entry, we wouldn't change the state from "not creating" to "creating" leaving an infinite loop. Using an effect is probably a bad idea because we can derive from the URL if we're making an entry & because we're never making a single-type (they always exist because they're singletons) we can omit the `useState`.
*locales*
* Go to an localised …

fix(cm): manage when we're creating entries derivatively in the CM

---

packages/core/content-releases/server/src/services/__tests__/release-validation.test.ts
packages/core/content-releases/server/src/services/release.ts
packages/core/content-releases/server/src/services/validation.ts

- Checks the license has been configured with the maximumReleases option
- Checks if the user has or has not reached the limit per their license
- If the license is missing the config a default of 3 will be set since if you have a license with the feature enabled you should have at least that limit.
This PR only handles the backend validation, another PR will handle the error on the FE 
- To enforce the license entitlements
- Ping me for a license with a limit of 3
- Then test you can't create more than 3 releases

chore(content-releases): enforce license limits for pending releases

---

packages/plugins/i18n/server/src/controllers/validate-locale-creation.ts

Content Manager was sending the following param when accessing a locale:
```
plugins[i18n][locale]=en
```
As i18n will be a core package, this is now changed to be
```
locale=en
```

chore: i18n content manager locale param

---

packages/core/admin/_internal/node/develop.ts

The --develop command in a JS Strapi project now skips the type generation step when config/typescript.js autogenerate = false
Types are not a hard requirement for JS projects and it's annoying in many cases to have it update after every change.
In a javascript Strapi project with a config/typescript.js containing `module.exports = { autogenerate: false }`, go to the content type builder and make some change, and see the server does not generate types
In all other project configurations, it should still generate types.
Fixes #18124 (autogeneration is required on TS projects for the develop command or the server will not start)
Fixes #19195

Respect autogenerate setting for JS projects

---

packages/core/content-releases/package.json

Remove prePublish only script from package.json
- so the package isn't built twice

chore(content-releases): remove prepublishOnly script

---

packages/core/data-transfer/src/strapi/providers/remote-source/index.ts

removes a comment for something we're not actually deprecating; support for single (non-array) items in data-transfer config 
it's really not a problem to support it, no reason to remove it

chore: remove comment about deprecation

---

packages/core/admin/admin/src/pages/Marketplace/MarketplacePage.tsx
packages/core/content-releases/admin/src/pages/ReleasesPage.tsx

It solves an issue we had in the TabGroup inside the CMS used in the Markeplace and Content Releases, it doesn't react to the changes of the initialSelectedTabIndex prop
Because for example when you try to use the browser back button or you click on the side bar menu on the left the tabs are not updated with the current selection
Link this DS version to your CMS and try to, for example, to the Marketplace page admin/marketplace
- then click on the tab Providers
- then use the Back button of the browser you need to see the Plugins tab selected instead of the Providers one
CS-468

fix(content-releases): TabGroup react to changes of the initialSelectedTabIndex value

---

packages/core/content-type-builder/admin/src/components/FormModal/forms/forms.ts
packages/core/content-type-builder/admin/src/translations/en.json

Temporarily disable CTB checkboxes for component unique fields until their behaviour is fixed
So we can release and fix this behaviour later
CONTENT-2120

[CTB] - temporarily disable component unique field checkboxes

---

packages/core/content-releases/server/src/controllers/__tests__/release.test.ts
packages/core/content-releases/server/src/controllers/release.ts
packages/core/content-releases/server/src/services/__tests__/release.test.ts
packages/core/content-releases/server/src/services/release.ts

Change the filter behaviour to fix a bug where we return all releases with 2 or more entries attached. Now only return the releases that doesn't have the entry attached when needed
1. Go to the Edit View of one entry that is already attached to some release
2. Try to add the entry to a new release
3. In the dropdown you should have only releases where the entry is not attached yet

fix(content-releases): filter releases with entry attached

---

packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeOption.tsx

Removes the new tag for blocks in the attribute picker.
I leave the badge component in place for when we'll need it in the future.
It's not new anymore

chore(ctb): remove "new" badge on Blocks attribute

---

packages/providers/upload-local/package.json
packages/providers/upload-local/src/__tests__/upload-local.test.ts
packages/providers/upload-local/src/global.d.ts
packages/providers/upload-local/src/index.ts
yarn.lock

> Wait for this to be merged 1st https://github.com/strapi/strapi/pull/19261
Removes the last circular deps (plugin-upload / upload-locale) and fixes the typings as `@strapi/plugin-upload` doesn't export any type at the moment
to fix circular deps

chore: remove last circular dep

---

packages/core/admin/ee/admin/src/services/auditLogs.ts

Audit logs request is not appending the query params to the url because we send the params in the wrong field.
1. Go to the Audit Logs page
2. It should work when you change page, apply filters, etc...

fix(admin): append query params to audit logs request

---

packages/providers/upload-aws-s3/README.md

Use 2-space indentation instead of 4 in s3 readme
It made the prettier check fail on PRs
~~Check the CI~~ (edit: it won't run since it's just a readme change)
#19169

fix(upload-aws-s3): prettier error in readme

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/providers/upload-aws-s3/README.md

it hides the More button on the Edit view if you don't have permission to remove an action from a release
Otherwise, we show an empty dropdown
- Create a new user with a Role different than super admin
- then as a super admin add an entry to a Release
- change the permission of the new user role and disable the "Remove an entry from a release" permission
- in a new tab login with the user editor and go to the Edit View of the entry added to the Release
- then in the Release action in the Edit view the more button needs to be hidden
it solves this issue
https://github.com/strapi/strapi/assets/2589748/f6d774ae-974f-4e4e-8292-2df1763515ca

fix(content-releases): hide the More button in the CM Edit View with no permission

---

packages/core/content-releases/server/src/services/__tests__/release-validation.test.ts
packages/core/content-releases/server/src/services/release.ts
packages/core/content-releases/server/src/services/validation.ts

Add a new validation to check the release user is trying to create doesn't have the same name that another pending release
1. Create one release with "X" name
2. Try to create another release with the same name
3. It should show an error

fix(content-releases): Don't allow pending releases with the same name

---

packages/core/strapi/src/cli/commands/plugin/build.ts
packages/core/strapi/src/cli/commands/plugin/init/action.ts
packages/core/strapi/src/cli/commands/plugin/link-watch.ts
packages/core/strapi/src/cli/commands/plugin/verify.ts
packages/core/strapi/src/cli/commands/plugin/watch.ts

* removes experimental logs from the plugin commands
* they're not experimental
* there shouldn't be any logs from the plugins being built
* resolves CONTENT-2151

chore: remove experimental logs for plugin CLI commands

---

packages/core/core/src/Strapi.ts
packages/core/core/src/utils/__tests__/convert-custom-field-type.test.ts
packages/core/core/src/utils/__tests__/filepath-to-prop-path.test.ts
packages/core/core/src/utils/addSlash.ts
packages/core/core/src/utils/convert-custom-field-type.ts
packages/core/core/src/utils/ee.ts
packages/core/core/src/utils/fetch.ts
packages/core/core/src/utils/filepath-to-prop-path.ts
packages/core/core/src/utils/get-dirs.ts
packages/core/core/src/utils/index.ts
packages/core/core/src/utils/is-initialized.ts
packages/core/core/src/utils/load-files.ts
packages/core/core/src/utils/open-browser.ts
packages/core/core/src/utils/startup-logger.ts
packages/core/core/src/utils/update-notifier/index.ts

- Remove default exports
- Using import * to reduce number of imports and scope all the utils inside the utils folder (avoid importing sub paths)
cleanup / prep for the lint changes

chore: cleanup core utils org

---

packages/core/data-transfer/src/commands/data-transfer.ts

It excludes releases from dts
The relations with user are broken, not sure on a product level if want them included

fix(dts): exclude content-releases

---

api-tests/core/strapi/document-service/relations/basic.test.api.ts
api-tests/core/strapi/document-service/relations/mutations/connect.test.api.ts
api-tests/core/strapi/document-service/relations/mutations/disconnect.test.api.ts
api-tests/core/strapi/document-service/relations/mutations/set.test.api.ts
api-tests/core/strapi/document-service/resources/fixtures/article.json

This is the first set of tests to validate relations are working at the document service level.
The tests are not filled, this is just so you can review them and agree this is what we want to test :) 
More context of the work needed to do in [CONTENT-2132](https://strapi-inc.atlassian.net/browse/CONTENT-2132)
There will be another list of tests for D&P and i18n interactions (publishing, unpublishing, non localized content types relations, ...)
(At the moment this will work for only a many-to-many relation, but we can extend it for all types of relations in the short term)
[CONTENT-2132]: https://strapi-inc.atlassian.net/browse/CONTENT-2132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: relations tests template for document service

---

packages/core/admin/admin/src/StrapiApp.tsx
packages/core/admin/admin/src/content-manager/history/components/InjectedLink.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionDetails.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionsList.tsx
packages/core/admin/admin/src/content-manager/history/pages/History.tsx
packages/core/admin/admin/src/content-manager/history/pages/tests/History.test.tsx
packages/core/admin/admin/src/content-manager/history/routes.tsx
packages/core/admin/admin/src/content-manager/pages/App.tsx
packages/core/admin/admin/src/content-manager/routes.tsx
packages/core/admin/admin/src/pages/Layout.tsx
packages/core/admin/admin/src/translations/en.json

Sets up the history page for single and collection types. Hides the main navigation and the content manager navigation for this page.
Also adds a temporary injected component in the edit view right links so that we can easily find the history page until the document action API is added
So we can start working in parallel on both the sidebar and the details view
- Go to the edit view for a collection type entry. Click on the history button on the right.
- Same thing for a single type
- Clicking on "back" should take you back 1 page

feat(cm): set up history page

---

packages/utils/pack-up/src/__tests__/cli.test.ts

Skip pack-up build test, this is going to be removed before the v5 release and it's a bit flakey.

fix: skip flakey test

---

packages/plugins/i18n/admin/src/components/CMEditViewLocalePicker.tsx

* checks if there's an ID as well before we try to create a new locale entry
* locales without D&P would be given the status of "we don't have a draft or published" which is true, but we still had the ID signifying that it existed.
* Have a content-type without D&P enabled & i18n enabled
* save default locale of content-type
* swap to alternate locale (should be empty form)
* swap back to original (should be filled)
* resolves CONTENT-2177
* resolves #19267

fix(i18n): locale swapping with content-types & D&P disabled

---

packages/core/types/src/modules/documents/params/attributes.ts
packages/core/types/src/modules/entity-service/params/attributes/index.ts
packages/core/types/src/types/core/attributes/relation.ts
packages/utils/typescript/lib/__tests__/generators/schemas/attributes.test.js
packages/utils/typescript/lib/generators/common/models/mappers.js

The `TOrigin` type param for `Attribute.Relation` was deprecated in V4 and is not used.
This PR aims to remove it completely (from the usage in the code & from the type gen)
Update unit tests
Cleanup types
Make sure types that depend on `Attribute.Relation` stills work properly and that the type generation no longer adds the `TOrigin` type param to generated types

[breaking change] Remove the TOrigin Type Param for Attribute.Relation

---

packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/content-type-builder/admin/src/components/FormModal/component/createComponentSchema.ts
packages/core/content-type-builder/admin/src/components/FormModal/forms/forms.ts
packages/core/content-type-builder/admin/src/components/FormModal/forms/utils/createCollectionName.ts
packages/core/content-type-builder/server/src/services/schema-builder/component-builder.ts

Add checks on the server and frontend for components collection name, so server doesn't crash
- Server crashed when adding a component that has the same plural as another component, example : new and news
- create a component named new, and then try to create one named news, it should give an error message

Check component against collectionTypeNames

---

api-tests/plugins/i18n/content-manager/crud.test.api.js
api-tests/plugins/i18n/locales.test.api.js
packages/plugins/i18n/server/src/controllers/validate-locale-creation.ts

Changes where we extract the locale from in query strings
From `query.plugins.i18n.locale` to `query.locale`
To support how we are sending locales in the CM

Extract locale from query strings

---

packages/utils/typescript/lib/__tests__/generators/schemas/attributes.test.js
packages/utils/typescript/lib/generators/common/models/attributes.js

Skip the `default` modifier on type generation when its value is a function.
Trying to convert a function to a type literal is not working (at least for now), and it was crashing the type generation process
- `cd examples/getstarted`
- `yarn strapi ts:generate-types --verbose`
The process should be completed successfully
- was preventing us from doing QA on https://github.com/strapi/strapi/pull/19338 and https://github.com/strapi/strapi/pull/19336

Prevent Type Generation From Failing on Functions as Default Value

---

api-tests/plugins/i18n/content-manager/crud.test.api.js
api-tests/plugins/i18n/locales.test.api.js
packages/core/admin/admin/src/content-manager/components/ContentTypeFormWrapper.tsx
packages/plugins/i18n/server/src/controllers/validate-locale-creation.ts

resolves #19289
* passes query params to the post requests for publish & unpublish calls
* in single-types you use the `locale` query param to understand what actions should target which entity as opposed to the ID, this was missing so all actions were directed at the default locale.
* ensure single-type is localised
* publish first locale
* navigate to second locale & publish (it should publish)
* unpublish first locale
* unpublish second locale (previously this would not have worked)
* resolves #19289
* resolves CONTENT-2176

fix(cm): pass params to post requests for publish & unpublish

---

packages/core/content-releases/admin/src/pages/ReleasesPage.tsx

It corrects the name of the property for the max number of pending releases for license
with wrong naming is always returning 3
- usa strapi license with unlimited releases
- create more than 3 releases
- you don't have errors

fix(content-releases): wrong value for the max number of pending releases limit

---

.github/actions/run-build/action.yml
.github/actions/yarn-nm-install/action.yml
.github/workflows/adminBundleSize.yml
.github/workflows/checks.yml
.github/workflows/contributor-doc.yml
.github/workflows/nightly.yml
.github/workflows/publish-prerelease.yml
.github/workflows/remove-dist-tag.yml
.github/workflows/skipped_tests.yml
.github/workflows/tests.yml

Updates to:
- actions/cache@v4
- actions/setup-node@v4
- actions/upload-artifact@v4
- dorny/paths-filter@v3
Sets the node version for our actions to node 20
The older actions were using Node 16 by default, which is deprecated in github CI
CI should still work exactly as before but with Node 20 actions

chore: update github action versions for node 16 deprecations

---

jest-preset.front.js
packages/admin-test-utils/src/after-env.ts
packages/admin-test-utils/src/fixtures/store/index.ts
packages/core/admin/admin/src/core/store/configure.ts
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplacePlugins.test.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplaceProviders.test.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/tests/ListPage.test.tsx
packages/core/admin/admin/tests/utils.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/components/tests/Stage.test.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/components/tests/Stages.test.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/components/tests/WorkflowAttributes.test.tsx
packages/core/content-releases/admin/tests/utils.tsx
packages/core/helper-plugin/src/components/tests/GenericInput.test.tsx
packages/plugins/color-picker/admin/src/components/tests/ColorPickerInput.test.tsx
packages/plugins/i18n/admin/tests/utils.tsx
packages/utils/pack-up/src/__tests__/cli.test.ts
playwright.base.config.js

- disable react default middleware timeouts for tests
- set jest timeout globally for front-end tests
- increase playwright expect timeout
- skips the pack-up cli test since it was also a major headache and doesn't really test anything that isn't already de facto tested by the fact strapi is built with it. We will add it back as a CLI e2e test once those are merged
Randomly failing tests are killing us; this should solve the vast majority of them
CI tests should work the first time without driving you bonkers

chore: fixes for flaky tests

---

packages/core/content-manager/server/src/services/document-metadata.ts

Available status array was returned empty if the requested Content Type didnt have i18n enabled.

fix: return available status when content type doesnt have i18n enabled

---

packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

Changed the icons width and height in the Release Details page
To have a similar layout for them, because at the moment they have different sizes
Go to the details page and check the icon size in the "More" menu and in every entry menu
CS-557

fix(content-releases): standardize icons size

---

packages/core/data-transfer/src/strapi/queries/link.ts

- Handles the morphToOne attribute on export
- Currently the case is not handled which leaves morphToOne polymorphic relations as null on export and therefore null on import
- Releases uses this relation and although it is not currently included in the @strapi/data-transfer it is used via a DTS engine in the e2e tests
In Strapi admin
- Create a kitchensink and a category
In your database explorer:
- Go to the kitchensinks, and pick an entry
- Add target_type: `api::category.category`
- Add target_id: `<id-of-existing-category>`
In your console:
- Run `strapi export -f test.tar --no-encrypt --no-compress`
- Run `strapi import -f test.tar`
In you database explorer
- Refresh and confirm kitchensinks has persisted the target_type, and target_id
- Note: the ids will have incremented but the …

fix(dts): support morphToOne relations

---

packages/core/content-releases/admin/src/components/ReleaseActionOptions.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

It adds some UI to the Unpublish radio button, the hover effect to both the radio buttons and the disabled state when the user has no permission to change the action type in the Release Details page
We need to improve the UX of the two radio buttons and avoid the possibility to change action type if the user doesn't have the right permissions
- create an Editor user from the settings and login as Editor in an other tab
- in the Tab where you are logged as admin create a new release and add some items to the release
- then in the Settings for the Editor role disabled the Edit and Publish permissions for Content Releases plugin
- then in the tab where you are logged as Editor you can see the Radio button related to the action type not selected disabled (in this way you cannot change action …

fix(content-releases): add disabled state to action radio buttons

---

packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/CreatePage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/EditPage.tsx
packages/core/admin/ee/admin/src/services/reviewWorkflows.ts
packages/core/admin/shared/contracts/review-workflows.ts

* The types we're incorrect so they're amended to highlight we send the data nested under `data` in the body
* The provides tag set up was wrong where `id===""` but we should be checking it's not an empty string to correctly provide the list tag & in addition provide a single `ReviewWorkflow` not `User`
* We use the param from react-router instead of redux to update the workflow with it's correct `id` 
* Users could not create or update workflows
* Data was not invalidated correctly
* As a user I should be able to create a workflow
* then update that workflow
* then go to the list view of workflows see that workflow
* edit that workflow again
* go back to the list view and delete the workflow 
* it should not be in the list view no longer
* resolves #19439

fix(review-workflows): cannot create or update workflow & data doesn't invalidate correctly

---

packages/core/admin/ee/admin/src/services/reviewWorkflows.ts

* Passes `data` instead of `body` to the API
* Users were unable to update the stage or assignee of an entity in the CM
* As a user I should be able to update the stage of an entity in the CM
* As a user I should be able to update the assignee of an entity in the CM
* resolves #19340

fix(review-workflows): pass data not body 

---

api-tests/core/content-manager/api/x-to-many-rf-preview.test.api.js
packages/core/content-manager/server/src/controllers/relations.ts

- Add some Api tests for pagination
- used correct pagination result for existing relations
- Load More was not appearing because of incorrect pagination values
- Make sure that the load more appears when you have 5+ relations present
- check the test explanation in this other PR: #19227 
fix #19402

Restore proper pagination object

---

e2e/constants.js
e2e/scripts/dts-import.js
e2e/tests/content-manager/uniqueness.spec.js

Stops playwright tests from importing 'plugin::i18n.locale' from the datasets by default
There were no locales exported in the `without-admin` export but on import we were saying to replace them, which left Strapi with no locales, so it couldn't load.
We could update the without-admin data to include locales but... they're only needed for one specific test and the fewer things we depend on, the less often we'll have to update ALL our test datasets.
Playwright tests should run

Chore: fix playwright test issue

---

api-tests/core/strapi/api/validate-query/validate-query.test.api.js
api-tests/core/strapi/deep-filtering.test.api.js

@innerdvations spotted this flakey test, that was sometimes matching the document id of the document. The solution was to search by a longer element.

fix: q search flakey test

---

packages/core/content-manager/server/src/controllers/collection-types.ts
packages/core/content-manager/server/src/services/__tests__/document-metadata.test.ts
packages/core/content-manager/server/src/services/document-metadata.ts

- Computes modified state
- Returns "status" on the list view (yep, it was not being returned )
I am sure we can optimize things a lot, specially for the list view.
Also, this PR will not properly work until [this PR is merged](https://github.com/strapi/strapi/pull/19373)

feat: compute modified status

---

packages/core/content-releases/server/src/content-types/release/schema.ts
packages/core/content-releases/shared/contracts/releases.ts
packages/core/content-releases/shared/validation-schemas.ts

This PR add a new string field to "Release" Content Type to save the Timezone selected by the user in the UI. 
⚠️ We are saving the `scheduledAt` **always** using UTC, as we do for any time in all Strapi. This new timezone field is **only** for showing the time in the Release UI with the timezone selected by the user. 
The scheduling functionality is implemented through future flags. To begin, ensure the future flag is set to true. Navigate to `config/features.js` and include `contentReleasesScheduling` as an option within your future object. Create the future object if it does not exist.
Example:
```js
// config/features.js
future: {
contentReleasesScheduling: true,
},
});
```
1. Create a new release with scheduledAt field, it should ask you to send the …

feat(content-releases): add timezone to releases

---

packages/utils/typescript/lib/__tests__/generators/schemas/attributes.test.js
packages/utils/typescript/lib/generators/common/models/attributes.js

Fix a behavior where the type generation could fail when min/max values for an attribute were set to a falsy value (e.g. `0`)
It prevents the generation of the type
- Add a numeric attribute to a schema such as the following
```json
{
"totalPrice": {
"type": "decimal",
"min": 0
}
}
```
- Run `yarn strapi ts:generate-types`
- The types should be generated correctly, without throwing an error
fix #19482

Fix Type Generation Checks for Min/Max Default Values

---

api-tests/plugins/i18n/content-manager/crud.test.api.js
api-tests/plugins/i18n/locales.test.api.js
packages/plugins/i18n/server/src/controllers/validate-locale-creation.ts

Changes where we extract relatedEntityId from the query string
i18n was broken as relatedEntityId was not nested in {plugins.i18n} as the BE was expecting
QA
Updated API tests
Fixes https://github.com/strapi/strapi/issues/19486

fix(i18n): extract relatedEntityId from the query

---

packages/core/admin/admin/src/content-manager/history/components/VersionContent.tsx
packages/core/content-manager/server/src/history/controllers/__tests__/history-version.test.ts
packages/core/content-manager/server/src/history/controllers/history-version.ts
packages/core/content-manager/server/src/history/services/history.ts

- Do not require `documentId` when fetching singleType history versions since only a single document can exist for single-type content types.
- Otherwise can't fetch single-types 
- It doesn't seem necessary for single types (tbd 🙃 ).
- Go to a single-type
- Make a change and save
- Click the history button, you should see a single version
- Go back to the single type
- Make another change and save
- Click the history button, you should see two versions.
- Move between them to see the data changes between versions
NOTE: It seems to be working but I am unable to create an entry in another locale to test that is working

fix(history): fetch single-types

---

packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/tests/reducer.test.ts
packages/core/admin/admin/src/content-manager/components/Wysiwyg/Editor.tsx
packages/core/admin/admin/src/content-manager/utils/fields.ts

It resolves a lot of rendering bugs in DZ when using for example Rich Text markdown fields.
In particular when you change the position of a markdown field inside a Dynamic Zone.
It ensures to generate unique IDs when we add new components in the DZ
To avoid strange behaviours like when a component was added in a Dynamic Zone above a component containing the rich text editor, the wrapper would show up twice.
We want to add a temporary key when we add a new component which has a unique value to avoid conflicts between components, so to do this we want to find the maxValue between previous components ids and temp keys
Please take a look at the video to have an idea of the previous bug and read the instructions to replicate it:
- in a collection create a dynamic zone with a markdown field and …

fix(content-manager): fix strange behaviours when you change position on Dynamic Zones and solve issue with ids not unique

---

api-tests/plugins/i18n/content-manager/crud.test.api.js
packages/core/content-manager/server/src/controllers/collection-types.ts
packages/core/content-manager/server/src/controllers/single-types.ts
packages/plugins/i18n/server/src/register.ts

Get an empty body object and a 204 status if document does not have requested locale

fix: send empty object if locale does not exist on document

---

api-tests/plugins/i18n/content-manager/crud.test.api.js
packages/core/content-manager/server/src/controllers/collection-types.ts
packages/core/content-manager/server/src/controllers/single-types.ts

When finding a specific document locale, if the locale doesn't exist but the document does, the content manager response will be:
```
status: 200 // 204 was removing everything from the response body
body: {
data: {},
meta: {
availableLocales: [...],
availbleStatus: []
}
```
works for collection types and single types ✌️

feat: return available locales when not finding locale

---

packages/core/admin/admin/src/content-manager/history/components/VersionHeader.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionsList.tsx
packages/core/admin/admin/src/content-manager/history/components/tests/VersionHeader.test.tsx

Makes sure the back button of the history page takes you to the edit view of the right component

fix: history page back button

---

packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx
packages/plugins/i18n/admin/src/index.ts
packages/plugins/i18n/admin/src/translations/en.json

* Adds the ability to delete a specific locale in the CM Edit & List View
* As a user I want to make an entry in a non-default locale, save that entry & delete the specific locale with my original document remaining.
* resolves CONTENT-2034

feat(i18n): add delete locale action

---

packages/core/database/src/dialects/mysql/database-inspector.ts
packages/core/database/src/dialects/mysql/index.ts

- pass nativeconnection to getInformation to be reused...
- ...so that each raw query doesn't create a new connection, causing an infinite loop that overflows the pool
Using mysql as the db should now work fine everywhere and in all cases (such as the [doc id migration](https://github.com/strapi/strapi/pull/19514))
https://github.com/strapi/strapi/pull/19527
https://github.com/strapi/strapi/pull/19514

fix: prevent infinite loop opening pool connections in mysql

---

e2e/tests/content-releases/release-details-page.spec.ts
e2e/tests/content-releases/releases-page.spec.ts
examples/getstarted/config/features.js
packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseModal.tsx
packages/core/content-releases/admin/src/components/tests/CMReleasesContainer.test.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/pages/ReleasesPage.tsx
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/admin/src/utils/tests/time.test.ts
packages/core/content-releases/admin/src/utils/time.ts

Adds the scheduled date (when release has one) on the Edit Entry View, Release list view and Release Details view.
1. Go to an entry attached to a release with scheduled date. You should see the scheduled date (with the timezone selected on the release, even if it's different from yours, this is the same for all the other cases)
2. Go to the Releases List view, you should see a relative time on releases with scheduled date.
3. Go to the Releases Details view, you should see the scheduled date on the top.

feat(content-releases): show release scheduled date

---

packages/core/admin/admin/src/content-manager/history/components/VersionContent.tsx
packages/core/admin/admin/src/content-manager/history/pages/History.tsx
packages/core/admin/admin/src/content-manager/history/services/historyVersion.ts

Forces a refetch of history versions when the history page is mounted. The cached entries are still displayed while we're refetching.
A consequence of this design is that you may not land on the most recent version anymore. If the refetching finds a more recent version than the one that was the 1st when you opened the page, then that newer version will appear as the new n°1 but you won't have it selected, you'll still have the previous one (now n°2).
Why not invalidate the cache when a content update is made? Because the history version creation is not awaited, so we don't know for sure that the history version has already been created when the PUT request is done. We could await the history version creation, but that would slow down all content updates, which I don't think is a good …

fix(history): refetch history versions on mount

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseActionOptions.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

This PR fix some small UI details on Content Releases Scheduling new feature.
1. Show times in 23h format (This means that we start with 00:00 and end on 23:59)
2. A typo on the Release Details subtitle
3. Add cursor pointer to change release action type

fix(content-releases): fix UI details

---

e2e/tests/content-manager/uniqueness.spec.ts
packages/core/admin/admin/src/content-manager/components/Form.tsx
packages/core/admin/admin/src/content-manager/components/FormInputs/types.ts
packages/core/admin/admin/src/content-manager/components/Relations/RelationInputDataManager.tsx
packages/core/admin/admin/src/content-manager/constants/attributes.ts
packages/core/admin/admin/src/content-manager/hooks/tests/useDocument.test.tsx
packages/core/admin/admin/src/content-manager/hooks/useDocumentLayout.ts
packages/core/admin/admin/src/content-manager/pages/EditView/EditViewPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/DocumentActions.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Component/Input.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/DynamicZone/DynamicZoneLabel.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/DynamicZone/Field.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/Header.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/InputRenderer.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActions/SelectedEntriesModal.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/components/BulkActions/tests/SelectedEntriesModal.test.tsx
packages/core/admin/admin/src/content-manager/utils/validation.ts
packages/core/admin/admin/src/translations/en.json
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/components/Stage.tsx
packages/core/helper-plugin/src/components/NotAllowedInput.tsx
packages/core/helper-plugin/src/components/tests/NotAllowedInput.test.tsx
packages/core/utils/src/yup.ts
packages/plugins/i18n/admin/src/components/tests/CreateLocale.test.tsx
packages/plugins/i18n/admin/src/components/tests/EditLocale.test.tsx

* refactors createYupSchema to avoid so many `@ts-expect-error` directives
* adds a blocker to the EditViewForm which is exported from Form so you're warned if you're about to dump your content
* handles validation errors from the server
* validates the form in the EditView
* re-implements useFieldHint logic to display max min for fields
* resolves CONTENT-1065
* resolves CONTENT-2172
* resolves CONTENT-2206
* resolves CONTENT-2107

feat(cm): re-implement validation

---

packages/core/upload/server/services/upload.js
packages/providers/upload-aws-s3/src/index.ts
packages/providers/upload-cloudinary/src/index.ts
packages/providers/upload-local/src/index.ts

Added a `sizeInBytes` attribute to the `File` object that we send to upload providers. This property adds to the current `size` property which expressed the size in kilobytes rounded to the 2 most significant digits.
Strapi Cloud need to know the exact size in bytes of a file to be able to upload it to an object storage using streams. The conversion from bytes to kilobytes is "lossy" and doesn't let us get the exact size of the file.
Upload a file and verify the the upload provider receives the file size ad expected.
**Jira task**: [CLOUD-808](https://strapi-inc.atlassian.net/browse/CLOUD-808)
[CLOUD-808]: https://strapi-inc.atlassian.net/browse/CLOUD-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sizeInBytes for upload providers

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/translations/en.json

Add missing "Edit Release" button on Edit View.
1. Go to edit an entry attached to a release
2. Click the "3 dots" button on the Releases box
3. You should see "Edit Release" link and it should work

feat(content-releases): Add edit release button on edit view

---

packages/core/content-manager/package.json
packages/core/content-manager/server/src/history/index.ts
packages/core/content-manager/server/src/history/services/__tests__/history.test.ts
packages/core/content-manager/server/src/history/services/history.ts
yarn.lock

- Adds a node scheduler to clear expired history versions every day
- This is more or less a copy paste from augit log (I believe the rules are the same 🤔 )
- To delete expired history versions base don the user or license config
- Change the schedule to
```
state.deleteExpiredJob = scheduleJob('* * * * *', () => {
// ... 
console.log('did call cron')
const expirationDate = new Date(Date.now());
```
- Create a history version and then in the database modify the created_at column so that it is a date before today
- run yarn develop
- Once you see the log refresh the db to confirm the history version was deleted

feat(history): delete expired history versions

---

packages/plugins/i18n/server/src/register.ts

I18n Backend koa middlweare was matching all CM routes, and validating locale creation even for actions that were not related (publishing, unpublishing)
If the API received the "relatedEntityId" param when publishing, it assumed this was for creating a new locale (and checked if the locale already existed), and failed because the action was to publish an existing locale.
My only worry here is that the url matching is not smart enough and we miss some cases
Create single types and collection type locales, and publish them. You should not get an error
* resolves CONTENT-2279
* resolves #19528

fix: do not validate locale if not creating

---

packages/core/admin/admin/src/content-manager/components/FormInputs/Date.tsx
packages/core/admin/admin/src/content-manager/components/FormInputs/DateTime.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionContent.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionHeader.tsx
packages/core/admin/admin/src/content-manager/history/components/tests/VersionHeader.test.tsx
packages/core/admin/admin/src/content-manager/history/components/tests/VersionsList.test.tsx
packages/core/admin/admin/src/content-manager/history/pages/History.tsx
packages/core/admin/admin/src/content-manager/history/routes.tsx
packages/core/admin/admin/src/content-manager/hooks/useDocumentLayout.ts
packages/core/admin/admin/src/content-manager/layout.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Component/Input.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/InputRenderer.tsx
packages/core/content-manager/server/src/history/services/__tests__/history.test.ts
packages/core/content-manager/server/src/history/services/history.ts

The goal of this PR is to make History work again with v5/main following the merge of Draft & Publish. The actual merge and the conflict fixes were done in the branch this PR targets. This PR is just about isolating the changes that make the feature actually work.
- use the new Form component to disable everything at once
- copy the FormLayout (don't import it directly because we need to hijack some input components, e.g. relations)
- use the proper document middleware API
Everything should work like it did before

chore: update History with new v5 APIs

---

packages/core/admin/admin/src/content-manager/components/ContentTypeFormWrapper.tsx

Send locale for DELETE requests to i18n singleTypes
We don't send an id for single types DELETE requests so every delete request was deleting the default locale as we were only specifying the single type UID
- Create multiple locales of an i18n single type
- Delete a non default locale from the CM edit view
- Verify it has deleting the correct entry
Fixes https://github.com/strapi/strapi/issues/19559
CONTENT-2281

fix(content-manager): send locale when deleting i18n single type

---

packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

Removed extra padding for action buttons, background color added for delete action
https://strapi-inc.atlassian.net/browse/CS-624
On release details page, when you click 3 dots, you will see "Edit" and "Delete" action buttons.

fix(content-releases): release details action styles 

---

packages/core/content-releases/admin/src/components/tests/CMReleasesContainer.test.tsx

- Fixes an incorrect argument that is breaking unit tests and throwing typescript errors
- The CI is failing 
- The CI should pass with no TS or frontend unit tests failing
- https://github.com/strapi/strapi/pull/19604

fix(content-releases): remove argument passed to test render

---

packages/core/admin/admin/src/content-manager/hooks/useContentManagerInitData.ts

* adds `refetchOnMountOrArgChange` to the `useGetInitialDataQuery` call in `useContentManagerInitData`
* this ensures we refetch the schemas all the time so if there are changes from the CTB we can see them updated accurately
* As a user I want to enable or disable i18n in the CTB and have the changes reflected in the content-manager
* resolves CONTENT-2889

fix(cm): fetch the init data on every mount

---

e2e/tests/content-releases/releases-page.spec.ts

* advances the date by a day to ensure the tests will pass even if it's after 2pm
* e2e EE mode fails after 2pm

test(e2e): fix content-releases bug by advancing time by a day

---

packages/core/admin/admin/src/pages/Settings/pages/TransferTokens/EditView.tsx
packages/core/strapi/src/cli/commands/develop.ts
playwright.base.config.js

* ensures playwright doesn't use dev-mode (hot reloading fucks with it)
* fix incorrect routing when successful token has been made

test(e2e): fix transfer token tests

---

packages/core/core/src/core-api/controller/__tests__/transform.test.ts
packages/core/core/src/core-api/controller/index.ts
packages/core/core/src/core-api/controller/transform.ts

Add a header to get a response format following v4 old shape to ease v5 migration.
To help with migrating to v5
Call the content-api (only affects core-api) with a `Strapi-Response-Format: v4` header to get the old format

chore: content-api response format header

---

packages/core/content-manager/server/src/services/document-metadata.ts

Query with locale in getManyAvailableStatus
For the status displayed in the CM list view. Every available status was being calculated for the default locale
See JIRA ticket for scenario
CONTENT-2276

fix(content-manager): compute document status based on locale

---

packages/core/content-releases/admin/src/components/ReleaseModal.tsx

added timezone select filter "contains" to filter by substring
As timezone values in dropdown are quite big, its a need to search by any substring value.
When you create a scheduled release, you should be able to filter timezones by any timezone value, eg: Europe/Paris, Asia/Mumbai.

fix(releases): Added timezone select filter

---

packages/providers/audit-logs-local/src/index.ts

- Adds two missing properties from audit logs schema (plugin and globalId)
- The CTB creation and edit breaks if those properties are missing
- It seems the refactoring of how we register admin contentTypes broke this in V5
- Run a strapi project in EE with audit-logs, check if you can edit and create contentTypes in the CTB

Fix: audit logs content type

---

playwright.base.config.js

increase playwright expect timeouts again
firefox e2e tests are failing sometimes from timeouts most likely
e2e tests should pass every time

test: increase playwright timeouts again

---

packages/core/content-releases/server/src/migrations/index.ts
packages/core/content-releases/server/src/register.ts

When localisation is enabled/disabled on a ContentType we update the locale of the actions from that ContentType.
1. Create a Release and add entries to it.
2. Try to enabled/disabled i18n on the entries' content type.
3. When you disabled i18n all actions should change its locale to null ('-')
4. When you enabled i18n all actions should change from null to the default locale

fix: change actions locale when changes on localization

---

api-tests/core/upload/admin/file-image.test.api.js
api-tests/core/upload/content-api/upload.test.api.js
packages/core/upload/server/services/image-manipulation.js

Adds the `sizeInBytes` attribute for images that have been resized and update it for optimized images.
The previous PR https://github.com/strapi/strapi/pull/19593 was incomplete, it added the attribute only for the original file and not thumbnails or responsive images.
Upload an image and verify the the upload provider receives the file size for all sizes, as expected.
Original PR https://github.com/strapi/strapi/pull/19593

Add sizeInBytes on resized and optimized images

---

packages/core/admin/admin/src/components/PageHelpers.tsx
packages/core/admin/admin/src/content-manager/history/components/VersionContent.tsx
packages/core/admin/admin/src/content-manager/history/pages/History.tsx
packages/core/admin/admin/src/content-manager/history/routes.tsx

- Wraps the history page in Page.Protect to guard it from users without permissions
- The ticket says to redirect when the user doesn't have permissions but here I implemented the same behavior as the EditViewPage to be consistent. Open to discussion.
- So users without permissions can't access the page
- Crete a user with an editor role
- Revoke all permissions from a content-type
- As a super admin make some changes to an entry in that content-type, copy the history page url
- Try to access the url as an editor. 
- You should see a "No permissions" state
NOTE: 
- Custom conditions throw an error. I believe this is a known issue according to the v5 bug board
CS-496

feat(history): protect history page

---

e2e/tests/content-releases/releases-page.spec.ts
packages/core/content-releases/admin/src/components/ReleaseModal.tsx

Min date considering selected timezone added for scheduling.
https://strapi-inc.atlassian.net/browse/CS-627
- Try to to create a scheduled release and check that you should not be allowed to select date past today. 
- Also try to check with timezones with `UTC-HH:00`, should display correct minimun date for selected timezone.
- Also BE validation should throw if you select a time earlier in the day which is passed.

fix(content-releases): Limit min date selection to schedule a release

---

packages/core/content-releases/server/src/__tests__/index.test.ts
packages/core/content-releases/server/src/index.ts
packages/core/content-releases/server/src/register.ts

- Exclude release content types from graphql
- Alway run register function from graphql. Since the content types are registered with or without a license we also need to exclude them with or without a license
- Release data should not be exposed to the content-api or graphql
- Run yarn setup
- Run yarn develop in examples/getstarted
- Go to localhost:1337/graphql, click schema on the right hand side
- Search for 'release'
- You should not find anything related to releases in the schema
Do the above with and without a license

fix(content-releases): exclude release content-types from graphql

---

examples/getstarted/src/api/address/content-types/address/schema.json
packages/core/admin/admin/src/content-manager/pages/EditView/EditViewPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/DocumentActions.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/Header.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/tests/Header.test.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/ListViewPage.tsx
packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/content-type-builder/admin/src/components/FormModal/contentType/contentTypeForm.ts
packages/core/content-type-builder/admin/src/components/FormModal/contentType/createContentTypeSchema.ts
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx

* adds the option in the CTB to disable D&P
* refactors the EditView/Header to not show a status if it does not exist as a prop
* does not add the status column to the list-view if D&P is disabled
* does not display tabs or enable status query to manage tabs in the edit-view if D&P is disabled
* does not display the status in the locale picker from i18n
* resolves CONTENT-2224
* resolves CONTENT-2232
* resolves CONTENT-2233
* resolves CONTENT-2234
* resolves CONTENT-2236
* resolves CONTENT-2237

chore: refactor CM, CTB & i18n to accomodate option D&P

---

packages/core/admin/admin/src/StrapiApp.tsx
packages/core/admin/admin/src/components/ErrorElement.tsx
packages/core/core/src/middlewares/security.ts
packages/core/strapi/src/node/vite/watch.ts

* sets the security policy for admin routes with GET methods to only run in development mode and allow `http` as a `content-src`.
* Adds global error element incase of catastrophic failure.
* Vite uses a websocket in watch-mode to get it's HMR updates, when we use the CTB we shut the server down and restart it, this disconnects the socket and the client cannot reconnect because it uses `http` to connect.
* Better UX
* using this experimental version – `0.0.0-experimental.171e4d8ec72685e5302378f337dc9073c35a9100`
* run `yarn develop`
* go to CTB
* add a content-type so the server restarts
* the app should be navigable to all pages like the EditView which is dynamically fetched
* you can verify because there will not be a continuous error saying "Refused to connect...." *AFTER* the server …

fix(strapi): vite crashes because files can't be found

---

packages/core/core/src/migrations/draft-publish.ts

Set the updated at value using new Date when enabling DP on a content type

fix: updated at value when enabling DP

---

e2e/app-template/config/features.js
examples/getstarted/config/features.js
packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseModal.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/pages/ReleasesPage.tsx
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/server/src/__tests__/index.test.ts
packages/core/content-releases/server/src/bootstrap.ts
packages/core/content-releases/server/src/destroy.ts
packages/core/content-releases/server/src/services/index.ts
packages/core/content-releases/server/src/services/release.ts

Remove all future flags related to scheduling following the stable release of the feature.

feat(content-releases): removing scheduling future flag for stable release

---

packages/core/types/src/index.ts

Mark strapi.documents as a beta api

chore: mark doc service as beta

---

packages/core/content-releases/server/src/controllers/__tests__/release-action.test.ts
packages/core/content-releases/server/src/controllers/release-action.ts
packages/core/content-releases/server/src/routes/release-action.ts
packages/core/content-releases/server/src/services/validation.ts
packages/core/content-releases/shared/contracts/release-actions.ts

Add a new endpoint & controller to add multiple entries to a release. This endpoint should not fail if there is one entry already on the release.
You need to run the project with a valid EE license and you can try to make different calls to the POST `/content-releases/:releaseId/actions/bulk` endpoint.
To know the form of the request to do please check the type associated: 
```ts
/**
* POST /content-releases/:releaseId/actions/bulk - Create multiple release actions
*/
export declare namespace CreateManyReleaseActions {
export interface Request {
params: {
releaseId: Release['id'];
};
body: Array<{
type: ReleaseAction['type'];
entry: {
id: ReleaseActionEntry['id'];
locale?: ReleaseActionEntry['locale'];
contentType: Common.UID.ContentType;
};
}>;
}
export interface Response {
data: …
```

feat(content-releases): new create many release actions endpoint

---

packages/core/content-type-builder/server/src/services/builder.ts

Restricts the attribute name 'locale' since we use it internally
if a user creates an attribute called 'locale' it causes weird / breaking issues in Strapi
Try to create an attribute called 'locale' and see that you get an error that it would conflict with existing functionality

fix: reserve attribute name 'locale' in CTB

---

.github/workflows/tests.yml
docker-compose.dev.yml
docker-compose.test.yml

removes mysql 5 and uses mysql 8
Strapi 5 drops support mysql 5 so we don't need to test it. Most of it had been removed already but there were still these few things remaining.
github CI should still work

ci: use only mysql 8 in workflows

---

.github/workflows/contributor-doc.yml
packages/core/admin/admin/src/components/Providers.tsx
packages/core/admin/admin/src/content-manager/components/ConfigurationForm/Form.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/Header.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/components/Header.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/tests/ListConfigurationPage.test.tsx
packages/core/admin/admin/src/content-manager/pages/ListView/ListViewPage.tsx
packages/core/admin/admin/src/core/store/configure.ts
packages/core/admin/admin/src/core/store/middleware.ts
packages/core/admin/admin/src/features/BackButton.tsx
packages/core/admin/admin/src/features/tests/BackButton.test.tsx
packages/core/admin/admin/src/index.ts
packages/core/admin/admin/src/pages/Settings/components/Tokens/FormHead.tsx
packages/core/admin/admin/src/pages/Settings/pages/ApiTokens/EditView/EditViewPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/CreatePage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/EditPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/TransferTokens/EditView.tsx
packages/core/admin/admin/src/pages/Settings/pages/Users/EditPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/WebhookForm.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/CreatePage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/EditPage.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/ReviewWorkflows/components/Layout.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-type-builder/admin/src/pages/ListView/ListView.tsx
packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/ListView.test.tsx.snap
packages/plugins/users-permissions/admin/src/pages/Roles/pages/EditPage.jsx
packages/plugins/users-permissions/admin/src/pages/Roles/pages/ListPage/index.jsx

* introduces a universal back-button that can / should be implemented on all pages, it records the internal app state so it won't cause the user to leave the application, instead it disables itself. It also works across the entire app without needing to know paths.
* user-story from design
* resolves CONTENT-2173

feat(admin): create internal history for universal back button

---

api-tests/core/content-manager/find-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-available-relations.test.api.js
api-tests/plugins/i18n/content-manager/find-existing-relations.test.api.js
examples/getstarted/src/index.js
packages/core/admin/admin/src/components/Form.tsx
packages/core/admin/admin/src/content-manager/pages/ComponentConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/admin/admin/src/content-manager/pages/ListConfiguration/ListConfigurationPage.tsx
packages/core/admin/admin/src/content-manager/services/relations.ts
packages/core/admin/admin/src/translations/en.json
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/content-manager/server/src/services/document-metadata.ts
packages/core/content-manager/shared/contracts/relations.ts

CM broke when loading an entry with enabled I18n but disabled DP

fix: fix cm metadata when dp is disabled

---

packages/core/admin/admin/src/components/ErrorElement.tsx

* tweaks copy & design for global error element
* adds copy to clipboard button for error
* make your app error e.g. `throw new Error("ahhhhh")`

chore: design-updates

---

packages/core/content-manager/server/src/services/document-manager.ts
packages/core/content-manager/server/src/services/populate-builder.ts
packages/core/content-manager/server/src/services/utils/populate.ts
packages/core/types/src/types/core/config/server.ts
packages/generators/app/src/resources/files/ts/config/server.ts

CM api returns count of relations (was returning populated relations). Also I am removing the following:
In order to always send populated relations to webhooks, we were using a complicated logic to populate relations on the backend and then return the count.
Not only that , we provided a config `webhooks.populateRelations` to disable this behaviour and improve performance. 
I am removing that in v5 because:
- I will refactor webhooks so they always send populated relations no matter what.
- Probably nobody knows about this
- It adds a lot of complexity

feat: count cm relations

---

api-tests/core/strapi/api/relations.test.api.js
packages/core/core/src/services/document-service/__tests__/middlewares.test.ts
packages/core/core/src/services/document-service/index.ts
packages/core/core/src/services/document-service/middlewares/errors.ts
packages/core/core/src/services/document-service/middlewares/index.ts
packages/core/core/src/services/document-service/middlewares/middleware-manager.ts

We were not handling database errors on the document service, so any thrown error on DB resulted in a 500 status error on the APIs.

feat: handle db errors on document service

---

packages/utils/upgrade/resources/examples/disable-jsx-buttons.code.ts
packages/utils/upgrade/src/modules/project/__tests__/project.test.ts
packages/utils/upgrade/src/modules/project/constants.ts
packages/utils/upgrade/src/modules/project/project.ts

- Added .jsx and .tsx files support for codemods
- Updated the tests
Allow running react migration for the admin
Put the following snippet into a codemod (`packages/utils/upgrade/resource/<version>/my-codemod.code.ts`) and execute it for the `getstarted` project. It should update the `src/admin/index.jsx` file 
```ts
import type { Transform } from 'jscodeshift';
import { relative } from 'node:path';
const transform: Transform = (file, api) => {
const j = api.jscodeshift;
const root = j.withParser('JSX')(file.source);
const isReactFile = file.path.endsWith('.jsx') || file.path.endsWith('.tsx');
if (!isReactFile) {
return root.toSource();
}
const fileName = relative(process.cwd(), file.path);
console.log(`Found React file: ${fileName}`);
const buttons = root.findJSXElements('Button'); …
```

Upgrade - Add support for React codemods

---

packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/services/release.ts

Fix multiple problems related to how we invalidate the cache on releases page.
Test all the cases:
1. When deleting an entry from a release the release status should be updated
2. If you go from the Edit View to the Release Details page the status should be the most updated and not one on the cache.

fix(content-releases): fix cache issues

---

packages/core/strapi/src/node/vite/watch.ts

We were manually checking if the requested url was from a bit chunk file. This is actually handled automatically by vite middlewares, and apparently doesn't have the "Failed to dynamically load..." error

fix: failed to dynamically load chunk

---

packages/utils/upgrade/resources/codemods/5.0.0/sqlite3-to-better-sqlite3.json.ts

fixes codemod to not add better-sqlite3 to all projects; only when a sqlite package was removed
currently ugprade tool is adding better-sqlite3 to all strapi projects regardless of original packages used
only projects that were previously using `sqlite3` will add `better-sqlite3`
projects such as those using mysql and postgres should not have anything added

fix: only add better-sqlite3 package when needed

---

packages/core/core/src/Strapi.ts

makes the strapi default log level 'http' instead of 'silly' (v4) or 'info' (previous v5)
so that admin http requests appear in server logs

chore: make default log level http

---

packages/core/core/src/Strapi.ts

sets the default server log level to 'http'
'info' was too high and preventing admin requests from being seen

chore: set default log level to 'http'

---

packages/core/core/src/services/document-service/transform/relations/utils/dp.ts

Make relation connecting status handling a bit smarter on the backend side.
Frontend sends status like "Modified" or "Published" when in reality the relation needs to be conected to the "Draft" state.  Before this PR, if you tried to connect a relation in a "Modified" state in the CM, you would see an error like:
This work assumes:
- If source and target content types of a relation have DP enabled
-  Then the relation target must match the source status (draft->draft, published->published)
That way, regardless of the sent status, this will always connect the relation to the correct status

feat: make relation status handling smarter

---

packages/plugins/i18n/server/src/migrations/__tests__/content-type.test.ts
packages/plugins/i18n/server/src/migrations/content-type/disable/index.ts
packages/plugins/i18n/server/src/migrations/content-type/enable/index.ts

Locales other than the default one were deleted when disabling i18n, but the left default locale was not set to null.

chore: remove locale when disabling i18n

---

packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx
packages/core/content-type-builder/admin/src/components/DataManagerProvider/constants.ts
packages/core/content-type-builder/admin/src/components/DataManagerProvider/reducer.ts
packages/core/content-type-builder/admin/src/contexts/DataManagerContext.ts
packages/core/content-type-builder/admin/src/pages/ListView/ListView.tsx

- forces ctb to reload after save
- After saving components in the ctb, state is not refreshing unless the page is reloaded manually
- create or update a contentType it should work properly
fix #19378

fix: reload ctb after save

---

api-tests/core/content-manager/find-relations.test.api.js
packages/core/admin/admin/src/content-manager/pages/EditView/components/DocumentActions.tsx
packages/core/admin/admin/src/content-manager/pages/EditView/components/FormInputs/Relations.tsx
packages/core/admin/admin/src/content-manager/services/api.ts
packages/core/admin/admin/src/content-manager/services/documents.ts
packages/core/admin/admin/src/content-manager/services/relations.ts
packages/core/content-manager/server/src/controllers/relations.ts

* sends the full relation back on the disconnect array
* I should have done it to begin with, but you can't disconnect a relation correctly without the dimensions

fix(cm): send status & locale with disconnect array

---

packages/core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.tsx
packages/core/content-type-builder/admin/src/components/DataManagerProvider/constants.ts
packages/core/content-type-builder/admin/src/components/DataManagerProvider/reducer.ts
packages/core/content-type-builder/admin/src/contexts/DataManagerContext.ts
packages/core/content-type-builder/admin/src/pages/ListView/ListView.tsx

- CTB refetches after save
- After saving components or contenttypes in the ctb, state is not refreshing unless the page is reloaded manually
- create or update a contentType it should work properly
duplicate of #19811 for V5 beta

fix: make ctb refetch data after save or update

---

.github/workflows/commitlint.yml
.github/workflows/tests.yml

Updates some lingering deprecated versions that weren't updated before
in April github will be updating actions servers to node 20, so we risk some of them breaking if we're using actions based on node 16
github ci should all still work
I'm making a similar one for develop branch too after this

chore(tooling): update deprecated github actions

---

packages/core/core/src/Strapi.ts
packages/core/strapi/src/node/develop.ts

- Logs when the server shuts down and starts up
- adds more exceptions for log files to the develop watcher
In general, even though we visually have the startupLogger(), it's important to have this in log files so we can track when these quite important events actually happen
In `develop`in particular, we log when files change, but not when the restart is triggered. That means we get multiple notifications for files changing but have no idea when the restart actually happens or completes. We need to see the actual events happening to know when they've started/completed.
use `yarn develop` and touch multiple files, then rm them all at once. You'll see that you still get multiple logs about the files changing, and then afterwards you get the singular log about server stopping/starting
Let …

enhancement: log when server restarts

---

packages/core/content-manager/server/src/history/constants.ts
packages/core/content-manager/server/src/history/services/__tests__/history.test.ts
packages/core/content-manager/server/src/history/services/__tests__/utils.test.ts
packages/core/content-manager/server/src/history/services/history.ts
packages/core/content-manager/server/src/history/services/utils.ts
packages/core/content-manager/shared/contracts/history-versions.ts

- Add a meta object to `findVersionsPage` containing unknown attributes 
- Refactor tests into describes
- So we can determine what can and cannot be restored
- Go to a contentType schema and add an attribute like `newField`
- Make a request to findVersionsPage
- You should have a `meta.unknownAttributes` object with:
```
{
added: {
newField: {type: 'string'}
}
}
```
- Remove an attribute and you should have
```
{
added: {
newField: {type: 'string'}
},
removed: {
fieldYouRemoved: {type: 'string'}
},
}
``` 
- Rename an attribute and you should have
```
{
added: {
newField: {type: 'string'}
renamedField: {type: 'string'}
},
removed: {
fieldYouRemoved: {type: 'string'}
fieldYouRenamed: : {type: 'string'}
},
}
```

feat(history): diff schemas to get unknown attributes

---

packages/utils/upgrade/resources/codemods/5.0.0/dependency-remove-strapi-plugin-i18n.json.ts

Add a new code mod that removes the `@strapi/plugin-i18n` package in the package.json dependencies of a Strapi project.
- if the dependency doesn't exist, ignore
- if the dependency exists, remove it
v5 strapi/strapi has a hard dependency on i18n, making useless the need to have it in the project dependencies
- Got to getstarted
- Run `../../packages/utils/upgrade/bin/upgrade.js codemods`, then only select `dependency remove strapi plugin i18n`
- You can play with the @strapi/plugin-i18n dep in the package.json and try again. It should work according to the description above

[codemod] Remove @strapi/plugin-i18n from the Project package.json

---

packages/utils/upgrade/resources/codemods/5.0.0/dependency-upgrade-react-router-dom.json.ts

Add a new code mod that updates the react-router-dom version in the package.json dependencies of a Strapi project.
- if the dependency doesn't exist, add it
- if the dependency exists but isn't valid, ignore
- if the dependency exists but already satisfies the new range, ignore
- if the dependency exists and does not satisfy the new range, update it with `^6.0.0`
Note: Should we manually ignore plugins? People should be responsible enough to know not to run this codemod on plugin, but... what do you think?
Note: Currently the codemod is named "dependency upgrade react router dom". If you've better suggestion, feel free to speak up :slightly_smiling_face: 
v5 uses a newer version of react-router-dom that’s not compatible with v4 one.
New apps are generated using ^6.0.0.
- Got to getstarted …

[codemod] Set react-router-dom version in the Project package.json

---

packages/core/types/src/schema/index.ts

It's now possible to do `const foo: Schema.Attributes;`.
It was previously annoying to type a structure representing the attributes of a schema (based on the schema registry).
Devs had to either use `Struct.SchemaAttributes` or `Record<string, Schema.Attribute.AnyAttribute>`

[Type System] Add a Default Param to Schema.Attributes 

---

packages/core/admin/admin/src/index.ts

Remove a duplicate export for StrapiApp in strapi/admin
test:ts:front is currently failing on v5/main
`yarn run test:ts:front`
Probably comes from https://github.com/strapi/strapi/pull/19860

Fix Duplicate Export in strapi/admin

---

e2e/tests/content-manager/listview.spec.ts

* skip list-view e2e for bulk actions
* we haven't implemented bulk actions in v5, so they will always fail!

chore: skip bulk actions test because they're not implemented in v5

---

packages/utils/api-tests/strapi.js

Changes the default log level for createStrapiInstance to 'warn'
Now that we're adding more logging, they are appearing in our API tests and polluting the test logs. Our tests should be mocking their own logger, but that would be a huge refactoring, and this works for now.
Our test utility for creating an instance should do something like automatically mock the logger, and people writing tests should be made aware of that and how to access those mocks directly instead of mocking console methods.
As long as the API tests pass without showing a bunch of info logs with every test, it should be fine. Currently running them, and expecting some of them to fail if they're `expect`ing the output of certain logs that won't appear now.
Update: tests pass! Yay!

test: change default test log level to warn

---

packages/core/core/src/core-api/controller/index.ts
packages/core/core/src/services/__tests__/content-api-permissions.test.ts
packages/core/core/src/services/content-api/index.ts
packages/core/types/src/modules/content-api.ts
packages/core/types/src/modules/sanitizers.ts
packages/core/types/src/modules/validators.ts
packages/core/upload/server/src/controllers/content-api.ts
packages/core/utils/src/index.ts
packages/core/utils/src/sanitize/index.ts
packages/core/utils/src/traverse-entity.ts
packages/core/utils/src/validate/index.ts
packages/plugins/graphql/server/src/services/builders/mutations/collection-type.ts
packages/plugins/graphql/server/src/services/builders/mutations/single-type.ts
packages/plugins/graphql/server/src/services/builders/resolvers/association.ts
packages/plugins/graphql/server/src/services/builders/resolvers/component.ts
packages/plugins/graphql/server/src/services/builders/resolvers/pagination.ts
packages/plugins/graphql/server/src/services/builders/resolvers/query.ts
packages/plugins/i18n/server/src/controllers/__tests__/locales.test.ts
packages/plugins/i18n/server/src/controllers/locales.ts
packages/plugins/users-permissions/server/controllers/auth.js
packages/plugins/users-permissions/server/controllers/user.js
packages/plugins/users-permissions/server/controllers/validation/__tests__/auth.test.js
packages/utils/api-tests/builder/index.js

Make utils generic & initialize API sanitization & validation inside the strapi app & expose with the strapi.contentAPI service
To remove the dependency on strapi/core from the utils to type things & prevent circular dependencies

chore: inverse control of contentAPI sanitize & validate

---

packages/core/content-releases/admin/src/components/ReleaseModal.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

On frontend, when we are creating the "UTC0" timestamp to send to the backend we have an error generating the UTC time.
Before we were doing this logic:
```
const formattedDate = parse(time, 'HH:mm', new Date(date));
```
when executing `new Date(date)`, if timezone is not defined on `date`, the constructor would assume that we are sending a date in UTC, and considering this is executed on client this would change the date to the system timezone (the one from the user executing this). 
So, what's the problem? If you are in a timezone with a positive offset you don't see any problem because:
- If you are in `Europe/Madrid` (UTC+01). Then `new Date('2024-03-21')` is translated to "2024-03-21 01:00:00 UTC+01" (We still have the same day, then we replace the time and everything is fine)
But, …

fix(content-releases): fix creation of utc time based when sending to back

---

packages/core/admin/server/src/services/permission/permissions-manager/sanitize.ts
packages/core/admin/server/src/services/permission/permissions-manager/validate.ts
packages/core/content-manager/server/src/services/document-manager.ts
packages/core/content-manager/server/src/services/utils/configuration/__tests__/settings.test.ts
packages/core/content-manager/server/src/services/utils/configuration/settings.ts
packages/core/content-manager/server/src/services/utils/populate.ts
packages/core/core/src/services/content-api/index.ts
packages/core/core/src/services/document-service/transform/populate.ts
packages/core/core/src/services/document-service/transform/relations/extract/data-ids.ts
packages/core/core/src/services/document-service/transform/relations/transform/data-ids.ts
packages/core/upload/server/src/services/extensions/content-manager/entity-manager.ts
packages/core/upload/server/src/services/extensions/utils.ts
packages/core/upload/server/src/services/upload.ts
packages/core/utils/src/__tests__/query-populate.test.ts
packages/core/utils/src/sanitize/index.ts
packages/core/utils/src/sanitize/sanitizers.ts
packages/core/utils/src/traverse-entity.ts
packages/core/utils/src/traverse/factory.ts
packages/core/utils/src/traverse/index.ts
packages/core/utils/src/traverse/query-filters.ts
packages/core/utils/src/traverse/query-populate.ts
packages/core/utils/src/traverse/query-sort.ts
packages/core/utils/src/types.ts
packages/core/utils/src/validate/index.ts
packages/core/utils/src/validate/validators.ts
packages/plugins/i18n/server/src/controllers/__tests__/locales.test.ts
packages/plugins/users-permissions/server/utils/sanitize/sanitizers.js

- Removes strapi global from traversal utils
- Next iteration will make the traversal more generic and move the non generic logic in a dedicated place with the right context
To make the utils agnostic

chore: remove strapi global from traversal utils

---

packages/plugins/graphql/server/src/bootstrap.ts

Allows get request. I couldn't find any reason to keep the old code arround.

chore: allow graphql get request with authentication

---

packages/core/content-manager/server/src/controllers/relations.ts

Display main field of relation instead of it's id when lazy loading them.
Fixes https://github.com/strapi/strapi/issues/19625

fix: show name of relations when lazy loading them

---

packages/core/content-manager/server/src/controllers/relations.ts

Copy of another pr that was approved

fix: relations lazy loading

---

api-tests/plugins/graphql/crud.test.api.js
api-tests/plugins/graphql/utils.test.api.js
packages/plugins/graphql/server/src/bootstrap.ts

This removes a line that wasnt required, that blocked GET queries from being authenticated on `/graphql`.
I've added a test to show, that with no authentication, the graphql playground still loads.
GET queries are often advantagous for caching, cdns, etc.
There is an API test that checks it, also, https://graphql.org/learn/serving-over-http/#get-request
n/a

fix(plugin-graphql): allow to use GET queries for graphql

---

cli-tests/scripts/dts-export.js
e2e/scripts/dts-export.js
packages/core/core/package.json
packages/core/core/src/Strapi.ts
packages/core/core/src/index.ts
packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/assets.test.ts
packages/core/strapi/packup.config.ts
packages/core/strapi/src/cli/commands/admin/__tests__/create-user.test.ts
packages/core/strapi/src/cli/commands/admin/__tests__/reset-user-password.test.ts
packages/core/strapi/src/cli/commands/admin/create-user.ts
packages/core/strapi/src/cli/commands/admin/reset-user-password.ts
packages/core/strapi/src/cli/commands/components/list.ts
packages/core/strapi/src/cli/commands/configuration/dump.ts
packages/core/strapi/src/cli/commands/configuration/restore.ts
packages/core/strapi/src/cli/commands/console.ts
packages/core/strapi/src/cli/commands/content-types/list.ts
packages/core/strapi/src/cli/commands/controllers/list.ts
packages/core/strapi/src/cli/commands/hooks/list.ts
packages/core/strapi/src/cli/commands/middlewares/list.ts
packages/core/strapi/src/cli/commands/policies/list.ts
packages/core/strapi/src/cli/commands/report.ts
packages/core/strapi/src/cli/commands/routes/list.ts
packages/core/strapi/src/cli/commands/services/list.ts
packages/core/strapi/src/cli/commands/start.ts
packages/core/strapi/src/cli/commands/ts/generate-types.ts
packages/core/strapi/src/cli/utils/data-transfer.ts
packages/core/strapi/src/node/create-build-context.ts
packages/core/strapi/src/node/develop.ts
packages/utils/api-tests/strapi.js

Inits facades for strapi to slowly remove the global & improve public interface naming

chore: cleanup public interface of strapi/strapi

---

packages/core/admin/package.json
packages/core/upload/package.json
packages/plugins/cloud/package.json
packages/plugins/color-picker/package.json
yarn.lock

* ensures all the peer deps for the strapi packages is `^5.0.0`
* afaik this should pass peer-dep checks when the versions are `beta` or `alpha`, but the documentation wasn't clear. Either way, they definitely should be min 5.
* resolves #19903

chore(deps): fix peer-deps to be 5 upwards

---

packages/core/admin/package.json
packages/core/content-releases/package.json
packages/core/content-type-builder/package.json
packages/core/email/package.json
packages/core/upload/package.json
packages/plugins/cloud/package.json
packages/plugins/color-picker/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json
yarn.lock

* allow pre-releases in peer-deps
* users should be able to use `npm` and `pnpm`

chore: allow pre-releases in deps

---

packages/core/admin/package.json
packages/core/admin/server/src/validation/project-settings.ts
packages/core/utils/package.json
packages/core/utils/src/index.ts
packages/core/utils/src/zod.ts
packages/utils/eslint-config-custom/back/typescript.js
yarn.lock

Introduce zod. use the same error formatting as yup so we can incrementally replace yup without breaking the response format.

chore: init zod usage

---

e2e/tests/admin/signup.spec.js
e2e/tests/content-manager/editview.spec.ts
e2e/utils/shared.ts

closes the "saved" notification box
the tests run fast enough that multiple "saved" boxes appear at once, so the checks for finding one saved box fail because there are more than one
e2e tests should pass
DX-1295

test(e2e): close 'saved' notification box after confirming it exists

---

CONTRIBUTING.md
docs/docs/api/container.mdx
docs/docs/docs/01-core/data-transfer/02-providers/01-source-providers.md
docs/docs/docs/01-core/data-transfer/02-providers/02-destination-providers.md
docs/docs/docs/01-core/database/01-relations/reordering.md
docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Upgrades to docusaurus 3.1.1
Fixes build issues from it
New features, stricter parsing, and we're having vercel deploy issues on `v5/main` which this upgrade should help detect the source of
docs should still build properly and deploy to vercel

docs: upgrade to docusaurus 3.1.1

---

packages/core/admin/admin/src/StrapiApp.tsx

Moves the v5 NotFoundPAge into the AuthenticatedLayout of the Admin panel.
_Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.18.0 darwin arm64
Edition: Community
Database: sqlite_
Fixes (see screenrecording):
1. Showing the not-found page in full browser width, so missing the left menu.
2. Not redirecting an unauthenticated user to login for a not-found route.
https://github.com/strapi/strapi/assets/31662805/e14b9cb7-09a9-4e32-a864-be800f7e5992
1. Login and navigate to /admin/not-existing-route
2. The page should show the `LeftMenu` and `NotFoundPage`
3. Logout and navigate to /admin/not-existing-route
4. User should be redirected to /auth/login
https://github.com/strapi/strapi/assets/31662805/4c745e84-1eef-44d7-b138-65e2 …

[v5] fix: move NotFoundPage into authenticated admin panel routes

---

packages/core/content-releases/admin/src/components/ReleaseModal.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

On edit release error, don't close modal and user should be able to edit details. 
Previously it used to close irrespective of the status
On editing release, if error appears it should not close the modal.

fix(releases): On edit release error dont close modal 

---

packages/core/admin/admin/src/render.ts
packages/core/admin/admin/src/utils/tests/urls.test.ts
packages/core/admin/admin/src/utils/urls.ts

* enforces the `BACKEND_URL` to always be an absolute URL falling back to use `window.location.origin` in cases where it's relative or for some reason does not exist.
* the `url` property of the `server` config file can be relative and this currently breaks the `appendSearchParams` helper. Realistically, we always want it to be absolute.
* resolves #18175
* resolves DX-1312

fix(admin): force an absolute URL if the BACKEND_URL is relative

---

packages/core/content-manager/admin/src/history/components/tests/VersionHeader.test.tsx
packages/core/content-manager/server/src/history/services/__tests__/history.test.ts
packages/core/content-manager/server/src/history/services/history.ts
packages/core/content-manager/shared/contracts/history-versions.ts

- Make the `meta.unknownAttributes` constant in the response
- Use the strapi type for schema attributes
- To simplify and have a more predictable response object
- Everything should work the same. You should always be able to access `versions.meta.unknownAttributes.added | .removed`

chore(history): simplify the meta object

---

packages/core/upload/server/src/services/upload.ts

Adds the name validation that was accidentally lost during a merge conflict resolution from `develop -> v5/main`
Tests are failing because some code was removed
Tests should pass with upload file name validation

fix: name validation

---

packages/core/database/src/migrations/common.ts
packages/core/database/src/migrations/index.ts
packages/core/database/src/migrations/internal.ts
packages/core/database/src/migrations/users.ts

Allows to dynamically register internal migrations:
```ts
strapi.db.migrations.providers.internal.register({
name: 'v5-train'
up: () => {}
})
```
The order of the migrations will always be:
User migrations -> Db Internal migrations ->  Dynamically registered internal migrations
https://github.com/strapi/strapi/pull/19813
It was required to use the document service in one of the db migrations.

feat: register internal migrations dynamically

---

packages/plugins/i18n/package.json
yarn.lock

* removes the `@strapi/strapi` dependency from `i18n`
* it was creating a circular dep and it's not required

fix(i18n): remove strapi dep to fix circular deps

---

packages/core/upload/package.json
yarn.lock

Update sharp package to version v0.33.3
New version requires libvips v8.15.1, what can I do about this?
Also they drop support for node.js 14, 16.
Bacause of bug in sharp https://github.com/lovell/sharp/issues/3893
It is platform dependent. (old Intel (before 2009) and QEMU-emulated CPUs)
Not sure how to test that...
#19310

Update sharp package to version v0.33.3

---

.gitignore

ignores the `.nx` folder
doing a build currently shows the nx cache as new files in git
build and you shouldn't see .nx folders in git status

chore: ignore nx cache

---

.github/filters.yaml
examples/getstarted/src/api/kitchensink/content-types/kitchensink/schema.json
examples/getstarted/src/api/tag/content-types/tag/schema.json
packages/core/database/src/metadata/relations.ts
packages/core/database/src/query/helpers/join.ts
packages/core/database/src/query/helpers/where.ts
tests/api/core/upload/content-api/upload.test.api.js

> ⚠️  Needs testing & qa
- Implements https://github.com/strapi/strapi/issues/12225 
- Add support for deep media (polymorphic) queries like `filters[media][name][$contains]=xxx`
- Support shortcut relational queries `filters[relation] = ${subQuery}` => will auto apply to the id
- Improve DX
- Follow the examples in the issue mentionned. 

feat: support media deep filtering & relation shortcut filters

---

packages/plugins/cloud/admin/src/pages/HomePage.tsx

It replaces the imports of Link to use the v2 of the `@strapi/design-system`
To use the latest version of the Link component.
Check that the frontend tests are passing and that the Cloud HomePage still works as expected
CONTENT-1485

Refactor Link to v2

---

packages/core/content-manager/admin/src/history/components/VersionContent.tsx
packages/core/content-manager/admin/src/history/components/tests/VersionHeader.test.tsx
packages/core/content-manager/server/src/history/services/__tests__/history.test.ts
packages/core/content-manager/server/src/history/services/history.ts
packages/core/content-manager/shared/contracts/history-versions.ts

**_ℹ️  This PR replaces #19786, as the git history became too much of a mess on that one_**
- Saves only the ID in the data key when history versions are related
- On retrieval, for each relation and media, populate an object with results and missingCount
- This PR starts messing around with the frontend too (relation input in history), but it's mostly pseudocode to make sure the approach works. The actual implementation is a separate ticket.
We need to display relations in history. And showing that some relations were deleted requires special handling.
🚨 Because of the data structure change, your app may crash with pre-existing history versions 🚨
Create history versions with some relations. View history, you should see the data. Go delete the related content, you should see that too in …

enhancement: add relation data to history versions response

---

packages/core/strapi/package.json
packages/core/types/package.json
yarn.lock

Reverts the upgrade made in https://github.com/strapi/strapi/pull/19921 due to https://github.com/strapi/strapi/issues/20033
CORs broken in 4.22.0 due to the @koa/cors upgrade
Reconfigure Strapi CORs middleware with a custom origin and ensure you can access the admin panel and fetch requests from external API
Fix https://github.com/strapi/strapi/issues/20033

Chore: Revert @koa/cors upgrade to 5.0.0 due to breaking cors middleware

---

packages/core/admin/package.json
packages/core/helper-plugin/package.json
packages/utils/pack-up/package.json
yarn.lock

- Updates `vite` from `5.0.11` to `5.0.13` to patch https://www.npmjs.com/advisories/1095466 and https://www.npmjs.com/advisories/1096873 
- Updates `webpack-dev-middleware` from `6.1.1` to `6.1.2` to patch https://www.npmjs.com/advisories/1096730
We were not vulnerable to these issues but upgrading to clean up the audit reports
fixes: #20032
Run an audit either `yarn audit` or `yarn npm audit --all`
Note that neither of these packages have complete change logs to compare differences, it's assumed those entries were omitted for security disclosure:
- Vite: Missing changelog entry for 5.0.13: https://github.com/vitejs/vite/blob/v5.2.8/packages/vite/CHANGELOG.md#5011-2024-01-05
- webpack-dev-middleware: Missing changelog entry for 6.1.2: …

Chore: Update vite and webpack-dev-middleware

---

packages/plugins/i18n/server/src/controllers/validate-locale-creation.ts

An i18n middleware was faliling when trying to clone a document.
The clone request had an empty body, which was an unexpected edge case.
Fixes 
Also, the content manager does not send any locale when duplicating an entry, I will create another ticket for that.

fix: prevent empty body when cloning

---

package.json

- removes `watch` script because it wasn't useful (only ran 3 random watch scripts in parallel with the rest pending)
- adds `build:watch` script that uses `nx watch --all`
Note that this still is not great for us because nx tries to be smart and rebuilds every project it depends on, but since we have circular dependencies, it causes the entire chain to be rebuilt every time. So, it's only a small improvement, but once we fix our circular deps this should be a good way to watch the entire monorepo for changes.
watch was broken, and sometimes it's nice to watch many different projects especially when working on changes in multiple projects at once
DX-1359

chore: add watch script for all projects

---

packages/core/content-releases/server/src/migrations/index.ts

Fix boot error when i18n is not installed

fix: fix boot issue when removing i18n from an app

---

packages/core/content-manager/admin/src/history/components/VersionInputRenderer.tsx

- Fixes an issue with the different cases for missing relations
- To show missing relations
- Always show relation results
- Show Relations results + missing relations alert
- No relation results and now missing relations show no relations

fix(history): update relations display

---

jest-preset.front.js
jest-preset.unit.js
package.json
yarn.lock

* installs `prettier@2` to be used by `jest` until `jest@30` is released
* you can't redo inline snapshots without it

chore(deps): install prettier@2 *just* for jest snapshots

---

tests/e2e/tests/content-releases/releases-page.spec.ts

Removes an instruction inside the e2e that keeps failing and it doesn't add too much value to the e2e test
Locally it works but if you try to run it line by line than you have a failing test because of the releaseColumn variable having value undefined, I tried different ways to wait for a meaningful value in the releaseColumn value but with no success, at the end the test is looking for the number of options and label of the options in the dropdown so I removed the check of the number of options and just check the labels
We are having issues in the CI
Run locally the e2e test with a strapi license to run EE e2e tests
In particular 
`STRAPI_LICENSE=... yarn test:e2e --domains=content-releases -- releases-page.spec.ts`
You can find an example of the failing e2e test here …

fix(content-releases): fix e2e failing test

---

packages/core/core/src/services/document-service/attributes/index.ts
packages/core/core/src/services/document-service/components.ts
packages/core/core/src/services/document-service/entries.ts
packages/core/core/src/services/document-service/index.ts
packages/core/core/src/services/document-service/internationalization.ts
packages/core/core/src/services/document-service/middlewares/middleware-manager.ts
packages/core/core/src/services/document-service/repository.ts
packages/core/types/src/modules/documents/component-extension.ts
packages/core/types/src/modules/documents/index.ts
packages/core/types/src/modules/documents/middleware.ts
packages/core/types/src/modules/documents/service-instance.ts
tests/api/core/strapi/api/populate/sanitize.test.api.js
tests/api/core/strapi/document-service/middlewares.test.api.ts

Adds more entries functions & add some more cleanups to make component & type simpler

Continue extending entries code

---

packages/core/admin/admin/src/StrapiApp.tsx

It fixes the SSO routes, because it wasn't rendering the appropriate component because of a mismatch in the router. 
To be able to use SSO
To check it in a Strapi project, make sure it is EE, and you have configured and SSO Provider. Do the login and and the logout and check it works. Check also that after doing the login the localStorage has the cookie value and the cookie value is deleted.
DX-1322

Fix SSO Routes

---

packages/core/admin/ee/admin/src/pages/SettingsPage/pages/SingleSignOnPage.tsx

Uses the `canRead` property exported from the useRBAC hook
To be able to fetch the roles and the information in the SSO Settings page
Try setting up an SSO Provider

Use the right name in useRBAC

---

packages/core/admin/ee/admin/src/pages/SettingsPage/pages/tests/SingleSignOnPage.test.tsx

Fixes the SSO failing tests after the `useRBAC` renaming
To make the frontend Tests pass
Check that unit frontend tests pass
https://github.com/strapi/strapi/pull/20105

Fix SSO Frontend Test

---

examples/getstarted/package.json
examples/kitchensink/package.json
packages/generators/app/src/utils/db-client-dependencies.ts
yarn.lock

Upgrades the MySQL2 package from 3.6.0 to 3.9.4
Changelog: https://github.com/sidorares/node-mysql2/blob/master/Changelog.md
Related to 3 dependabot alerts to a vuln we aren't directly susceptible too however some users may hit it if they use direct queries.
Related PRs for the vuln: 
- https://github.com/sidorares/node-mysql2/pull/2572
- https://github.com/sidorares/node-mysql2/pull/2424
Test against clients accepting the mysql2 package (MySQL 8+ and MariaDB 10.5+
N/A

Chore: Upgrade mysql2 from 3.6.0 to 3.9.4

---

packages/core/content-type-builder/server/src/services/builder.ts

Adds reserved attribute names to the CTB validation
**Please comment your opinions on these**
Some of them are not currently strictly necessary and may be going "too far" and cause issues during v4->v5 migration, as well as annoyances that some common words are restricted.
Roadmap in a future PR:
- restrict entire prefix(es), most like `strapi` and/or `__`
- restrict the suffix `_`
These attributes will conflict with internal Strapi attributes (or planned attributes in the future)
Try to use one of these reserved words in the CTB and you will get an error
DX-1267

enhancement(ctb)!: reserve keywords needed for Strapi 5

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/ListPage.tsx

Removes the double modal toggle for the delete confirmation for RBAC roles in the admin panel.
The modal is toggled off and back on, because ConfirmDialog executes onClose after onConfirm has been successful. See code reference below:
https://github.com/strapi/strapi/blob/971168147bacca33746fef2a1c66c1f17603eed6/packages/core/admin/admin/src/pages/Settings/pages/Roles/ListPage.tsx#L265-L269
https://github.com/strapi/strapi/blob/971168147bacca33746fef2a1c66c1f17603eed6/packages/core/admin/admin/src/components/ConfirmDialog.tsx#L84-L85
1. npx create-strapi-app@beta strapi-v5-delete-role --quickstart
2. Create super admin
3. Go to Settings > ADMINISTRATION PANEL > Roles
4. Delete role Editor
fixes: #19962

[v5] fix(admin): remove double modal toggle for on delete RBAC role

---

packages/core/content-manager/admin/src/history/components/VersionInputRenderer.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Input.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/NonRepeatable.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Repeatable.tsx

- Add `customInputRenderer` render prop to component inputs so they can provide their own renderer
Unknown fields for history version need to ignore RBAC. This is handled in the `VersionInputRenderer` which we use to replace the EditView's `InputRenderer`. Components however also call this InputRenderer and we need to replace it with `VersionInputRenderer` at the level as well.
This solution seemed the most flexible with least amount of change, but happy to discuss alternatives.
Currently on v5/main components that have been renamed or deleted show No permissions:
- Using a content type that has both repeatable and non-repeatable components, add some values to each component, then save to create a history version
- Rename or delete these component fields
- Save the document again to …

fix: add render prop to use VersionInputRenderer

---

packages/core/core/src/services/document-service/repository.ts

Refactored document service `publish()`, `unpublish()`, `discardDraft()` methods to not trigger the `entry.delete` webhook.
They were internally calling the doc service `deleteDocument` method and so triggering the delete webhook

feat: refactor publication methods to not trigger entry.delete webhook

---

packages/core/admin/server/src/services/permission/permissions-manager/sanitize.ts
packages/core/content-manager/server/src/history/controllers/history-version.ts
packages/core/content-manager/shared/contracts/history-versions.ts

Sanitizes the data field in the history version controller
Passwords, even in their hashed version, should not be in the data object. This change aligns history with the behavior of the edit view
Go to the history page on a content type that has a password field. You shouldn't see any data for that password in the history page. Nothing else should change

fix: sanitize history versions data field

---

packages/core/admin/admin/src/content-manager/pages/ListView/components/TableCells/CellContent.tsx

content can be undefined because of some timing issues. the Cell is rendered before the new data is loaded when navigating between content types in the CM list views. 
There is a depper issue to fix for v5 but it it's still valid to check the value is defined and is an array before accessing that length prop regardless
Fix a bug
Navigating in the CM between content-types with repeatable components displayed in the list view should not reproduce the error anymore
Fix https://github.com/strapi/strapi/issues/19660

fix: content could be undefined

---

tests/api/core/content-manager/content-manager/history/history.test.api.ts

Use the created versions to restore

fix(tests): update history api tests to created ids

---

packages/plugins/graphql/package.json
packages/plugins/graphql/server/src/services/content-api/index.ts
yarn.lock

Upgrade deps, changelogs only indicate on place I had to update. 
get up to date for v5
All graphql tests should pass, specificaly check that graphql extensions are still working (upload, users...)

chore: upgrade graphql-tools

---

packages/core/admin/admin/src/App.tsx

* if we're in EE the `routes` variable will be an `array` not `null`, if that's the case we wait for the routes to be loaded (which is not feature specific) before trying to re-render the app after being redirected from `admin/connect/PROVIDER` to `admin/login/success` because the component would not be ready to handle it & therefore the redirect will never complete
* You can't login with SSO at the moment
Experimental: `0.0.0-experimental.ccba4ea6043b6bab83888f85cc9a3f07f61dc262`
* Follow steps here https://docs.strapi.io/dev-docs/configurations/sso (I used Github, it was v easy)
* login with SSO
* be redirected to the homepage!
* resolves #20219
* resolves DX-1392

fix(admin): if were in EE mode wait for the EE routes to be loaded before rendering

---

packages/core/content-releases/admin/src/components/CMReleasesContainer.tsx
packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/components/tests/CMReleasesContainer.test.tsx

Fixes "update not wrapped in act()" error coming from CMReleasesContainer. I found that the async request at the root of the issue seemed to be [the useRBAC call in ReleaseActionMenu](https://github.com/strapi/strapi/blob/301d2027a59183bfa76012748eaeef6b5ffae9d1/packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx#L224).
Also fixes an unrelated TS error
same bug as #20233

fix: CMReleasesContainer test

---

packages/core/content-manager/admin/src/content-manager.ts
packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/Actions.tsx

* adds `type` to the action signature (no the description interface)
* users can use the reducer pattern for adding bulk actions and remove ones like `publish` or `delete` or swap them out, similar to how document actions work

chore: add type to bulk action actions

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
packages/core/core/src/migrations/draft-publish.ts
tests/api/core/strapi/migrations/migration-draft-publish.test.api.js

On V5, content types without draft and publish have a single version , where the publishedAt value is filled with a date.
Content Types with draft and publish have two versions, a draft and a published version, where the publishedAt value is null on drafts and filled with a date on published versions.
When enabling draft and publish on a content type, we were copying the single version with the publishedAt value filled and updating the publishedAt value to be null. 
This process did not copy components or relations, and now all documents are processed in batch, to call the `documents.discard`method, which takes care of that, at the cost of processing one version at a time.

feat: discard drafts when enabling draft and publish on ct

---

packages/core/content-manager/admin/src/history/components/VersionInputRenderer.tsx

- Fix condition from return "No relations" for missing relations
- Missing relations are always represented as no relations
- Go to a content-type with relations like kitchensink
- Create some entries to relate to like Tag
- Attach the relations to kitchensink and create some history versions
- Now go delete some relations
- Access previous versions where the relations existed
- Make sure the correct message is displayed
Relation should display:
- No relations (including no missing relations) should display "No relatins"
- Relations + missing relations should display the existing relations + missing relation message
- Missing relation messages should display the number of missing relations if there are several that are missing.

fix(history): adjust condition to display missing relations

---

packages/core/admin/admin/src/components/LeftMenu.tsx

Reverts the order of the NavLink.Tooltip and the NavLink.Link
Because we had a strange behaviour in Safari, the position of the tooltip was starting in the middle of the icon link, wrapping the NavLink.Link with the NavLink.Tooltip solved the issue
Open the CMS in Safare and check the tooltips position

feat(main-nav): Fix the tooltip position of the links

---

packages/plugins/users-permissions/admin/src/pages/Roles/pages/tests/EditPage.test.jsx

U&P test changes
Fix failures like
https://github.com/strapi/strapi/actions/runs/9015798490/job/24771319080?pr=19898

fix: u&p FE tests

---

packages/core/content-manager/admin/src/pages/EditView/components/Header.tsx

It changes the Cog icon of the Configure the view link of the edit view to a ListPlus icon. 
The edit view is currently the only page where we use the Cog icon to illustrate the Configure the view feature. In every other page we we use the ListPlus icon (my bad, the error comes from my mockups).
It can be seen in the edit view of any entry.
Not related to any issue or pull request.
https://github.com/strapi/strapi/assets/45385696/a13d90ab-fcbb-4533-a338-8222ccfa4a56

chore(cm): changed the Configure the view link icon in the edit view

---

.github/workflows/caniuse.yml

Adds a script to keep browserslist up to date
So we don't see:
```shell
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
ALL THE TIME

chore: add workflow to update Browserslist DB

---

packages/utils/typescript/tsconfigs/server.json

Adds a tsBuildInfoFile to tsconfig so that incremental option works
v5 plugins are receiving build errors in v5 because of this missing config value (among other things that are solved in strapi/sdk-plugin)
using this updated config should allow to build without receiving the error `[ERROR]  Option '--incremental' can only be specified using tsconfig, emitting to single file or when option '--tsBuildInfoFile' is specified.`
DX-1400

fix(typescript-utils): add tsBuildInfoFile to fix incremental options

---

packages/core/strapi/src/cli/utils/__tests__/logger.test.ts
packages/core/strapi/src/cli/utils/data-transfer.ts
packages/utils/logger/src/configs/output-file-configuration.ts

- only create one log file per cli command run
- change log level to 'info' for file transport
Data transfer commands are currently creating a log file for every individual warning that is sent to the console, and it's an empty file because the file transport was set to 'error'
This way we get only one single file for every data transfer command that is run
unit test has been added
when you run a data transfer, you should only see a single log file, and it should only be created if there was a reason to create it like a warning or error.
DX-1408

fix: data transfer logging

---

packages/core/data-transfer/src/engine/index.ts

- filtering out documentId key from data, so it's not removed when consolidating destination and source schemas
- documentId property was not being transferred with the entities 
- attempt a transfer ( import, export, or a transfer between two projects)
- documentId should not change, translations should be preserved and publishing status should be preserved as well

Fix transfer document id in DTS

---

.gitignore
packages/cli/create-strapi-starter/src/resources/gitignore
packages/generators/app/src/resources/dot-files/common/gitignore

Adds package manager files, .tsbuildinfo, and .eslintcache to generated project gitignore and the root gitignore
I did not do the individual strapi package gitignore files because tbh they shouldn't even exist unless they are overriding the root level one, but we can deal with that later.
To ignore more files, but specifically it is needed for .tsbuildinfo because that is now created when building typescript projects in v5
Generate a new typescript project, build it, and see that it ignores those files.

enhancement: improve gitignore in generated projects

---

packages/core/content-type-builder/admin/src/components/FormModal/forms/forms.ts
tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/create-single-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts
tests/e2e/utils/shared.ts

Fixes the comparison in the validator so that takenCollectionNames only includes collectionNames and not also collectionNames equal to the current pluralName (which meant that it would then compare its pluralName against its own collectionName and fail validation because they were equal)
To allow saving content types after changing the value of i18n or d&p
See https://github.com/strapi/strapi/issues/19750 for details. It should now allow saving.
e2e tests have also been added, which fail without the change and pass with the change
DX-1160
Fixes https://github.com/strapi/strapi/issues/19750

fix(ctb): validation compares pluralName and collectionName correctly

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
packages/core/database/src/migrations/internal-migrations/5.0.0-03-locale.ts
packages/core/database/src/migrations/internal-migrations/index.ts

Migrating from v4 content types with i18n disabled resulted in the following error:
The cause was the `locale` column not being in the database for those content types. It is assumed , in v5, that the locale column will be present even if i18n is disabled on a content type.
This fix proposes adding a locale column in the discard-draft migration,  similarly to how we add the document_id in another migration.

fix: create locale column when migrating from v4

---

packages/core/types/src/modules/entity-service/params/attributes/relation.ts

Make `position` optional in WithPositionArgument
See: https://github.com/strapi/strapi/issues/19252#issuecomment-2129722983 and more generally https://github.com/strapi/strapi/issues/19252
See https://github.com/strapi/strapi/issues/19252#issuecomment-2129672212
fix #19252

[TS] Update position attribute to be optional in relation reordering types

---

packages/core/admin/admin/src/pages/Settings/pages/Webhooks/EditPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/ListPage.tsx
packages/core/admin/shared/contracts/webhooks.ts
packages/core/core/src/services/webhook-runner.ts
packages/core/core/src/services/webhook-store.ts

Frontend
- Fix create action not redirecting to the created entry
- Fix delete action in the list view not closing the confirm dialog
- Fix update action not opening the EditPage
Backend
- Refactor to use the Webhook type exported from @strapi/types
- Ensure the webhook store returns webhooks with string ids as the type dictates
I set it up this way since the Webhook type id is set as string, so I assume that's what we want to be dealing with even if db.query returns a number... Open to discussion not sure it's the best solution 🤷 
Otherwise the client expects a string but receives a number this breaks client side redirects when navigate receives a number instead of a string
- Go to the webhooks page, settings -> webhooks
- Create a webhook, on create the url should change from /create to …

fix(webhooks): ensure id sent to client is always a string

---

packages/core/content-manager/admin/src/components/LeftMenu.tsx
packages/core/content-manager/admin/src/index.ts
tests/e2e/tests/i18n/listview.spec.ts

- Remove the i18n plugin search params that persist when changing content-types in the content-manager
- Remove unused import
- It doesn't make sense to have the search params for content-types that do not have i18n enabled
- It breaks the history page (and probably other queries) if the search params are present on a content-type that does not have i18n enabled
- Go to a content-type with i18n enabled, you should see in the search params something like `&plugins[i18n][locale]=fr`
- Now select another content-type from the side nav that you know doesn't have i18n enabled, the search params `&plugins[i18n][locale]=fr` should no longer be present.
- Go to setting -> internationalization. Change the default locale to another locale. Go back to a content-type with i18n enabled. It should (by …

fix(content-manager): remove i18n search params when navigating

---

packages/core/content-manager/admin/src/hooks/useDocumentActions.ts

- it passes the params (with the locale selected) to the discard endpoints
Without the locale every time we try to discard some changes in a document with a different locale than the default one the discard has no effect
- Go to a content-type with i18n enabled, and add a new locale in the setting
- then create a new document with the new locale
- Save and publish the document
- and then modify the document and Save
- click on the Document menu and click "Discard changes"
- then confirm that you want to discard the last changes
- the value changed needs to be discarded and replaced with the last one published 
CS-707
Here you can see a video with the bug
https://github.com/strapi/strapi/assets/2589748/ad17e00d-4adf-41ce-98a4-dc6fda57238a

fix(content-manager): fix discard action in different locale than the default one

---

packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/Actions.tsx
packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/PublishAction.tsx
packages/core/content-manager/admin/src/translations/en.json

1. Updated publication status for modified entry
2. Show unpublish bulk action for the modified entry
- When you are on a bulk publish modal, if there is a `modified` entry user should see publication status as : `Ready to publish changes`.
- Should show `unpublish` bulk action along with `publish` action for the `modified` entry

Fix: bulk publish modified entry status

---

packages/cli/cloud/src/config/api.ts
packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/login/action.ts

- After successful login, or after "already logged in" message, we display the link to the dashboard (list of projects):
- After build, we display the link to the deployment logs

feature: display cloud dashboard urls in cli

---

packages/core/utils/src/__tests__/convert-query-params.test.ts
packages/core/utils/src/convert-query-params.ts

Allow morph-like attributes to request a count at the root level.
This is breaking some CM features, + is was a regression when we removed the root level nested populate params
- Tests
- Start the getstarted, head to the CM, and try to create a kitchensink entity. It should succeed.

Allow morph-like attributes to request a count (populate)

---

tests/api/plugins/content-releases/releases.test.api.ts

Skip API Tests for releases on v5 until releases is migrated to v5

chore(content-releases: skip api tests until releases is migrated to v5

---

.github/workflows/tests.yml
docker-compose.test.yml

Removes `MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password`
8.4 (which mysql:latest now points to) throws an error instead of deprecation warning when using mysql_native_password
DX-1439

chore(ci): remove mysql_native_password in test container

---

examples/getstarted/src/api/category/content-types/category/schema.json
packages/core/content-manager/admin/src/history/components/VersionInputRenderer.tsx
packages/core/content-manager/admin/src/translations/en.json
packages/plugins/i18n/admin/src/contentManagerHooks/editView.tsx

Changes the i18n label action wording on the history page. It does it by mutating the labelAction component at the field level in history when it detects that it comes from i18n.
There's a completely different way to solve the problem that I also explored. It requires adding another CM hook to let the i18n plugin. But it prevents us from directly using the edit view layout in history, so it ends up requiring a lot more changes. Even though this current solution feels more hacky, I personally prefer it.
Instead of:
>This value is the same across all locales
When in history we want to show:
>This value is common to all locales. If you restore this version, the content will be replaced for all locales.
So that users are aware that their actions on one locale can affect the others.
The i18n …

feat: customize localization label actions in history

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts

- find first button now that there are multiple role:edit buttons on the page
- use correct text for confirm modal
the test is broken
Note: The test still fails because of an actual bug; the [modal does not close even after confirming it correctly](https://github.com/strapi/strapi/issues/19953)
but now if you run the tests you see that it doesn't break on the edit button or the modal close click
https://github.com/strapi/strapi/issues/19953

test: fix ctb edit collection type

---

packages/core/data-transfer/src/engine/__tests__/engine.test.ts
packages/core/data-transfer/src/engine/validation/schemas/index.ts
packages/core/data-transfer/src/file/providers/source/index.ts
packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
packages/core/data-transfer/src/strapi/providers/local-source/index.ts
packages/core/data-transfer/src/utils/schema.ts

- Add 'default' to the list of ignorable attributes's properties
- Sanitize schemas to be valid JSON to make sure no invalid JSON properties are present during the checks
strapi import on identical apps is currently broken because of 'default' not being present all the time
See #20388 for reproduction
fix #20388

fix: allow '.default' to be ignored during schema validation

---

packages/core/content-manager/server/src/history/services/lifecycles.ts
tests/e2e/tests/content-manager/history.spec.ts

Prevents the creation of a duplicate history item when publishing a document.
Because of how D&P works in v5, when publishing a document, both the draft and the published document get updated, which until now created two items in content history. This was confusing to users. Now they should only see the published entry in history when they publish a document.
Publish a document, check history.

fix: prevent duplicate history versions on publish

---

packages/core/admin/admin/src/components/LeftMenu.tsx

Fix the color issue that we have in the Left menu with the Lightning icon color
Because we want to use this color for the icon
So to override the style with higher specificity I used this trick recommended in the styled components doc
https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity
Open a Strapi App with Community Edition license

fix(chore): increase specificity of the Lightning icon color

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

Skip two tests on the CI that work locally but always fail on github
A compromise to allow CI to pass while we work on finding the issue
Tests should pass on the CI, and the "broken" tests should still run locally

test: temporarily disable broken edit ctb tests

---

tests/e2e/tests/content-manager/editview.spec.ts
tests/e2e/tests/content-manager/listview.spec.ts
tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts
tests/e2e/tests/i18n/settings.spec.ts

allow tests to run locally (copied from `develop` branch)
These tests are currently failing on CI and blocking a lot of PRs, but they pass locally. This will allow people to still run the tests locally but unblock the CI until we have time to solve the issue.
Tests should pass on CI with these specific tests skipped, and pass locally with the tests running.

test: fix broken e2e tests

---

docs/docs/docs/01-core/admin/01-ee/00-intro.md
packages/core/admin/admin/src/StrapiApp.tsx
packages/core/admin/admin/src/components/LeftMenu.tsx
packages/core/admin/admin/src/constants.ts
packages/core/admin/admin/src/hooks/useSettingsMenu.ts
packages/core/admin/admin/src/pages/Settings/components/SettingsNav.tsx
packages/core/content-releases/admin/src/index.ts
packages/core/review-workflows/admin/src/index.ts

Replace the Lock icon used for the features not available without EE license with the Lightning icon
We want to replace the Lock icon that shows users they don’t have access to Releases and other features in the Community Edition by a lightning flash icon so that these features are perceived as boosters if users upgrade their app (rather than blockers).
Open a Strapi App with Community Edition
CS-808

Replace lock icon with lightning icon in the Settings and Navbar links

---

packages/core/admin/admin/src/StrapiApp.tsx
packages/core/admin/admin/src/components/Providers.tsx
packages/core/admin/admin/src/constants.ts
packages/core/admin/admin/src/core/apis/router.tsx
packages/core/admin/admin/src/features/StrapiApp.tsx
packages/core/admin/admin/src/hooks/useSettingsMenu.ts
packages/core/admin/admin/src/index.ts
packages/core/admin/admin/src/render.ts
packages/core/admin/admin/src/router.tsx
packages/core/admin/admin/src/tests/StrapiApp.test.tsx
packages/core/content-manager/admin/src/index.ts
packages/core/content-manager/admin/src/layout.tsx

* adds first iteration of the client router API (marked as alpha)
* enables users to add route objects to the react-router i.e. to use `loaders` and `actions`.
* enables users to completely modify routes e.g replace the homepage
* resolves DX-1177

feat: add client router API

---

packages/core/admin/admin/src/components/FormInputs/Date.tsx
packages/core/admin/package.json
yarn.lock

* handles timezones with the date picker
* the date picker is timezone aware (should we want to start working with them) but the date it converts it too doesn't handle it well, making it think it should be X time prior
* add a date
* blur the input
* date should stay what you set
* resolves #20321
* resolves DX-1462

fix(admin): date picker jumps around due to timezones

---

packages/core/admin/admin/src/components/Pagination.tsx

Add a bottom padding to the pagination component so it looks with more space on pages where it's the last element.

fix(admin): add bottom padding to pagination component

---

packages/core/admin/admin/src/components/NpsSurvey.tsx
packages/core/admin/admin/src/components/tests/NpsSurvey.test.tsx

It changes the delays to display the NPS for the first time (from 5 minutes to 30 minutes) and after the first dismissal (from 7 days to 14 days)
Many users complain about the frequency of NPS
- Register for the first time on Strapi and on the Registration page accept the Newsletter checkbox
- then wait after 30 minutes of activity and you will be able to see the NPS survey at the bottom of the page
- when the NPS survey is displayed, close it by closing the modal
- then after 14 days the survey will be proposed again
CS-795

NPS: Update frequency of the NPS

---

packages/core/admin/admin/src/components/FormInputs/Time.tsx

it fixes the Time format in a Time field, because right now when we try to save we receive an error
Time format in component is not valid when filling in an entry using this component.
1. Create a component with a Time field which will be a type "time (ex: 00:00 AM)
2. Use this component in a collection type
3. In CM, create an entry for this CT and save
4. See error on Component (it works with classic Time field outside of component)
Repeat the above steps to check if the error is still present
[Let us know if this is related to any issue/pull request](https://github.com/strapi/strapi/issues/20236)

Fix the Time field format on saving

---

packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/server/src/services/release-action.ts

Fix 2 small issues on Content Releases:
1. When adding an entry to a release we need to wait for the entry status validation
2. Remove endIcon from edit release button to match designs

fix(content-releases): release validation and dropdown menu endIcon

---

packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx

Add a new variable to the isLoading check on the add column to table hook.
When rendering the additional columns added by plugins, we have two values that are separated: the model and collectionType information (found in the URL and accessible using the useDoc hook) and the list view data.
When a user moves from one ContentType list view to another, there is a moment when the model changes to the new one, but the data still reflects the old one because we are in the process of fetching the new data. To avoid this, we use an isLoading check. However, this is insufficient because isLoading is true only the first time a query is performed. Instead, we need to check both isLoading and isFetching to ensure that whenever the user is fetching different data, nothing is displayed.
This approach …

fix(content-manager): add isFetching to loading check

---

packages/core/content-manager/admin/src/utils/validation.ts
packages/core/core/src/services/entity-validator/index.ts
packages/core/core/src/utils/transform-content-types-to-models.ts

* Check required is not present on relation fields on schemas and throw an error asking user to change it if it's present. 
* Remove required check from relations fields

fix(core): disallow required on relation fields on schemas

---

packages/core/admin/admin/src/components/Filters.tsx
packages/core/admin/admin/src/components/FormInputs/Renderer.tsx
packages/core/admin/admin/src/components/FormInputs/types.ts
packages/core/admin/admin/src/constants/filters.ts
packages/core/content-manager/admin/src/pages/ListView/components/Filters.tsx

Fix multiple issues related to filters on v5:
* Relations filter are using the mainField instead of always the id
* UID filtering is supported 
* enum filtering has the right options
#20483 
#20058

fix(content-manager): fix filters bugs with relations, enums and uids

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/CreatePage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

- saving a new RBAC role redirected to a 404
- adds "replace: true" to the navigation when an entry is initially created
When saving for the first time, the path is rewritten, but the redirection isn't perceptible to the user. When he then clicks on the back button, the expectation is to land on the list view, not the create view
- Create and save an RBAC role
- Create and an RBAC role by duplicating an existing one
- In the CM, create a new entry in a collection type. Upon saving, if you go back you should not land on the create page
Fix https://github.com/strapi/strapi/issues/20217

fix: navigation issues

---

packages/core/admin/admin/src/components/FormInputs/Date.tsx
packages/core/admin/admin/src/components/FormInputs/DateTime.tsx

Fix the issue we had with Date fields, everytime we change a date and save we were saving the locale date and not the utc one resulting that the value shown is the day before
Otherwise after saving the date we show the day before
1. Create an entry on a collection with a date field, add a date value and save
2. After save you need to see the date saved and not the date with the day before
fixes https://github.com/strapi/strapi/issues/20569

V5 fix: wrong date saved

---

packages/utils/upgrade/src/modules/runner/json/transform.ts

- Enforce the use of
- `hookIgnoreNodeModules` to allow loading external files in isolated context (npx/dlx)
- `hookMatcher` to make sure we're not matching anything else than our codemod in external directories.
When using the upgrade tool to run JSON codemods with tools like npx or dlx, it crashes with the following error "Cannot use import statement outside a module".
See the added comments for more information about the issue (`packages/utils/upgrade/src/modules/runner/json/transform.ts`)

[Upgrade Tool] Fix JSON Transform Loader

---

packages/generators/app/src/resources/files/js/README.md
packages/generators/app/src/resources/files/ts/README.md

Insert the new `yarn strapi deploy` command in the README files.
Give more visibility to this useful command for our users to quickly and easily deploy their project.

Add: Strapi deploy command to README files

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
packages/core/core/src/migrations/draft-publish.ts

Adds a check to conditionally set locale in the `discardDraft`'s params.
This can break app with no i18n
See https://github.com/strapi/strapi/issues/20225
See reproduction steps in https://github.com/strapi/strapi/issues/20225
fix https://github.com/strapi/strapi/issues/20225

Handle non-localized content-types in discard-draft migration

---

packages/cli/cloud/src/create-project/action.ts
packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/login/action.ts
packages/cli/cloud/src/logout/action.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/services/token.ts

We perform a proper OIDC logout by opening the logout endpoint in the browser. We provide the client ID and token. We do nothing if an error happens during the logout process: the logout happens at least on the app level, this just adds a logout on the Auth0 SSO level.
"chore" changes (unrelated to the initial task):
- Handle errors while fetching the config
This change is needed to address the issue where users are unable to switch between different login providers. By logging out the user from the OIDC provider, the user's session is cleared. This allows the user to choose a different login provider when they attempt to log in again.
First, use the login command:
Log in in the CLI using one of the login providers (e.g., Google), 
Then, log out (using the logout command):
The CLI should …

feat(cli): add browser logout step

---

examples/getstarted/src/admin/app.jsx
packages/core/admin/admin/src/translations/en.json
packages/core/content-type-builder/admin/src/components/AutoReloadOverlayBlocker.tsx
packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/strapi/src/node/vite/config.ts

The HMR configuration in config.ts has been tweaked; now the server property is set to the instance of the HTTP server that Strapi uses, so that Vite HMR server and Strapi start accepting requests at the same time.
The Vite server was restarting faster than the Strapi HTTP server, hence triggering vite to reload the page before Strapi is ready to accept requests (hence the "Unable to connect" message).
- Got to the CTB
- Modify a content-type
- The server shouldn't display the "Unable to connect" page and instead only reload when the server is ready
fix #20220

Fix Vite HMR Server Restart 

---

packages/core/review-workflows/admin/src/routes/settings/components/Layout.tsx
packages/core/review-workflows/admin/src/routes/settings/components/Stages.tsx

Fixes the z-index bug in the review workflow edit view by making the header not sticky. I checked with @lucasboilly and the sticky behavior was not necessary on that page
fixes #20211

fix: remove sticky review workflow nav

---

packages/cli/create-strapi-app/src/cloud.ts
packages/cli/create-strapi-app/src/create-strapi-app.ts
packages/generators/app/src/index.ts

Removing the cloud project creation part on create-strapi-app.
As we experienced some issues with the actual flow, we decided to remove that part.
Issues:
- Delays the strapi project creation by ~10s
- Active the free trial when the project is generated
- If the user remove his project and creates another, he cannot re-use the Cloud CLI to create a project as he as already used his free trial.
The create-strapi-app command should not create a project on Cloud anymore.
The project should be created on Cloud during the first `strapi deploy` command (this is already handled in the deploy command).

feat(create-strapi-app): remove the cloud project creation part

---

packages/core/database/src/migrations/internal-migrations/5.0.0-05-drop-slug-unique-index.ts
packages/core/database/src/migrations/internal-migrations/index.ts

Adds a migration to drop the unique index of slug fields, those are automatically removed by the strapi schema diff, but that diff is executed after the migrations, and  `discard-draft` migration will fail if there are such indexes.

fix: drop slug fields index

---

packages/core/admin/admin/src/components/ConfirmDialog.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/ListPage.tsx
packages/core/strapi/src/node/create-build-context.ts
packages/core/upload/admin/src/pages/App/ConfigureTheView/index.jsx

Separates concerns between bulk & single webhook delete. the UX was pretty strange (when clicking on the trash icon it opens a confirm but also selects in the bulk delete in the background)

fix: split single & bulk delete

---

packages/core/core/src/utils/transform-content-types-to-models.ts
packages/core/database/src/schema/__tests__/schema-diff.test.ts
packages/core/database/src/schema/diff.ts
packages/core/database/src/schema/index.ts
packages/core/database/src/schema/storage.ts
packages/core/types/src/struct/schema.ts

> ⚠️ This requires heavy beta testing before it gets into the RC
- Uses previsouly stored schema to force delete resources we are sure we have been tracking.
- This will leave alone any extra table, column, index, fks manually managed by users outside of strapi schema sync.
- Make strapi db sync safer for users
- Manually create tables, columns, indexes in your db and restart and see they are still there. 
- Then add them into the schema once, then remove them and see they get deleted from the db once they are considered tracked
- Closes https://github.com/strapi/strapi/issues/13732

chore: only delete tables,columns,idx,fks we track

---

packages/core/content-manager/admin/src/content-manager.ts
packages/core/content-manager/admin/src/history/index.ts
packages/core/content-manager/admin/src/index.ts
packages/core/content-manager/admin/src/tests/content-manager.test.ts
packages/core/content-releases/admin/src/components/ReleaseActionModal.tsx
packages/core/strapi/src/admin.ts

Fixes the position of the history document action in the edit view header. It used to show up last, but the designs specify it has to show up in the middle, right before the "danger" actions.
I'm doing it by using the public addDocumentAction, instead of setting it in the default array. It's the [same approach as done in i18n](https://github.com/strapi/strapi/blob/93fad71560acac3452f5fbd9b63fe0490e9eaedd/packages/plugins/i18n/admin/src/index.ts#L72-L76) to control the action's position in the array.

fix: history action position in menu

---

packages/core/content-manager/admin/src/pages/ListView/components/BulkActions/ConfirmBulkActionDialog.tsx

Clicking cancel at the confirmation stage of a bulk list view publish does nothing.
The modal is being toggled multiple times and therefore staying visible
DX-1482

fix(content-manager): dismiss bulk list view publish

---

packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/ContentTypeBuilderNav.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.tsx.snap
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/mockData.ts
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.ts

- The CTB menu counted the amount of folders, not of components. Fixes it
- Fixes a defaultMessage that didn't match the translation file values (hence the snapshot update)
Open the CTB, make sure the count of components, single types and collection types is accurate. Use the search to filter the result, the counts should be updated.

fix: components count in ctb menu

---

packages/core/admin/ee/server/src/audit-logs/services/lifecycles.ts

Publishing an entry resulted in duplicated "entry.update" logs in the audit logs settings page. 
The cause is a bug in how we stored events in audit logs:
```ts
await strapi.db.transaction(({ onCommit }) => {
onCommit(() => auditLogsService.saveEvent(processedEvent));
});
```
See the explanation of why this was introduced in https://github.com/strapi/strapi/pull/16768
This bit of code is not necessary anymore, as the document service emits the events using this same api.
**To dig more: For some reason, nested onCommit calls (a callback inside an oncommit opening another transaction with an onCommit call inside) caused the callbacks to be called twice**

fix: duplicated audit log events

---

packages/core/admin/admin/src/types/permissions.ts
packages/core/admin/ee/admin/src/constants.ts
packages/core/content-releases/admin/src/constants.ts
packages/core/content-releases/admin/src/index.ts
packages/core/content-releases/admin/src/modules/hooks.ts
packages/core/content-releases/admin/src/pages/ReleasesSettingsPage.tsx
packages/core/content-releases/admin/src/pages/tests/ReleasesSettingsPage.test.tsx
packages/core/content-releases/admin/tests/utils.tsx
packages/core/content-releases/shared/contracts/settings.ts

Apply the Read and Update permissions in the Release Settings page
Here the different scenarios:
- NO READ NO UPDATE : we show the No Permissions body content in the page
- READ NO UPDATE: we show the Release Settings Page with the Save button not shown and the Default timezone combobox disabled
- READ UPDATE: we show the normal Release Settings page with all the functionalities enabled
To show the proper content to the different kind of users
- Open the CMS with a EE license (if you want you can try to check if we show the Purchase page in the settings with CE license)
- As an admin create a new user with the Editor Role (by default the permissions are set to false)
- Go to the settings page, select the Editor Role and in the Settings Tab change the permissions for the Content Releases
- …

feat(release-settings): apply rbac permission in the release settings page

---

packages/core/content-type-builder/admin/src/components/SelectCategory.tsx

disable the ability to edit a category name, by disabling the drop down menu in the CTB
- Category edits don't work now, they will be worked on later in a bigger editing initiative 
- Prevent users from editing a category name and facing an error or losing there data
- Attempt to edit a component, you shouldn't be able to change the category 
#20356

Fix prevent category edits

---

packages/core/database/src/entity-manager/regular-relations.ts

Added information about the schema when executing a request for clear inverse order column
Merging this PR will solve the entity duplication error when using a potgresql database when using a non-default schema.
For testing, you need to use a postgresql database (declared in docker-compose.dev.yml is sufficient). You need to run the getstarted application on NOT THE DEFAULT SCHEMA postgresql (If the schema is default for postgresql, then the query without specifying the schema will succeed and the problem will not appear). After launch, you need to create 2 collection type entities:
1. Products (singular api id = product, plural api id = products) with field name (short text).
2. Products by region (singular api id = product-by-region, plural api id = products-by-region) with field name …

fix clone entity, #20509

---

packages/core/core/src/index.ts
packages/core/core/src/middlewares/query.ts

Augment koa query type in `BaseRequest` and `BaseContext`
We're modifying the default query type to be able to use `qs` instead of `node:querystring`. This change reflects that in the types.
See #20230 for reproduction steps
fixes #20230

Fix Koa Query Type

---

packages/core/strapi/src/node/create-build-context.ts
packages/core/strapi/src/node/vite/config.ts
packages/core/strapi/src/node/vite/watch.ts

Introduce a dedicated HTTP server used by vite hmr, and reference it in the related vite configuration.
[Vite hmr hijacks any WS upgrade events](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/server/ws.ts#L149). 
Since the current hmr config is re-using Strapi HTTP server, this behavior prevents Strapi data transfer requests from triggering remote transfers (handling custom WS connections (with policies, middleware, etc...)).
Both remote data transfers and vite hmr should be working fine.
fixes #20649

Prevent Vite hmr from Hijacking WS Upgrade Events

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-releases/admin/src/components/ReleaseActionModal.tsx
packages/plugins/i18n/admin/src/components/BulkLocaleActionModal.tsx
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx

Fix the UI error on Bulk Publish modal. Bulk Publish API shouldn't force user to always wrap render in `Modal.Body` and `Modal.Footer` so users can build custom modals as they want (Bulk publish use case).
We can discuss later if we want to have a different API to add context when adding a Bulk Action modal. 
Check all the modals from Bulk Actions (currently we have Bulk Publish, Add To Release, Publish multiple locales)

fix(content-manager): bulk actions modal don't force to use modal

---

tests/api/core/content-manager/api/relations-permissions.test.api.js

Spotted an api tests that was skipped. 
Adapted the response formats to make tests pass
Note: Users & Permissions Content Manager endpoints are not returning the content wrapped inside a `data` object. We might want to take a look at that in the future.

chore: run relation permissions test

---

packages/core/core/src/utils/__tests__/filepath-to-prop-path.test.ts
packages/core/core/src/utils/filepath-to-prop-path.ts

Add support for cross-platform handling of separators (win32 and posix) when parsing file paths 
Added unit test to avoid regression
It's not possible to start the server on Windows with components in the app.
See #20057 for more information
- On Windows, you should now be able to load components without errors and the server should start
- You can also verify it works by running the added unit tests
**Original**
close #20057
**Duplicates**
close #20638
close #20631

Fix file path parsing to allow cross-platform compatibility

---

packages/cli/cloud/src/utils/compress-files.ts
packages/cli/cloud/src/utils/pkg.ts

Update Cloud-CLI to use fs-extra everywhere
Maintenance purpose. Was in the todo-list after first release of Cloud CLI.
You can re-test all the Cloud CLI commands "login", "deploy", "logout".

chore(cloud-cli): migrate to fs-extra

---

packages/cli/cloud/src/index.ts
packages/cli/cloud/src/list-projects/action.ts
packages/cli/cloud/src/list-projects/command.ts
packages/cli/cloud/src/list-projects/index.ts
packages/cli/cloud/src/services/cli-api.ts

This PR introduces projects listing command into cloud CLI
It gives users the chance to list their projects deployed in Strapi Cloud from the CLI
- Verify that the projects command is listed among the available commands.
- Ensure that the `projects` command executes correctly.
- If the user is not logged in the user should be prompted to login
- If the user logs in it should continue with the project fetching
- Confirm that any 500 error returned from the server is handled gracefully, without causing the CLI to crash
- The rest of the commands should function correctly

feat(cli): Add projects list command

---

packages/core/content-manager/admin/src/services/documents.ts

Adds optimistic behavior to the RTK updateDocument API. We now assume that the backend won't throw errors when the user saves content, so that we can immediately update the UI with the new content when the user clicks update.
If the backend _does_ throw however, then the local state update is rollbacked, as you can see here:
https://github.com/strapi/strapi/assets/8087692/4a79c1d5-a1f7-47cd-a1df-caea9761e21d
- It prevents flickering in the edit view: when you save an update, you would see the old version of your content for a split second.
- Fixes an issue in Blocks: #20028 (the Slate state wasn't kept properly in sync with the RTK state during that "flickering" phase)
- Update content in the edit view, and save. The content in the inputs should not change, not even for a split second. …

feat(cm): add optimistic document updates

---

packages/core/strapi/src/load/__tests__/filepath-to-prop-path.test.ts
packages/core/strapi/src/load/filepath-to-prop-path.ts

Copy of https://github.com/strapi/strapi/pull/20680 on the v4 branch (develop)
Adds support for cross-platform handling of separators (win32 and posix) when parsing file paths.
fixes https://github.com/strapi/strapi/issues/20730

fix: invalid path separator

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/Blocks/Image.tsx
packages/core/upload/admin/src/components/MediaLibraryDialog/index.jsx

The media dialog did not display in the rich text editors (both Blocks and Markdown). This fixes it
The open/closed state is actually managed outside of the MediaLibraryDialog, by conditionally rendering it. So when it is rendered, it should always display its content, hence the `open={true}`
Also removes some unnecessary onClose code, because since the component is now remounted when we reopen it, the state will be reinitialized, no need to do it manually
- Add an image to a blocks field. Create a folder too from within the dialog.
- Do the same in a markdown field
fix #20743

fix: show media dialog in blocks and markdown editors

---

packages/core/content-manager/admin/src/components/LeftMenu.tsx
packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/ContentTypeBuilderNav.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.tsx.snap
packages/core/content-type-builder/admin/src/components/Relation/RelationField/RelationTargetPicker/RelationTargetPicker.tsx
packages/core/content-type-builder/admin/src/pages/ListView/ListView.tsx

It solves the UI issues when you have a collection with a long title
Because it breaks the UI in the Content manager, Content-Type builder, the Relation field and the Left menu
- create a new collection with a long name (use a long big word)
- check if the Edit view of the new collection in the CTB has no UI issues and also its Left menu
- check if the List view of the Collection has no UI issues in the content manager and its left menu
- check if a relation with this collection has UI issues
fixes https://github.com/strapi/strapi/issues/20366

Fix Long Collection title breaks ui

---

packages/utils/upgrade/resources/codemods/5.0.0/dependency-upgrade-styled-components.json.ts

Adds a new codemods for the upgrade utility to properly upgrade the `styled-components` as currently it's not updating this dependency causing errors when starting the newly migrated project
Admin throws errors after using the upgrade
Run the upgrade command and see that `styled-components` are actually updated to v `^6.0.0`
N/A

chore: add styled-components upgrade codemod

---

.github/workflows/issues_handleLabel.yml

Removing Simen and Nick from the array of people issues will be auto-assigned to
They no longer work for us
N/A
N/A

Chore: Removing some people from the issue auto-assignment

---

packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/services/build-logs.ts

This PR adds some logs and handle a timeout that was not properly cleared before ending the deploy action.
Avoid our users waiting for unnecessary time when something wrong happens with the logs from the build engine.
You may need to edit the code to try to get logs from a not found URL (I added 123 in the URL for example), in the build engine service.
Then run the deploy command on a strapi project. You will reach the max retries and the command should gracefully quit the node process.

fix(cloud-cli): avoid blocking event loop in deploy command

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/server/src/controllers/collection-types.ts
tests/api/core/admin/admin-permissions-custom-conditions.test.api.js

There is an inconsistency on the content manager publish / update permisions.
Scenario:
- User has permissions to publish and not update
- Expected behaviour: User can publish but not update draft
- Current behaviour: User can not publish
And also, there was a workaround about this, bulk publishing multiple locales.
See more [CS-838](https://strapi-inc.atlassian.net/browse/CS-838)
This is only the first step to fix the inconsistency, some FE work will be required (enabling the publish button on this scenario)
[CS-838]: https://strapi-inc.atlassian.net/browse/CS-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: inconsistent publish permissions

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-releases/admin/src/components/ReleaseActionMenu.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx

it fixes the dimensions of the More button in the Header, in the Document menu and in the Edit view
Because the button needs to be a square with the More icon inside centered
Open an entry and check
- the header
- the Document menu
- and the Release section in the Edit view
fixes https://github.com/strapi/strapi/issues/20764

Fix the dimensions of the More button

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

It fixes a UI problem we had in the Document actions when some of them are disabled, instead of using the variant color it is better to inherit the disabled color
Because otherwise, the UI is wrong, we show some disabled buttons with the enabled color
- Go to the CM and add a new document to a collection
- before saving, click on the More button in the Header, you can see the Delete document and Delete locale buttons disabled with the correct color
fixes https://github.com/strapi/strapi/issues/20759

fix color in disabled buttons

---

packages/cli/cloud/src/create-project/action.ts
packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/index.ts
packages/cli/cloud/src/link/action.ts
packages/cli/cloud/src/link/command.ts
packages/cli/cloud/src/link/index.ts
packages/cli/cloud/src/login/action.ts
packages/cli/cloud/src/logout/action.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/services/strapi-info-save.ts
packages/cli/cloud/src/types.ts
packages/cli/cloud/src/utils/analytics.ts

This PR introduces the project `link` command into the Strapi Cloud CLI
It gives users a chance to link their local projects to existing projects in Strapi Cloud from the CLI
1. Verify that the projects command is listed among the available commands.
2. Ensure that the link command executes correctly.
3. If the user is not logged in, they should be prompted to log in.
4. If the user is not in a valid project folder, the command should exit with a message.
5. If there is a project already linked to the current folder, it should ask the user if they want to update the current link and correctly display the name of the linked project.
6. If the user selects "no", the command should exit.
7. If the user selects "yes", the command should …

feat(cli): add project link command to cloud cli

---

packages/utils/typescript/tsconfigs/admin.json

Adds back the admin.json tsconfig file
It's being referenced by existing plugins, and plugins created by @strapi/sdk-plugin, possibly other places
You should be able to reference it in plugins again
DX-1495

revert(typescript-utils): replace deleted admin tsconfig

---

packages/core/content-manager/server/src/history/services/lifecycles.ts
packages/core/content-manager/server/src/history/services/utils.ts
packages/core/content-manager/server/src/services/document-metadata.ts
tests/api/core/content-manager/content-manager/history/history.test.api.ts

- Creates a history version when bulk publishing multiple locales of the same document.
- Splitted the history document service middleware as it was getting a bit long. 
- Go to the Edit View of an entry
- Bulk publish one or more locales
- See that each locale has a "publish" history version created

feat: history version on bulk publish locales

---

packages/core/admin/admin/src/components/FormInputs/Json.tsx
packages/core/database/src/fields/json.ts

Makes sure the JSON fields are parsed properly when read from the database. It turns out sometimes, probably because of v4 to v5 migrations, they were stringified twice, so [they needed to be parsed twice](https://stackoverflow.com/questions/31662849/parse-json-object-that-stringify-twice).
I also made a fix on the frontend to support both string and object types, as both could be sent for users migrating.
- Write JSON in a JSON field in the edit view, the experience should be normal
- Save and refresh, your changes should be retrieved
- Query the content using the content API, you should see your JSON input in object form, not as a string
replaces #20829
fixes #20655

fix: json fields not parsed properly

---

packages/plugins/cloud/admin/src/pages/HomePage.tsx

Fix a UI issue we had in the cloud plugin
The Cloud background left image had the wrong offset so it seems cut in the layout
- add the cloud plugin to your Strapi instance with an EE license and check the plugin home page
fixes https://github.com/strapi/strapi/issues/20824

fix: the left offset of the cloud image

---

packages/core/content-manager/admin/src/services/documents.ts
packages/core/review-workflows/admin/src/services/api.ts
packages/core/review-workflows/admin/src/services/content-manager.ts
packages/core/review-workflows/admin/src/services/settings.ts

Make sure to invalidate document queries when RW stage or assignee is changed so we can see the change on the Edit View.
1. Go to an entry with RW.
2. Change the stage of the entry.
Closes #20745

fix(review-workflows): invalidate document queries when stage & assignee is changed

---

packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.jsx

Mock usefolderstructure to fix flaky frontend test
The isLoading state here 
`packages/core/upload/admin/src/components/BulkMoveDialog/BulkMoveDialog.jsx`
was causing a state update that failed this test case
https://github.com/strapi/strapi/blob/47fed6c2b2716a33bc5b44c7465d4be77be27a84/packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.jsx#L361-L362
Run the tests. To check flaky tests like this I've been using a (pretty hacky) script that looks like
```
#!/bin/zsh
COMMAND='yarn test:front packages/core/upload/admin/src/pages/App/MediaLibrary/tests/MediaLibrary.test.jsx'
TIMES=10
fail_count=0
for i in {1..$TIMES}; do
echo "Attempt $i of $TIMES"
if ! eval $COMMAND; then
echo "Command failed on attempt $i"
((fail_count++))
fi
done
echo "Command failed $fail_count …
```

fix(upload): mock usefolderstructure to fix flaky frontend test

---

packages/core/admin/admin/src/components/FormInputs/Json.tsx
packages/core/content-manager/admin/src/utils/validation.ts

In the admin validation, handles the case where JSON content is in object form, not stringified.
The JSON value will be an object if it was created via the content API and hasn't been modified in the input.
- Create a kitchensink entry via the content API, give the json field an object value.
- Find the entry in the CM, modify another field without touching the json field
- Save. You shouldn't get a validation error.
fixes #20882

fix: admin validation broken when json is still an object

---

package.json

- adds cli to clean
- allow all clean scripts to run even if one fails
it wasn't cleaning cli test apps
run `yarn test:clean`

chore: add cli tests to clean script

---

packages/cli/cloud/src/deploy-project/action.ts

Update the error log in the cli `deploy` command to suggest the usage of `link` command when a project is not found.
Previously, when a project was not found, we couldn't do anything so we logged an error. Now, users can use the strapi link command to link a project to the existing project folder.
Try to deploy in a project with wrong project name in `.strapi-cloud.json` config and you should see the right warning log.

fix(cli): Update 'project not found' error message in deploy command

---

tests/api/core/review-workflows/review-workflows-content-types.test.api.ts
tests/api/core/review-workflows/review-workflows.test.api.ts

Fixes API tests. Hopefully the CI passes now.
My earlier PR (#20880) deleted a review workflows endpoint as it was no longer used by the frontend (GET individual workflow). I didn't see that it had associated API tests. This PR deletes those left over tests

chore: delete api tests for deleted review workflows route

---

packages/core/core/src/registries/__tests__/policies.test.ts
packages/core/core/src/registries/policies.ts

- fixes policies registry to return the same data types as controllers, services, etc
fixes the `strapi policies:list` command and makes the policies `keys()` return type consistent with other registries
Policies should all work fine
especially check that `strapi policies:list` should return policies
DX-1505 
Fixes #20893

fix: policies registry returns same data types as other registries

---

.github/workflows/checks.yml
.github/workflows/commitlint.yml
.github/workflows/tests.yml

Sets up missing workflows for v5/main
security-lock-analysis and pr-status were being required to merge but not being required to run, which means currently all(?) `v5/main` PRs must be force merged
security-lock-analysis and pr-status should run on this PR's workflow

chore: v5/main workflows

---

packages/core/core/src/services/entity-validator/__tests__/biginteger-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/date-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/datetime-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/email-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/float-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/integer-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/string-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/time-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/timestamp-validators.test.ts
packages/core/core/src/services/entity-validator/__tests__/uid-validators.test.ts
packages/core/core/src/services/entity-validator/validators.ts
tests/api/core/strapi/document-service/uniqueness.test.api.ts
tests/e2e/tests/content-manager/uniqueness.spec.ts

Modifies backend validators so, only max validators are applied on draft entries.
This was identified and discussed with the product team during our QA sessions, and we concluded it makes sense to exclude all validations on drafts except the max length/value ones.
This PR only includes de BE side, but will require adapting the FE to not trigger the validations on draft entries.

fix: draft validations

---

packages/core/admin/server/src/config/admin-actions.ts
packages/core/admin/server/src/domain/action/__tests__/action-provider.test.ts
packages/core/admin/server/src/domain/action/index.ts
packages/core/admin/server/src/domain/action/provider.ts
packages/core/admin/server/src/domain/condition/__tests__/condition-provider.test.ts
packages/core/admin/server/src/validation/action-provider.ts
packages/core/admin/server/src/validation/common-validators.ts
packages/core/content-manager/server/src/controllers/__tests__/relations.test.ts
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/content-manager/server/src/policies/hasPermissions.ts
packages/core/content-manager/server/src/services/permission-checker.ts
packages/core/utils/src/__tests__/provider-factory.test.ts
packages/core/utils/src/provider-factory.ts
packages/plugins/i18n/server/src/services/permissions/actions.ts
packages/plugins/users-permissions/server/bootstrap/users-permissions-actions.js
tests/api/core/content-manager/api/relations-permissions.test.api.js

:warning:  **This PR is a v4 port of https://github.com/strapi/strapi/pull/20878.**
Introduce a new `aliases` property on admin actions (`RBAC`).
This property is defined as an optional array of action alias.
```ts
interface ActionAlias {
/**
* The action ID to alias
*/
actionId: string;
/**
* An optional array of subject to restrict the alias usage
*/
subjects?: string[];
}
type Action = {
// other properties ...
/**
* An optional array of @see {@link ActionAlias}.
*
* It represents the possible aliases for the current action.
*
* Aliases are unidirectionals.
*
* Note: This is an internal property and probably shouldn't be used outside of Strapi core features.
*       Its behavior might change at any time without notice.
*
* @private
*/
aliases?: ActionAlias[];
};
```
A new method …

RBAC Action Aliases - v4

---

packages/utils/upgrade/resources/codemods/5.0.0/dependency-upgrade-react-and-react-dom.json.ts

Codemod to upgrade react and react-dom to `^18.0.0`, and keeps both under the same version
run following command from examples project in the repo
`../../packages/utils/upgrade/bin/upgrade.js codemods run 5.0.0-dependency-upgrade-react-and-react-dom-json`
play around with the versions in package.json, should upgrade both to `^18.0.0`

Add codemod for react and react-dom

---

packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx

`DescriptionComponentRenderer` receive all the possible buttons and all the components are rendered even if at the end they are not showed. So we explicitly remove the publish button as it is not showed in the ListView and because the PublishAction button performs requests that we don't want to make at the list view.
1. Go to any CT on the Content Manager. 
2. It should not have any request to countDraftRelations endpoint
closes #20736

fix(content-manager): dont perform unnecessary requests

---

packages/core/core/src/services/entity-validator/validators.ts
tests/api/core/strapi/document-service/uniqueness.test.api.ts

Skips the uniqueness validation when the value is an empty string. This applies to short text, long text, and uid fields.
After checking with @innerdvations, we never want to check uniqueness when no value is provided. Uniqueness was already skipped for null and undefined, but not for empty strings. This was revealed when working on the UID field, but was also an issue for text fields.
- create a content type with a slug field
- save 2 entries with different slug values, you should be able to save
- try to have the same value in both slugs, you should get an error
- clear the value in both slugs (make them empty), **you should be able to save**
Repeat the same steps for a text value with uniqueness turned on

fix: don't check uniqueness for empty strings

---

packages/core/core/src/utils/__tests__/transform-content-types-to-models.test.ts
packages/core/core/src/utils/transform-content-types-to-models.ts

- We probably forgot to include lifecycles when transforming contentTypes into models format,
so this adds the lifecycles attribute
- Lifecycles are not triggered in V5
- Add some lifecycles to any contentType, maybe some logs, and check if they are triggered
- look at issue #20551 
fixes #20551

Add lifecycles when transforming contentTypes to models

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

Don't call the `countDraftRelations` from the content manager list view
- There is no use for the response from these calls in the list view
- When bulk publishing from the list view we make a call to `API/countManyEntriesDraftRelations` which provides the data we need
- It was causing performance issues as a call was made for every entry in the list view table
Navigate to the CM list view and inspect the network tab
DX-1501
Fixes https://github.com/strapi/strapi/issues/20736

fix(content-manager): dont count draft relations on the list view

---

packages/utils/upgrade/resources/codemods/5.0.0/comment-out-lifecycle-files.code.ts

Comments out lifecycles files, and add a comment describing why
- Lifecycles will probably behave in unexpected ways for users in V5, they probably need to migrate to document service middlewares
- run codemod from any example project
`../../packages/utils/upgrade/bin/upgrade.js codemods run 5.0.0-comment-out-lifecycle-files-code`
- all lifecycles files  will be commented out with a description at the top

V5 lifecycles codemods

---

packages/utils/upgrade/resources/codemods/5.0.0/change-useAPIErrorHandler-import.code.ts

Codemod to change useAPIErrorHandler import to `@strapi/strapi/admin`
you can test in any of the example folders using:
`../../packages/utils/upgrade/bin/upgrade.js codemods run 5.0.0-change-useAPIErrorHandler-import-code`

change useAPIErrorHandler import to `@strapi/strapi/admin` codemod

---

packages/core/content-type-builder/server/src/controllers/validation/__tests__/component.test.ts
packages/core/content-type-builder/server/src/controllers/validation/__tests__/content-type.test.ts
packages/core/content-type-builder/server/src/controllers/validation/content-type.ts
packages/core/content-type-builder/server/src/controllers/validation/model-schema.ts
packages/core/content-type-builder/server/src/services/builder.ts
packages/core/content-type-builder/server/src/services/constants.ts
tests/api/core/content-type-builder/collection-type.test.api.js

- adds support for prefixes in the ctb reserved names
- reserves `strapi*`, `_strapi*`, and `__strapi*` for model and attribute names in the CTB
So that no further breaking changes are required to add new Strapi content types or attributes
You should now receive an error if you try to create content types or attributes within a content type that start with 'strapi', '_strapi', or '__strapi'
DX-1370

enhancement!: restrict strapi prefixes in CTB

---

tests/e2e/tests/i18n/editview.spec.ts

Fixes an issue with i18n bulk actions test
Related to DX-1550 but does not fix it
I found a bug with webkit while looking into this. It seems like an app wide issue with webkit + modals. I thought it best to continue with this fix and handle the webkit issue separately

fix(e2e): i18n bulk actions

---

packages/core/upload/admin/src/components/AssetCard/tests/AssetCardBase.test.jsx
packages/core/upload/admin/src/components/FolderCard/tests/FolderCard.test.jsx
packages/core/upload/admin/src/components/FolderCard/tests/__snapshots__/FolderCard.test.jsx.snap

remove `.only` from a couple tests and udpates the snapshots for them
they shouldn't have been committed
tests should pass

test(front): enable skipped tests

---

examples/getstarted/src/api/category/content-types/category/schema.json
examples/getstarted/src/api/relation-locale/content-types/relation-locale/schema.json

Some changes were made to the getstarted schema in v5. In order for us to test the v4->v5 migrations, those schemas need to be the same, hence this PR updates the `relation-locale` content type in v4 to be the same as in v5.
This fixes a failing internal migration (discard draft) that was assuming the relation existed in the v4 database data.
Fixes #20953

chore: getstarted schema sync between v4-v5

---

packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/services/cli-api.ts

This PR adds a new validation that prevents deployment if the project is in a suspended status.
Currently, the deployment process continues even if the project is suspended, only failing after the user completes the upload without the CLI providing any prior warning.
- Try the deploy command on a suspended project:
- 	The deployment should not initiate.
-   A message should be displayed explaining why the deployment didn’t start, along with a link to the dashboard where you can view the suspension reason and take action.

Chore(CLI): Add validation to prevent deployment of suspended projects

---

packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts

If you had a content-type with i18n enabled and multiple locales in v4, when you use the upgrade tool to migrate to v5 the locales are no longer properly linked (different document ID)
We renamed some of our table names in v5, mostly to fit long content types /field names into the database. The migration to migrate to document ids expected the locale join table to be renamed to the new format, but it wasn't.
This PR adds the necessary changes so the locales share the same document id.
Ideally , we would have some automated tests.
- Using a v4 project, create multiple locales of the same entry in a content type with i18n.
- Migrate to v5
- You should see a single document with multiple locales
fixes: https://github.com/strapi/strapi/issues/21037

fix: v5 migration does not link locales

---

packages/core/content-manager/server/src/history/services/history.ts
packages/core/content-manager/server/src/history/services/lifecycles.ts
packages/core/content-manager/server/src/history/services/utils.ts
tests/api/core/content-manager/content-manager/history/history.test.api.ts

Fix a bug related to the history page of content type without localisation enabled. Now we considered these type of content types and we allow saving history of content types with no i18n.
1. Go to a Content Type with no i18n enabled and create and edit one entry.
2. Go to the history page of that entry
3. It should show the history without errors
closes https://github.com/strapi/strapi/issues/20945

fix(content-manager): error when content type has no i18n enabled

---

packages/utils/upgrade/src/modules/format/formats.ts
packages/utils/upgrade/src/modules/project/__tests__/project.test.ts
packages/utils/upgrade/src/modules/project/constants.ts
packages/utils/upgrade/src/modules/project/project.ts
packages/utils/upgrade/src/modules/project/types.ts
packages/utils/upgrade/src/tasks/__tests__/codemods.test.ts
packages/utils/upgrade/src/tasks/codemods/list-codemods.ts
packages/utils/upgrade/src/tasks/codemods/run-codemods.ts
packages/utils/upgrade/src/tasks/upgrade/upgrade.ts

Refactors the handling of project files by differentiating between application and plugin projects.
It introduces new constants for allowable root paths and specific root files for both project types.
The `Project` class is updated to accept a configuration object, which includes paths specific to either applications or plugins.
`AppProject` and `PluginProject` constructors are updated to define their specific paths.
The previous approach used generic constants that led to inconsistencies and (most importantly) errors when dealing with different types of projects (app/plugin).
1. Create a sample application and plugin projects in their respective directories.
2. Run the upgrade tasks (e.g., `list-codemods`, `run-codemods`, `upgrade`) with the `debug` flag enabled to ensure project …

Fix Upgrade Tool Targeted Files For Plugins

---

packages/cli/cloud/src/services/cli-api.ts

This PR updates the link command request route to get a list of projects available to link.
The cli-api has a new route for getting the list of linkable projects
Run the link command and you should get the list of available projects to link

fix(cli): Update endpoint path for listLinkProjects

---

packages/core/content-manager/admin/src/hooks/useDocumentLayout.ts

Pass complete components data to format edit layout function so it works when you change the fields name in configure the view for nested components.
Follow the steps mentioned on the [issue](https://github.com/strapi/strapi/issues/20978). It should work without errors.
Closes #20978

fix(content-manager): pass components data to format function for edit layout

---

docs/yarn.lock
package.json
yarn.lock

updates `lint-staged` from 13.3.0 to 15.2.9
updates the `yarn.lock` resolution for `micromatch` to 4.0.8
micromatch <= 4.0.7 technically has a security vulnerability, and even though Strapi is not vulnerable to it, this helps clean up for security audits
Note that it doesn't solve the issue completely, as `plop` still requires an old version of `liftoff` which requires a 3.x version of `micromatch`, but that will come in a later PR
CI should still work correctly even with the new version of `lint-staged`
DX-1571

chore: update lint-staged to 15.2.9

---

.github/workflows/skipped_tests.yml

remove 'typescript' from the CLI needs, because it doesn't actually exist
it's sometimes breaking CI checks
CI should pass
Example of PR it is blocking: https://github.com/strapi/strapi/pull/21065

chore: remove missing workflow dep

---

.github/filters.yaml
.github/workflows/adminBundleSize.yml
.github/workflows/issues_handleLabel.yml
docs/yarn.lock
packages/admin-test-utils/package.json
packages/core/content-releases/package.json
packages/core/content-type-builder/package.json
packages/core/strapi/package.json
yarn.lock

- adds missing dependencies
- removes helper-plugin references (doesn't actually fix anything, but they aren't needed anymore)
- incidentally updates docs/yarn.lock which needed to be done and hadn't, so cacheKey is modified, hence most of the file being modified
contributor docs deployment was failing because of missing dependencies
CI check for contributor docs deploy should now pass

chore: fix vercel contributor-docs deploy errors

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts

Covers CTB modal state management with e2e test

chore(e2e): cover ctb tab state management

---

packages/core/core/src/middlewares/__tests__/security.test.ts
packages/core/core/src/middlewares/security.ts
packages/core/strapi/src/node/vite/plugins.ts

Fix https://github.com/strapi/strapi/issues/20473
- set `'url': '/dashboard'` in `config/admin.js`
- get to http://localhost:1337 in dev mode -> it should redirect to /dashboard & work just fine
- run yarn build and yarn start
- - get to http://localhost:1337 in dev mode -> it should redirect to /dashboard & work just fine

fix: admin path not taken into account on build & security middleware

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentStatus.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx

Fix two IU issues:
* [Draft tag color was not the right one](https://github.com/strapi/strapi/issues/20814)
* [Release menu icons size is wrong](https://github.com/strapi/strapi/issues/20776)
https://github.com/strapi/strapi/issues/20776
https://github.com/strapi/strapi/issues/20814

fix: draft tag color & release menu icons size

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

Width of dialog buttons should be 100%
Try to delete document or delete locale 
https://github.com/strapi/strapi/issues/20816

fix(content-manager): change buttons of dialog to have fullWidth

---

packages/core/content-releases/server/src/controllers/__tests__/release-action.test.ts
packages/core/content-releases/server/src/controllers/release-action.ts
packages/core/content-releases/server/src/services/release.ts

On createAction function we run the updateReleaseStatus function without awaiting for it. This is on purpose because updateReleaseStatus function could be expensive to run, so we want to return an answer and let this run on the background.
For bulk add to release we create a transaction so we can catch a possible error when adding one entry to a release and rollback everything, so we call `createAction` for each entry user is adding, this create two problems:
* We are calling `updateReleaseStatus` for each entry added to the release, this is inefficient.
* Depending on how long takes `updateReleaseStatus`, and considering this is inside a transaction, we could end up running queries when transaction is ended, causing crash errors.
To fix all this, I add a new option to `createAction` so …

fix(content-releases): await release status update after createMany actions

---

packages/utils/upgrade/resources/codemods/5.0.0/nocontent-migrate-to-emptystatelayout.code.ts
packages/utils/upgrade/resources/codemods/5.0.0/useRBAC-hook-import-change.code.ts
packages/utils/upgrade/resources/utils/change-import.ts
packages/utils/upgrade/resources/utils/replace-jsx.ts

Adds a codemod to change NonContent to EmptyStateLayout
V5 plugin upgrade path
- `npx create-strapi-app@rc v5-rc`
- `npx @strapi/sdk-plugin@latest init sdk-plugin` in the project
- cd PATH_TO_PLUGIN
- `PATH_TO_THIS_BRANCH/packages/utils/upgrade/bin/upgrade.js codemods run`
DX-1532

chore(upgrade): codemod for replacing nocontent with emptystatelayout

---

packages/cli/create-strapi-app/src/index.ts

- fix: use dynamic pkg.json import to get write pkg version during install

fix: use dynamic pkg.json import to get write pkg version during install

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts

V5 Migration  is erasing some existing relations on the draft versions, but they are kept on the published ones.
Fixes https://github.com/strapi/strapi/issues/21116

fix: draft relations not being copied over when migrating to v5

---

packages/core/core/src/services/document-service/repository.ts
packages/core/core/src/services/document-service/utils/unidirectional-relations.ts
tests/api/core/strapi/document-service/relations/unidirectional-relations.test.api.ts
tests/api/core/strapi/document-service/relations/unidirectional-relations.ts
tests/api/plugins/i18n/content-manager/non-localized-fields.test.api.js

Updates uni directional relations to target the right entries when overriding published or draft entries.
Based on the following [notion RFC](https://www.notion.so/strapi/Unidirectional-relations-on-publish-discard-29d0133709c646b088f377727c9c7ff1)

feat: sync unidirectional relations

---

.husky/pre-commit
packages/core/admin/admin/src/components/tests/PrivateRoute.test.tsx
packages/core/upload/admin/src/components/AssetCard/tests/AssetCardBase.test.jsx

adds a pre-commit hook for staged changes that include `(test|it|describe).only`
prevent us from accidentally committing a `.only()` in a test, which has happened several times in the past; we should only allow `.skip()` because then it is obvious something was intentionally skipped
- after running `yarn prepare`
- try staging and committing a change with a test that includes .only left in it; you should be prevented
- having .only in your code that isn't staged should still be ok
DX-1593

enhancement: prevent committing tests with only

---

packages/core/admin/admin/src/pages/Marketplace/components/NpmPackageCard.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplacePage.test.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplacePlugins.test.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplaceProviders.test.tsx

Hides the install button for incompatible versions
v5 plugins are entering the marketplace, and this will be the initial approach to guiding users to the correct plugin version
more updates will be coming after v5 launch to improve the experience
Only compatible plugins should show the install button.
You can set up a proxy to mock the data from market-api.strapi.io or verify with some existing plugins that are out of the current version range. Which there currently aren't any, but in a few hours the marketplace cache should pick up that we've upgraded the documentation plugin to 5.0.0.
DX-1531

fix: (v4) marketplace hide install button when incompatible

---

packages/core/admin/admin/src/pages/Marketplace/components/NpmPackageCard.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplacePage.test.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplaceProviders.test.tsx

Hides the install button for incompatible versions
v5 plugins are entering the marketplace, and this will be the initial approach to guiding users to the correct plugin version
more updates will be coming after v5 launch to improve the experience
Only compatible plugins should show the install button.
You can set up a proxy to mock the data from market-api.strapi.io or verify with some existing plugins that are out of the current version range. Which there currently aren't any, but in a few hours the marketplace cache should pick up that we've upgraded the documentation plugin to 5.0.0.
However, it's also being tested in front-end tests
DX-1586
[v4 version](https://github.com/strapi/strapi/pull/21111)

fix: (v5) marketplace hide install button when incompatible

---

docs/yarn.lock
templates/website/yarn.lock
yarn.lock

- docs: fixes the mismatched checksum
- templates/website: updates the resolution from 4.0.7 to 4.0.8 (security issue)
- root: moves the ^4.0.2 resolution to 4.0.8
Note: we still have a resolution from 4.0.5 -> 4.0.5 because it's a fixed version coming from `plop`. But strapi isn't and wasn't vulnerable to the security issue. We will handle upgrading plop at a later time to allow security audits to pass.
- [security issue for micromatch](https://github.com/advisories/GHSA-952p-6rrq-rcjv)
- fixes vercel deployment (mismatched checksum)

fix: micromatch update

---

packages/core/content-manager/server/src/controllers/relations.ts

It was noticed during the development of https://github.com/strapi/strapi/pull/21010 (specifically [here](https://github.com/strapi/strapi/pull/21010#discussion_r1716882293)) That a relation from a Content Type with disabled DP to another one with enabled DP can show both the relation targetting the draft and the published version, see:
This is at least confusing, and we should only show one relation.
We have debated multiple solutions, and atm product and engineering proposals are contradictory and we need to get to an agreement.
Product:
- From the content type without DP, show only the published version of the relation, and fallback to the draft
Engineering:
- From the content type without DP, show only the draft relation. 
That way, modifying the relation from that side does not …

fix: return only drafts on relations from no DP to DP

---

packages/core/admin/admin/src/pages/Auth/AuthPage.tsx
packages/core/admin/admin/src/pages/Auth/components/Register.tsx
tests/e2e/tests/admin/signup.spec.ts

When user mark "news" checkbox during registration they should be redirected to `/usecase` page before going to the admin panel. Right now they are being redirected to the admin panel instead.
This was happening because on `Register` component, on Register function (exactly [here](https://github.com/strapi/strapi/blob/develop/packages/core/admin/admin/src/pages/Auth/components/Register.tsx#L156)) we set the user's token. This cause `AuthPage` ([here](https://github.com/strapi/strapi/blob/develop/packages/core/admin/admin/src/pages/Auth/AuthPage.tsx)) to rerender because token has changed, that cause users to being redirected to the admin panel instead of `/usecase` because now token is not empty
Solution is very simple, we really don't need to redirect users to admin if token is set at …

fix(admin): don't redirect if token is set

---

packages/core/types/src/modules/documents/params/sort.ts

Restrict the sort array notation to `StringNotation[] | ObjectNotation[]` to forbid arrays with mixed types.
To make the types reflect what's happening in the internal params validation.
In an example application's bootstrap file, paste the following snippet
```ts
await strapi.documents('admin::role').findMany({
sort: [{ createdBy: { email: 'asc' } }, 'name:asc'],
});
```
`'name:asc'` should be highlighted as a type error (it wasn't before)
Verify you can still use the following without errors
```ts
await strapi.documents('admin::role').findMany({
sort: [{ createdBy: { email: 'asc' } }, { name: 'asc' }],
});
```
or
```ts
await strapi.documents('admin::role').findMany({
sort: ['name:asc', 'description:desc'],
});
```

fix: update ArrayNotation type to forbid arrays of mixed types

---

packages/core/database/src/query/helpers/populate/apply.ts
packages/core/database/src/types/index.ts
packages/plugins/i18n/server/src/register.ts

Create a virtual localization relations point document_id back to itself. 
One caveat I saw for now that might still be better than not having localizations:
- The entry is populating itself too (we could fix this quickly)

enh: localizations field

---

packages/core/content-manager/admin/src/pages/EditView/components/Header.tsx
packages/core/content-manager/admin/src/translations/en.json
packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx
packages/plugins/i18n/admin/src/translations/en.json
tests/e2e/tests/content-manager/editview.spec.ts
tests/e2e/tests/content-manager/history.spec.ts
tests/e2e/tests/i18n/settings.spec.ts

Fix the labels of document actions to match [the designs](https://www.figma.com/design/Tt8uHuQezEP0CsWunbulb5/Draft-%26-Publish?node-id=3189-207205&node-type=FRAME&t=MyrsKiYZY6SfTvTN-0):
- "delete document" => "delete entry" with i18n, "delete entry (all locales)" without i18n
- "delete locale" => "delete entry (locale name)"
check the action with i18n enabled, disabled, as well as while creating a new locale before it's saved

fix: delete document actions labels

---

packages/core/content-manager/server/src/controllers/single-types.ts

maps property to `documentId` instead of `id` so the document query is consistent for versions that are being created and the ones already created
similar issue fixed already in collection types in a different PR before, check https://github.com/strapi/strapi/pull/21009/files#r1726619948
- fill from locale in single types is not working
- fill from locale for singletypes should be working now and the button should not be disabled
fixes #21178

fix: single type fill from locale disabled

---

packages/core/content-type-builder/admin/src/components/GenericInputs.tsx
packages/core/content-type-builder/admin/src/utils/tests/timeFormat.test.ts
packages/core/content-type-builder/admin/src/utils/timeFormat.ts

add `handleTimeChange` function to format time when needed.
Input (Display) Format:
The`TimePicker` only supports the time format "HH:MM" (hours and minutes).
The default value set in the Content-Type Builder (CTB) comes in the format `HH:mm:ss.SSS`
To display the default value correctly, we need to convert it from `HH:mm:ss.SSS` to `HH:MM`.
Output (Submission) Format:
When a user selects or changes a time in the `TimePicker`, it provides the time in `HH:MM` format.
However, the backend expects to receive the time in the full `HH:mm:ss.SSS` format.
Therefore, we need to convert the user-selected time from `HH:MM` back to `HH:mm:ss.SSS` before sending it to the backend.
In summary:
For display: Convert `HH:mm:ss.SSS` → `HH:MM`
For submission: Convert `HH:MM` → `HH:mm:ss.SSS`
Manually: 
- …

fix: fix default time formatting issue

---

packages/plugins/i18n/admin/src/utils/clean.ts

Remove status field from added fields fields when filling from another locale
look at issue #21179 
status field shouldn't be filled from another locale
Try to fill from another locale (when the other locale is in `modified` status) and then save it should work with no errors
you can check #21179 for reproduction
fixes #21179

fix: add status to removed fields when cleaning data

---

packages/core/review-workflows/admin/src/routes/settings/index.tsx

Fixes issue where the review workflows settings page would mess up the colors of the Admin main menu's icons (because of an odd styled-components scoping issue)
Fixed by using IconButton from the design system instead of a custom component
- Go to the RW settings page
- The main nav shouldn't look any different
- Make sure the edit and delete buttons still work as expected
https://github.com/strapi/strapi/issues/20817

fix: review workflow settings icons

---

packages/core/database/src/metadata/metadata.ts
packages/core/database/src/metadata/relations.ts
packages/core/database/src/types/index.ts
packages/core/types/src/schema/attribute/definitions/relation.ts
packages/plugins/i18n/server/src/register.ts

Prevents generating localizations link tables in the database, because they are a virtual relation
Those tables shouldn't exist in Strapi 5 and it's currently wreaking havoc in a lot of areas of the code
simple test: migrating from v4 to v5, migration should run fine and db should not include any `*localizations_links` or `*localizations_lnk` tables
long test: see the linked issues, this should solve all of them
I believe it will fix all of the following, but I haven't confirmed yet:
fix #21189
fix #21186
another migration issue that was reported internally by @PaulBratslavsky
initial misdirected poc to fix some of the issues: https://github.com/strapi/strapi/pull/21211
DX-1604

fix: do not generate localizations links table

---

packages/core/content-manager/admin/src/utils/validation.ts
packages/core/content-releases/admin/src/services/release.ts

Fix two bugs that were affecting content releases.
* When validating relations to many entries that are required we want to validate id is a number, not a string
* We need to invalidate cache data of release when entries are added to a release
1. Add one entry to a release with "hasMany" relation, validation should work 
1. Create a release
2. Add one entry to that release and move to the release page
3. Release status should be ready and publish button enabled
https://github.com/strapi/strapi/issues/21227

fix(content-releases): validation and cache releases

---

packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx
packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx
packages/plugins/color-picker/admin/src/components/tests/ColorPickerInput.test.tsx

Pass field values to CustomField Input so we can have backward compatibility and don't introduce a breaking change.
Use a Custom Field without using `useField`, instead use `value` and `onChange` that you should receive as param in your Input CustomField 
https://github.com/strapi/strapi/issues/20915

fix(content-manager): pass field to CustomField input to have backward compatibility

---

packages/core/content-releases/admin/src/components/ReleaseActionModal.tsx
packages/core/content-releases/admin/src/components/ReleasesPanel.tsx
packages/core/content-releases/server/src/controllers/release-action.ts
packages/core/content-releases/server/src/controllers/release.ts
packages/core/content-releases/server/src/services/__tests__/release-action.test.ts
packages/core/content-releases/server/src/services/release-action.ts

This PR fix multiple errors on Releases when you add a Single Type entry. SingleTypes have documentId but we don't have them on the frontend so we don't send it to the releases' endpoints. With this PR we append the documentId when content type is a Single Type. 
Follow all the Releases flow (adding an entry, edit the entry, remove it, publish, etc...) with singleType entries.
https://github.com/strapi/strapi/issues/21177

fix(content-releases): get entryDocumentId when entry is singleType

---

packages/core/admin/admin/src/pages/Marketplace/MarketplacePage.tsx
packages/core/admin/admin/src/pages/Marketplace/hooks/useMarketplaceData.ts

added a `version` parameter when sending request to market place
Allow us to filter plugins depends on Strapi App version
more detailed description [here](https://strapi-inc.atlassian.net/browse/DX-1607)
Inspect in dev tool under network tab, the payload (for both Plugins and Providers) should contain a `version` parameter when on the Marketplace page
DX-1607

enhancement: add version param when send request to marketplace

---

packages/core/utils/src/__tests__/morph.test.ts
packages/core/utils/src/relations.ts
packages/core/utils/src/sanitize/visitors/remove-restricted-relations.ts
packages/core/utils/src/types.ts
packages/core/utils/src/validate/visitors/throw-restricted-relations.ts
tests/api/core/strapi/api/relations.test.api.js
tests/api/core/upload/content-api/upload.test.api.js

- allows morph relations set, connect, disconnect, and options properties to validate/sanitize correctly
This PR is necessary for v5 stable to allow polymorphic relations input to validate/sanitize properly
It came from https://github.com/strapi/strapi/pull/21135 but that PR has too many potential side effects to merge into v5 this close to release, so only this critical part is being added for now
- verify that polymorphic relations can set/disconnect/connect through validation -- beware that they may not actually work correctly due to [this bug](https://github.com/strapi/strapi/issues/20961), the thing to test is that it makes it through validation
- ensure that it properly sanitizes and validates connect, disconnect, set, and options and doesn't allow bad values to pass through …

fix: allow morphToMany relation ordering in sanitize and validate

---

packages/cli/cloud/src/create-project/action.ts
packages/cli/cloud/src/deploy-project/action.ts

Using API URL to display the deployments for the project when the `strapi deploy` command has ended.
To avoid hard-coded URLs to the Cloud dashboard that may change.
Try to deploy a Strapi project to Strapi Cloud using `strapi deploy` command (you may need to target the local bin file of strapi binary).
`node /packages/core/strapi/bin/strapi.js`

chore(cli): replace hardcoded deployment URL

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx

This PR fix the inconsistent gap in dynamic section between components and fields.
Re-wrapping the grid with another Grid.Root and Grid.item
1. Go to /example/getstarted
2. Add a component field into blog/test-como
3. Insert a Kitchen Sink and add the Test como component, you will now see the gap
Closes #21215

fix(DynamicComponent): inconsistent gap between fields and components

---

packages/core/content-releases/server/src/controllers/release.ts

Find releases with one entry attached was returning all the actions on the release and not only the action we are. With this change we only return the action with the entry.
1. Create a release and add multiple entries to it
2. Try to delete from the release one of the last entries
3. It should delete the right entry
https://github.com/strapi/strapi/issues/21291

fix(content-releases): delete from release

---

packages/core/content-releases/admin/src/services/release.ts

Invalidate documents list from CM when a Release is published.
1. Create a release and add some entries in-draft to it.
2. Publish the release and go to the content-manager
3. Entries status should be updated

fix(content-releases): invalidate documents when release is published

---

packages/core/review-workflows/server/src/controllers/assignees.ts
packages/core/review-workflows/server/src/controllers/stages.ts
packages/core/review-workflows/server/src/routes/review-workflows.ts

fixes https://github.com/strapi/strapi/issues/21292
Basically we were checking for the "view review workflows settings" permission to update the stage, which was wrong.
So I removed it, and after [checking with Yannis](https://strapihq.slack.com/archives/C051PLC9CF7/p1726562903262239), I added a check to only allow a user to change the assignee if they have the permission to change the current stage
Note that this is only a backend fix, the field is not disabled in the frontend, but you should see the error message in the field if you don't have the permission.
Follow the steps listed in Yannis' issue: https://github.com/strapi/strapi/issues/21292

fix(rw): check transition permission to change assignee

---

packages/core/content-manager/admin/src/history/components/VersionContent.tsx
packages/core/content-manager/admin/src/history/components/VersionInputRenderer.tsx
packages/core/content-manager/server/src/history/services/history.ts

Prevents content history fields from shrinking. It copied the method from the main edit view
Instead of this:
We want this:
I also removed the shadow from the relation boxes that we don't want
Open history, check and check normal fields, fields in components, and fields in dynamic zones

fix: history fields width

---

packages/cli/create-strapi-starter/README.md
packages/core/content-manager/README.md
packages/core/content-type-builder/README.md
packages/core/email/README.md
packages/core/helper-plugin/README.md
packages/core/upload/README.md
packages/plugins/i18n/README.md

Add warning banners to be published during next v4 release

chore: v4-to-v5 warning on changed packages

---

examples/experimental-dev/package.json
packages/core/admin/package.json
packages/core/strapi/package.json
yarn.lock

upgrades vite to 5.1.7
https://github.com/advisories/GHSA-8jhw-289h-jh2g
DX-1609
https://github.com/strapi/strapi/pull/21279

chore: upgrade vite to 5.1.7

---

packages/core/data-transfer/package.json
yarn.lock

Update the `ws` dependency in the `data-transfer` package.
To solve the [CVE-2024-37890](https://github.com/advisories/GHSA-3h5v-q93c-6h6q)
Make sure it still works (seems to be covered by tests)
#20578

chore(data-transfer): update ws dependency to 8.17.1 for CVE-2024-37890

---

examples/kitchensink/.eslintrc
package.json
yarn.lock

- replace deprecated `babel-eslint` with `@babel/eslint-parser`
- upgrade `@babel/eslint-parser` to `^7.25.1`
it's unmaintained and deprecated
DX-1609
https://github.com/strapi/strapi/pull/21280

chore: replace babel-eslint with babel-eslint-parser

---

packages/core/admin/admin/src/content-manager/components/LeftMenu.tsx

Changes the filter logic for content manager , instead of using `startsWith` it uses `includes`

[feat] content manager filter logic

---

packages/core/upload/admin/src/pages/App/MediaLibrary/index.jsx

removes the un-necessary padding-y which causes the alignment issue 
`perfectly aligned as all things should be`

fix: media library action container alignment issue

---

packages/utils/upgrade/resources/codemods/5.0.0/deprecate-helper-plugin.code.ts

- Add a `newImport` to helper plugin-codemods to distinguish  between how a component is imported and how it's used
- We have issues with some of the transforms examples:
transforming to this `import { Page.Protect } from "@strapi/strapi/admin";`
instead of this `import { Page } from "@strapi/strapi/admin";`
run codemods against 
`import { CheckPagePermissions } from '@strapi/helper-plugin` should become `import { Page } from "@strapi/strapi/admin";`

fix: add importName to helper-plugin codemods

---

packages/plugins/users-permissions/server/services/providers-registry.js

Corrected TYPO in keycloak provider
Fixes issue #21391 
Default configuration of keycloak provider does not work.
Configure the provider according to https://docs.strapi.io/dev-docs/plugins/users-permissions#keycloak-config
No related issues

fix: correct spelling of keycloak provider

---

tests/e2e/tests/content-manager/uniqueness.spec.ts

- Skipping uniqueness e2e test on webkit
- The test is only failing on webkit on the github CI, we already have ticket to fix the webkit issues
- it's blocking PRs, so until we get around to fix this we will skip only on webkit 
wait for CI tests to pass

skipping uniquness e2e test on webkit

---

SECURITY.md

Updates the security document with the proper dates and information
Had some incorrect dates and the first paragraph wasn't correct
N/A
N/A

chore: Update security document in relation to Strapi 5 stable release

---

.github/workflows/issues_handleLabel.yml

Adds a new GitHub workflow that works based on if the specific `flag: v4-unsupported` label is set and comments on the issue and automatically closes it
Related to v4 issue cleanup we plan on doing for closing low/medium sev issues that cannot be reproduced in Strapi 5
N/A
N/A

chore: add workflow for automatically closing v4 issues with label

---

packages/utils/typescript/lib/generators/components/index.js
packages/utils/typescript/lib/generators/content-types/index.js

Do not generate the module augmentation for empty artifact collections (content-types, components).
Instead, add a comment to explain why the file is empty.
When no components (or content-types) exist in an app, we still try to do the module augmentation which can lead to unexpected behavior in the type system.
- `cd examples/kitchensink-ts`
- `yarn strapi ts:generate-types -d`
- open `types/generated/components.d.ts`
- The file should only contain a single comment
- `cd examples/kitchensink-ts`
- `yarn strapi ts:generate-types -d`
- open `types/generated/components.d.ts`
- The file should contain all the components' type definitions + the module augmentation
take over #19883

Add Placeholders for Empty Artifacts in Type Generation

---

packages/core/admin/ee/server/src/services/metrics.ts
packages/core/admin/server/src/services/metrics.ts
packages/core/core/src/ee/index.ts
packages/core/review-workflows/server/src/services/metrics/weekly-metrics.ts
packages/core/upload/server/src/services/weekly-metrics.ts

Previously all of our built-in metrics based cron tasks were using the simplified format:
```js
cron.add({
'*/1 * * * *': () => console.log('A minute has passed.'),
});
```
And they have been changed to use the named format
```js
cron.add({
myTask: {
task,
options: '*/5 * * * *', // Executes every 5 minutes.
},
});
```
As the maintainer of the Strapi Redis Plugin and with the new changes coming in my plugin for Strapi 5 I'm integrating the Redlock package which automatically forces all cron-tasks to use red-locks to prevent clustered environments from running the same task at the same time.
In essence what this could do is help prevent duplicate data being sent to the telemetry system from the same project running in a horizontal or vertical cluster mode.
Simply run Strapi in console mode …

enhancement: change all internal cron tasks to named tasks

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/CreatePage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/EditPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Users/EditPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Webhooks/components/WebhookForm.tsx
packages/core/admin/ee/admin/src/pages/SettingsPage/pages/SingleSignOnPage.tsx
packages/core/review-workflows/admin/src/routes/settings/:id.tsx

I removed the `size="L"` and `size="M"` properties of the buttons that had them in the settings. I also added a `<Check />` icon to the "Save" button of the admin role page.
A few pages in the settings had buttons that had a `size="L"` or a `size="M"`, but it's not supposed to be the case. All the other pages from the settings have a `size="S"`. I changed it so we have a consistent design across all pages of the settings. I added the `<Check />` icon for the same reasons.
You'll need to go to the following pages:
- Settings > Review Workflow > Open any workflow
- Settings > Review Workflow > Create new workflow
- Settings > Single Sign-On
- Settings > Webhooks > Open any webhook
- Settings > Webhooks > Create new webhook
- Settings > Roles (admin panel) > Open any role
- Settings > Roles …

chore: Harmonized all button sizes in settings

---

packages/core/review-workflows/server/src/bootstrap.ts
packages/core/review-workflows/server/src/services/document-service-middleware.ts
tests/e2e/tests/review-workflows/settings.spec.ts

Add validation when ContentType is related to one RW with required stage for publish. Entry only will be published if the entry is at the right stage.
1. Create one RW with a required stage for publish and assign it to one Content Type.
2. Create or go to an already existing entry of that Content Type and put it in a wrong stage
3. Try to publish, it should throw an error
4. Change entry's stage for the required one and try to publish
5. It should publish with no errors

feat(review-workflows): check entry stage before publish

---

packages/core/admin/admin/src/components/Filters.tsx
packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx
packages/core/content-manager/admin/src/services/documents.ts
packages/core/upload/admin/src/components/FilterList/index.jsx
packages/core/upload/admin/src/components/FilterList/tests/__snapshots__/index.test.js.snap
packages/core/upload/admin/src/components/FilterPopover/index.jsx

Fixes a bug where filtering by text fields containing the "&" symbol fails due to improper encoding and decoding of query parameters.
Without this fix, users cannot correctly filter records by text fields containing special characters such as "&", which significantly hampers the usability of the filtering functionality.
Create an entity in a collection type with a text field containing the "&" symbol.
Example: Create an article titled "Test article & issue reproduce".
Go to the list of the collection type.
Use the "Filters" button to select the text field, "is" operand, and text with the "&" symbol.
Click "Add filter".
Verify that the filter is applied correctly and the appropriate records are displayed.
Related issue(s)/PR(s)
#20271

fix: Filter by text field with "&" symbol doesn't work #20271

---

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.jsx
packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.jsx.snap

I added a gap between the 2 icon buttons of the media library modal (add new assets).
It's only a UI issue but it makes it look less "buggy".
Go to the edit view, find an empty media input and click on it.
https://github.com/strapi/strapi/issues/20772

fix: Added a gap between the 2 icon buttons

---

SECURITY.md
packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations.tsx
packages/core/content-manager/admin/src/services/relations.ts
packages/core/content-manager/server/src/controllers/relations.ts
packages/core/content-manager/server/src/services/document-metadata.ts
packages/core/content-manager/server/src/utils/index.ts
packages/core/core/src/services/document-service/repository.ts
packages/core/core/src/services/document-service/utils/unidirectional-relations.ts
tests/api/core/content-manager/api/relations-permissions.test.api.js

- Fix https://github.com/strapi/strapi/issues/21355
- Fix https://github.com/strapi/strapi/issues/21382
Replacement for https://github.com/strapi/strapi/pull/21390
- Fixes findExisting returning both draft & published entries when non DP relations are present
- Fixes UI not sending the documentId & locale as part of relations infos
- Fixes Relation links not including the locale & redirecting to the defaultLocale instaed (will need refactoring later)
- When a DP doc is published and is targeted by a non DP source with a unidirectional relation, the relation should point to both Draft & Published
- v4 to v5 migration doesn't create links to both published & drafts when running discardDraft
- RTK query cache is messing up with the UX

fix: cm relations

---

packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/ContentTypeBuilderNav.tsx
packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.tsx.snap

- Added padding bottom to SubNav component to provide room for "Create new component" button
check :  https://github.com/strapi/strapi/issues/20801
Visit `content-type-builder` page and scroll to the bottom such that "Create new component" button is visible. Now if we hover over any link, the browser popup that display the link will not hide the "Create new component" button.
fixes: https://github.com/strapi/strapi/issues/20801

fix : Create new component button ends up being hidden

---

packages/core/content-manager/admin/src/hooks/tests/useDocument.test.tsx
packages/core/content-manager/admin/src/hooks/tests/useDocumentLayout.test.ts
packages/core/content-manager/admin/src/hooks/useDocumentLayout.ts
packages/core/content-manager/admin/tests/mockData.ts

Fixes https://github.com/strapi/strapi/issues/21267
I narrowed down the problem to when a dynamic zone is the first field in the edit view layout, and there's one or more fields after.
I updated the tests so they would get the bug with the previous version of the `useDocumentLayout` code (by adding a dynamic zone at the start of the layout).
Test the flow that would break before:
- create a new content type
- add a dynamic zone field first
- then add a text field (or anything else)
- then open the edit view for that content type, or the configure the view page
I think we also need some random QA to try various combinations: DZ after DZ, DZ then field then DZ, field then DZ...
https://github.com/strapi/strapi/issues/21267

fix: dynamic zones breaking layout logic

---

packages/core/types/src/modules/documents/params/attributes/id.ts
packages/core/types/src/modules/documents/params/attributes/index.ts
packages/core/types/src/modules/documents/params/attributes/relations.ts
packages/core/types/src/modules/documents/params/filters/index.ts
packages/core/types/src/public/shared.ts
packages/core/types/src/schema/attribute/definitions/relation.ts

- Add the possibility to filter on `documentId` (root and nested filters)
- Added back the support for the relation re-ordering API in create/update data payloads
_I've also split the attribute utils (document service's params) into different files to make it less bloated._
Fix incorrect behaviors in the document service types
Reproduce the queries from https://github.com/strapi/strapi/issues/20735#issuecomment-2380452010 using any application and similar content types
fix #20735

Fix Various Document Service Type Issues

---

packages/core/admin/admin/src/components/LeftMenu.tsx
packages/core/admin/admin/src/components/Onboarding.tsx

Closes #21545, solution from another branch.
Сhanged the with and height value for all svgs used in the LeftMenu & Onboarding. It was changed from rem to <N*10>px. Rem was leading to the error message Error: Invalid value for attribute width="rem" in the Safari browser.
Changed the with and height value for all svgs used in the packages/core/admin/admin/src/components/LeftMenu.tsx LinkIcon component. It was changed from 2rem to 20px.
Changed the with and height value for all svgs used in the packages/core/admin/admin/src/components/Onboarding.tsx Play component. It was changed from 1.2rem to 12px.
Rem was leading to the error message Error: Invalid value for attribute width="rem" in the safari browser.
Run new project in dev mode, open …

fix: <svg> attribute width="<N>rem" errors in Safari

---

packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-releases/admin/src/components/EntryValidationPopover.tsx
packages/core/content-releases/admin/src/components/tests/EntryValidationPopover.test.tsx
packages/core/content-releases/admin/src/pages/ReleaseDetailsPage.tsx
packages/core/content-releases/admin/src/translations/en.json
packages/core/content-releases/package.json
packages/core/content-releases/server/src/controllers/release-action.ts
packages/core/content-releases/server/src/services/release-action.ts
packages/core/content-releases/shared/contracts/release-actions.ts
tests/api/core/review-workflows/review-workflows.test.api.ts
tests/e2e/tests/content-releases/release-details-page.spec.ts
yarn.lock

This PR refactors the Status column on Releases details page to add a Popover where we show both: fields validations & stage validation of each entry inside a release.
1. Create a release and a Review Workflow with a required stage to publish
2. Add multiple entries to your release.
3. Check the status column is showing the expected information
- Icon colors are not okay. I will add a following PR on the DS for this.

feat(content-releases): add stage check to releases details page

---

packages/core/core/src/loaders/plugins/get-enabled-plugins.ts

Update the plugin loader to use `packageModulePath` instead of `packagePath` when resolving plugins.
It ensures that the `toDetailedDeclaration` function gets the correct path and thus doesn't throw unwanted errors
See #20298
See https://github.com/strapi/strapi/issues/20298#issuecomment-2380550149
fix #20298
---

Fix Internal Plugin Resolve Path

---

packages/core/types/src/modules/documents/params/populate.ts
packages/core/types/src/schema/attribute/definitions/component.ts
packages/core/types/src/schema/attribute/definitions/media.ts
packages/core/types/src/utils/expression.ts
packages/core/types/src/utils/index.ts
packages/core/utils/src/convert-query-params.ts

Introduces (add back) a deprecated method for populating second-level links in polymorphic structures using a shared `populate`.
It also includes:
- the addition of the `CountClause` type
- updates for handling nested population queries more robustly
- introduces the `Pretty` type for enhancing readability of complex type intersections
Ease the migration to v5 while we work on a better solution to allow pattern matching during populate ops.
Allow developers to populate polymorphic links' relations using a wildcard (`'*'`), although this method will be deprecated in the next major.
- Verify that the deprecated `populate` method works with polymorphic links using a wildcard.
- Ensure that the `CountClause` type is applied correctly in populate clauses (should only be there for regular …

Add Back the Deprecated Shared Populate Option for Morph Links

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts
packages/core/core/src/services/document-service/common.ts
packages/core/core/src/services/document-service/entries.ts
packages/core/core/src/services/document-service/index.ts
packages/core/core/src/services/document-service/repository.ts

As described in https://github.com/strapi/strapi/issues/21583#issuecomment-2393242982 , trying to migrate from v4 with invalid enum values (e.g. an enum that allows red,green, blue but the stored value is "yellow") resulted in the `discard-draft` migration crashing, and so preventing the migration to happen.
example error:
```
MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: theme must be one of the following values: dark, light, yellow,    
at /Users/marcroig/Documents/strapi/strapi/node_modules/umzug/lib/umzug.js:169:27    
```
We concluded that any badly formated data in v4 should be also preserved in v5 during the migration (as long as app works and data is modifiable). So the `discard-draft` migration will run without any data validation (enums, max, …

fix: v5 migration with wrong enum values

---

packages/core/admin/admin/src/pages/Marketplace/components/NpmPackageCard.tsx
packages/core/admin/admin/src/pages/Marketplace/tests/MarketplacePage.test.tsx

insures that  a plugin is considered incompatible if versionRange is not valid
copy install button is showing on invalid plugins for v5
- plugins like “BigBluebutton” or “Cloudflare pages” shouldn’t be shown with the “Copy install command” button

fix: copy button shown on v4 plugins

---

packages/cli/cloud/src/cloud/command.ts
packages/cli/cloud/src/environment/command.ts
packages/cli/cloud/src/environment/list/action.ts
packages/cli/cloud/src/environment/list/command.ts
packages/cli/cloud/src/environment/list/index.ts
packages/cli/cloud/src/index.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/types.ts

This PR introduces the environment list command to the Strapi Cloud CLI.
Additionally, it aligns with the General CLI Guidelines RFC by removing colons as namespace separators for commands and subcommands. To support this, two new base commands, cloud and environment, have been added to enable clearer command composition.
A future refactor of existing commands to follow this updated structure should be considered.
With the introduction of Strapi Cloud multi environments feature, we want to allow users to list their available environments from a linked project in their CLI.
An endpoint is available in CLI-API. The command can be tested against staging env checking the following scenarios:
1. Non-Strapi Project:
Running the command in a non-Strapi project should fail and return an …

feat(cli): add environment list command to cloud cli

---

packages/core/content-manager/server/src/history/services/__tests__/lifecycles.test.ts
packages/core/content-manager/server/src/history/services/lifecycles.ts

- stops using an ISO 8601 string in the filter, because it breaks on mysql
- gives a name to the cron job (we don't use strapi.cron because we don't want the job to be disable-able)
- adds a catch clause to prevent crashing the app if other errors occur
- Use different types of databases, starting with mysql
- Update the code to make the job run every second: `* * * * * *`, add a log to make sure it works, and build the content manager (or run yarn setup)
- The app should not crash
- Old history version entries should be deleted (you can make some to test with a db explorer)
fixes #21613

fix: history cron job breaking on mysql

---

packages/core/review-workflows/server/src/services/stages.ts

There is an ongoing [PR](https://github.com/strapi/strapi/pull/21501) to fix non DP entries that were migrated with an empty "publishedAt" column, this issue also was breaking RW, making it imposible to change a stage. 
This will fix it asap before we merge the other PR

fix: update review workflow

---

packages/core/core/src/services/document-service/transform/__tests__/id-map.test.ts
packages/core/core/src/services/document-service/transform/id-map.ts
packages/core/database/src/migrations/internal-migrations/5.0.0-04-published-at.ts

A migration to add the publishedAt column was not setting a default value for content types without DP. 
Resulted in non DP entries to have null values on the publishedAt column. It failed when trying to load relations to such content types with an unexpected NULL publishedAt column. 
This PR:
- Fixes the migration
- Prevents this being an issue at all. Loading relations to nonDP content types do not require filtering by the publishedAt attribute
Fixes https://github.com/strapi/strapi/issues/21166

fix: loading relations without DP fails after migrating to v5

---

.github/workflows/tests.yml

Moved lint to second strage since it requires build stap
Removed pretty as a requirement to run second stage tests (Final test will still fail but we atleast want to know if the code passes) 
increase E2E shards 
1  to not build 2 times
2 To make the tests run if prettier fails so that we can still check if there are any code issues or only prettier issues
3 so that the time it takes for the tests to run goos down from 21 to 15
If all test pass it should be fine 
https://github.com/strapi/strapi/pull/21467
2 shards https://github.com/strapi/strapi/actions/runs/11256802614
5 shards https://github.com/strapi/strapi/actions/runs/11257246445/job/31301300364?pr=21740
7 shards https://github.com/strapi/strapi/actions/runs/11257753134?pr=21 …

fix: test CI/CD building repo 2 times

---

packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx

Do not display the "Fill from locale" button if i18n is not enabled or there is not more than one locale.
fixes #21203

fix: do not display fill from locales if i18n no enabled

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations.tsx
packages/plugins/users-permissions/server/controllers/validation/user.js

It was not possible to create a new U&P user, or update its roles. 
U&P was expecting the role attribute to be set using the `id` attribute, but the CM was only sending the document ID.
By default, when connecting a relation, the document service [ will prioritize the documentId ](https://github.com/strapi/strapi/blob/7a6d9a2b0e029dd25100e68f71a35f20a134d3a2/packages/core/core/src/services/document-service/transform/relations/extract/data-ids.ts#L60) and transform it to the appropiate entry id.
fixes #21653

fix: send ids when connecting relations to update u&p user role

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Initializer.tsx
packages/core/content-manager/admin/src/translations/en.json
packages/core/content-manager/admin/src/translations/es.json
packages/core/content-manager/admin/src/translations/fr.json
packages/core/content-manager/admin/src/translations/ja.json
tests/e2e/tests/content-manager/uniqueness.spec.ts

I changed the wording in the component and in 4 translation files (English, French, Spanish and Japanese).
The current wording asks the user to click on a button that doesn't exist.
Open an entry that has components and check their empty version.
https://github.com/strapi/strapi/issues/20798

fix: changed empty components wording

---

packages/core/content-manager/admin/src/preview/components/PreviewSidePanel.tsx
packages/core/content-manager/admin/src/preview/index.ts
packages/core/content-manager/admin/src/preview/services/preview.ts
packages/core/content-manager/admin/src/translations/en.json

Adds an external link button to the preview URL.
No tests here as unit tests wouldn't add real value, and this will be covered by end to end tests soon.
Open any edit view page, you should see the preview panel on the right sidebar, clicking should take you to the (fake) preview URL in a new tab

enhancement: add preview panel button

---

.github/filters.yaml
.github/workflows/skipped_tests.yml
.github/workflows/tests.yml

implements filters specific for each type of integration/e2e tests so we run exactly what is necessary
e2e tests are currently not running when e2e tests are changed, because we were piggybacking on the setup for api tests. now all the test types should just track themselves
CI should run exactly what it needs to. For example:
- a change to a backend file will trigger runs for api, cli, e2e, and unit:back
- a change to a frontend file will trigger runs for unit:front and e2e
- a change to an api test or utility will trigger runs only for api
- a change to an e2e test or utility will trigger runs only for e2e
- a change to a cli test or utility will trigger runs only for cli
- a change to github workflows will trigger all tests (this is a trade-off; the test results themselves will never …

chore: add test workflow filters for each test type

---

examples/getstarted/package.json
examples/kitchensink/package.json
packages/cli/create-strapi-app/src/utils/database.ts
yarn.lock

generates new projects with mysql 3.9.8 instead of 3.9.4
CVE-2024-21511
CVE-2024-21512

chore: upgrade mysql2 package

---

.github/workflows/tests.yml

use mysql for dbclient in api_ce_mysql workflow
api_ce_mysql tests are not receiving a dbclient value and are probably currently running with sqlite
CI should work

chore: fix mysql workflow

---

packages/core/core/package.json
packages/core/types/package.json
templates/website/yarn.lock
yarn.lock

upgrades @koa/router from 12.0.1 to 12.0.2
fixes path-to-regexp subdep vulnerability
tests should all pass

chore: upgrade koa/router to 12.0.2

---

packages/core/content-manager/admin/src/services/documents.ts
tests/e2e/tests/content-manager/listview.spec.ts

Fixes the way query params are written into the URL of the list
It seems like when passing a params object in the config, RTK query stringifies it properly, but here an object was put directly into the string.
Have 2+ pages of content. Navigate between pages. Then content should reflect the page you're on
fixes #21789
introduced in #21406

fix: broken list view pagination

---

packages/plugins/i18n/server/src/register.ts
packages/plugins/i18n/server/src/services/index.ts
packages/plugins/i18n/server/src/services/sanitize/index.ts
packages/plugins/i18n/server/src/utils/index.ts
packages/plugins/users-permissions/server/controllers/role.js
tests/api/core/content-manager/search.test.api.js
tests/api/core/strapi/api/sort/sort.test.api.ts
tests/api/core/strapi/api/validate/validate-query.test.api.js

Make `locale` and `localizations` attributes private if a content-type is not localized. 
Prevent those fields from appearing in the GraphQL schema or REST API response
- Create a CT with and without i18n enabled. 
- Check the graphql queries
fix #21401

Make locale/localizations private for non-localized cts

---

packages/providers/email-sendgrid/package.json
yarn.lock

upgrade sendgrid-mail to 8.1.3 so that subdependency on axios is upgraded
the only breaking changes reported in their https://github.com/sendgrid/sendgrid-nodejs/blob/main/CHANGELOG.md was dropping support for old versions of node
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857
- try sending mail with sendgrid
DX-1701

chore: upgrade sendgrid-mail to 8.1.3

---

examples/getstarted/src/api/category/content-types/category/schema.json
packages/core/content-releases/admin/src/components/EntryValidationPopover.tsx
packages/core/content-releases/admin/src/components/tests/EntryValidationPopover.test.tsx
packages/core/content-releases/admin/src/services/release.ts
packages/core/content-releases/server/src/middlewares/documents.ts
packages/core/content-releases/server/src/services/release-action.ts
packages/core/content-releases/server/src/utils/index.ts
packages/core/content-releases/shared/contracts/release-actions.ts
packages/core/content-type-builder/admin/src/components/FormModal/FormModal.tsx
packages/core/content-type-builder/admin/src/components/FormModal/contentType/createContentTypeSchema.ts
packages/core/content-type-builder/server/src/controllers/validation/model-schema.ts
packages/core/review-workflows/server/src/services/workflows.ts
tests/api/core/review-workflows/review-workflows-content-types.test.api.ts
tests/api/core/review-workflows/review-workflows-stage-permissions.test.api.ts
tests/api/core/review-workflows/review-workflows-webhooks.test.api.ts
tests/api/core/review-workflows/review-workflows.test.api.ts

Releases' status depends on the validation status of attached entries. Now these status could change based on changes on Review Workflows (if one content type is added to a Review Workflow for example)
Tests that all the following actions cause the required changes on releases's status:
- Changing the review stage of one entry inside a release.
- Creating a new Workflow with one content type that has entries inside a release.
- Update a Workflow with content types that has entries inside a release.
- Remove a workflow with content types that has entries inside a release.

feat(content-releases): considered review stage when getting the action status

---

packages/core/database/src/query/helpers/where.ts

we were using the config client name before, which could be postgres / pg / pg-native depending on the pg driver that was instaled. This now uses the dialect name, which should be postgresql for any of the knexjs supported pg drivers.

fix: search by numeric numbers in a relation

---

packages/core/content-releases/admin/src/components/EntryValidationPopover.tsx

If status of entry is published and the action is not publish (means that actions is unpublish) we want to show the right message: "Ready to publish", this PR handle that case.
1. Create an entry and publish it
2. Assign it to a Release for unpublish
3. The message should say "Ready to unpublish", before was showing "Ready to publish"

fix: validation message errors

---

packages/utils/typescript/lib/generators/common/imports.js
packages/utils/typescript/lib/generators/common/models/schema.js
packages/utils/typescript/lib/generators/common/models/utils.js
packages/utils/typescript/lib/generators/components/index.js
packages/utils/typescript/lib/generators/content-types/index.js

Introduces consistent sorting for generated imported definitions, schema attributes, content-types, and components.
By ensuring a consistent order, it streamlines the generation process and prevents annoying git issues.
See https://github.com/strapi/strapi/issues/21208
To test these changes:
1. Go to a Strapi v5 application
1. Generate TypeScript definitions using `yarn strapi ts:generate-types`
2. Verify that the imports, schema attributes, content-types, and components are consistently sorted in the generated output, even after multiple generations
fixes https://github.com/strapi/strapi/issues/21208

Sort Generated Content-Types and Components Definitions

---

packages/core/review-workflows/server/src/services/metrics/index.ts
packages/core/review-workflows/server/src/services/workflows.ts

We need the workflowId and is stage required to publish has been enabled so we can use this data to get a total of workflows with required stage to publish set.

feat: add workflowId & hasRequiredStageToPublish to workflows metrics

---

packages/core/types/src/schema/attribute/base.ts

Types the `Attribute.column` for Strapi v5
Missing `column` type when create schema attributes
#21577 #21580
cc @Convly

fix(strapi/types): add Attribute column type

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-manager/admin/src/preview/components/PreviewSidePanel.tsx

Adds a tracking event when the user is about to leave the admin to view their preview in a new tab
- open the network devtools, you should see a tracking API call when clicking on "open preview"
- the preview should still open in a new tab

chore: add preview tracking

---

.github/filters.yaml
docs/yarn.lock
templates/website/yarn.lock
yarn.lock

upgrades locked versions of:
- cookie to 0.7.1
- express from 4.21.0 to 4.21.1
CVE-2024-47764
cookie is only a subdependency but it's used by:
- @apollo/server (via express)
- @docusaurus/core
but we're already on the latest version of those packages and they use a version range that includes the updated cookie, so we just need the yarn.lock bump
- @apollo/server (via express) -- check graphql
- @docusaurus/core -- check contributor docs
msw still has a dependency on cookie that might need to be upgraded, PR for that can be found in https://github.com/strapi/strapi/pull/21617
DX-1709

chore: upgrade cookie to 0.7.1

---

packages/utils/typescript/lib/generators/common/imports.js
packages/utils/typescript/lib/generators/common/models/schema.js
packages/utils/typescript/lib/generators/common/models/utils.js
packages/utils/typescript/lib/generators/components/index.js
packages/utils/typescript/lib/generators/content-types/index.js

> @Convly
> Introduces consistent sorting for generated imported definitions, schema attributes, content-types, and components.
> By ensuring a consistent order, it streamlines the generation process and prevents annoying git issues.
(cherry picked from merge commit c23fb8e on development branch, coming from pull request #21868)
See #21208
To test these changes:
1. Go to a Strapi v4 application
2. Generate TypeScript definitions using `yarn strapi ts:generate-types`
3. Verify that the imports, schema attributes, content-types, and components are consistently sorted in the generated output, even after multiple generations
fixes #21208
@Convly suggested somebody made this pull request for V4 in #21208

enhancement: Sort Generated Content-Types and Components Definitions (#21868)

---

packages/core/data-transfer/src/strapi/providers/remote-destination/index.ts
packages/core/data-transfer/src/strapi/remote/handlers/push.ts
packages/core/data-transfer/types/remote/protocol/client/transfer/push.d.ts

- Adds counters to the remote transfers, so we know how much data is sent, received and successfully added
- does a comparison and throws and error incase of a mismatch
- Throw and error and rollback to prevent data loss during transfers
- Transfers should work just fine

feat: DTS assert count of items sent and received is equal

---

packages/core/content-manager/admin/src/services/relations.ts

Fix loading more than 2 pages of relations in the content manager. 
Relations are assigned a __temp_key__ value based on their order (a0, a1, ..., z1, z2) . Each time a page was loaded the new temp keys were based from the first temp key of the list (a0), but that same value was used to compute the temp keys for the 3rd , ... pages. So the order was messed up.
Load more than 10 relations in a relational field.
Fixes https://github.com/strapi/strapi/issues/21808

fix: order when loading more than 10 relations 

---

packages/core/admin/admin/src/features/Auth.tsx

Fixes an issue where the app's local cache wasn't cleared when you logged out.
Prevent one user's data from leaking to the next user to log in via the same browser
Have 2 users users:
- one is a super admin with full permissions
- one is an "author" without permissions to read a specific field
You should be able to do this in the same tab without refreshing:
- login as the author user
- open the edit/create view where you removed the permissions for a field. You shouldn't see that field.
- logout
- login as super admin
- go to the same edit/create view. You should see the field
fixes #20344

fix: api state not cleared on logout

---

tests/e2e/tests/content-manager/blocks.spec.ts

Restores blocks editor e2e that was disabled during v5 development

chore: re-enable blocks e2e test

---

packages/core/content-releases/server/src/bootstrap.ts
packages/core/content-releases/server/src/utils/index.ts
tests/e2e/tests/content-releases/release-details-page.spec.ts

- Updates the dataset to remove duplicate release actions
- Returns the draft entry for a release action targeting a document that hasn't been published yet
- Handles a null case throwing errors when trying to delete many release actions in bootstrap
- To test the feature

fix(e2e): enable tests for release-details-page.spec.ts

---

tests/e2e/tests/content-manager/listview.spec.ts

Enables the bulk action tests in listview.spec.ts
To test the feature
The tests should pass here in the CI

fix(e2e): enable e2e bulk action tests in listview.spec.ts

---

packages/core/utils/src/__tests__/query-populate.test.ts
packages/core/utils/src/sanitize/sanitizers.ts
packages/core/utils/src/traverse-entity.ts
packages/core/utils/src/traverse/factory.ts
packages/core/utils/src/traverse/query-filters.ts
packages/core/utils/src/traverse/query-populate.ts
packages/core/utils/src/traverse/query-sort.ts
packages/core/utils/src/validate/validators.ts
tests/api/core/strapi/api/populate/filtering/index.test.api.js

As seen in https://github.com/strapi/strapi/issues/21338 , attribute names called `filters` broke the populate validation.
That's cause it was confusing a "filter" inside a populate with the filters attribute name:
```ts
{
populate: {
foo: {
filters: { bar: { $eq: 1 } }  // Should filter entries where bar is 1
}
}
}
{
populate: {
foo: {
populate: {
filters: true  //  Should populate the "filters" attribute
}
}
}
}
```
The `traverseQueryPopulate` was assuming `filters` was an attribute, as it was an actual attribute of the schema. Hence the first query was always invalid.
This PR solves this by modifying the `traverseQueryPopulate` and tracking each traversed node parent.

feat: fix filters attribute name

---

packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
tests/e2e/tests/content-manager/editview.spec.ts

Displays the single type schema name instead of "Untitled" if there is no relevant mainField.
When a contributor is editing a document, it's not clear which document they are working on if the `mainField` is irrelevant.
Create a single type document and switch to the content manager.
Fix #20844

fix: single type name not applied in the content manager

---

examples/getstarted/config/middlewares.js
packages/core/content-manager/admin/src/preview/components/PreviewContent.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx

Renders the preview url content inside an iframe.
> [!WARNING]  
> To render external URLs users will need to set that url into the CSP directives
```ts
// config/middlewares.js
module.exports = [
// ...
{
name: 'strapi::security',
config: {
contentSecurityPolicy: {
useDefaults: true,
directives: {
'frame-src': ["'self'", 'https://docs.strapi.io'], // e.g render strapi.io docs
},
},
},
},
// ...
];
```

feat: preview content in an iframe

---

packages/core/admin/ee/server/src/bootstrap.ts
packages/core/admin/ee/server/src/services/__tests__/persisted-tables.test.ts
packages/core/admin/ee/server/src/services/index.ts
packages/core/admin/ee/server/src/services/persist-tables.ts
packages/core/review-workflows/server/src/register.ts

Review workflows adds two additional attributes to content types, strapi_assignee and strapi_stage . Those are the values displayed in the content manager edit view.
As RW is an EE feature, it was decided for those attributes to not exist on the Comunity Edition. But at the same time if a user filled those values in EE and they downgrade, we want to keep the data there.
In v4 we were using a persist_table logic, to persist those join tables even if the attribute didn't exist. At some point we discussed doing otherwise, but eventually this was forgotten.
This PR reintroduces the persisted table logic we had in in v4.

fix: review workflow persist data

---

packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx

Fix preview close button redirecting to the edit view regardless of having switched to Draft & publish.
Open preview, switch to publish & draft multiple times and close preview.

fix: preview close button

---

packages/cli/cloud/src/cloud/command.ts
packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/deploy-project/command.ts
packages/cli/cloud/src/environment/command.ts
packages/cli/cloud/src/environment/list/command.ts
packages/cli/cloud/src/services/cli-api.ts

This PR introduces a feature to allow the cloud CLI deploy command to deploy to a specific cloud project environment by using a prompt selection or a flag.
- When the user runs `strapi deploy`, they would be asked to select an environment to deploy
- When the user runs `strapi deploy -e <environment> `, the deployment will be done in the specified environment
With the introductions of Strapi Cloud multi environments, a feature to allow users to deploy to a specific environment from the CLI is needed.
Pre-test: new options should be displayed on running `strapi deploy -h`:
`  -e, --environment <name>  Specify the environment to deploy`
Test Case 1: NO prompt for Environment Selection
Steps: Run strapi deploy with only 1 environment in a cloud project.
Expected: deploy should proceed as …

Feat(cloud-cli): deploy command allows environment to be passed

---

packages/core/content-manager/admin/src/components/RelativeTime.tsx
packages/core/content-manager/admin/src/components/tests/RelativeTime.test.tsx

It fixes the 'NaN' issue when you open the see more of a content you edited less than 1 second ago.
To fix issue [20756](https://github.com/strapi/strapi/issues/20756) : Last draft NaN value for a content
1. Go To CM
2. Click on any collection type.
3. Edit the a field and Save it.
4. try to see the Updated in the top right ellipses menu. (Note: Please try to see within 1 sec of the content edited and saved) 
fixes [20756](https://github.com/strapi/strapi/issues/20756)

fix: added fix for the last draft displaying NaN

---

packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts

Removes concurrency from the discardDrafts migration
Unfortunately that means it will run slower, but we can work on safer performance improvements later and unblock those who are stuck upgrading to Strapi 5.
When discardDrafts is run in parallel, there is something akin to a race condition where it tries to create relations to (or from?) an entity that is being changed at the same time. When run one at a time, the problem cannot occur.
Solves https://github.com/strapi/strapi/issues/21607
Experimental: 0.0.0-experimental.a13c58eec89ab119f0e381fb79c0252979e9c125
In Strapi v4, with postgres:
- Create a `destination` schema like so:
```
{
"kind": "collectionType",
"collectionName": "destinations",
"info": {
"singularName": "destination",
"pluralName": "destinations",
"displayName": …
```

fix: run discardDrafts without concurrency

---

.github/workflows/skipped_tests.yml
playwright.base.config.js

- increase overall test timeout
- decrease action and expect timeouts
- adds missing outputs to skipped_tests.yml (update: nope, this won't change anything, but for now I'll leave it to keep it in sync with test.yml)
- to reduce incidence of flaky tests while also allowing them to fail faster
- I'm hoping that fixing the outputs also fixes handling of PRs that don't trigger any tests but don't have evidence yet; if this doesn't work then I'll follow up with something else
There are currently several tests that fail because they take too long. Efforts like [this](https://github.com/strapi/strapi/pull/22079) improve them, and we should continue to write shorter and more performant tests, but right now just having a couple of servers restarts is enough to make a test flaky because the CI is …

test(e2e): change playwright timeouts

---

packages/core/review-workflows/server/src/controllers/assignees.ts
packages/core/review-workflows/server/src/controllers/stages.ts
packages/core/review-workflows/server/src/services/assignees.ts
packages/core/review-workflows/server/src/services/stages.ts
tests/api/core/review-workflows/review-workflows.test.api.ts

Changing the stage/assignee attribute made the document status go from publshed to modifed, confusing the users.
This PR ensures changhing those values will not change the publicaton status of the document, by keeping the same updated at value when making the update on the entry.
Go to the Content Manager
Go to a content type with a review workflow assigned (you will need a paid license)
Go to an entry with a published state
Change the stage of this entry
You will see the state not changed from Published to Modified
Fixes https://github.com/strapi/strapi/issues/21429

fix: stage change should not update modified status

---

packages/core/content-manager/admin/src/history/components/VersionsList.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentStatus.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx

Reuses the CM's DocumentStatus component in History and Preview. It wasn't possible before because it didn't have an XS size variant, but now it does thanks to the last RC and [this PR](https://github.com/strapi/design-system/pull/1801)
Love deleting code
Check the status in the history sidebar and in the preview header. Nothing should have changed.

chore: reuse DocumentStatus in history and preview

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts
tests/e2e/utils/setup.ts

Updates the code in the CTB e2e tests so that it can work regardless of test order.
Our tests often rely on retries (especially on webkit), and on retries, [the execution order is no longer respected](https://playwright.dev/docs/test-retries#failures), because Playwright will only resume at the specific test that failed, the previous ones won't re-run.
For context, the PR that introduced the logic that relies on retries is #21464. I understand why, as it makes tests a lot faster. But I believe our priority should be the flakiness right now, and the extended timeouts should allow us to have slow tests that don't fail. Then I think when the tests pass reliably we can discuss the different ways to speed them up. And a test that passes means a faster CI, because fewer retries are triggered …

 chore: make ctb tests no longer rely on test order

---

docs/docs/guides/e2e/02-data-transfer.md
tests/e2e/scripts/dts-export.ts
tests/e2e/scripts/dts-import.ts
tests/e2e/utils/dts-export.ts
tests/e2e/utils/dts-import.ts
tests/scripts/run-e2e-tests.js

- Migrates the export script to TypeScript
- Adds an import script 
- Updates the documentation so it is more clear how to properly update the data set.
- Removes two article entries in the database that were unnecessary
- When following the current documentation the export script doesn't work
- The documentation suggests using the dts import with `yarn strapi import` which won't work since it won't include admin users and content-types such as `releases`.
- Follow the documentation to import a data set
- Follow the documentation to export a data set

fix(e2e): update data import and export scripts

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-manager/admin/src/history/components/HistoryAction.tsx
packages/core/content-manager/admin/src/history/components/VersionHeader.tsx

We added the track for:
- the number of times users go to the Content History page: we’ll need to implement the willNavigate event for that
- the number of times users restore a history version: we’ll need to implement the didRestoreHistoryVersion event
To have some metrics regarding the use of the Content History feature
- add some entries to a Collection and try to modify them and save
- click on the "Content History" button in the Edit view 
- check the Network tab in the DevTool, a new POST track call will be triggered with the event "willNavigate"
- now in the History page try to select an old version and click on the Restore button (it needs to be enabled)
- in the Confirmation dialog click Restore
- check the Network tab in the DevTool, a new POST track call will be triggered with …

enhancement: add didRestoreHistoryVersion and willNavigate to history

---

packages/core/admin/package.json
packages/core/content-manager/package.json
packages/core/content-type-builder/package.json
packages/core/email/package.json
packages/core/review-workflows/package.json
packages/core/upload/package.json
packages/plugins/cloud/package.json
packages/plugins/color-picker/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/i18n/package.json
packages/plugins/sentry/package.json
packages/plugins/users-permissions/package.json
yarn.lock

removes references to prerelease versions of Strapi 5
Now that Strapi 5 has been released, they should not be used
0.0.0-experimental.b0db56479de441dfe8feb37a43c7f6f6fecf75c1
Possibly related to https://github.com/strapi/strapi/issues/21151

fix: remove references to prerelease versions of Strapi

---

packages/core/admin/admin/src/components/FormInputs/Enumeration.tsx

It adds again in the Enumeration field the "Choose here" as the empty option, to reflect the behavior we had in v4 
Because otherwise there is no possibility to set to empty an enumeration field when filled. In the case the field is required the "Choose here" option is not selectable like it was in v4
- Create an enum on Strapi v5 
-  set the field as not required
- then create a new instance of the enum field and try to select an option
- Save
- then edit the entry and choose the "Choose here" option to save the empty value and save
test the required field case
- go to a collection and add an enum field required
- then create a new instance of the Collection and try to save the enum empty
- then try to publish the entry (an error message needs to show up for the enumeration field)
- then …

fix: Enumeration add "Choose here" as empty value

---

examples/getstarted/config/admin.js
examples/getstarted/src/admin/app.jsx
examples/getstarted/src/admin/preview/dummy-preview.jsx
examples/getstarted/src/admin/preview/index.jsx

Creates a dummy Preview route in the getstarted example app, so we can easily test this feature.
On preview, you will see a page with the uid, documentId, locale and status information.
I didn't find a way to hide the main sidebar

chore: dummy preview page on getstarted

---

packages/core/core/src/services/document-service/repository.ts

Resets the `createdAt` field when duplicating entries instead of duplicating the existing value.
According to #21593, this is important to sort on the createdAt field for duplicated entries, and also to keep it consistent with v4.
1. Duplicate an entry
2. Compare the `createdAt` value, it shouldn't be the same as the original value
```js
{
"results": [
// current state
{
"id": 4,
"documentId": "e7c3l7w9o791ovxwovds8ugs",
"name": "A",
"createdAt": "2024-10-25T21:44:19.832Z",
"updatedAt": "2024-10-25T21:26:09.221Z",
"publishedAt": "2024-10-25T21:26:09.220Z",
},
{
"id": 5,
"documentId": "wxntm8myw7pbe58p338tifwx",
"name": "A",
"createdAt": "2024-10-25T21:44:19.832Z",
"updatedAt": "2024-10-25T21:26:09.221Z",
"publishedAt": "2024-10-25T21:26:09.220Z",
},
// with this change
{
"id": 6, …
```

fix: reset createdAt field when duplicating entry

---

packages/core/upload/admin/src/hooks/useCropImg.js

> [!NOTE]  
> Same fix as https://github.com/strapi/strapi/pull/22126 but for v4.
Images uploaded using AWS could not be cropped.
We use Cropperjs to crop images, the library exposes a Cross Origin config param to only allow images from the same source. It was enabled by default, this PR disables it so whe
Using an AWS provider:
1. Update `/config/plugins.js`
```ts
upload: {
config: {
provider: 'aws-s3',
providerOptions: {
credentials: {
accessKeyId: env('AWS_ACCESS_KEY_ID'),
secretAccessKey: env('AWS_ACCESS_SECRET'),
},
region: env('AWS_REGION'),
params: {
// ACL: 'private', 
// signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 15 * 60),
Bucket: env('AWS_BUCKET'),
},
},
actionOptions: {
upload: {},
uploadStream: {},
delete: {},
},
},
},
```
2. Update `config/middlewares.js`:
```ts
{
name: …
```

fix(v4): allow cross origin sources when cropping images

---

packages/plugins/documentation/package.json
yarn.lock

upgrade to a release version of `cheerio`
best to not have an `rc` dep in our packages
documentation plugin should work

chore: upgrade cheerio to release version

---

packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/deploy-project/command.ts
packages/cli/cloud/src/environment/link/action.ts
packages/cli/cloud/src/environment/link/command.ts
packages/cli/cloud/src/environment/link/index.ts
packages/cli/cloud/src/environment/list/action.ts
packages/cli/cloud/src/index.ts
packages/cli/cloud/src/link/action.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/services/strapi-info-save.ts
packages/cli/cloud/src/utils/get-local-config.ts

This PR adds a command for Cloud CLI users to link their local project to a specific cloud environment.
With strapi environment link, users can select an environment from their available options to set as the default for deploying their local project.
If a user runs strapi deploy without a linked environment or an `-e / --env` flag, they will be prompted to choose an environment.
Once an environment is linked, the strapi deploy command will use it automatically, without further prompts.
**Additional changes**
- Duplicated configuration retrieval functions have been consolidated in a utils file.
- Type names have been updated for consistency.
With the introduction of Strapi Cloud multi-environments, users need a way to deploy to specific environments via the CLI. This command completes the …

feat(cloud-cli): add command to link project with environment

---

packages/core/admin/admin/src/pages/Settings/components/Tokens/TokenBox.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/components/ConditionsButton.tsx

It prevents some forms from being submitted when a button is clicked, such as the Copy token button on the API Token page or the Settings button on the Roles form.
The `Button` and `IconButton` components from the `@strapi/design-system` package don't specify a type for the buttons, so by default, they have `type="submit"`, which submits the form on click.
This PR covers two scenarios, there might be others with the same issue.
- API Token
1. Create an API Token
2. Click on the copy button
3. It should only copy the token and nothing else
- Roles form
1. Open the Roles form
2. Click to edit an existing role
3. Open the Settings tab
4. Expand any row and click on the Settings button
5. It should open a confirm modal and nothing else
| Case | Before | After |
| -- | -- | -- |
| API Token | …

fix: prevent submitting form on button clicks

---

.github/filters.yaml
.github/workflows/tests.yml
package.json

use `--run-in-band` to run test:front
front-end tests quite consistently fail without it, probably due to race conditions
it's essentially a requirement for running front end test, CI was already using it, this just makes it so it's also used locally
try running front-end unit tests locally and they should pass
without this PR it's very likely that some of them fail

test(front): run front-end tests with runInBand

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Initializer.tsx

I have fixed a component cosmetic issue where inside the Content History page it was showing as not disabled.
Eventually I chose to pass props at the level of the component and remove the styled component all together.
The <Flex> component supports passing down the current color prop. Also the <PlusCircle> icon supports pasing down props such as width and height.
The disabled components don’t look like they are disabled. It makes it hard to understand that the fields in Content History are not editable.
Steps to reproduce:
- Go to an entry with a component
- Click on the 3 dots
- Click on Content History (you will need a paid license)
- The Components should appear as disabled (grey text instead of blue).
https://github.com/strapi/strapi/issues/20796

fix: the disabled components don’t look like they are disabled inside content history

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/create-single-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

use existing content types instead of creating 2 additional types on every test (reducing server restarts by 8 🙈 )
test is flaky because it restarts too many times and is exceptionally slow
it should pass

test(e2e): improve efficiency of collection-type test

---

packages/cli/cloud/package.json
packages/cli/cloud/src/deploy-project/action.ts
packages/cli/cloud/src/deploy-project/command.ts
packages/cli/cloud/src/environment/link/action.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/types.ts
yarn.lock

We add a warning message to be displayed when the deploy command is used and the target environment has already a deployment done or is in progress.
At the same time, a `-f / --force` flag to skip the warning and confirmation prompt has been introduced.
Deploying a local project with a different db state will incur in data loss. We need to warn users that deploying is a also a destructive operation. 
----
**Pretest** 
**Verify Deployment Commands**
- Steps: Run the `strapi deploy -h` command.
Confirm the help output includes the following commands and options:
```
Deploy a Strapi Cloud project
Options:
-d, --debug       Enable debugging mode with verbose logs
-s, --silent      Don't log anything
-f, --force       Skip confirmation to deploy
-e, --env <name>  Specify the environment to …
```

feat(cloud-cli): display warning when using deploy command

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

I replaced the translation `id` for the "Save" button of the edit view.
The save button is never translated in any language because the `id` is not the right one.
1. Go to the profile settings
2. Change the language to anything else than english
3. Go to any entry
4. Check the "Save" button
fixes https://github.com/strapi/strapi/issues/22192

fix: replaced translation id for the save button of the edit view

---

packages/core/review-workflows/admin/src/routes/settings/index.tsx

I had to pass a prop to display the cursor as pointer to Create new workflow button inside Settings/Review Workflows.
It is just cosmetics fix.
The cursor had to show as pointer on mouse over.
- Go to Settings
- Go to Review Worfklows (you will need a paid license)
- Hover over Create new workflow below the list of workflows
- The cursor should now be a hand like pointer.
https://github.com/strapi/strapi/issues/20792

fix: added the prop for pointer cursor

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

for both single-type and collection-type:
- use an existing content type to add attributes to instead of creating one
- add tests for toggles in both directions
- add fix / workaround with comment for bug where after server restart the UI still uses the old schema settings for the modal data
no longer tests creating a content type with spaces in the 'edit' tests, but they are still created in the 'create' tests, so no coverage is actually lost
flaky and/or broken tests

test(e2e): fix flaky ctb tests

---

tests/e2e/tests/search/content-type.spec.ts

adds an e2e test suite for the content-type search box
it was missing
specifically, to provide a (skipped) tests for the eventual resolution of https://github.com/strapi/strapi/issues/21791
it should pass
https://github.com/strapi/strapi/issues/21791

test(e2e): add content search test suite

---

examples/getstarted/config/admin.js
packages/core/content-manager/server/src/preview/index.ts
packages/core/content-manager/server/src/preview/services/preview-config.ts
packages/core/content-manager/server/src/register.ts

Introduces a new `allowedOrigins` preview config, so all the necessary configuration for Preview is in the same place.
Until now, it was required to set up the preview URL in the `config/middlewares.js` security middleware. It was tedious and just another step that made preview config more complicated. 
Now you can do the same by configuring it in `config/admin.js`:
```ts
preview: {
enabled: env.bool('PREVIEW_ENABLED', true),
config: {
allowedOrigins: ['docs.strapi.io'],
handler: (uid, { documentId, locale, status }) => {
if (status === 'published') {
return 'https://docs.strapi.io/';
}
return 'https://docs.strapi.io/dev-docs/intro';
},
},
},
``` 
There is no need to update the `config/middlewares.js` file anymore.

feat: preview allowed origins config

---

tests/e2e/tests/content-manager/history.spec.ts
tests/e2e/utils/shared.ts

- Removes condition in order to `waitForLoadState` on every browser
- Uses clickAndWait when navigating from page to page
- The test is flaky often failing to find the first locator after page navigation
- It fails for webkit and firefox 
The CI should pass

fix(e2e): use clickAndWait to ensure the page is ready

---

packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts

This PR fixes the migration that adds `document_id` column to existing content type tables. 
The original issue was reported here and mistakenly closed as a duplicate:
Fix #21899 
A follow-up PR (#22049) was also closed unmerged in favour of #21596, but as @innerdvations mentioned, #21596 doesn't fully resolve the issue with content types named "Document".
This takes care of a potential naming conflict that happens when you have a content type with a singular name "document", which seems to be a common naming pattern for Strapi installations in the wild.
- Start with the latest v4 and prepare it for the v5 migration
- Start the server, all the migrations should pass
- Do this on postgres, sqlite and mysql
_Important: I only have managed to test the postgres migration, and people in the …

fix: resolve naming conflict in the v5 `document_id` migration

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/Blocks/Code.tsx

Replaced the Code icon with CodeBlock icon inside the block editor.
Users were confusing them. One is a code block modifier and the other is simply a inline block modifier.
Create a collection with a block editor field. Click the dropdown and see at the bottom where it says Code Block.
The icon should be now different than the inline code on the Toolbar.
https://github.com/strapi/strapi/issues/22058

fix: replaced the Code icon with CodeBlock icon

---

packages/core/content-manager/admin/src/history/components/VersionHeader.tsx
packages/core/content-manager/admin/src/translations/en.json

It updates the message for the notification box after an user restores a document version.
The message was reported as incorrect.
- Edit an entry of a content-type without D&P enabled
- Go to the content history of this entry (you will need a paid license)
- Restore a past version of the entry
- See the notification saying that the version was restored on top of a published one
https://github.com/strapi/strapi/issues/21175

fix: the confirmation message of restoring a version was updated

---

packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx

Handle long title names for static preview:
Before , the title was being wrapped and made the header higher.
- Create an entry with a long title
- Open Preview and see the title being cropped to fit maximum 200px
Fixes https://github.com/strapi/strapi/issues/22158

fix: preview title overflow

---

packages/core/admin/admin/src/utils/getFetchClient.ts
packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx
packages/core/content-manager/admin/src/services/documents.ts
packages/core/content-manager/admin/src/utils/api.ts
packages/core/content-manager/admin/src/utils/tests/api.test.ts
packages/core/review-workflows/admin/src/utils/api.ts

Searching in the List View with special characters ( * & / ...) was not working.
Characters were being encoded twice.
The solution proposes removing all encodings we had for `_q` (or any other param) , and handling the encoding inside the injected content manager endpoints.
Ideally, this should be done by the api interceptor, but doing so would be a breaking change at the moment.
- Create some entries in a content-type named like `A & B` and `C & D`
- Try to search specifically for `A & B`
- The `A & B` entry should appear in the list
Fixes https://github.com/strapi/strapi/issues/21791

fix: search param being encoded twice

---

packages/utils/typescript/lib/__tests__/generators/schemas/attributes.test.js
packages/utils/typescript/lib/__tests__/generators/schemas/utils.test.js

Take into account the fact that properties are sorted within objects when generating typescript types. Fixes the unit tests.
https://github.com/strapi/strapi/pull/21868 introduced sorting for generated types and their attributes, but didn't update the related unit tests.
For some reason, Github CI didn't seem to have an issue with that, but locally tests were failing.
1. Checkout onto the branch
2. Run the unit tests, everything should work
take over #22147

fix: unit tests for typescript types gen

---

examples/getstarted/config/admin.js
examples/getstarted/src/admin/preview/dummy-preview.jsx
examples/getstarted/src/admin/preview/index.jsx

Adds a JSON input with the raw document data to the internal dummy preview page
it's more like a real preview that actually queries the content. It was handy for me in another PR where I want to make sure content updates are saved by the time I open the preview

chore: add json data to dummy preview

---

packages/core/upload/admin/src/components/MediaLibraryInput/MediaLibraryInput.tsx

I changed the type of the attribute prop in the MediaLibraryInput to be optional instead of required.
Some strapi plugins had issues with the new type definition of the component, in particular reactions and navigations
- Create a new Strapi project using the experimental `npx create-strapi-app@0.0.0-experimental.fb22a8bd8745528903b2f168fdd286dfd1f5082e --quickstart`
- then install the `reactions` plugin following the instructions at this page https://market.strapi.io/plugins/strapi-plugin-reactions
- open the settings page and click the Reactions link
- create a new Reactions
- you should be able to see the modal and create the reaction
fixes https://github.com/strapi/strapi/issues/22258

fix: change MediaLibraryInput attribute type from required to optional

---

tests/e2e/tests/i18n/settings.spec.ts
tests/e2e/utils/dts-import.ts

- Turns on i18n settings.spec.ts tests
- Handles test differences between EE and CE
- To fix the tests
Tests should pass here in the CI and locally
Required an update in the DS https://github.com/strapi/design-system/pull/1829 to disable menu triggers

fix: turn on and update i18n settings.spec.ts

---

.github/workflows/tests.yml

allows docs_build to run by making it dependant on build and installing its deps
docs_build isn't actually able to run because it fails to install dependencies and build the monorepo
it should run and pass here

ci: fix docs_build

---

packages/core/content-manager/admin/src/content-manager.ts
packages/core/content-manager/admin/src/history/components/HistoryAction.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/Header.tsx
packages/core/content-manager/admin/src/pages/EditView/components/Panels.tsx
packages/core/content-manager/admin/src/pages/ListView/components/TableActions.tsx

Prevents document actions from being rendered multiple times, by introducing a static optional "position" property on the component function, and using it to pre-filter the actions to render when possible.
The issue is that the document action "components" do several things. They return static information, like their label, position, or icon. But they also do logic in the same component, to check if they should be enabled for example, or to define on onClick behavior. And that logic relies on hooks, like accessing context.
We keep a single document actions store, but they're split in 3 places: edit view side panel, edit view header, and list view table row. To get the right subset of actions in each location, we filter by the returned 
So here's the problem: on the edit view, we call …

fix: document actions being rendered multiple times

---

packages/plugins/users-permissions/server/graphql/types/me.js

Since I need the documentId to do other graphql queries to the user, I really want to get it from the `me`.
Add `documentId` to the `me` schema.
To allow to fetch the `documentId` in graphql queries

add documentId to `me` graphql query

---

packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/preview/components/PreviewSidePanel.tsx
tests/e2e/tests/content-manager/preview.spec.ts

Adds 3 fixes related the the preview page header title, reported in the blitz:
- adds a tooltip, so we have a way to see the full title when it's cropped because it's too long. I rely on the native HTML title to trigger the browser's default tooltip. I checked with @lucasboilly and he approved it, our DS tooltip isn't great at handling long content over multiple lines. It's also much simpler to implement.
- makes sure the title is the same as the one from the edit view by copying the logic from there
- properly disables the link. TIL the disabled tag does nothing for anchors! so I combined [this workaround](https://stackoverflow.com/questions/13955667/disabled-href-tag#comment119178426_27057625) with [this one](https://stackoverflow.com/a/46665946/3661792) for the not allowed cursor
- …

fix(preview): page title and disabled link

---

tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

adds tests for update and delete collection type and single type
Note: there is a bug that the CTB does not update the schemas until after a page refresh, which has been noted in a TODO
tests didn't exist
they should pass
DX-1468
DX-1650

test(e2e): add update and delete content type tests

---

examples/getstarted/src/middlewares/test-middleware.js

comments out the middleware log in getstarted
in a normal project it would only log once, but in the monorepo it runs ptentially hundreds of times on each request because of all the live admin building done by vite

chore: comment out getstarted log

---

packages/core/utils/src/__tests__/convert-query-params.test.ts
packages/core/utils/src/convert-query-params.ts

When querying a CT with a compo, trying to select a field from the compo errored out.
Issue was in convertQueryParams utility, it always injected a `documentId` field inside the `fields`attribute, regardless if the populated model was a content type or a component.
To fix the following scenario
e.g. query:
```ts
const result = await strapi.documents('plugin::myplugin.test').findMany({
populate: {
compo: {
fields: ['name']
},
}
})
```
e.g error
This will hopefully unblock https://github.com/strapi/strapi/pull/22273

fix: do not select document ids on components

---

packages/core/admin/admin/src/features/BackButton.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx

Updates the preview back button so it uses navigate(-1) from React Router, simulating a click on the browser's back button. It's needed because otherwise, if you go to preview, click back, and click and the edit view's back button, you're take to the preview page again.
I also fixed an issue in the shared BackButton component where the href of the link was the wrong one, it would show the URL of the current page instead of the previous one.
I think it's better to let you try it and see if it does what you expect. Just avoid starting a session (or reloading) directly on the preview page, because that will rely on the fallback URL, in which case the back/previous logic cannot be managed.
FYI I noticed a bug where if you toggle the draft and publish tabs multiple times on the preview page, …

fix: preview back button behavior

---

packages/core/admin/admin/src/pages/Home/HomePage.tsx
packages/core/admin/admin/src/pages/Home/components/GuidedTour.tsx
tests/e2e/tests/admin/home.spec.ts

Create pages/comonents/GuidedTour.tsx which now handles the logic to return the existing GuidedTourHomepage component.
- For the homepage feature
- Go to the new homepage
- You should see the gudied tour
- Skip the tour, you should now longer see it (reset local storage to get it back)
- Otherwise the GuidedTour should behave as usual

chore(homepage): move guided tour

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/ListPage.tsx
packages/core/admin/admin/src/pages/Settings/pages/Roles/components/RoleRow.tsx
packages/plugins/users-permissions/admin/src/components/Permissions/PermissionRow/SubCategory.jsx
packages/plugins/users-permissions/admin/src/pages/EmailTemplates/components/EmailTable.jsx
packages/plugins/users-permissions/admin/src/pages/Roles/pages/ListPage/components/TableBody.jsx

Fixes Inconsistent cursor state for clickable elements
To fix issue [20768](https://github.com/strapi/strapi/issues/20768) : Inconsistent cursor state for clickable elements
1. Go to main menu setting.
2. Then click on Users & Permissions plugin > Roles
3. Click on any role.
4. Now if we open one of any accordion in the list and hover over the icon beside checkbox.
5. You will be able get the cursor pointer on hover. 
fixes [20768](https://github.com/strapi/strapi/issues/20768)

Fix: Cursor pointer issue in permission checkbox settings icon

---

.github/filters.yaml

Makes sure the backend tests run in the CI when JSON files change in the server part of a package
i18n locales config can break snapshots with JSON data. We need the CI to run to catch that.
For example this PR: https://github.com/strapi/strapi/pull/21881
That required this change: https://github.com/strapi/strapi/pull/22347

ci: run backend tests on server json file changes

---

packages/plugins/graphql/server/src/bootstrap.ts

- skips the authenticate request for the graphql playground
- So we are able to load graphql playground without users-permissions
- remove users-permissions and try to access graphql playground the UI should work
- `GET` queries on graphql should be authenticated
#21977 
fixes #21915

fix: accessing graphql playground without users-permissions plugin

---

packages/core/admin/ee/server/src/controllers/index.ts
packages/core/admin/server/src/controllers/homepage.ts
packages/core/admin/server/src/controllers/index.ts
packages/core/admin/server/src/routes/homepage.ts
packages/core/admin/server/src/routes/index.ts
packages/core/admin/server/src/services/homepage.ts
packages/core/admin/server/src/services/index.ts
packages/core/admin/server/src/utils/index.d.ts
packages/core/admin/shared/contracts/homepage.ts
tests/api/core/admin/admin-homepage.test.api.ts

Adds a `/admin/homepage/recent-documents` endpoint in the admin package.
I haven't extracted many utils or anything, because this PR blocks the frontend work, so ideally we'd merge it soon. I think we can look at the abstractions to create when we work on the recently published documents ticket.
For the "recently edited" widget on the new homepage
Make updates in Strapi. Then make a GET `/admin/homepage/recent-documents?action=update`, while being authenticated. You should see the most recent documents you have updated across all content types. Each should have a "title" field that is the main field (or the documentId if there's no main field)

enhancement(homepage): create recently edited documents endpoint

---

packages/core/admin/server/src/controllers/homepage.ts
packages/core/admin/server/src/services/homepage.ts
packages/core/admin/shared/contracts/homepage.ts
tests/api/core/admin/admin-homepage.test.api.ts

- Refactors the service to extract functions to be shared 
- Updates homepage service to get recent publishing activity
- To display publish activity
- Publish some stuff, update a published document to get a modified state, and make some updates to documents that don't have draft and publish
- Make an authenticated GET to `http://localhost:1337/admin/homepage/recent-documents?action=publish` 
- You should see only documents with draft and published, only the published data, and the correct status (published or modified)

enhancement(homepage): get recent publish activity

---

.github/actions/run-e2e-tests/action.yml
examples/getstarted/config/features.js
packages/core/content-manager/admin/src/preview/constants.ts
packages/core/content-manager/admin/src/preview/index.ts
packages/core/content-manager/server/src/preview/constants.ts
packages/core/content-manager/server/src/preview/index.ts
packages/core/types/src/modules/features.ts
tests/api/core/content-manager/preview/preview.test.api.ts
tests/e2e/app-template/config/features.js
tests/e2e/tests/content-manager/preview.spec.ts

Removes the future flag to make Static Preview available to everyone
So folks can use it! Docs should be live in time for next week's release

feat: add static preview (remove future flag)

---

packages/core/database/src/entity-manager/index.ts

Fix the components' reordering by passing the relation's type field (_`__type` for relations and `__component` for dynamic zones' components_) instead of hard-coding `__type`.
Additionally, start the value of the order property at `1` instead of `0` to maintain consistency with the rest of the code.
This was causing issues on entries' creation as components would not be ordered correctly (_`encodePolymorphicRelation` was returning `1::undefined`-like IDs since `__type` doesn't exist in component data_)
See reproduction steps in related issues and PRs.
fix #22170
fix #22228
fix #22250

fix: adjust polymorphic relation encoding and index mapping

---

packages/core/review-workflows/package.json

- we have a duplicated dependency `@strapi/utils` 
- allows nx releases to resolve the versioning issue in this package

chore: remove duplicate dependency

---

packages/core/admin/admin/src/pages/Home/HomePage.tsx
packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx
packages/core/content-manager/admin/src/translations/en.json
tests/e2e/tests/admin/home.spec.ts

- Add new `LastPublishedWidget`
- Refactor the `LastEditContent` component to support the `LastPublishedWidget`
To show recently published documents
- Go to the CM and publish some stuff
- Go to Home, you should see the new widget with the documents you just published
- Go edit one of those published documents
- You should now see the document in the widget with the modified status, but the data will still be the published data

enhancement(home): add recently published widget

---

yarn.lock

Dependabot bumped it for docs, for some reason was unable to create the PR for root
CVE-2024-55565
id generation of all kinds should still work, and that's all covered by the existing tests
https://github.com/strapi/strapi/pull/22389

security(deps): bump nanoid to 3.3.8 in yarn.lock

---

packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx

Replace documentId with title
It was a mistake
Hover over the titles in the widgets and you should see the title not the documentId

fix(home): replace title documentId with document title

---

packages/core/admin/server/src/services/homepage.ts
packages/core/admin/shared/contracts/homepage.ts
tests/api/core/admin/admin-homepage.test.api.ts

Ensures locale is defined or null when getting a status
Otherwise the status is incorrect
Edit some content in draft and published 
Verify the correct status show up on the homepage
NOTE: A content-type without d&p will still show draft. This is another bug....I think?

fix(home): make locale defined or null to get the correct status

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/AddComponentButton.tsx

- Simplifies `AddComponentButton` by using its styles inherited from `Button`
- Removes the unnecessary styles change on hover when disabled
- Changes the padding left to better fit the icon shape
The current version is not in sync with the design and makes users think that they can click on the button even if it's disabled. It will improve the UX of the disabled Dynamic Zones in the "Published" tab and in Content History.
https://github.com/user-attachments/assets/c9d987d1-e66d-492d-939e-28ba27cfd34f
https://github.com/user-attachments/assets/e19ad3c6-859a-47fb-a629-c35acc1e98c9
Open any entry with a Dynamic Zone and check its disabled version.

fix: add component button style

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/Blocks/Code.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/Blocks/Quote.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksContent.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksEditor.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksToolbar.tsx

- Removes the border of the `DragIconButton` in both default and disabled mode
- Changes the color and the size of the `Drag` icon because it wasn't visible enough
- Hides the `DragIconButton` when the input is disabled
- Changes the cursor to `not-allowed` for disabled modifiers
- Adds a shadow to `ExpandIconButton` to make it understandable that it is sticky
- Set the with of `ToolbarWrapper` to 100% and added a background color for its disabled state
- Thanks to the new width of `ToolbarWrapper` the input has a disabled style in expanded mode as well
- Removed `dragHandleTopMargin` for `Code` and the `Quote`
- Fixes padding issues
Blocks is currently not aligned with the designs and its disabled states are not understandable.
Open any entry that has a Blocks field. Don't forget to …

fix(blocks): various ui issues

---

packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx

Appends the i18n params when a recent document has a locale
The back button is broken for documents that have entries in several locales
Create a document in one locale, then create another version of the document in a different locale
Go to the homepage and click the edit link on the recent document
Once in the CM click the back button
You should go back to the homepage
fixes: https://github.com/strapi/strapi/issues/22427

fix(homepage): make back button work when document has a locale

---

packages/core/core/src/services/document-service/draft-and-publish.ts
packages/core/core/src/services/document-service/repository.ts
tests/api/core/strapi/document-service/validation/validation.test.api.ts

remove lookup param from document service
it's for internal use only

fix: remove lookup param from document service

---

tests/api/core/content-manager/api/basic-relations.test.api.js

Remove the skip to the api test and replace the id with documentId and the correct response object
The test was disabled during the implementation of v5
- from the root run the api test
`yarn test:api tests/api/core/content-manager/api/basic-relations.test.api.js`
CS-1193

fix: renable the basic relations test

---

packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx
packages/core/admin/admin/src/pages/Home/components/Widget.tsx

- Refactors the root component to handle every state
To match the designs
Check the designs
resolves https://github.com/strapi/strapi/issues/22426

fix(homepage): add missing styles for error, loading, and empty states

---

packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx
packages/core/admin/server/src/services/homepage.ts
tests/api/core/admin/admin-homepage.test.api.ts
tests/e2e/tests/admin/home.spec.ts

- [Backend] Return undefined locale if the CT doesn't have D&P
- [Backend] Update API tests 
- [Frontend] Hide the status for documents undefined locale
- [e2e] TODO: Looking into it in the related PR, but there is already a published product in the DB that isn't present in the CMS in the e2e test instance.
Only d&p documents should have a status
Make changes to documents with and without draft and publish
Check the statuses are correct for draft and published (draft, published, modified)
Check there is no status for no draft and published (empty grid cell)
https://github.com/strapi/strapi/pull/22407

fix: hide doc status when no d&p

---

packages/core/content-manager/server/src/services/document-metadata.ts

Entries were displayed as Draft even if they were published in the list view.
When populating the published version of a draft, we were always filtering by locale even for non i18n content types.
Fix https://github.com/strapi/strapi/issues/22470

fix: entries always showing up as "Draft"

---

packages/core/content-type-builder/admin/src/components/AutoReloadOverlayBlocker.tsx

- Makes the CTB loader round
- Harmonizes the icons sizes between the 2 states
It's currently not the case.
https://github.com/user-attachments/assets/451077b7-6ca9-4e5b-921d-adf55c20205b
https://github.com/user-attachments/assets/e6a0d05a-cf35-4612-a8e1-d4a57766cd35
Create or update any content type.
fixes https://github.com/strapi/strapi/issues/21349

fix: make ctb loader truly round

---

packages/core/content-type-builder/admin/src/components/Relation/RelationNaturePicker/Components.tsx

Fix missing pointer cursor when hover top of possible relations
To fix issue [21341](https://github.com/strapi/strapi/issues/21341) : Missing the pointer cursor when on top of a possible
1. Go to CTB
2. Create relation field and hover over the possible relations.
3. Now you will not be able to see the pointer cursor.
fixes [21341](https://github.com/strapi/strapi/issues/21341)

fix: missing pointer cursor when hover top of possible relations

---

packages/core/admin/admin/src/components/FormInputs/Number.tsx
tests/api/core/content-manager/fields/integer.test.api.js

Ensure that when a number field is cleared, its value is explicitly set to null instead of undefined to guarantee the update is processed correctly.
Fixes #22533 by explicitly setting the value to null when a number field is cleared. Previously, the value was set to undefined, which was interpreted as no change, preventing the number field from being cleared.
This fix is necessary to enable clearing a number field. Without it, passing undefined results in no change, leaving the field uncleared.
1. Navigate to the content-manager section.
2. Clear the value of a number input field.
3. Reload the page.
4. Verify that the value of the cleared field is null.
Related to #22533.

fix: handle clearing of number field to send null instead of undefined

---

docs/docs/docs/01-core/utils/traverse-entity.md

Adds documentation for the `traverseEntity` utility
So it is easier for everyone to understand and use the utility
Read it 
https://github.com/strapi/strapi/pull/22278
p.s.
ChatGPT did a good job IMO

chore(docs): document traverseEntity util

---

packages/core/admin/admin/src/components/MainNav/NavLink.tsx

- Changes the `background` of an active link to `primary100` instead of `neutral100`
- Removes the text-related properties (`color` and `font-weight`) since links are now only icons
The current version is not aligned with the designs.
You can check it on any page since it's the main navigation.

fix: changed active state background color

---

packages/core/admin/admin/src/pages/Home/components/Widget.tsx

Adds a `borderColor` property to the `Widget` component.
I missed it during the QA phase.
Go to the homepage.

fix: add missing borders to widgets

---

playwright.base.config.js
tests/e2e/tests/content-manager/create-content.spec.ts
tests/e2e/tests/content-manager/date.spec.ts
tests/e2e/utils/content-creation.ts
tests/e2e/utils/content-types.ts
tests/e2e/utils/shared.ts

Adds testing for text field "required" and "regexp" advanced settings, from creating it in the CTB to entering data for them in basic fields, components, and dzs.
More specifically:
- adds util for to ensure a checkbox value
- retain logs on failure locally (helps with debugging flaky tests)
- findAndClose allows to skip in case of expected error
- add test that error messages show up when a required text field in a dynamic zone is not entered
TODO:
gap in testing
run them
DX-1843

test(e2e): text fields advanced settings

---

.github/workflows/publish-release.yml
scripts/publish.sh

- setup the github actor to do the commits 
- ensures the github token is passed to the script
- make the workflow work

ci: passing github token to publishing script

---

packages/plugins/i18n/admin/src/index.ts
packages/plugins/i18n/admin/src/translations/de.json
packages/plugins/i18n/admin/src/translations/dk.json
packages/plugins/i18n/admin/src/translations/en.json
packages/plugins/i18n/admin/src/translations/es.json
packages/plugins/i18n/admin/src/translations/fr.json
packages/plugins/i18n/admin/src/translations/ko.json
packages/plugins/i18n/admin/src/translations/pl.json
packages/plugins/i18n/admin/src/translations/ru.json
packages/plugins/i18n/admin/src/translations/tr.json
packages/plugins/i18n/admin/src/translations/zh-Hans.json
packages/plugins/i18n/admin/src/translations/zh.json
tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts

This PR fixes an issue in i18n where it was not possible to define unique and non-localized fields for i18n content types. It modifies the handling of uniqueness constraints to allow these fields to function correctly in i18n models.
1. Create an i18n content type with at least one unique and non-localized field.
2. Add multiple records to the content type in different locales.
3. Verify that the unique constraints are respected across locales for the non-localized field.
4. Confirm that the application does not throw errors when managing such content types.
DX-1834

fix(i18n): allow unique + un localized fields on i18n content types

---

packages/utils/upgrade/package.json
yarn.lock

- upgrade jscodeshift to eliminate sub-dependency of unmaintained `rimraf` v2
rimraf v2 is unmaintained and we are trying to eliminate it
upgrade tool should still work as before (it's the only thing using jscodeshift)
DX-1850

chore: upgrade jscodeshift to v17

---

packages/core/admin/ee/server/src/utils/persisted-tables.ts
packages/core/database/src/dialects/dialect.ts
packages/core/database/src/index.ts
packages/core/database/src/repairs/__tests__/remove-orphan-morph-types.test.ts
packages/core/database/src/repairs/__tests__/repair.test.ts
packages/core/database/src/repairs/index.ts
packages/core/database/src/repairs/operations/remove-orphan-morph-types.ts
packages/core/database/src/schema/index.ts
packages/core/database/src/utils/async-curry.ts
packages/core/strapi/src/Strapi.ts
tests/api/core/strapi/components/cleanup-after-delete.test.api.js

- backports the [database repair manager](https://github.com/strapi/strapi/pull/22267)
- run it on startup when schema changes are detected
Fixes https://github.com/strapi/strapi/issues/20931
To test manually:
- create a component
- add it to a content type
- add some data for it
- delete the component
- the component data should no longer exist in the `_components` table for that content type
Fixes https://github.com/strapi/strapi/issues/20931 for v4
Seems to fix https://github.com/strapi/strapi/issues/19535 for me, but waiting on confirmation
Backported from v5 PR: https://github.com/strapi/strapi/pull/22267
DX-1731

fix: delete orphan component data when schema changes

---

packages/core/core/src/services/metrics/__tests__/middleware.test.ts
packages/core/core/src/services/metrics/__tests__/rate-limiter.test.ts
packages/core/core/src/services/metrics/middleware.ts
packages/core/core/src/services/metrics/rate-limiter.ts

Rate limited events now resets 24h after the last event (or process start), instead of each day at midnight.
It will smooth the sending of events, and avoid receiving a burst of events at midnight on the telemetry server.

chore(telemetry): smooth event rate limiting

---

packages/core/admin/admin/src/components/Form.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx
tests/e2e/tests/content-manager/editview.spec.ts

- Fixes #22399. I do the fix by not relying on setIn anymore, because it's designed to overwrite content at the index it's given. I use toSpliced instead (the FP version of splice) which just inserts at the the given position
- Adds new e2e test case to catch the issue
- Fixes the alignment of the "more" action button on components
To avoid accidental data loss
Create content in dynamic zones, add components to the top, to the bottom, in the middle, maybe delete and recreate some.
Also do sanity check changing review workflows stages, because it seems to use the same addFieldRow util.

fix: adding component to dynamic zone overwrites data

---

packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/assets.test.ts
packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/index.test.ts
packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
packages/core/data-transfer/src/strapi/providers/local-source/__tests__/index.test.ts
packages/core/data-transfer/src/strapi/providers/local-source/index.ts
packages/core/data-transfer/src/strapi/remote/handlers/utils.ts
packages/core/database/src/lifecycles/index.ts

- disable lifecycle hooks during a transfer
enable them back again after a transfer
- prevent lifecycle hooks from being triggered during transfer operations
- during a transfer or import or export lifecycle hooks should not be triggered
fixes #19383

fix: disable lifecycle hooks on transfers [v4]

---

packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/assets.test.ts
packages/core/data-transfer/src/strapi/providers/local-destination/__tests__/index.test.ts
packages/core/data-transfer/src/strapi/providers/local-destination/index.ts
packages/core/data-transfer/src/strapi/providers/local-source/__tests__/index.test.ts
packages/core/data-transfer/src/strapi/providers/local-source/index.ts
packages/core/data-transfer/src/strapi/remote/handlers/utils.ts
packages/core/database/src/lifecycles/index.ts

- disable lifecycle hooks during a transfer
enable them back again after a transfer
- prevent lifecycle hooks from being triggered during transfer operations
- during a transfer or import or export lifecycle hooks should not be triggered
fixes #19383

fix: disable lifecycle hooks on transfers [v5]

---

packages/core/strapi/src/node/vite/watch.ts

Followup on github.com/strapi/strapi/issues/21184
when setting vite `base` it will not serve them correctly if we are rewriting the pathname 

fix: virtual prefix proxy path for vite middleware to work

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations.tsx

EditView relation search did not have any debouncing, every written character triggered an API request.
This PR introduces such behaviour.
Note: If this is not enough, we could abort the rtk query by using the .abort() method, but it feels less responsive if using it, so lets try if this works.
See https://github.com/strapi/strapi/issues/22437 for reproduction
Continuously type in a relational field search and at some point your client will stop responding
Fixes https://github.com/strapi/strapi/issues/22437

fix: debounce relation search

---

.github/workflows/publish-release.yml
scripts/publish.sh
scripts/release.js

Use github app token for permissions in release workflow
Normal github token cannot bypass protected branches

ci: use release app token permissions for release workflow

---

packages/core/admin/admin/src/components/PageHelpers.tsx
packages/core/admin/admin/src/components/tests/PageHelpers.test.tsx
packages/core/admin/admin/src/translations/en.json
packages/core/admin/admin/src/translations/ja.json
packages/core/upload/admin/src/components/AssetDialog/tests/AssetDialog.test.tsx

I've added the missing `h` to whoops.
To correct the spelling.
N/A
N/A

Fix 'woops' spelling disagreement 

---

packages/core/admin/admin/src/components/PluginsInitializer.tsx
packages/core/admin/admin/src/core/apis/Plugin.ts

Make the Plugin class immerable 
https://immerjs.github.io/immer/complex-objects/
It fixes an infinite loading state
The bug is only reproducible in production. It can be reproduced on strapi cloud.
The work here is published on an experimental: `0.0.0-experimental.a4df7ad5ff6a4366442059f7c067a0424ba1e2f9`
Deploy a project to strapi cloud to reproduce the bug
Login, you should be stuck with infinite loading
Update your project with the experimental and redploy
Login, the homepage should load
fixes https://github.com/strapi/strapi/issues/21811
https://github.com/strapi/strapi/pull/22402

fix: class Plugin is not immerable

---

examples/getstarted/config/features.js
packages/core/content-manager/admin/src/preview/components/PreviewContent.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
packages/core/types/src/modules/features.ts
tests/e2e/app-template/config/features.js

- Setup future flag
- Split the screen so half the viewport is the space for the side editor and the other half the preview content
- Add the new header layout
Still a weird thing in the e2e tests where its using the future flag for the space for the side editor but not for the header 🤔 
The future flag should be set to true by default in examples/getstarted now
Go to a preview page
You should see the new layout:

chore(preview): prepare layout for side editor

---

tests/api/plugins/i18n/locales.test.api.js

- deletes test data before test run
- sometimes if a test is interrupted, or if a previous test creates similar data and fails to clean it up, this test fails
- if you run the entire api test suite concurrently (`--runinband`) locally, the tests should all pass
- without this PR, generally the locales test will fail unless it is run by itself or in a shard on the CI

test(api): cleanup test data

---

packages/plugins/i18n/admin/src/contentManagerHooks/editView.tsx

See https://github.com/strapi/strapi/pull/22242.
See https://github.com/strapi/strapi/pull/22242.
https://github.com/strapi/strapi/pull/22242

fix: remove icon for fields without i18n

---

packages/core/admin/admin/src/pages/Settings/pages/ApiTokens/EditView/components/ContentTypesSection.tsx
packages/core/admin/admin/src/pages/Settings/pages/ApiTokens/EditView/components/Permissions.tsx

- Removes unexpected padding around the accordions list
- Removed unused background property
- Added a gap between the subtitle and the accordions list
It currently doesn't look good.
Go to Settings, API Tokens and check or create a token.

fix: removed unexpected padding around accordions

---

packages/core/admin/admin/src/layouts/AuthenticatedLayout.tsx

Defers loading package.json until `@strapi/admin` is built in the end application, instead of when preparing for a release.
As explained in bug #22117 strapi always notifies the user that a new version is available. This is caused by the fact that the version of strapi is embedded in the `@strapi/admin` when the package is built prior to increasing the version.
Create a new release, go to the Strapi admin page. The notification should be gone.
#22117

fix(admin): display correct version on admin notification

---

tests/e2e/tests/content-manager/history.spec.ts
tests/e2e/tests/content-type-builder/collection-type/edit-collection-type.spec.ts
tests/e2e/tests/content-type-builder/components/update-components.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

removes workarounds caused by the bug that is being fixed

test(e2e): ctb refreshes automatically after changes

---

packages/core/upload/admin/src/pages/App/App.tsx

The window title is not set when opening the Media Library.
Other Strapi components correctly set the Media Library. Without this change, a tab with the Media Library open shows a wrong title.
Open the Media Library, look at the browsers window title.

fix(upload): window title in media library

---

packages/core/admin/admin/src/components/Form.tsx
packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormLayout.tsx
packages/core/content-manager/admin/src/preview/components/PreviewContent.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
packages/plugins/color-picker/admin/src/components/tests/__snapshots__/ColorPickerInput.test.tsx.snap
tests/e2e/tests/content-manager/preview.spec.ts

Renders the edit view form on the preview page. aka the side editor
This does NOT handle saving content updates on that form.
Next iteration of preview
Needs a future flag:
```
// config/features.js
future: {
unstablePreviewSideEditor: true,
unstableRelationsOnTheFly: true,
},
});
```
Open the preview for an entry that has preview set up. You should see the edit view form for that entry on the left half of the page next to the preview iframe. The form should be editable.
Open that same page while authenticated as a user who has permissions to read but not update that content type. You should see the preview page, but the fields should be disabled.

future: add edit form to preview page

---

packages/core/upload/admin/src/components/EditAssetDialog/EditAssetContent.tsx
packages/core/upload/admin/src/translations/ca.json
packages/core/upload/admin/src/translations/de.json
packages/core/upload/admin/src/translations/dk.json
packages/core/upload/admin/src/translations/en.json
packages/core/upload/admin/src/translations/es.json
packages/core/upload/admin/src/translations/fr.json
packages/core/upload/admin/src/translations/he.json
packages/core/upload/admin/src/translations/it.json
packages/core/upload/admin/src/translations/ja.json
packages/core/upload/admin/src/translations/ko.json
packages/core/upload/admin/src/translations/ms.json
packages/core/upload/admin/src/translations/pl.json
packages/core/upload/admin/src/translations/pt-BR.json
packages/core/upload/admin/src/translations/pt.json
packages/core/upload/admin/src/translations/ru.json
packages/core/upload/admin/src/translations/sk.json
packages/core/upload/admin/src/translations/th.json
packages/core/upload/admin/src/translations/tr.json
packages/core/upload/admin/src/translations/uk.json
packages/core/upload/admin/src/translations/zh-Hans.json
packages/core/upload/admin/src/translations/zh.json
packages/plugins/documentation/server/src/services/helpers/build-component-schema.ts

Changes the word `decription` to `description` in the `form.input.decription.file-alt` translation key, resulting in `form.input.description.file-alt`.
It's simply an enhancement to have a cleaner codebase.
Check all files in the diff.

fix: corrected typing mistake in translation key

---

packages/core/database/src/entity-manager/index.ts

This PR calls the `attachRelations` function in the database package to remove previous relations before creating new ones, restoring behavior from earlier versions.
Starting from version **5.4.0**, a bug was introduced that prevents updating files linked to an entry via the [upload entry file query](https://docs.strapi.io/dev-docs/plugins/upload#upload-entry-files) if the entry already has an associated file.
1. Create an entity with a field of type **Media**.
2. Upload a file linked to this entity using the following parameters:
```javascript
{
ref: 'plugin::users-permissions.user',
refId: userId,
field: 'avatar',
}
3. Attempt to update the media file. The update should now succeed.
When an image is already linked to a content-type (e.g., user avatar) and you try to link a new image …
```

fix: delete previous relations in morph to many relation

---

packages/plugins/i18n/admin/src/components/CMHeaderActions.tsx

Replaces the download icon with the eartch icon for fill in from another locale
It's confusing
Take a look
Enabled
Disabled

chore: swap Download icon for Earth icon

---

packages/core/admin/admin/src/pages/Auth/components/Register.tsx
packages/core/admin/admin/src/pages/Auth/components/ResetPassword.tsx
packages/core/admin/admin/src/pages/Auth/components/tests/ResetPassword.test.tsx
packages/core/admin/admin/src/utils/strings.ts
packages/core/admin/admin/tests/setup.ts
tests/api/core/admin/admin-auth.test.api.js

- fix the validation on front end password reset and registration because `TextEncoder` is not available there
- fix the message itself which was incorrectly wrapped in an object
- adds additional tests for too short / too long
- fixes an api test that was not expecting correctly
- the front end tests are failing because of the above reasons
tests should pass

fix: password validation tests

---

packages/core/admin/server/src/services/homepage.ts
tests/api/core/admin/admin-permissions-conditions.test.api.js

- Makes sure advanced permissions are respected in the endpoint for the content manager homepage widgets.
- Renames some variables to make the homepage service code easier to understand
Security issue, it made content visible to users on the homepage that they shouldn't have been able to see
Follow the instructions in https://github.com/strapi/strapi/issues/22910
fixes #22910

fix: apply advanced permissions in content manager home widgets

---

packages/core/types/src/modules/documents/params/attributes/index.ts

Fix the `documentId` type in the documents' `GetValues` type util.
Make it point to a `DocumentId` type rather than the given Schema UID.
Make sure the document service works fine with document IDs
fix #22916

fix: invalid documentId type in the getvalues util

---

packages/core/content-manager/server/src/controllers/collection-types.ts

At [collection-types.ts#L423](https://github.com/strapi/strapi/blob/8264ee203574958f5f79b39d6365b90d99074674/packages/core/content-manager/server/src/controllers/collection-types.ts#L423), it appears that an asynchronous function call is missing the await keyword. As a result, the conditional branch that depends on its return value always evaluates to false, leading to behavior that deviates from the intended functionality.
Fixes https://github.com/strapi/strapi/issues/22951

fix: await document exists

---

packages/core/content-manager/admin/src/components/InjectionZone.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/tests/content-manager.test.ts
packages/core/review-workflows/admin/src/index.ts
packages/core/review-workflows/admin/src/routes/content-manager/model/id/components/AssigneeSelect.tsx
packages/core/review-workflows/admin/src/routes/content-manager/model/id/components/Header.tsx
packages/core/review-workflows/admin/src/routes/content-manager/model/id/components/StageSelect.tsx
tests/e2e/tests/review-workflows/content-manager.spec.ts

- Create a preview.actions injection zone
- Uses that injection zone for review workflows
- Updates the InjectionZone component to pass the area to the injected component. We need something like this to conditionally render things in the ReviewWorkflows components. It think it could be useful in other cases where components are injected in different places that require different behaviors. 
To be able to update stage and assignee from preview
Go to the preview page and update the stage and assignee
This PR should be merged after https://github.com/strapi/strapi/pull/22902

feat(preview): add review workflow injection zone

---

packages/core/admin/admin/src/layouts/AuthenticatedLayout.tsx

Use the default export from package.json instead of a named export.
Only the default export can be imported from a JSON file using webpack when using ES modules.
Commit a6235c371be33d4fe306f5ead9b48bd3a0453f7a introduced mjs files shortly after be068eb4403fd20e7c662dc05f5d18858a72dd3f was merged. Together, they break building strapi using webpack.
Run `yarn build --bundler=webpack` in examples/getstarted.
Fixes #22994

fix(admin): building the admin with webpack

---

packages/core/database/src/repairs/__tests__/remove-orphan-morph-types.test.ts
packages/core/database/src/repairs/operations/remove-orphan-morph-types.ts

- removes unnecessary `target` check in `isMorphRelationWithPivot` method in the `remove-orphan-morph-types` repair method
- when removing  components that exist in a dynamic zone, the join table between the entity and component resulting in a an error whenever trying to save and edit to the contentType in the Content Manager
- Create component, 
- create a DZ and add the component
-  fill the component in the with some test data in the content-manager and save it 
- delete component from contentType builder
- come back to the contentType that used to have this component attempt to edit anything and save
this process should work with no error
fixes #22641

fix: make sure to clean _cmp tables from orphaned morph types

---

packages/core/admin/package.json
packages/core/content-manager/package.json
packages/core/content-releases/package.json
packages/core/content-type-builder/package.json
packages/core/core/package.json
packages/core/data-transfer/package.json
packages/core/email/package.json
packages/core/types/package.json
packages/core/upload/package.json
packages/core/utils/package.json
packages/plugins/documentation/package.json
packages/plugins/graphql/package.json
packages/plugins/users-permissions/package.json
yarn.lock

- upgrades `koa` to 2.15.4 to fix https://www.cve.org/CVERecord?id=CVE-2025-25200
https://www.cve.org/CVERecord?id=CVE-2025-25200
Everything should work as before, particularly anything koa specific

security(deps): upgrade koa to 2.15.4

---

docs/yarn.lock
examples/experimental-dev/package.json
packages/core/admin/package.json
packages/core/strapi/package.json
yarn.lock

- upgrades vite to 5.4.11
- bump /docs pinned version of dompurify to 3.2.4
CVE-2025-24010

security(deps): upgrade vite to 5.4.11

---

packages/core/content-manager/admin/src/features/DocumentContext.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/DocumentStatus.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/RelationModal.test.tsx
packages/core/content-manager/admin/src/preview/components/PreviewContent.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
tests/e2e/tests/content-manager/preview.spec.ts
tests/e2e/tests/content-manager/relations.spec.ts

- Adds the save and publish actions
To save and publish
Open the relation modal
Make a change
Save or publish
- There is an issue where save reverts back to the original data, then updates with the newly saved data. Removing `resetForm` in UpdateAction fixes the issue but causes issues on the editview form. Still investigating. 
https://github.com/user-attachments/assets/76d1440e-bce0-4fc1-9a71-67392c887416
- A relation that has not been saved does not refresh its data when edited

feat(relations): add save and publish actions to relations modal

---

examples/getstarted/src/admin/preview/dummy-preview.jsx
packages/core/content-manager/admin/src/content-manager.ts
packages/core/content-manager/admin/src/hooks/useDocument.ts
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/preview/components/PreviewContent.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx

- Uses [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to inform the preview iframe that strapi was updated
- To refresh the preview content without having to reload the page
Go to a preview page. Make an update and click save or publish. You should see the data updated in the preview iframe. It should the correct data based on the document status.

feat(preview): refresh iframe when strapi updates

---

packages/core/review-workflows/admin/src/routes/content-manager/model/id/components/tests/AssigneeSelect.test.tsx

Fixes the failing typescript test
To pass the CI
The Typescript tests should pass
https://github.com/strapi/strapi/pull/23024

fix: missing mock function causes typescript to fail

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-manager/admin/src/hooks/useDocumentActions.ts

adds documentId to some tracking events
telemetry for the product team to understand which features lead to more content being published
- publish content
- update content
- create content
for each action inspect the devtools, see the tracking request, you should see the documentId in the eventProperties object

chore: add documentId to tracking events

---

tests/e2e/tests/content-type-builder/collection-type/create-collection-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/create-single-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts

- copies the enhancements from the collection type tests for creating every attribute type (except relations) to single types
single type tests weren't testing attribute creation
the tests should pass

test(e2e): test all attribute types for single type in CTB

---

packages/core/admin/ee/admin/src/hooks/tests/useLicenseLimitNotification.test.tsx
packages/core/admin/ee/admin/src/hooks/useLicenseLimitNotification.ts

Remove unwanted warning on seat limit reached
A bit too visible and unecessary when you are just at the limit

enhancement: remove warning when project is at seat limit

---

packages/core/content-manager/admin/src/preview/pages/Preview.tsx

disables preview side editor form when on the published tab if the status is modified
it should only be editable on the draft tab, just like on the edit view
fixes #23079

fix: disable preview form when status is modified

---

examples/experimental-dev/package.json
packages/core/admin/package.json
packages/core/strapi/package.json
yarn.lock

upgrades vite to 5.4.13
fixes https://github.com/advisories/GHSA-vg6x-rcgg-rjx6
note that this vulnerability has not been confirmed in Strapi, and even if it is, it affects only `develop` mode
https://github.com/strapi/strapi/pull/23023

security(deps): upgrade vite to 5.4.13

---

packages/core/content-type-builder/admin/src/components/Relation/RelationNaturePicker/RelationNaturePicker.tsx
tests/e2e/tests/content-type-builder/collection-type/create-collection-type.spec.ts
tests/e2e/tests/content-type-builder/components/create-components.spec.ts
tests/e2e/tests/content-type-builder/components/edit-components.spec.ts
tests/e2e/tests/content-type-builder/single-type/create-single-type.spec.ts
tests/e2e/tests/content-type-builder/single-type/edit-single-type.spec.ts
tests/e2e/utils/content-types.ts

Adds aria attributes to the relations buttons in the CTB
NOTE: I accidentally merged [some tests](https://github.com/strapi/strapi/pull/23078) into this that were dependant on this PR and I had intended to wait until this was merged. But they're just tests and technically do test this functionality 😆 and they've already been reviewed [here](https://github.com/strapi/strapi/pull/23078)
There was no way for screen readers (or Playwright) to identify which button was which, nor to detect which button was currently active. This way we tell screen readers to ignore the svg and read the new label instead.
inspect element on the ctb relations buttons as you use them and see the labels

enhancement(ctb): add aria data to relations buttons

---

packages/core/content-manager/admin/src/features/DocumentContext.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
tests/e2e/tests/content-manager/relations.spec.ts

Maintains document history in DocumentContext
So we can use the back button in the relation modal
Go to an entry with relation, that has a relation, that has a relation...or something like that
Click the relation, then its relation, then its relation.
The go back, back, back.
You should be where you started.
Going back with with unsaved changes should trigger a confirm dialog

feat(relations): add back button history

---

packages/cli/cloud/package.json
packages/core/admin/package.json
yarn.lock

upgrades axios to 1.8.2
CWE-918
used in too many places to list
The [changelog](https://github.com/axios/axios/releases) lists some breaking changes in 1.8.0 but they don't seem to affect us; but if someone who knows more about where and how axios is used can confirm, please do!
DX-1927

security(deps): upgrade axios to 1.8.2 for CWE-918

---

packages/core/content-manager/admin/src/features/DocumentContext.tsx
packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/NonRepeatable.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Repeatable.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/ComponentCategory.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/Relations.test.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormLayout.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
tests/e2e/tests/content-manager/relations.spec.ts

Main quest:
The main goal of the PR is to fix dynamic zones and components. Currently they do not work at all. After this PR you should be able to see components and dynamic zones. If they have a relation you should be able to open that relation in a modal.
Side quests:
I also made some other improvements and fixed some issues with i18n, see below:
- Passes document to InputRenderer as a prop. (This just simplifies what document we are dealing with in the InputRenderer).
- Fix issues with locale relations
- You should be able to open the relation modal from a relation inside a component or dynamic zone
- The browser console should have no network request errors for relations when the modal is open
Please also check i18n specific edge cases at the root level and in dz and components:
- …

fix(relations): dynamic zones and components do not work

---

packages/core/content-manager/admin/src/preview/pages/Preview.tsx
tests/e2e/tests/content-manager/preview.spec.ts

Prevents switching tabs in the preview page when the side editor form has unsaved changes
- makes changes on the draft tab
- try to go to published without saving
- see the confirmation dialog
fixes #23080

fix: prevent switching preview tabs with unsaved changes

---

packages/core/content-manager/admin/src/preview/pages/Preview.tsx

Fixes incorrect boolean has background passed to layout
To not see the background on the preview page
Go to the preview page you should see this:
Not this:

fix: preview should not have a background

---

examples/getstarted/src/admin/preview/dummy-preview.jsx
packages/core/content-manager/admin/src/features/DocumentContext.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/RelationModal.test.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx

- Passes onPreview to the DocumentContextProvider instead of the PreviewProvider
Side quests:
- Rename RelationModalWrapper => RelationModalForm
- Update incorrect component string names in the context providers
- So the callback can be called in the RelationModal and on the PreviewPage
Go to preview, update a relation, you should see the change immediately without having to refresh
https://github.com/user-attachments/assets/2f0029f8-1380-48f0-90be-dbe129ca5417

fix: onPreview is not called when updating a relation

---

packages/core/core/src/services/document-service/utils/bidirectional-relations.ts
tests/api/core/strapi/api/relations.test.api.ts

When publishing, we were re we were syncing bidirectional relations order
https://github.com/strapi/strapi/pull/22834
This PR introduced a rather manual process in the document service, to handle the inverse order of relations when publishing.
It was achieved by retrieving all relations connected to a soon to be published entry, and overwritting the order of new relations.
This introduced an issue for bidirectional relations targeting itself (same content type). Those do not store any inverse order, and the code didn't account for null order values.
The current PR addresses the issue by NOT syncing any bidirectional relation that targets itself (the same content type)
- Create a content type (e.g Category) with Draft and Publish enabled
- Create a bidirectional relation (e.g oneToMany) …

fix: fails to update self referencing relations on publish

---

.github/actions/pr_diff/action.yml

use `github.token` instead of `secrets.GITHUB_TOKEN` as the later is only accessible from workflows

fix: incorrect token source in pr diff

---

.github/actions/pr_diff/action.yml
.github/workflows/diff_prs.yml

- Use the absolute path to the script
- Use hardcoded `strapi` values for the owner and repo parameters as it's not possible to dynamically get the repository name from the `github` namespace (`github.repository` equals `strapi/strapi` instead of `strapi`)

fix: incorrect file path and parameters for pr_diff

---

.github/actions/pr_diff/action.yml
.github/actions/pr_diff/script.sh
.github/workflows/diff_prs.yml

use the new step summary instead of the deprecated set:output for the pr diff

fix: deprecated step summary output

---

packages/core/content-manager/admin/src/pages/EditView/components/EditorToolbarObserver.tsx

Fix the visibility problem we had in preview with the blocks and markdowns when you reduce the width of the viewport and show the three dots menu
Currently the menu is not shown
Open an entry with a markdown field or a block field and open the preview page of it, then reduce the width of the page and click on the three dot menu in the header of the block field and markdown field and check it is working
CS-1361

fix: add z index property to the menu content in blocks and markdown

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/DynamicZone/DynamicComponent.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx

Fix related document components in dynamic zones not diplaying
A related document could not display its components within the relation modal
Create a relation with a document that has a dynamic zone and one of the dz components has a relation input
Open the relation in the relation modal, go to the dz and select a component, you should see the form
Select a relation in the component form
Open that relation in the modal to confirm it works

fix(relations): no components available in relation modal dynamic zone

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx

Pass the correct data on reordering
Because otherwise we have this issue in the Relations on the fly modal
https://github.com/user-attachments/assets/757e85f5-9caa-4dad-a602-5cedcf129ff4
adding a new relation, reorder, click to open the modal

fix: add the correct locale and document Id when we reorder the relations

---

packages/core/data-transfer/src/strapi/providers/local-source/assets.ts

- res.body is already a readable stream no need to convert it
- reading assets streams from remote providers is not working and getting stuck
experimental: `0.0.0-experimental.9678892591ed5d28450369e1511b3d21cb7db4f9`
- test a pull transfer against a project hosted on cloud
- or setup a project with aws or cloundinary providers and try to pull
possibly fixes #16473 
fixes #22038

fix: correctly read asset stream for dts asset remote providers

---

packages/core/admin/admin/src/pages/Settings/constants.ts

Updated the import of ProtectedEditPage in the webhook module to prevent failure in the production build. Introduced delayed import by first assigning the module to a const and resolving it afterwards.
It solves the issue : Cannot destructure property 'ProtectedEditPage' of '(intermediate value)' as it is undefined. On production build webhooks detail page.
I validated this by creating a webhook in an older version and attempting to update it. Before applying this fix, I encountered the error:
"Cannot destructure property 'ProtectedEditPage' of '(intermediate value)' as it is undefined."
After implementing the fix, the issue is resolved.
It is related to #23099.

fix: On production build webhooks detail page intermediate value issue.

---

packages/core/review-workflows/server/src/services/metrics/weekly-metrics.ts
packages/core/upload/server/src/services/weekly-metrics.ts

Upload cronjob take 5 minutes until it first, and its too much time for cloud environments that shutdown the container if there is no use.
This PR reduces this time.

fix: run cronjobs closer to app start

---

docs/package.json
docs/yarn.lock
packages/core/content-manager/package.json
yarn.lock

Upgrades prismjs to 1.30.0
Remove warnings for CVE-2024-53382 -- in Strapi's usage there does not appear to be an actual vulnerability
syntax highlighting should still work
DX-1951

chore: upgrade prismjs to 1.30.0

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-manager/admin/src/content-manager.ts
packages/core/content-manager/admin/src/hooks/useDocumentActions.ts
packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/preview/components/PreviewHeader.tsx

Add the property fromRelationModal to true when we trigger the events didEditEntry and didPublishEntry
Add the property fromPreview to true when we trigger the events didEditEntry and didPublishEntry in the Preview page
and Add the properties fromRelationModal and fromPreview to true when we trigger the events didEditEntry and didPublishEntry in a relation modal inside the Preview page
to Distinguish between the Save and Publish events in the Relation modal and in the Preview page
Try to save and modify an entry in the Relation modal and do the same in the Edit View and check if the event property fromRelationModal is set to true in the first case and to false in the other cases
Try to save and modify an entry in the Relation modal inside a Preview page and do the same in the Edit View …

enhancement: add tracking for editing relations on-the-fly and preview

---

packages/core/content-manager/admin/src/pages/ListView/components/TableCells/Relations.tsx

Removes the "prohibited" icon (🚫) that shows up when hovering over related items in dropdowns. Items stay clickable, just without the confusing icon.
When viewing relation fields in the list view, hovering over entries in the dropdown menu shows a 🚫 icon, which confuses non-technical users by suggesting these items aren't clickable when they actually are. This PR ensures the UI accurately represents the interactive nature of these items while maintaining their navigation functionality.
Create two content-types with a many-to-many relation between them
Create some entries and set up relationships between them
Add the relation field to the list view
Click on the relation count to open the dropdown
Hover over the entries in the dropdown menu
Verify that the 🚫 icon no longer appears when …

fix: relation menu link

---

packages/core/admin/ee/admin/src/pages/AuthResponse.tsx

prevent deleting cookie in SSO sense we will re-set the cookie in the login logic anyways
We are using the session cookies for login now, deleting the cookie will log the user out

fix: preserve cookie in sso login

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/RelationModal.test.tsx

Moves the FormProvider inside Modal.Body, because inside Modal.Root wasn't enough for it to be inside the react portal. This should fix the nested form error
Also fixes the ellipsis issue on the relation modal trigger. The actual fix is max-width: 100% on StyledTextButton, I just made some housekeeping updates around it too
- check the errors in your console
- try having a relation with a super long name to make sure the ellipsis shows

fix: relation modal nested form issue

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/tests/RelationModal.test.tsx

From entry A, open relation B in a modal, then on it click on relation A. Then click the open full page button. Before this fix the relation modal wouldn't close. Also make sure the open full page button still works in other cases

fix: relation modal not closing when opening self in full page

---

packages/core/admin/admin/src/reducer.ts
packages/core/admin/admin/src/utils/getFetchClient.ts
packages/core/admin/ee/admin/src/pages/AuthResponse.tsx

removes re-setting cookie of `jwtToken` in SSO,
cookies is already set from the server
Login with SSO doesn't work because of session cookies enhancement
Try to login with SSO it should work
fixes #23246

fix: SSO login JWT formatting issues

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/UID.tsx

Avoids calling useDoc directly in the UID field. Because it would not work when inside a relation modal. Use useDocumentContext instead.
Normal UID field behavior:
- open kitchensink editview
- regenerate the slug field, it should not throw errors and should match the shortField value
Then do the same inside of a relation modal. You can find a relation to kitchensink via a tag entry.

fix: uid fields broken inside relation modals

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx

Disables the 'publish' / 'save' button when publishing an entry that only updated a relation.
We were not reseting the form after publishing.
After updating a relation (one to many in this case) and then clicking "publish", the "save" and "publish" buttons immediately became available again, and when trying to navigate away from the page it opened  the "are you sure" confirmation modal.
1. Have an "article" and "category" type, with article having one category
2. Create an article
3. Publish it
4. Go back and edit the article, changing the category
5. Click publish
6. Publish and save should be disabled, as there is not any modified content.
Fixes https://github.com/strapi/strapi/issues/21378

fix: disable publish button when publishing a relation change

---

packages/core/content-manager/admin/src/pages/EditView/components/DocumentActions.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/RelationModal.tsx

It handles the case you publish, in the Relation on the fly modal, a relation starting from the creation entry form, because if you try to publish an entry from the creation view you have a redirect to the edit view of the just created document, but in the case of a relation modal, we need to skip this redirection
We had a wrong redirection when we tried to Publish a nested relation inside a creation entry form
- Go to a Collection and click "Create an entry"
- in the form you need to have a relation field, try to select a value for this relation field and click on it to open the Relation modal
- in the relation modal change a value and Publish
- you need to see a successful message and no redirections but instead remain in the modal
fixes https://github.com/strapi/strapi/issues/23286

fix: OTF relations wrong redirect when publishing a nested relation during new entry creation

---

packages/utils/upgrade/src/modules/codemod-repository/constants.ts

Update the path to codemods
It is broken
Create a strapi 5.12.1 app
From that app run
```
node ../../path-to-strapi/packages/utils/upgrade/bin/upgrade.js minor
```
It should upgrade and not throw an error

fix(upgrade): incorrect path to codemods

---

packages/core/content-manager/package.json
yarn.lock

Bumps markdown-it from 12.3.2 to 13.0.2

chore(deps): bump markdown-it from 12.3.2 to 13.0.2

---

.github/workflows/tests.yml
playwright.base.config.js
tests/scripts/run-e2e-tests.js

There are some problems with JUnit report generation. 
- Look like all the files are called junit, which collides
- Looks like the `test-apps/e2e/test-results` was getting wiped between runs so only the last run ever gets saved there
- Updates the upload job to Trunk, which should point now to `test-apps/junit-reports/*.xml`
This instead outputs different test domains as separate files in a path that isn't wiped between runs
Existing HTML reports aren't changed.
Currently, uploads to Trunk is incorrect, this affects flaky tests detection.
Further more, this will allow accurate display if you choose to enable PR comments: https://docs.trunk.io/flaky-tests/github-pull-request-comments
Run tests and observe the outputted XML files. Also view upload succeeds in CI and uploads are found in …

Fix report generation and upload

---

packages/cli/cloud/package.json
packages/core/admin/package.json
yarn.lock

Update axios dependency to prevent [reported vulnerability](https://github.com/strapi/strapi/security/dependabot/487)

chore: bump axios to 1.8.4

---

packages/core/admin/admin/src/components/WidgetHelpers.tsx
packages/core/admin/admin/src/components/tests/Widget.test.tsx
packages/core/admin/admin/src/index.ts
packages/core/admin/admin/src/pages/Home/HomePage.tsx
packages/core/admin/admin/src/pages/Home/components/ContentManagerWidgets.tsx
packages/core/admin/admin/src/pages/Home/components/tests/Widget.test.tsx
packages/core/admin/admin/src/translations/en.json

- Exports the widget helper components
- Does NOT export the root since all widgets will be wrapped in this component
- Adds a NoPermissions helper component
- Refactors the current homepage to use the Root directly
Prepare for incoming widgets
No visible change. The homepage should look and function exactly the same. 
You should be able to import Widget from a plugin like:
```
import { Widget } from '@strapi/strapi/admin';
```

future(homepage): export widget helper components

---

.github/filters.yaml
tests/scripts/run-e2e-tests.js

launch dev server in watch mode on initial run to save the admin build time on every test domain (20-30 seconds on github runners)
also updates the workflow filter to actually run the tests when their runners are modified
In https://github.com/strapi/strapi/pull/23337 I erroneously used `--no-watch-admin` but that's only needed for the server launched by playwright; since we're only waiting for this one to come up and run bootstrap, we don't care if the admin is built or not
tests should pass (but a bit faster)

test(e2e): launch initial server in watch mode

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Relations/Relations.tsx

Add a link icon on the left of the relation option's label
It is required from the design
Open a collection with a relation field and try to open the combobox of the Relation's field to check the presence of the icon
CS-1309

feat: add a link icon on the left of the relation option

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/BlocksEditor.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/BlocksInput/EditorLayout.tsx
packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Wysiwyg/EditorLayout.tsx
tests/e2e/tests/content-manager/relations.spec.ts

Changes the implementation of the blocks and markdown editor "focus mode" modals, in order to use the Modal component from the design system instead of a DIY React portal
Without it the modal can't be rendered on top of the ROTF relation modal. It also removes some old imperative code
Use the markdown and blocks editors in the edit view, try the focus mode, preview mode for markdown, etc.
Also try it in the context of a relation modal: Tag entry => open Kitchensink relation modal => see rich text fields
Replaces #23296

fix: rich text editors focus mode modals

---

packages/core/admin/admin/src/core/apis/Widgets.ts
packages/core/admin/admin/src/features/Auth.tsx
packages/core/admin/admin/src/pages/Home/HomePage.tsx

Uses the permissions array provided by each plugin. Only display each widget to the user if they have all the permissions in the array
Security / content safety
- Have the widgets API future flag (it's enabled in getstarted)
- You should see the CM widgets when logged in as super admin since you have the CM explorer.read permission
- Log in as a user that does not have the CM eplorer.read permission (aka someone who has no read permissions at all, both collection types and single types). You should see the CM widgets in their "no permissions" mode

future: check permissions before rendering widgets

---

packages/core/admin/admin/src/index.ts
packages/core/admin/admin/src/pages/Home/HomePage.tsx

Export the Widget type from `@strapi/admin/strapi-admin`
To make TS happy
Run yarn test:ts:front the tests should pass
https://github.com/strapi/strapi/pull/23397
It looks like it's causing an error on the release branch https://github.com/strapi/strapi/pull/23413
but I don't get it the code isn't on that branch 🤔

fix: widget type not exported from @strapi/admin/strapi-admin

---

packages/core/admin/admin/src/features/Tracking.tsx

Adds information about registered widgets to the didInitializeAdministration tracking event
So we can watch usage of the widgets API
Open your admin. The first tracking event, that should only appear once, should be didInitializeAdministration. Look at the event payload. In the groupProperties object, you should see a registeredWidgets property that should be an array of UID strings (e.g. `global::mywidget`, or `plugin::myplugin.mywidget`)

future: track registered widgets

---

packages/core/content-manager/admin/src/services/homepage.ts

Fixes the cache invalidation for the homepage widgets in the content manager
The cache becomes stale and requires a refresh
Make sure you have the future flag set for unstableWidgetsApi (set by default in examples/getstarted)
Go edit an entry
Go to the homepage
You should see your update without refreshing
Go publish and entry
Go to the hompage
You should see your published entry without refreshing
https://github.com/user-attachments/assets/5a4d236a-0049-4b35-b799-893371facd6c

future(homepage): missing addTagTypes results in stale data

---

packages/core/admin/admin/src/pages/Home/HomePage.tsx

Displays the link that may be provided through the widget API
we forgot about it, it's in the API and the designs
Either register a new plugin with a link, or modify the CM plugins locally to add a link like this:
https://github.com/user-attachments/assets/f8a51fd7-09f3-40dc-a856-7b724a3717dd

future: add missing widget link button

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/Component/Repeatable.tsx

Disables the icon button for repeatable component in published tab 
See #23305 
Go to a repeatable component and try clicking on delete icon when in Published tab. 
Nothing will happen as it is disabled. 
Go to draft tab and click the delete button and it will work. 
#23305

fix: updated icon button to include disabled flag for repeatable comp

---

packages/core/strapi/src/cli/utils/data-transfer.ts

Current CLI output:
```
✔ entities: 93 transfered (size: 177.2 KB) (elapsed: 123 ms) (1.4 MB/s)
✔ assets: 12 transfered (size: 439.1 KB) (elapsed: 35 ms) (12.3 MB/s)
✔ links: 303 transfered (size: 53.4 KB) (elapsed: 17 ms) (3.1 MB/s)
✔ configuration: 49 transfered (size: 148.1 KB) (elapsed: 7 ms) (20.7 MB/s)
```
The word 'transfered' appears in the output; this PR corrects it to 'transferred'.
Grammatically correct output is always nice.
Perform a `strapi import -f ...` CLI command

fix: typo in `data-transfer` CLI

---

packages/core/openapi/package.json
packages/core/strapi/package.json
packages/core/strapi/src/cli/commands/index.ts
packages/core/strapi/src/cli/commands/openapi/generate.ts
yarn.lock

Add a command to generate an OpenAPI specification for the app's content-API
```bash
yarn strapi openapi:generate [-o, --output <output>]
```
Accept an optional output option to specify where to generate the specification (by default, set to `specification.json`)
Integrate the OpenAPI work done in `@strapi/openapi` into Strapi

feat(strapi): add an openapi:generate command

---

packages/core/admin/server/src/content-types/api-token.ts

Uses 'text' instead of 'string' to store the encrypted key
The size of the string exceeds the length of varchar(255) so mysql and postgres fail to start up
- Set the encryptedKey config property
- using mysql + postgres
- start up strapi; it should work now

fix: use text for encrypted key of viewable api token

---

packages/core/types/src/core/config/admin.ts

Adds the missing config `Admin['flags']` prop
When typing `config/admin.ts`  TS gives an error
```
Object literal may only specify known properties, and 'flags' does not exist in type 'Admin'.ts(2353)
```
https://docs.strapi.io/cms/configurations/admin-panel#available-options
| Parameter | Description | Type | Default |
|--------|--------|--------|--------|
| `flags` | Settings to turn certain features or elements of the admin on or off | `object` | - |
| `flags.nps` | Enable/Disable the Net Promoter Score popup | `boolean` | `true` | 
| `flags.promoteEE` | Enable/Disable the promotion of Strapi Enterprise features | `boolean` | `true` | 
Add `Core.Config.Admin` return type to the `config/admin.ts`
https://github.com/strapi/strapi/pull/22620

fix(types): add missing flags prop to admin config

---

packages/core/types/src/core/config/database.ts

Add missing `settings.useTypescriptMigrations` prop to database config
When adding `settings.useTypescriptMigrations` to config/database.ts TS gives an error
```
Object literal may only specify known properties, and 'useTypescriptMigrations' does not exist in type '{ forceMigration?: boolean | undefined; runMigrations?: boolean | undefined; }'.ts(2353)
```
https://docs.strapi.io/cms/database-migrations#handling-migrations-with-typescript-code
Add `settings.useTypescriptMigrations` to the `config/database.ts`

fix(types): add missing `settings.useTypescriptMigrations` prop to database config

---

.github/workflows/tests.yml

updates trunk to stable `v1`
for stability, we shouldn't be using `main` (`latest`)
if it somehow stops reporting data to trunk, we revert it

chore(ci): update trunk to v1

---

docs/package.json
docs/yarn.lock

Fix: Update image-size to 1.2.1 in docs to resolve CVE
Dependabot Alert: image-size Denial of Service via Infinite Loop during Image Processing #486
This commit resolves a vulnerability in the `image-size` package by forcing its version to `1.2.1` within the `docs/package.json` using Yarn resolutions.
The `image-size` package, a transitive dependency pulled in by Docusaurus, had a Denial of Service vulnerability (versions >= 1.1.0, < 1.2.1). The patched version is 1.2.1.
Initially, I attempted to update the Docusaurus packages (`@docusaurus/core`, `@docusaurus/preset-classic`, `@docusaurus/theme-mermaid`) from `3.7.0`, but they were already at their latest versions and did not bring in the patched `image-size`.
I then used the `resolutions` field in `docs/package.json` to explicitly set …

chore(deps): upgrade image-size package in docs

---

packages/core/content-manager/server/src/history/services/__tests__/lifecycles.test.ts
packages/core/content-manager/server/src/history/services/lifecycles.ts

persists the history table
We want to avoid deleting history data when users no longer have a valid license. They should be able to re-add a license and still have access to their old history.
Same thing is done for audit logs already
User facing:
- Start the app with an EE license
- Make on an entry
- Open the history page, see the history versions
- Restart the app without the license
- Restart the app with the license again
- Check the history page for your entry. You should see the history versions
Or checking the implementation detail: open a database explorer, in the `core_store` table, find the `core_persisted_tables` table. The json content should include `strapi_history_versions`

fix: avoid history data loss when license is missing

---

examples/getstarted/src/api/address/content-types/address/schema.json
packages/core/upload/admin/src/components/MediaLibraryInput/MediaLibraryInput.tsx
packages/core/upload/admin/src/utils/getAllowedFiles.ts

Fix #23572 
We used a default allowed type preventing user from uploading different types even when their schema should allow it
try to upload a gpx file for ex inside the CM edit view 
#23572

fix: issue #23572 support undefined allowed types

---

packages/core/admin/admin/src/components/Layouts/HeaderLayout.tsx

It fixes a z-index issue showing the content of an accordion above the sticky header in the admin interface.
_ℹ️ I picked 3 as zIndex because I saw that the modal of the guided tour starts at 4 and the accordions are 1, it gives a tiny flexibility to have other elements at 2 while keeping the sticky header above._
To improve the user experience on the site and improve readability when displaying accordions in the admin.
- Go to the admin interface
- Go to Settings > Roles
- Click on any role
- Scroll to an accordion and expand it
- The header appear behind the content of the accordion
Resolves #22208 
🚀

fix: header behind other elements

---

packages/core/admin/admin/src/pages/Home/components/FreeTrialEndedModal.tsx
packages/core/admin/admin/src/pages/Home/components/FreeTrialWelcomeModal.tsx
packages/core/admin/admin/src/pages/Home/components/tests/FreeTrialEndedModal.test.tsx

Fix 2 bugs found during QA
- The trial ended dialog not appearing when trial ends -> the `FreeTrialEndedModal` component now use the same logic as the `UpsellBanner` component
- LocalStorage is not updated when `FreeTrialEndedModal` and `FreeTrialWelcomeModal` modals are closed by clicking the modal background layer -> logic updated for the `onOpenChange` prop

chore: update trial ended modal logic

---

docs/yarn.lock
examples/experimental-dev/package.json
packages/core/admin/package.json
packages/core/strapi/package.json
yarn.lock

Monorepo
- updates package.json version of `vite` to 5.4.19 for CVE-2025-46565
- updates pinned version of `tar-fs` to `2.1.3` for CVE-2025-48387
- udpates pinned version of `axios` to 1.9.0
Docs
- updates pinned version of `http-proxy-middleware` to 2.0.9 for CVE-2025-32997
- updates pinned version of `estree-util-value-to-estree` to 3.4.0 for CVE-2025-32014
Labeled this `chore` because Strapi is not actually vulnerable to any of the CVEs
general maintenance and package health
Existing tests and functionality should all work

chore: upgrade vite, axios, tar-fs

---

packages/core/types/src/core/config/index.ts

Export the `Shared` types namespace for Core.Config
With this exported, Strapi users are able to type their config files.
```ts
import type { Core } from "@strapi/strapi";
type AdminConfig = Core.Config.Shared.ConfigFunction<Core.Config.Admin>;
const config: AdminConfig = ({ env }) => {
return {
apiToken: { salt: env("API_TOKEN_SALT") },
transfer: { token: { salt: env("TRANSFER_TOKEN_SALT") } },
auth: { secret: env("ADMIN_JWT_SECRET") },
};
};
export default config;
```
> [!NOTE]
> This `shared.ts` file seems to have been created for this but was never exported and is not used inside Strapi code also.

feat(core/config): export Shared types

---

packages/core/content-manager/admin/src/pages/EditView/components/FormInputs/UID.tsx
packages/core/content-manager/admin/src/utils/validation.ts
packages/core/content-manager/server/src/controllers/validation/index.ts
packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.ts
packages/core/content-type-builder/server/src/controllers/validation/__tests__/types.test.ts
packages/core/content-type-builder/server/src/controllers/validation/schema.ts
packages/core/content-type-builder/server/src/controllers/validation/types.ts
packages/core/core/src/services/entity-validator/validators.ts
packages/core/types/src/schema/attribute/definitions/uid.ts
tests/api/core/content-manager/content-manager/uid.test.api.js

The UID field can be used to generate a slug but it misses the opportunity to include a slash (`/`).
This PR implements a new "regex" attribute based on the one from the Text field.
It adds a `regex` attribute on the UID field type.
When using the UID field type to generate a slug, we may need to include a slash (`/`).
- In the "get started" example, update the homepage content type to set the regex attribute of the `slug` property with the following pattern `^[A-Za-z0-9-_.~/]*$`. It's the same than the UID_REGEX used everywhere in the codebase, except it allows the `/` character.
- Edit the `slug` property in homepage content to replace the value with `home/page`.
BEFORE
AFTER

feat(uid): add regex attribute

---

packages/core/upload/package.json
yarn.lock

upgrades formidable from 3.5.1 to 3.5.4
Removes warning for CVE-2025-46653 although Strapi does not appear to be vulnerable
DX-2051

chore(deps): upgrade formidable to 3.5.4

---

packages/core/upload/admin/src/components/AssetCard/AssetCard.tsx
packages/core/upload/admin/src/components/AssetCard/AssetCardBase.tsx
packages/core/upload/admin/src/components/AssetGridList/AssetGridList.tsx

I have fixed some issues with upload media files for example:
* Checkbox z-index with audio file
* Edit button with audio file
* Draggable media file style
The main problem is that it is not obvious that you can change the order of files in the field
1. Create media field with multiple files
2. Upload files
3. Select "Selected files"
4. Move files and change order.
5. Check action buttons position
Fixed issue
https://github.com/user-attachments/assets/826c887a-8a5e-4b94-a599-a4b72b40ba80
Expected behavior in browse tab
https://github.com/user-attachments/assets/55d7b3c9-ae04-4ffe-ad3c-3dff22a8709c
#22097

fix(upload): draggable element style

---

packages/core/admin/admin/src/pages/Settings/pages/Roles/components/PluginsAndSettings.tsx
packages/plugins/users-permissions/admin/src/utils/formatPluginName.js

Changes the name of the upload plugin in Roles and Permissions from Upload to Media Library.
Before:
After:
It's confusing to the user since the plugin is called Media Library on the CMS. Even if the plugin is called upload, on the frontend it's displayed and identified as Media Library.
In a second time, we should consider moving the plugin itself but for now we just changed the displayed name in the Roles and Permissions.
- Go to the admin interface > Settings > Roles
- Select any role
- Go to Plugins tab (if in Admin Roles) or by just scrolling to the accordion (if in Users & Permissions)
Resolves #20842
🚀

fix: display name of upload plugin in roles settings

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/content-type-builder/admin/src/components/AIChat/UploadCodeModal.tsx
packages/core/content-type-builder/admin/src/components/AIChat/UploadFigmaModal.tsx
packages/core/content-type-builder/admin/src/components/AIChat/hooks/useAttachments.ts
packages/core/content-type-builder/admin/src/components/AIChat/providers/ChatProvider.tsx

Removes the tracking event `didUserSendMessage` from the CTB
We don't know the token count from the client. Therefore it may make more sense to send the amplitude tracking event `didUserSendMessage` from https://github.com/strapi/strapi-ai where we know these values
See https://github.com/strapi/strapi-ai/pull/22 - we should wait for this approach to be approved before merging
DX-2026

refactor: remove didusersendmessage tracking event

---

packages/core/admin/admin/src/pages/Settings/pages/Users/ListPage.tsx

Fixing the design of the user's status in the list in Settings > Administration Panel > Users to match other badges in the CMS.
Before:
After:
_There's also an initiative to revamp the badges in the design system to unify them on the CMS here: https://github.com/strapi/design-system/issues/1935_
To unify the experience of the badges and their meaning.
- Go to the admin interface > Settings > Administration panel > Users
- The tags are displayed in each element of the list (Active / Inactive)
Resolves #21343
🚀

fix: design of user status

---

packages/core/admin/admin/src/features/Tracking.tsx
packages/core/admin/admin/src/layouts/AuthenticatedLayout.tsx

- remove the didInitializeAdministration event as be block it anyway on amplitude as it created too many events
- move the widgets tracking to didAccessAuthenticatedAdministration instead
check your networks tab, find didAccessAuthenticatedAdministration, see the registeredWidgets property with an array of string uids

chore: track widgets usage

---

packages/core/core/src/Strapi.ts
packages/core/core/src/services/utils/__tests__/conditional-fields.test.ts
packages/core/core/src/services/utils/conditional-fields.ts

add conditional field count tracker
because
1. in `packages/core/core/src/services/metrics/sender.ts` OR do a global find/replace (necessary if you are testing some events that happen outside of normal Strapi usage) 
2. replace the `https://analytics.strapi.io/`string to be `http://localhost`
You may have to replace it in several places, and when starting your Strapi server, you should see your localhost (http://localhost/) URL in the logs rather than analytics.strapi.io
3. Build Strapi again so that it builds with that URL
4. Run the command `npx http-echo-server 80` in a terminal window
NOTE: if you don't have port 80 available for this purpose, you’ll need to add a port to the previous line such as 'http://localhost:1234'
5.In another terminal window, start Strapi (or run the CLI …

feat: add tracker for conditional field count

---

packages/core/admin/server/src/strategies/api-token.ts

- Checks if lastUsedAt in api tokens is null and updates it to currentDate
- ensures that lastUsedAt is correctly updated
- fix #23274 
Create an Api Token, use it in any content-api request, Last Used should show and update like below
fix #23274

fix(api-tokens): update lastUsedAt if it's null

---

packages/core/admin/admin/src/components/GuidedTour/Provider.tsx
packages/core/admin/admin/src/components/UnstableGuidedTour/Step.tsx
packages/core/admin/admin/src/components/UnstableGuidedTour/Tours.tsx

Adds the Popover.Arrow to the Guided tour popovers
it is required by design
- Clean the local storage and create a new Strapi project from scratch without collectiions
- try to create new Collections following the Guided tour
- and add new content using the Content manager
- and create a new Api token
use the experimental 0.0.0-experimental.f37a0ea0333947b6879c4608fae75646d63c07a1  to create the project

future: add the Popover.Arrow in the guided tour

---

packages/core/admin/admin/src/components/UnstableGuidedTour/Overview.tsx
packages/core/admin/admin/src/translations/en.json

Add the confirmation dialog when closing the guided tour
It's in the designs
Make sure you have the future flag enabled and local storage is clear
Go to the overview and click close guided tour
You should see a confirmation dialog
Click confirm
It should close the dialog and the guided tour overview 
https://github.com/user-attachments/assets/68830e90-1b95-4ede-bb33-d92f29470e1d

future: add confirmation dialog when closing the tour

---

packages/core/admin/admin/src/components/UnstableGuidedTour/Tours.tsx
packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx
packages/core/content-type-builder/admin/src/pages/ListView/ListView.tsx

- Runs the tours no matter what the app state is
Simplify
0.0.0-experimental.7281e9ed655cf0093344801f3db6c50a4f6ec20f
- Test with this option: Start with an example structure & data? y
When the overview loads all tours should be marked as not done yet
When you go to the CTB it should propose the tour even if there is already a schema
When you go to the CM it should propose the tour even if there is already content
When you go to the API tokens it should propose the tour even if a new token has been created
Otherwise it should function the same as before. Test an empty app too to ensure this is the case. 

future: always run the tour regardless of app state

---

packages/core/upload/admin/src/components/FilterPopover/FilterPopover.tsx

Changed the z-index of the filter popover component used in `Media Library`.
https://github.com/user-attachments/assets/93e4b4c0-a077-407d-8d67-9d86cadd8749
To resolve the issue of the filter popover overlapping the datepicker, making parts of the datepicker unusable.
The steps provided to reproduce the issue are correct and remain the same when testing the changes made.
Fixes #23952

Resolved filter overlapping issue by changing z-index

---

packages/core/content-manager/admin/src/preview/pages/Preview.tsx

- fixes regression from #23985 that caused a full screen loader when saving an update from the preview side editor. That prevented "live" preview to work because it reloaded the iframe every time
- another attempt at fixing the "no data" flash by adding a more specific condition for the loader
- navigate from the edit view to the preview page. You should not see the "no data" screen, even for a fraction of a second
- make an update in the preview side editor and fix it. There shouldn't be any full screen loader. The preview on the right should directly update to reflect the change instead

fix: prevent full screen loader regression in preview page

---

packages/core/openapi/package.json
yarn.lock

Fix failing `nx run @strapi/openapi:build:types` by using the correct version of @strapi/types in @strapi/openapi

chore(openapi): update dependencies to version 5.20.0

---

examples/empty/config/admin.ts
examples/empty/config/server.ts
examples/empty/package.json
examples/getstarted/package.json
examples/kitchensink-ts/package.json
examples/kitchensink/package.json
packages/core/strapi/src/node/vite/config.ts

Adds config with default env vars
The example app won't start without them
Run `examples/empty` it should work

fix: incorrect config won't run app

---

tests/api/core/admin/admin-api-token-crud.test.api.ts

Tests that the viewable api tokens works correctly
tests weren't missing
specifically, it will prevent a regression of the critical bug solved in https://github.com/strapi/strapi/pull/23477
See the CI, or to run it manually, make sure you have a mysql and postgres running on your system (matching the config found in `run-api-tests.js`) and run:
`yarn test:api:clean`
`yarn test:api --db=mysql admin-api-token-crud` 
`yarn test:api --db=postgres admin-api-token-crud`
https://github.com/strapi/strapi/pull/23477
DX-2009

test(api): add test for viewable api tokens

---

packages/core/admin/ee/server/src/audit-logs/services/lifecycles.ts

Changes the Audit Logs retention check to allow for increases if the license allows it. 
Previously it would only check that the override was "less than" the license limit but in some cases a few customers have a longer retention based on their license features (greater than 90 days)
Create a license key with longer than 90 days audit logs retention and manually configure the longer limit, verify that the retention was properly increased
TID 2075

fix: allow audit logs to be increased up to the license maximum

---

examples/getstarted/src/admin/preview/dummy-preview.jsx
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
packages/core/content-manager/admin/src/preview/utils/constants.ts
packages/core/content-manager/admin/src/preview/utils/previewScript.ts

sets up the boilerplate needed to get code that lives in the content manager to run on the websites of users.
we need to own a script that runs in the websites of users for the next preview improvements
open the preview for any entry in getstarted, open your console, you should see a log from within the preview page
fixes https://github.com/strapi/content-squad/issues/59

future: set up preview injected script

---

examples/empty/package.json
examples/getstarted/package.json
examples/kitchensink-ts/package.json
examples/kitchensink/package.json
packages/core/strapi/src/node/vite/config.ts

Reverts the prefix on uuids
Apparently they should all be getstarted fro analytics
https://github.com/strapi/strapi/pull/24063

chore: revert uuid in examples

---

examples/getstarted/src/admin/preview/dummy-preview.jsx
packages/core/content-manager/admin/src/preview/utils/previewScript.ts

⚠️ this doesn't affect production users, it can be ignored for pre-release QA
Adds actual functionality into the preview script from #24111
- creates an overlay div over the whole page that doesn't affect user interactions
- tracks elements that have a data-source-strapi tag
- displays a "highlight" (blue box) on top of these elements. their position is dynamic, will react to scroll and resize events
- unregisters all its logic, listeners and observers so the script can be called multiple times safely
- handles double clicks on higlights (see console log)
- lets users customize the color of highlights via a window property
for live preview / visual editing
open a preview page in getstarted. hover elements that display strapi content. you should see the highlights. double click them and …

future: create preview overlay div with highlights

---

packages/core/content-manager/server/src/homepage/services/homepage.ts

This PR fixes the query that counts the number of published entries. 
The current implementation just adds 1 for each content type.
1. Spin up a clean Strapi instance and create some entries
2. Publish some entries, leave others in draft mode
3. Compare the number of published entries and the count in the front page widgets (see image below).
None (yet).

fix: wrong count for published entries in homepage widget

---

packages/cli/cloud/src/bin.ts
packages/cli/cloud/src/create-growth-sso-trial/action.ts
packages/cli/cloud/src/login/action.ts
packages/cli/cloud/src/services/cli-api.ts
packages/cli/cloud/src/services/context.ts
packages/cli/cloud/src/types.ts
packages/cli/create-strapi-app/src/cloud.ts

We updated the ContextCLI interface to include a new user field, allowing us to associate Amplitude events with the correct user context.
We were missing user data in Amplitude events. This has now been resolved by properly initializing the userId field.
1. Create a new project.
2. Log in.
3. Complete the onboarding steps.
4. Check amplitude
4.1. Locate your event (e.g. `didCreateGrowthSsoTrial`) 
4.2. Ensure that the event includes your user ID under the userId field
[JIRA CBA-1200](https://strapi-inc.atlassian.net/browse/CBA-1200)

Add the user ID to amplitude events

---

packages/core/content-manager/admin/src/pages/EditView/EditViewPage.tsx
packages/core/content-manager/admin/src/pages/EditView/components/Blocker.tsx
packages/core/content-manager/admin/src/pages/EditView/components/InputRenderer.tsx
packages/core/content-manager/admin/src/preview/components/InputPopover.tsx
packages/core/content-manager/admin/src/preview/hooks/usePreviewInputManager.ts
packages/core/content-manager/admin/src/preview/pages/Preview.tsx
packages/core/content-manager/admin/src/preview/utils/getSendMessage.ts
packages/core/content-manager/admin/src/preview/utils/previewScript.ts

Adds all the interactions we want to enable live/visual editing on Preview:
- highlighting elements matching the focused input in the preview
- double clicking on a highlight triggers a popover with the input for that field
- editing a field (both in side editor and in popover) reflects the changes in real time in the preview
⚠️ not handling nested fields yet, I'll look at that as part of the stega/encoding task
⚠️ not handling yet inputs that require more space than the popover offers, e.g. markdown
ℹ️ an e2e test suite and some contributor docs will come in separate PRs
Open any preview page in getstarted, click around, edit stuff

future: sync preview to side editor forms

---

packages/cli/create-strapi-app/src/create-strapi.ts
packages/cli/create-strapi-app/src/index.ts
packages/cli/create-strapi-app/src/prompts.ts
packages/cli/create-strapi-app/src/types.ts

Implement a new prompt in the CLI at then end asking if a user is interested in participating in A/B test.
If yes, we send an event to track the percentage of users interested and then take the decisiong to implement or not A/B tests.
To potentially propose A/B tests on the product so we can easily improve the product.
- Run the following command: `node packages/cli/create-strapi-app/bin/index.js`
- You should get asked to enable A/B test. By default it is false.
- An event should be sent.

chore: implement a new prompt to enable A/B test and track the event

---

packages/core/admin/server/src/services/token.ts
packages/core/core/src/providers/sessionManager.ts
packages/core/core/src/services/__tests__/session-manager.test.ts
packages/core/core/src/services/session-manager.ts
packages/plugins/users-permissions/server/services/jwt.js

To address https://github.com/strapi/strapi/pull/24133#discussion_r2304231650 in the base branch
```
// Admin (config/admin.js or .ts)
auth: {
secret: env('ADMIN_JWT_SECRET'),
options: {
algorithm: 'HS256',
// ...
},
},
});
// Users-permissions (config/plugins.js)
'users-permissions': {
config: {
jwtSecret: env('JWT_SECRET'),
jwt: {
algorithm: 'HS256',
// ...
},
},
},
});
```

feat: enhance JWT handling with configurable algorithms

---

packages/core/core/src/services/document-service/components.ts
packages/core/core/src/services/document-service/repository.ts
packages/core/core/src/services/document-service/utils/unidirectional-relations.ts
packages/core/database/src/index.ts

moves all components logic out of the database layer and into the document service
db layer should not be aware of strapi logic
see linked issue
Parent PR: https://github.com/strapi/strapi/pull/24227
Issue: https://github.com/strapi/strapi/issues/23858

fix: syncing components in draft and publish relations

---

SECURITY.md
examples/getstarted/src/api/address/content-types/address/schema.json
packages/core/content-manager/admin/src/pages/EditView/utils/data.ts
packages/core/content-manager/admin/src/pages/EditView/utils/tests/data.test.ts

Fixes an issue in v5.23.3 where deleted optional components reappeared after saving. Restores ability to save deletions correctly.
| Before fix | After fix |
| --- | --- |
| https://github.com/user-attachments/assets/d0b177d2-fff9-4489-995f-ba1673033e10 | https://github.com/user-attachments/assets/7966b6d1-d2c7-4a14-8dcc-cf805bc0ca03 |
Because it should be possible to remove optional components. Behavior in Strapi content manager was broken.
Fix https://github.com/strapi/strapi/issues/24315

fix: saving deletion of optional components not working

---

packages/core/admin/admin/src/features/Notifications.tsx
packages/plugins/i18n/admin/src/components/CreateLocale.tsx
packages/plugins/i18n/admin/src/components/EditLocale.tsx
packages/plugins/i18n/admin/src/components/tests/CreateLocale.test.tsx
packages/plugins/i18n/admin/src/components/tests/EditLocale.test.tsx
tests/e2e/tests/content-manager/cloning.spec.ts
tests/e2e/tests/content-manager/uniqueness.spec.ts
tests/e2e/tests/i18n/create-edit.spec.ts
tests/e2e/tests/i18n/editview.spec.ts
tests/e2e/tests/i18n/permissions.spec.ts
tests/e2e/tests/i18n/settings.spec.ts

Removes the notification title that was added by default to the text of notifications. We were adding the notification variant as the title, but it looked clunky, and that information is still visible via the color and the toast and the icon.
before:
after:
When the title is explicitly passed however, then it's still visible.
It was redundant, it looked clunky. @lucasboilly also wanted to remove it.
do anything that triggers a notification, e.g. updating an entry

enhancement: remove default notification title

---

packages/core/admin/ee/server/src/controllers/authentication-utils/middlewares.ts
packages/core/admin/server/src/bootstrap.ts
packages/core/admin/server/src/controllers/authentication.ts
packages/core/admin/server/src/services/constants.ts
packages/core/admin/shared/utils/session-auth.ts
tests/api/core/admin/session-manager.test.api.ts

- Fixes **SSO login flow** using the new session manager:
- Adds a **shared session/auth utils module**:
- SSO previously didn’t create a proper session/refresh token
1. Configure an SSO provider (e.g., GitHub/Google).
2. Login via SSO → check cookies:
- `strapi_admin_refresh` is present, with correct expiry (absolute/idle or session).
- `jwtToken` is present and usable in the Admin UI.
3. Verify refresh token rotation and logout clear cookies correctly.

[Session Manager] Fix SSO

---

packages/core/admin/server/src/controllers/__tests__/authenticated-user.test.ts
packages/core/admin/server/src/controllers/authenticated-user.ts
packages/core/admin/server/src/services/user.ts
packages/core/admin/shared/contracts/users.ts
packages/core/upload/server/src/controllers/__tests__/admin-upload.test.ts
packages/core/upload/server/src/controllers/admin-upload.ts
packages/core/upload/server/src/services/__tests__/ai-metadata.test.ts
packages/core/upload/server/src/services/ai-metadata.ts
packages/core/upload/server/src/services/index.ts
packages/core/upload/server/src/services/upload.ts
packages/core/upload/server/src/utils/index.ts

- moves the admin's getAiToken into a service (so we can retrieve the token from the upload plugin)
- create an aiMetadata service on the upload plugin with:
- isEnabled method: check if feature should be on
- processFiles method: takes files, sends them to the ai server, returns the metadata
- hooks the upload controller to this processFiles method.
- Check that getAiToken is not broken. For this, clear session storage, refresh and open the CTB chat.
- Upload an image from the media library page. Then click on the pen icon to edit its metadata. You should see the AI-generated caption and alt text already there
- Upload multiple files at once. Some that are images, some that are not. Only the images should get AI metadata. Make sure the metadata is for the right images
and do it again

future(upload): generate image metadata on file upload

---

packages/core/upload/server/src/controllers/__tests__/admin-upload.test.ts
packages/core/upload/server/src/controllers/admin-upload.ts
packages/core/upload/server/src/controllers/validation/admin/upload.ts
packages/core/upload/server/src/routes/admin.ts

Adds new route for bulk update.
Currently, the media library only allows updating files one by one. This new route makes it possible to update the file information for multiple files at once (bulk update).
Run the Strapi.
Log in with an authenticated admin user.
Call (you can use curl, Postman, or any other HTTP client):
POST /upload/actions/bulk-update
Authorization: Bearer <your-admin-token>
Request body:
{
"updates": [
{ "id": 3, "fileInfo": {"name": "img3", "alternativeText": "altText1", "caption": "capt3"}},
{"id": 4, "fileInfo": {"name": "img4", "alternativeText": "altText2"}}
]
}
Response:
[
{
"id": 3,
"documentId": "q2t1gpuss2h3s460gc5ufa7m",
"name": "img3",
"alternativeText": "altText1",
"caption": "capt3",
"width": null, …

AI media lib bulk update

---

.github/workflows/tests.yml

switch from bitnami/mysql to bitnamilegacy/mysql
our API tests are sometimes not able to run mysql, I believe because [Bitnami have deprecated the images](https://hub.docker.com/r/bitnami/mysql) causing docker to fail to find the image
This is a quick-fix until we move to a different image maintainer.

ci: use bitnamilegacy images for mysql

---

packages/core/core/src/providers/index.ts
packages/core/core/src/providers/session-manager.ts

Moves the assertion for admin.auth.secret to bootstrap instead of init
init is run on build, and the secret is not actually required for build. this causes errors on workflows where different env vars are passed in to build.

fix: assert admin.auth.secret on bootstrap instead of init

---

packages/core/content-type-builder/admin/src/components/AIChat/Chat.tsx

- Checks if we are in Production mode before rendering the CTB AI chat
- Chatbot should not be accessible in production mode, because no changes can be done to the CTB
- run the app with `NODE_ENV=production yarn start` 
- chatbot should not appear even when having a growth license

fix: don't render ctb ai chatbot in production mode

---

packages/core/upload/server/src/services/__tests__/ai-metadata.test.ts
packages/core/upload/server/src/services/ai-metadata.ts

As we found out in testing, `server.url` is not always provided, so `server.absoluteUrl` is the one that can be relied on. I found it by looking up what the startup terminal log used:

fix(upload): use absolute server url for file url

---

packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssets.tsx
packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/tests/CarouselAssets.test.tsx

If the media library field is disabled (e.g. the user doesn't have permission to edit the content), it should not display the edit button.
This aligns with the permissions given to the user. If a user can read the content without updating, they shouldn't be able to modify the media fields
1. Create a new permission and give them access to only read and publish a content type
2. Create a content type with the media fields as a part of the schema
3. Login using the user with the new permission and head to the content
4. You will find that field without the edit button
Before the fix:
After the fix:
Fixes #24262

fix(upload): disable the edit button on media input if disabled

---

packages/core/upload/admin/src/ai/components/AIUploadModal.tsx
packages/core/upload/admin/src/pages/SettingsPage/SettingsPage.tsx
packages/core/upload/admin/src/pages/SettingsPage/tests/SettingsPage.test.tsx
packages/core/upload/admin/src/translations/en.json

- Conditionally renders the media lib ai settings based on whether or not the app has ai available
- Updates the upload modal header text to:  'X assets uploaded, review AI generated metadata'
We shouldn't see ai related settings if there is no AI
With CE or an EE license that does NOT have AI 
Go to the settings page for media library
You should NOT see any settings related to AI
With a growth license or license with AI
You should see the AI settings

fix: ai settings show up for licenses without ai

---

packages/core/upload/admin/src/pages/App/MediaLibrary/MediaLibrary.tsx

closes #24256
I added an effect to watch for the change in `query.folder`. If the directory changes, the selection of the folders in the media gallery is restted and eventually the bulk actions buttons are hidden.
Because without it, if a user selected a folders/files then navigated to another folder, the bulk actions can be applied to the items added previously leading to potential troubles.
1. Open the media manager
2. Click the checkbox on a folder or an item, the bulk actions bar will appear
3. Change the directory
The bulk actions bar will be hidden.
Check the video on the first issue [here](https://github.com/strapi/strapi/issues/24256#issuecomment-3241890361)
#24256

fix: reset selection when folder changes to hide bulk actions
