strapi/strapi

lib/configuration/hooks/dashboard/config/config.js
Remove toJSON attribute from models in dashboard config controller
=> Remove toJSON attribute from models in dashboard config controller

lib/Strapi.js, lib/load.js, lib/restart.js, lib/server.js, lib/start.js, lib/stop.js
With ES5 native `Function.bind()` you can bind `this` context without using `lodash`
With ES6 arrow functions, the context `this` pass through the call chain, so there is no need to specify a reference to `this`.
**Note**:
Regarding lines https://github.com/wistityhq/strapi/blob/master/lib/Strapi.js#L41-L49 I don't think you even have to bind those functions, since they are already part of the `Strapi.prototype` when `Strapi` is called with `new`, all those functions will use `this` as the instance of `Strapi` by default.
**Note 2**:
Is this funciton used somewhere? https://github.com/wistityhq/strapi/blob/master/lib/start.js#L38
=> Use ES5 .bind() and ES6 arrow functions

packages/strapi-generate-new/files/config/environments/test/authentication.json, packages/strapi-generate-new/files/config/environments/test/databases.json, packages/strapi-generate-new/files/config/environments/test/security.json, packages/strapi-generate-new/files/config/environments/test/server.json
This PR adds `test` environment configuration files to `strapi-generate-new` package. This way, a `strapi new` command will generate an app with test configuration files.
Ref. #117.
=> Add `test` env config to `strapi-generate-new`

packages/strapi-cli/bin/strapi-migrate-make.js
This commit updates the `strapi-cli` package by removing extra backticks from `strapi-migrate-make.js`.
=> Remove extra backticks from strapi cli  

packages/strapi/lib/configuration/hooks/models/utils/index.js
`strapi.models.modelname.associations` contained only one association before because the array was reset on every call to `defineAssociations`.
=> fixed missing associations

packages/strapi-bookshelf/lib/index.js
the lifecycle methods fetched and fetching are not called when the user uses fetchPage or fetchAll in Bookshelf.js. Therefore I added these two mapping to be able to use the appropriate lifecycle methods for collections as well:
'fetching:collection': 'beforeFetchCollection'
'fetched:collection': 'afterFetchCollection'
=> Add beforeFetchCollection & afterFetchCollection lifecycle hooks

packages/strapi-admin/admin/src/components/LeftMenuHeader/index.js, packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js, packages/strapi-helper-plugin/lib/src/components/PopUpWarning/styles.scss, packages/strapi-plugin-content-type-builder/admin/src/components/PopUpWarning/styles.scss
- Center popUpWarning component
- Remove confirm button border-color
- Hide leftMenu content types section if there isn't any model
- Change `LeftMenuLinkContainer` component to stateless function instead of `React.Component`
- Same for `LeftMenuHeader` component
=> Center popupwarning and remove confirm button border

.github/CONTRIBUTING.md
There was a typo in CONTRIBUTING.md when you switched over from your old email address
=> fix: Contributing.md

packages/strapi/lib/Strapi.js
Addresses #162. Allow for the passing and using of a config json value when strapi starts instead of relying on preconfigured config values
=> Allow for overwriting of config in start

packages/strapi-generate-new/lib/after.js, packages/strapi-generate/lib/target.js
- Fallback to `process.cwd()` during module resolution in case of local installation
- Use full path to `strapi` binary, instead of global one
=> Fix local installation

packages/strapi-admin/admin/src/app.js, packages/strapi-admin/admin/src/containers/AdminPage/index.js, packages/strapi-admin/admin/src/containers/App/actions.js, packages/strapi-admin/admin/src/containers/App/constants.js, packages/strapi-admin/admin/src/containers/App/reducer.js, packages/strapi-admin/admin/src/containers/App/selectors.js, packages/strapi-admin/admin/src/containers/ListPluginsPage/saga.js, packages/strapi-plugin-users-permissions/config/roles.json
- Prevent plugins from being loaded if the 'users-permissions' plugin is present in the app and the user is not logged in
=> Fix loadOrder plugins in FIREFOX and SAFARI

packages/strapi-plugin-users-permissions/admin/src/components/Plugin/index.js
Auto open the Application's permission section (if the user has already created APIs) when editing a role
=> Improve UX when editing a role

packages/strapi-knex/lib/index.js
This is necessary option for ssl-only remote DB services e.g. heroku-postgres. This option can be set, as any other, in database.json file in 'settings' section.
=> SSL option for strapi-knex connections.

docs/3.x.x/en/SUMMARY.md
Reference to authentication was broken when its name was updated. Its fixed with correcting the filename.
=> Updates the Summary.md to refer to correct Authentication page

packages/strapi-generate-new/lib/before.js
The problem was in paths with backslashes on windows. The path.join() solved the problem.
=> strapi new connection config fail fix #476 #485 issues

packages/strapi-generate-new/lib/before.js, packages/strapi/bin/strapi-new.js
Stop project creation if one of db argument is missing
Better detection for using db arguments
=> Fix strapi new without db args

packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/styles.scss
Depending on screen resolution, when adding many content types the side
menu can't fit them all. This commit simply uses absolute positioning
and overflow-y: auto to allow vertical scrolling when it's needed.
=> Fix #660: Allow side menu to scroll when content requires it

packages/strapi-admin/admin/src/components/Logout/styles.scss
I think it makes sense not to capitalize the usernames.
Example: I see `Abdonrd` instead of `abdonrd`.
=> Avoid username capitalize

packages/strapi-admin/scripts/setup.js, packages/strapi-bookshelf/lib/utils/connectivity.js, packages/strapi-mongoose/lib/utils/connectivity.js, packages/strapi-redis/lib/utils/connectivity.js
Now the `npm run build --plugins` works for me in paths with spaces.
Also fix spaces path issues on databases. I'm not sure if something else is missing, because when I try `strapi new myDevelopmentProject --dev` use the `strapi-mongoose` from npm.
Fix #709.
=> Fix spaces path issues on npm run build --plugins

packages/strapi-mongoose/lib/utils/index.js
Also, sort types alphabetically.
You can see the two commits separately.
Reference: https://github.com/strapi/strapi/issues/784#issuecomment-373649898
=> Allow Array type in the backend

packages/strapi-plugin-content-type-builder/admin/src/containers/ModelPage/index.js
Add a notification if a user tries to edit a field in the content type builder plugin that it cannot currently handle.
For example the enumeration or the array field
=> Prevent the ctb from breaking 

docs/3.x.x/en/guides/models.md
Not sure if I understand the example correctly, but with the given config it does not work for me.
Shouldn't be the collection names the other way round?
=> (doc) fix collection name in many-to-many example

packages/strapi-plugin-settings-manager/admin/src/translations/en.json, packages/strapi-plugin-settings-manager/admin/src/translations/pl.json, packages/strapi-plugin-settings-manager/controllers/SettingsManager.js
While browsing through `./plugins/settings-manager/controllers/SettingsManager.js` I've found some issues with translation strings:
1. There was `request.error.environment.unknown` instead of `request.error.environment.unknow` (as in translation files). I corrected it.
2. There were no `request.error.database.unknow` string in translation files. I added lacking string and its translations to EN and PL files. Other files need updating.
=> Corrected and added "request.error.*.unknow" translations

packages/strapi-admin/admin/src/components/LeftMenuHeader/styles.scss
`center center` logo background position so that we don't have to use logos with a specific height and width.
=> Center logo

packages/strapi-generate-new/json/package.json.js, packages/strapi-generate-new/lib/after.js, packages/strapi-generate-new/lib/before.js, packages/strapi-generate-new/lib/index.js
This PR fixes some issues in development mode when we're creating a project with a SQL database.
- It auto-installs the right version of `strapi-knex` and `knex` when you're choosing a SQL database.
- It creates the symlinks to the global dependencies if you've setup the monorepo.
- It forces to install the dependency at the root of the project (to avoid the well-know knex issue)
- It installs the exact same version of `knex` than the `bookshelf` dependency.
=> Easily use MySQL project in development mode

packages/strapi-mongoose/package.json, packages/strapi-plugin-content-manager/config/queries/bookshelf.js, packages/strapi-plugin-content-manager/config/queries/mongoose.js
If you set a new value in the lifecycle function, it was always overridden due to the call of the update method to handle relations.
=> Fix beforeCreate lifecycle

packages/strapi/bin/strapi-start.js
Added a little check if `strapi start`runs inside a strapi project
Closes #481
=> check if `strapi start` runs inside a strapi project

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
My PR is a: 🐛
Avoid to delete duplicate permissions per role. Also fix #1134. And sort the Roles list by `name`.
=> Avoid to delete duplicate permissions per role

packages/strapi-bookshelf/lib/index.js
My PR is a:
🐛 Bug fix
Plugin
Update MySQL float data type from `float` to `double` to properly store large float values.
=> Update Strapi-Bookshelf to properly store long float values

packages/strapi-plugin-users-permissions/config/policies/permissions.js
My PR is an 💅 Enhancement
Main update on the: Plugin (strapi-plugin-user-permissions)
HTTP code which is returned when current user does not have enough permissions to perform an operation was changed from 401 (Unauthorized) to 403 (Forbidden) which is more suitable in this case.
=> Return HTTP 403 (not 401) if user is not allowed to perform an operation

docs/3.x.x/en/migration/migration-guide-alpha-10-to-alpha-11.md
My PR is a:
🐛 Bug fix
Documentation
For me, copying the files from the newly generated strapi environment was not sufficient. When I started the strapi after following the guide, 
I got the following error: 
```
/home/xxx/Dev/Projects/xxx/server/node_modules/mongodb/lib/mongo_client.js:804
throw err;
^
TypeError: Cannot read property 'globalId' of undefined
```
I guess this was the case because strapi-mongoose was not upgraded.  I don't know if I'm blind or did not read the migration guide carefully enough, but for me a `npm install` at the end did the trick and upgraded it.
Maybe this is helpful for you
=> Add npm install as last step of migration guide

docs/3.x.x/en/migration/migration-guide-alpha-11-to-alpha-12.md
My PR is a:
💅 Enhancement
Documentation
Since there are some issues with the release alpha.12 concerning the webpack build process, we should advise the user to upgrade to the latest alpha.12.x
=> Upgrade to latest alpha-12.x in migration guide

packages/strapi-plugin-graphql/services/GraphQL.js
My PR is a:
🐛 Bug fix
Plugin
Fix error type `Union type Morph can only include Object types, it cannot include [Enum name]`
=> Update Union type creation rules for GraphQL

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Plugin
We had issues with getting duplicate permissions when deployed on Heroku. It seems this logic was in the wrong order.
To reproduce the bug:
- Deploy a new project to Heroku (free dyno, really slow)
- Let it populate permissions
- Restart dyno
- You now have duplicate permissions
=> Fix clean up of duplicate permissions

packages/strapi-plugin-graphql/services/GraphQL.js
My PR is a:
🐛 Bug fix
Plugin
If I update the `shadowCRUD` setting to false, there is some bugs about the generation of the schema, independently of custom type, queries or another rules added.
=> Fix generate GraphQL schema if ShadowCRUD is false

packages/strapi-plugin-graphql/services/GraphQL.js
My PR is a:
💥 Breaking change
Plugin
To respect the openCRUD after talking with @Aurelsicoko, I update the fields about timestamp to follow the camel case logic for the naming of fields.
FYI: I indicate this PR as a `breaking change` because it will generate errors for people already using GraphQL if they don't update their requests.
=> Change names for timestamp fields in GraphQL plugin

packages/strapi-admin/admin/src/translations/de.json, packages/strapi-admin/admin/src/translations/en.json, packages/strapi-admin/admin/src/translations/fr.json, packages/strapi-admin/admin/src/translations/pl.json, packages/strapi-admin/admin/src/translations/ru.json, packages/strapi-admin/admin/src/translations/tr.json, packages/strapi-admin/admin/src/translations/zh-Hans.json, packages/strapi-admin/admin/src/translations/zh.json, packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
My PR is a:
- 💥 Breaking change?
- 💅 Enhancement
Admin
This PR fixes a typo in one of the error strings.
Unsure if thi will be considered a breaking change, maybe someone is working on translations and will miss this?
=> Fix a typo in the error key

packages/strapi-plugin-content-manager/config/queries/bookshelf.js
My PR is a:
🐛 Bug fix
Plugin
Little fix to change the verification of the data with `toJSON` (as it makes with the `create` function)
=> Fix toJSON verification inside bookshelf for content-manager

packages/strapi-plugin-graphql/services/GraphQL.js
My PR is a:
💅 Enhancement
Plugin
In order to follow the GraphQL spec, this PR add the flag `!` for a type when the field must be a non-nullable (because it's required).
=> Add `!` flag for GraphQL and non-nullable field

packages/strapi-generate-api/json/routes.json.js, packages/strapi-generate-api/templates/mongoose/controller.template, packages/strapi-generate-api/templates/mongoose/service.template
My PR is a: 💅 Enhancement
strapi-generate-api 
This PR is to add document count to mongoose templates
=> Add count route on generated API

docs/3.x.x/en/getting-started/installation.md
Need to use MongoDB >= 2.6 otherwise get wire version errors on start:
```
UnhandledPromiseRejectionWarning: MongoError: Server at 127.0.0.1:27017 reports wire version 0, but this version of Node.js Driver requires at least 2 (MongoDB2.6).
```
My PR is a:
💅 Enhancement
Documentation
Older versions of MongoDB (installed by default on many versions of Debian, Ubuntu, etc.) may cause Strapi to crash mysteriously on start.
=> Specify MongoDB >= 2.6

packages/strapi-plugin-content-manager/admin/src/containers/ListPage/index.js, packages/strapi-plugin-graphql/services/GraphQL.js
My PR is a:
🐛 Bug fix
Plugin
Remove Loadable import with `PopUpWarning` components that always keeps the `loading` state instead of being mounted.
FYI: it's the reason why we could see `Loading...` after the table in the list view of the `content-manager` plugin.
=> Fix content-manager build

packages/strapi-mongoose/lib/relations.js, packages/strapi-plugin-content-manager/services/ContentManager.js, packages/strapi-plugin-graphql/services/GraphQL.js, packages/strapi/lib/Strapi.js
Main update on the:  Framework
When deleting entry that have a manyToMany relation, the reference was not deleted in the other entry.
=> Fix delete relations manyToMany mongoose

packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js, packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
Main update on the:  Plugin
Fix loose info.mainField when update content type via content-type-builder
Related issue: #1301
=> Fix delete info.mainFied in content type builder

packages/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js
Main update on the:  Admin
During `strapi.load` we load middlewares and hooks, they can start process witch need app kill to end. (like watcher and other things) So when the `load` function is complete I force the end of the script.
=> Fix admin start

packages/strapi-plugin-graphql/config/settings.json, packages/strapi-plugin-graphql/hooks/graphql/index.js
My PR is a:
🚀 New feature
Plugin
Fix for #1392 
It add an option `playgroundAlways` to force the availability of the GraphQL Playground IDE, whatever the environment.
=> Add option to enable GraphQL playground anywhere

packages/strapi-mongoose/lib/index.js
My PR is a:
🐛 Bug fix
Framework
This PR fixes the SSL connection which is set as true whereas it shouldn't if the `DATABASE_SSL` environment variable is not set in production.
=> Fix ssl interpretation for Mongo connection

docs/3.x.x/en/advanced/customize-admin.md
My PR is a:
🐛 Bug fix
Documentation
Asked [by Slack](https://strapi.slack.com/archives/C0BNGCDNH/p1530292003000009)"
Te docs mention a `/admin/config/admin.json` file. Instead there is a `/admin/config/layout.json` ... There are equivalents? Is a bug in the docs or in the directory structure?
=> Fix filename reference

packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js, packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
My PR is a: 🐛 Bug fix
Not clear oneWay relation on model update.
Fix #1477
=> Fix loose oneWay relation on update content type

packages/strapi-admin/.gitignore, packages/strapi-admin/admin/.gitignore, packages/strapi-email-mailgun/.gitignore, packages/strapi-email-sendgrid/.gitignore, packages/strapi-email-sendmail/.gitignore, packages/strapi-generate-admin/.gitignore, packages/strapi-generate-admin/files/.gitignore, packages/strapi-generate-api/.gitignore, packages/strapi-generate-controller/.gitignore, packages/strapi-generate-model/.gitignore, packages/strapi-generate-new/.gitignore, packages/strapi-generate-plugin/.gitignore, packages/strapi-generate-policy/.gitignore, packages/strapi-generate-service/.gitignore, packages/strapi-generate/.gitignore, packages/strapi-helper-plugin/.gitignore, packages/strapi-hook-bookshelf/.gitignore, packages/strapi-hook-ejs/.gitignore, packages/strapi-hook-knex/.gitignore, packages/strapi-hook-mongoose/.gitignore, packages/strapi-hook-redis/.gitignore, packages/strapi-middleware-views/.gitignore, packages/strapi-plugin-content-manager/.gitignore, packages/strapi-plugin-graphql/.gitignore, packages/strapi-plugin-upload/.gitignore, packages/strapi-upload-aws-s3/.gitignore, packages/strapi-upload-cloudinary/.gitignore, packages/strapi-upload-local/.gitignore, packages/strapi-utils/.gitignore, packages/strapi/.gitignore
My PR is a:
💅 Enhancement
Plugin
I am sure this was intended was since line 118 of the main .gitignore has a wildcard match for yarn.lock - this is ignored as each package has it's own .gitignore file.
=> Include yarn.lock in packages .gitignore

packages/strapi-plugin-content-manager/admin/src/components/Search/styles.scss
My PR is a:
💅 Enhancement
Admin / Content manager
#1563 Hidding an useless scrollbar appearing in firefox
Don't know the CMS well yet, but I wanted to help, keep up the good work 👌
=> Fix search input extra scrollbar in Firefox

docs/3.x.x/en/configurations/configurations.md
My PR is a:
🐛 Bug fix
Documentation
Removes parameters related to Session in the database configuration parameters list.
=> Wrong database parameters

packages/strapi-plugin-users-permissions/controllers/Auth.js
If you try to login with non existing email or username, it will trigger error 500.
=> Check user exist before user is blocked

packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
BugFix in content-type-builder plugin service
My PR is a:
🐛 Bug fix 
Plugin 
i was getting below error during new content type save
```
TypeError: Cannot read property 'toJS' of undefined
at Object.appearance (/fakepath/api/plugins/content-type-builder/services/ContentTypeBuilder.js:101:71)
```
same error was on two places, it was caused by missing values in the immutable object so i added second parameter to empty List/Map.
=> Fix content type generation with bookshelf.

packages/strapi/lib/core/configurations.js
My PR is a:
🐛 Bug fix
Framework
----
`'server.proxy' || {}` is **always** returning `server.proxy`. The real intention is pass `{}` as default value for `_.get`.
=> Fix bug on conditional code

packages/strapi-hook-bookshelf/lib/index.js
... If aren't text colums definend in the schema do not lanch the SQL to create the fulltext index that generate the following SQL Error:
> Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
> ...
>  sql: 'CREATE FULLTEXT INDEX SEARCH_MY_TABLE ON `my_table` ()'
My PR is a:
🐛 Bug fix 
Framework strapi-hook-bookshelf with Relational DBs such as MySql
New pull request from #1845
=> Fix ORM Create FullText index error if no text colums founded

packages/strapi-plugin-settings-manager/admin/src/components/List/styles.scss
My PR is a:
🐛 Bug fix #1844 
Update of `strapi-plugin-settings-manager`
Update lanagues list label break on multi-line.
Center vertically label with flexbox and decrease line-height in order to increase render of language name.
=> Update lanagues list label breaked on multi-line.

packages/strapi-generate-new/files/config/environments/development/server.json, packages/strapi-generate-new/files/config/environments/production/server.json, packages/strapi-generate-new/files/config/environments/staging/server.json
My PR is a:
💅 Enhancement
Framework
Added the config options for the autoOpen option to the server.js configs by default on generation to make it easier to find and change.
Personally I think it should be disabled by default on development, on most environments it does not refresh the current tab and instead opens up a new one. Very frustrating when you are trying to add models using the content-type builder or directly editing files while the server is running. Every time it auto-restarts it opens a new tab.
@Aurelsicoko thoughts on this? If you agree we can disable it by default I'll push the change.
=> Add config options for AutoOpen by default

packages/strapi-plugin-content-type-builder/admin/src/containers/Form/index.js
My PR is a:
🐛 Bug fix #1897 
Update of the `strapi-plugin-content-type-builder`
Model name is camelCased only on input blur, a `getModelWithCamelCaseName` function has been added and is used for model object on form submission (create and edit) in order to prevent model name with whitespaces.
=> Fix model name with whitespace on keyboard content-builder form submission

docs/3.x.x/en/guides/authentication.md
My PR is an: 💅 Enhancement
This PR fixes the (required) URL used for password-resets via the REST-API. It also fixes some small typos and code-formatting.
=> Update docs to show correct password-reset URL and fix formatting

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
My PR is a:
🐛 Bug fix #985 
Update of `strapi-plugin-content-manager`
Remove `moveFocusToEnd` in order to prevent cursor which going to the bottom of the textarea when user put text in `bold`, `italic`, `line-through` or add `header`.
=> Remove moveFocusToEnd in addContent and addBlock WYSIWYG methods.

docs/3.x.x/en/configurations/configurations.md, packages/strapi-generate-new/files/config/environments/development/request.json, packages/strapi-generate-new/files/config/environments/production/request.json, packages/strapi-generate-new/files/config/environments/staging/request.json
My PR is a: 💅 Enhancement 
Actually we allow by default an router option `prefix` because it was possible by the router we use in Strapi. But it cause issues with Public files and Admin so we chose to remove the possibility to prefix all routes. 
Related issue #1323
=> Remove API prefix 

README.md
Hi 👋 
I really love Strapi and have been using it for a few months. I think you have all done a great job!
My PR is an:  💅 Enhancement
This took me ages of trial & error when I first started investigating Strapi. I nearly gave up several times because of my inexperience with both Strapi and Heroku. 
The only available instructions I found to be a bit difficult to follow (https://help.heroku.com/XOBUHLKQ/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository-when-using-heroku-git-clone).
I think this addition would help new adopters to get a more useful instance of Strapi running that would help them more easily evaluate the benefits of the content builder.
=> [Docs] Add instructions for cloning locally from Heroku

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
My PR is a:
🐛 Bug fix
Plugin
Fix warning for controlled input without onChange handler in WYSIWYG
=> Fix warning for controlled input without onChange handler in WYSIWYG

scripts/lint.js
According with @soupette , we need to prevent lint run in docs. 
My PR is a:
🐛 Bug fix
💅 Enhancement
Framework
No issue concerned, lint will not pass in doc files.
=> Prevent lint run in docs

packages/strapi-hook-bookshelf/lib/index.js
My PR is an 💅 Enhancement. See #1850 issue posted by @jbergstroem.
Main update on the package strapi-hook-bookshelf.
Add IF NOT EXISTS parameter for creating indexes in postgresql case to avoid this type message :  
> 2018-08-30 23:01:50.060 UTC [146] ERROR:  relation "search_users_permissions_permission_type" already exists
> 2018-08-30 23:01:50.060 UTC [146] STATEMENT:  CREATE INDEX search_users_permissions_permission_type ON "users-permissions_permission" USING gin(type gin_trgm_ops)
>
=> Add IF NOT EXISTS parameter for creating indexes with PG

packages/strapi-plugin-users-permissions/controllers/Auth.js
My PR is a:
🐛 Bug fix
Plugin
Step 1) Enable the email confirmation
Step 2) Signin with bad credentials on `/auth/local` POST
An 500 error comes up instead of the expected 400 response
```
TypeError: Cannot read property 'confirmed' of null
at callback (/usr/src/api/plugins/users-permissions/controllers/Auth.js:59:83)
```
Expected : 
```
{
"statusCode": 400,
"error": "Bad Request",
"message": "Identifier or password invalid."
}
```
=> Fix error 500 when user trying to signin with bad credentials

packages/strapi-admin/admin/src/components/LeftMenuFooter/index.js, packages/strapi-generate-new/lib/index.js
- Update link of version in leftMenuFooter : redirect now to changelog on github.
- Fix typo in strapi-generate-new.
My PR is a:
🐛 Bug fix
💅 Enhancement
Admin
Close #2197
=> Update link version in left menu and fix typo in strapi-generate-new

packages/strapi-plugin-content-manager/services/ContentManager.js, packages/strapi/lib/core/plugins.js
My PR is a:
🐛 Bug fix
Framework
The original implementation throws and runtime error if the `host` is
not defined making the conditional uselees.
Using a try/catch block is the correct implementation of the original
intention.
---
Proof:
=> Corrects conditional management plugin host

packages/strapi-utils/lib/models.js
My PR is a:
When content manager use deleteAll function, it send `0` as url query and it breaks convertParams function cause it's not a `string`.
=> Fix delete all

packages/strapi-plugin-users-permissions/config/queries/mongoose.js
My PR is a:
When user API fetch user, it sort on empty string and Mongoose fail the request `MongoError: $sort stage must have at least one sort key`
So I apply filters only if the key exist and is not empty.
=> Fix fetch user mongoose

packages/strapi-plugin-email/config/functions/bootstrap.js, packages/strapi-plugin-upload/config/functions/bootstrap.js
My PR is a:
Keep support of `strapi-email-*` and `strapi-upload-*` during few versions to let time to providers maintainers to make migration to `strapi-provider-email-*` and `strapi-provider-upload-*`.
=> Deprecated providers

packages/strapi-lint/lib/internals/eslint/front/.eslintrc.json, packages/strapi-lint/lib/internals/prettier/front/.prettierrc.js, packages/strapi-lint/lib/internals/prettier/index.js
This PR fixes eslint for the indent rule that wasn't working with inline conditions.
With the PR you should be able to run `npm run prettier` in the framework and pass the lint pre-commit hook.
My PR is a:
=> Fix eslint inline condition error

packages/strapi-generate-new/lib/index.js
I remove `.npmignore` from project generated files cause it's useless.
It make generated application cleaner.
Close #823
=> Remove .npmignore from generated files.

packages/strapi-plugin-users-permissions/config/layout.js
My PR is a:
The provider was not able to be added to the content manager schema to show in the list view, worked with @lauriejim to allow it to be shown.
=> Fix to allow provider to be shown in the content manager

.github/ISSUE_TEMPLATE/BUG_REPORT.md
My PR is a:
To hopefully help us debug issues, I've added a place in the bug template for users to provide a link to their Strapi project. This will hopefully allow us to clone and test ourselves and/or compare changes between their project and a fresh Strapi project.
=> Add a place for users to link their project in Issue Template

docs/3.x.x/guides/filters.md
change line 88 from "[...] returned objects is formatted [...]" to "[...] returned objects are formatted [...]"
My PR is a:
Fix spelling mistake in documentation, chapter filters, line 88 from "[...] returned objects is formatted [...]" to "[...] returned objects are formatted [...]"
=> Fix spelling mistake

docs/3.x.x/cli/CLI.md, packages/strapi-generate-new/lib/before.js, packages/strapi-hook-bookshelf/lib/utils/connectivity.js, packages/strapi-hook-mongoose/lib/utils/connectivity.js, packages/strapi/bin/strapi-new.js, packages/strapi/bin/strapi.js
My PR is a:
**TODO:**
Now when you are creating a new project in `--dev` mode, it use your local install of ORM you need to test the database connection (`connectivity.js` script). It will be more easy to develop code in the part of Strapi.
Some time errors are fired dureing the connection test to the database and error are not display (we force some specific messages). Now you can use `--debug` during your `strapi new` it will display the full error message. It will be usefull tu understand the issue you you have one.
=> Improve strapi new

docs/3.x.x/cli/CLI.md, packages/strapi-hook-bookshelf/lib/utils/connectivity.js, packages/strapi/bin/strapi-new.js, packages/strapi/bin/strapi.js
My PR is a:
When there is data already present in either Postgres or MySQL database, the `strapi new` command prompts with an interactive prompt to either proceed or abort.
This PR adds an `--dbforce` option, if present it proceeds with the creation of the project even if there's content already present in the database.
=> Add force option when database not empty with bookshelf

docs/3.x.x/guides/models.md, packages/strapi-hook-bookshelf/lib/index.js, packages/strapi-hook-mongoose/lib/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js, packages/strapi-plugin-content-manager/config/functions/bootstrap.js
My PR is a:
This PR adds the ability to change the default names for the timestamp columns. The current solution works with both the database hooks.
**Changes Made:**
The following packages were changed/updated in order to add this feature.
1. `strapi-hook-bookshelf`
2. `strapi-hook-mongoose`
3. `strapi-plugin-content-manager`
**How to defile the custom column names:**
In your model's `<modelName>.settings.json` add the following attribute in `options` object.
```javascript
{
"options": {
"timestamps": ["createdAt", "updatedAt"]
}
}
```
Here the first element of the array is associated with the create timestamp and the second element of the array is associated with the update timestamp.
The attribute accepts either `boolean` or `Array` of strings. If nothing is …
=> Custom timestamp column names in database

packages/strapi-generate-new/package.json, packages/strapi-hook-bookshelf/package.json
My PR is a:
As reported in the issue #1281 creating a new project hangs in the windows CLI.  Updating the inquirer dependency appears to resolve this.  I have tested this locally and it doesn't appear that inquirer is utilized extensively so I don't believe this will be a breaking change.
Closes #1281
=> Update inquirer version to resolve Windows cli hang

packages/strapi-plugin-users-permissions/services/Providers.js
My PR is a:
Fixes the parameters passed to the call to the `query` method in `user-permissions/services/Provider.js`. It specifies the symbol and value separately, instead of just passing a string.
=> Fix query building in user-permissions/services/Provider.js

packages/strapi-admin/admin/src/components/Logout/index.js, packages/strapi-admin/admin/src/containers/AdminPage/index.js, packages/strapi-admin/admin/src/translations/ar.json, packages/strapi-admin/admin/src/translations/de.json, packages/strapi-admin/admin/src/translations/en.json, packages/strapi-admin/admin/src/translations/es.json, packages/strapi-admin/admin/src/translations/fr.json, packages/strapi-admin/admin/src/translations/it.json, packages/strapi-admin/admin/src/translations/ja.json, packages/strapi-admin/admin/src/translations/ko.json, packages/strapi-admin/admin/src/translations/nl.json, packages/strapi-admin/admin/src/translations/pl.json, packages/strapi-admin/admin/src/translations/pt-BR.json, packages/strapi-admin/admin/src/translations/pt.json, packages/strapi-admin/admin/src/translations/ru.json, packages/strapi-admin/admin/src/translations/tr.json, packages/strapi-admin/admin/src/translations/zh-Hans.json, packages/strapi-admin/admin/src/translations/zh.json
My PR is a:
💅 Enhancement
Admin
In Logout component "Profile" and "Logout" strings were replaced with `<FormattedMessage />`. `app.components.Logout.profile` and `app.components.Logout.logout` translation keys were defined in all locale files.
=> Add intl support in logout component

packages/strapi-plugin-users-permissions/controllers/User.js
Fixes an issue when trying to update a user record when 'One account per email address' is turned on. The error was caused due to a mismatch in the router parameter (_id) and the parameter being used in the controller (ctx.params.id)
Closes #2631
=> Incorrect params variable name in user update

packages/strapi/lib/core/admin.js
Fix avoid write files if production mode
⚠️ Right now the `npm start` command is broken for `production` & `staging` environments.
=> Fix avoid write files if production mode

packages/strapi-hook-bookshelf/lib/index.js, packages/strapi-hook-mongoose/lib/index.js, packages/strapi-plugin-content-manager/config/functions/bootstrap.js
Timestamp key name was not send to the content manager to omit the correct keys during the update of one entry.
So I fix the way we give the correct information to the content manager.
=> Fix get timestamp in the admin

packages/strapi-plugin-content-manager/config/queries/bookshelf.js, packages/strapi-plugin-content-manager/services/ContentManager.js, packages/strapi-plugin-graphql/services/Loaders.js, packages/strapi-utils/lib/models.js
I fixed the SQL query that allows retrieving multiple entries through GraphQL, there was a bug when a oneWay relationship was null.
=> Fix SQL query where oneWay relationship is null

.github/PULL_REQUEST_TEMPLATE.md, packages/strapi-generate-api/templates/mongoose/service.template, packages/strapi-hook-mongoose/lib/index.js, packages/strapi-hook-mongoose/lib/relations.js, packages/strapi-plugin-content-manager/config/queries/mongoose.js, packages/strapi-plugin-email/config/queries/mongoose.js, packages/strapi-plugin-upload/config/queries/mongoose.js, packages/strapi-plugin-users-permissions/config/queries/mongoose.js, packages/strapi/lib/core/store.js
This PR removes the warnings we had when using Strapi with MongoDB. I followed the [deprecated  guide](https://mongoosejs.com/docs/deprecations.html) given by the Mongoose team.
=> Remove Mongoose warning logs

packages/strapi-hook-mongoose/lib/index.js
When you receive populated data, morph relations are omit and it's not good for media (images)
So now we auto populate morph relations. You will receive images.
=> Fix image populate

packages/strapi-hook-bookshelf/lib/index.js
This is a spin off of https://github.com/strapi/strapi/pull/2664 that only fixes the backend of bookshelf and doesn't add support for `big integer` on the frontend. Mongo wasn't checked as there was no existing code for big integer.
=> Fix Bookshelf big integer - backend only

docs/3.x.x/guides/deployment.md
The Docker [link](https://strapi.io/documentation/3.x.x/guides/deployment.html) had a typo at the end which sent users to Docker's 404 page instead of strapi page.
=> Docker link had a closing bracket at the end

packages/strapi/lib/utils/openBrowser.js
Catch error for auto open browser
Catch error for auto open Google Chrome with AppleScript
Fixes #2817
=> Catch error for auto open Google Chrome with AppleScript

packages/strapi-plugin-users-permissions/config/policies/permissions.js, packages/strapi-plugin-users-permissions/controllers/Auth.js
SQLite doesn't support boolean fields, so I replace strict check for enable type conversation
=> Fix for SQLite #2879

packages/strapi-generate-new/files/.npmrc
Forces NPM to disable automatic generation of the `package-lock.json` that can cause problems for projects cloned from Github or other Git related repos.
=> Forcefully disable package-lock generation

packages/strapi-plugin-users-permissions/controllers/Auth.js
When the route to confirm the email address is hited, if the token is wrong it fire a 500 error instead of a 400 error with a correct message.
=> Fix bad token for confirmation link

packages/strapi-plugin-users-permissions/controllers/Auth.js
When the email confirmation feature is enable, the jwt send in the response let the user able to valid his email.
so I remove the jwt from the response.
=> Remove token from register route if confirm email is required

packages/strapi-plugin-documentation/services/Documentation.js
Fix for UPPERCASE / camelCase names in "model" or "collection" field when generate documentation
=> Fix for UPPERCASE / camelCase names

packages/strapi-provider-upload-local/lib/index.js
the public folder path shouldn't be hard-coded, it needs to follow the "strapi.config.public.path" value.
I faced this issue on my current project where i have a custom path for the "public" folder for development, replacing:
```
path.join(strapi.config.appPath, 'public', `uploads/${file.hash}${file.ext}`)
```
with
```
path.join(strapi.config.public.path, `/uploads/${file.hash}${file.ext}`)
```
solved my problem, so i need to notify you on this issue.
=> The public folder path shouldn't be hard-coded in "strapi-provider-upload-local"

packages/strapi-plugin-graphql/services/Query.js
Fix convertParams that wasn't adding `_` in front of the params
=> Fix missing _ in the convertParams graphql queries

packages/strapi-generate-plugin/files/admin/src/containers/App/selectors.js, packages/strapi-generate-plugin/files/admin/src/containers/ExamplePage/selectors.js, packages/strapi-generate-plugin/files/admin/src/containers/HomePage/selectors.js
The front-end selectors for the generate-plugin package were trying to get an undefined key so which was breaking the admin.
- [] Plugin
=> Fix front-end generators plugin

packages/strapi-hook-bookshelf/lib/buildQuery.js
Fix the column name use for relations many to many.
=> Fix column name for many to many relations

packages/strapi-utils/lib/convertRestQueryParams.js
Set back the limit to 100 in rest queries
=> Set the fetch limit to 100 by default and add a default param

packages/strapi-plugin-graphql/services/Query.js
=> Fix missing populate in graphql queries

packages/strapi-hook-bookshelf/lib/index.js, packages/strapi-hook-mongoose/lib/index.js, packages/strapi-utils/lib/buildQuery.js
Filter on timestamps attributes was not available. 
So I restore the filters on these attributes
=> Fix filters on timestamp attributes

packages/strapi-generate-new/lib/index.js
Add  a .gitkeep file in the api folder to make sure we can deploy an empty strapi project via git
=> Add api and extensions gitkeep

packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
Remove not null on sqlite alter as the table is recreated afterwards
=> Remove not null on sqlite alter

CONTRIBUTING.md
This PR updates the CONTRIBUTING GUIDE to reflect the new development workflow.
=> Update the CONTRIBUTING GUIDE

packages/strapi-plugin-content-type-builder/controllers/ContentTypeBuilder.js
Fix model rename not using the right api name to persist files
=> Fix model rename not using the right api name to persist files

package.json
The version key in the root `package.jons` file is not necessary? We can remove it.
=> Remove version key from root package.json of the monorepo

docs/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.md
Add `extensions` folder creating step in the migration guide
=> Add missing migration step mkdir extensions

packages/strapi-plugin-graphql/services/Mutation.js
If we make delete **GraphQL** request, this 
```
policiesFn.push(
policyUtils.globalPolicy(
undefined,
{
handler: `${name}.${action === 'delete' ? 'destroy' : action}`,
},
undefined,
plugin
)
);
```
replace "delete" on "destroy". 
In the beta version it is not necessary 
**Note**: test **graphqlCrud.test.e2e.js / Delete Posts** does not see this bug, because as running under admin rights.
=> Remove graphql special condition for delete request

packages/strapi-helper-plugin/lib/src/utils/request.js
When strapi is behind a proxy (nginx) you will get a 502 which isn't right now and displays an error message
=> Add status code handler to health checks

packages/strapi/lib/Strapi.js
In the alpha version when using the module `dotenv` in the bootstrap.js file it would allow the use of process.env.VAR in the config files. This happened because the templateParsing of the json files was executed after requiring all the files and not on file load like it is now on beta. 
To reenable this behavior without involving other changes this PR ensures bootstrap.js is required (not executed) just after the initialization of Strapi. 
This will also allow more global package loading if necessary.
We will be thinking about adding native support for dotenv and revamping the whole configuration system in a future release
=> Requiring bootstrap.js before config loading

packages/strapi-provider-email-mailgun/lib/index.js
Mailgun has two api endpoints: api.eu.mailgun.net and api.mailgun.net (default). We should have possibility to configure it.
=> Mailgun: possibility to configure api host

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
When request to https://marketplace.strapi.io/plugins occurs a connection error, the `response` was `undefined` which cause app crash.
```javascript
getPlugins: (plugin, lang = 'en') => {
return new Promise(resolve => {
request(
{
uri: `https://marketplace.strapi.io/plugins?lang=${lang}`,
json: true,
headers: {
'cache-control': 'max-age=3600',
},
},
(err, response, body) => {
if (response.statusCode !== 200 || err) { // when connection error occurs, response was undefined
return resolve([]);
}
```
=> Fix crash caused by strapi-plugin-users-permissions

packages/strapi/lib/load/__tests__/check-reserved-filename.test.js, packages/strapi/lib/load/check-reserved-filename.js, packages/strapi/lib/load/load-config-files.js, packages/strapi/lib/load/load-files.js, packages/strapi/package.json
Fixes #3449 when starting an app with a different env than dev/prod or staging it broke because it didn't load correctly the env files in environments/*/
=> Allow different envrionment names on config load

packages/strapi-plugin-documentation/services/Documentation.js, packages/strapi/lib/Strapi.js
- Make sure to only use the right keys in the documentation file.
- Fix the extensions config merge strategy (only concat array for routes)
Fixes #3455
=> Only use keys from settings.json to create documentation files

docs/.vuepress/config.js
In the documentation **Blog** and **Slack** links in the header was not available.
So I added VuePress configurations to add them.
This PR fix #3559 issue
=> Fix doc header's link blog & slack

docs/3.0.0-beta.x/guides/filters.md, docs/3.0.0-beta.x/guides/graphql.md, docs/3.0.0-beta.x/guides/restapi.md, packages/strapi-hook-bookshelf/lib/buildQuery.js, packages/strapi-hook-mongoose/lib/buildQuery.js, packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js, packages/strapi-utils/lib/__tests__/convertRestQueryParams.test.js, packages/strapi-utils/lib/buildQuery.js, packages/strapi-utils/lib/convertRestQueryParams.js, packages/strapi/__tests__/filtering.test.e2e.js
This is working progress. @alexandrebodin ask me to open this, so he can help me on the development.
Knex (SQL) works. MongoDB not yet.
https://portal.productboard.com/strapi/1-public-roadmap/c/57-filter-on-null-value-in-the-generated-api
=> Add null and not null filters

packages/strapi-plugin-content-type-builder/admin/src/components/LeftMenuSection/styles.scss
Previously the lists in the Content Type Builder (e.g. Content Types
section) had bullet points still. This was hard to see as they're a
similar colour to the background behind them, but could be seen more
clearly when the page had enough content to enable scrolling.
This fixes that issue.
Previous behaviour:
=> Fix styling on content type builder left menu list

examples/getstarted/api/articles/models/Articles.settings.json, examples/getstarted/config/environments/development/database.js, examples/getstarted/exports/graphql/schema.graphql, examples/getstarted/package.json, packages/strapi-plugin-content-manager/services/ContentManager.js, yarn.lock
The PR #3356 introduced bugs when parsing booleans and numbers. I'm changing the strategy to use the parsed value correctly and only ignore it if the parsed value is a string.
Fix #3588
- [] Postgres
=> Fix content manager json parsing strategy

packages/strapi-plugin-users-permissions/package.json
`npm audit` is throwing some vulnerabilities coming from `koa2-ratelimit` package. Testing updating to the latest version `0.9.0`
=> Update koa2-ratelimit to latest version

packages/strapi-hook-bookshelf/lib/relations.js
The updates on relation were executed in concurrency with the update of the model data. This should cause issue at first sight but some of the relational updates clear some of the main model columns for certain relations (e.g https://github.com/strapi/strapi/issues/3565) 
This Fix should probably fix quite a few issues we have add with relations not appearing randomly (image upload for example)
Fixes https://github.com/strapi/strapi/issues/3565
=> Force relationnal updates to be done before main model update

docs/3.0.0-beta.x/advanced/customize-admin.md
Hello. I am currently working on Strapi. After migrating from alpha to beta version, we do not have `admin` directory anymore. I wanted to customize some styles of Admin panel, but the beta documentation does not provide it in details. Therefore, I would like to update it based on my figured solution, it would help beginners in the same case.
fixes #3604
=> Update customize-admin in beta documentation

packages/strapi-generate-new/lib/resources/json/database.json.js
When generating a new strapi application the database.json file generated for `production`and `staging` didn't contain the connector field.
Fixes #3600
=> Fix missing connector in generated database.json files

packages/strapi-plugin-graphql/services/Query.js
This issue fixes #3648 If no limit is provided and `amountLimit` is set it still sends default 100 records. After this fix, if amountLimit is set to 20 it will only return 20 records
Ready for merge
=> Fix graphql amountLimit must be used when no limit is provided

packages/strapi-plugin-users-permissions/config/schema.graphql
The schema for GraphQL in the users-permission plugin was forcing the use of `_id` instead of the database agnostic `id`.
=> Fix graphql me query on sql databases

packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js, packages/strapi-plugin-content-manager/services/utils/configuration/index.js, packages/strapi-plugin-content-manager/services/utils/configuration/settings.js
Group mainField (field displayed in the editView on top of a collapsed group) should not be the id if there are valid attributes to display
=> Set group default mainField not id unless no attributes

packages/strapi-hook-knex/lib/index.js
Hey. I noticed that the property name for socketPath from config is mapped to the wrong name before initializing Knex connection. Because of it I could not deploy app to google app engine and use mysql database.
My PR is a:
=> Fix socketPath connection setting's variable name

docs/3.0.0-beta.x/configurations/configurations.md, docs/3.0.0-beta.x/guides/models.md, packages/strapi-hook-bookshelf/lib/mount-models.js, packages/strapi-hook-bookshelf/package.json
~~Adding bookshelf-uuid to generate UUIDs for MySQL as it doesn't have a simple way to generate UUIDv4 IDs.~~
Generic loading of bookshelf plugins like `bookshelf-uuid` support
=> Add support for bookshelf plugin loading

packages/strapi-helper-plugin/lib/src/components/GlobalPagination/index.js
Added `1` as a default return value for our `getLastPageNumber` method. If the result of `Math.Ceil` returns `0` and we know that when there is no items we shouldn't be able to navigate between pages and since `0` evaluates to false, we can use the or logical operator and return `1` as our last page.
=> Infinite pagination when count is zero fix

packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
Fixes `Make you sure you understand` to `Make sure you understand`.
=> Fix typo in en.json

packages/strapi-hook-mongoose/lib/index.js
Added support for connection setting useUnifiedTopology so it can be positioned via the database.json file in strapi project. By default it is positioned to false.
If this is not set and you are connecting to a mongo db v4.0.x using the beta-16.1 and higher version of the strapi-hook-mongoose you will get the following warning message when starting the strapi server:
DeprecationWarning: current Server Discovery and Monitoring engine is
deprecated, and will be removed in a future version. To use the new Server
Discover and Monitoring engine, pass option { useUnifiedTopology: true } to
the MongoClient constructor.
=> Connect to mongo db 4.0.x using mongoose 5.7.0

docs/3.0.0-beta.x/guides/models.md
Fix typo from `create data` to `create date`.
=> Fix documentation typo

packages/strapi-plugin-content-manager/controllers/validation/model-configuration.js
Allow group mainField and defaultSortBy to be id
Fix https://github.com/strapi/strapi/issues/3969
=> Allow group mainField and defaultSortBy to be id

packages/strapi-hook-bookshelf/lib/mount-models.js, packages/strapi-plugin-content-manager/test/types/json.test.e2e.js
Add support for json array : `[{"key": "value"}]` to pg
Fix https://github.com/strapi/strapi/issues/2882
=> Stringify json input for pg to support arrays

docs/3.0.0-beta.x/guides/graphql.md, packages/strapi-plugin-graphql/services/Mutation.js, packages/strapi-plugin-graphql/services/Query.js, packages/strapi-plugin-graphql/services/Resolvers.js, packages/strapi-plugin-graphql/services/Schema.js
Old deprecated PR: https://github.com/strapi/strapi/pull/3881
Fixes three issues as outlined in this issue:
fix #3880 fix #2766 
Issue 1: Inaccurate Documentation on GraphQL Policies
Issue 2: Policies not triggering for custom Mutations
Issue 3: Policies don't have `ctx.state.user`
=> Graphql policies fix

examples/getstarted/api/menu/models/Menu.settings.json, examples/getstarted/api/menusection/models/Menusection.settings.json, packages/strapi-plugin-graphql/services/Mutation.js, packages/strapi-plugin-graphql/services/Schema.js, packages/strapi-plugin-upload/package.json, packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js, packages/strapi-plugin-upload/test/upload.test.e2e.js, packages/strapi-plugin-users-permissions/config/schema.graphql, packages/strapi-plugin-users-permissions/controllers/User.js, packages/strapi-plugin-users-permissions/test/graphql.test.e2e.js
Fix https://github.com/strapi/strapi/issues/4035
=> Fix graphql plugin resolverof

packages/strapi-admin/package.json
Webpack v4.40.0 had a bug that caused a create to fail with this error:
```
Error: Conflict: Multiple assets emit to the same filename
```
This ups the minimum version constraint to v4.40.1.
Ref #3981 Closes #3982
=> Update minimum webpack version for strapi-admin

packages/strapi-generate-new/lib/create-project.js
=> Use stderr instead of message

packages/strapi-hook-mongoose/lib/relations.js, packages/strapi-plugin-graphql/services/Resolvers.js
Fixes: #4109 
Fixes possibility to set null values for manyToMany and manyWay relation types.
=> Allow null values on manyToMany and manyWay to set empty array

packages/strapi-admin/admin/src/components/PluginCard/index.js
Updates the url of the settings button for Content Manager PluginCard. This PR fixes the bug reported in #4104.
The PR is ready to merge.
=> Updates the url of the settings button for Content Manager PluginCard

packages/strapi-hook-ejs/lib/index.js
Default `ejs` hook configs are not used.
Strapi only send `strapi.config.hook.settings.ejs` that represent hook config in the app.
And the `root` option is managed in default settings of the hook.
=> Fix default config usage ejs

packages/strapi-admin/admin/src/containers/LocaleToggle/index.js, packages/strapi-admin/admin/src/containers/LocaleToggle/tests/index.test.js
China uses Simplified Chinese (zh-Hans) instead of Traditional Chinese, so I changed the flag.
Most websites use the national flag of Taiwan (ROC) as a Traditional Chinese icon.
=> Change Traditional Chinese flag in LocaleToggle

packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js
This will leave date types with default null except for created_at and updated_at. this isn't ideal for now because we still set any timestamp with a default time but it isn't a user interface field and will be changed later on
Fix #2300
Replaces the PR #4019
=> Do not set default timestamp value for date types

docs/3.0.0-beta.x/guides/graphql.md
I don't think installing the documentation plugin will install graphql
=> Fix typo in graphql plugin documentation

README.md
In this PR I remove the Heroku button.
This button doesn't make sense.
The power of Strapi is the let you create your content types and then contribute you content and then offer you and API to consume your data where you want.
But in Heroku you can't create/update/remove content type. You can't do the first steps.
So please if you want to use Heroku to deploy your app, you will have to follow the [Heroku deployment documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku).
=> Remove Heroku button

packages/strapi-plugin-graphql/services/Loaders.js, packages/strapi-plugin-graphql/services/Resolvers.js
Might Fix https://github.com/strapi/strapi/issues/4080 it needs testing by @JelmerV-WFC
=> Improve graphql perf

packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js
=> fix images not respecting configurable being set as false

packages/strapi-plugin-graphql/services/Query.js
Fix #4116
this PR replaces https://github.com/strapi/strapi/pull/4159
=> Pass graphql full context to custom queries

packages/strapi-plugin-content-type-builder/controllers/Groups.js
Fix issue #4138 - Cannot remove default value for number type in group.
Fixed by converting the zero-length string that is being submitted (from the frontend) to undefined.  This removes the default attribute and it then doesn't fail the validation checks as per issue #4138.
=> Allow empty default on group attributes

packages/strapi-plugin-graphql/services/Resolvers.js
=> Check if many-many relation is populated before loading it

packages/strapi-plugin-graphql/services/Query.js
=> Fix multiple query in one graphql request

packages/strapi-generate-api/templates/bookshelf/controller.template, packages/strapi-generate-api/templates/bookshelf/service.template
Updated the documentation links in the service and controller templates to point to the changed links
=> Update template links in services/controllers to new doc pages

packages/strapi-plugin-email/config/functions/bootstrap.js, packages/strapi-plugin-upload/config/functions/bootstrap.js
When the provider load has been re-write, providers scoped in an npm originazation was no more loaded.
Due to `startWith` that is too restrictive. So I changed to `includes` to also manage is the provider is scoped.
Related to #2723 pinged by @greatwitenorth
=> Load scoped providers

packages/strapi-hook-mongoose/lib/mount-models.js
In case that any Lifecycle pre callback returns Promise.reject it will be caught by Admin UI showing error banner.
It allows custom validations with Lifecycle callbacks as well
Admin UI will show saving process without it in case of error inside Lifecycle callback just writing error message in log.
=> Lifecycle pre callbacks can be cancelled

docs/3.0.0-alpha.x/guides/filters.md
Tiny update to the documentation for 3.0.0-alpha:
In the Filters section is stated that you need to use `_limit=-1` to get the full data set, but in fact it is `_limit=0`
=> Use limit=0 to require full data set

packages/strapi-admin/controllers/Auth.js, packages/strapi-plugin-users-permissions/controllers/Auth.js
=> Fix security issue with reset password

.github/ISSUE_TEMPLATE/SECURITY.md, docs/SECURITY.md
Added Security page for reporting vulnerabilities directly to Strapi via email or slack.
It's likely the email address will need to be changed as it probably doesn't exist.
=> Add security and vulnerability reporting page

packages/strapi-generate-new/lib/resources/json/database.json.js
Some options provided in the staging and production template would break knex from connecting due to it throwing errors instead of ignoring keys it doesn't support.
=> Clean up template and remove keys that would break bookshelf/knex

docs/3.0.0-beta.x/plugins/users-permissions.md, packages/strapi-plugin-users-permissions/config/routes.json, packages/strapi-plugin-users-permissions/controllers/Auth.js, packages/strapi-plugin-users-permissions/documentation/1.0.0/overrides/users-permissions-User.json
Add POST route /auth/send-email-confirmation to call sendEmailConfirmation function of plugin users-permissions.
In case the user didn't received the confirm email, this function trigger a new call, based on the email given.
This feature send a badRequest in case of null email, wrong email, or if user has already been verified.
=> Add POST route /auth/send-email-confirmation

packages/strapi-generate-new/lib/create-customized-project.js
When a database connection fails, the CLI proposes a retry.
If you succeed to connect to the database during this retry, the database information is written in the `./config/environments/development/database.json` is the info of the first try.
So it means it's the wrong info.
This PR fix that to use the last successful try info.
=> Write the correct database configuration

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Fix #4511 
In UsersPermissions bootstrap function, we are using the query builder to retrieve roles, it autopopulates permissions and users by default, which slow down the start of strapi when there is a big number of users or permissions in database.
=> Retrieve roles without populating users and permissions relations

docs/3.0.0-beta.x/concepts/services.md
Related PR: https://github.com/strapi/strapi/pull/4530
Similar to the linked PR there were references to `{ model }` in the service docs. This has been adjusted to match the controller docs using the `restaurant` model as an example.
=> Clarify usage of model in create and update examples

packages/strapi-admin/index.js
Unable to hot reload when save file when --watch-admin [#4532](https://github.com/strapi/strapi/issues/4532)
Linux or MacOS is using `/`
and Windows is using `\`
to fix this bug.
=> Fix hot reload bug on Win 10

docs/3.0.0-beta.x/concepts/configurations.md
Resolves #4567
Fixed the indentation of database configuration documentation.
=> Fix misleading database configuration documentation

packages/strapi-admin/controllers/Admin.js
=> Validate plugin name

packages/strapi-hook-bookshelf/lib/queries.js
Columns are now wrapped in `coalesce` before joining the tsvectors because a single NULL would result in the entire tsvector being NULL. This used to result in unexpected behaviour where a single NULL would disable searching for relations in the content-manager when using postgres as the backend.
=> Wrap tsvector attributes with coalesce before join

packages/strapi-admin/admin/src/containers/LanguageProvider/reducer.js
Previously admin panels language defaulted to Arabic if browsers preferred language was not supported. 
I think it definitely should be English, so I changed that.
=> Change admin UI's default language to English if browser's preferred language is not found

packages/strapi-plugin-documentation/services/Documentation.js
Fix the access to the `config.description` if the `config` key not exist.
=> Fix documentation generation when route has no config

docs/3.0.0-beta.x/concepts/models.md
There is a typo in Many-to-Many Relationship section. It should be `Many-to-Many` instead of `One-to-Many`.
=> Fix typo in documentation of Many-to-Many relationship in model.md

docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Added tabs for mongoose and restructured a bit (Moved comp/groups to the end to make the CSP and root pages changes clear for those that aren't using comp/groups)
=> Beta.18.x migration guide add mongoose tabs

docs/3.0.0-beta.x/concepts/configurations.md
Added example link to php standard timezones for use with the database config option for timezone.
=> Add database timezone config options to documentation

packages/strapi-plugin-content-type-builder/admin/src/InjectedComponents/ContentManager/EditSettingViewButton.js, packages/strapi-plugin-content-type-builder/admin/src/InjectedComponents/ContentManager/EditViewLink.js
This PR removes the injected links components in the content manager when the user is not in development environments as it might be confusing for the user. The content builder is still in read only in these environments.
=> Remove content builder links from content manager in non development environments

packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/reservedNames.js
This PR prevents a user from creating a content type called either `map` or `series` in the ctb as it can break their project.
fix #4875 
fix #4470
=> Add map and series to RESERVED_NAMES in CTB

docs/3.0.0-beta.x/concepts/policies.md
Added a link in the concept/policy documentation to the related GraphQL policy docs to clarify you need to edit the schema.graphql file to enable policies for GQL routes (Mutations as an example)
=> Update policies documentation to include link to GraphQL doc

docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md
Fix some grammar for the migration guide from beta.17.x to beta.18.x
=> Fix a few grammar mistakes on beta.18.x migration guide

packages/strapi-admin/controllers/Auth.js, packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
Remove soft hypen (https://graphemica.com/00AD) from the reset password email subject lines. It's not visible in the browser, but appears in my IDE as well as in Outlook or other non-browser-based email clients.
=> Remove soft hyphen (U+00AD) from reset password email subject line

packages/strapi-connector-mongoose/lib/mount-models.js
Fix #5129 
Check if `ref` is set before calling toJSON to prevent doing toJSON on a null object.
=> Check if ref is set before checking toJSON

docs/3.0.0-alpha.x/getting-started/introduction.md, docs/3.0.0-alpha.x/getting-started/quick-start-tutorial.md, docs/3.0.0-alpha.x/getting-started/quick-start.md
Adding warning messages to new users not to use the Alpha version. Based on feedback the deprecated notice at the top of the docs didn't quite get the point across.
=> Add warning messages to Alpha docs

packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js, packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js, packages/strapi-plugin-content-type-builder/admin/src/translations/en.json
This PR fixes the relation target name by preventing the user from creating a relation with a target attribute name that is already taken.
Fixes #3914
=> Fixes #3914

packages/strapi-connector-mongoose/lib/index.js
When a connection is open with Bookshelf we can access the Knex instance via `strapi.connections.default` and that lets you execute custom SQL queries.
Here is the code line https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/knex.js#L227
But this not happen with Mongoose. This PR just apply the same logic to be able to execute custom requests to the MongDB database.
This PR will close #5199
=> Expose mongoose connections

docs/3.0.0-beta.x/concepts/requests-responses.md
These paths to body and files differ from Koa's typical pathing, adding them to the docs temporarily until the docs are reworked.
=> Added information about body and files to request docs

packages/strapi-plugin-content-manager/services/utils/store.js
Now Strapi rewrite all 'plugin_content_manager_configuration_content_types' keys in "core_store" database table on each restart.
I add comparison of stored config with generated, and skip unnecessary write config to database, when there are no changes.
fixes #5367
Signed-off-by murznn@gmail.com
=> Fix #5337 - suppress rewrite config in db without changes

packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
Bugfix: don't show unique attribute for rich text fields
fixes #5305
My PR is a:
🐛 Bug fix
Admin
Manual testing done on the following databases:
MongoDB
=> fix: don't show unique attribute for rich text fields #5305

packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
Currently, when you add a value to a numeric field, there is no way to reset that value; after saving it, the backend will set it to 0.
This is because an empty string is being sent to the backend, and it parses it as zero. This PR explicitly sends null when leaving a numeric field blank, so that the backend interprets it correctly.
=> fix(EditViewDataManagerProvider): allow to reset number input

packages/strapi-admin/admin/src/components/GlobalStyle/index.js, packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/MenuSection.js, packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/Wrapper.js, packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js, packages/strapi-admin/admin/src/components/LeftMenuLinkSection/LeftMenuListLink.js, packages/strapi-admin/admin/src/components/LeftMenuLinkSection/index.js, packages/strapi-admin/admin/src/containers/LeftMenu/Wrapper.js, packages/strapi-plugin-content-manager/admin/src/components/SelectMany/components.js
This PR contains 3 different things I did in Admin UI
1. Fit Left menu items to available space.
With strapi@beta.18.9 I found that content type has max-height which looks good on small screens, but on FHD it makes dificult to use. With this commit I allow sections to grow/shrink depends on available space. 
2. Added custom scrollbars (different for light and dark app sections). Default scrollbars are just to big, especially in Left Menu and small sections like relations in entry view.
3. added scrollbar to many relation list in entry view.
Ad. 2 & 3. Scrollbar colors may be different. I'm waiting for suggestions
Some screenshots:
**Menu Before**
Short
**Menu After**
short
**Scrollbars Before**
**Scrollbars After**
**Relations list in entry view - before**
**Relations list in entry view - …
=> Fit Left menu + scrollbars

docs/.vuepress/config.js, docs/3.0.0-beta.x/guides/count-graphql.md
This PR adds a Guide to the docs.
Some people from the community asked about `count` function in GraphQL.
Aggregation is not working well and is not available for every database, this guide let you understand how to add custom GraphQL query, in this case, a `count` query.
=> Add count GraphQL guide

packages/strapi/lib/Strapi.js
Strapi does not the host value in the configuration when launching the server currently. Therefore, Node server listens on all interface when host value is omitted. This causes a problem when the user has other applications that run on the same port but different interfaces. 
Fix #5399.
=> fix #5399 Strapi is not using the configured host when launching the server

docs/3.0.0-beta.x/cli/CLI.md
Not sure if you want to call-out that it will leverage yarn if/when possible (if npm flag is not set).
Did notice other APIs need an update, but unsure how `---tpl` relates to new cli. I assume it's been refactored into `--extend`, but unsure.
=> Add --no-run and --use-npm to CLI docs

packages/strapi-admin/admin/src/containers/App/reducer.js, packages/strapi-admin/admin/src/containers/App/tests/reducer.test.js, packages/strapi-admin/index.js
This PR uses the version from the `package.json` to display the `built` version in the left menu. This PR will let users know if they have updated their administration panel correctly.
=> Display version from package.json in left menu

packages/strapi-connector-bookshelf/lib/mount-models.js, packages/strapi/lib/Strapi.js
=> Change error message when bookshelf db connection fails at start

packages/strapi-plugin-content-manager/test/dynamiczones/with-media.test.e2e.js, packages/strapi-plugin-content-type-builder/controllers/ContentTypes.js, packages/strapi-plugin-content-type-builder/controllers/validation/relations.js, packages/strapi-plugin-content-type-builder/services/schema-builder/index.js, packages/strapi-plugin-graphql/services/type-builder.js, packages/strapi-plugin-graphql/services/type-definitions.js, packages/strapi-plugin-graphql/test/graphqlRelations.test.e2e.js
=> add possibility to set a relation "private"

docs/3.0.0-beta.x/installation/digitalocean-one-click.md
Per PR https://github.com/strapi/one-click-deploy/pull/6 there will be some changes, please don't merge until after me and @pierreburgy have talked with DigitalOcean about changing the image for the marketplace.
=> Update DigitalOcean one-click docs for recent changes

packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/Wrapper.js
Hello There!
I was following the tutorial and realize that variable names are capitalized, which is a bit misleading.
So thought of removing that.
=> removed text-transform from variable name

packages/strapi-plugin-graphql/services/resolvers-builder.js, packages/strapi-plugin-users-permissions/test/graphql.test.e2e.js
Fix #5531 issue. Make `policiesMiddleware` works in custom resolvers too.
=> Fix context issue in custom GraphQL query and mutation

docs/3.0.0-beta.x/concepts/services.md
- Update the documentation:
Find little syntax error and fix it.
=> Fix little syntax error

packages/strapi-plugin-users-permissions/config/policies/permissions.js
Users-permissions plugin was throwing an extra `strapi.log.error` instead of just letting handleErrors deal with it.
Removed
=> Remove extra logs in users-permissions

packages/strapi-connector-mongoose/lib/queries.js
This PR should fix #5577. This only changes `strapi-connector-mongoose` and should be ready to be merged.
=> Make UID searchable in Mongoose and avoid errors if content type can't be searched

packages/strapi-provider-email-amazon-ses/lib/index.js
What:
- change the priority so that we use custom values first, and fall back to defaults if customs are not provided.
Why:
- as there is a default hardcoded value in `options.from` (originating here: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/controllers/Auth.js#L327), the custom email plugin settings would never be used.
=> Fix the order of settings in ses provider

packages/strapi-plugin-users-permissions/config/schema.graphql.js, packages/strapi-plugin-users-permissions/controllers/Auth.js
In regard to: https://github.com/strapi/strapi/issues/5524
- Added missing forgotPassword, changePassword and emailConfirmation mutations/resolvers. 
- Made a slight adjustment to the emailConfirmation controller function in Auth.js to return a UsersPermissionsLoginPayload when using GraphQL
=> Added missing forgotPassword, changePassword and emailConfirmation mutations/resolvers

packages/strapi-generate-api/json/routes.json.js
=> don't generate default routes when generating plugin api

packages/strapi-admin/admin/src/translations/de.json
"Terms and Conditions" are called "Allgemeine Geschäftsbedingungen" in German (often abbreviated as "AGB") or "Nutzungsbedingungen".
In the context of the admin sign-up of 'strapi' I'd go for the latter.
(Research results attached to the pull request)
The previous version "Begriffe" is wrong in this context as it is the literal translation of the word "term".
=> Translations: Updated the 'terms' translations for 'de'

packages/strapi-plugin-users-permissions/config/schema.graphql.js
=> Fix checkBadrequest useless logic in user-permissions' graphql config

packages/strapi-plugin-graphql/services/build-aggregation.js
I discovered a bug that filters conditions aren't applied to `groupBy`.
Original's `filters` are raw GraphQL's filters object, eg:
```filters = { limit: 100, start: 0, where: { country: "France" } }```
We need convert it to Strapi's ORM filter object, eg 
```filters = { _limit: 100, _start:0, where: [ { field: "country", operator: "eq", value: "France" } ] }```
=> fix: GraphQL Aggregation Bookshelf `where` condition aren't applied to groupBy

docs/3.0.0-beta.x/guides/deployment.md
There was a problem in Heroku when using the default "localhost". We must change it to "0.0.0.0". We can help others by adding this to the documentation so they don't have to invest much time to find the solution like me.
=> Added 0.0.0.0 to Deployment Configuration Doc

packages/strapi-plugin-content-manager/admin/src/containers/Initializer/index.js, packages/strapi-plugin-upload/admin/src/components/EditForm/index.js, packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/index.js, packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/init.js, packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/reducer.js, packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/tests/init.test.js, packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/tests/reducer.test.js, packages/strapi-plugin-upload/admin/src/components/SortPicker/index.js, packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js, packages/strapi-plugin-upload/admin/src/containers/Initializer/index.js, packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js, packages/strapi-plugin-upload/admin/src/index.js, packages/strapi-plugin-upload/admin/src/utils/getFileModelTimestamps.js, packages/strapi-plugin-upload/admin/src/utils/index.js, packages/strapi-plugin-upload/admin/src/utils/tests/getFileModelTimestamps.test.js
This PR improves:
- the filtercard by retrieving the timestamps directly from the plugin's model
- add the timestamps to the sort component
- fix the isMounted in the homepage
- Prevents from replacing a file with a one that has a different type
- Prevents from cropping a GIF
=> Allow only same type when replacing asset

packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js, packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js, packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js, packages/strapi-plugin-content-type-builder/admin/src/translations/en.json, packages/strapi-plugin-content-type-builder/controllers/validation/common.js, packages/strapi-plugin-content-type-builder/controllers/validation/types.js, packages/strapi/lib/services/entity-validator/validators.js
Signed-off-by: yacir dev.yassir@gmail.com
FIX #1493
WIP: If it LGTY, translations should be added before merge.
=> Add RegExp as text type attribute validation option

packages/strapi/lib/services/__tests__/entity-service.test.js, packages/strapi/lib/services/__tests__/entity-validator.test.js, packages/strapi/lib/services/entity-validator/index.js, packages/strapi/lib/services/entity-validator/validators.js
When a model has an attribute with `default: true` and `required: true` and you use public API (POST /entitity) to create record it will return `400 ValidationError`, example:
**Model settings example**
```JSON
{
"kind": "collectionType",
"attributes": {
"someAttr": {
"type": "string"
},
"testAttr": {
"type": "boolean",
"default": true,
"required": true
}
}
}
```
**Request:**
```HTTP
POST /entity HTTP/1.1
Content-Type: application/json
{
"someAttr": "test"
}
```
**Response:**
```JSON
{
"statusCode": 400,
"error": "Bad Request",
"message": "ValidationError",
"data": {
"testAttr": [
"testAttr must be defined."
]
}
}
}
```
It should create record with default values, provided in model settings.
I predefined default attributes in `packages/strapi/lib/services/entity-service.js` in `create` …
=> Fix default values on create entity.

packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js
=> Update sqlite table migration query to escape column names

packages/strapi-connector-mongoose/lib/mount-models.js
resolves #5682 
https://github.com/strapi/strapi/pull/5612 forced MongoDB indexes to be synced with the JSON model.
However, this pr caused some breaking changes for peoples using manually created indexes.
After discussing it in #5682 and while it's not possible to create compound indexes in models.json, the `syncIndex` will now be executed only in a development environment.
=> Remove auto-sync indexes for mongodb from production envs

packages/strapi-plugin-users-permissions/config/schema.graphql.js, packages/strapi-plugin-users-permissions/controllers/Auth.js
Fixes #5816
#5580 changed the signature of the `emailConfirmation` endpoint by adding the `returnUser` argument, which in that PR got introduced to disable the frontend redirect after confirming the email via the GraphQL endpoint.
However, when using the REST API, the second argument for the `emailConfirmation` endpoint is always the `next` callback. Therefore #5580 caused the frontend redirect to break when using REST.
=> Fix email confirmation redirect

docs/3.0.0-beta.x/deployment/google-app-engine.md, docs/3.0.0-beta.x/getting-started/deployment.md
During the merge of the new Deployment docs this PR: https://github.com/strapi/strapi/pull/5088/files accidentally got skipped over, this new PR fixes that and merges in these GCP docs with the new deployment docs structure.
=> Re-add Google App Engine deployment docs

packages/strapi-connector-mongoose/lib/queries.js
The id used in the relationship verification can be either a string or a Buffer at this point. For example, when the update function is run by the users-permissions plugin on the forget-password call, and a user has components, it will currently throw a 400 as it tries to compare the id Buffer and an id string.
This fixes the deleteOldComponents function in the strapi-connector-mongoose package by adding a `toString()` to it.
=> Fix relation detection for components in mongoose connector

docs/3.0.0-beta.x/concepts/models.md
Signed-off-by: Convly <jean-sebastien.herbaux@epitech.eu>
Added a warning when renaming models.settings.json files or changing the value of a model's globalId
=> Add warning about changing models globalId

packages/strapi-provider-email-amazon-ses/package.json
Fixes #5852
Just updated the dependency to `node-ses`, as I had to fix the issue there: https://github.com/aheckmann/node-ses/pull/60
=> Fix AWS SES not working in eu-central-1 region

packages/strapi-plugin-users-permissions/services/UsersPermissions.js, packages/strapi/__tests__/deepFiltering.test.e2e.js
fix #4045 
- changed the function that creates permissions at startup
- remove "removeDuplicates" function as it is not necessary
- @alexandrebodin I let the default `enabled` management in `updatePermissions` because by default 2 roles are created before (`Authenticated` and `Public`) but the permissions are not created. It would require a new logic like a function `createDefaultRoleAndPermissions` that would share some code with `updatePermissionns` but not sure we want to give time to that for the moment. I would be happy to discuss about it if you want.
=> fix missing permissions at startup

packages/strapi-connector-bookshelf/lib/queries.js
Fix a bug introduced by: https://github.com/strapi/strapi/pull/5814.
Bug : default users were not created because `roleCount` is a string when using postgresql.
=> fix count() result not a number

packages/strapi-plugin-users-permissions/config/schema.graphql.js
Fix for #5854 Updated arguments sent from the to role GraphQL schema to the controller to match the expected format
Added code in the schema file for updateRole and deleteRole to supply the Id from the "where" of the request into the context as expected by the controller (which expects context.params.role). Additionally, the updateRole expects only the context as an argument.
Did not modify the controller as not to break any non-graphql implementation.
FYI - This is my first PR.
#5854
=> Fix #5854 - GraphQL implementation of updateRole and deleteRole fails

docs/3.0.0-beta.x/plugins/graphql.md, packages/strapi-plugin-graphql/services/resolvers-builder.js, packages/strapi-plugin-graphql/services/type-definitions.js, packages/strapi-plugin-graphql/services/utils.js
fix #4224 
- Checks if the resolver exists before trying to add it the graphql schema. If it doesn't exist, it doesn't add it to the schema.
- Moved some functions in utils
=> fix shadow crud breaking build when resolvers are not defined in a plugin

packages/strapi-plugin-content-manager/admin/src/translations/de.json
Abbrechen means cancel. Which implies the user would get back to the list view, while editing a single item.
Zurücksetzen means to revert back - reset. :)
=> docs: DE Abbrechen does not mean reset

packages/strapi/lib/services/core-store.js
Found a bug, that the `core-store` returns `null` when the stored `type` is `'string'`.
The problem only affected the `get` function.
Added string type to the condition above JSON.parse, now it is converted back to the original value and returned from `core-store.get`.
=> Fixed: Core store returned null instead of string

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
Hello, I meet the same bug of issue #4621
The rich text field can't save the Chinese words input through IME.
Here is the gif of this issue.
I tried to add some logs to debug it. I find the problem is between the `setState` and `sendData` function of WYSLWYG component. I added the following piece of code.
```javascript
/**
* Update the parent reducer
* @param  {Map} editorState [description]
*/
sendData = editorState => {
console.log("editorState.getCurrentContext().getPlainText():", editorState.getCurrentContent().getPlainText())
console.log("this.getEditorState().getCurrentContext().getPlainText():", this.getEditorState().getCurrentContent().getPlainText())
console.log("this.getEditorState().getCurrentContext() equals editorState.getCurrentContext()?", …
```
=> fix #4621 - rich text can't save Chinese

packages/strapi/lib/core/__tests__/fs.test.js
The unit tests on the file system were failing on Windows platforms as they were assuming / as path separator. Amended them to use path.combine so that they're independent from the platform they're running on.
=> Make unit tests on files platform agnostic by using path.combine. Avoid them failing on Windows 

packages/strapi-connector-bookshelf/lib/mount-models.js
Currently using the idAttribute and idAttributeType options can break strpai in many ways. We will reconsider a better approach in the future but right now it is preferable to remove the options and only work with a conventional `id`. 
Close https://github.com/strapi/strapi/issues/4084
Close https://github.com/strapi/strapi/issues/1762
=> Remove idAttribute and idAttributeType options because breaks strapi

packages/strapi-connector-bookshelf/lib/knex.js
In the case where this is a schema defined, `options.pool` is reassigned ignoring the object constructed in a previous step (only preserving min and max, but not the other values such as `createTimeoutMillis` etc...  This change is to keep the other values intact.
=> Preserve pool setttings when there is a schema

packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js, packages/strapi-connector-bookshelf/lib/queries.js, packages/strapi-connector-mongoose/lib/index.js, packages/strapi-connector-mongoose/lib/queries.js, packages/strapi-connector-mongoose/package.json, packages/strapi-utils/lib/__tests__/stringFormatting.test.js, packages/strapi-utils/lib/index.js, packages/strapi-utils/lib/stringFormatting.js, packages/strapi/__tests__/search.test.e2e.js, test/e2e.js, yarn.lock
The search logic was not the same for every database (it was most often a semantic search which requires that the query contains full words).
Now the search is a simple LIKE search were we are looking for data that **contains** the query. 
**New feature:**
When the query is a number, the search was looking for an exact match.
Now I propose that it searches as if numbers were string so the query `12` would find an entry were a field is the number `123`.
This feature has an impact on the performance and I'm asking if the impact is acceptable or not.
Here are my performance results :
|Test nb|Database|Nb of requests|Kind of requests|Using new feature|Duration (sec)|Duration/request (ms)|
|---|---|---|---|---|---|---|
|1|postgres|600|half string, half number|no|79|131|
|2|postgres|600|half …
=> Change search logic

packages/strapi/lib/commands/uninstall.js
Fix for #5302 - there were no argument with folder path to delete. And previously used function didn't delete folder with it's content. The new `removeSync` delete folder with all content.
Tested locally and works fine.
I don't see any tests for /lib/uninstall.js
Documentation needs no changes, imho.
**Before Merge:**  shouldn't it also delete this folders?
```
/extensions/user-permissions/documentation
/extensions/email/documentation/1.0.0 
/extensions/upload/documentation/1.0.0
```
I could add some code to delete this folders if plugin name === "documentation".
**FYI:** this is my first Open Source contribution. Any suggestions appreciated :)
=> Fix #5302 - Uninstall plugin: function to delete folder with files

packages/strapi-plugin-upload/config/functions/bootstrap.js
Signed-off-by: Convly <jean-sebastien.herbaux@epitech.eu>
fix #4918
Currently, on MongoDB, deleting a content-type doesn't update the `related` field of the `upload_file` entries which can cause some issues (eg: #4918)
This PR introduces a new query ran in the bootstrap function of the `strapi-plugin-upload` package.
This query search for obsolete relations in the `upload_file` document and remove them.
=> Prune obsolete files relations on startup

docs/3.0.0-beta.x/deployment/google-app-engine.md
This changes documentation for the App Engine Deployment. Specifically the example `app.yaml` file.
Setting the `HOST` variable to one that has `*.appspot.com` domain seems to be causing connectivity issues for multiple people - https://github.com/strapi/strapi/issues/3433#issuecomment-621764964
My first deployment spawned 10 App Engine instances because of starting/connectivity problem.
The solution is simply setting `0.0.0.0`.
=> Changes the App Engine HOST variable to '0.0.0.0'

docs/3.0.0-beta.x/deployment/heroku.md
Heroku Error: self-signed certificate SSL fix for PG '^8.0.0'. Setting SSL options to `"ssl": { "rejectUnauthorized": false }` enables SSL but does not reject self-signed certificate for Heroku deployment. The issue occurs when Heroku invokes node application but fails at SSL cert for PG ^8.0.0.
=> Heroku Error: self-signed certificate SSL fix

packages/strapi-utils/lib/__tests__/parse-type.test.js
Preventing parse-type.test.js Date test from failure due to Time Zone differences
`Summary of all failing tests
FAIL  packages/strapi-utils/lib/__tests__/parse-type.test.js (19.811s)
● parseType › Date › Supports ISO formats and always returns the right format
expect(received).toBe(expected) // Object.is equality
Expected: "2019-04-21"
Received: "2019-04-20"
52 |       expect(parseType({ type: 'date', value: '2018-11-02' })).toBe('2018-11-02');
53 | 
> 54 |       expect(parseType({ type: 'date', value: '2019-04-21T00:00:00.000Z' })).toBe('2019-04-21');
|                                                                              ^
55 |     });
56 | 
57 |     it('Throws on invalid formator dates', () => {
at Object.<anonymous> (packages/strapi-utils/lib/__tests__/parse-type.test.js:54:78)` …
=> Preventing parse-type.test.js Date test from failure due to Time Zone differences

docs/3.0.0-beta.x/plugins/documentation.md
Hello there,
Just a small fix for a syntax error in your plugins documentation
=> Fix: Plugins docs syntax error

packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/content-type.test.js, packages/strapi-plugin-content-type-builder/controllers/validation/content-type.js
Right now names that can't be pluralize will not work correctly as we rely on the plural form to generate endpoints, queries, database tables and more.
This PR adds a check in the CTB to prevent the creation of such content types.
=> Check pluralize name in ctb

packages/strapi-plugin-users-permissions/config/schema.graphql.js, packages/strapi-plugin-users-permissions/test/users-graphql.test.e2e.js
Fixes #5834 
- Ignore private fields before passing input to resolver
PS: I'm only using GraphQL so I don't know if the same bug could be used to exploit the REST API.
=> Ignore private fields input on user register

docs/3.0.0-beta.x/concepts/configurations.md
- Changed description of `url`
- Changed default value of `emitErros`
- Removed `admin.build` and `admin.build.backend`
@alexandrebodin we agree that `admin.build.backend` is not needed anymore?
=> update server.url + remove server.admin.build

docs/3.0.0-beta.x/cli/CLI.md, packages/strapi/bin/strapi.js, packages/strapi/lib/Strapi.js, packages/strapi/lib/commands/configurationDump.js, packages/strapi/lib/commands/configurationRestore.js
Adds `strapi configuration:dump` and `strapi configuration:restore` commands. 
This will dump the content of all core_store keys starting with `plugin_`. This encloses all the plugin configurations put not the internal strapi keys. 
- This doesn't dump webhooks.
- This doesn't dump user-permissions or any other model data.
=> Configuration dump and restore cli

docs/3.0.0-beta.x/deployment/haproxy-proxy.md, docs/3.0.0-beta.x/getting-started/deployment.md
**This should not be merged until after:** #6134 
Currently missing a proper SVG logo, if the design team want to redraw the current HAProxy logo to add in. I am not terribly skilled in graphical editing enough to get their complex logo added. Example logo can be grabbed here: https://www.vectorlogo.zone/logos/haproxy/index.html
=> Add HAProxy proxy documentation

packages/strapi-plugin-users-permissions/controllers/Auth.js
Pull request https://github.com/strapi/strapi/pull/6072 aimed to add security by preventing user creation with email confirmation already enable. By limiting user params to 'username', 'email', 'password', the current code do not allow adding custom field to user entity anymore. This may breaks existing applications that have added required custom fields into user model.
Having required custom fields into user model that are now ignored leads code to throw an error that is catch line 566 and leads to `Username already taken` error which is in this situation inaccurate
Remove "confirmed" params off the registration payload instead of keeping only "username", "email", "password" params.
=> Prevent user registration with confirmed status

packages/strapi-plugin-upload/package.json, packages/strapi-plugin-upload/services/Upload.js, packages/strapi-plugin-upload/services/__tests__/upload.test.js, packages/strapi-utils/lib/stringFormatting.js, yarn.lock
Using the local upload provider with the new media library introduced in beta.20, images with a name that contains reserved characters such as `%` are not displayed properly any more, as the image URL is not encoded and now contains the image name as well.
This changes the upload function of the local upload provider to encode the URL of uploaded images with `encodeURI()`.
=> Fix url encoding for local upload provider

packages/strapi-plugin-upload/controllers/proxy.js
Error messages was unclear. As a developer, you could save a lot of time, with a more specific error-message.
=> Clarified upload proxy error messages

packages/strapi-plugin-upload/controllers/proxy.js
Found out that when using `res.headers.raw()` the header value would be wrapped in an array like: `['image/jpeg']`.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries
=> Upload proxy - Using Header objects build-in entries function

docs/3.0.0-beta.x/plugins/documentation.md
Erroneous double quote in custom  extensions/documentation/config/settings.json example
Removed a a double quote to make the JSON parse.
=> Erroneous double quote syntax error

docs/.vuepress/config.js, docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md, docs/3.0.0-beta.x/getting-started/quick-start.md, docs/v3.x/getting-started/quick-start-tutorial.md, docs/v3.x/getting-started/quick-start.md, packages/strapi-admin/admin/src/containers/HomePage/BlogPost.js, packages/strapi-admin/admin/src/containers/HomePage/index.js
The URL of the blog changed from `blog.strapi.io` to `strapi.io/blog`
There is a 301 redirection from the old one to the new one.
So I'm updating documentation links to the new one to don't have 301 redirection for nothing.
=> Fix strapi blog url

docs/v3.x/guides/error-catching.md
In order to catch errors from the other middlewares, it is important to have sentry middleware loaded at the beginning.
If let's say responseTime middleware would throw an error, sentry would not be able to pick it up if it's not loaded before.
=> Load sentry as first middleware

docs/v3.x/concepts/configurations.md
fix some typos in configurations documentation
=> fix some typos in configurations documentation

docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
Fixing some typos and adjusting the structure to make it easier to hard link users to sub-menus.
=> Fix typos in stable migration guide

docs/3.0.0-beta.x/deployment/google-app-engine.md, docs/v3.x/deployment/google-app-engine.md
Hello,
Some people are writing issue about misunderstood in the `google cloud storage` section for the deployment with Google App Engine.
In order to avoid further mistake, I prefer than the documentation provide a redirection to the full documentation of the plugin.
Thanks,
=> Update documentation of the section plugin Google Cloud Storage

packages/strapi-plugin-graphql/services/type-definitions.js
Fixed the GraphQL resolver, so that findOne uses the singular collectionType name instead of the plural name.
Currently the singular query resolver is ignored and the plural resolver is used. Which makes adding policies or custom resolvers to singular GraphQL queries impossible.
=> Fix singularName resolver for GraphQL findOne action

docs/v3.x/deployment/amazon-aws.md, docs/v3.x/plugins/email.md, packages/strapi-plugin-email/controllers/Email.js, packages/strapi-provider-email-amazon-ses/lib/index.js, packages/strapi-provider-email-mailgun/lib/index.js, packages/strapi-provider-email-sendgrid/lib/index.js, packages/strapi-provider-email-sendmail/lib/index.js
fix #6543
**What I did**
- log correctly the error from the provider on server side and send a 500 to user.
- send 400 error to user in case the error concerns the resquest (bad email for example). Only on `strapi-provider-email-mailgun` for the moment.
**What should be done in the future**
- Each provider should handler its own errors by adding a statusCode to the error it throws. 400 if it concerns a bad request, 500 if it's something else. Won't be done in the PR as it takes time and is not a priority.
=> better error handling in email

packages/strapi-connector-bookshelf/lib/knex.js
This PR removes pool options specified for database client connections other than `sqlite3`.
This was done because the `pool` options had very low values, particularly the `acquireConnectionTimeout`, which was causing the connection to timeout.
I'm not sure why this removed code was there in the first place, but maybe to fast detect connection timeouts. 
Instead of updating the code to have more permissive values, I choose to remove the code, making the `knex` and `tarn` dependencies responsible to set the default options. 
In userland, it's still possible to set the poll options as before.
@derrickmehaffy I've did not found any tests concerning database connections, maybe `strapi` relies on e2e tests for this?  
fix #6335
=> Remove options pool for non sqlite3 clients

docs/v3.x/guides/slug.md
The changes to the lifecycle hooks were not reflected in the guide.
=> Update slug system to new lifecycle hooks

packages/strapi-plugin-users-permissions/controllers/Auth.js
Fix #5861 
Hello. At Windows (10) when accessing provider at server route /connect/{provider} you receive following error: 
`{"statusCode":400,"error":"Bad Request","message":"This provider is disabled.","data":"This provider is disabled."}` even when the provider is enabled. 
This PR fixes it at Windows and should be ok at other platforms as well as the condition is not required.
=> Remove platform check

docs/3.0.0-beta.x/concepts/models.md
Fixed a typo in model relation docs:
`liked` -> `linked`
=> Fix typo in model relations docs

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
When the `changepassword` function has been renamed `resetpassword`.
the init permissions hasn't been updated?
So the function has been no longer available by default for the public role.
close #6440
=> Fix init reset password permission

packages/strapi-provider-upload-aws-s3/README.md, packages/strapi-provider-upload-cloudinary/README.md, packages/strapi-provider-upload-rackspace/README.md
Updated the README files of the 3 upload providers to use the `./config/plugins.js` instead of extensions.
=> Update upload providers README to reflect stable changes

packages/strapi-admin/admin/src/containers/AuthPage/index.js
We don't need to send most of the registration fields for optin newsletter registration. Let's remove them. This can also avoid some security issues down the line.
=> Only pick required fields to register for newsletter updates

packages/strapi-plugin-users-permissions/admin/src/components/Controller/index.js
This PR fixes the removed import of React in the users-permissions plugin.
Fixes #6733
=> Fixes #6733

docs/v3.x/migration-guide/migration-guide-alpha.26-to-beta.md, docs/v3.x/migration-guide/migration-guide-beta.15-to-beta.16.md, docs/v3.x/migration-guide/migration-guide-beta.19-to-beta.20.md
In migration guide, some links were relative so pointing to the wrong version of the documentation.
I fix this issue.
close #6776
=> Fix links wrong documentation version

packages/strapi-generate-new/lib/utils/usage.js, yarn.lock
To improve the product, we need to know if the users prefer using Yarn or npm. To make sure it'll pass all our security protections in our telemetry tools we need to stringify the value instead of using boolean.
=> Stringify boolean to detect Yarn or npm

docs/3.0.0-beta.x/plugins/users-permissions.md, docs/v3.x/plugins/users-permissions.md
Signed-off-by: ScottAgirs <scott@ijs.to>
=> [typofix] Client ID > Client Secret

packages/strapi-generate-new/lib/index.js
We need to differentiate One-click deploy buttons from other installations. That's the reason why we would like to introduce a way to prefix the `uuid` generated for each project. We do so by using an environment variable called `STRAPI_UUID_PREFIX`.
Then, each One-click deployment script will have to use the environment variable to prefix the uuid.
=> Support STRAPI_UUID_PREFIX env var

packages/strapi-connector-bookshelf/lib/queries.js, packages/strapi-connector-mongoose/lib/buildQuery.js, packages/strapi-connector-mongoose/lib/queries.js, packages/strapi-utils/lib/buildQuery.js, packages/strapi-utils/lib/models.js, packages/strapi/__tests__/deepFiltering.test.e2e.js, packages/strapi/__tests__/search.test.e2e.js
Finish work started in this PR : #5534
=> add filtering to search route

packages/strapi-connector-mongoose/lib/mount-models.js
This is to ensure custom mongoose queries that exclude dynamic zone fields don't fail.
Fix issue: https://github.com/strapi/strapi/issues/6016
=> Update mount-models.js to check if dynamic zone field exists from returned mongo object

packages/strapi-helper-plugin/lib/src/components/OverlayBlocker/index.js
New link for the button **Read the documentation** that pops up as overlay in Strapi. (plugin install blocker)
Fixed read the doc button link. #6669 
The button was broken with an old link. Replaced it with new link.
=> Fix broken link install plugin popup

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
Fixed permission action to all lowercase, as [commented](https://github.com/strapi/strapi/pull/6696/files#r453004242) by @nicksp on @alexandrebodin PR #6696
=> Fix all lowercase action name

docs/v3.x/plugins/users-permissions.md
removes misleading documentation around which fields on the USER model can be used in the email templates, as at this commit: https://github.com/strapi/strapi/pull/6629/commits/ccb428e04f9d19aee2fc4d54210684c3ceca6f98#diff-bbc9dda26221803c32574c89c58bdb24R6
only email and username may be referenced in the email template
=> Removes misleading documentation

packages/strapi-admin/admin/src/containers/LocaleToggle/index.js, packages/strapi-admin/admin/src/containers/LocaleToggle/tests/index.test.js
Fixes #6912 — Add another `case` for Swedish since the language code (`sv`) is different than the country code (`se`).
=> Fix wrong flag for Swedish

docs/v3.x/plugins/users-permissions.md
Strapi uses purest 3.1 but docs were linking to an old 2.x branch of purest.
=> Update Purest docs link

docs/v3.x/concepts/services.md
Signed-off-by: Diego Albitres <diego.albitres@gmail.com>
Fixed a [404](https://strapi.io/documentation/v3.x/concepts/content-api/parameters.html) on [Extending a Model Service](https://strapi.io/documentation/v3.x/concepts/services.html#core-services).
=> docs: fix 404 link on services.md

docs/v3.x/concepts/models.md
Read to merge
fixed typo in `bellow` text link
=> typo fix for `below` text link

packages/strapi-helper-plugin/lib/src/testUtils/commonTrads.json, packages/strapi-plugin-content-manager/admin/src/translations/en.json, test/config/front/testUtils/commonTrads.json
A simple update of the English translations so the error makes a bit more sense.
=> FIX - Update regex error value for English translation

packages/strapi/lib/Strapi.js, packages/strapi/lib/core/app-configuration/index.js
allows setting STRAPI_LOG_PRETTY_PRINT, STRAPI_LOG_LEVEL etc in env file
Load env vars from env file at starpi start, allows setting STRAPI_LOG_LEVEL, STRAPI_LOG_PRETTY_PRINT, STRAPI_LOG_TIMESTAMP etc related to #6693.
but it might not fix it as middleware config is overriding log level to 'debug', using default json file, not sure if I can use this env variable(STRAPI_LOG_LEVEL) in that logger middlerware's defaults json file, but it allows use of other vars like STRAPI_LOG_PRETTY_PRINT, STRAPI_LOG_TIMESTAMP & STRAPI_LOG_FORCE_COLOR
=> load dotenv lib at start

packages/strapi-plugin-graphql/package.json, yarn.lock
Updates `apollo-server-koa` to a version that fixes the security advisory in #7085
=> Upgrade apollo-server-koa

docs/v3.x/concepts/services.md, docs/v3.x/deployment/digitalocean.md, docs/v3.x/installation/digitalocean-one-click.md
Fixed a typo on the create and update services that incorrectly referenced `plugin: users-permissions` instead of `source: users-permissions`
Changed the referral URL for the free $100 credits on both DigitalOcean docments.
=> Fixing service documentation and fixing DO referral link

packages/strapi-plugin-upload/controllers/upload/api.js
Fix https://github.com/strapi/strapi/issues/7131
@Convly you can add test for this
=> Fix upload api

packages/strapi-plugin-users-permissions/services/Providers.js
Bumped VK provider API version. Prior to this VK OAuth used to fail silently without creating a user. As it turned out - VK API responded with `versions prior to 5.21 are not supported`.
=> Fix VK OAuth not working

packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
=> Fixes #7139

docs/v3.x/concepts/customization.md
Follow up on #7140 & #7143 
**Description of what you did:**
Add warning in the extensions docs
=> Add extension warning

packages/strapi-connector-bookshelf/lib/queries.js, packages/strapi-connector-mongoose/lib/queries.js
=> fix count with sort param

docs/v3.x/admin-panel/deploy.md
The `module.exports` example code is missing a closing parenthesis at the end of each example. Added the closing parenthesis.
=> Fix typos with the `module.exports` examples.

packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
This PR fixes the required validation issue when updating a entry that has a required date field.
- Fixes #7186 
- Fixes #7183
=> Fix date and datetime required validations issue

packages/strapi/lib/Strapi.js
Fix https://github.com/strapi/strapi/issues/5869
=> Fix server not accessible at bootstrap

packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
=> Fixes #7189

docs/v3.x/installation/docker.md
This PR only affects the documentation and is ready to be merged.
1. **Changed volume for strapi in SQLite from `./:/srv/app` to `./app:/srv/app`**
Both the PostgreSQL and MongoDB strapi service binds to `./app` instead of `./`, so this feels more uniform. It's also better to keep strapi into the `./app` folder and not mixed up with the docker-compose file here.
2. **Removed `links` option for strapi service in PostgreSQL and MongoDB**
Since docker-compose v3, the `links` option became a legacy feature and may eventually be removed, [as mentioned in the official Docker docs over here](https://docs.docker.com/compose/compose-file/#links). Since docker-compose joins services/containers into the same network, they can already communicate to each other, as quoted from the previous docker docs …
=> Update docker-compose examples

packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
Signed-off-by: Eric Liu <eric@ericliu.page>
fix https://github.com/strapi/buffet/issues/136
1. ~~Changing from 'text' to 'number' input for 'biginteger'. So it will show the inc/dec arrows for bigingeter input.~~
2. Set 'step' to 0.1 instead of 'any' so the inc/dec arrows on Decimal and Float type can work properly.
3. Changing 'step' value to the specific number type
=> Fix Input Number issue

packages/strapi-admin/admin/src/containers/Onboarding/StaticLinks/index.js, packages/strapi-admin/admin/src/translations/en.json
Added a link to our [Cheatsheet](https://strapi-showcase.s3-us-west-2.amazonaws.com/CheatSheet.pdf) in the bottom right blue button (?).
=> Add the CheatSheet link

docs/v3.x/concepts/middlewares.md
In a convo on slack, noticed we were missing some of the useful options for the parser middleware from `koa-body` added them and a link to the package in the docs.
=> Add more information about the parser middleware configuration

packages/strapi-plugin-upload/controllers/upload/admin.js, packages/strapi-plugin-upload/middlewares/upload/index.js, packages/strapi-provider-upload-local/lib/index.js
=> Upload path can be absolute

packages/strapi-admin/admin/src/containers/Users/EditPage/index.js, packages/strapi-admin/admin/src/translations/en.json
Changed words to be gender neutral.
=> Gender Equality

docs/v3.x/concepts/configurations.md, packages/strapi/lib/Strapi.js, packages/strapi/lib/core/app-configuration/index.js
=> Add conf proxy koa variable

docs/v3.x/concepts/middlewares.md
Removed some extra fields from the session middleware docs that don't work/don't apply. This is related to #6421 **but does not fix it** we should further review this middleware and update it to reflect changes and allow users to change their session storage location and not just node memory.
=> Remove session options from docs that no longer work

packages/strapi-utils/lib/sanitize-entity.js
Fix #7335 
In sanitizeEntity, setting `includeFields` to `null` should indicates "all fields".
It was not the case before thus creating issues with `allowedFieldsHasKey` checks for dynamic zones.
=> Fix sanitizeEntity's includeFields usage

packages/strapi-plugin-graphql/services/build-aggregation.js
We have entities that reference another entity that could be deleted. For performance reasons, any entity that is orphaned is cleaned at a later time, but this is breaking our graphql aggregation queries. This PR adds a simple existence filter on the `_id` field that exists when null as well. Maybe it might also be beneficial to allow grouping by null to check orphaned relationships?
Output from a log above converting the result to an array:
Output from the graphql query:
```json
{
"errors": [
{
"message": "Cannot read property 'toString' of null",
"locations": [
{
"line": 4,
"column": 7
}
],
"path": [
"entriesConnection",
"groupBy",
"release"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR",
"exception": {
"stacktrace": [
"TypeError: Cannot read property 'toString' of null",
"    at …
```
=> fix(graphql): filter out orphaned relationships

docs/v3.x/concepts/configurations.md
fixes #7339
Adjusted docs to remove the `require` that would throw errors trying to load bookshelf plugins.
=> Fix docs for loading ORM plugins

packages/strapi-plugin-graphql/services/data-loaders.js, packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js
fixed strapi/strapi#7334 add the data-loader for admin users to the graphql plugin
Signed-off-by: Daan van Ham <daan.van.ham@frontmen.nl>
=> fixed strapi/strapi#7334 add the data-loader for admin users to the graphql plugin

packages/strapi-provider-upload-local/README.md
Fixed the Readme docs of the strapi-provider-upload-local package.
They talked about Cloudinary, probably because of a copy and paste mistake.
I also wrote that the `sizeLimit` config value should be specified in bytes and not KB, since it seems to rely on [File.size](https://developer.mozilla.org/en-US/docs/Web/API/File/size)
=> Fix strapi-provider-upload-local readme

docs/v3.x/concepts/configurations.md
Fix: Broken links to reference docs
```diff
- `./middlewares#global-middlewares` 
+ `./middlewares.md#global-middlewares`
- `../plugins/email#create-an-email-from-a-template-fillemailoptions` 
+ `../plugins/email.md#programmatic-usage`
- `../admin-panel/forgot-password` 
+ `../admin-panel/forgot-password.md`
- `../plugins/email#configure-your-provider`
+ `../plugins/email.md#configure-the-plugin`
```
=> FIX: Broken links to email configurations & middlewares

docs/.vuepress/config.js
Just fixed the favicon link on documentation. Right now it isn't loading because it can't find the icon on [`https://strapi.io/favicon.ico`](https://strapi.io/favicon.ico).
=> Fix favicon link in docs

docs/3.0.0-beta.x/plugins/upload.md
Fixed small typo in upload plugin documentation.
This is ready to be merged.
=> Fix typo in upload plugin documentation

packages/strapi-connector-mongoose/lib/mount-models.js
Fix https://github.com/strapi/strapi/issues/7304
=> Fix virtual mongoose remove _v char

docs/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.md
The `username` field is no longer required.
So in the database, the `username` field has `NOT NULL` constraint.
In the 3.1.x the field is not in the form to create a new admin. 
So there is an issue when you create a new admin because of this constraint.
We should remove the `NOT NULL` constraint to be able to create a new admin.
=> Docs update on migration guide for username constraint

packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
This PR fixes the initialisation of the default data structure in the content manager plugin.
Fixes #7414
=> Fixes #7414

packages/strapi/bin/strapi.js
Some exceptions, like module inclusion errors, don't generate nice
Error objects with message defined. This causes hard-to-debug failures.
When encountering an error with no message, show the whole Error object.
In the `strapi` executable if a subcommand throws an error the driver prints `error.message`. But some errors don't have a `message` and this leads to a bad error message in the console. I print `error.message || error` instead.
=> Show error.message || error on failed command

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/constants.js, packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js, packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
=> Fix WYSIWYG bugs

packages/strapi-admin/admin/src/translations/en.json
"Enterprise" was incorrectly spelt as "Entreprise"
I changed the spelling of "Enterprise" in packages/strapi-admin/admin/src/translations/en.json so that it is no longer spelt incorrectly.
=> Fixing typo in translations/en.json.

packages/strapi-plugin-content-type-builder/admin/src/containers/ListView/index.js
=> Fixes #7301

docs/v3.x/concepts/middlewares.md, packages/strapi/lib/middlewares/parser/defaults.json, packages/strapi/lib/middlewares/parser/index.js
Updated the arrayLimit in the parser to 100 (arbitrarily).  There might be a better number to use here, but it's causing issues when trying to do a where [field]_in query with a list of more than 20 items (see the tagged issue) using GraphQL.  You could theoretically use `Infinite` here but that might open things up to abuse. 
Fix #5995
=> Increase parser arrayLimit to 100

packages/strapi-utils/lib/__tests__/sanitize-entity.test.js, packages/strapi-utils/lib/sanitize-entity.js, packages/strapi/lib/core-api/controller.js
Add tests for sanitize-entity.
Rise coverage to 100% and handle edge cases;
=> Add utils::sanitize-entity tests

packages/strapi-plugin-upload/package.json
This PR fixes #7572 by preventing users from uninstalling the upload plugin from the administration panel.
=> Prevent from uninstalling the upload plugin in the admin panel

packages/strapi-helper-plugin/package.json, packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js, yarn.lock
=> CM bug fixes

packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
fixes https://github.com/strapi/strapi/issues/7401
=> Fix decimal on content manager's inputs

packages/strapi/lib/Strapi.js
Fix https://github.com/strapi/strapi/issues/7561
=> Setup http server in Strapi constructor

docs/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.md, docs/v3.x/migration-guide/migration-guide-beta.17-to-beta.18.md
During the migration, I ran into the problem while updating the kind attribute: in my repeatable components `kind` attribute was updated only in first element. I fixed it by using all positional operator $[] in update query.
Operator differences: https://docs.mongodb.com/manual/reference/operator/update-array/#array-update-operators
=> Fix kind attribute update query in beta.17 to beta.18 migration guide

packages/strapi-plugin-upload/config/schema.graphql.js, packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js
Adds a new mutation that allows to update file information (name, alternative text and caption). Fixes https://github.com/strapi/strapi/issues/7406
=> Update file info mutation

packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/index.js, packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/retrieveComponentsFromSchema.js
~ fixed ReferenceError: Cannot access 'allComponents' before initialization
=> fix strapi-plugin-content-type-builder

packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js, packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/tests/reducer.test.js
If a file is selected, but not loaded in the 'files' array of the state, it can't be found and you will get an error after clicking on the edit icon.
This PR will make sure it will look in both the 'files' and the 'selectedFiles' arrays for the given file id.
This resolves https://github.com/strapi/strapi/issues/7458
=> Find file to edit in all available files

docs/v3.x/guides/unit-testing.md
Added `sqlite3` to the list of modules to install for testing, as the guide assumes it is there. In the configuration I also dropped the pool size to 1; I was consistently hitting sqlite3 database lock errors until I did this.
=> Add sqlite details to unit testing guide

packages/strapi-plugin-upload/package.json
Related Issue https://github.com/lovell/sharp/issues/2352
I've faced an issue when building electron app with strapi.
Updating version of sharp solved the problem.
Please check and hope be merged soon.
=> Update sharp module to 0.26.0

docs/v3.x/concepts/controllers.md
The default SingleType service doesn't have an findOne() function only find().
Closes #7718
=> Fix typo in controllers.md

packages/strapi-admin/admin/src/components/ContainerFluid/index.js
Fix : #7265 
I have just extended the bottom padding , so that there is room for scrolling down to access the pagination tab.
Before :
After :
=> FluidContainer: Fix overlapping on pagination tab

packages/strapi-plugin-upload/admin/src/components/EditForm/index.js, packages/strapi-plugin-upload/admin/src/utils/createFileToDownloadName.js
=> Fix replace media 

docs/3.0.0-beta.x/concepts/models.md, docs/v3.x/concepts/models.md
found 3 minor typos and replaced them
=> Fix minor typos on model documentation

packages/strapi-admin/admin/src/containers/ProfilePage/utils/form.js, packages/strapi-admin/admin/src/containers/Users/EditPage/utils/form.js
Signed-off-by: richardgrey <richie.grey@gmail.com>
This PR fixes #7666 
The fix is a simple setting `autocomplete` attribute to `new-password`. For `username` setting this attribute to `no` telling the browser that this field should be autocompleted as a field called "no". Basically, using unique value switching off the autocomplete.
=> Fix autocomplete issue in Chrome. Fixes #7666

docs/v3.x/installation/docker.md
Adds a MySQL tab to the list of docker-compose yaml files in the "Installation using Docker" section of the docs.
=> Update docs to include MySQL docker-compose.yaml

docs/v3.x/plugins/users-permissions.md
- Edit steps 2 and 4 to make it more readable. The previous one is quite confusing when I read it.
- Edit assumption `Let's say...` to be more readable
- Change github to GitHub for consistency
=> Edit `understanding login flow` to be more readable

packages/strapi-plugin-users-permissions/admin/src/translations/pl.json
"EditForm.inputToggle.label.email-reset-password": "Straona resetowania hasła"   <--- should be "Strona resetowania hasła"
=> translation improvement

packages/strapi-plugin-upload/controllers/proxy.js, packages/strapi-plugin-upload/test/proxy.test.e2e.js
If the URL we were fetching via the proxy had utf-8 characters, the proxy returned a 500 "Request path contains unescaped characters". 
Before fetching the URL, we now encode it.
I added a few tests (the utf-8 characters one is failing on master, as expected). I used strapi.io as the proxied url, not really happy about it as it relies on an external service. If you have a better idea, tell me.
=> Encode the URL before fetching it.

packages/strapi-plugin-graphql/package.json
Signed-off-by: Abdón Rodríguez Davila <a@abdonrd.com>
Update graphql plugin dependencies
=> Update graphql plugin dependencies

packages/strapi-plugin-graphql/services/type-definitions.js
This fixes strapi/strapi#4353 and all its duplicates.
As said by @abanchev [here](https://github.com/strapi/strapi/issues/4353#issuecomment-616209971) the problem is at file services/type-definitions.js near line 184:
```
if (
((association.nature === 'manyToMany' && association.dominant) ||
association.nature === 'manyWay') &&
_.has(obj, association.alias) // if populated
) { ... } else {
_.set(queryOpts, ['query', association.via], obj[targetModel.primaryKey]);
}
```
It turns out that in the case of a 3+ level nested query, the third level will not work because the obj is not populated with the `association.alias` so it enters the else block and add the `association.via` in the query. But the problem is that `association.via` for `manyWay` is `undefined`. This will propagate and the …
=> fix(plugin-graphql): Fix association resolver for `manyWay` nature.

docs/v3.x/concepts/models.md
Quickly went through the models' page in the documentation and updated some grammar as well as added some emphasis and brief clarification in a couple of places.
=> Updated Models Page Grammar

packages/strapi-admin/admin/src/containers/AuthPage/components/Register/index.js, packages/strapi-admin/admin/src/containers/AuthPage/index.js, packages/strapi-admin/admin/src/containers/AuthPage/utils/forms.js, packages/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js, packages/strapi-plugin-upload/admin/src/containers/HomePage/HomePageContent/HomePageSettings.js
This PR fixes #7699 in particular point 2 and 4 of the issue. 
Regarding point 1 about the prompt when clicking on an external link this cannot be achieved using **react-router**.
A workaround could be to use an html `<a>` tag with `target="_blank"  so modifications are not lost when testing a link.
=> Fixes Admin bugs

packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
fix https://github.com/strapi/strapi/issues/7990
=> fix cropped size too big

docs/v3.x/cli/CLI.md, packages/strapi-admin/index.js, packages/strapi/bin/strapi.js, packages/strapi/lib/commands/develop.js, packages/strapi/lib/commands/watchAdmin.js
```
strapi develop --watch-admin   //open the default browser
strapi develop --watch-admin --browser false   //do not open any browser
strapi develop --watch-admin --browser 'google chrome' //open Google Chrome
strapi develop --watch-admin --browser Firefox //open Firefox
```
=> Allow browser options while using watch-admin

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/constants.js, packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/helpers.js
Fixes #7890
Title says it all, when replacing a selection, assume the selection is text and not a link; as per the issue
=> Assume selection is text when creating a link

packages/strapi-connector-mongoose/lib/utils/index.js
Signed-off-by: richardgrey richie.grey@gmail.com
This PR fixes #5777 
This changes will allow setting an empty value (null, undefined) for fields of type Date/Time through the API.
In the admin panel, it's still not possible to clear the value of Date or Time fields. It is on buffet/core DatePicker component and has related [feature request](https://github.com/strapi/buffet/issues/97) to be able to clear the value of such inputs.
=> Fix validation of Date and Time field types for Mongoose connector #5777

docs/3.0.0-beta.x/installation/docker.md
Fixed the PostgreSQL data path to a correct one (`postgres` Docker image stores the database files in `/var/lib/postgresql/data`. The example documentation originally stated `/data/postgres` path, which is incorrect).
=> Fix incorrect PostgreSQL data path in example doc

packages/strapi/lib/middlewares/public/index.html
Added noindex to index page as it is rare that such a page would want to be indexed.
=> Add noindex to public index page

jest.config.js
Add `.cache` pattern to excluded paths in `jest.config.js`
=> Prevent .cache folders to impact the unit tests

packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js, packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/tests/forms.test.js, packages/strapi-plugin-content-type-builder/test/content-types.test.e2e.js, packages/strapi-plugin-content-type-builder/utils/attributes.js
This PR adds `private option` to the `relation`.
=> Feat: Add private option field for relations

docs/v3.x/concepts/configurations.md
Default values for pooling options is removed in #6469, so currently they are same as `knex` and `tarn`. And `settings.options` is not used anywhere, so I guess it is succeeded by `options`.
=> docs: update database configurations to match current implementation

packages/strapi-plugin-email/admin/src/translations/index.js, packages/strapi-plugin-email/admin/src/translations/th.json
Add translations to a new language - Thai to **strapi-plugin-email**
If you are Thai and use Strapi, please join for discussion and contribute with us.
**[Strapi Thailand](https://www.facebook.com/groups/564370471172538)** Facebook group. See you there!
=> add strapi-plugin-email thai translation

packages/strapi-generate-new/lib/utils/merge-template.js
Better error management during the installation of templates. We use `node-fetch` to download the templates from GitHub, and it only throws an error if there is a network error. I added an additional check to make sure the status of the download was ok.
This has an effect when:
* The user enters a repo that doesn't exist
* The user enters a private repo
Before this fix, the error message was quite obscure. It only failed while uncompressing the downloaded files with `tar`.
=> Handle template download error

packages/strapi-plugin-graphql/test/single-type.test.e2e.js, packages/strapi-plugin-upload/config/schema.graphql.js, packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js
This fix #5292 by implementing and testing the removeFile mutation.
=> Implement deleteFile graphql mutation (#5292).

packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header/index.js
This PR removes the D&P related modals when the feature is disabled on a content type.
=> Remove unneeded modals when D&P is disabled

docs/v3.x/deployment/heroku.md
closes #8164 
The documentation was not clear as it was replacing the SQLite config, making it difficult to understand for new users how to run locally.
=> Fix heroku guide to set database settings in proper env path

packages/strapi-generate-new/package.json, packages/strapi-plugin-upload/package.json, packages/strapi/package.json, yarn.lock
node-fetch < 2.6.1 has a security vulnerability
(https://github.com/advisories/GHSA-w7rc-rwvf-8q5r)
This is a major version bump for strapi-plugin-upload (from 1.7.3), but
it does not look like strapi-plugin-upload is relying on any of the
functionality that has broken from 1.x to 2.x
This covers the same change in https://github.com/strapi/strapi/pull/7975, but for more than strapi-generate-new.
This also covers three dependabot PRs that were closed without merging:
* https://github.com/strapi/strapi/pull/7857
* https://github.com/strapi/strapi/pull/7837
* https://github.com/strapi/strapi/pull/7757
Bumped node-fetch in the packages that use it, to address a security vulnerability.
* strapi-generate-new: 1.7.3 -> 2.6.1
* strapi-plugin-upload: 2.6.0 -> 2.6.1
* strapi: 2.6.0 -> 2.6.1
=> Bump node-fetch to 2.6.1

docs/v3.x/concepts/middlewares.md, packages/strapi/lib/middlewares/gzip/defaults.json, packages/strapi/lib/middlewares/gzip/index.js, packages/strapi/package.json, yarn.lock
Upgrade `koa-compress` and add support for `Brotli compression`
```javascript
{
"gzip": {
"enabled": false,
"options": {
"br":  false
}
}
}
```
```javascript
{
"gzip": {
"enabled": true,
"options": {
"br":  true,
"threshold": 2048
}
}
}
```
=> Add support for brotli compression

packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils/getDraftRelations.js
Fixes #8220 
In #8221 I explained the problem thoroughly, but it was closed as it is a duplicate of 8220.
Basically `getDraftRelationsCount` is called with `null` as data, and then `Object.keys(data)` fails on [line 5](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils/getDraftRelations.js#L5)
I'm pretty sure this doesn't affect other functionalities.
=> fixes #8221 - fixed publish failing if non-repeateable component data is "null"

packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header/utils/getDraftRelations.js
This PR fixes an helper that retrieves the number of relations that are still in draft state.
=> Fix getDraftRelationsCount utility

packages/strapi-database/lib/constants/index.js
Fixed issue where user was allowed to create a model with reserved word 'format'. Creating this model would then break one-to-one relationships and cause an error: "Maximum call stack size exceeded."
=> Add missing 'format' reserved model word.

packages/strapi-connector-bookshelf/lib/populate.js, packages/strapi-connector-bookshelf/lib/utils/populate-queries.js
fix #8225 
Fix wrong behaviour from bookshelf's populate which was extending custom populate queries for each part of the deep path instead of only extending the full path and binding populate queries to the rest.
The fix consist of **extending** the original query only for the full path. **Binding** only populate queries otherwise.
=> Fix wrong query generation with bookshelf

packages/strapi-connector-bookshelf/lib/utils/store-definition.js
Fix #8227
Setting the attribute id to undefined will run an insert query with an undefined id binding.
=> do not set id to undefined

packages/strapi/lib/Strapi.js
I updated the health check to handle both GET and HEAD requests, where before it only handled HEAD requests. 
I'm an engineer at Render, and recently worked on our [Deploy Strapi doc](https://render.com/docs/deploy-strapi) and Strapi example repos. Render uses health checks to enable zero downtime deploys, as described here: https://render.com/docs/zero-downtime-deploys. Our health checks use GET requests, so currently we're recommending that people deploying Strapi on Render create a file at `/public/healthz/index.html` with contents `OK`, and specify `/healthz` as their health check path. This is okay, but it would be cleaner if we could use the existing health check at `/_health`.
I imagine this could be helpful for Strapi users on other platforms as well.
=> Update /_health to accept GET requests

packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js
fix #7669 point 8
verified point 6 on strapi@3.2.1 and it looks good.
for point 5 and 7, not sure if need to fix because it is subjective. Let me know if strapi team wants a fix.
=> Fix incorrect notification when copy media url to clipboard

packages/strapi-utils/lib/logger.js, packages/strapi/lib/middlewares/logger/index.js
- Remove STRAPI_LOG_LEVEL environment variable related redundant code.
- Add helpful error message to the current log level configuration
system.
Fixes #7673
=> Refactor log level configuration

packages/strapi-admin/services/permission/permissions-manager/index.js, packages/strapi-admin/test/admin-permissions-conditions.test.e2e.js, packages/strapi-admin/test/admin-role.test.e2e.js, packages/strapi-plugin-content-manager/controllers/ContentManager.js, packages/strapi-plugin-upload/controllers/upload/admin.js, packages/strapi-plugin-users-permissions/controllers/user/admin.js
Conditions based on author's roles were not working properly. This PR aims to fix this behaviour.
fix https://github.com/strapi/strapi/issues/8129
About the `SERVER_ERROR` mentionned in the issue, the backend is sending back a `403 Forbidden` error.
@soupette / @HichamELBSI do you have any insight on this?
=> Fix "has same role as author" condition not working properly

packages/strapi-connector-mongoose/lib/buildQuery.js, packages/strapi-plugin-graphql/services/type-definitions.js, packages/strapi-plugin-users-permissions/controllers/User.js, packages/strapi/lib/core-api/__tests__/service.test.js, packages/strapi/lib/core-api/controller.js, packages/strapi/lib/core-api/service.js, packages/strapi/lib/services/entity-service.js
Fix D&P population (gql, rest, single-types)
=> Fix D&P population

packages/strapi-connector-bookshelf/lib/build-database-schema.js, packages/strapi-connector-bookshelf/lib/mount-models.js
bad column generated on startup for many way rels
fixes #8258
=> Fix undefined pk

packages/strapi/lib/services/__tests__/entity-validator.test.js, packages/strapi/lib/services/entity-validator/index.js
Fixes #8294 
With the new draft/publish system, models with custom field types could no longer be saved.
(Custom field types described [here](https://strapi.io/documentation/v3.x/plugin-development/frontend-field-api.html#registering-a-new-field))
When trying to create or update a model with an un-handled attribute type, the API would give a 500 internal server error, as no validator exists for this attribute type.
This PR handles the case where a custom validator is not available for a specific attribute type, and instead of throwing an error, falls back to using a mixed type validator.
=> Fix validations for custom field types

packages/strapi-admin/admin/src/containers/HomePage/SocialLink.js, packages/strapi-admin/admin/src/containers/HomePage/index.js
I added a link to the academy in the "Join the community" card in the homepage
=> Add Academy link to the 'Join the community' card in the homepage

docs/v3.x/concepts/draft-and-publish.md
Addition of a note in the Draft & Publish documentation to mention the possibility to activate/deactivate the feature when creating a new content type. It was forgotten when writing the 1st version of the documentation.
=> Draft and Publish documentation - Fix

packages/strapi-connector-mongoose/package.json, yarn.lock
resolves strapi/strapi#8066
Signed-off-by: Jonas De Kegel <jonas@fluid.desi>
bumped mongoose to 5.10.8 as requested [here](https://github.com/strapi/strapi/issues/8066#issuecomment-705798188) **AND** manually ensure 5.10.7 was not used in yarn.lock (for some reason yarn kept resolving `^5.5.13` to 5.10.7 even though it was the only remaining 5.10.7 usage (it should've switched to 5.10.8); manually updating the yarn.lock did make yarn see this, also after subsequent changes (but it will be important to check this on merge if there are lock conflicts)
=> Don't use mongoose 5.10.7

packages/strapi-plugin-upload/controllers/upload/admin.js, packages/strapi-plugin-users-permissions/config/routes.json
=> Fix wrong permissions assigns (upload, users-permissions)

docs/v3.x/concepts/middlewares.md, docs/v3.x/deployment/heroku.md
Added notes about gzip performance via koa-compress' default Brotli settings and a recommendation to disable Brotli on Heroku. These changes were prompted by the discussion in https://github.com/strapi/strapi/issues/7439#issuecomment-706200710 after experiencing extremely long response times on Heroku for the Admin panel javascript assets.
=> Adds warnings and workarounds for Brotli performance in koa-compress

docs/v3.x/cli/CLI.md, packages/create-strapi-app/package.json, packages/strapi-admin/services/__tests__/user.test.js, packages/strapi-admin/services/user.js, packages/strapi/bin/strapi.js, packages/strapi/lib/commands/__tests__/admin-reset.test.js, packages/strapi/lib/commands/admin-reset.js, packages/strapi/package.json, yarn.lock
Add the `admin:reset-password` command. Might rename it before merging though.
Documentation to review by before merging @derrickmehaffy
=> Reset admin password CLI

packages/strapi-plugin-graphql/services/utils.js, packages/strapi-plugin-graphql/test/graphqlCrud.test.e2e.js, packages/strapi-utils/lib/convert-rest-query-params.js, packages/strapi-utils/lib/index.js
=> Support query operators _or & _where in graphql with deep nesting

docs/v3.x/migration-guide/README.md, docs/v3.x/migration-guide/migration-guide-3.1.x-to-3.2.x.md, docs/v3.x/migration-guide/migration-guide-3.2.3-to-3.2.4.md, examples/getstarted/extensions/users-permissions/models/User.settings.json, packages/strapi-plugin-users-permissions/controllers/Auth.js, packages/strapi-plugin-users-permissions/models/User.config.js, packages/strapi-plugin-users-permissions/models/User.settings.json, packages/strapi-plugin-users-permissions/services/User.js
Adds a confirmationToken to use in the email confirmation instead of a valid jwt token.
We will need to explain how to add this field manually for users that did extend the User model. Will create a specific migration guide
=> Add confirmationToken to user for email confirmation

packages/strapi-connector-bookshelf/lib/buildQuery.js, packages/strapi-connector-bookshelf/lib/utils/populate-queries.js, packages/strapi-connector-mongoose/lib/buildQuery.js
Handle draft & publish for the deep filtering.
Prevent search & filters on draft content.
fix #8331
=> Fix deepFiltering with draft & publish

packages/strapi-connector-bookshelf/lib/build-database-schema.js, packages/strapi-connector-bookshelf/lib/database-migration.js, packages/strapi-connector-bookshelf/lib/mount-models.js, packages/strapi-connector-bookshelf/lib/utils/associations.js, packages/strapi-connector-bookshelf/lib/utils/store-definition.js, packages/strapi-connector-mongoose/lib/database-migration.js, packages/strapi-database/test/migration-required-attribute.test.e2e.js
- doesn't run d&p migration when a content-type is created
- rebuild tables if they were deleted in DB
=> fix d&p regressions

packages/strapi-plugin-content-manager/admin/src/components/PreviewWysiwyg/index.js, packages/strapi-plugin-content-manager/admin/src/components/PreviewWysiwyg/utils/satinizeHtml.js, packages/strapi-plugin-content-manager/package.json, yarn.lock
The PR fixes a security vulnerability with the WYSIWYG preview.
=> Fix XSS security with the wysiwyg preview

README.md
NodeJS 14 is supported now, so remove the hint that it's not supported
=> Adapt README.md because NodeJS 14 is supported now

packages/strapi-admin/package.json, packages/strapi-plugin-upload/package.json
fixes #8413 
Issue with upstream package causing a problem on windows, issue fixed upstream
https://github.com/strapi/strapi/issues/8413
=> Fix #8413 - Immer dependancy

docs/v3.x/guides/databases.md
Hello, and thanks for building Strapi, we're using it for our next-gen website and it looks very promising.
I started my project using the quickstart option, but quickly wanted to move on to my PostgreSQL instance to get a setup as close to production as possible (also, I had to use Docker anyway since I have Node v14 on my machine, and well docker-compose just works). So I wen through the configuration to change my database settings, and looked at the documentation to find the relevant parameters. Having two pages with the same title made it difficult for me to find the right options since the guide page does not talk about PostgreSQL or MySQL. This PR aims to add the missing link between the two pages.
Added a section in the Databases guide referring to the configuration options for SQL …
=> DOC: Reference the configuration options for SQL databases from the Databases guide

README.md
=> Strapi requires NodeJS between equals or greater than 10.16 and equals or less than 14

packages/strapi-generate-new/lib/resources/json/package.json.js, packages/strapi-generate-plugin/json/package.json.js
Projects were being generated with the node engine `>=10.0.0` and it was causing issues deploying on heroku which watches this to figure out which version of node to install
We don't support node v15
https://forum.strapi.io/t/how-do-i-connect-heroku-to-strapi/703/5
=> Fix project generation with wrong node engine spec

docs/v3.x/guides/slug.md
After following [this guide](https://strapi.io/documentation/v3.x/guides/slug.html#auto-create-update-the-slug-attribute), I was receiving server errors in my app when attempting to publish content whose content type had an automatically generated slug. I found that the lack of if statement generates runtime errors.
I added an if statement to the code snippet.
Generates errors on other events that invoke the lifecycle method.
N/A
=> [Docs] Add missing if statement to guide on slug generation

docs/v3.x/migration-guide/README.md, docs/v3.x/migration-guide/migration-guide-3.2.5-to-3.3.0.md
This PR adds the migration guide for 3.2.5 to 3.3
So users can migrate
=> Add migration guide

packages/strapi-plugin-graphql/package.json
update `graphql-tools` package to **4.0.8** to use **GraphQL v15** syntaxes.
related to #8374
=> Upgrade graphql-tools package to use GraphQL v15

docs/v3.x/concepts/configurations.md, docs/v3.x/guides/scheduled-publication.md, packages/strapi/lib/middlewares/cron/index.js
I have added cron timezone configuration on the cron initialisation hook. Strapi uses `node-scheduler`, the way you add timezone with this library is mentioned [here](https://github.com/node-schedule/node-schedule/issues/217#issuecomment-478624773).  I implemented the timezone feature in a similar manner
As mentioned in [3099](https://github.com/strapi/strapi/issues/3099)
None
=> Added timezone for cron jobs

docs/v3.x/admin-panel/deploy.md
Updated typo in redirect URL to proxy section on admin panel deployment section **NOTE**.
https://strapi.io/documentation/v3.x/admin-panel/deploy.html#deploy-the-administration-panel-on-another-server-aws-s3-azure-etc-than-the-api
To improve the doc experience and to avoid an unnecessary 404 Not Found
None
=> typo fix in the redirect url

packages/strapi-provider-email-nodemailer/LICENSE, packages/strapi-provider-email-nodemailer/README.md, packages/strapi-provider-email-nodemailer/lib/index.js, packages/strapi-provider-email-nodemailer/package.json, yarn.lock
This will merge repository https://github.com/yutikom/strapi-provider-email-nodemailer/ into this mono repo under
```
packages/strapi-provider-email-nodemailer
```
~I followed this [suggestion](https://stackoverflow.com/a/61450995) and ran the following commands:~
In summer I opened [issue 6998](https://github.com/strapi/strapi/issues/6998) because I had a terrible developer experience from a multitude of unmaintained or outdated 3rd party libraries for email delivery through SMTP. As explained in the issue, we made `strapi-provider-email-nodemailer` compatible with version 3.
I think the best idea would be to incorporate the library into the main strapi mono repository, so it does not get out of sync and stays maintained. Strapi is already maintaining several proprietary email providers …
=> Maintain strapi-provider-email-nodemailer

packages/strapi-provider-upload-cloudinary/lib/index.js
Handle the case with strapi-provider-upload-cloudinary when trying to delete a file that is already deleted in Cloudinary. Cloudinary responds with `{ result: 'not found' }` when trying to delete a non-existent file. This is added as an extra condition to be checked in strapi-provider-upload-cloudinary before throwing an error.
When using strapi-provider-upload-cloudinary and the file is already deleted in Cloudinary, that file cannot be deleted from the Strapi UI and throws an internal server error.
Fix #5729 Cannot delete file already deleted in Cloudinary
=> Allow deleting file that is already deleted in Cloudinary

docs/v3.x/deployment/heroku.md
Fixes usage of PG on Heroku so it doesn't use the SQLite database
Heroku doesn't set `NODE_ENV` by default to production anymore
N/A
=> Update Heroku guide to set NODE_ENV to production

docs/.vuepress/theme/components/Navbar.vue
Make it more clear the user is viewing old documentation.
Old:
This PR:
Temporary until we can remove the beta docs
N/A
=> Make the beta docs more clear, depreciated notice

README.md, docs/v3.x/deployment/render.md, docs/v3.x/getting-started/deployment.md, docs/v3.x/getting-started/installation.md, docs/v3.x/installation/render.md
I added docs on deploying Strapi to Render, as discussed with @derrickmehaffy and @malgamves: https://github.com/strapi/community-content/issues/166. Feedback is very welcome.
Would it be possible to add a "Deploy on Render" button at the top of the main README? I would've done it myself, but it looks like the button images need to be generated and uploaded to assets.strapi.io.
=> Add Render as a deployment option

docs/v3.x/deployment/heroku.md
Signed-off-by: akhilmhdh <akhilmhdh@gmail.com>
- Fixed broken link inside heroku-deployment section 
- Link pointing towards the admin-user creation in quick start guide
- Better doc
- Better user experience
#8710
=> fixed admin-tutorial broken link in heroku-deployment

examples/getstarted/.gitignore, packages/strapi-generate-new/lib/resources/dot-files/gitignore
`.strapi-updater.json` was in the `.gitignore` of the example app but not in the `.gitignore` generated by `generate-new`. Causing issues in some environments : https://forum.strapi.io/t/error-open-packages-api-strapi-updater-json-permission-denied/1255/2
Some other variables were different between the 2 gitignores, I harmonized them.
=> Update gitignore in example and in generate-new

docs/v3.x/guides/jwt-validation.md
In the catch block the code would never reach the return statement, hence removing
=> fix(docs): Remove unreachable code

packages/strapi-connector-mongoose/lib/utils/index.js
Mirrors functionality of Bookshelf for custom types:
https://github.com/strapi/strapi/blob/6b6c1e2f7d5ae969f92b6f9a9b145944df53cda3/packages/strapi-connector-bookshelf/lib/build-database-schema.js#L149-L152
Custom fields and assigning a field a specific type in the database, such as with [this guide](https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms?utm_content=144907300&utm_medium=social&utm_source=twitter&hss_channel=tw-3832252517)
N/A reported on slack
=> Add support for columnType in Mongoose

docs/v3.x/concepts/services.md
fix doc typo for singleType in services.md, specifically at createOrUpdate section
currently when i try to follow createOrUpdate, i got error `findOne is not a function`. so i know this is a typo because it related to #7721
Issue:  #7718
PR: #7721
PR attempt: #8763
=> Docs fix type singleType findOne

packages/strapi/bin/strapi.js
When running the docker container I got weird output when initializing the container. This was caused by the fact that it runs `strapi -v` and this option no longer works. It seems it broke in c81af9a1d0b16cdc83cf1a0b73bd3012ebb80476 where `program.version(...)` got replaced with `program.option(...)` without an associated `.command(...)` to execute the option. I have changed `.option()` to `.version()`.
To get `strapi -v` and `strapi --version` to work again.
It seems noone noticed.
=> Fix `strapi -v` and `strapi --version` options

docs/v3.x/concepts/services.md
Fix bug **_strapi.entityValidator.validateEntity_** is not a function
Fix so that the document show the correct function name. **validateEntityCreation** instead of **validateEntity**
It seems that the validateEntity function no longer exists or it was renamed to validateEntityCreation but the document wasn't updated.
No
=> Change validateEntity to validateEntityCreation

docs/.vuepress/public/assets/migrations/scripts/migrate-3.4.0.js, docs/v3.x/migration-guide/README.md, docs/v3.x/migration-guide/migration-guide-3.3.x-to-3.4.0.md
The script has to be tested on a strapi app with branch `feature/relational-fields` (because it needs the refacto code).
=> Add migration script and guide

packages/strapi-connector-mongoose/lib/buildQuery.js, packages/strapi-connector-mongoose/lib/queries.js
When a many-to-many or a many-way relation is added to a model while some entity already exist, the existing entities are not updated with an empty array, resulting in some bugs.
I fixed the queries, is it enough or should we make sure the empty arrays are added ?
=> Fix mongo preview when array is missing

packages/strapi-connector-bookshelf/lib/build-database-schema.js, packages/strapi-connector-bookshelf/lib/migrations/create-migration-runner.js, packages/strapi-connector-bookshelf/lib/migrations/draft-publish-migration.js, packages/strapi-database/test/migration-draft-publish.test.e2e.js
After disabling _draft&publish_ with _sqlite_, the indexes were gone.
It's because of this bug: https://github.com/knex/knex/issues/631
=> Fix migration when disabling dp on sqlite

packages/strapi-plugin-content-manager/admin/src/utils/removeKeyInObject.js, packages/strapi-plugin-content-manager/admin/src/utils/tests/removeKeyInObject.test.js
Fixes the bug in function removed specified key in object. 
Previously, after the function array of arrays would be returned as array of objects. This PR fixes this bug.
#8994
=> Fixed removeKeyInObject function

packages/strapi/lib/services/entity-service.js
The files variable is sent in as {}, so if (files) is always true
Slight optimisation, found it when trying to figure out why my update hooks didn't keep the values, and it turned out it's because it's always entering the if statement and doing a findOne.
=> if there are files

packages/strapi-connector-mongoose/lib/queries.js, packages/strapi/tests/publication-state.test.e2e.js
Fix a bug where calling the `query().count()` method on mongoose don't take the `publicationState` filter into account.
fix #9092
=> Fix count method w/ D&P filters on MongoDB

CONTRIBUTING.md
- Provides information to M1 users on how to fix sharp troubles when setting the project up.
- Incrementing a title number (there was two "5")
M1 users may not be able to run the project in dev mode without that.
Not in this repository but in the sharp's one: https://github.com/lovell/sharp/issues/2460
Tested on Node v12.20.1 / yarn 1.22.10
=> Adding documentation for M1 users

packages/strapi-plugin-content-manager/services/utils/configuration/__tests__/attributes.test.js, packages/strapi-plugin-content-manager/services/utils/configuration/attributes.js
Sortable param was set to false for relational fields when restarting the app
fixes #9099
=> Fix sortable config disabled at launch

packages/strapi/lib/middlewares/public/index.js
=> Fix REST api for content-types that start with "admin"

packages/strapi-plugin-users-permissions/config/functions/bootstrap.js, packages/strapi-plugin-users-permissions/package.json, packages/strapi-plugin-users-permissions/services/Providers.js, yarn.lock
=> Fix instagram login after instagram API changed

packages/strapi-generate-new/lib/utils/db-client-dependencies.js
Forced SQLite3 v5.0.0 instead of ^5.0.0
Fixes issue for Windows users and an issue with SQLite3 v5.0.1
fixes #9120 
https://github.com/mapbox/node-sqlite3/issues/1424
=> Fix for failing SQLite3 issue on windows

packages/strapi-connector-bookshelf/lib/buildQuery.js
When using the `contains` (or `ncontains`) database filter, it casts column to `CHAR` datatype so calling `LOWER(string)` function doesn't throw an error when a passed value is an integer
It crashed on the non-text field (e.g. `id`)
Fixes https://github.com/strapi/strapi/issues/7854
=> Fix lower() error when running on non-string column

packages/strapi-plugin-upload/config/schema.graphql.js, packages/strapi-plugin-upload/tests/graphqlUpload.test.e2e.js
Rebased version of https://github.com/strapi/strapi/pull/8494
Accept info fields when uploading file through GraphQL
To send http request lesser.
closes #8493
=> [Rebased] Accept info fields when uploading file through GraphQL

packages/strapi-plugin-users-permissions/config/functions/bootstrap.js, packages/strapi-plugin-users-permissions/services/Providers.js
Added support for a reddit provider.
There currently is no reddit provider.
=> Add reddit auth provider

packages/strapi-admin/package.json, packages/strapi-admin/webpack.config.dev.js, yarn.lock
Adds a new command: `yarn analyze:bundle` in strapi-admin that aims to display a tree map of the bundles and their dependencies
Helping isolating loading bottlenecks, provide information
=> Add webpack bundle analyzer in admin

packages/strapi-plugin-upload/services/image-manipulation.js
Prevent returning optimized image if it's larger than the original. It's mostly visible on PNG images, and it's a known behavior of `sharp` https://github.com/lovell/sharp/issues/1110, https://github.com/lovell/sharp/issues/1017, https://github.com/lovell/sharp/issues/600, https://github.com/lovell/sharp/issues/478.
When the user is uploading an already optimized image, or just the optimizer is unable to reduce the size, we should keep the image that is smaller.
I didn't find any of them.
=> Prevent returning optimized image if it's larger than original

packages/strapi-plugin-upload/services/image-manipulation.js
This PR changes the upload plugin to read the responsive image breakpoints from the config instead of being hardcoded.
The hardcoded values are still available as defaults if the config is not present.
Currently adjusting the sizing or names of the responsive images requires overriding the entire `image-manipulation.js` file, which is prone to errors and breaking when upgrading.
=> strapi-plugin-upload: Read responsive breakpoints from config

packages/strapi-plugin-content-manager/admin/src/components/Container/index.js
It increases the padding bottom of the container in content manager.
The blue button (for questions) at the bottom right corner is overlapping over pagination in some cases:
The following is the fix in action:
https://github.com/strapi/strapi/issues/9186
=> Increasing padding bottom to prevent question button from overlapping

packages/strapi-plugin-documentation/public/login.html
Quick fix for language on the /documentation/login page
"to access to documentation" reads a little weird
None that I know of.
=> fix typo "to access to"

packages/strapi-utils/lib/sanitize-entity.js
Fix sanitize removing polymorphic relations.
Fix https://github.com/strapi/strapi/issues/9308
=> Fix sanitize removing polymorphic relations

packages/strapi-plugin-graphql/services/type-definitions.js
Test fix for many many perf issues
=> Fix some many many perf issues in graphQL

packages/strapi-connector-bookshelf/lib/knex.js
=> Fix crash when database (SQL) options are not defined

packages/strapi-generate-new/lib/resources/json/package.json.js
Sets the default npm version to npm v6 in the package.json engines
There are currently some breaking changes in npm v7 which has now gone into general release. This should stop providers like Heroku from trying to use npm v7 by default
Related to the following comment: https://github.com/strapi/strapi/issues/9206#issuecomment-773036382
fixes: #8786
=> Do not use npm v7 on new projects

packages/strapi-helper-plugin/lib/src/components/Tabs/TabComponents.js, packages/strapi-helper-plugin/lib/src/components/Tabs/index.js, packages/strapi-helper-plugin/lib/src/index.js, packages/strapi-plugin-i18n/admin/src/components/LocaleRow/index.js, packages/strapi-plugin-i18n/admin/src/components/ModalEdit/BaseForm.js, packages/strapi-plugin-i18n/admin/src/components/ModalEdit/index.js, packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js, packages/strapi-plugin-i18n/admin/src/translations/en.json
- Iterating on the i18n ModalEdit, switching the input and positioning elements
- Suggests a declarative tabs navigation API using indexes. Selecting the first Tab will display the content of the first TabPanel.
If needed, we can add keyboard navigation (using left / right arrow) quite easily to this one.
```jsx
<TabsNav defaultSelection={0} label="This is an aria label" id="i18n-settings-tabs">
<Tabs position="right">
<Tab>Base settings</Tab>
<Tab>Advanced settings</Tab>
</Tabs>
<TabsPanel>
<TabPanel>
<BaseForm />
</TabPanel>
<TabPanel>
<AdvancedForm />
</TabPanel>
</TabsPanel>
</TabsNav>
```
=> [I18N] add tabs for navigating between forms

packages/strapi-plugin-documentation/services/Documentation.js
It adds missing enums for associations.
Example. Before:
```  
"components": {
"schemas": {
"Post": {
"properties": {
// ...fields
"employee": {
"properties": {
"id": {
"type": "string"
},
// enum of collection Employee. generated as string
"location": {
"type": "string",
},
}
},
// high-level enum (generated correctly)
"language": {
"type": "string",
"default": "RU",
"enum": [
"RU",
"EN"
]
},
}
},
}
},
```
after:
```
"components": {
"schemas": {
"Post": {
"properties": {
// ...fields
"employee": {
"properties": {
"id": {
"type": "string"
},
// enum of Employee. generated correctly
"location": {
"type": "string",
"enum": [
"SAINT_PETERSBURG",
"MOSCOW",
"KALININGRAD",
]
},
}
},
// high-level enum (generated correctly)
"language": {
"type": "string",
"default": "RU",
"enum": [
"RU",
"EN"
] …
```
=> plugin-documentation: added enum for associations

packages/strapi-plugin-documentation/services/Documentation.js
It fixes generating of types in case of using 'manyWay' relation
The plugin generates a single instance ref instead of an array for one-to-many (manyWay) relations.
[#9280](https://github.com/strapi/strapi/issues/9280)
=> plugin-documentation: added missed manyWay relation

packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/component.test.js, packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/content-type.test.js, packages/strapi-plugin-content-type-builder/controllers/validation/__tests__/types.test.js, packages/strapi-plugin-content-type-builder/controllers/validation/model-schema.js, packages/strapi-plugin-content-type-builder/controllers/validation/relations.js, packages/strapi-plugin-content-type-builder/controllers/validation/types.js, packages/strapi-plugin-content-type-builder/services/Components.js, packages/strapi-plugin-content-type-builder/services/ContentTypes.js, packages/strapi-plugin-content-type-builder/services/__tests__/__snapshots__/content-types.test.js.snap, packages/strapi-plugin-content-type-builder/services/__tests__/content-types.test.js, packages/strapi-plugin-content-type-builder/services/schema-builder/component-builder.js, packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js, packages/strapi-plugin-content-type-builder/tests/components.test.e2e.js, packages/strapi-plugin-content-type-builder/tests/content-types.test.e2e.js, test/__snapshots__/all.test.e2e.js.snap
Ability to toggle i18n for an CT and for fields.
Ability to add custom keys in the attributes schema (such as "index" for mongo) : based on discussion #8022
=> handle toggle i18n on CT and fields

packages/strapi-plugin-i18n/admin/src/components/ModalCreate/BaseForm.js, packages/strapi-plugin-i18n/admin/src/components/ModalCreate/index.js, packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js, packages/strapi-plugin-i18n/admin/src/hooks/useAddLocale/index.js, packages/strapi-plugin-i18n/admin/src/schemas.js, packages/strapi-plugin-i18n/admin/src/translations/en.json
Allows to add a locale from the iso list.
- Log in the dashboard
- Go to settings (left side menu)
- Select "Internationalisation" in the sub-left menu
- Click the "Add a locale" button
- Play with the form
- Validate at some point
- After adding a locale, make sure the new locale is listed in the list
=> [i18n] add a locale from the ISO list

packages/strapi-plugin-upload/middlewares/upload/index.js
Make `strapi-plugin-upload` accepts `localServer` configuration for `koa-static`.
To support custom `koa-static` options such as `maxage`
https://github.com/strapi/strapi/issues/6645#issuecomment-645217698
fixes #8809
=> strapi-plugin-upload accepts localServer configuration

packages/strapi-plugin-i18n/admin/src/components/ModalDelete/index.js, packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js, packages/strapi-plugin-i18n/admin/src/hooks/useDeleteLocale/index.js
Allows to delete a locale from the iso list.
It's not possible right now (except by console.logging in the code) until https://github.com/strapi/strapi/pull/9393 gets merged
=> [i18n] delete a locale

packages/strapi-plugin-i18n/admin/src/components/ModalCreate/index.js, packages/strapi-plugin-i18n/admin/src/hooks/useAddLocale/index.js
Add `isDefault` to the POST request when adding a locale to a project
=> [i18n] fixing add locale params

packages/strapi-plugin-sentry/README.md, packages/strapi-plugin-sentry/config/settings.json, packages/strapi-plugin-sentry/services/sentry.js
Adds a new `init` option to strapi-plugin-sentry. It allows users to customize their Sentry instance
=> Add init option to strapi-plugin-sentry

packages/strapi-connector-bookshelf/lib/build-database-schema.js, packages/strapi-connector-mongoose/lib/mount-models.js, packages/strapi-database/lib/__tests__/lifecycle-manager.test.js, packages/strapi-database/lib/database-manager.js, packages/strapi-database/lib/lifecycle-manager.js, packages/strapi-database/lib/migration-manager.js, packages/strapi-database/lib/queries/__tests__/create-query.test.js, packages/strapi-database/lib/utils/lifecycles.js, packages/strapi-plugin-i18n/config/functions/bootstrap.js, packages/strapi-plugin-i18n/services/__tests__/localizations.test.js, packages/strapi-plugin-i18n/services/localizations.js
- Adds a lifecycle manager to support programmatically adding lifecycles to models without changing the model lifecycles.
- Add lifecycles handler to manage `locale` & `localizations` fields
I think this approach is good enough for the remainder of v3 but it is not want I think we should have later on. 
registering lifecycles should allow for passing multiple models at once & the actions should receive the context of the query differently. To do so we would also need to change the current model lifecycles API that's why I chose to wait for v4
=> Add Lifecycles for i18n 

packages/strapi-plugin-i18n/admin/src/permissions.js
It fixes permissions on read for the locale settings
=> [i18n] fix typo on permissions

packages/strapi-admin/package.json
This minor change fixes the repository.url field in strapi-admin/package.json.
=> Fix repository url in strapi-admin/package.json

packages/strapi-admin/webpack.config.js
It fixes setting up the build path within the strapi-admin package.
The current implementation splits the path of the project at the first occurrence of the string `src` in order to rebuild it later considering special behavior when building an ee edition application. This causes an issue when the full path of the project already contains a `src` directory, e.g. `~/projects/src/MyStrapiApp`.
The PR modifies the code in such a way, that the last occurrence of `src` within the path is chosen as split location.
Sorry, I am just learning NodeJS development. I've tested it locally by altering a regular installation and then it worked for me.
=> Update of webpack configuration: fix #9442 

examples/getstarted/package.json, packages/strapi-connector-bookshelf/package.json, packages/strapi-generate-new/lib/utils/db-client-dependencies.js
=> Fix knex, pg, mysql versions

packages/strapi-plugin-i18n/admin/src/components/LocaleList/index.js, packages/strapi-plugin-i18n/admin/src/components/ModalCreate/index.js, packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/LocaleSettingsPage.js
Make sure to refresh the list of locales when adding a new one
- Login
- Go the the settings on the left sidebar
- Select "Internationlization" on the sub-sidebar
- Click the "Add a locale" button
- Fill the form
- Click save 
- **The list of locales should be refreshed with the new lang**
=> Fixing refresh when adding a new locale

packages/strapi-admin/admin/src/containers/Admin/Logout/components.js
=> Fixing dropdown background

packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/reducer.js
This commit fixes an error that occurs when an ADD_RELATION action is
called with an empty value from a relationship field.
To be extra safe, the fix is applied both in the component and the
reducer.
- Add isEmpty check in SelectWrapper component when adding relations.
- Add array check in reducer function for ADD_RELATION.
Fix #9500
- Add an extra check to the `action.value` item, thereby avoiding reading from an `undefined` object.
It might be the [`react-select` `onChange`](https://github.com/strapi/strapi/blob/cd809720ba002cb74e33b93b9b2abbc121aac6c9/packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js#L85) event that sends empty values to the reducer when hitting the backspace key. Because the select box is an external dependency, changing the reducer was …
=> Fix TypeError: action.value[0] is undefined

packages/strapi-plugin-content-manager/admin/src/components/WysiwygEditor/index.js
When adding Arabic into the RichText fields of Strapi, the text will automatically be aligned to the right after this change. 
I cannot identify any change to the interface after this change other than this automation. 
To test, copy and paste some Arabic into a Rich Text field and it will align right automatically. 
Resolves: https://github.com/strapi/strapi/issues/9412
=> Add RTL support to WysiwygEditor

packages/strapi-plugin-graphql/services/schema-generator.js
As mentionned here https://github.com/strapi/strapi/pull/6146, we merged a PR that change the config name for the federation config for graphql. I'm reverting it the the original name here
=> Fix incorrect graphql config var

packages/strapi-connector-mongoose/lib/utils/connectivity.js
Uses the `useUnifiedTopology` option when creating a new project with MongoDB
Prevents the following warning when creating a new project (we already enable this setting normally, just not during the connection test)
> (node:44216) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> (Use node --trace-deprecation ... to show where the warning was created)
Create a new project selecting a custom MongoDB install, notice the lack of a warning message.
fixes: #9198
=> Use the MongoDB setting useUnifiedTopology when testing connection

packages/strapi/lib/services/__tests__/core-store.test.js, packages/strapi/lib/services/core-store.js
This PR adds a `del` method to the CoreStore. I had to call it `del` as an error was raised when using `delete`
For security and cleaning purposes, I would like to be able to delete a key from the store. 
I could not find where to add store tests but I tested it locally in a plugin the following way:
```javascript
const pluginStore = () => strapi.store({
environment: strapi.config.environment,
type: 'plugin',
name: 'myStore'
})
const key = { key: 'mykey', value: 'myvalue' }
await pluginStore().set(key)
const before = await pluginStore().get(key)
await pluginStore().del(key)
const after = await pluginStore().get(key)
console.log({ before, after })
```
fixes: #9533
=> Add delete function in store

packages/strapi-helper-plugin/lib/src/components/InjectionZone/index.js, packages/strapi-helper-plugin/lib/src/index.js, packages/strapi-plugin-content-manager/admin/src/containers/ListView/FieldPicker/index.js, packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js, packages/strapi-plugin-content-manager/admin/src/index.js, packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js, packages/strapi-plugin-i18n/admin/src/index.js, packages/strapi-plugin-i18n/admin/src/utils/tests/mutateCTBContentTypeSchema.test.js
Adds a locale dropdown next to the "settings" option in ListView
Make sure to have locales set in I18N settings. (at least one)
- Login the application
- On the left sidebar, select a content type
- You're not on the List view of that content type. You should see a dropdown listing the available locales
=> [i18n] add locale dropdown in listview filters

packages/strapi/lib/middlewares/parser/index.js
Throwing error inside of a controller (using plain javascript) results in a different error in parser middleware.
Before calling (`String.prototype.includes`) method on the `message` property on the error object, a check should be performed to see if the `message` property is defined on the error instance so no runtime `TypeError` is thrown.
Throw statements from within the code resulted in a `TypeError` with stack trace leading to `Strapi` parser middleware.
Instead, error logging should have appropriate stack trace from within the file where the error is thrown from.
> Just in custom controller code, instead of usual ctx.throw(400, "something") write throw "something"
Reference: https://github.com/strapi/strapi/issues/9356#issuecomment-783571349
Related issue: #9356
No new test cases …
=> [Fix]: 🐛 Strapi parser middleware, catch block error logging

packages/strapi-helper-plugin/lib/src/components/Select/index.js, packages/strapi-plugin-i18n/admin/src/components/ModalCreate/BaseForm.js, packages/strapi-plugin-i18n/admin/src/components/ModalEdit/BaseForm.js
Fixes the carret in the ModalCreate / ModalEdit
=> Fix carret for modal edit/create locale dropdown

packages/strapi-admin/admin/src/translations/de.json
Fix german translation.
Resolves a bad impression on the first screen you get after installing strapi.
=> Fix german translation

packages/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/Banner.js
Display the "new component" message if the displayed value is strictly `null` or `undefined`, and display valid "falsey" values otherwise.
The repeatable component banner displays the main field from the component, or a "new component" message if the component is not yet created. It shows the "new component" message when the value of the component's main field is "falsey". However, if the main field of the component is a number, boolean, or string, then perfectly valid values such as `0` and `false` are overridden by the "new component" message.
Create a component and configure the "main" field to be a number field. Create a component instance with the value of that field as `0`. It should display "0" instead of the "new component" message in the banner.
=> Fix display of falsey values in component banner

packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
Move the call to the sendData function outside the setState callback. The function sendData compare `prevState` and `currentState`. If we call the sendData in the setState callback, we compare `currentState` vs `currentState`.
1. Create a content-type with a Rich Text field.
2. Create a new entry of that content-type.
3. Edit the entry you just created.
4. Select some text in the Rich Text field and click one of the formatting buttons (e.g. Bold).
5. You should be able to save the entry.
fix https://github.com/strapi/strapi/issues/9589
=> Fix WYSIWYG state

packages/strapi-connector-bookshelf/lib/mount-models.js
Use the polymorphic attribute info to name the type field correctly.
Currently, It is  hardcoded to `related_type`
Fix error with polymorphic relations when the attribute name is different to `related`
Look at the last comment of the issue
https://github.com/strapi/strapi/issues/5348
=> Fix error with polymorphic relations when the attribute name is different to related

packages/strapi-plugin-content-type-builder/admin/src/translations/ko.json
It fixes Korean translations for `relation.manyToOne`
Previously shown as `Article N : 1 Comments` while it should show `Article 1 : N Comments`
Since en.json uses `has many` for this description, do the same for Korean translation
Previous translation shows wrong description that might confuse the user.
This is the current description shown on Korean language setting:
This is the same description shown on English language setting:
Tested on v3.5.3
N/A
=> Fix Korean translations for relation.manyToOne

packages/strapi-connector-bookshelf/lib/mount-models.js, packages/strapi-connector-mongoose/lib/mount-models.js, packages/strapi-database/lib/queries/relations-counts-queries.js, packages/strapi-plugin-content-manager/services/data-mapper.js, packages/strapi-plugin-content-type-builder/utils/attributes.js, packages/strapi-plugin-i18n/config/functions/register.js, packages/strapi-utils/lib/__tests__/content-types.test.js, packages/strapi-utils/lib/content-types.js, packages/strapi-utils/lib/sanitize-entity.js, packages/strapi/lib/core-api/service.js
Generalize usage or visible & wirtable on attributes instead of using hardcoded properties
=> Split logic cleanly between visible & writable attributes

packages/strapi-admin/admin/src/containers/LeftMenu/utils/generateModelsLinks.js, packages/strapi-helper-plugin/lib/src/hooks/useUserPermissions/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewLayoutManager/index.js, packages/strapi-plugin-content-manager/admin/src/containers/ListView/ListViewLayout.js, packages/strapi-plugin-content-manager/admin/src/containers/RBACManager/useSyncRbac.js, packages/strapi-plugin-i18n/admin/src/middlewares/localePermissionMiddleware.js
It allows to switch from one locale to another in the edit view
In order to apply the correct permissions depending on the locale
In one terminal window clone the monorepo checkout the branch corresponding to #9535 PR's branch && start the getstarted app.
In another terminal checkout the i18n/editview-rbac-manager branch and start the webpack devServer
Related issue(s)/PR(s)
Waiting for #9697 to be merged
=> [i18n] Edit view RBAC management

packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeFormWrapper/index.js, packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeFormWrapper/index.js, packages/strapi-plugin-content-manager/admin/src/reducers.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/actions.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/constants.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/index.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/reducer.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/selectors.js, packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/tests/crudReducer.test.js
It migrates the CRUD of the edit view to redux
So a plugin can override the actions
1. In one terminal window clone the monorepo checkout the branch corresponding to #9535 PR's branch && start the `getstarted` app.
2. In another terminal checkout the `i18n/edit-view-redux` branch and start the webpack `devServer`
=> [i18n] Migrate CollectionTypeFormWrapper and SingleTypeFormWrapper to redux

packages/strapi-plugin-i18n/admin/src/utils/mutateCTBContentTypeSchema.js, packages/strapi-plugin-i18n/admin/src/utils/tests/mutateCTBContentTypeSchema.test.js
It fixes the bug that caused all non localized field to be set to true when updating a content type schema that already had i18n enabled
=> [I18n] Fix schema mutation

packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js, packages/strapi-plugin-i18n/admin/src/middlewares/localeQueryParamsMiddleware.js, packages/strapi-plugin-i18n/admin/src/middlewares/tests/localeQueryParamsMiddleware.test.js, packages/strapi-plugin-i18n/admin/src/utils/getDefaultLocale.js, packages/strapi-plugin-i18n/admin/src/utils/tests/getDefaultLocale.test.js
Set the initial locale in the i18n middleware using the following rules (in that order):
- If a CT is allowed to be read and that it has the default locale on it, it returns the **default locale**
- If a CT is allowed to be created and that it has the default locale on it, it returns the **default locale**
- If a CT is allowed to be read and that it has NOT the default locale on it, it returns the **first allowed locale**
- If a CT is allowed to be created and that it has NOT the default locale on it, it returns the **first allowed locale**
- else, it returns null
=> [i18n/rbac] initialize with the first authorized locale

packages/strapi-plugin-content-manager/admin/src/components/CustomTable/styledComponents.js, packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/LocaleListCell.js, packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/tests/LocaleListCell.test.js, packages/strapi-plugin-i18n/admin/src/middlewares/localeQueryParamsMiddleware.js, packages/strapi-plugin-i18n/admin/src/middlewares/tests/localeQueryParamsMiddleware.test.js
It adds a locale column using the `localeQueryParamsMiddleware` in i18n using the following rules:
- Show only the complementary to the actual locale (if I'm looking to "EN" entries, I don't show "En" in the list of locales of the row)
- The default locale is always the first and it has a `(default)` suffix
- Other locales are ordered in alphabetical order
_NB: the weird name is based on a custom modification I did on my set to test i18n settings edition_
=> [i18n] add the locale column in the CM list view

packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
Shows the locale dropdown even when the user doesn't have the locale activated so that they can switch language.
=> [i18n/rbac] show locale picker even when not authorized

packages/strapi-plugin-i18n/admin/src/hooks/useAddLocale/index.js, packages/strapi-plugin-i18n/admin/src/translations/en.json
Does not add a line in the array when the locale already exists and show an explicit toast about that
=> [i18n] don't add locale in settings when it already exists

packages/strapi-helper-plugin/lib/src/components/InjectionZone/InjectionZone.js, packages/strapi-helper-plugin/lib/src/components/InjectionZone/InjectionZoneList.js, packages/strapi-helper-plugin/lib/src/components/InjectionZone/index.js, packages/strapi-helper-plugin/lib/src/components/InjectionZone/useInjectionZone.js, packages/strapi-helper-plugin/lib/src/components/PopUpWarning/index.js, packages/strapi-helper-plugin/lib/src/index.js, packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js, packages/strapi-plugin-content-manager/admin/src/index.js, packages/strapi-plugin-i18n/admin/src/components/DeleteModalAdditionalInfos/index.js, packages/strapi-plugin-i18n/admin/src/index.js, packages/strapi-plugin-i18n/admin/src/translations/en.json
- Creates an `InjectionZoneList` component for list-based injection zone (semantic)
- Modify the `PopupWarning` so that it accepts children in its body in order to enhance it with injection zones
- Configure an Injection zone in the content-manager-plugin in order to show addition information there
- Create a component in plugin i18n that will be injected in the delete modal injection zone of the content-manager
=> [I18n/rbac] add additional infos in delete modal

packages/strapi-plugin-i18n/admin/src/components/ModalCreate/BaseForm.js
Allows to filter from the start in the I18N settings page when trying to add a new locale to the project
Better UX
- Log in the app
- Go on the Settings page (left sidebar)
- Select internationalization in the sub-left sidebar
- Click "Add a locale" button on the top right-hand corner
- Play with the locale dropdown
=> [i18n] add filters from the start

packages/strapi-plugin-users-permissions/services/UsersPermissions.js
=> Just a minor typo

packages/strapi-plugin-i18n/admin/src/hooks/useAddLocale/index.js
When trying to add a locale that already exists, we use to show a message informing the user. However, the loading information set on the submit button was never reset.
This PR makes sure that the loading information on the submit button is well reset on success AND on error.
=> [i18n] hide loader when trying to add a locale that already exists

packages/strapi-helper-plugin/lib/src/components/Select/styles.js
Fixes the padding for the locale dropdown in the settings when adding a new locale
=> [I18N] Fix padding in dropdown locale (settings)

packages/strapi-admin/admin/src/containers/ProfilePage/index.js
Add bottom margin to the user preferences page so that we can see the locale dropdown entierly
=> Add bottom margin to the user preferences page

packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js
When a locale has been added without a display name, let's show the code instead in the locale picker of the ListView
=> Display locale code instead of name when name is not defined

packages/strapi-helper-plugin/lib/src/components/InjectionZone/InjectionZoneList.js
There's a difference on the way FF and Chrome manage list-style-type on UL elements. I had to move to use a `:before` pseudo-class in order to have the same behavior and to see that bullet point in the delete locale content modal
=> Fix bullet position in delete content for a locale modal

packages/strapi-plugin-content-manager/admin/src/containers/ListView/FieldPicker/index.js
Fix the margin between the cog SVG and the Carret SVG. I failed on the previous one and the space was 15px instead of 10px (because of the extra margin on the carret svg)
=> Fix margin cog again

packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js
When there was only 1 locale available, we still displayed the locale picker (empty) list content on the screen when clicking on the locale picker of the listview.
This created a weird and empty white box. This PR aims to hide this box when there is only one locale
=> Fix empty locale picker on listview

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Update the bug report template to state the new LTS version of Node
v12 is no longer the LTS version
N/A
N/A
=> Update bug report template with LTS version information

packages/strapi-plugin-i18n/services/__tests__/content-types.test.js, packages/strapi-plugin-i18n/services/content-types.js, packages/strapi-utils/lib/__tests__/content-types.test.js, packages/strapi-utils/lib/content-types.js
makes uid always localized in i18n
This avoids removing the unique constraint from DB in v3
=> UID should be localized in i18n

packages/strapi-plugin-i18n/admin/src/middlewares/extendCMEditViewLayoutMiddleware.js, packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCMEditViewLayoutMiddleware.test.js
it shows that uid fields are localised in the content manager / edit view
=> Uid fields are localised in CM

packages/strapi-utils/lib/build-query.js
Replaces the Error (when having `undefined` as value in a where filter) with an warning `strapi.log.warn`.
Fixes/gives a solution for the discussion in #8490.
1.
```js
return strapi.query('category').findOne({ id: undefined });
```
Returns 200, but gives an warning in the logs: _The value of field: 'id', in your where filter, is undefined._
2.
```js
return strapi.query('category').findOne({ unknownField: 1 });
```
Returns 400: _Your filters contain a field 'unknownField' that doesn't appear on your model definition nor it's relations_
3.
```js
return strapi.query('category').findOne({ undefinedUnknownField: undefined });
```
~Returns 400: The field 'undefinedUnknownField' in your where filter has undefined as value.
And~ gives warning in the logs: _The value of field: …
=> Fix undefined filter value Error (#8490)

packages/strapi-plugin-i18n/constants/__tests__/index.test.js, packages/strapi-plugin-i18n/constants/index.js, packages/strapi-plugin-i18n/services/__tests__/locales.test.js
Add an env var to set the init locale code on startup
=> Add an env var to set the init locale code on startup

packages/strapi-admin/admin/src/translations/es.json
Fixed a small but annoying typo in the spanish translation
The list in Settings > Roles page was showing literally the string `{número} usuario` instead of `1 usuario`.
Check Settings > Roles page in spanish
None (do you recommend to create an issue before the PR even for fixes small like this?)
=> Fix typo in spanish translation

packages/strapi-plugin-email/README.md, packages/strapi-provider-email-amazon-ses/README.md, packages/strapi-provider-email-mailgun/README.md, packages/strapi-provider-email-nodemailer/README.md, packages/strapi-provider-email-sendgrid/README.md, packages/strapi-provider-email-sendmail/README.md
Add a warning in the email provider & plugin readme to avoid errors when sending.
Changed the default mailgun api to the correct endpoint. see https://documentation.mailgun.com/en/latest/api-intro.html#introduction
=> Fix Email Provider Readme.

packages/strapi-plugin-i18n/services/core-api.js, packages/strapi-plugin-i18n/tests/graphql.test.e2e.js
Fix graphql naming to use the same input namine convention as the plugin
=> Fix graphql naming to use the same input naming convention as the graphql plugin

packages/strapi-plugin-graphql/services/shadow-crud.js, packages/strapi-plugin-i18n/config/functions/register.js
fix #10130
3 solutions exist:
1) replacing the primaryKey variable by `id` in the resolver (what I did)
2) `packages/strapi-plugin-i18n/config/functions/register.js`
```diff
- populate: ['id', 'locale', PUBLISHED_AT_ATTRIBUTE],
+ populate: ['_id', 'id', 'locale', PUBLISHED_AT_ATTRIBUTE],
```
3) automatically add `id` and `_id` in the populate option when it exist (avoid any problem if the user don't put `id` or `_id` in the populate option. However this option is not public so it should not happen)
=> [graphQL + mongo] Fix broken localizations query

packages/strapi-plugin-graphql/services/__tests__/resolvers-builder.test.js, packages/strapi-plugin-graphql/services/resolvers-builder.js
=> Fix #10125 - Accept falsy values returned by controllers in GraphQL queries and mutations

packages/strapi-utils/lib/build-query.js
The possessive `its` doesn't have an apostrophe.
https://www.dictionary.com/e/its-vs-its/
=> Fix typo in query error message

packages/strapi-provider-email-sendmail/README.md
Updating the `readme` file by adding the DKIM configuration example for `strapi-provider-email-sendmail`.
=> Add DKIM config example

packages/strapi-admin/services/permission/sections-builder/handlers.js, packages/strapi-admin/tests/admin-permission.test.e2e.js
The permission builder is currently ignoring all non-configurable attributes. This leads to missing fields for some CTs (eg: user-permissions::user).
This PR update the attribute validation and ignore only the non-visible attributes.
=> [RBAC] Ignore only non visible attributes instead of non configurable ones

packages/create-strapi-app/create-strapi-app.js
Fixes #5759
On Windows, an empty return from the `createQuickStartProject` function caused the process termination to hang.
Added explicit process termination for this platform
Command `yarn create strapi-app backend --quickstart --no-run` did not work as expected from the documentation.
Run command `yarn create strapi-app backend --quickstart --no-run`
In PR #6721 problem fixed by change return statement to `process.exit` but @alexandrebodin said that this is an incorrect decision.
I decided to fix it in the package `create-strapi-app` by getting the result of the promise and terminate process if the platform is windows
=> Fix issue with incorrect cli termination when using flags quickstart and no-run

packages/strapi-plugin-content-type-builder/admin/src/components/ListRow/index.js
It displays the name of the custom field in the content type builder list-view.
Fixes #10187
=> Fixes #10187

packages/strapi-admin/config/migrations/permissions-fields-to-properties.js
Fix usage of model.updateOne in admin migration to ensure compatibility with mongo < 4.2.
Aggregate (array) parameter is not available for model.updateOne until mongo 4.2.
should fix #10096
=> Fix compatibility issue for mongo < 4.2

packages/strapi-connector-bookshelf/lib/formatter.js, packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/cleanData.js
Stops using the built in Javascript date which reads the systems timezone by replacing `new Date()` with the date-fns function `parseISO` [see it's docs here](https://date-fns.org/v2.20.3/docs/parseISO)
if the string value passed from upstream in Strapi is `2021-04-14`:
date-fns function
```js
const cast = parseISO(value);
// returns: 2021-04-14T07:00:00.000Z
```
javascript native function
```js
const cast = new Date(value);
const castString = cast.toString();
// returns: Tue Apr 13 2021 17:00:00 GMT-0700 (Mountain Standard Time)
```
The problem is that the built in Javascript `Date()` will use the local systems timezone, and instead the date-fns has the ability to just parse the raw date string and not pass in the system timezone. …
=> Fix date field being parsed with a timezone

packages/strapi-admin/services/__tests__/permissions.engine.test.js, packages/strapi-admin/services/permission/engine.js
Fix a bug that causes the RBAC permissions that don't have any subject (for example `plugins::upload.read`) to ignore the attributed conditions.
Breaking RBAC (media library & other plugins)
- Open the getstarted app
- As a super admin upload an image to the media library
- As a super admin, give the Plugins/Upload/Read media library permission to the author role (if not already set + the is-creator condition should be checked)
- As an author, go to the media library, you shouldn't be able to see the uploaded image
fix #10221
=> Fix RBAC permissions without subject ignoring conditions

packages/strapi-plugin-users-permissions/config/functions/bootstrap.js, packages/strapi-plugin-users-permissions/services/Providers.js
This adds support for CAS as an OIDC login provider. CAS is supported by grant but there isn't a central CAS server so the `subdomain` parameter is required to be in the grant context so the URLs can be generated. If I ran a CAS server for a company at `https://my.company.com/cas` then the subdomain would be `my.company.com/cas`.  The fact that subdomain includes the whole domain and possibly some extra non-domain stuff is because that is how it is done in grant (for CAS and several other providers). https://github.com/simov/grant/blob/master/config/oauth.json#L148
We are currently using this as a strapi extension by overriding these same files in the `extensions\users-permissions` folder.
Edited: removed some stuff that was no longer accurate. After this PR was made initially, another …
=> Add support for login via cas - github.com/apereo/cas

packages/strapi-admin/admin/src/containers/Webhooks/ListView/index.js
Replaced link in webhooks page with proper documentation link
Doc link for webhooks returned a 404
Run Strapi application, go to settings => webhook and click on the documentation link
fixes #10294
=> Update webhook doc link

packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/index.js
=> Fixes #10328

packages/strapi-plugin-i18n/config/policies/validateLocaleCreation.js
Replace #10256
**Description**
With the Content-Manager API It was possible to create a related entry in the default locale, even if the default locale was already existing. To do it, you just had to create a new locale without specifying the locale.
=> Fix duplicate locale when creating an entry without specifying the locale

README.md
Changes the slack link to a discord one
Getting rid of slack
click the link
n/a
=> Update slack to discord

README.md, packages/strapi/README.md
- Removed the old Travis badge and swapped the Slack one for the Discord one
- Copied README to the strapi package root to update the NPM page (Suggested by @vcoisne )
Badges were broken
N/A
N/A
=> Update badges and copy README to main Strapi package for NPM

packages/core/admin/admin/src/pages/Admin/index.js, packages/core/admin/admin/src/pages/App/index.js, packages/core/admin/webpack.config.js, packages/core/content-manager/admin/src/index.js, packages/core/content-type-builder/admin/src/index.js, packages/core/upload/admin/src/index.js
It makes obvious for the admin package that the CTB, CM and upload plugins are required.
Until we built the plugins separately the admin panel can now require these plugin directly in the pages/Admin component.
In order to remove some complex logic regarding these plugins and also to reduce the build size.
Now the main bundle size is about the following:
It app should work as it used to.
=> Load internal plugins

examples/getstarted/api/address/models/Address.settings.json, packages/core/admin/webpack.config.dev.js
It invalidates the cache for the core plugins.
Because of the new way of loading the internal plugins CM, CTB, upload webpack did not update the cache when making a modification in these packages.
This fixes the issue
=> Invalidate webpack cache in dev mode

packages/strapi-plugin-upload/controllers/upload/admin.js
Fix an issue where setting permissions with conditions on the assets for the upload plugin can break the permissions checks.
In a [previous PR](https://github.com/strapi/strapi/pull/10370/files#diff-ce5847e2721e68f1c2682b5812248461031c101c4bf74ed7abcbd6a8cd5b47d1R194), the auto-populate for the fetch has been removed, which caused the `created_by` attribute to be raw instead of populated, hence causing an issue when fetching the associated role.
As a fix, we simply use the raw identifier (from the `created_by` field) instead of trying to access the `id` property inside.
Another idea would've been to fetch directly the whole user based on the `created_by` id, but it would mean fetching also unwanted properties for the user, such as password & co. 
Upload plugin's assets permissions are not …
=> Fix RBAC upload permissions

packages/strapi-admin/admin/src/containers/MarketplacePage/index.js
adds send events when user visits marketplace or downloads a plugin
=> Metris: improve marketplace activity metrics to prepare next version

packages/strapi-plugin-users-permissions/admin/src/translations/en.json
Minor typo fix:
registred to registered
Let me know if any further detail is required for the PR.
=> Typo fix for English translations in user-permissions

packages/create-strapi-starter/utils/build-starter.js, packages/create-strapi-starter/utils/child-process.js, packages/create-strapi-starter/utils/has-yarn.js
Fixes https://github.com/strapi/strapi/issues/10516
The function to check for yarn was not being invoked and always resolving to true
`execa.shellSync` has been removed
https://github.com/sindresorhus/execa/pull/219
=> [Starter CLI] fix has-yarn

packages/create-strapi-app/create-strapi-app.js, packages/create-strapi-app/package.json, packages/create-strapi-app/utils/prompt-user.js, packages/create-strapi-starter/create-strapi-starter.js, packages/create-strapi-starter/package.json, packages/create-strapi-starter/utils/build-starter.js, packages/create-strapi-starter/utils/fetch-github.js, packages/create-strapi-starter/utils/prompt-user.js, packages/strapi-generate-new/lib/create-project.js, packages/strapi-generate-new/lib/generate-new.js, packages/strapi-generate-new/lib/index.js, yarn.lock
Prompts user to select a template or starter
- create-strapi-app: `./node_modules/.bin/create-strapi-app`
- create-strapi-starter: `./node_modules/.bin/create-strapi-starter`
=> [CLI] Add interactive options for templates and starters

packages/strapi-plugin-i18n/package.json
Fixed missing lodash upgrade in the i18n plugin
Prototype pollution fix when we upgraded the lodash version: https://github.com/strapi/strapi/pull/9990
Run a `yarn audit` and notice missing vuln reports
N/A
=> Fix missing lodash upgrade in i18n plugin

packages/strapi-admin/admin/src/containers/MarketplacePage/index.js
=> fix typo didGotToMarketplace => didGoToMarketPlace

examples/getstarted/plugins/myplugin/admin/src/index.js, packages/core/admin/admin/src/StrapiApp.js, packages/core/admin/admin/src/index.js, packages/core/content-type-builder/admin/src/index.js, packages/core/email/admin/src/index.js, packages/core/upload/admin/src/index.js, packages/generators/plugin/files/admin/src/index.js, packages/plugins/documentation/admin/src/index.js, packages/plugins/graphql/admin/src/index.js, packages/plugins/i18n/admin/src/index.js, packages/plugins/sentry/admin/src/index.js, packages/plugins/users-permissions/admin/src/index.js
It renames the `boot` lifecycle to `bootstrap` to match the back-end conventions.
In order to adopt the same conventions in both the admin and the back-end .
The app should work as it used to.
=> Rename boot lifecycle to bootstrap

README.md, packages/strapi/README.md
Remove the one-click buttons as it is now the installation workflow we recommend.
Strapi has been designed to be installed in a local environment, versioned through git, and deployed to production. The one-click deploy buttons create some confusion.
Preview the markdown.md file.
None.
=> Remove one-click deploy buttons

packages/strapi-plugin-users-permissions/admin/src/index.js
It fixes some ids to activate translations on strapi-plugin-users-permissions HeaderNav
To prevent mixed language content while using admin interface in another language rather than English (default).
1. Change UI language through the user profile.
2. Access admin settings
3. You shall see at users-permissions links that "Email Templates" and "Advanced Settings" are not translated
This commit fix the issue.
=> Fix some users-permissions plugin HeaderNav translation ids

packages/strapi-admin/index.js
I´m using a custom Docker setup and had trouble to get the watch-admin running. After some testing i found a few things. 
I had to first add the url to the config and second add the devServer config.
webpack: (config, webpack) => {
config.devServer = {
host: '0.0.0.0',
useLocalIp: false
};
return config;
},
After that strapi develop --watch-admin was accessible over the docker ip. But because the config gets not forwarded in the opts, the hot reload doesn't work. 
That's because this doesn't get the args that i setup.
function createDomain(options, server) {
const protocol = options.https ? 'https' : 'http';
const hostname = options.useLocalIp
? ip.v4.sync() || 'localhost'
: options.host || 'localhost';
If there is a another way I would like to know. Otherwise I would appreciate this …
=> fix: consider custom devServer config

packages/strapi-plugin-content-type-builder/admin/src/components/List/index.js
Add a tracker event in the CTB list view banner button
=> Add an event to CTB banner button

packages/strapi-provider-upload-aws-s3/README.md
Gives more information about what actions are needed for this provider to work without using `s3:*`
=> Update AWS S3 Provider Documentation

CONTRIBUTING.md
Changes the Slack to Discord in the contrib guide
Deprov of Slack
click the link
N/A
=> Update contrib guide to swap slack for discord

README.md
Remove Netlify from the list of cloud provider suggestions in the readme
It's confusing for a lot of people that you can't deploy Strapi on Netlify or Vercel. I know that we can host only the frontend build on Netlify, but I find it misleading to see Netlify next to servers that can actually run a Node app.
=> Remove netlify mention from readme

packages/generators/generate-plop/plopfile.js, packages/generators/generate-plop/templates/controller.js.hbs, packages/generators/generate-plop/templates/policy.js.hbs
Add controller and policy generators to the generate-plop package, as part of the POC.
I thought I would add the API generator later, since that one will also rely on the model generator that I don't already have.
=> Add controller and policy plop generators

packages/strapi-plugin-users-permissions/controllers/Auth.js
Adds a check in the forgot password controller to see if a user is blocked and return the valid error message if they are
Blocked users should not be able to perform any request at all
Create a user, set them as blocked, and attempt to send a password reset request
fixes #10776
=> Fix blocked users being able to sign in using forgot password

packages/strapi-admin/admin/src/translations/en.json
"You are logged as the first administrator." -> "You are logged in as the first administrator."
Fix a small grammar issue in the English translations for strapi-admin.
I don't know.
N/A
N/A
=> fix grammar

packages/core/strapi/lib/core-api/controller/__tests__/transform.test.js, packages/core/strapi/lib/core-api/controller/collection-type.js, packages/core/strapi/lib/core-api/controller/index.js, packages/core/strapi/lib/core-api/controller/single-type.js, packages/core/strapi/lib/core-api/controller/transform.js, packages/core/strapi/tests/endpoint.test.e2e.js, packages/core/utils/lib/parse-multipart.js, packages/plugins/i18n/server/services/core-api.js
Done in this PR:
- Cleanup parse multipart to be simpler
- Transform response relations to use data & meta format
- Apply relation format to media fields
=> [v4] Rest api response format for relations

packages/core/admin/server/content-types/api-token.js, packages/core/admin/server/controllers/__tests__/api-token.test.js, packages/core/admin/server/controllers/api-token.js, packages/core/admin/server/routes.js, packages/core/admin/server/services/__tests__/api-token.test.js, packages/core/admin/server/services/api-token.js, packages/core/admin/server/services/constants.js, packages/core/admin/server/tests/admin-api-token.test.e2e.js, packages/core/admin/server/validation/api-tokens.js
It adds a GET endpoints that returns all the API tokens sorted alphabetically by `ApiToken.name`.
This will allow us to retrieve all the tokens in the admin UI.
The logic is supported by both unit and e2e tests.
=> Add GET endpoint to list API tokens

CONTRIBUTING.md
This PR adds more clarity in how to run the e2e test suite. It also document how to run the tests only for CE or how to add a license to run the tests in EE.
The current CONTRIBUTING guide isn't very explicit on how to run the e2e tests suite, which can cause some issues as the information is hard to find in the code base.
N/A
=> Improve the test section of the CONTRIBUTRING file.

packages/strapi-plugin-upload/package.json
Upgrades sharp dependency in strapi-plugin-upload to latest stable version (0.29.0).
In some cases, width and height could not be determined for PNG images as sharp threw an error (`Input buffer has corrupt header: pngload_buffer: invalid chunk position`). This also prevented strapi-plugin-upload from generating different image sizes/formats.
The latest sharp version no longer has this issue.
--
--
=> bump sharp to 0.29.0

packages/strapi-helper-plugin/package.json, packages/strapi-plugin-documentation/package.json, packages/strapi-plugin-graphql/package.json, packages/strapi-plugin-i18n/package.json, packages/strapi-plugin-sentry/package.json, packages/strapi-plugin-upload/package.json, packages/strapi-provider-upload-rackspace/package.json
With the rise in supply chain attacks and OSS dependencies being used as a attack vector, Microsoft is working with our ecosystem partners, such as the Linux Foundation's OpenSSF, to enable OSS consumers to track packages back to their public sources.
We've identified that the following packages published to NPM do not report where sources can be found, typically accomplished by including a link to your GitHub repository in your `package.json` REPOSITORY field. This PR was created to add this value, ensuring future releases will include this provenance information.
Published NPM packages with repository information:
* strapi-helper-plugin
* strapi-plugin-documentation
* strapi-plugin-graphql
* strapi-plugin-i18n
* strapi-plugin-sentry
* strapi-plugin-upload
* …
=> Update package.json to include the repository key 

packages/core/admin/server/controllers/__tests__/api-token.test.js, packages/core/admin/server/controllers/api-token.js, packages/core/admin/server/routes.js, packages/core/admin/server/services/__tests__/api-token.test.js, packages/core/admin/server/services/api-token.js, packages/core/admin/server/tests/admin-api-token.test.e2e.js
It adds an endpoint to revoke (delete) an api token.
This will allow users to revoke tokens that shouldn't be used anymore (ie. for security reason).
The endpoint is supported by unit and e2e tests.
=> add DELETE route to revoke API tokens

packages/plugins/sentry/package.json
Reformat @strapi/plugin-sentry name
To avoid this error in the v4:
>Plugin name "Sentry" is not in kebab (an-example-of-kebab-case)
=> Format Sentry plugin name in kebab-case

packages/core/admin/server/controllers/api-token.js, packages/core/admin/server/register.js, packages/core/admin/server/services/api-token.js, packages/core/admin/server/strategies/__tests__/admin.test.js, packages/core/admin/server/strategies/__tests__/api-token.test.js, packages/core/admin/server/strategies/admin.js, packages/core/admin/server/strategies/api-token.js, packages/core/admin/server/strategies/index.js, packages/core/strapi/lib/services/auth/index.js, packages/plugins/users-permissions/server/register.js, packages/plugins/users-permissions/server/strategies/users-permissions.js
It add a new auth strategy to the content-api.
The `admin` strategy has been moved out of the `register.js` file for readability and consistency. We now have a `strategies` folder to hold them.
You can now use an `api-token` to authorized your requests.
The strategy is supported with unit tests and was tested manually using Insomnia and the `gestarted` app.
=> add an `api-token` auth strategy to the `content-api`

packages/core/admin/admin/src/components/LeftMenu/index.js
FA icons have a fixed width.
This PR wraps the FA icons from the MainMenu inside a span that overrides their styles
=> Fix FA icons that are too large on the menu

packages/cli/create-strapi-app/utils/prompt-user.js, packages/generators/app/lib/index.js
We disable the template system in V4 for the moment. It will be re-enabled once the templates have been migrated to V4.
@JabStrapi for the wording :)
=> Disable templates for the moment

packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
The caret was not aligned with the center of the row
Now =>
=> Fix Rbac icon alignement

packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewLocalePicker/index.js
It displays the first locale in the cm edit view locale selector
=> Display selected locale

packages/core/admin/index.js
- Allows to build the admin using the V4
🙄 
It's quite hard actually. One way is to checkout this PR and run `yarn build` inside the example folder. The other way is a bit complex but is the most realistic way:
- `npx create-strapi-app@beta beta --quickstart`
- Inside a code editor, go to the `node_modules\@strapi\admin\index.js` file and modify the line 99 with the following (it's the code suggested in this PR):
```javascript
const realPath = path
.join(path.relative(path.resolve(dest, 'admin/src'), pathToPlugin), 'strapi-admin.js')
.replace(/\\/g, '/');
```
and to modify the line 117 of the same file and put ` const req = `'${pathToPlugin}'`;` instead (removing `/strapi-admin.js`)
There are multiples, or too many 😬
=> Attempt to fix plugin loading on v4

.github/ISSUE_TEMPLATE/BUG_REPORT.md, CONTRIBUTING.md, packages/generators/app/lib/resources/json/package.json.js
Modifies the new project generator to properly set the engines object to support Node 16
Prepare for stable release
- Generate a fresh project and confirm the root project package.json has the proper engine keys to match all other core packages
- Try to install node modules using both npm and yarn
- Try to start Strapi using Node 16
fixes #11135
=> Enable Node 16 and NPM 7/8 support on generation

packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/components/RoleRow/index.js
Added truncate text on name and description columns in Settings/Roles/LV
Added fix width to allow ellipsis to work
=> QA/ Truncate name-description Role LV

packages/core/admin/admin/src/content-manager/components/InputJSON/components.js
Fixed inputJSON z-index 
Go to CM / create edit an entry with inputJSON in it
Scroll until you find the input
inputJSON shouldn't go over/overflow the sticky header
=> QA/ InputJSON z-index

packages/core/strapi/lib/middlewares/errors.js, packages/core/strapi/lib/services/errors.js
Add possibility to set a status on a thrown Error.
The goal is to stay consistent with what koa offer with ctx.throw()
you can create a custom controller and trow a new Error with a status code
=> [v4] Add possibility to set a status on a thrown Error

packages/core/strapi/lib/services/entity-service/index.js
Adds a default value to the params attribute of the entity-service's load method
When loading a dynamic zone without any additional params, the entity service passes down params = undefined which cause the next layer to throw.
See #11544
Fix #11544
=> [V4] Fix DynamicZone queries for GraphQL

packages/plugins/graphql/server/services/builders/resolvers/component.js, packages/plugins/graphql/server/services/builders/type.js, packages/plugins/graphql/server/services/builders/utils.js
- Removes args (filters, sort, etc...) from non-repeatable components
- Fix filters transformation when loading components 
Filters for non-repeatable components are basically useless & filters are currently broken
=> [V4] GraphQL - Fix components' filtering

packages/plugins/graphql/server/services/builders/type.js
Remove code dedicated to timestamps in type definition
Since timestamps are now handled as regular attributes, we don't need to add them manually in the type definition
=> [V4] GraphQL - Remove Manually Added Timestamps

packages/core/admin/admin/src/pages/InstalledPluginsPage/Plugins.js, packages/core/admin/admin/src/pages/InstalledPluginsPage/index.js, packages/core/admin/admin/src/pages/InstalledPluginsPage/utils/api.js
=> Add plugins page

packages/core/admin/server/services/content-type.js
Fix missing permission on empty components for super admins
When creating a component without any fields, it doesn't add the field to the related permissions, even for the super admin
=> [V4] Fix empty component permissions

packages/core/content-type-builder/admin/src/components/AttributeOptions/AttributeOption/index.js, packages/core/content-type-builder/admin/src/components/AttributeOptions/index.js, packages/core/content-type-builder/admin/src/components/ComponentCard/index.js, packages/core/content-type-builder/admin/src/components/ComponentIconPicker/index.js, packages/core/content-type-builder/admin/src/components/CustomRadioGroup/components.js, packages/core/content-type-builder/admin/src/components/CustomRadioGroup/index.js, packages/core/content-type-builder/admin/src/components/DraftAndPublishToggle/index.js, packages/core/content-type-builder/admin/src/components/DynamicZoneList/index.js, packages/core/content-type-builder/admin/src/components/FormModal/index.js, packages/core/content-type-builder/admin/src/components/FormModalHeader/index.js, packages/core/content-type-builder/admin/src/components/List/index.js, packages/core/content-type-builder/admin/src/components/ListRow/index.js, packages/core/content-type-builder/admin/src/components/NestedTFooter/index.js, packages/core/content-type-builder/admin/src/components/Relation/RelationField/index.js, packages/core/content-type-builder/admin/src/components/Relation/RelationNaturePicker/index.js, packages/core/content-type-builder/admin/src/components/TabForm/index.js, packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap
Replaced all Text components with Typography is CTB components && views
=> [DS] Typography in CTB

packages/plugins/graphql/server/services/builders/resolvers/component.js
Use `strapi.getModel` instead of `strapi.contentTypes[]` to fetch the model containing a given component, which allow to handle both content types & components parents.
Currently, the resolvers are broken for components that are inside other components
fix #11605
=> [V4] Graphql - Fix nested component resolvers

packages/plugins/graphql/server/services/builders/input.js
Removes non-writable attributes from GraphQL input types
Currently, non-writable attributes are registered in input types (such as `createdAt` or `updatedAt`) but are sanitized later on. This PR removes this weird scenario by eliminating those fields from the input types.
=> [V4] GraphQL - Only keep writable attributes in input types

packages/strapi/lib/commands/develop.js
This PR tells the file watcher to only ignore occurrences of the word admin from the root folder onwards
It fixes this issue #11586. 
Create a strapi project inside a parent folder called admin, and try to edit the project in all valid directories including extension and plugin admin directories, it works as expected. 
#11586
=> ✏️ Edit the file watcher to only ignore admin folder occurrences from project folder onwards and not parent folder

packages/core/admin/ee/server/controllers/authentication/middlewares.js, packages/core/admin/server/services/user.js
It adds a findUserByEmail method in the admin user service & use it from the admin authentication middleware
The admin authentication middleware was using the old findOne syntax to check for an existing user (by mail). This caused the app to crash when trying to log in using SSO.
Should fix #11652
=> [V4] Fix sso existing user query

packages/generators/generators/lib/plops/prompts/get-attributes-prompts.js
Adds the following warning when creating a content type from the CLI without attributes.
> You won't be able to manage entries from the admin, you can still add attributes later from the content type builder.
Offer more visibility on the impact of creating a ct without any attributes
=> [V4] CLI add warning for ct without attributes

packages/generators/generators/lib/files/plugin/server/controllers/my-controller.js.hbs
Replaces 'id' with 'pluginName' in the handlebars template since that is what is passed in the plop generator
The generated controller returns an empty string for the plugin
```
'use strict';
index(ctx) {
ctx.body = strapi
.plugin('') // should return the name of the plugin
.service('myService')
.getWelcomeMessage();
},
};
```
Run `yarn strapi generate` and generate a plugin
=> [v4] fix plugin name variable when generating controller

packages/cli/create-strapi-starter/utils/build-starter.js
Fixes a bug in the create-strapi-starter CLI: when the starter monorepo's backend is created, it doesn't use the template specified by the starter.json file.
The bug was introduced when I wanted to apply [this feedback comment](https://github.com/strapi/strapi/pull/11635#discussion_r754892072)
The command:
```sh
npx create-strapi-starter@beta blog-starter-test next-blog --quickstart
```
currently creates an empty Strapi app, so the starter frontend breaks
=> Fix starter CLI creating Strapi apps without a template

packages/core/admin/server/services/permission/permissions-manager/sanitize.js, packages/core/content-manager/server/tests/index.test.e2e.js
It sanitize the admin::user relations to only keeps relevant fields and avoid disclosing sensible information to the front-end.
It prevent the disclosure of sensible information that can be used to take over someone else's account.
Check the network tab when in the CM. When it queries the content-types the query results contains the `createdBy` and `updatedBy` information.
=> remove unallowed fields from admin::user relations

packages/core/strapi/lib/middlewares/security.js
Fixes a CSP preventing safari from fetching https  (instead of HTTP) resources on localhost
Allow people using Safari to run the project on localhost
Run the project on safari, you should see the UI
Thanks @alexandrebodin for the help 🙏🏻
=> Fix CSP for safari

.github/workflows/tests.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
Context: https://github.com/strapi/strapi/pull/11248
=> Add cache to node workflows

packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/DisplayedFieldButton.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FieldButtonContent.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/__snapshots__/index.test.js.snap
Fix the label overflow on CM edit settings view
=> Fix label overflow on cm edit settings view

packages/plugins/documentation/server/services/documentation.js
Fix plugin crashing when content type gets deleted
When deleting a content type the doc plugin still tries to write undefined data to disk and crashes
=> Fix plugin crashing when content type gets deleted

packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/index.js, packages/core/admin/admin/src/content-manager/pages/App/reducer.js, packages/core/admin/admin/src/content-manager/pages/App/tests/reducer.test.js, packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewLocalePicker/index.js
It fixes the CM's permissions when a role does not have a locale property.
=> [v4] Fix CM permissions with locales

CONTRIBUTING.md, README.md, packages/core/admin/admin/src/components/AutoReloadOverlayBlockerProvider/Blocker.js, packages/core/admin/admin/src/pages/Admin/Onboarding/index.js, packages/core/content-manager/oas.yml, packages/core/email/admin/src/pages/Settings/components/Configuration.js, packages/core/email/server/controllers/email.js, packages/core/helper-plugin/lib/src/old/components/OverlayBlocker/index.js, packages/core/strapi/README.md, packages/core/strapi/lib/services/metrics/index.js, packages/core/utils/lib/convert-query-params.js, packages/plugins/documentation/server/config/default-config.js, packages/plugins/graphql/README.md, packages/plugins/i18n/oas.yml, packages/plugins/users-permissions/documentation/1.0.0/overrides/users-permissions-User.json, packages/plugins/users-permissions/server/controllers/auth.js, packages/providers/upload-aws-s3/README.md, packages/providers/upload-cloudinary/README.md, packages/providers/upload-local/README.md, packages/providers/upload-rackspace/README.md
Updates all references of `strapi.io/documentation` to their new `docs.strapi.io` links
Moving documentation to a subdomain
N/A
N/A
=> [v4] Update all documentation links to new docs url

packages/plugins/users-permissions/server/bootstrap/index.js, packages/plugins/users-permissions/server/controllers/auth.js, packages/plugins/users-permissions/server/services/providers.js
**Problem:**
The `defaults` key in grant config (stored in the database) is used as a provider by the strapi code, making the provider `defaults` shown in the admin.
**Fix:**
Remove the key from the database and only add it before passing the config to grant.
=> Remove defaults key from stored grant config

README.md
Removes Invalid Link to the Academy
=> Remove Academy Link in Readme

packages/providers/email-amazon-ses/README.md, packages/providers/email-mailgun/README.md, packages/providers/email-nodemailer/README.md, packages/providers/email-sendgrid/README.md, packages/providers/email-sendmail/README.md, packages/providers/upload-aws-s3/README.md, packages/providers/upload-cloudinary/README.md, packages/providers/upload-local/README.md, packages/providers/upload-rackspace/README.md
Fixed all the example configs as they were not wrapped in a `config: {}` object
=> Fix provider config examples for v4

packages/strapi-connector-bookshelf/lib/migrations/draft-publish.js, packages/strapi-connector-mongoose/lib/migrations/draft-publish.js, packages/strapi-connector-mongoose/package.json
I think we can create a function `deleteRelationsWhere` to avoid copy-pasting the same logic. However, as it will all change soon, it may not be worth spending time on it. What do you think ?
Also this PR is based on `features/i18n`, it could be on `master`. What do you prefer?
EDIT: base branch changed to `releases/v3.6.9`
=> Delete relations when disabling dp on a content type

packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.js
Updated `useContentTypeBuilderMenu.js` to include `isInDevelopmentMode` on the data customLink
Noticed a slight admin UI error, when running in production the create component button was still visible (although nonfunctional) and therefore should be removed from the render. 
Run Strapi in production, do you see the create component button?
["Create new component" toggle visible in production #11790](https://github.com/strapi/strapi/issues/11790)
=> Set visibility on create component button when in production

packages/core/database/lib/dialects/mysql/schema-inspector.js, packages/core/database/lib/dialects/sqlite/index.js, packages/core/database/lib/schema/diff.js, packages/core/database/lib/schema/schema.js
Fixes #11739
Native enum types aren't handled well in Knex and there really is no point to use them as you get almost zero benefit and a lot of drawbacks when you need to update them. A simple string is fine.
=> Switch Enum from native type to string or text

packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js, packages/core/strapi/lib/services/entity-validator/__tests__/validators.test.js, packages/core/strapi/lib/services/entity-validator/validators.js
Fixes a validation bug that caused empty strings to not validate in non-required fields with a regex constraint. This PR contains fixes for both frontend (admin) and backend validation.
It should be possible to leave out non-required fields even if they uses regex validation.
1. Go to content-type builder and create a text field that is not required but has some form of RegExp validation (e.g., `^\d+$`)
2. Go to content-manager and create a new entry with that field correctly filled in (as a number)
3. Edit that same entry and remove that field's value (back to blank).
4. Update should be successful.
5. Update the content type and set the regex field to be required.
6. Update the entry created in step 2 and try to save it with the regex field empty (update should fail)
7. Fill in a valid …
=> Fix regex validation for empty string in non-required fields

packages/core/upload/admin/src/components/AssetCard/AssetCard.js, packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js, packages/core/upload/admin/src/components/EditAssetDialog/tests/EditAssetDialog.test.js, packages/core/upload/admin/src/components/EditAssetDialog/tests/index.test.js, packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAsset.js, packages/core/upload/admin/src/utils/createAssetUrl.js
Signed-off-by: harimkims <harimkims@gmail.com>
- Fix unable to download original image in uploader
- Add parameter to `createAssetUrl` function to specify that it is for `thumbnail` or `original` image url
Because you cannot download original image from edit UI now.
1. Go to Media Library menu
2. Upload asset
3. Click Edit button
4. Download image
Closes #11768
=> Fix unable to download original image in uploader

packages/core/strapi/lib/services/entity-validator/__tests__/biginteger-validators.test.js
It frees 2 bytes* on the maintainers hard drive.
(* well, minus the space needed for this commit when it’ll land on local repo installations…)
The better the grammar, the happier the maintainers.
You need to submit this pull request to an English teacher.
None.
=> Fix English grammar in test files

packages/plugins/users-permissions/server/graphql/mutations/auth/reset-password.js
Signed-off-by: harimkims <harimkims@gmail.com>
- Replace `forgotPassword` with `resetPassword` in reset password GraphQL Mutation
- Enabling reset-password by GraphQL Mutation
1. Execute Mutation
```gql
mutation ForgotPassword($email: String!) {
forgotPassword(email: $email) {
ok
}
}
{
"email": "test@gmail.com"
}
```
2. Get reset-password token
3. Execute Mutation
```gql
mutation ResetPassword(
$password: String!
$passwordConfirmation: String!
$code: String!
) {
resetPassword(
password: $password
passwordConfirmation: $passwordConfirmation
code: $code
) {
jwt
user {
id
email
}
}
}
{
"password": "somepassword",
"passwordConfirmation": "somepassword",
"code": "sometoken"
}
```
4. Check out you get proper response with  `jwt`, `user` field
Closes #11934
=> Fix unable to reset password in GraphQL mutation

packages/core/admin/server/strategies/api-token.js
Signed-off-by: harimkims <harimkims@gmail.com>
- Fix bug throwing an error when API-token verify scope
When sanitizing result, `strapi.auth.verify` **send a string scope** as a second parameter.
```js
// packages/core/utils/lib/sanitize/visitors/remove-restricted-relations.js
const hasAccessToSomeScopes = async (scopes, auth) => {
for (const scope of scopes) {
try {
await strapi.auth.verify(auth, { scope });
return true;
} catch {
continue;
}
}
return false;
};
```
And it throws an error in below code - `config.scope.every is not a function` - since scope is string, not an array..
```js
// packages/core/admin/server/strategies/api-token.js
if (config.scope && config.scope.every(isReadScope)) {
```
So I store them in an array if it's not an array.
```js
const scopes = …
```
=> Fix relations are not populated when API key is read-only

packages/core/strapi/lib/commands/develop.js
Ignore the build folder (and its files) when watching for changes.
Went from 466 to 208 files watched on the getstarted example.
Trying to remove as many useless watches as possible so we don't reach the default limit on different OS
=> Remove the build directory from the watched files list

packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js, packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js, packages/core/upload/admin/src/hooks/useUpload.js
Fix upload file info form
Send the info form with the file upload
1. Create a content type with a media input and create a new entry
2. Drop a file in the media input and edit the media before the upload
3. Change the file info (name, caption and/or alternativeText)
4. Finish and upload the file
5. The file info should be updated
Closes #11772
=> Fix upload file info form

README.md
Added a logo for project README in dark mode as per [this syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to).
Previously logo was set to 318px width and centered with HTML, which is not possible with markdown, while conditional images for light/dark themes is only supported in markdown.
With this change, the image is now the default 100% width for SVG images in markdown.
The logo is hard to read in a dark theme.
View project README in dark & light GitHub theme.
Fixes #10917
=> Added logo for GitHub dark mode

packages/core/strapi/bin/strapi.js, packages/core/strapi/lib/commands/build.js, packages/core/strapi/lib/commands/develop.js
It forces the deletion of the .cache and build folder when running the build command.
I am seeing a lot of issues being opened because the build is wrong. This is often dure because the `.cache` folder is not clear when running the build command without `--clean` flag.
After some thoughts I think that the `--clean` flag should be removed and that we should always trigger a build with a clean .cache folder in order to avoid issues when upgrading a Strapi app.
⚠️ We need to update the documentation and remove this [line](https://github.com/strapi/documentation/blob/717d9c31ee02b4f0f62ba8c7ade4b3643657985c/docs/developer-docs/latest/developer-resources/cli/CLI.md?plain=1#L94)
=> Always remove the build and cache folder when running the build command

packages/core/admin/admin/src/components/LeftMenu/index.js
Fix the logout on Safari
-> Safari needs a tabIndex=0 on links element to define the relatedTarget value of the blur event we use to close the popover.
To be able to logout on Safari
- Log into Strapi with Safari
- Try to logout or go to the profile view :)
https://github.com/strapi/strapi/issues/12015
=> Fix logout on Safari

packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/IconButtonCustoms.js, packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js, packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/DisplayedFieldButton.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FieldButtonContent.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/RelationalFieldButton.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/__snapshots__/index.test.js.snap, packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/DraggableCard.js, packages/core/admin/admin/src/content-manager/pages/ListSettingsView/tests/__snapshots__/index.test.js.snap
- Change draggable element from button to span (Firefox `button` and `a` can't be draggable).
- Creating a custom icon button (The IconButton from the DS break the DnD on Firefox).
- Fix the Firefox drag and drop issue on EditSettingsView, ListSettingsView and EditView (Repeatable components)
- Log into Strapi using Firefox
- Create a collection and add a repeatable component field
- Create an entry in the collection
- Create multiple entries in the repeatable component field
- Click and drag the entry in the repeatable component field using the icon on the far right of the entry
https://github.com/strapi/strapi/issues/11930
Fixes #12048
=> Fix firefox drag n drop

packages/core/content-type-builder/admin/src/components/DataManagerProvider/index.js, packages/core/content-type-builder/admin/src/components/DataManagerProvider/utils/validateSchema.js, packages/core/content-type-builder/admin/src/translations/en.json, packages/core/content-type-builder/server/controllers/validation/__tests__/types.test.js, packages/core/content-type-builder/server/controllers/validation/types.js
It prevents from saving a content type when a dynamic zone is empty.
Empty dynamic zone makes no sense.
=> Prevent saving content type when dynamic zone does not have components.

packages/core/admin/admin/src/content-manager/components/Wysiwyg/Editor.js, packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorLayout.js, packages/core/admin/admin/src/content-manager/components/Wysiwyg/WysiwygFooter.js, packages/core/admin/admin/src/content-manager/components/Wysiwyg/WysiwygNav.js, packages/core/admin/admin/src/content-manager/components/Wysiwyg/index.js
Some UI fixes for the WYSIWYG
- Fix "Markdown mode" Button size
- Click outside to close the Expand modal
- Reach the more button popover with the keyboard navigation
- Tab or Shift-Tab to exit the text editor
- Remove useless disable on the Expand button (during preview mode)
=> Some UI fix for the WYSIWYG

packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/EventInput/index.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/utils/schema.js, packages/core/admin/server/controllers/webhooks.js
Remove required validation for the events attributes of webhooks
In a previous minor version of the v3 of Strapi, the events attribute (checkboxes) was not required to trigger a webhook (some developers used it to check their app was functioning).
Therefore this PR takes advantage of the V4' refactor to remove this dependency and allow to trigger a webhook from that very button without checking any box of the events
https://www.loom.com/share/d13b510de1ed454ea733218e9291325a
=> Enable to create/trigger webhooks with no events

.github/actions/install-modules/script.sh, packages/strapi-admin/admin/src/containers/ProfilePage/index.js, packages/strapi-admin/admin/src/containers/ProfilePage/utils/schema.js, packages/strapi-admin/admin/src/translations/en.json, packages/strapi-admin/controllers/authenticated-user.js, packages/strapi-admin/tests/admin-authenticated-user.test.e2e.js, packages/strapi-admin/validation/user.js
Add current password input to update a user credentials
=> Add current password requirement to edit own profile password

packages/core/admin/server/services/api-token.js, packages/plugins/users-permissions/server/bootstrap/index.js
When setting a custom ENV_PATH the variables API_TOKEN_SALT and JWT_SECRET are now written in the file that is set via the variable.
The ENV_PATH was not respected
Create a folder `test` and run `ENV_PATH=./test/.env strapi start`
The .env file is created in the the folder `test` now.
=> [FIX] respect custom ENV_PATH

packages/core/strapi/lib/services/server/policy.js, packages/core/utils/lib/errors.js, packages/plugins/graphql/server/services/content-api/policy.js
Adds a new error type for policies that user can extend with their own custom classes if they want
Better to have a specific error class for throwing custom errors in policies
```js
// path: ./src/policies/test.js
const utils = require('@strapi/utils');
const { PolicyError } = utils.errors;
module.exports = (policyContext, config, { strapi }) => {
let blah = false
if (blah === false) {
throw new PolicyError('Some message', { policy: 'test' })
} else {
return true
}
}
```
N/A
=> Add PolicyError error class for use in policies

packages/core/strapi/lib/services/metrics/sender.js, packages/core/strapi/lib/utils/machine-id.js, packages/core/strapi/lib/utils/success.js, packages/core/strapi/package.json, packages/generators/app/lib/index.js, packages/generators/app/lib/utils/machine-id.js
This PR adds try/catch logic to all places where deviceId is generated with machineIdSync(). As machineIdSync requires a shell to be available in order to work, it crashes the startup script on non-shell hosts, such as distroless containers. Instead, if no shell is available, deviceId will be generated by using uuid/v4. Although such id is not persistent, it will still help us to track analytics from a container session while the container is up and running; and allow our tracker to function without any changes. Currently, if there is no deviceId on the request to the tracker, such request will not go through.
Fixes the issue where startup script would fail on non-shell hosts.
Create a distroless container and run the application. It should start up as normal. …
=> Fixed non-shell host crash on startup

packages/core/strapi/lib/commands/develop.js
**Cluster.isMaster => Cluster.isPrimary** 
A minor fix that will embrace backward and forward compatibility with the Cluster module. 
Cluster.isMaster was marked as deprecated by node since version 16.0.0
This fix will allow to continue using the deprecated name with prior node versions and prepare the codebase to work with the new name. [nodejs.org/api/cluster](https://nodejs.org/api/cluster.html#clusterismaster)
=> Prepare for deprecated cluster.isMaster in node > 16.0.0

packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.js, packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
The duplicate & crop feature does not work anymore
- Go to the media library
- Upload an image
- Click the pencil icon button on the image to open the edit modal 
- Click the crop icon button 
- Try to Save (Duplicate & crop)
=> Fix duplicate & crop an image on the media library file edit form

packages/core/admin/admin/src/pages/Admin/index.js, packages/core/admin/admin/src/pages/InternalErrorPage/index.js, packages/core/admin/admin/src/pages/InternalErrorPage/tests/index.test.js, packages/core/admin/admin/src/pages/NotFoundPage/tests/index.test.js, packages/core/admin/admin/src/translations/en.json
=> Migrate 404 page and init 500 page

packages/core/strapi/package.json, yarn.lock
To resolve https://github.com/advisories/GHSA-r683-j2x4-v87g.
=> chore(deps): update node-fetch to v2.6.7

packages/core/admin/package.json, packages/core/admin/server/services/permission/permissions-manager/sanitize.js, yarn.lock
- Works on solving issue #12232. 
- Normalizes the codebase for the BREAKING CHANGES introduced in v5.1.0 of @casl/ability 
- npm v8 installations are not working because of @casl/ability v4 that does not support it and makes strapi fail on the installation.
- Unit and e2e tests were all passed to check for the changes made in this PR. 
To assert for a green light on an npm v8 installation (#12232) I used "verdaccio" to mimic a public npm registry locally so I can have a registry to publish forth and pull back. After that I went with the standard worflow on how to create a strapi app but with npm (--use-npm flag). 
The steps I used:
- `npm i -g verdaccio` 
- `npm i -g npm` - install npm@latest
- `verdaccio` - opens the registry and starts listening at …
=> Fix sanity check for @casl/ability upgrade #12232

scripts/front/find-duplicate-translation-values.js, scripts/front/utils/translation-files.js
Adds a script to detect duplicate translations
- Search for duplicates within each file (separately)
- Search for duplicates between the main translation file (core/admin) and every other file
Output example:
To cleanup and maintain the translation files
```sh
node scripts/front/find-duplicate-translation-values.js
```
=> Translations cleanup: duplicates finder script

packages/plugins/documentation/package.json, packages/plugins/graphql/package.json, packages/plugins/sentry/package.json
Adds Strapi as a peerDependency to the sentry, graphql and docs plugins
Sentry, GraphQL & Documentation plugins are listed on the marketplace. It is a [requirement](https://market.strapi.io/guidelines#guidelines) of Strapi Market to specify `@strapi/strapi` compatibility as a peerDependency. This lets the marketplace know if a plugin is compatible with a user's version of Strapi. Also, it generates an npm warning when you install an incompatible Strapi plugin.
I'll create a similar PR for v3 too
=> Add strapi as peerDependency to Strapi Market plugins

packages/core/helper-plugin/package.json, yarn.lock
Bumps axios in the Strapi helper plugin
When plugin developers submit plugins to the marketplace our security tool Snyk reports a vulnerability introduced through `@strapi/helper-plugin@4.0.2 => axios@0.24.0 › follow-redirects@1.14.6`. 
This  was fixed in `follow-redirects@1.14.7` which axios bumped in its latest [release](https://github.com/axios/axios/releases)
=> [helper-plugin] bump axios to v0.25.0

packages/core/admin/index.js
It exposes the webpack devServer configuration when extending the configuration.
It fixes #11936 
To be able to change the port when developing the in the admin panel.
1. Change the `/config/admin.js` configuration:
```js
// autoOpen: false,
auth: {
secret: env('ADMIN_JWT_SECRET', 'example-token'),
},
port: 3000
});
```
2. Run `yarn develop --watch-admin`
It should open the dev server on the 3000 port.
It fixes #11936
=> Fix admin.port not used in the webpack dev server configuration

packages/core/admin/ee/admin/pages/App/utils/customRoutes.js, packages/core/admin/ee/server/controllers/authentication/utils.js
Redirect URLs for SSO were missing a default "admin" value since the route has changed for the V4.
Redirect for SSO is broken. See #12328 
See #12328 
fix #12328
=> Fix SSO redirection

packages/plugins/sentry/server/middlewares/sentry.js
Fixes the sentry plugin middleware throwing an error when trying to send another error to sentry.
According to #12064 the plugin middleware was calling the `sendError()` function on the wrong object:
https://github.com/strapi/strapi/blob/6b2e0dc72db42f8aceb98da87865d9300c298375/packages/plugins/sentry/server/middlewares/sentry.js#L8-L22
The code loaded the sentry plugin service (line 8). Based on this service it loaded the Sentry SDK by using the `getInstance` (line 10) and stores the this instance in the `sentry` variable.
On this sentry variable, it calls the `sendError()` function (line 21)
This is wrong: this `sendError()` function is not part of the Sentry SDK so it does not exist here.
Instead this function is defined in the plugin service itself. So the correct code should be:
I …
=> Fix sentry plugin calling sendError on wrong object

packages/plugins/sentry/README.md
Fixes the Sentry plugin readme which was not updated to v4
v3 instructions did not work on v4
Install the plugin on a v4 app. Follow the previous readme instructions, it does not work, whereas the new ones should work
Replaces this pr: #12066
Partially fixes #12064
The guide on how to disable only the middleware was removed, because that feature was removed on v4. That's because the plugin doesn't expose an actual Strapi middleware, so you can't disable it at the application level.
=> Update Sentry plugin docs for v4

packages/core/strapi/bin/strapi.js
Improves command description and help texts:
- Start with a verb, if possible
- "your" -> "the" because that's the form that is used anywhere else
- favor `yarn` over `npm`
=> CLI: Improve command descriptions

packages/plugins/graphql/package.json, packages/plugins/graphql/server/services/content-api/index.js, yarn.lock
Merge SDL type definition with Nexus' ones before binding the plugins
Currently, it's not possible to either reference types defined from Nexus (shadow CRUD or user-defined) or to apply plugin to SDL type definitions
`src/index.js`
```javascript
"use strict";
/**
* An asynchronous register function that runs before
* your application is initialized.
*
* This gives you an opportunity to extend code.
*/
register({ strapi }) {
const extensionService = strapi.plugin('graphql').service('extension');
extensionService.use(({ nexus }) => ({
typeDefs: /* GraphQL */`
type Query {
test: JSON
}
`,
resolvers: {
Query: {
test: {
async resolve() {
return {'foo':'baz'}
},
},
}
},
resolversConfig: {
'Query.test': {
auth: false,
},
},
}));
},
/**
* An asynchronous bootstrap function that …
```
=> Allow SDL type definitions to beneficiate from Nexus types context & processing

packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/SingleComponent/index.js, packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js, packages/core/admin/admin/src/content-manager/utils/checkIfAttributeIsDisplayable.js
Similar to #12213 it allows to display single components in the list view of the content manager.
TODO:
- Create a new collection type
- Add a non-repeatable component to this collection type and save
- Create a new entry and fill several values for the non-repeatable component
- Go back to the collection type list view
- Enable the non-repeatable component field to show it in the list columns
Refs: #12213
Refs: #12155
Issue: https://strapi-inc.atlassian.net/browse/CONTENT-48
=> CM: Allow displaying single components in list-views

packages/core/admin/index.js
The webpack argument was undefined, so it has been fixed.
Hot reloads in admin did not work, fixed
I changed the value of node_modules directly, and the server started on port 8000!
#12343
Sorry if this has already been resolved.
=> Fixed hot reload in admin

packages/core/content-type-builder/admin/src/components/ListRow/index.js, packages/core/content-type-builder/admin/src/components/Tr/index.js, packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap
This fixes two visual glitches:
- in production mode the line on the left overflows the curve
- in production mode the curve isn't properly aligned to the vertical center of the word, because the rows were shorter, due to the missing action icons
| Before         | After     |
|--------------|-----------|
| <img width="1177" alt="Screenshot 2022-02-10 at 14 14 31" src="https://user-images.githubusercontent.com/2244375/153426641-5786299c-61de-4034-a6da-538e3d55dcce.png"> | ![Screenshot from 2022-02-10 15-15-52](https://user-images.githubusercontent.com/2244375/153426533-83f53d6e-a81b-4f14-8342-564a2f290139.png) |
Fixes design issues.
1. Go to the content type builder
2. Run the app in dev & production mode and see the curve icon of a content type in the right position
=> CTB: Fix alignment of curve icons in production mode

packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FormModal.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/ModalForm.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/reducer.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/reducer.test.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/utils/layout.js, packages/core/admin/admin/src/content-manager/pages/EditSettingsView/utils/tests/layout.test.js
Allows fields to be resized in the content types builder. They can either be `4`, `6`, `8` or `12` columns wide. The field types `dynamiczone`, `component`, `json` and `richtext` are excluded for now and can only render at full-width.
TODO:
Content-editors need to tailor the edit interfaces to their needs.
1. Go to the content-type builder
2. Add at least one field to the layout
3. Edit the field and select the desired size
Closes: https://github.com/strapi/strapi/issues/8094
Issue: https://strapi-inc.atlassian.net/browse/CONTENT-10
=> CM: Make fields resizable

packages/plugins/users-permissions/server/bootstrap/index.js
Default redirect url setting in User-Permission's provider has a extra slash, because of apiPrefix has already contain a '/'.
Remove extra '/' in baseURL
Default redirect url setting in User-Permission's provider has a extra slash, because of apiPrefix has already contain a '/'.
https://github.com/strapi/strapi/issues/12403
=> remove extra '/' in baseURL

packages/strapi-admin/README.md, packages/strapi-connector-bookshelf/README.md, packages/strapi-connector-mongoose/README.md, packages/strapi-database/README.md, packages/strapi-helper-plugin/README.md, packages/strapi-hook-ejs/README.md, packages/strapi-hook-redis/README.md, packages/strapi-middleware-views/README.md, packages/strapi-plugin-content-manager/README.md, packages/strapi-plugin-content-type-builder/README.md, packages/strapi-plugin-documentation/README.md, packages/strapi-plugin-email/README.md, packages/strapi-plugin-graphql/README.md, packages/strapi-plugin-i18n/README.md, packages/strapi-plugin-sentry/README.md, packages/strapi-plugin-upload/README.md, packages/strapi-plugin-users-permissions/README.md, packages/strapi-provider-email-amazon-ses/README.md, packages/strapi-provider-email-mailgun/README.md, packages/strapi-provider-email-nodemailer/README.md, packages/strapi-provider-email-sendgrid/README.md, packages/strapi-provider-email-sendmail/README.md, packages/strapi-provider-upload-aws-s3/README.md, packages/strapi-provider-upload-cloudinary/README.md, packages/strapi-provider-upload-local/README.md, packages/strapi-provider-upload-rackspace/README.md, packages/strapi-utils/README.md, packages/strapi/README.md
As we released Strapi V4 and are about to reach end-of-support for Strapi V3 (around Q3 2022).
We decided to add a deprecation notice to the concerned packages so that users can be warned in advance about what's going to happen.
Packages will either:
- Not going to change at all (no deprecation warning)
- Be moved to another package (deprecation warning + link to the V4 version of the package)
- Be deleted (deprecation warning + notice of no further support)
We want to prepare the migration from V3 to V4 the best we can, and it includes warning the community as soon as possible about the changes that are about to come.
Open some packages readme (`strapi`, `strapi-hook-ejs`, `strapi-plugin-graphql`) files and... read them :shrug:
=> [V3] Packages Deprecation

packages/plugins/graphql/server/services/content-api/index.js
Adds a `artifacts` attribute in the GraphQL plugin configuration that allows generating artifacts (GraphQL schema & types definitions) for ou application.
Also, add a `generateArtifacts` config option to allow or not the generation of such artifacts. The default value is `true` in dev ENV and `false` otherwise.
A documentation PR will follow soon.
In V3 it was possible to extract our GraphQL schema.
`src/config/plugins.js`
```javascript
'use strict';
const { join } = require('path');
module.exports = () => ({
// ...
graphql: {
enabled: true,
config: {
generateArtifacts: true,
artifacts: {
schema: join(__dirname, '..', 'schema.graphql'),
typegen: join(__dirname, '..', 'types.d.ts'),
},
}
}
})
```
Fix https://github.com/strapi/strapi/issues/12420
=> Add configuration options to generate graphql schema + types

packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
Fixes #12498 
Guard with an IF condition to not replace/exhange position with an item of a different hierarchy level.
When moving a ChildComponent it moved the ParentComponent instead the child.
Create a Collection with a ComponentField (for example Menu), and add a ChildComponent (SubMenu) to the ParentComponent as a FieldComponent.
Try to order child components if you have multiple parent components.
Issue: #12498
=> Fixing Drag ordering bug with Nested Component.

packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
Enable to drop image to upload dialog in edit view
Because drag & drop image uploading doesn't work
1. Create Content-type with media field
2. Drop & Drop image to asset box
Close #12230
=> Enable to drop image to upload dialog in edit view

packages/core/upload/package.json
Update to the latest version of sharp in upload plugin.
As of v0.30.0, sharp supports arm64 instances on AWS. I'd like to deploy my Strapi app on AWS, using these more efficient instance types. You find more about the support here: [https://github.com/lovell/sharp/issues/2938#issuecomment-1027322170](https://github.com/lovell/sharp/issues/2938#issuecomment-1027322170)
-
-
=> Update sharp in upload plugin

examples/getstarted/src/api/address/content-types/address/schema.json, packages/core/content-type-builder/admin/src/components/AllowedTypesSelect/index.js, packages/core/content-type-builder/admin/src/components/FormModal/attributes/types.js, packages/core/content-type-builder/admin/src/components/FormModal/reducer.js, packages/core/content-type-builder/admin/src/components/FormModal/tests/reducer.test.js, packages/core/content-type-builder/admin/src/pages/ListView/tests/mockData.js, packages/core/content-type-builder/server/controllers/validation/types.js, packages/core/upload/admin/src/components/AssetCard/AssetCard.js, packages/core/upload/admin/src/components/AssetCard/AudioAssetCard.js, packages/core/upload/admin/src/components/AssetCard/AudioPreview.js, packages/core/upload/admin/src/components/AssetCard/DocAssetCard.js, packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js, packages/core/upload/admin/src/components/AssetCard/VideoAssetCard.js, packages/core/upload/admin/src/components/AssetList/index.js, packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.js, packages/core/upload/admin/src/components/MediaLibraryDialog/index.js, packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAsset.js, packages/core/upload/admin/src/components/MediaLibraryInput/index.js, packages/core/upload/admin/src/constants.js, packages/core/upload/admin/src/utils/typeFromMime.js, packages/generators/generators/lib/plops/content-type.js
- Added a new file type category: Audio for the supported types cfr w3c, https://www.w3schools.com/tags/tag_audio.asp
- Added specific preview for this type both in builder and content mode so audio can be played in the admin panels
Following things I'm not entirely sure about:
- I presume this could be a breaking change for items which currently have 'files' as allowed type if currently it would be a different file type. I'm not really sure what the best way to tackle this is.
- Not sure if translation additions/changes would be required
- AudioAssetCard has a different dom order than VideoAssetCard for the select/edit buttons because otherwise the z-index didn't play nicely and I couldn't figure out why it did work for video/image currently.
Some screenshots of what it looks like: …
=> added audio preview in content builder

packages/core/helper-plugin/lib/src/components/FilterPopoverURLQuery/Inputs.js
It removes all time-related information from the date filter of the content manager list-view, to avoid deprecation warnings and to fix the filter.
Fixes a bug mentioned & related to https://github.com/strapi/strapi/issues/11509.
1. Navigate to the content manger
2. Create a piece of content with a date field (ex. Category)
3. Filter for the date in the content manager list view.
Refs: https://github.com/strapi/strapi/pull/12586
Refs: https://github.com/strapi/strapi/issues/11509
=> FilterPopoverURLQuery: Remove all time-releated information from date

packages/core/content-manager/server/services/utils/configuration/layouts.js
In https://github.com/strapi/strapi/pull/12398 I didn't notice that the layout is also validated & processed by the bootstrap process. This PR refactors the validation, so that it doesn't invalidate fields with a modified size.
Before the field invalidation was triggered by two things:
- a new field was added
- the type of a field has changed
Now we have to validate, if the size of a field size is smaller than the allowed size of it. If so, everything is fine. If not, the field should be resized to it's maximum size. In case a field was added manually, a sensible default size should be applied.
1. Resize a field in the content manager
2. Restart strapi
3. Validate the size of field hasn't changed and the field is still in the proper position of the layout
1. Change the type of field to …
=> CM: Fix changed field sizes during the bootstrap process

packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js, packages/core/upload/admin/src/components/AssetList/tests/AssetList.test.js, packages/core/upload/admin/src/components/EditAssetDialog/index.js, packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap, packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
Swaps the width and height attribute for an `ImageAssetCard`.
It follows a convention to name the width first.
1. Navigate to the ML
2. Upload an image asset
3. Check that width and height are displayed as `width x height`
4. Edit the asset
5. Check the "Dimensions" displays the same format as in 3.
Fixes: https://github.com/strapi/strapi/issues/12594
=> ML: Swap width and height when displaying image dimensions

packages/plugins/graphql/server/format-graphql-error.js
Add a missing `new` keyword before ApolloError instanciation.
It breaks otherwise.
Throw an error so that it won't be caught by the first 5 ifs in `packages/plugins/graphql/server/format-graphql-error.js` (`formatGraphqlError`)
fix #12622
=> Add a missing new keyword when trying to format the graphql errors

packages/core/admin/admin/src/pages/MarketplacePage/components/PluginCard/index.js, packages/core/admin/admin/src/translations/en.json
Adds the copy command on plugin cards
Adds tracking for learn more and copy command
Click the copy command
=> [MARKET] add copy command and track usage data

packages/core/content-manager/server/tests/content-manager/content-types.test.e2e.js
Adds end-to-end tests for https://github.com/strapi/strapi/pull/12577.
Because the case it not obvious and it will help in the future to avoid this error.
Trust the test.
- https://github.com/strapi/strapi/pull/12577
=> CM: Add e2e tests for layout updates

packages/core/database/lib/dialects/mysql/index.js
fixes #11723
Based on: https://www.digitalocean.com/community/questions/how-to-disable-sql_require_primary_key-in-digital-ocean-manged-database-for-mysql
DigitalOcean forcefully requires primary keys on all tables, in Strapi we don't place primary keys on join tables for relations because they aren't needed. During the database initialization, we do some migration steps and it was during this the error occured. This PR disables this requirement for the session to allow the migration to function and shouldn't be needed later on.
=> Disable primary key requirement on session initialize

packages/core/upload/admin/src/components/EmptyAssets/EmptyAssetGrid.js
Changes the background gradient color for the media library empty view.
Using a theme color `neutral200` instead of a hardcoded value `#eaeaef`
/!\ The fix makes the light theme cards a little darker as there is no theme color matching the previous hardcoded color.
**Before**
**After**
=> fix(dark-mode): fixed medialib empty card grid

packages/core/admin/index.js
This PR merge the custom configuration for webpack-dev-server specified in `src/admin/webpack.config.js` with the application default.
The bug is described in #12667 
Specify a custom devServer configuration in `src/admin/webpack.config.js`:
```
'use strict';
/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
// Note: we provide webpack above so you should not `require` it
// Perform customizations to webpack config
// Important: return the modified config
config.devServer = {
...config.devServer,
port: 9000,
allowedHosts: 'all',
};
return config;
};
```
Then run `yarn strapi develop --watch-admin` and verify that port `9000` is used for the front-end development server.
Fixes #12667
=> fix: merge devServer custom configuration with default #12667

packages/core/admin/admin/src/content-manager/components/SelectWrapper/utils/getSelectStyles.js
Sets the CM relation selects background color to `neutral0`
**Before**
**After**
=> fix(dark-mode): fixed cm relation select bg color

packages/core/content-manager/server/tests/api/populate/filtering/index.test.e2e.js, packages/core/strapi/lib/services/entity-service/params.js, packages/core/utils/lib/convert-query-params.js
4.0.8 introduced a bug that breaks the populate filtering. This PR aims to resolve the issue by correctly passing down the entry schema in the `convertPopulateQueryParams` function.
Populate filtering is broken right now
1. Create a new app
2. Try to make a request with a populate + some filtering on it (eg: ?populate[relationField][filters][id][$eq]=2
3. It should work and return the expected data without throwing a 500 error.
Fix https://github.com/strapi/strapi/issues/12578
=> Fix the populate filtering

packages/core/database/lib/dialects/mysql/index.js
fixes: #12553
For some reason the initialize option for this didn't work on all schema changes, this PR forcefully ensures the check is passed during the schemaUpdate function.
Tested this fix manually using v4.1.2 as a base on a DO droplet + a managed MySQL database on DO.
=> Ensure the session PK check is disabled during schema update for MySQL

.github/dependabot.yml
Updates the dependabot config to use the right labels automatically
To include dependency upgrade in changelogs and to CI pass checks
=> Update dependabot label config

packages/plugins/documentation/server/utils/builders/build-api-responses.js
fix #12487
This solves #12487. The problem was just a missing `description` property in the response object of the 200 response.
Start the example getstarted project and look at the generated file **examples/getstarted/src/extensions/documentation/documentation/2.0.0/full_documentation.json**. It should now contain a `description` property for 200 response like it does for all other responses.
#12487
=> Include required description in 200 response

packages/plugins/documentation/server/utils/builders/build-api-endpoint-path.js
fix #12489
This solves #12489 by generating operationIds consisting of the HTTP verb and the route.
Start the example getstarted project and look at the generated file **examples/getstarted/src/extensions/documentation/documentation/2.0.0/full_documentation.json**. All operations should now contain a `operationId` field.
#12489
Should be merged after #12488 to avoid confusion or merge conflicts.
=> Set operationId

packages/core/content-manager/server/services/entity-manager.js
Fix #12004
In the project `getStarted`:
1. create a relation many-to-many between country and category.
2. in the file `src/index.js`, replace the bootstrap function by this one.
```js
async bootstrap({ strapi }) {
const countries = await strapi.entityService.findMany('api::country.country', {});
if (countries.length > 50) {
return;
}
const category = await strapi.entityService.create('api::category.category', {
data: {
name: 'Nice category',
},
});
for (let i = 0; i < 1000; i +=1) {
console.log('create country', i);
await strapi.entityService.create('api::country.country', {
data: {
name: `France-${i}`,
categories: [category.id],
},
});
}
},
```
3. start the project
4. in the CM, in `categories`, open the category `Nice category`
5. see that the loading time is reasonable and that the …
=> Fix loading time when opening an entity with many related entities

.github/PULL_REQUEST_TEMPLATE.md
Updates the wording of the PR template a little bit:
- swapped tests and documentation because usually you'd have to write tests first, before you contribute to the documentation
- mentioned the documentation repository instead of the documentation branch (which, I believe, doesn't exist anymore)
The improve the setup/ contributing experience.
=> Docs: Update PR template

packages/core/email/admin/src/pages/Settings/index.js
Fixed the translation key for the mail plugin.
I was working on a plugin that translates into Japanese, and I noticed that it didn't translate correctly.
Run examples/getstarted to enable the Japanese language setting.
This is because the default English and French languages do not have a translation key.
When I open the page in question, the buttons and text fields that should have translation keys are still in English.
Settings > Configuration
=> Translation key correction of wording

packages/plugins/users-permissions/admin/src/translations/en.json
fix #12671 
fix the placeholder of the input for the redirection of for email confirmation seems not correct.
=> fix: placeholder for email confirmation link input

packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js, packages/core/admin/admin/src/pages/AuthPage/index.js, packages/core/strapi/lib/Strapi.js
I added events to understand better why 13% of the users don't successfully create their first administrator account.
- didSubmitWithErrorsFirstAdmin
- willCreateFirstAdmin
- didOpenTab
- didNotOpenTab
We have too many users who are unsuccessful because of the bad UX, or at least, it's our assumption.
Update the generated UUID of the example project, run the project, launch the admin on port 4000, create your first administrator. Go to our telemetry system, then look for that specific UUID you created and look at the events received.
=> Add events to monitor first administrator account creation

packages/utils/logger/lib/default-configuration.js
This fix log level override of winston logger
Create `config/logger.js`
```js
"use strict";
level: env("STRAPI_LOG_LEVEL", "error"),
});
```
Using `strapi.log.silly('foo')` should output nothing
=> fix: winston default configuration

packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorStylesContainer.js, packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js
Set `line-height` of the editor content to `1.5`.
Currently, the `line-height` inherits from `body` where it is set to `1`. This lead to very tight leading, which makes the text inside of the editor hard to read.
Open WYSIWYG editor and edit text.
=> fix(editor): set proper line height

packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/schema.test.js, packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/utils/schema.js
Allow all URI schemes other than http(s) for validating reset password page field.
In order to cover cases such as deep link.
1. Go to http://localhost:1337/admin/settings/users-permissions/advanced-settings
2. Enter `abcd://test` in Reset password page
3. Save without regex validation error.
Closes #12629
=> Allow all URI schemes for setting reset password page

packages/core/admin/server/routes/serve-admin-panel.js
This add `cache-control: public, max-age=31536000, immutable` to `.js` and `.css` files served for the admin panel.
The `immutable` and long `max-age` can safely be used because [`[contenthash:8]` is used by webpack](https://github.com/strapi/strapi/blob/master/packages/core/admin/webpack.config.js#L63) to generate filenames
As you saw on this screen, the total admin sources take `8.7 MB`, which without this patch are always downloaded on each visit.
With this enabled, transferred size go down to `72.4 kB` on each visit (**which represent a ~120% bandwidth saving**)
Save bandwidth, save money, save the planet 👍 
close #12763
=> fix: serve admin static file with public cache

packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/index.js
Tries to use translation for category label in the dynamic zone component picker.
Internationalization of the admin panel.
Setup environment, create a dynamic zone with some components. Override the translation of the category name in `src/admin/app.js` (`config.translations`).
=> Make component category translatable

packages/core/utils/lib/convert-query-params.js, packages/plugins/graphql/tests/fields/date.test.e2e.js, packages/plugins/graphql/tests/fields/datetime.test.e2e.js
Adds a separated verification for date type in the filter. Currently filters with type `Date` are being incorrectly handled as objects when sanitizing.
Currently, the result it's parsing a date/datetime value as an operator, due to `isObject(date)` from lodash handling dates as Objects, but with this PR it should parse as a primitive value.
Filters of date and datetime are broken in GraphQL API. The query returns the entities without applying the filter.
See the issue mentioned below, the steps should be similar but for the `example/getstarted`.
Fix #12706 
The bug resulted from password sanitization in PR https://github.com/strapi/strapi/pull/11917 when released [v4.0.8](https://github.com/strapi/strapi/releases/tag/v4.0.8)
=> Fix sanitization of datetime type in query param

packages/generators/generators/lib/plops/prompts/get-attributes-prompts.js, packages/generators/generators/lib/plops/utils/validate-attribute-input.js, packages/generators/generators/lib/plops/utils/validate-input.js
Allow snake case in content type attribute names when generating them via the generator.
Strapi content types can have underscores, its common practice, so this should be reflected in the generator.
Strapi 3 has this too, so its a missing feature in strapi 4.
`npx strapi generate content-type`
__
**https://github.com/strapi/strapi/issues/12670**
=> Allow snake case in content type generator 

packages/core/admin/admin/src/components/AuthenticatedApp/index.js, packages/core/admin/admin/src/components/AuthenticatedApp/tests/index.test.js, packages/core/admin/admin/src/components/AuthenticatedApp/utils/api.js, packages/core/admin/admin/src/pages/Admin/index.js
Issue related: #12728 
Release notification called multiple times/stacking in Admin on reload (for example when saving a CT).
Moved `toggleNotification` call in `AuthenticatedApp` during `fetchStrapiLatestRelease` call.
- Make sure you're on an old version of Strapi (one way is to change Strapi version in admin/packages.json)
- Make sure you didn't disable release notification on locale storage by removing it
- You should see release notification appearing
- On submitting/saving a CT in CTB, only one release notification should be displayed
=> Fix / Release notification stacking

codecov.yml
In https://github.com/strapi/strapi/pull/12356 in realized codecov currently takes `.md` and `.mdx` files into account. Since we don't have any tests for these files, I think it makes sense to exclude them.
- https://docs.codecov.com/docs/ignoring-paths
Adding for example some docs to a PR would show the checks as failed since the code coverage decreased.
Rely on the automated checks.
=> Codecov: ignore md and mdx files

packages/core/admin/admin/src/content-manager/components/SelectWrapper/utils/getSelectStyles.js
Fixes the relation select in CM
Before
After
=> Dark mode/fix relation select fg color

packages/core/admin/admin/src/components/AuthenticatedApp/tests/index.test.js, packages/core/admin/admin/src/components/GuidedTour/Modal/tests/index.test.js, packages/core/admin/admin/src/components/Notifications/tests/index.test.js, packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js, packages/core/admin/admin/src/content-manager/pages/EditView/Header/tests/index.test.js, packages/core/admin/admin/src/content-manager/pages/EditView/Informations/tests/index.test.js, packages/core/admin/admin/src/content-manager/pages/NoContentType/tests/index.test.js, packages/core/admin/admin/src/content-manager/pages/NoPermissions/tests/index.test.js, packages/core/admin/admin/src/pages/ProfilePage/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/WebhookForm/tests/index.test.js, packages/core/admin/admin/src/pages/SettingsPage/tests/index.test.js, packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/index.test.js, packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/ListPage/tests/index.test.js, packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/index.test.js, packages/core/content-type-builder/admin/src/pages/ListView/tests/index.test.js
Fixed prop validation warning for `ThemeToggleProvider` in tests
=> fix: prop validation warning in dark mode tests

packages/core/helper-plugin/lib/src/components/DynamicTable/DynamicTable.stories.mdx, packages/core/helper-plugin/lib/src/components/DynamicTable/index.js
Adds the option to add a `footer` (e.g. `TFooter`) to the `DynamicTable` helper component.
So custom plugin development can use the `TFooter` from the Strap DS when using the `DynamicTable`.
(Re)build the `helper-plugin` and run its storybook with:
```bash
cd packages/core/helper-plugin
yarn build
yarn storybook
```
Check example at: http://localhost:6006/?path=/docs/components-dynamictable--delete-custom-components#usage-no-content-with-footer.
=> Add footer to DynamicTable component

packages/plugins/users-permissions/server/controllers/auth.js, packages/plugins/users-permissions/server/controllers/validation/email-template.js, packages/plugins/users-permissions/server/services/user.js
It adds an additional variable to e-mail templates ("Reset password" and "Email address confirmation") called `SERVER_URL` that holds the current absolute server URL provided by `getAbsoluteServerUrl(strapi.config)`.
When the same application is deployed in several environments (i.e. staging, production), the domain and thereby the URL's might change. The server URL is configurable in the strapi configuration (which might be done using environment variables). However, the content of e-mail templates is configured via the admin panel (or the config-sync plugin). This makes referencing the server URL a hassle. By having the server URL as a variable in e-mail templates, adding deeplink to your templates becomes much easier.
Add `<%= SERVER_URL %>` to the templates "Reset password" and "Email …
=> Add SERVER_URL variable to user e-mail templates

packages/core/helper-plugin/lib/src/components/GenericInput/index.js, packages/core/helper-plugin/lib/src/components/GenericInput/tests/__snapshots__/index.test.js.snap, packages/core/helper-plugin/lib/src/components/GenericInput/tests/index.test.js
Before this PR it was not possible to clear the value of a number input. This PR normalizes the saved value to `null`.
ℹ️ Why `??` instead of `||`?
```
0 || null => null
0 ?? null => 0
```
To be able to clear the number field.
1. Create a content type with a number field
2. Save a value
3. Reload
4. Clear the field
5. Save
6. Reload
7. Make sure the field is still empty
- Fixes: https://github.com/strapi/strapi/issues/12860
=> GenericInput: Allow number inputs to be cleared

packages/core/upload/server/services/upload.js, packages/core/upload/tests/upload.test.e2e.js
Assigns the `provider` property is unconditionally to uploaded file metadata before saving.
Previously the uploaded file data was assigned a `provider` in the conditional block that calculated dimensions on supported images. This caused the provider to get stored as `null` in the database for some upload types such as PDFs and SVGs.
* Run e2e tests at `packages/core/upload/tests/upload.test.e2e.js`
* Upload an SVG or PDF file via the Admin UI. Ensure the `provider` column in the `files` table contains a non-null value such as `"local"`
Fix #12885
=> Always set the provider property in uploaded file database entries

packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.js, packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
Since v4 only thumbnail images are loaded in the media library. However, this broke cropping images, because the crop would operate on the thumbnail image, instead of the original one, which leads to tiny images.
With this PR, we start cropping the original image again.
To make the crop function work.
1. Go to the media library
2. Upload an image
3. Edit the image and crop it (make the crop cover the full area or the original image)
4. Check the file-size of the generated image; it should be similar to the original one
- Fixes https://github.com/strapi/strapi/issues/12568
- Refs https://github.com/strapi/strapi/issues/12599
=> EditAssetDialog: Use original image as source for cropping

packages/core/upload/admin/src/hooks/tests/useAssets.test.js, packages/core/upload/admin/src/hooks/tests/useFolders.test.js, packages/core/upload/admin/src/hooks/useAssets.js, packages/core/upload/admin/src/hooks/useFolders.js
Similar to use `useAssets()` this PR adds a hook called `useFolders()`, which will be used to fetch folders from the API in the media library.
This PR adds tests to both of them.
To be able to fetch folders.
Not yet. It's preparation work.
=> ML: Add useFolders() hook

packages/core/upload/admin/src/utils/displayedFilters.js, packages/core/upload/admin/src/utils/getAllowedFiles.js, packages/core/upload/admin/src/utils/tests/getAllowedFiles.test.js
Since https://github.com/strapi/strapi/pull/12419 audio files can be uploaded & displayed in the media library. However, we never added a filter for it.
To be consistent with other mime-types which have a preview.
1. Upload an audio file to the ML
2. Select "type=audio" from the filter
3. Expect to see the audio file (only)
=> ML: Add audio type to asset filters

packages/plugins/graphql/server/bootstrap.js
This PR passes down `cors` and `bodyParserConfig` params to the Apollo Server middleware.
When enforcing `cors` with `/graphql` endpoint, if it is not passed down this middleware. `cors` will be set to `origin=*`.
```js
// apollo-server-koa/src/ApolloServer.ts - line 100
if (cors === true || cors === undefined) {
// Unlike the express `cors` package, `fastify-cors`, or Hapi, Koa's cors
// handling defaults to reflecting the incoming origin instead of '*'.
// Let's make it match.
middlewares.push(
middlewareFromPath(path, corsMiddleware({ origin: '*' })),
);
} else if (cors !== false) {
middlewares.push(middlewareFromPath(path, corsMiddleware(cors)));
}
```
Apollo Client (example: React) using `credentials=include` config which enforces cors
```js
const apolloLink = createHttpLink({
uri: …
```
=> fix: ApolloServer middleware CORS issue

packages/core/admin/scripts/build.js
It prevents the swallowing of errors thrown in e.g. webpack.
|---|---|
| <img width="1533" alt="Screenshot 2022-03-25 at 10 02 00" src="https://user-images.githubusercontent.com/2244375/160090215-da7dbd89-0858-4bbd-8b3c-57cfa08d0ee1.png">  |  <img width="1533" alt="Screenshot 2022-03-25 at 09 45 10" src="https://user-images.githubusercontent.com/2244375/160090267-83ec1c27-b17e-4009-ae3f-1e3e085ff1af.png"> | 
Better developer experience.
1. E.g. mess up a path, which leads to a webpack error.
2. Run `yarn build`
=> Build: Prevent output from swallowing webpack errors

packages/core/helper-plugin/lib/src/components/GenericInput/index.js
https://github.com/strapi/strapi/pull/12861 made it visible that we currently do not handle controlled components for input fields properly (it should pass down `defaultValue` and `value` instead).
This PR partly reverts to the previous behavior to prevent React warnings in development mode. I did not revert to the old behavior to have a central place to add a TODO and to make the file easier to understand.
To prevent React warnings in development mode.
> Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.*
Change the value of an empty text input field from nothing to something …
=> GenericInput: prevent controlled/ uncontrolled warnings

packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/hasContent.js, packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/tests/hasContent.test.js, packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js, packages/core/admin/admin/src/content-manager/utils/isFieldTypeNumber.js, packages/core/admin/admin/src/content-manager/utils/tests/isFieldTypeNumber.test.js
Fixes displaying number fields in list views, which broke with https://github.com/strapi/strapi/pull/12213
To properly display all field types in list views.
You can either trust the automated tests or create a content type that contains all sorts of number fields and/ or components containing these.
- https://github.com/strapi/strapi/pull/12213
=> CM: Fix displaying number fields in the DynamicTable

packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/hasContent.js, packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/tests/hasContent.test.js
Makes sure we display the ID for media and relations in single components in the list view instead of `-`
https://user-images.githubusercontent.com/2244375/160646312-f6082066-33ae-4132-8518-28180c033d6f.mp4
Consistency.
Create a table with components, which have a main field of type media or relation and see the value being displayed.
- https://github.com/strapi/strapi/pull/12213
=> DynamicTable: Show id for media and relations in components

packages/core/admin/admin/src/content-manager/components/FieldComponent/index.js, packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js, packages/core/admin/admin/src/content-manager/components/RepeatableComponent/utils/getComponentErrorKeys.js, packages/core/admin/admin/src/content-manager/components/RepeatableComponent/utils/tests/getComponentErrorKeys.test.js
This PR fixes a case, where an error within a nested repeatable component is not properly displayed on the accordion.
| Before  | After  |
|---|---|
| <img width="834" alt="Screenshot 2022-03-29 at 13 47 54" src="https://user-images.githubusercontent.com/2244375/160604731-850c2a23-e529-4160-ad0c-c1a45892ea25.png">  | <img width="834" alt="Screenshot 2022-03-29 at 13 47 25" src="https://user-images.githubusercontent.com/2244375/160604725-b63b20e1-52bf-4d3b-99ff-975b82a7c53d.png">  |
So content editors can see where an error occurred. 
1. Use the Restaurant content type
2. Make one field of the "Dish" component required
3. Try to publish the content-type with the required field being empty
=> RepeatableComponent: Fix error messages when component is nested

packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
Allows fields of type `date` to be selected as a components main field.
Because all other date flavours (time, dateTime) are already selectable.
1. Create a component that contains a field of type date
2. Configure the view of the component to use the date field as entry title
- Fixes https://github.com/strapi/strapi/issues/12974
=> Allow date fields to be selected as component main fields

packages/core/admin/server/config/admin-actions.js, packages/core/admin/server/tests/admin-permission.test.e2e.js
Adds a permission in the core package for updating project settings.
Needed for **logo customization** and next customization features / project level settings.
=> feat(menu-logo): added a permission for project level settings

examples/getstarted/package.json, packages/generators/app/lib/utils/db-client-dependencies.js, yarn.lock
Some M1 mac users still are failing to install better-sqlite3 without build tools:
> prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=arm64 libc= platform=darwin)
> ENOENT: no such file or directory, symlink -snip-/node_modules/better-sqlite3/deps/sqlite3/sqlite3.c' -> '-snip-/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3/sqlite3.c'  failedTask=build stackTrace=Error: ENOENT: no such file or directory...
Per this issue: https://github.com/JoshuaWise/better-sqlite3/issues/771#issuecomment-1054182344
> This problem has been introduced in the 7.5.0 release, downgrading to 7.4.6 the build process works correctly.
=> Fix better-sqlite3 version

packages/core/upload/server/__tests__/bootstrap.test.js, packages/core/upload/server/bootstrap.js, packages/core/upload/server/services/provider.js
It implements `uploadStream` wrapping for `actionOptions`.
Thank you @neilpoulin for catching the issue and spotting the cause!
- Re-opens: https://github.com/strapi/strapi/pull/12838
- Fixes https://github.com/strapi/strapi/issues/12809
- Docs: https://github.com/strapi/strapi/pull/12959
=> Fix actionOptions not taking into account by the upload provider

packages/core/admin/package.json
It adds a missing dependency to the admin panel.
Babel polyfill is now needed in the webpack config so we need to add it to the package's dependencies.
=> Add missing babel polyfill dependency

packages/plugins/i18n/server/constants/iso-locales.json, packages/plugins/i18n/server/services/__tests__/__snapshots__/iso-locales.test.js.snap
Added Sanskrit (ISO 639-1 code `sa`) to `/packages/plugins/i18n/server/constants/iso-locales.json`
=> Added Sanskrit (sa) to i18n locales

examples/kitchensink-ts/index.d.ts, examples/kitchensink-ts/src/index.ts, packages/core/strapi/lib/index.d.ts
Simply export the StrapiInterface type so that it can be extended by the user in its custom definition files.
This allows users to benefit from future Strapi typings updates and add their definitions.
Note: The `AllTypes` interface is still exposed globally, but it shouldn't be used now as it's considered unstable. The next iteration on `Strapi` <> `TypeScript` will replace this interface with another one. Thus, it's strongly advised not to use it.
Currently, the `StrapiInterface` isn't exported, which means that the `Strapi` type based on it cannot be extended to fit specific users' needs.
Create a test project & add an `index.d.ts` file containing the following snippet:
```typescript
import '@strapi/strapi'
declare module '@strapi/strapi' {
interface StrapiInterface { …
```
=> [TS] Allow to extend the StrapiInterface type

packages/core/admin/index.js, packages/core/admin/utils/create-cache-dir.js, packages/core/admin/webpack.config.js, packages/core/strapi/lib/commands/build.js, packages/core/strapi/lib/commands/builders/admin.js, packages/core/strapi/lib/commands/builders/typescript.js, packages/core/strapi/lib/commands/develop.js, packages/core/strapi/lib/commands/watchAdmin.js, packages/core/strapi/lib/core/loaders/plugins/get-enabled-plugins.js, packages/generators/app/lib/create-project.js, packages/generators/app/lib/resources/json/ts/tsconfig-admin.json.js, packages/generators/app/lib/resources/json/ts/tsconfig-server.json.js, packages/generators/generators/lib/files/ts/plugin/strapi-server.js, packages/generators/generators/lib/files/ts/plugin/tsconfig.json, packages/generators/generators/lib/plops/api.js, packages/generators/generators/lib/plops/content-type.js, packages/generators/generators/lib/plops/controller.js, packages/generators/generators/lib/plops/middleware.js, packages/generators/generators/lib/plops/plugin.js, packages/generators/generators/lib/plops/policy.js, packages/generators/generators/lib/plops/service.js, packages/generators/generators/lib/templates/ts/plugin-package.json.hbs, packages/utils/typescript/lib/configs/admin.json, packages/utils/typescript/lib/configs/server.json, packages/utils/typescript/lib/utils/get-config-path.js, packages/utils/typescript/lib/utils/index.js, packages/utils/typescript/lib/utils/is-using-typescript-sync.js, packages/utils/typescript/lib/utils/is-using-typescript.js
See #12927 
- clone the monorepository
- create a new Strapi project using the cli (in the monorepo) with --ts
- the project should have been created with 2 tsconfig.json files (one at the root level & another one in src/admin)
- try to yarn develop inside this project
- everything should work correctly
#12927
=> [TS] Updated tsconfigs design for generated app

packages/core/admin/server/controllers/admin.js, packages/core/admin/server/routes/admin.js, packages/core/admin/server/services/__tests__/project-settings.test.js, packages/core/admin/server/services/index.js, packages/core/admin/server/services/project-settings.js, packages/core/admin/server/utils/index.d.ts, packages/core/admin/server/validation/project-settings.js
- It adds `POST /project-settings` route in the admin API
- It takes `form-data` to allow file upload
- It allows to update/delete a custom menu logo
- It is restricted to users with `admin::project-settings.update` permission
Example requests:
**Logo upload | POST /project-settings**
Body:
```
menuLogo: file.png
```
Response:
```json
{
"menuLogo": {
"name": "file.png",
"url": "/uploads/file_201796d45f.png",
"width": 498,
"height": 570,
"ext": ".png",
"size": 24.61
}
}
```
**Logo delete | POST /project-settings**
Body:
```
menuLogo: (empty)
```
Response:
```json
{
"menuLogo": null
}
```
This is necessary for the menu logo customization feature + upcomming project wide settings for customization
=> Menu logo/update project settings route

packages/core/upload/package.json
Update sharp package version from 0.30.1 to 0.30.4 
Strapi server crashed with  error when upload big image (15Mb). 
Image was photographed on Samsung device.
Error: `Error: VipsJpeg: Invalid SOS parameters for sequential JPEG`
I found sharp issue - https://github.com/lovell/sharp/issues/2780
They recommend add sharp option `failOnError: false` on sharp transformer creation.
But `failOnError` option deprecated in [v0.30.4](https://github.com/lovell/sharp/blob/main/docs/changelog.md#v0304---tbd) in favor `failOn` option.
`failOn`has `warning` value by default and  should not crash strapi server on uploading invalid images.
[sharp docs](https://github.com/lovell/sharp/blob/926572b41ea363ede57189128441a42fb77f66f4/docs/api-constructor.md#parameters):
> options.failOn …
=> FIx upload error: Error: VipsJpeg: Invalid SOS parameters for sequential JPEG

packages/providers/upload-aws-s3/README.md, packages/providers/upload-cloudinary/README.md
Just adds the airtable url to the allowed CSP settings for the upload provider readme files.
=> add marketplace media csp settings to provider docs

packages/core/admin/admin/src/pages/MarketplacePage/components/PluginCard/index.js, packages/core/admin/admin/src/pages/MarketplacePage/tests/index.test.js
Reduce horizontal padding on marketplace cards from 24px to 16px
To prevent the buttons in marketplace cards from having to do a line break on most screen sizes
=> Shrink marketplace cards padding

packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
This brings single content types in line with collection types, when errors from e.g. lifecycle events need to be displayed. Collection types display the error message defined in the backend, where as single types only displayed "Bad Request".
Solves an issue by a user. Error messages should be as helpful as possible.
1. Create a new content-type (single)
2. Create a file called `lifecycles.js` in `./src/api/[content-type]/content-types/` with the following content:
```js
const { ForbiddenError } = require("@strapi/utils").errors
async beforeCreate(event) {
console.log('wwatt')
throw new ForbiddenError("Custom error")
}
}
```
3. Try to save the content type
4. Validate the error message displayed contains the text "Custom error"
- Fixes …
=> SingleTypeFormWrapper: Display custom error messages

packages/core/helper-plugin/lib/src/utils/auth/index.js
GUIDED_TOUR_SKIPPED variable in local storage wasn't memorized when logging out
Memorize GUIDED_TOUR_SKIPPED before clearing local storage
setItem after clearing local storage
=> [Fix] Guided tour skipped local storage

packages/core/utils/lib/__tests__/hooks.test.js, packages/core/utils/lib/hooks.js
Fixes hooks getter being spread thus not allowing changes to handlers (delete is not working correctly).
To allow unregistering a hook for customization purposes.
try to delete a hook (e.g https://gist.github.com/alexandrebodin/62e5b0b446b9494c81ce672feaf0def3) to replace it with another function.
=> fix: hook getter spread make handlers invalid

examples/getstarted/src/extensions/users-permissions/content-types/user/schema.json, packages/core/admin/server/services/__tests__/permissions-manager-sanitize.test.js, packages/core/admin/server/services/permission/permissions-manager/sanitize.js, packages/core/admin/server/services/user.js, packages/core/content-manager/server/tests/api/basic.test.e2e.js, packages/core/content-type-builder/server/services/schema-builder/component-builder.js, packages/core/content-type-builder/server/services/schema-builder/content-type-builder.js, packages/core/content-type-builder/server/services/schema-builder/index.js, packages/core/content-type-builder/server/services/schema-builder/schema-handler.js
It removes hidden attributes from responses in the admin API responses.
Since `hidden` attributes are meant to be hidden from the admin panel, it makes no sense to return them in the API responses. 
1. Set any attribute of any content type as "hidden"
2. Create some data for that specific content type
3. Go to the edit view or the list view of the admin panel
4. Check the network console of your browser to see if the attribute is omitted in the GET call.
=> Sanitize hidden attributes from admin API responses

packages/core/strapi/lib/middlewares/body.js, packages/core/strapi/package.json, packages/core/upload/package.json, packages/core/upload/server/graphql.js, yarn.lock
While debugging https://github.com/strapi/strapi/issues/12761 we discovered that koa sometimes fails to set a mime-type for uploaded files through the API. Instead, it assumes `null` and is written to the database, which causes the admin panel to crash, because we rely on the presence of a mime-type in several cases (e.g. to different components for different assets). A working python reproduction can be found here: https://github.com/gu-stav/strapi-upload-rest-graphql
This PR fixes the root cause, however, we might need more work to fully fix the issue, since users might have a corrupted database state. We could therefore create a migration. If we decide on migration the frontend can stay as it is. If not, we need to handle the case, that an asset doesn't have a mime-type and display the …
=> ML: Apply fallback mime-type if none is set

packages/plugins/users-permissions/server/controllers/auth.js
Fix `emailConfirmation` inside the `auth` controller
`emailConfirmation` method is failed because `userService.fetch` applies only `id` after [User population](https://github.com/strapi/strapi/pull/11960) was merged.
strapi@4.1.10
An error when I try to use email confirmation:
```
Undefined attribute level operator confirmationToken
at processAttributeWhere (node_modules/@strapi/database/lib/query/helpers/where.js:82:13)
at processWhere (node_modules/@strapi/database/lib/query/helpers/where.js:176:36)
at node_modules/@strapi/database/lib/query/helpers/where.js:104:29
at Array.map (<anonymous>)
at Object.processWhere (node_modules/@strapi/database/lib/query/helpers/where.js:104:18)
at Object.processState (node_modules/@strapi/database/lib/query/query-builder.js:234:29)
at …
```
=> Fix email confirmation

packages/core/admin/admin/src/content-manager/components/SelectWrapper/utils/getSelectStyles.js
Fixed unreadable select input text in dark mode
Helps users see what they are typing
Ran yarn test:unit and yarn test:front
Additionally, we also re-created the behavior mentioned in issue #13149, and now input text appears as expected
#13149
=> fix: issue #13149 input color

packages/core/helper-plugin/lib/src/components/ReactSelect/utils/getSelectStyles.js, packages/core/upload/admin/src/components/EditFolderDialog/tests/__snapshots__/EditFolderDialog.test.js.snap, packages/core/upload/admin/src/components/SelectTree/tests/__snapshots__/SelectTree.test.js.snap
Backports the change from https://github.com/strapi/strapi/pull/13291 into the new component structure, which will be part of the media library folders.
To not re-introduce a bug, once the feature is merged.
- https://github.com/strapi/strapi/pull/13291
=> ReactSelect: Backport changes from #13291

packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
Fixed required field checkbox to be on the left side to be consistent with other content-types
=> [Fix] CTB Media advanced settings layout

packages/core/admin/admin/src/pages/HomePage/ContentBlocks.js
To have a better idea of how useful homepage links are, 4 trackUsage events were added: 
- didClickonReadTheDocumentationSection
- didClickonCodeExampleSection
- didClickonTutorialSection
- didClickonBlogSection
=> [Enh] Homepage links trackUsage

packages/plugins/documentation/server/config/default-plugin-config.js
Adds the `items` property to the Error schema 
it is required for `type: array`
https://swagger.io/docs/specification/data-models/data-types/#array
Otherwise it causes an infinite loader
Open the documentation, go to the Error schema, click on data, click on the array. 
You should see an empty object inside instead of an infinite load
=> add missing items property causing infinite load on error schema

packages/generators/generators/lib/plops/utils/__tests__/get-file-path.test.js
Increased test coverage for generators/lib/utils/get-file-path
Three different paths in get-file-path.js in the generators/lib/utils were not being tested. I have added test cases to make sure it returns the right route according to the given destination.
Run unit tests with yarn/npm. You can also use WebStorm IDE to run tests directly in the added file
Increased test coverage for generators/lib/utils/get-file-path. No related issues.
=> Increase test coverage for get-file-path util

packages/plugins/documentation/__tests__/build-component-schema.test.js, packages/plugins/documentation/server/services/helpers/build-component-schema.js
Returns all attributes for post requests distinguishing required attributes from non-required attributes.
https://swagger.io/docs/specification/2-0/describing-request-body/
fixes: #12887
Create a content type with required and non-required attributes. Open the documentation and look at the post request schema. The required should be marked required with a red `*`. The data object should always be marked required. Localization requests should also have `locale` marked as required.
=> [plugin:documentation] fix required attributes on post requests

packages/core/strapi/lib/services/entity-validator/__tests__/biginteger-validators.test.js
Test validates the min constraint if no min is specified.
The file biginteger-validators.test.js did not have test for min while test files for integer-validators.test.js and float-validators.test.js had the min tests.
Test can be run through IDE, such as WebStorm, or using yarn/npm command.
No related issues.
=> Added test to validate the min constraint for big integer if no min is specified

packages/core/strapi/lib/services/entity-validator/__tests__/email-validators.test.js, packages/core/strapi/lib/services/entity-validator/validators.js
Check for not empty string or not null value accepted by API.
When I send a POST request to API with an email field type, for example: 
`{
"data": {
"email": ""
}
}` 
It creates an empty object and get a 200 OK response.
1. Create a collection type with a required email field
2. Send a post request with an empty string for the field
3. Now get a 400 Validation Error instead 200.
Related Issue: [12081](https://github.com/strapi/strapi/issues/12081)
=> #12081 Fix empty string is accepted by API

packages/providers/upload-aws-s3/README.md, packages/providers/upload-cloudinary/README.md, packages/providers/upload-rackspace/README.md
ℹ️  To be merged after https://github.com/strapi/strapi/pull/13018 is released.
In https://github.com/strapi/strapi/pull/12889 we realized some documentation on how to configure upload providers was missing.
Better docs lead to a better developer experience.
- https://github.com/strapi/strapi/pull/12889
- https://github.com/strapi/strapi/pull/12838
- https://github.com/strapi/strapi/pull/13018
=> Docs: Update upload provider readme files

packages/core/strapi/lib/core/loaders/apis.js
I want to track the folders in /src/api in their own git repo, as I can imagine reusing some of that on different projects. I ended up with /src/api/.git/config, which I think made the loader try to add .git as a content type. :)
The error message when I ran strapi develop was:
```
error: ENOTDIR: not a directory, scandir '/api/src/api/.git/config'
api         | Error: ENOTDIR: not a directory, scandir '/api/src/api/.git/config'
```
loadDir was checking that the path to "config" existed, but not that config was folder, so fse was getting confused at readdir. This adds an additional check that config is a directory rather than a path.
=> fix: skip git config file that looks like dir

packages/core/strapi/lib/index.d.ts
Adds the missing StrapiInterface and exports it from `@strapi/strapi`.
=> [TS] Add missing StrapiInterface 

packages/plugins/users-permissions/server/graphql/mutations/auth/email-confirmation.js
Fix emailConfirmation graphql mutaion to correctly call auth.emailConfirmation by passing args as query instead of request.body
To let graphql mutation confirm email using confirmation code
Register a user and get confirmation code from email to test with graphql request below
```
{"query":"\n  mutation ($confirmation:String!){\n    emailConfirmation(confirmation: $confirmation) {\n      jwt\n    }\n  }\n  ","variables":{"confirmation":"code-from-email"}}
```
Related issue #12772
=> fix emailConfirmation graphql mutation

packages/providers/upload-aws-s3/README.md
Add information for security settings in middleware.js if dots in a bucket name are used.
If a bucket name has dots in it, the url of the ressources in the buckets are different to buckets with names without dots. This has consequences what to add to the security settings in middleware.js.
Uploading and deleting files to s3 buckets with and without dots in their names.
=> dots in bucket names

packages/core/database/lib/__tests__/lifecycles.test.js, packages/core/database/lib/entity-manager.js, packages/core/database/lib/lifecycles/index.d.ts, packages/core/database/lib/lifecycles/index.js
Fix state not being shared between "beforeXXX" and "afterXXX" events, as described in the documentation here:
https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#hook-event-object
The feature is described in the documentation.
Sharing state can be useful to update external resources for instance.
* Create a content-type `<type>` from the UI
* Create `lifecycles.js` file in `src/api/<type>/content-types/<type>`
* Minimal test case code
```js
async beforeUpdate(event) {
event.state = 'hello world';
return event;
},
async afterUpdate(event) {
// event.state is undefined before this fix, but it should be set to 'hello world'
console.log(event.state);
},
};
```
None
=> Fix state not being shared with "beforeXXX" and "afterXXX" events

packages/core/content-type-builder/admin/src/utils/formAPI.js
add validators and forms after the if clause
fixes #13322
Basically as described in #13322 
The registration of validators and forms is done after the if clause where it is checked for if a validator for the specific field is in the defined attributes
When the field is in the defined attributes, it could not be extended anymore
See #13322 
See #13322
=> Fix CTB not adding all field extensions

packages/core/strapi/lib/commands/admin-create.js, packages/core/strapi/lib/commands/admin-reset.js, packages/core/strapi/lib/commands/build.js, packages/core/strapi/lib/commands/configurationDump.js, packages/core/strapi/lib/commands/configurationRestore.js, packages/core/strapi/lib/commands/console.js, packages/core/strapi/lib/commands/develop.js, packages/core/strapi/lib/commands/routes/list.js, packages/core/strapi/lib/commands/start.js, packages/core/strapi/lib/commands/watchAdmin.js, packages/utils/typescript/lib/utils/index.js, packages/utils/typescript/lib/utils/resolve-outdir.js
Get the outDir path for compiled code from tsconfig instead of using 'dist' statically
if the user changes the outDir value all cli commands fail to excute since they will be looking for a dist folder
Start a typescript project, and change outDir value in tsconfig, then test the cli commands, the compiled and build code should be in a directory with the name specified in outDir.
=> Typescript Fix cli commands when outDir is changed

packages/utils/typescript/lib/configs/server.json
Adds incremental builds by default for the generated tsconfig.json files.
Increase builds time and decreases used resources
1. Create a new TS project
2. Check that the incremental option is enabled in the generated tsconfig.json file
3. Make the first compilation, change a small line of code somewhere, and then rebuild. The second build should be faster than the first.
=> Add incremental build by default in the generated tsconfig.json

packages/core/database/lib/index.d.ts
Fixes #13287 
As described in the mentioned issue. Most of the parameters listed in the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/filtering.html#logical-operators) are missing. Only the and, or and not was added so far. 
This PR adds all missing attributes so that the typing for the WhereParams is correct.
It adds the filter parameters `$eq`, `$ne`, `$in`, and all others while supporting the nested structure.
As of now the typescript complirer throws an error on the where clause. Example:
```ts
const data = await strapi.query('api::bber-post.bber-post').findMany({
where: {
$and: [
{ date: { $gte: '2019-01-01' } },
{ date: { $lt: '2020-01-01' } }
]
}
});
```
this was not possible, because `$gte` and `$lt` where both within …
=> [@strapi/database]: Add missing WhereParams attributes to the type definition 

packages/plugins/documentation/__tests__/build-component-schema.test.js, packages/plugins/documentation/server/services/helpers/build-component-schema.js
Adds the type attribute to ListResponse and Response component schemas in the Documentation plugin.
This is required to make TypeScript type generation work from the OpenAPI specification
1. Generate a new strapi app
2. Install Documentation plugin
3. Start strapi app
4. Open ./src/extensions/documentation/documentation/1.0.0/full_documentation.json
5. Search for UsersPermissionsUserListResponse or UsersPermissionsUserResponse
These component definition lacked the type attribute at the top level before this PR.
fixes #13373
=> Fix generation of OpenAPI documentation with top level type attribute

examples/getstarted/.gitignore
API endpoints and content-types created with name "coverage" will be omitted unless exempted
We can all now use the word `coverage` as a collection-type or single-type without fear.
We know we used a reserved word usually meaning "test coverage" which `.gitignore` prevents from going out to our friends and colleagues using our `Strapi` implementation.
Because `coverage` is a normal word to use in day-to-day life, as it pertains to `geographical` coverage, etc. We really, in a way, just saved "the world" here. Believe it or not.
Create a new `Strapi` implementation using `--quickstart` and relax, seeing that when we `commit` updates to endpoints and schema, all our team members and out future selves, will have `coverage` in the repository, even though it is a reserved word.
=> Update .gitignore to allow use of word "coverage"

yarn.lock
When I merged the yarn lockfile of master and the media library folder feature branch earlier, I made the mistake to resolve the conflicts by running `yarn setup` which brought us into the state, where the tests (lint stage) won't pass any longer, because `@redis/client` is not compatible with node 12 any longer.
This PR resets the lockfile to master and installed new dependencies (mainly `uuid`) by running `yarn install`, which doesn't update the lockfile for other dependencies than that.
To make the tests work again.
=> ML: Update yarn lockfile with latest changes from master

.github/workflows/addToProject.yml
Will need to have the ~~`ADD_TO_PROJECT_PAT`~~ `PROJECT_TRANSFER_TOKEN` secret added before merged.
Automatically adds new GitHub issues to the following project: https://github.com/orgs/strapi/projects/15/views/1
=> Automatically add new github issues to support project

packages/core/upload/admin/src/hooks/tests/useBulkMove.test.js, packages/core/upload/admin/src/hooks/useBulkMove.js
Adds a hook similar to `useBulkDelete` to move assets and folders in bulk.
To support all required actions in the media library.
Until implemented you can rely on the automated tests.
=> ML: Add bulk move hook

scripts/front/add-missing-keys-to-other-language.js
Fixes a bug that doesn't affect many users but causes unit tests to fail.
There is a `require.main === module` in the file, Next to the `argv` check file,
All I did was moving `argv` check within the `if` block to prevent the check when the module is being imported (like in the `scripts/front/__tests__/add-missing-keys-to-other-language.test.js`)
The file is not imported anywhere, I'm not sure if anyone imports `updateMissingKeysToJSON` from this file (which is a script => `scripts/front/add-missing-keys-to-other-language.test.js`),
Maybe deleting the `module.exports` and the `require.main === module` check is a better refactoring solution,
I agree with you, "Why is it needed?"
Run `yarn test:unit` in the "main" branch and compare the output of the same command within this PR's branch.
=> Prevent `argv` check on "add-missing-keys-to-other-language"

packages/core/content-manager/server/services/entity-manager.js
Removes the hard limit on deep populate for an entity.
(It was not possible before but since we populate relations only once, it is possible to remove the limit)
In order to populate the admin edit view when there are more than 2 levels of nested components.
1. Create compo1 with a field "name"
2. Create compo2 with a field "compo1" and a field "name"
3. Create compo3 with a field "compo2" and a field "name"
4. Create a content-type "dog" with a field "compo3"
5. Create an entry for the content-type "dog" with all the components filled
6. Save and see that the data is correctly displayed
NB: component creation is possible only by editing the files directly, not through the content-type builder.
- https://github.com/strapi/strapi/issues/11319
- …
=> Remove limit on deep populate on components

packages/core/database/lib/index.js, packages/core/database/lib/query/query-builder.js, packages/core/upload/server/controllers/admin-folder-file.js, packages/core/upload/server/services/folder.js, packages/core/upload/tests/admin/folder-structure.test.e2e.js
- Use transactions for some actions (update folder location + bulk move)
- Add transaction implementation to the queryBuilder
=> Ml folder/transactions

packages/core/utils/lib/__tests__/validators.test.js, packages/core/utils/lib/validators.js
`strapiID` got broken when upgrading yup from `0.28.1` to `0.32.9` : the mixed class is exported in a different key.
`strapiID` was not checking anything.
=> Fix yup strapiID not working

packages/core/upload/package.json
Updates Sharp to latest version
CVE Details: https://github.com/advisories/GHSA-gp95-ppv5-3jc5
Low sev as it requires your build env to be vuln but it's a quick fix.
Install and run `yarn audit` check to make sure there is no CVE alert
N/A
=> Fix CVE-2022-29256

packages/plugins/documentation/package.json
Updates Swagger UI (I did look through their change log and the only breaking change I saw was moving from react 15 to 17 which we already use anyway)
Fix these:
- https://github.com/advisories/GHSA-6c9x-mj3g-h47x
- https://github.com/advisories/GHSA-qrmm-w75w-3wpx
Run a yarn audit and check the two advisories are gone
N/A
=> Fix CVE-2021-46708

packages/core/upload/admin/src/components/EditAssetDialog/index.js, packages/core/upload/admin/src/hooks/useEditAsset.js
When you change the location of an asset in the `EditAssetDialog` previously the file was not moved. This PR fixes the problem. I will add a test in another PR later to cover the issue.
To be able to move files.
=> EditAssetDialog: Fix changing folder location

packages/core/upload/admin/src/components/EditFolderDialog/EditFolderDialog.js, packages/core/upload/admin/src/pages/App/MediaLibrary.js
Fixed not checking if `currentFolderToEditRef` exists, which doesn't when on create mode
Fixed passing undefined value to `name` TextInput when on create mode
=> [ML Folder] fixes EditFolderDialog

packages/core/upload/admin/src/components/MediaLibraryDialog/index.js
This PR fixes a case, where the user wasn't redirected properly after creating a folder or uploading a file using the modal from a richtext field.
To properly give location context for the user.
1. Open an media library modal from a richtext field
2. navigate into a folder
3. create a folder or upload a file
4. you should still be in the proper location
=> MediaLibraryDialog: Fix displayed location after changes

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js, packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/index.test.js
Forces the filter in the `AssetModal` to be open, regardless of the asset or folder count, if the user is filtering.
To properly support filtering.
1. Open the media library modal
2. Select a filter, by which neither assets nor folders are returned
3. Confirm the filter toolbar is still visible
=> BrowseStep: Always display filter toolbar (regardless of asset/ folder count)

packages/core/upload/admin/src/hooks/useEditAsset.js
Re-fetches folders, after an asset was edited. If an asset gets moved, the asset count on one or more folder cards might change.
This PR ensures the counts are always in sync with the database.
1. Move an asset into a sub-folder of your current folder.
2. Confirm the asset count of that sub-folder was updated.
=> useEditAsset: Re-fetch folders after edit

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js, packages/core/upload/admin/src/components/AssetDialog/index.js
This PR allows users to edit folders directly from the `AssetDialog`.
To be consistent with assets.
=> AssetDialog: Allow folders to be edited

packages/core/upload/admin/src/components/AssetDialog/DialogHeader.js
- Fixed back button + folder title alignment
- Added hover state to back button to make it more clear that an action is available
⚠️ wait for design approval before merging
=> [ML Folder] AssetDialog header improvements

packages/core/upload/admin/src/components/EditFolderDialog/EditFolderDialog.js, packages/core/upload/admin/src/translations/en.json
Fixed folder count not showing in EditFolderDialog
Fixed count information format
=> [ML Folder] Fix count info in EditFolderDialog

packages/core/upload/server/controllers/content-api.js, packages/core/upload/server/routes/content-api.js
Remove count controller from upload plugin
Detected that count controller (& route) is defined, but count service is not defined, after raising this in an issue, staff mark as TODO to remove the count controller for upload.
Plugin upload should not contain neither the count route, neither the controller method/
fixes https://github.com/strapi/strapi/issues/13011
=> Fix upload plugin

packages/core/upload/admin/src/components/EditAssetDialog/index.js
Properly set the `disabled` prop on the location field of the `EditAssetDialog`, if the user does not have permissions or is in cropping mode, same as all other fields.
Consistent UI.
=> EditAssetDialog: Disable location select field conditionally

packages/core/upload/admin/src/components/AssetDialog/BrowseStep/tests/__snapshots__/index.test.js.snap, packages/core/upload/admin/src/components/FolderCard/FolderCard/FolderCard.js, packages/core/upload/admin/src/components/FolderCard/tests/__snapshots__/FolderCard.test.js.snap
This PR increases / fixes the size of the folder icon.
Signed off by @maevalienard.
To look 💅🏼 .
=> FolderCard: Increase icon size

packages/core/upload/server/services/upload.js
I added missing `await` in upload plugin
The service's `replace` function is not awaiting for file uploads. This results in the database data to be corrupt as instead of including uploaded data, it includes a JSON stringified version of the temporary file stream
Before change: "replace media" and check that in the database data, the thumbnail doesn't have a url, but has the node stream file properties
After change: it works
N/A
=> add missing await in upload plugin
