- packages/strapi-plugin-upload/admin/src/components/CardImgWrapper/index.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/ErrorMessage.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/FileWrapper.js
- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/tests/reducer.test.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/tests/reducer.test.js
Error state in CTM and plugin Edit modals
> Edit Error states

- packages/strapi-helper-plugin/lib/src/components/BackHeader/StyledBackHeader.js
- packages/strapi-helper-plugin/lib/src/components/BackHeader/index.js
This PR adds an event in order to improve the UX.
> Add BackButton event

- packages/strapi-helper-plugin/lib/src/utils/generateSearchFromFilters.js
- packages/strapi-plugin-upload/admin/src/components/ModalHeader/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/utils/generateStringFromParams.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/utils/tests/generateStringFromParams.test.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
This PR adds the selected filters to en count endpoint
> [ML] Fix count endpoint

- packages/strapi-plugin-upload/admin/src/components/Card/index.js
- packages/strapi-plugin-upload/admin/src/components/CardControl/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/FileInfos/index.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/index.js
- packages/strapi-plugin-upload/admin/src/components/ListEmpty/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/ListWrapper/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-upload/admin/src/icons/Download/index.js
ListView baseline with filters
EditView clickable icons sizes
Images dimensions
Pagination margin
> Media lib UI

- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
> Add disable state when uploading media

- packages/strapi-plugin-upload/admin/src/components/SelectedAssets/SortableList.js
Fix the preview in the selected assets
> Fix preview URL on selected asset

- packages/strapi-plugin-upload/admin/src/components/CardWrapper/index.js
- packages/strapi-plugin-upload/admin/src/components/ModalHeader/BackButton.js
- packages/strapi-plugin-upload/admin/src/components/ModalNavWrapper/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/Container.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/CustomModalSection.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/index.js
> Fix the modal list view in the Media Library

- packages/strapi-helper-plugin/lib/src/components/PageFooter/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/CardBorder/index.js
- packages/strapi-plugin-upload/admin/src/components/ListEmpty/Wrapper.js
Signed-off-by: Ky <virginie.ky@gmail.com>
> Media lib pagination alignment 

- examples/getstarted/api/homepage/models/homepage.settings.json
- packages/strapi-plugin-upload/admin/src/components/BrowseAssets/index.js
- packages/strapi-plugin-upload/admin/src/components/Card/index.js
- packages/strapi-plugin-upload/admin/src/components/CardWrapper/index.js
- packages/strapi-plugin-upload/admin/src/components/Filters/index.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard/index.js
- packages/strapi-plugin-upload/admin/src/components/FiltersPicker/index.js
- packages/strapi-plugin-upload/admin/src/components/List/index.js
- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/tests/reducer.test.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
- packages/strapi-plugin-upload/admin/src/utils/formatFilters.js
- packages/strapi-plugin-upload/admin/src/utils/index.js
- packages/strapi-plugin-upload/admin/src/utils/tests/formatFilters.test.js
Fix the filters in the Media Library and the allowed types in the Input file
> Fix filters and allowed types

- docs/3.0.0-beta.x/guides/custom-admin.md
- docs/3.0.0-beta.x/guides/registering-a-field-in-admin.md
- docs/3.0.0-beta.x/plugin-development/frontend-settings-api.md
- docs/3.0.0-beta.x/plugins/upload.md
This PR fixes some typos spotted in the created documentation.
> Media lib doc typos

- docs/.vuepress/config.js
- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/reducer.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/schema.js
This PR is the first step towards fixing the input type field. When the users clears an input password it will remove the key from the data in order to remove the unwanted changes. Also, the required validation will not be applied for this specific field when editing a document.
> Fix input type and add clear logic for this field type

- docs/3.0.0-beta.x/cli/CLI.md
- packages/strapi-admin/index.js
- packages/strapi/bin/strapi.js
- packages/strapi/lib/commands/build.js
This PR adds the `--clean` flag to the build command in order to remove the `build` and `.cache` folders.
> Add clean command to remove the .cache and build folders

- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.19.4.md
> add migration guide 19+ to 19.4

- docs/.vuepress/config.js
- docs/3.0.0-beta.x/admin-panel/custom-webpack-config.md
- packages/strapi-admin/index.js
This PR allows to modify the webpack configuration
> Allow custom webpack config

- packages/strapi-plugin-upload/admin/src/containers/HomePage/index.js
Signed-off-by: Ky <virginie.ky@gmail.com>
Fix pagination count on listview
> ML fix pagination count

- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
The dynamic validations caused the content manager to be very slow.
This PR fixes it
> Remove validations statement for input password

- packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js
Signed-off-by: Ky <virginie.ky@gmail.com>
> Fix input media delete

- packages/strapi-admin/admin/src/containers/InstalledPluginsPage/Row.js
This PR removes the link to the ML settings. It is now useless since there is a dedicated section in the settings menu
> Remove useless link in installed plugins

- examples/getstarted/api/homepage/models/homepage.settings.json
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/tests/reducer.test.js
Fix the select all in the media lib modal.
> Fix toggle all

- examples/getstarted/api/homepage/models/homepage.settings.json
- packages/strapi-plugin-upload/admin/src/components/Card/index.js
- packages/strapi-plugin-upload/admin/src/components/List/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/reducer.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/tests/reducer.test.js
Allow file deselect also if not allowed.
> Allow deselect files

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/components.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentIconPicker/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/utils/forms.js
- packages/strapi-plugin-content-type-builder/controllers/validation/common.js
- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
This PR fixes:
- #5805 
- #5771 
- #5781
> Fix front-end issues

- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.md
Feedback from user on slack to make it more clear the migration script only applies to mongoose databases
> Add note that migration script for beta.19 to beta.20 is only for Mongo

- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
This PR allows to register new field type in the content manager
> Fix register new fields in content manager

- packages/strapi-provider-upload-rackspace/lib/index.js
> Fix rackspace upload to use hash

- docs/3.0.0-beta.x/guides/registering-a-field-in-admin.md
Fix documentation typos in the "Creating a new Field in the administration panel" section.
> Fix documentation typos

- docs/3.0.0-beta.x/concepts/services.md
This close #5743 issue.
The param to upload file was not well documented in the service doc.
> Fix upload models name definition

- packages/strapi-admin/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-documentation/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-users-permissions/package.json
- yarn.lock
> Upgrade reactstrap dependency.

- docs/3.0.0-beta.x/concepts/models.md
These options are not working correctly with the current version of Strapi.
AND with the re-work of the data layer and stable version, this will be reviewed.
For these reasons, we are removing them from the documentation.
> Remove options from the model documentation

- packages/strapi-plugin-content-manager/admin/src/containers/EditView/Header.js
- yarn.lock
This PR adds the API id in the content manager's edit view.
> Add collection API ID in the content manager edit view header

- docs/3.0.0-beta.x/plugins/upload.md
Add a simple example of using env vars in provider config files
> Add a simple example of using env vars in provider config files

- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
This PR adds event in order to improve the usage of Strapi
> Add front-end media lib usage events

- docs/3.0.0-beta.x/getting-started/quick-start-tutorial.md
- docs/3.0.0-beta.x/getting-started/quick-start.md
Update tutorial files to use the Collection type instead of Content type
Updated tutorial files **`quick-start.md`** and **`quick-start-tutorial.md`** to use the Collection type instead of Content type
close #5555
> Update documentation from Content to Collection Type

- docs/3.0.0-beta.x/getting-started/contributing.md
We are currently working on the RFCs system to improve contribution from the community and the process of dialog and validation of new feature development.
To go in this way, I added a paragraph and RFC repo link into the documentation under the Contribution section.
> Add rfcs into the contribution docs

- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi/lib/services/metrics/__tests__/rate-limiter.test.js
- packages/strapi/lib/services/metrics/index.js
- packages/strapi/lib/services/metrics/rate-limiter.js
- packages/strapi/lib/services/metrics/sender.js
Add metris to the media lib with ratelimit
> Add metris to the media lib with ratelimit

- packages/strapi-plugin-users-permissions/controllers/Auth.js
> Only allow registeration with specific fields

- docs/.vuepress/config.js
Remove duplication in menu Guides.
> docs: remove duplication in menu Guides/Count with GraphQL

- packages/strapi-admin/controllers/Admin.js
- packages/strapi-plugin-users-permissions/services/User.js
- packages/strapi/lib/middlewares/router/index.js
Allow calling the update api without a password so it doesn't get updated
> Make password input optional while editing

- docs/3.0.0-beta.x/concepts/models.md
Changed from 'liked' to 'linked' of One-To-Many and Many-To-Many's description.
> Fix typographical errors in Models concept of documentation

- docs/3.0.0-beta.x/plugins/users-permissions.md
The second "Client Id" should be: "Client Secret"
> google provider section modified

- docs/3.0.0-beta.x/guides/databases.md
> Fixed link to deployment guide

- packages/strapi-plugin-users-permissions/services/Providers.js
Vk auth provider fix 
Fix https://github.com/strapi/strapi/issues/5647
> fix vk providers

- packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js
- packages/strapi-plugin-users-permissions/admin/src/translations/en.json
- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
- packages/strapi-plugin-users-permissions/services/Providers.js
Signed-off-by: David Thomas <dev@synth3.tk>
Adds Twitch as an authentication provider. Documentation from the previous attempt is still current. Succeeds PR #1616.
> Add Twitch auth provider

- docs/3.0.0-beta.x/deployment/nginx-proxy.md
This updates the Nginx proxy documentation to include the new changes to the server config + the new proxy changed merged in #5833
> Update Nginx proxy docs for new proxy changes

- docs/3.0.0-beta.x/getting-started/troubleshooting.md
based on: https://github.com/strapi/strapi/pull/6154 (applied PR feedback)
> Update FAQ for Beta Docs

- packages/strapi-plugin-users-permissions/controllers/Auth.js
- updated register handler, response will only include jwt if email confirmation is false
> in register, response will only include jwt if email confirmation is false

- docs/3.0.0-beta.x/deployment/google-app-engine.md
Based on: https://github.com/strapi/strapi/pull/6040 for beta docs
Fixes: #6106
> Update GCP host in beta docs

- README.md
Added the existing 1 click buttons in the README.md file
> Add 1 click buttons in the README.md

- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MultipleMenuList.js
This PR fixes the UI of the select components in the content type builder
> Fix ctb react-select ui

- packages/strapi/lib/core/load-policies.js
> Fix global policies case sensitive

- docs/3.0.0-beta.x/migration-guide/README.md
- docs/3.0.0-beta.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
- docs/3.0.0-beta.x/plugins/graphql.md
- docs/3.0.0-beta.x/plugins/upload.md
- packages/strapi/lib/core/load-middlewares.js
Add Migration guide for stable. Will rename the folders etc once the guide is done
> Migration guide for stable

- packages/strapi-admin/admin/src/components/StaticLinks/index.js
This PR removes the help link that is no longer up-to-date from the "blue box".
> Remove help link

- packages/strapi-admin/admin/src/components/LeftMenuHeader/Wrapper.js
Move the new header logo to the left
> Move header logo to the left

- packages/strapi-connector-mongoose/lib/relations.js
Fix https://github.com/strapi/strapi/issues/6235
> Fix mongo error trying to cast from empty array

- packages/strapi-admin/admin/src/containers/HomePage/hooks.js
This PR fixes the blog posts request
> Fixes #1766

- CONTRIBUTING.md
- README.md
- packages/strapi-admin/admin/src/components/EmptyList/index.js
- packages/strapi-admin/admin/src/containers/HomePage/index.js
- packages/strapi-generate-api/templates/controller.template
- packages/strapi-generate-api/templates/model.template
- packages/strapi-generate-api/templates/service.template
- packages/strapi-generate-model/templates/model.template
- packages/strapi-generate-new/lib/resources/files/config/functions/bootstrap.js
- packages/strapi-generate-new/lib/resources/files/config/functions/cron.js
- packages/strapi-plugin-documentation/config/settings.json
- packages/strapi-provider-upload-local/README.md
- packages/strapi/lib/services/metrics/index.js
> Fix multiple doc links to v3

- packages/strapi/lib/middlewares/language/index.js
> Fix language middleware

- packages/strapi-plugin-users-permissions/config/schema.graphql.js
Signed-off-by: ScottAgirs <scott@ijs.to>
Fixed typo in GraphQLUser-permissions-payload
> Typofix in GraphQL User permissions payload

- packages/strapi-admin/admin/src/containers/Webhooks/ListView/tests/__snapshots__/index.test.js.snap
> Fix snapshots

- packages/strapi/lib/middlewares/cron/defaults.json
- packages/strapi/lib/middlewares/cron/index.js
- packages/strapi/lib/middlewares/index.js
> Fix cron should check for server.cron.enabled option to work

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Specify only bug reports for stable, and ensure users see the link to the contributing guide for creating issues.
> Update bug report template to specify stable, and link to the contributing guide

- packages/strapi-generate-api/templates/model.template
> Fix lifecycle hooks URL

- docs/v3.x/installation/digitalocean-one-click.md
Change default service name to match the real one.
> Update digital Ocean One Click doc

- docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
> Fix typo in migration guide to stable

- docs/v3.x/getting-started/quick-start-tutorial.md
After having the feedback from Sunny (new comer in the Strapi team 🤗) I fix the link for the local installation.
> Fix link CLI installation

- README.md
Updates the README npm badge to show the latest version and not the beta
> Update README NPM badge from beta to latest

- docs/v3.x/guides/slug.md
Updated new (3.x) life cycle callbacks for slug :)
> Update slug guide match the v3 life cycle documentation

- docs/3.0.0-beta.x/concepts/configurations.md
- docs/v3.x/concepts/configurations.md
You can not check that the database is up and running in the bootstrap function, as it is executed after the database connection is initialized
> Fix bootstrap use cases

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Updated to clarify the difference between PRs made against the master and documentation branches.
> Update Contrib guide defining documentation pull requests

- docs/v3.x/guides/client.md
> docs: Fix a few typos in the 3rd party client guide

- docs/v3.x/guides/custom-data-response.md
> Typo error

- packages/strapi-plugin-users-permissions/config/functions/bootstrap.js
- packages/strapi-plugin-users-permissions/config/policies/rateLimit.js
- packages/strapi-plugin-users-permissions/controllers/Auth.js
- packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js
- packages/strapi-plugin-users-permissions/controllers/validation/__tests__/email-template.test.js
- packages/strapi-plugin-users-permissions/controllers/validation/email-template.js
> Fix some user permission issue

- docs/v3.x/admin-panel/customization.md
After testing on my own, I saw that if you change the value of admin.path from '/admin' to '/dashboard' and you re-build the app, nothing is happening. After testing and reading on the Web, I tried changing 'path' to 'url' and it worked properly.
> Modified admin.path to admin.url

- docs/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.md
After collecting some community feedback on slack, I have made a few fixes to the wording of the stable migration guide.
> Clean up the stable migration guide

- docs/v3.x/concepts/models.md
Lifecycle hook appears misspelled in documentation.
> Fixed misspelled lifecycle hook in documentation

- docs/v3.x/deployment/digitalocean.md
> Should be port 5432

- docs/v3.x/concepts/webhooks.md
> Very slight improvement of the webhook definition

- docs/3.0.0-beta.x/concepts/services.md
- docs/v3.x/concepts/services.md
> Fixed Typo on v3.x

- docs/v3.x/concepts/models.md
> Fixed misspelled word

- docs/v3.x/admin-panel/customization.md
Admin customization docs referenced the old config structure for the server config, fixed and removed some outdated docs.
> Remove outdated docs for stable admin customization

- packages/strapi-admin/package.json
- packages/strapi-helper-plugin/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-documentation/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-users-permissions/package.json
> Fixes #6775

- docs/v3.x/plugins/email.md
- docs/v3.x/plugins/upload.md
Added instructions to alias scoped providers in `package.json`
> scoped packages doc

- docs/v3.x/deployment/digitalocean.md
Thanks Jay for reporting this link issue.
> Fix 404 link in the DO deployment guide

- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
> Fix selected files for the media lib modal

- packages/strapi-admin/services/permission/engine.js
- packages/strapi-admin/services/permission/permissions-manager.js
Fix some light issues in permissions-manager & engine
> Fix some light issues in permissions-manager & engine

- packages/strapi-generate-new/lib/utils/usage.js
We added a new property in the scope to be able to distinguish users using the `--no-run` parameter in the CLI.
> Add noRun property in global scope

- docs/v3.x/guides/is-owner.md
fix grammatical error in delete action tip
fix grammatical error in delete action tip
> typo in is-owner.md

- docs/v3.x/guides/unit-testing.md
Fix a typo in Strapi instance paragraph
> fix a minor typo

- docs/v3.x/getting-started/installation.md
> Fixes: broken link to deployment page

- packages/strapi-plugin-email/documentation/1.0.0/overrides/email-Email.json
Skinny dipping in the codebase and just came across a small error.
> fix(email): malformed json

- docs/v3.x/content-api/parameters.md
> Add _where parameter OR and AND doc v1

- packages/strapi-admin/services/__tests__/action-provider.test.js
- packages/strapi-admin/services/__tests__/permissions-manager.test.js
- packages/strapi-admin/services/__tests__/permissions.engine.test.js
- packages/strapi-admin/services/permission/permissions-manager/index.js
- packages/strapi-admin/services/permission/permissions-manager/query-builers.js
- Adding coverage for strapi-admin services (especially in the /permissions folder).
- Found and fixed some bugs on query generation while testing it.
> Add tests for strapi-admin services (rbac)

- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-utils/package.json
Update the `@sindresorhus/slugify` dependency:
https://github.com/sindresorhus/slugify/releases/tag/v1.1.0
The last update allow the empty separator requested here: https://github.com/strapi/strapi/pull/5614#issuecomment-644259658
> Update slugify dependency

- packages/strapi/lib/Strapi.js
- packages/strapi/lib/commands/build.js
- packages/strapi/lib/commands/develop.js
- packages/strapi/lib/commands/watchAdmin.js
- packages/strapi/lib/core/app-configuration/index.js
Fix https://github.com/strapi/strapi/issues/7059
> Make sure dot env is loaded at the right moment

- .github/dependabot.yml
- .npmrc
Setup official GitHub Dependabot.
https://docs.github.com/en/github/administering-a-repository/about-github-dependabot-version-updates
> GitHub Dependabot takes the effort out of maintaining your dependencies. You can use it to ensure that your repository automatically keeps up with the latest releases of the packages and applications it depends on.
Then you will have a new tab `Dependabot` in the [`Insights > Dependency graph`](https://github.com/strapi/strapi/network/dependencies) here:
https://github.com/strapi/strapi/network/updates
> Setup official GitHub Dependabot

- docs/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.md
Add warning for user using extensions
> Add migration warning

- packages/strapi-admin/controllers/authentication.js
> Fix missing event

- packages/strapi-utils/lib/parse-multipart.js
I Improved the error message of file upload by adding an example. I have found it confusing the first time encountered. And I only understood by going through the source code.
> Improve error message of file upload by adding an example

- packages/strapi-plugin-users-permissions/controllers/user/api.js
I have updated api.js deleting an unnecessary console.log
> Updating api.js deleting console.log

- packages/strapi/lib/middlewares/router/index.js
- packages/strapi/lib/middlewares/router/utils/routerChecker.js
> Fix admin routes and user controllers conflicting

- packages/strapi-generate-plugin/files/admin/src/index.js
This PR fix #7162 - the plugin name was not displayed in the menu because the key was not well named.
> Fix pluginsSectionLinks in plugin generator

- docs/v3.x/getting-started/troubleshooting.md
Fixed a simple grammar issue in the documentation
> fix grammar issue

- docs/v3.x/guides/api-token.md
Upgrade api token tuto to not break rbac feature
> Upgrade api token tuto to not break rbac feature

- packages/strapi-plugin-users-permissions/services/User.js
fix regression issue due to pull #7204
Signed-off-by: Akash P <aksdevac@gmail.com>
Fixed #7252
> Fix #7252: fix relation name

- packages/strapi-admin/services/__tests__/metrics.test.js
- packages/strapi-admin/services/__tests__/role.test.js
- packages/strapi-admin/services/__tests__/user.test.js
- packages/strapi-admin/services/metrics.js
- packages/strapi-admin/services/role.js
- packages/strapi-admin/services/user.js
- packages/strapi/lib/services/metrics/__tests__/index.test.js
- packages/strapi/lib/services/metrics/sender.js
> Add events for user creation

- packages/strapi-plugin-users-permissions/admin/src/components/Roles/EmptyRole/BaselineAlignment.js
- packages/strapi-plugin-users-permissions/admin/src/components/Roles/EmptyRole/index.js
- packages/strapi-plugin-users-permissions/admin/src/components/Roles/RoleListWrapper/index.js
- packages/strapi-plugin-users-permissions/admin/src/components/Roles/RoleRow/RoleDescription.js
- packages/strapi-plugin-users-permissions/admin/src/components/Roles/RoleRow/index.js
- packages/strapi-plugin-users-permissions/admin/src/components/Roles/index.js
- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/ListPage/BaselineAlignment.js
- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/ListPage/index.js
- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/ProtectedListPage/index.js
- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/index.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/index.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/useRolesList/index.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/useRolesList/init.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/useRolesList/reducer.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/useRolesList/tests/init.test.js
- packages/strapi-plugin-users-permissions/admin/src/hooks/useRolesList/tests/reducer.test.js
- packages/strapi-plugin-users-permissions/admin/src/index.js
> Add Roles list

- docs/v3.x/guides/custom-admin.md
Related to: https://github.com/strapi/strapi/pull/7323
fixes: https://github.com/strapi/strapi/issues/7322
Thank you @diwakersurya for the original PR :)
> Fix custom admin guide typo

- docs/v3.x/concepts/middlewares.md
CORS documentation on the origin property is now more explicit for multiple domains.
Updated documentation on CORS `origin` property.
> Change CORS documentation on origin

- docs/v3.x/concepts/queries.md
Per @alexandrebodin in https://github.com/strapi/strapi/issues/6220#issuecomment-671798068
> Fix custom mongoose query .toObject() is undefined

- docs/3.0.0-beta.x/guides/send-email.md
I fixed a minor thing which is create ',' expected
> send-email.md updated.

- docs/v3.x/guides/custom-admin.md
Signed-off-by: Valerian Pereira <valerianpereira25@gmail.com>
Points added one below the other
> Points added one below the other

- docs/v3.x/getting-started/troubleshooting.md
Updated the FAQ to reflect the new RBAC feature
> Update FAQ with latest RBAC information

- docs/v3.x/plugins/users-permissions.md
Remove tips in login provider tab causing templating issues
Thank you @MattieBelt for reporting it.
> Remove tips in login provider tab causing templating issues

- docs/.vuepress/config.js
Setup docs branch to update directly the documentation branch
This update the `Improve this page` link to create a PR directly to the documentation branch.
fix #7002
> Setup docs branch to update directly the documentation branch

- docs/v3.x/admin-panel/customization.md
Improve Docs: How to change the logo of login page.
```diff
To change the top-left displayed admin panel's logo, add your custom image at `./admin/src/assets/images/logo-strapi.png`.
+ To change the login page's logo, add your custom image at `./admin/src/assets/images/logo_strapi.png`.
```
Fixes: #4241
> Add how to change login page's logo

- packages/strapi-admin/controllers/__tests__/role.test.js
- packages/strapi-admin/domain/action.js
- packages/strapi-admin/services/__tests__/action-provider.test.js
- packages/strapi-admin/services/__tests__/content-type.test.js
- packages/strapi-admin/services/__tests__/role.test.js
- packages/strapi-admin/services/content-type.js
- packages/strapi-admin/services/permission.js
- packages/strapi-admin/services/permission/action-provider.js
- packages/strapi-admin/services/role.js
- packages/strapi-admin/test/__snapshots__/admin-permission.test.e2e.js.snap
- packages/strapi-admin/test/admin-role.test.e2e.js
- packages/strapi-admin/validation/action-provider.js
- packages/strapi-admin/validation/common-validators.js
- packages/strapi-admin/validation/permission.js
- packages/strapi-plugin-content-manager/config/functions/bootstrap.js
- packages/strapi-utils/lib/validators.js
Added the "Publish" action/permissions
> Add Publish permission & action

- docs/v3.x/guides/error-catching.md
> Boom middleware needs to be loaded before sentry middleware

- docs/v3.x/guides/unit-testing.md
fixes #7494 
Added a warning that the guide won't work with Windows + SQLite
> Add warning to unit testing guide for windows/SQLite

- packages/strapi-admin/admin/src/translations/de.json
> fix German word for E-Mail

- packages/strapi-plugin-content-manager/config/routes.json
- packages/strapi-plugin-content-manager/controllers/ContentManager.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/services/__tests__/content-manager.test.js
- packages/strapi-plugin-content-manager/test/index.test.e2e.js
Add the ability to unpublish an entry if it's already published, throws otherwise.
> [D&P] Unpublish an entry

- packages/strapi-admin/admin/src/containers/HomePage/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/CreatableSelect/index.js
This PR fixes some small issues in order to clean up the GitHub repo a bit.
- Fixes #7523 
- Fixes #7503
> Fix front-end small issues

- docs/3.0.0-beta.x/guides/count-graphql.md
- docs/v3.x/guides/count-graphql.md
Signed-off-by: Valerian Pereira <valerianpereira25@gmail.com>
GraphQL typos in naming the file. Fixed the same.
> GraphQL Typos fixed to improve documentation

- docs/v3.x/concepts/webhooks.md
- packages/strapi-admin/controllers/Webhooks.js
- packages/strapi-admin/test/admin-role.test.e2e.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/services/__tests__/content-manager.test.js
- packages/strapi-plugin-upload/controllers/upload/admin.js
- packages/strapi-plugin-upload/services/Upload.js
- packages/strapi-utils/lib/index.js
- packages/strapi-utils/lib/webhook.js
- packages/strapi/lib/services/__tests__/entity-service.test.js
- packages/strapi/lib/services/entity-service.js
- Triggers webhooks when publishing/unpublishing
- sanitize the webhooks contents (breaking change)
- fix wrong creator fields in media webhooks
> add webhooks for draftAndPublish + sanitize all webhooks info

- examples/getstarted/api/address/models/Address.settings.json
- examples/getstarted/api/category/models/Category.settings.json
- examples/getstarted/api/like/models/Like.settings.json
- packages/strapi-plugin-content-manager/admin/src/components/DragLayer/index.js
- packages/strapi-plugin-content-manager/admin/src/components/RelationDPState/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/components.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/SingleValue.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/ClearIndicator.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/DropdownIndicator.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/IndicatorSeparator.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/Option.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/components.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/utils/styles.js
- packages/strapi-plugin-content-manager/admin/src/translations/en.json
This PR adds a visual info about the state of the relation that is being made (published or draft).
> Display relationship D&P state in relation dropdown

- docs/v3.x/concepts/configurations.md
(Example provided by Matthew on Slack, thank you)
Added an example for client side SSL verification, loading in the SSL CA and converting to string to pass off to Knex
> Add example for PG SSL CA verification

- packages/strapi-plugin-users-permissions/controllers/Auth.js
- Fix a comment (solves: https://github.com/strapi/strapi/issues/7481)
> Fixed comment

- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/getFieldsActionMatchingPermissions.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/tests/getFieldsActionMatchingPermissions.test.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/tests/testData.js
> Fixes #7232

- docs/v3.x/deployment/heroku.md
Automatically deconstructs the Heroku environment variable for PostgreSQL `DATABASE_URL` in the `./config/database.js` file so that when Heroku updates it, you don't need to manually change the environment variables.
> Heroku PG DB env variable deconstruction automatically

- packages/strapi-connector-bookshelf/lib/build-database-schema.js
- packages/strapi-connector-bookshelf/lib/database-migration.js
- packages/strapi-connector-bookshelf/lib/index.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-bookshelf/lib/utils/store-definition.js
- packages/strapi-connector-mongoose/lib/database-migration.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/utils/store-definition.js
- packages/strapi-database/test/migration-draft-publish.test.e2e.js
- packages/strapi-plugin-content-manager/test/content-type-api.test.e2e.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
- test/helpers/models.js
off -> on
- for each entry: add column `published_at` with same value as `created_at` if the column exists, `new Date().toISOString()` otherwise
on -> off
- delete all drafts
- remove column `published_at`
> Draft publish/migration

- packages/strapi-plugin-upload/test/graphqlUpload.test.e2e.js
> Cleanup upload tests

- docs/v3.x/getting-started/quick-start.md
- docs/v3.x/guides/auth-request.md
- docs/v3.x/plugins/users-permissions.md
This PR is related to the design update of the Roles & Permission delocalization in the Settings section.
Because this PR is related to the next release - the PR is made on the `master` branch.
⚠️ This PR is WIP, should be merged JUST before the release even if it's still in WIP.
WIP here means that we can add some updates on that branch before the release.
> Update Roles & Permissions left menu mentions

- packages/strapi-plugin-content-manager/test/content-type-api.test.e2e.js
- packages/strapi-plugin-content-manager/test/relation-list.test.e2e.js
- packages/strapi/__tests__/api.test.e2e.js
- test/jest2e2.setup.js
###Description of what you did:
Only added tests as the feature was already added
> Draft publish/knowing relationships are drafts

- packages/strapi-admin/admin/src/containers/Users/ProtectedEditPage/index.js
- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/Option.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/utils/select.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationFormBox/Wrapper.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationFormNaturePicker/Wrapper.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationFormNaturePicker/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationTargetPicker/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/cleanData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/tests/cleanData.test.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/tests/expectedFormattedData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/tests/rawData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/reducer.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/tests/reducer.test.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/index.js
This PR allows to create relations with the admin users.
> Allow relations with the admin panel users

- docs/v3.x/content-api/parameters.md
> Parameters docs typo

- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/EditPage/index.js
This PR fixes the display of the role's permission.
> Fix role edition

- docs/v3.x/content-api/parameters.md
- packages/strapi-connector-bookshelf/lib/buildQuery.js
- packages/strapi-connector-bookshelf/lib/database-migration.js
- packages/strapi-connector-bookshelf/lib/populate.js
- packages/strapi-connector-bookshelf/lib/queries.js
- packages/strapi-connector-bookshelf/lib/utils/populate-queries.js
- packages/strapi-connector-mongoose/lib/buildQuery.js
- packages/strapi-connector-mongoose/lib/database-migration.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/queries.js
- packages/strapi-connector-mongoose/lib/utils/populate-queries.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/services/__tests__/content-manager.test.js
- packages/strapi-utils/lib/__tests__/convert-rest-query-params.test.js
- packages/strapi-utils/lib/content-types.js
- packages/strapi-utils/lib/convert-rest-query-params.js
- packages/strapi/__tests__/filtering.test.e2e.js
- packages/strapi/__tests__/publication-state.test.e2e.js
- packages/strapi/lib/core-api/service.js
- packages/strapi/lib/services/entity-validator/index.js
- test/helpers/models.js
- Add _publicationState query param.
- Handle live & preview contents from public GET APIs
- Returns live version by default
> [D&P] Return published content by default from get apis

- docs/v3.x/getting-started/contributing.md
> Typo in contributing.md

- docs/v3.x/installation/cli.md
From https://github.com/strapi/strapi/discussions/7805#discussioncomment-75329 I forgot to update the installation docs on the CLI page for https://github.com/strapi/strapi/pull/7409
> Fix missing note about Node v12 in cli docs

- docs/v3.x/getting-started/quick-start.md
> Remove outdated reference in getting started guide

- docs/v3.x/concepts/routing.md
Removes bad example that uses an array of strings for method which is not supported.
fixes #7961
> Remove bad example with array for method

- packages/strapi-helper-plugin/lib/src/components/LeftMenuLink/index.js
- packages/strapi-helper-plugin/lib/src/components/LeftMenuList/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationTargetPicker/Item.js
- packages/strapi-plugin-content-type-builder/admin/src/components/RelationTargetPicker/index.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/cleanData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/tests/expectedFormattedData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/utils/tests/rawData.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/reducer.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/tests/reducer.test.js
- packages/strapi-plugin-content-type-builder/admin/src/containers/LeftMenu/index.js
- packages/strapi-plugin-content-type-builder/services/ContentTypes.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/index.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/schema-handler.js
Add the from info when making a relation with a plugin model
> Add the from info for relations

- packages/strapi-connector-bookshelf/lib/build-database-schema.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
Fix wrong created_at date format
> fix missing hasTimestamp

- packages/strapi-admin/admin/src/containers/AuthPage/index.js
> Fix analytics registration bad info

- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js
This PR fixes the wrong redirection in the content type builder
> Fixes #8040

- packages/strapi-admin/admin/src/components/Roles/Permissions/PluginsAndSettingsPermissions/PermissionRow/SubCategory/SubCategoryWrapper.js
- packages/strapi-plugin-content-manager/admin/src/components/State/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/InformationCard.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/components.js
- packages/strapi-plugin-users-permissions/admin/src/components/Permissions/PermissionRow/SubCategory/SubCategoryWrapper.js
> Small ui improvements

- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepper/InputModalStepper.js
- packages/strapi-plugin-upload/admin/src/containers/InputModalStepperProvider/index.js
- packages/strapi-plugin-upload/admin/src/containers/ModalStepper/index.js
This PR adds better error message for 413 responses
> Add better error message for 413 errors in ML

- docs/.vuepress/config.js
Added a header link to the forums in the documentation
> Add forum to header links on docs

- .github/ISSUE_TEMPLATE/config.yml
Changed the link from GHD to Forum
> Move questions link to forums

- docs/v3.x/global-strapi/api-reference.md
"... you can access to every ..." -> "... you can access every ..:"
> Fix grammar

- packages/strapi-admin/admin/src/components/Roles/Permissions/index.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/init.js
- packages/strapi-admin/ee/admin/components/Roles/Permissions/init.js
- packages/strapi-helper-plugin/lib/src/components/PopUpWarning/tests/__snapshots__/index.test.js.snap
Hide publish action for the author's role + Update snapshot
> Fix author role for the publish permission action

- docs/v3.x/plugins/graphql.md
> Add docs for sorting graphql queries

- docs/v3.x/admin-panel/customization.md
Documentation > Admin Panel > Customization > Development mode > Styles 
https://strapi.io/documentation/v3.x/admin-panel/customization.html#styles
```
./node_modules/strapi-admin/admin/src/components/LeftMenuHeader
↓
./node_modules/strapi-admin/admin/src/components/LeftMenu/LeftMenuHeader
```
```
./admin/src/components/LeftMenuHeader/Wrapper.js
↓
./admin/src/components/LeftMenu/LeftMenuHeader/Wrapper.js
```
> LeftMenuHeader Path FIX

- docs/v3.x/plugins/graphql.md
One road bump I hit to trying out strapi is that no requests work out of the box with Graphql because of the authorization. And there aren't any docs showing how to do this.
>  Provide docs on how to use the auth with graphql

- packages/strapi-helper-plugin/lib/src/components/PopUpWarning/tests/__snapshots__/index.test.js.snap
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/DeleteLink/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/DeleteLink/utils/select.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
This PR adds events regarding the D&P feature
> Add events regarding the D&P feature

- packages/strapi-admin/admin/src/components/Roles/Permissions/reducer.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/tests/reducer.test.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/utils/generateContentTypeActions.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/generateContentTypeActions.test.js
> Replace static permissions by layout and update tests

- packages/strapi-admin/services/content-type.js
- packages/strapi-connector-bookshelf/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-plugin-content-manager/services/ContentManager.js
- packages/strapi-plugin-content-manager/test/search.test.e2e.js
- packages/strapi-utils/lib/__tests__/content-types.test.js
- packages/strapi-utils/lib/content-types.js
- packages/strapi/__tests__/api/basic-dp.test.e2e.js
- packages/strapi/lib/core-api/service.js
Allow setting the published_at field in the API
> Allow setting the published_at field in the API

- packages/strapi-connector-bookshelf/lib/populate.js
- packages/strapi-connector-bookshelf/lib/utils/populate-queries.js
- packages/strapi-plugin-graphql/services/type-definitions.js
> Fix publicationState for nested populations

- docs/v3.x/migration-guide/README.md
- docs/v3.x/migration-guide/migration-guide-3.1.x-to-3.2.x.md
> Add 3.2 migration guide and improve migration guides homepage

- packages/strapi-admin/admin/src/components/Roles/ConditionsSelect/MenuList/Ul.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MenuList.js
- packages/strapi-plugin-content-type-builder/admin/src/components/SelectMenuUl/index.js
This PR
- fixes #8175 
- fixes #8219
> Fixes UI glitch

- README.md
Update Platform.sh button image URL
> Update Platform.sh button image URL

- docs/v3.x/concepts/models.md
Added the `autoPopulate` to the docs, with a note that it doesn't prevent GraphQL from populating the data.
> Add autoPopulate to model docs

- docs/v3.x/guides/draft.md
- docs/v3.x/guides/scheduled-publication.md
Everything is in the title and files I updated.
fixes: #8268
> Update the draft and schedule guides

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/PULL_REQUEST_TEMPLATE.md
Fixed syntax of markdown templates, as well as expanded information for creating ISSUE / PR
> Update issues/PR templates

- docs/v3.x/admin-panel/customization.md
> Add STRAPI_UPDATE_NOTIF in config doc.

- docs/v3.x/guides/update-version.md
Remove the hook packages from the examples
Packages don't exist/aren't maintained anymore
fixes: #8421
> Fix bad package in the update version guide

- docs/v3.x/concepts/controllers.md
- docs/v3.x/concepts/routing.md
Update the docs to make the config option in the routing more clear
Example that bypasses users-permissions plugin
fixes: #8438
> Add policies information to routing and link controllers to routing docs

- .github/PULL_REQUEST_TEMPLATE.md
Fix a 404 in this very pull request template
Link is broken
discovered this in #8459
> docs: fix 404 in PR template

- docs/v3.x/guides/update-version.md
Improved formatting to clarify necessary step to actually update the installed Strapi version.
The necessary step to actually update the installed Strapi version, wasn't recognized as required.
none
> Clarifies the necessary step to actually install the new version

- docs/v3.x/guides/update-version.md
- docs/v3.x/migration-guide/README.md
Update the _Update Strapi version_ guide. 
The guide was a bit outdated/unclear.
> Update the update-version guide

- docs/v3.x/deployment/amazon-aws.md
Updated the steps to configure the aws-s3 upload provider, because someone [on Slack](https://strapi.slack.com/archives/C0BNGCDNH/p1601998500006700) could not find the settings tab. 
**NOTE**: I could not test it (I have no AWS instance), but this should be the right way to configure the upload provider.
> Updated amazon AWS deployment docs

- docs/v3.x/getting-started/deployment.md
- docs/v3.x/installation/cli.md
> Remove references to node v14 not being supported

- docs/v3.x/getting-started/quick-start.md
Added step about publishing content before accessing it from client.
Per discussion on forum:
https://forum.strapi.io/t/getting-started-does-not-mention-how-to-publish-draft-collection-types/768/4
n/a
> Added step to getting started topic per forum discussion.

- docs/v3.x/concepts/templates.md
> Fix typo in templates docs

- docs/v3.x/migration-guide/migration-guide-3.2.5-to-3.3.0.md
- docs/v3.x/plugin-development/frontend-development.md
Update the strapi.notification documentation
> Update new notification api doc

- docs/v3.x/guides/update-version.md
- Add note about new notifications when new Strapi version is available
- Add information about new Settings > Application section in Admin panel
- Put important existing piece of information in Caution note to avoid being hidden by new note
> Documentation: update notifications + "Application" section in admin panel

- packages/strapi/lib/utils/update-notifier/index.js
> Fix write access error of the update-notifier

- packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/reducer.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/utils/tests/data.js
- packages/strapi-admin/admin/src/containers/Webhooks/EditView/index.js
- packages/strapi-admin/admin/src/utils/getAttributesToDisplay.js
- packages/strapi-admin/admin/src/utils/tests/getAttributesToDisplay.test.js
- packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
This PR updates the views according to the new API format
> Migrate RBAC views to new API format

- packages/strapi-plugin-content-manager/admin/src/components/ComponentInitializer/index.js
- Fixed the onClick event of a non-repeatable component on its empty state.
- Made the whole area clickable
Admin panel better user experience
#8640 #8608 - one part
> Fixed click event on non-repeatable empty component

- docs/v3.x/plugins/upload.md
Make the parser middleware config example a bit more clear
It was not clear how to properly configure the middleware
#8620
> Make upload parser middleware example more clear

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/styledComponents.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeRecursivePath/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
- packages/strapi-plugin-content-manager/admin/src/testUtils/data.js
- packages/strapi-plugin-content-manager/admin/src/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/utils/removeFieldsFromClonedData.js
- packages/strapi-plugin-content-manager/admin/src/utils/tests/removeFieldsFromClonedData.test.js
Applied PR feedback for  #8563
> MeXaaR feature/duplicate document

- docs/v3.x/concepts/queries.md
Improves the docs and the examples. Adds a suggestion on how to return a more usable response to the frontend
The examples had room from improvements
> Improved raw SQL queries example

- docs/v3.x/getting-started/troubleshooting.md
Updates the FAQ to clarify some information
N/A
N/A
> Update docs FAQ with component filtering

- packages/strapi-plugin-content-manager/admin/src/components/DraggedFieldWithPreview/DynamicComponent.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeFormWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeFormWrapper/index.js
> Fix small bugs related to RF migration

- packages/strapi-admin/index.js
> Fixes hot reload

- docs/3.0.0-beta.x/guides/count-graphql.md
- docs/v3.x/guides/count-graphql.md
Signed-off-by: Valerian Pereira <valerianpereira25@gmail.com>
Document update to hold the correct spelling - restaurant
> Restaurant spelled right

- docs/v3.x/plugins/users-permissions.md
Remove files that no longer need to be changed
No longer need to be changed
> Remove files that no longer need to be changed

- docs/v3.x/concepts/templates.md
Clarifies some of the steps for creating a template.
Without the changes, I found some of the steps ambiguous.
None
> Clarify some of the template creation steps

- README.md
Add Academy link to the README
To help people find the link to the academy on our Github
> Add academy link to the README

- docs/v3.x/concepts/models.md
Adds missing relationship type to model documentation
Was missing
N/A
> Add manyWay relation example

- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeFormWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeRecursivePath/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeRecursivePath/index.js
This PR fixes the cleanup phase of the useEffect hook in the CollectionFormWrapper.
> Fix cleanup effect

- packages/strapi-plugin-content-manager/controllers/collection-types.js
> Use correct mainField

- packages/strapi-plugin-content-manager/admin/src/components/RelationPreviewList/RelationPreviewTooltip.js
> Fix updatePosition uncaught error

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row/Cell.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row/index.js
- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js
- packages/strapi-plugin-content-manager/admin/src/components/RelationPreviewList/RelationPreviewTooltip.js
- packages/strapi-plugin-content-manager/admin/src/components/RelationPreviewList/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/SingleValue.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/Option.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeRecursivePath/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/Filter.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/reducer.js
- packages/strapi-plugin-content-manager/admin/src/hooks/useFetchContentTypeLayout/utils/formatLayouts.js
- packages/strapi-plugin-content-manager/admin/src/hooks/useFetchContentTypeLayout/utils/tests/formatLayouts.test.js
- packages/strapi-plugin-content-manager/admin/src/utils/formatLayoutToApi.js
- packages/strapi-plugin-content-manager/admin/src/utils/getDisplayedValue.js
- packages/strapi-plugin-content-manager/admin/src/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/utils/tests/formatLayoutToApi.test.js
This PR adds the needed main field info in the CM metadatas
In order to simplify the code and be able to use the same utils in the entire CM.
> CM Fix layout shape

- packages/strapi-plugin-users-permissions/services/Providers.js
I removed a unnecessary variable and removed a comment that was not even needed there!
It was not really needed, but I found this and decided to do a pull-request on it.
> Small changes to 'cognito' case!

- packages/strapi-admin/admin/src/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
- packages/strapi-admin/admin/src/containers/LocaleToggle/Wrapper.js
- packages/strapi-admin/admin/src/containers/SettingsPage/components/MenuWrapper/index.js
- packages/strapi-admin/admin/src/containers/SettingsPage/components/StyledLeftMenu/index.js
- packages/strapi-admin/ee/admin/components/Roles/Permissions/ContentTypes/ContentTypesRow/index.js
- packages/strapi-plugin-content-manager/admin/src/components/InputUID/RightContentLabel.js
- packages/strapi-plugin-content-manager/admin/src/components/InputUID/RightLabel.js
- packages/strapi-plugin-content-manager/admin/src/components/InputUID/index.js
- packages/strapi-plugin-content-manager/admin/src/components/RelationPreviewList/index.js
> Fix UI bugs RF and CM

- packages/strapi-admin/admin/src/containers/Admin/actions.js
- packages/strapi-admin/admin/src/containers/Admin/index.js
- packages/strapi-admin/admin/src/containers/Admin/reducer.js
- packages/strapi-admin/admin/src/containers/Admin/tests/reducer.test.js
- packages/strapi-admin/admin/src/containers/ApplicationInfosPage/index.js
- packages/strapi-admin/admin/src/containers/LeftMenu/index.js
- packages/strapi-admin/admin/src/containers/SettingsPage/components/ApplicationDetailLink/index.js
- packages/strapi-admin/admin/src/utils/checkLatestStrapiVersion.js
- packages/strapi-admin/admin/src/utils/index.js
- packages/strapi-admin/admin/src/utils/tests/checkLatestStrapiVersion.test.js
- packages/strapi-admin/package.json
Check the latest version of Strapi with Semver to not display the update notification on beta versions.
> Check Strapi versions with Semver

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Headers/Header.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
Add property to filter and sort events.
> RF Telemetry

- packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
The PR fixes the value display of the wysiwyg for the following case: editing an entry and the wysiwyg is the first input of the layout.
> Fix wysiwyg lifecycle

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/Row/Cell.js
- packages/strapi-plugin-content-manager/admin/src/components/FilterPicker/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/Filter.js
Fixes #8951. 
This PR also makes sures we fetch the first page when we are applying/removing filters.
> Fix listview bug

- packages/strapi-connector-mongoose/lib/buildQuery.js
fix: https://github.com/strapi/strapi/issues/5608#issuecomment-754218298
> Fix deep query sort when using pagination operators (start, limit) & MongoDB

- packages/strapi-plugin-upload/admin/src/components/Card/index.js
- packages/strapi-plugin-upload/admin/src/components/CardControl/index.js
- packages/strapi-plugin-upload/admin/src/components/List/index.js
- packages/strapi-plugin-upload/admin/src/components/UploadList/RowItem.js
> Add tooltip on strapi-upload-plugin

- README.md
Updated the README.md file to include a section about trying the Foodadvisor demo
> Update README to include a section for the live demo

- packages/strapi-connector-bookshelf/lib/queries.js
- packages/strapi-connector-mongoose/lib/queries.js
> Fix CM limited to show only 100 entries

- packages/strapi-plugin-content-manager/admin/src/components/Search/index.js
This PR forces the search to be made on page 1 instead of the current one.
> Fix search

- packages/strapi-provider-upload-cloudinary/lib/index.js
> Fix file extensions not always detected with cloudinary

- packages/strapi-admin/package.json
- packages/strapi-plugin-upload/package.json
- yarn.lock
> Bump immer version

- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/admin/src/configureStore.js
- packages/strapi-admin/admin/src/utils/MiddlewareApi.js
- packages/strapi-admin/admin/src/utils/Strapi.js
This PR adds the middleware api, in order for a plugin to override another plugin redux action.
> Middleware API

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-content-manager/config/routes.json
- packages/strapi-plugin-content-manager/controllers/__tests__/relations.test.js
- packages/strapi-plugin-content-manager/controllers/relations.js
- packages/strapi-plugin-content-manager/oas.yml
- packages/strapi-plugin-content-manager/tests/relation-list.test.e2e.js
> Fix relation search

- packages/strapi-admin/services/__tests__/permissions-manager.test.js
- packages/strapi-admin/services/permission/permissions-manager/index.js
- packages/strapi-plugin-content-manager/controllers/collection-types.js
- packages/strapi-plugin-content-manager/services/permission-checker.js
Fix conditions not use to buildfind queries in CM.
Fix https://github.com/strapi/strapi/issues/9187
> Fix is-creator condition not applied on find

- packages/strapi-plugin-i18n/config/functions/__tests__/bootstrap.test.js
- packages/strapi-plugin-i18n/config/functions/bootstrap.js
- packages/strapi-plugin-i18n/package.json
> Add locale crud permissions

- packages/strapi-plugin-upload/admin/src/components/InputMedia/EmptyInputMedia.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/IconUpload.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/index.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/tests/EmptyInputMedia.test.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
- packages/strapi-plugin-upload/admin/src/translations/fr.json
- test/config/front/strapi.js
The idea is change the style of the droppable area when dragging something hover it
Improve the UX for the DnD when overring the droppable area.
> [ContentManager] Improving Drag&Drop experience

- packages/strapi-plugin-i18n/admin/src/components/LocaleRow/index.js
- packages/strapi-plugin-i18n/admin/src/components/index.js
- packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/index.js
- packages/strapi-plugin-i18n/admin/src/hooks/index.js
- packages/strapi-plugin-i18n/admin/src/hooks/useLocales/index.js
- packages/strapi-plugin-i18n/admin/src/hooks/useLocales/reducer.js
- packages/strapi-plugin-i18n/admin/src/hooks/useLocales/tests/reducer.test.js
- packages/strapi-plugin-i18n/admin/src/index.js
- packages/strapi-plugin-i18n/admin/src/translations/en.json
- packages/strapi-plugin-i18n/admin/src/translations/fr.json
- packages/strapi-plugin-i18n/admin/src/utils/getTrad.js
- packages/strapi-plugin-i18n/admin/src/utils/index.js
Display the list of locales in the settings for the i18n plugin
> Fake locales list

- packages/strapi-admin/ee/admin/containers/AuthPage/components/Login/index.js
- packages/strapi-admin/ee/admin/containers/AuthPage/components/Providers/index.js
- packages/strapi-admin/ee/admin/hooks/useAuthProviders/index.js
Fix login use auth providers hook when sso disabled
> Fix login providers hook

- packages/strapi-admin/index.js
This PR disables the dotRule in the watchAdmin config.
> Improve front end development

- packages/strapi-admin/ee/admin/components/ProviderButton/index.js
Changes the css of the `<ProviderButton>` component.
> Fix sso login button UI

- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
> Fix idsToOmit

- packages/strapi-admin/admin/src/components/Roles/ConditionsSelect/MenuList/index.js
- packages/strapi-admin/ee/admin/components/Roles/ConditionsSelect/MenuList/index.js
- packages/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect/MultipleMenuList.js
It automatically open the first section of a `<MultipleMenuList />` component
To reduce the number of mouse click.
> Open the first section of <MultipleMenuList /> component by default

- packages/strapi-plugin-i18n/admin/src/components/LocaleList/index.js
- packages/strapi-plugin-i18n/admin/src/components/LocaleRow/index.js
- packages/strapi-plugin-i18n/admin/src/components/ModalEdit/index.js
- packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/LocaleSettingsPage.js
- packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js
- packages/strapi-plugin-i18n/admin/src/hooks/useEditLocale/index.js
- packages/strapi-plugin-i18n/admin/src/hooks/useLocales/index.js
- packages/strapi-plugin-i18n/admin/src/translations/en.json
- Provides the logic for editing a locale
- Add the tests to cover the management rules
- TODO (another PR?): make the UI
> [I18N] edit locale modal

- packages/strapi-admin/admin/src/containers/Admin/Wrapper.js
- packages/strapi-plugin-users-permissions/admin/src/components/Policies/Components.js
- packages/strapi-plugin-users-permissions/admin/src/components/Policies/index.js
It makes policies component in  `Edit Role` page sticky.
https://user-images.githubusercontent.com/53975050/107182587-9d3ce700-6a0f-11eb-90f0-1c8321b179b6.mp4
> UI - Make policies components sticky

- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/Permissions/README.md
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/Permissions/tests/reducer.test.js
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/Permissions/utils/tests/updateValues.test.js
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/Permissions/utils/updateValues.js
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/utils/tests/createArrayOfValues.test.js
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/utils/tests/getCheckboxState.test.js
This PR adds technical documentation on how the `<Permissions />` components works
> Add documentation

- packages/strapi-connector-bookshelf/lib/knex.js
Fix pool config knex not allow overwrites
Ref https://github.com/strapi/strapi/pull/9155#issuecomment-779473486
> Fix pool config

- packages/strapi-admin/admin/src/containers/App/index.js
- packages/strapi-admin/admin/src/containers/AuthPage/index.js
Fix the redirection bug when you log out right after the first admin registration.
> Fix first admin logout bug

- packages/strapi-plugin-sentry/README.md
> Add install instructions to strapi-plugin-sentry docs

- packages/strapi-utils/lib/sanitize-entity.js
Fix https://github.com/strapi/strapi/issues/9438
> Fix sanitize polymorphic entities that can be undefined or ids only

- packages/strapi-admin/admin/src/containers/ApplicationInfosPage/index.js
- packages/strapi-plugin-upload/admin/src/containers/SettingsPage/index.js
- packages/strapi-plugin-upload/admin/src/translations/en.json
- packages/strapi-plugin-users-permissions/admin/src/containers/Roles/ListPage/index.js
- packages/strapi-plugin-users-permissions/admin/src/translations/en.json
Adding missing titles on pages
- Go to /admin/settings/application-infos and see "Settings - Application" in title
- Go to /admin/settings/media-library and see "Settings - Media Library" in the title
- Go to /admin/settings/users-permissions/roles and see  "Settings - Roles" in the title
- Go to /admin/settings/users-permissions/email-templates and see "Settings - Email Templates" in the title
https://github.com/strapi/strapi/issues/9359
> Fixing page titles

- packages/strapi-admin/admin/src/components/Roles/ContentTypeCollapse/utils/activeStyle.js
- packages/strapi-admin/admin/src/components/Roles/Permissions/index.js
- packages/strapi-admin/admin/src/config.js
- packages/strapi-admin/admin/src/containers/Roles/EditPage/index.js
- packages/strapi-admin/admin/src/translations/index.js
- packages/strapi-admin/ee/admin/containers/Roles/CreatePage/index.js
This PR adds the telemetry back.
> Add telemetry back

- packages/strapi/lib/commands/watchAdmin.js
This PR fixes the admin development mode.
Fixes #9468
> Fix watch-admin in EE mode

- packages/strapi-helper-plugin/lib/src/components/Select/index.js
- packages/strapi-plugin-i18n/admin/src/components/ModalCreate/AdvancedForm.js
- packages/strapi-plugin-i18n/admin/src/components/ModalCreate/BaseForm.js
- packages/strapi-plugin-i18n/admin/src/components/ModalCreate/index.js
- packages/strapi-plugin-i18n/admin/src/components/ModalEdit/BaseForm.js
- packages/strapi-plugin-i18n/admin/src/components/ModalEdit/index.js
- packages/strapi-plugin-i18n/admin/src/components/SettingsModal.js
- packages/strapi-plugin-i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js
- packages/strapi-plugin-i18n/admin/src/translations/en.json
Fixes the baseline alignements and styles for the edit and add locale in settings
> Fix baseline alignements for I18N modales

- packages/strapi-admin/admin/src/validations/users/profile.js
- packages/strapi-admin/package.json
Hello @soupette, 
**Issue** >> https://github.com/strapi/strapi/issues/6475
With ref to your following comment https://github.com/strapi/strapi/pull/9496#issuecomment-785663843
I updated the Profile Schema. Can you please check and confirm. Also please let me know if any modifications/changes are required
> Issue: Domain name validation c Fixed. With Ref to Previous PR #9496

- packages/strapi-plugin-content-manager/admin/src/components/AddDropdown/components.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListSettingsView/MenuDropdown.js
Remove the duplicated `&:hover` to fix the linter
> Fix the front linter

- packages/strapi-admin/admin/src/validations/users/profile.js
- packages/strapi-admin/package.json
- yarn.lock
Reverts strapi/strapi#9521
I am reverting this PR as it is not a wanted behaviour. Such behaviour should be added in the lifecycle hooks.
Fixes #9554
> Revert "Issue: Domain name validation c Fixed. With Ref to Previous PR #9496"

- packages/strapi-plugin-content-type-builder/admin/src/containers/DataManagerProvider/index.js
> Enable the content type builder in other environments than development

- packages/strapi-plugin-i18n/admin/src/components/LocaleRow/index.js
Fixing font-weight on i18n locale list
> Fixing font-weight on i18n list

- packages/strapi-plugin-i18n/admin/src/components/ModalCreate/AdvancedForm.js
- packages/strapi-plugin-i18n/admin/src/components/ModalEdit/AdvancedForm.js
> Fix description size in i18n modales

- packages/strapi-plugin-i18n/admin/src/components/LocaleRow/index.js
Fix icon positioning in I18N locale list
> Fix icon alignment in i18n settings

- CONTRIBUTING.md
- README.md
- packages/strapi-admin/admin/src/app.js
- packages/strapi-admin/admin/src/components/Webhooks/EmptyList/index.js
- packages/strapi-generate-api/templates/controller.template
- packages/strapi-generate-api/templates/model.template
- packages/strapi-generate-api/templates/service.template
- packages/strapi-generate-new/lib/resources/files/config/functions/bootstrap.js
- packages/strapi-generate-new/lib/resources/files/config/functions/cron.js
- packages/strapi-plugin-documentation/config/settings.json
- packages/strapi-plugin-documentation/services/Documentation.js
- packages/strapi-plugin-email/admin/src/containers/Settings/index.js
- packages/strapi-plugin-email/controllers/Email.js
- packages/strapi-plugin-graphql/README.md
- packages/strapi-plugin-users-permissions/admin/src/containers/EmailTemplates/CustomTextInput.js
- packages/strapi-plugin-users-permissions/admin/src/containers/EmailTemplates/utils/forms.js
- packages/strapi-plugin-users-permissions/controllers/Auth.js
- packages/strapi-plugin-users-permissions/documentation/1.0.0/overrides/users-permissions-User.json
- packages/strapi-provider-upload-aws-s3/README.md
- packages/strapi-provider-upload-cloudinary/README.md
- packages/strapi-provider-upload-local/README.md
- packages/strapi-provider-upload-rackspace/README.md
- packages/strapi-utils/lib/convert-rest-query-params.js
- packages/strapi/lib/services/metrics/index.js
Updates documentation links to fit the new docs structure
Doc structure has changed and we aren't handling redirects
N/A
N/A
> Update all documentation links in the code-base and readmes

- examples/getstarted/api/restaurant/models/Restaurant.settings.json
- packages/strapi-connector-bookshelf/lib/populate.js
- packages/strapi-connector-bookshelf/lib/utils/populate-queries.js
- packages/strapi-connector-mongoose/lib/mount-models.js
- packages/strapi-connector-mongoose/lib/queries.js
- packages/strapi-plugin-i18n/config/functions/bootstrap.js
- packages/strapi-plugin-i18n/config/functions/register.js
- packages/strapi-utils/lib/models.js
Move `localizations` to many way & add populate option on assoc
> Move to many way & add populate option on assoc

- packages/strapi-plugin-i18n/config/functions/__tests__/bootstrap.test.js
- packages/strapi-plugin-i18n/config/functions/bootstrap.js
- packages/strapi-plugin-i18n/services/__tests__/localizations.test.js
- packages/strapi-plugin-i18n/services/entity-service-decorator.js
- packages/strapi-plugin-i18n/services/localizations.js
- packages/strapi/lib/services/__tests__/entity-service.test.js
- packages/strapi/lib/services/entity-service.js
>
> Must be merged after https://github.com/strapi/strapi/pull/9621
>
> Implement entity service decoration & move lifecycles to entity service

- packages/create-strapi-starter/create-strapi-starter.js
- packages/create-strapi-starter/package.json
- packages/create-strapi-starter/utils/build-starter.js
- packages/create-strapi-starter/utils/child-process.js
- packages/create-strapi-starter/utils/fetch-github.js
- packages/create-strapi-starter/utils/logger.js
- packages/create-strapi-starter/utils/stop-process.js
- yarn.lock
Provides clear formatted error messages
Create CLI errors by:
- providing only 1 or more than 2 arguments
- providing only 1 or more than 2 arguments + an option
- providing an argument with an invalid option
Otherwise 
- pass an invalid github url or shortcut
- starter without starter.json
> [Starter CLI] error handling

- .github/workflows/tests.yml
Fix issue with failing tests for dependabot following github policy change 
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions
> Fix dependabot not allowed to use secrets

- packages/strapi-plugin-content-manager/admin/src/containers/EditViewLayoutManager/actions.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewLayoutManager/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
- packages/strapi-plugin-content-manager/admin/src/hooks/useContentTypeLayout/index.js
- packages/strapi-plugin-i18n/admin/src/middlewares/extendCMEditViewLayoutMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCMEditViewLayoutMiddleware.test.js
This PR improves the layout middleware in order to add filters to the GET relations.
In order to add parameters to the GET relations endpoint
In one terminal window clone the monorepo checkout the branch corresponding to #9535 PR's branch && start the getstarted app.
In another terminal checkout the `i18n/add-filters-to-relations` branch and start the webpack devServer
> Waiting for #9688 to be merged
> [I18n] CM Add filters to relations

- packages/strapi-plugin-i18n/services/entity-service-decorator.js
- packages/strapi/lib/services/entity-service.js
Handle "all" usecase & pass action to be able to disable the overwritten when necessary
> Handle more usecase for the _locale query param

- packages/strapi-plugin-content-manager/config/routes.json
- packages/strapi-plugin-content-manager/controllers/__tests__/content-types.test.js
- packages/strapi-plugin-content-manager/controllers/content-types.js
Add route to return the list of settings for all content types
> Content manager content types settings

- packages/strapi-plugin-content-manager/oas.yml
Add GET content-types-settings spec
> Add GET content-types-settings spec

- packages/create-strapi-starter/utils/build-starter.js
- packages/strapi-generate-new/lib/create-project.js
- packages/strapi-generate-new/lib/index.js
- packages/strapi-generate-new/lib/resources/json/package.json.js
- packages/strapi-generate-new/lib/utils/merge-template.js
- packages/strapi-generate-new/lib/utils/usage.js
- packages/strapi/lib/core/app-configuration/index.js
- packages/strapi/lib/services/metrics/sender.js
Adds starter url to tracking event
> [Starter CLI] Add starter tracking

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewLayoutManager/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/utils/arrayOfPluginOptions.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/utils/buildQueryString.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/utils/createPluginsFilter.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/utils/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListView/utils/tests/buildQueryString.test.js
- packages/strapi-plugin-content-manager/admin/src/containers/ListViewLayoutManager/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/RBACManager/actions.js
- packages/strapi-plugin-content-manager/admin/src/containers/RBACManager/useSyncRbac.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewLocalePicker/index.js
- packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js
- packages/strapi-plugin-i18n/admin/src/middlewares/extendCMEditViewLayoutMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/localePermissionMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/localeQueryParamsMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCMEditViewLayoutMiddleware.test.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/localePermissionMiddleware.test.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/localeQueryParamsMiddleware.test.js
- packages/strapi-plugin-i18n/admin/src/utils/getLocaleFromQuery.js
- packages/strapi-plugin-i18n/admin/src/utils/tests/getInitialLocale.test.js
> [I18n] Change plugins filter in CM

- packages/strapi-plugin-content-manager/admin/src/components/State/Wrapper.js
- packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeFormWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditViewLayoutManager/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/RBACManager/useSyncRbac.js
It sends the correct query string in the post endpoint
> [I18n] Post single locale

- packages/strapi-plugin-content-manager/admin/src/components/Inputs/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/cleanData.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/generateOptions.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/tests/cleanData.test.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/tests/generateOptions.test.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewInjectedComponents/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewInjectedComponents/selectors.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewLocalePicker/index.js
- packages/strapi-plugin-i18n/admin/src/translations/en.json
- packages/strapi-plugin-i18n/admin/src/utils/getDefaultLocale.js
This PR fixes some small bugs and add the RBAC management to the locale picker.
> [I18n] CM fixes

- packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLink/LeftMenuLinkContent.js
- packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLink/index.js
- packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLinkSection/index.js
- packages/strapi-admin/admin/src/containers/LeftMenu/actions.js
- packages/strapi-admin/admin/src/containers/LeftMenu/constants.js
- packages/strapi-admin/admin/src/containers/LeftMenu/index.js
- packages/strapi-admin/admin/src/containers/LeftMenu/useMenuSections.js
- packages/strapi-admin/admin/src/containers/LeftMenu/utils/generateModelsLinks.js
- packages/strapi-admin/admin/src/containers/LeftMenu/utils/getCtOrStLinks.js
- packages/strapi-admin/admin/src/containers/LeftMenu/utils/tests/generateModelsLinks.test.js
- packages/strapi-admin/admin/src/containers/LeftMenu/utils/tests/getCtOrStLinks.test.js
- packages/strapi-plugin-i18n/admin/src/middlewares/addLocaleToSingleTypesMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/index.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/addLocaleToSingleTypesMiddleware.test.js
- packages/strapi-plugin-i18n/admin/src/utils/getDefaultLocale.js
This PR adds a middleware in order to mutate a single type link.
> Needs to merged after #9751 & #9752
> [I18n] Add middleware to override menu links for single types

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/ListItem.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js
- packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewInjectedComponents/index.js
- packages/strapi-plugin-i18n/admin/src/middlewares/extendCMEditViewLayoutMiddleware.js
- packages/strapi-plugin-i18n/admin/src/middlewares/tests/extendCMEditViewLayoutMiddleware.test.js
This PR persists the search when navigating from one localised content type to another.
> [I18n] CM fix navigation between localised content types

- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeFormWrapper/index.js
- packages/strapi-plugin-content-manager/admin/src/sharedReducers/crudReducer/actions.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewInjectedComponents/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewLocalePicker/index.js
- packages/strapi-plugin-i18n/admin/src/middlewares/addCommonFieldsToInitialDataMiddleware.js
This PR fixes small bugs related to the single types management
> [I18n] Fix single types

- packages/strapi-plugin-i18n/admin/src/components/LocalePicker/index.js
Fixes padding in the locale picker list
> [i18n] fix padding in locale picker list

- packages/strapi-plugin-i18n/services/__tests__/core-api.test.js
- packages/strapi-plugin-i18n/services/core-api.js
Improve localization  file sanitizer
> [i18n] Improve localization  file sanitizer

- packages/strapi-admin/admin/src/containers/LeftMenu/useMenuSections.js
It fixes the left menu when updating a content type.
To prevent the collection types and single types section from being removed from the left menu when updating a content type.
Go to the content type builder and modify an existing content type, the menu should be updated only when the loader stop showing up
> Fix menu links that were missing when updating a content type

- packages/create-strapi-starter/utils/build-starter.js
Fixes an issue where `FORCE_COLOR` breaks dev server on Windows
> add cross env

- packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/LocaleListCell.js
- packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/tests/LocaleListCell.test.js
It shows all the available locale in the listview "content available" cell
> [i18n] show all the available locale in the listview "content available" cell

- packages/strapi-plugin-content-manager/admin/src/components/CustomInputCheckbox/index.js
> [CM] Fix margin checkbox in ListView

- packages/strapi-plugin-i18n/admin/src/components/LocaleList/index.js
> [I18N] Add border-radius in settings list of locales

- packages/strapi-plugin-content-manager/admin/src/translations/en.json
Fixing a typo in the delete modale
> [I18N] fix typo in delete modal

- packages/strapi-plugin-content-manager/admin/src/containers/ListView/FieldPicker/index.js
In the ListView, the distance between the cog and the dropdown carret was 20px. It needs to be 10px.
> Fix margin for cog in ListView dropdown

- packages/strapi-plugin-content-manager/admin/src/translations/en.json
> [I18N] fix typo

- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeFormWrapper/index.js
Add search params to publish action
> Add search params to publish action

- packages/strapi-admin/admin/src/components/Roles/ContentTypeCollapse/Wrapper.js
- packages/strapi-plugin-upload/admin/src/components/InputMedia/Name.js
> Add padding

- packages/strapi-admin/admin/src/components/Roles/ContentTypes/Wrapper.js
- packages/strapi-admin/admin/src/components/Roles/PluginsAndSettings/ListWrapper.js
This PR adds the missing bottom border radius in the rbac editview
> Fix border radius in RBAC Editview

- packages/strapi-admin/admin/src/containers/Roles/EditPage/index.js
- packages/strapi-admin/config/functions/bootstrap.js
- packages/strapi-admin/services/content-type.js
- packages/strapi-admin/services/permission/queries.js
- On bootstrap, removes permissions with invalid properties
- On the role/permissions form in the FE, display a notification with a meaningful message on validation error
> Remove breaking permissions

- packages/strapi-helper-plugin/lib/src/components/InjectionZone/InjectionZoneList.js
Resetting the `<ul>` styl fot the InjectionZoneList
> Center content delete locale content

- packages/strapi-admin/admin/src/containers/ProfilePage/components.js
- packages/strapi-admin/admin/src/containers/ProfilePage/index.js
- packages/strapi-helper-plugin/lib/src/components/Select/styles.js
It uses the same components as the ones used in the users page.
> Change Profile page dom

- packages/strapi-plugin-i18n/admin/src/components/LocaleList/index.js
- packages/strapi-plugin-i18n/admin/src/components/ModalCreate/index.js
It removes the already added locales from the available options.
> Only display not used locales

- packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuFooter/Wrapper.js
- packages/strapi-admin/admin/src/containers/LeftMenu/useMenuSections.js
- packages/strapi-admin/admin/src/containers/ProfilePage/index.js
- packages/strapi-admin/admin/src/containers/Users/EditPage/index.js
It fixes some small ui regression
> i18n small fixes

- packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/LocaleListCell.js
> Fix tooltip i18n

- packages/strapi-plugin-content-manager/admin/src/utils/removeKeyInObject.js
- packages/strapi-plugin-content-manager/admin/src/utils/tests/removeKeyInObject.test.js
> Fix object wrong mutation in the CM

- packages/strapi-admin/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-documentation/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-users-permissions/package.json
- yarn.lock
It downgrades the version of react-redux.
> Revert react-redux upgrade

- packages/strapi-admin/admin/src/containers/Admin/Logout/components.js
The user dropdown has now a min-width of 190px
> Fix dropdown size for the user

- packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/tests/LocaleListCell.test.js
It fixes the tests on locale cells in listview table
> Fix locale cells tests

- packages/strapi-plugin-i18n/admin/src/permissions.js
> Remove create permissions for i18n settings

- packages/strapi-plugin-content-type-builder/admin/src/components/CheckboxWithDescription/index.js
- packages/strapi-plugin-i18n/admin/src/index.js
- packages/strapi-plugin-i18n/admin/src/translations/en.json
- packages/strapi-plugin-i18n/admin/src/utils/localizedFields.js
It removes the ability to localise the `uid` fields and ensures that unique fields are localised.
> Ensure unique fields are localized

- packages/strapi-admin/admin/src/plugins.js
- packages/strapi-admin/package.json
- packages/strapi-plugin-content-manager/admin/src/containers/ComponentSetttingsView/index.js
- packages/strapi-plugin-content-manager/admin/src/containers/EditSettingsView/index.js
- packages/strapi-plugin-content-manager/admin/src/hooks/useFetchContentTypeLayout/index.js
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/admin/src/containers/FormModal/index.js
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-plugin-documentation/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi-plugin-users-permissions/package.json
- yarn.lock
It upgrades the version of react-redux.
> Upgrade react-redux

- packages/strapi-plugin-content-manager/admin/src/components/CustomTable/styledComponents.js
- packages/strapi-plugin-i18n/admin/src/components/LocaleListCell/LocaleListCell.js
It Fixes a bug preventing the preview of an image from overflowing the cell
> Ellipsis on locale cell instead of all cells in ListView

- packages/strapi-admin/admin/src/containers/Admin/Wrapper.js
- packages/strapi-helper-plugin/lib/src/components/ModalConfirm/styledComponents.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/index.js
- packages/strapi-plugin-i18n/admin/src/components/CMEditViewCopyLocale/utils/generateOptions.js
Fixes the sticky header, and selects the first locale for copy
> Fix sticky header and select the first locale for copy

- packages/strapi-plugin-content-manager/admin/src/containers/SingleTypeFormWrapper/index.js
I looked at the tests to create one but I was a bit lost :P I can do it with a front however. Please tell me if it's needed and how we can do it if we want to :)
> fix singletype put

- packages/strapi-plugin-i18n/controllers/content-types.js
It was throwing a 404 for a locale different from the default locale
> fix getNonLocalizedAttributes route for ST

- packages/strapi-plugin-graphql/services/resolvers-builder.js
- packages/strapi-plugin-graphql/services/shadow-crud.js
- packages/strapi-plugin-i18n/controllers/__tests__/content-types.test.js
Fix single type delete by passing locale param over to the action for all mutations
> [i18n] Fix single type delete 

- packages/strapi-generate-new/lib/index.js
> Make i18n preinstalled

- packages/strapi-admin/admin/src/translations/en.json
- packages/strapi-helper-plugin/lib/src/testUtils/commonTrads.json
- test/config/front/testUtils/commonTrads.json
Improves an English language translation
Original text is awkward
No additional testing needed
None
> Improve english text

- packages/strapi-plugin-sentry/package.json
- packages/strapi-plugin-upload/package.json
- packages/strapi/lib/Strapi.js
- packages/strapi/lib/core/app-configuration/index.js
Adds plugins and providers to 'didStartServer' send event
> Add plugins and providers to send event

- packages/strapi-plugin-content-type-builder/controllers/ContentTypes.js
- packages/strapi-plugin-i18n/config/functions/bootstrap.js
- packages/strapi-plugin-i18n/services/__tests__/locales.test.js
- packages/strapi-plugin-i18n/services/__tests__/metrics.test.js
- packages/strapi-plugin-i18n/services/locales.js
- packages/strapi-plugin-i18n/services/metrics.js
- packages/strapi/lib/services/metrics/__tests__/stringify-deep.test.js
- packages/strapi/lib/services/metrics/sender.js
- packages/strapi/lib/services/metrics/stringify-deep.js
> Add i18n telemetry

- packages/strapi-plugin-content-type-builder/services/schema-builder/content-type-builder.js
- packages/strapi-plugin-content-type-builder/services/schema-builder/index.js
Keeps extra options set in the model definition  file for relation  on CTB update
Fixes #3409
> Fix issue relation loosing extra options on ctb update 

- packages/strapi-plugin-upload/admin/src/components/EditForm/index.js
Fixes #10044
@vinod77 can you test this ?
> Remove cache key so the url is valid for cors policy

- packages/strapi/lib/core-api/service/collection-type.js
> Fix #10172

- packages/strapi-plugin-i18n/admin/src/translations/fr.json
Fixed a typo and harmonized according to the other plugins.
> Update french translation to i18n plugin

- packages/core/admin/package.json
- packages/core/admin/webpack.config.js
- packages/core/helper-plugin/package.json
- packages/core/helper-plugin/rollup.config.js
- yarn.lock
It adds the babel-plugin-styled-components to both the helper-plugin rollup config and the admin webpack config
Please refer to the [styled-components](https://styled-components.com/docs/tooling) documentation.
> Add babel plugin styled components

- packages/strapi-admin/ee/admin/containers/AuthResponse/index.js
Remove the useless condition on success redirection and clear app storage before SSO connection.
close #9919
> Fix SSO success redirection

- packages/strapi-plugin-i18n/config/routes.json
> Make listLocales route available for non-admin

- packages/core/admin/admin/src/StrapiApp.js
- packages/core/admin/admin/src/core/store/configureStore.js
- packages/core/admin/admin/src/plugins.js
- packages/plugins/i18n/admin/src/containers/Initializer.js
- packages/plugins/i18n/admin/src/containers/SettingsPage/tests/SettingsPage.test.js
- packages/plugins/i18n/admin/src/hooks/useHasI18n/index.js
- packages/plugins/i18n/admin/src/hooks/useLocales/index.js
- packages/plugins/i18n/admin/src/index.js
- packages/plugins/i18n/admin/src/middlewares/addCommonFieldsToInitialDataMiddleware.js
- packages/plugins/i18n/admin/src/middlewares/addLocaleColumnToListViewMiddleware.js
- packages/plugins/i18n/admin/src/middlewares/addLocaleToCollectionTypesMiddleware.js
- packages/plugins/i18n/admin/src/middlewares/addLocaleToSingleTypesMiddleware.js
- packages/plugins/i18n/admin/src/middlewares/extendCTBAttributeInitialDataMiddleware.js
- packages/plugins/i18n/admin/src/middlewares/tests/addCommonFieldsToInitialDataMiddleware.test.js
- packages/plugins/i18n/admin/src/middlewares/tests/addLocaleColumnToListViewMiddleware.test.js
- packages/plugins/i18n/admin/src/middlewares/tests/addLocaleToCollectionTypesMiddleware.test.js
- packages/plugins/i18n/admin/src/middlewares/tests/addLocaleToSingleTypesMiddleware.test.js
- packages/plugins/i18n/admin/src/middlewares/tests/extendCTBAttrributeInitialDataMiddleware.test.js
- packages/plugins/i18n/admin/src/selectors/selectCollectionTypesRelatedPermissions.js
- packages/plugins/i18n/admin/src/selectors/selectI18nLocales.js
it loads the i18n plugin in the admin panel
> Load i18n plugin

- examples/getstarted/plugins/myplugin/admin/src/index.js
- packages/core/admin/index.js
- packages/core/strapi/lib/commands/watchAdmin.js
It updates the admin/index.js file to support the new admin architecture.
> Fix generated app build

- README.md
Dropping MongoDB support announcement
> Update: dropping MongoDB support

- packages/core/content-manager/admin/src/pages/ListSettingsView/index.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/init.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/reducer.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/tests/init.test.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/tests/reducer.test.js
Move the list view settings reducer of the Content Manager to Immer and add tests.
> Move listview settings reducer and add tests

- packages/core/content-manager/admin/src/pages/EditSettingsView/index.js
- packages/core/content-manager/admin/src/pages/EditSettingsView/init.js
- packages/core/content-manager/admin/src/pages/EditSettingsView/reducer.js
- packages/core/content-manager/admin/src/pages/EditSettingsView/tests/init.test.js
- packages/core/content-manager/admin/src/pages/EditSettingsView/tests/reducer.test.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/reducer.js
- packages/core/content-manager/admin/src/pages/ListSettingsView/tests/reducer.test.js
- packages/core/content-manager/admin/src/utils/arrayMoveItem.js
- packages/core/content-manager/admin/src/utils/index.js
- packages/core/content-manager/admin/src/utils/tests/arrayMoveItem.test.js
Move the actual edit settings reducer to immer and add tests
> Move edit settings reducer and add tests

- packages/strapi-admin/package.json
- packages/strapi-plugin-content-manager/package.json
- packages/strapi-plugin-content-type-builder/package.json
- packages/strapi-utils/package.json
Upgrade Yup and fix breaking changes to resolve a high security alert with prototype pollution.
Security update
N/A
N/A
> Upgrade yup to resolve prototype pollution

- packages/core/admin/admin/src/StrapiApp.js
- packages/core/admin/admin/src/tests/StrapiApp.test.js
- packages/core/admin/package.json
- packages/core/helper-plugin/lib/src/providers/StrapiAppProvider/index.js
- packages/utils/hooks/lib/index.js
- packages/utils/hooks/lib/tests/index.test.js
- packages/utils/hooks/package.json
- yarn.lock
It implements a "Hook" API to resolve a bunch of functions sequentially, in waterfall or "in parallel". Wildly inspired by the POC made by @alexandrebodin (it's basically a c/c of the sandbox).
```js
// This is the proposed API
const app =  new StrapiApp({ appPlugins, library, middlewares, reducers });
// Creating a new hook
app.createHook('hello-world')
// Registering a function that should execute when the "hello-world" hook is run
app.registerHook('hello-world', () => 'hello world')
// Runs the hook using the different methods
const [result] = app.runHookSeries(args?, asynchronous?);
const result = app.runHookWaterfall(args?, asynchronous?);
const [result] = await app.runHookParallel(args?, asynchronous?);
// Async variants are provided also in case async hooks may be registered
// …
```
> Add the Hooks API in core

- packages/strapi-plugin-content-manager/admin/src/components/SelectMany/Relation.js
Improve the relation item spacing
To fix the relation item spacing as mentioned here #9043:
Check the fixed relation item spacing
Fix #9043
> Improve the relation item spacing

- packages/strapi-plugin-sentry/package.json
Updates the version of the `@sentry/node` SDK
We should try to always keep the SDK up to the newest stable versions
> chore(sentry-sdk): update the sentry SDK version

- examples/getstarted/api/address/models/Address.settings.json
- packages/core/admin/admin/src/content-manager/components/CollectionTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/InputUID/index.js
- packages/core/admin/admin/src/content-manager/components/RelationPreviewList/RelationPreviewTooltip.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/index.js
- packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
- packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js
- packages/core/admin/admin/src/content-manager/pages/App/useModels.js
- packages/core/admin/admin/src/content-manager/pages/App/utils/getContentTypeLinks.js
- packages/core/admin/admin/src/content-manager/pages/App/utils/tests/getContentTypeLinks.js
- packages/core/admin/admin/src/content-manager/pages/ComponentSetttingsView/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
- packages/core/admin/admin/src/content-manager/pages/ListSettingsView/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/admin/src/content-manager/utils/getRequestUrl.js
- packages/core/admin/admin/src/core/utils/axiosInstance.js
- packages/core/admin/admin/src/tests/StrapiApp.test.js
It removes the request helper from the cm to use axios instead.
> Remove request helper use in CM

- jest.config.front.js
- packages/core/admin/admin/src/components/LeftMenu/compos/Footer/index.js
- packages/core/admin/admin/src/index.js
- packages/core/admin/controllers/__tests__/admin.test.js
- packages/core/admin/controllers/admin.js
- packages/core/admin/ee/admin/components/Users/ModalCreateBody/utils/formDataModel.js
- packages/core/admin/ee/admin/components/Users/ModalCreateBody/utils/roleSettingsForm.js
- packages/core/admin/ee/admin/hooks/useSettingsMenu/utils/customGlobalLinks.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Login/index.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Providers/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/utils/customRoutes.js
- packages/core/admin/env.js
- packages/core/admin/index.js
- packages/core/admin/scripts/build.js
- packages/core/admin/webpack.config.dev.js
- packages/core/admin/webpack.config.js
- packages/core/helper-plugin/lib/src/hooks/useTracking/index.js
- packages/core/strapi/lib/commands/build.js
- packages/utils/babel-plugin-switch-ee-ce/README.md
- packages/utils/babel-plugin-switch-ee-ce/lib/index.js
- packages/utils/babel-plugin-switch-ee-ce/lib/mapToRelative.js
- packages/utils/babel-plugin-switch-ee-ce/lib/normalizeOptions.js
- packages/utils/babel-plugin-switch-ee-ce/lib/resolvePath.js
- packages/utils/babel-plugin-switch-ee-ce/lib/utils.js
- test/config/front/strapi.js
It allows to enable custom features at runtime.
> Allow to switch plan at runtime

- packages/strapi-plugin-users-permissions/services/Providers.js
> Fix Typo actualy to actually

- packages/core/content-type-builder/admin/src/components/FormModal/reducer.js
- packages/core/content-type-builder/admin/src/components/FormModal/tests/reducer.test.js
- packages/core/content-type-builder/admin/src/utils/tests/getRelationType.test.js
It fixes and adds the missing tests in the CTB FormModal reducer.
> Fix FormModal reducer tests

- packages/core/admin/controllers/admin.js
It fixes the server that won't start if the plan is not EE
> Fix server not starting 

- packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
Add the private option to components.
Fixes #10563
> Add private option to components

- packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js
> Add DndProvider to fix the front tests

- examples/getstarted/plugins/myplugin/admin/src/index.js
- packages/core/admin/index.js
It removes the current plugin customisations. Now the front-end part of the plugins cannot be customised using the filesystem, plugin extensions will be possible either by forking the plugin or by using the provided API.
> Remove plugins customisations

- packages/strapi-plugin-content-type-builder/controllers/validation/types.js
Fixed a typo in an error I ran against
The error message isn't clear and contains a typo.
Create a deeply nested component and try to save it.
no, but could be created if needed.
> Fixed typo

- packages/strapi-plugin-documentation/services/Documentation.js
fixed typo
Fixed a typo in strapi. 
Because spelling was incorrect, which cause all the children document spelling wrong
> Fix typo in documentation plugin

- packages/core/admin/admin/src/components/GlobalStyle/index.js
- packages/core/admin/package.json
- packages/core/helper-plugin/package.json
- yarn.lock
> Remove bootstrap

- packages/generators/generate-plop/plopfile.js
- packages/generators/generate-plop/templates/model.js.hbs
- packages/generators/generate-plop/templates/model.settings.json.hbs
> add model generator

- packages/core/utils/lib/__tests__/convert-rest-query-params.test.js
- packages/core/utils/lib/convert-rest-query-params.js
> Cleanup convert sort params

- packages/core/admin/server/config/admin-actions.js
- packages/core/admin/server/tests/admin-permission.test.e2e.js
This PR introduce the permissions for the API token.
Registering the permission is the first step in adding the API token feature into the admin.
The code is supported by the e2e test: Role CRUD End to End - Can get the existing permissions (`packages/core/admin/server/tests/admin-permission.test.e2e.js`)
> Add CRUD permission for the api token

- packages/core/admin/admin/src/pages/Webhooks/ListView/index.js
- packages/core/admin/admin/src/pages/Webhooks/ListView/tests/index.test.js
- packages/core/admin/admin/src/pages/Webhooks/ListView/tests/server.js
Replaced old confirmation modal with Dialog component
Added tests
> Webhooks LV delete

- packages/core/strapi/lib/services/entity-service/params.js
- packages/core/utils/lib/convert-query-params.js
- Implement convert fields query params to handle field select in the REST API
> Implement fields convert query params

- packages/core/utils/lib/convert-query-params.js
- Implement sort query param
Here is a simple test script
```js
const qs = require("qs");
const axios = require("axios");
const queries = [
{ sort: "name" },
{ sort: "name:asc" },
{ sort: "name,slug:desc" },
{ sort: "name:asc,slug:desc" },
{ sort: ["name"] },
{ sort: ["name", "slug"] },
{ sort: ["name:asc", "slug"] },
{ sort: ["name:asc", "slug:desc"] },
{ sort: { name: "asc" } },
{ sort: { name: "asc", slug: "desc" } },
{ sort: [{ name: "asc" }, { slug: "desc" }] },
{ sort: [{ name: "asc" }, { categories: { name: "desc" } }] },
{ sort: "categories.name:asc" },
];
async function main() {
for (const query of queries) {
const s = qs.stringify(query, { encoding: false });
const url = `http://localhost:1337/restaurants?${s}`;
const r = await axios.get(url);
console.log(url, r.status);
}
} …
```
> Handle sort query param

- packages/core/admin/server/bootstrap.js
- packages/core/admin/server/config/api-token.js
- packages/core/admin/server/config/index.js
- packages/core/admin/server/content-types/api-token.js
- packages/core/admin/server/content-types/index.js
- packages/core/admin/server/controllers/__tests__/api-token.test.js
- packages/core/admin/server/controllers/api-token.js
- packages/core/admin/server/controllers/index.js
- packages/core/admin/server/routes.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/services/index.js
- packages/core/admin/server/tests/admin-api-token.test.e2e.js
- packages/core/admin/server/utils/index.d.ts
- packages/core/admin/server/validation/api-tokens.js
This PR adds an endpoint to create API tokens. 
This is the first endpoint required to be able to implement the rest of the API token related features.
The code is supported by unit test on the `controller` and `service` layer. It also includes e2e tests.
> Implement the POST endpoint to create api tokens

- .eslintignore
- examples/getstarted/config/api.js
- packages/core/strapi/lib/core-api/__tests__/service.test.js
- packages/core/strapi/lib/core-api/controller/index.js
- packages/core/strapi/lib/core-api/service/collection-type.js
- packages/core/strapi/lib/core-api/service/index.js
- packages/core/strapi/lib/core-api/service/pagination.js
- packages/core/strapi/lib/core-api/service/single-type.js
- packages/core/strapi/lib/core/domain/content-type/index.js
- packages/core/strapi/lib/middlewares/parser/index.js
- packages/core/strapi/tests/search.test.e2e.js
- packages/generators/app/lib/resources/files/config/api.js
What is done in this PR
- Implement REST API pagination with paged or offset and withCount
- Implement pagination logic in core api
> [v4] REST api pagination

- packages/core/admin/admin/src/pages/Webhooks/ListView/index.js
- packages/core/admin/admin/src/pages/Webhooks/ListView/tests/index.test.js
- packages/core/admin/admin/src/translations/en.json
Implemented delete all in webhooks LV + test confirmation delete modal
> Webhooks LV - Delete all

- packages/core/strapi/lib/core-api/controller/collection-type.js
- packages/core/strapi/lib/core-api/controller/single-type.js
- packages/core/strapi/lib/core-api/controller/transform.js
- packages/core/strapi/tests/api/basic-compo-repeatable.test.e2e.js
- packages/core/strapi/tests/api/basic-compo.test.e2e.js
- packages/core/strapi/tests/api/basic-dp-compo-repeatable.test.e2e.js
- packages/core/strapi/tests/api/basic-dp-compo.test.e2e.js
- packages/core/strapi/tests/api/basic-dp.test.e2e.js
- packages/core/strapi/tests/api/basic-dz.test.e2e.js
- packages/core/strapi/tests/api/basic.test.e2e.js
- packages/core/strapi/tests/components/repeatable-not-required-min-max.test.e2e.js
- packages/core/strapi/tests/components/repeatable-not-required.test.e2e.js
- packages/core/strapi/tests/components/repeatable-required-min-max.test.e2e.js
- packages/core/strapi/tests/components/repeatable-required.test.e2e.js
- packages/core/strapi/tests/components/single-not-required.test.e2e.js
- packages/core/strapi/tests/components/single-required.test.e2e.js
- packages/core/strapi/tests/dynamiczones/simple.test.e2e.js
- packages/core/strapi/tests/dynamiczones/with-media.test.e2e.js
- packages/core/strapi/tests/endpoint.test.e2e.js
- packages/core/strapi/tests/search.test.e2e.js
- packages/core/strapi/tests/single-type.test.e2e.js
The goal is to make the request format more flexible
- Use `{ data: {..} }` as request body instead of directly sending an object.
> [v4] Move request format in core-api

- packages/core/admin/admin/src/hooks/useSettingsMenu/index.js
- packages/core/admin/admin/src/hooks/useSettingsMenu/init.js
- packages/core/admin/admin/src/pages/SettingsPage/components/SettingsNav/index.js
Added notification bullet point on Application NavLink when user can upgrade their admin panel
> added subnav application notification

- packages/core/helper-plugin/lib/src/components/ContentBox/ContentBox.stories.mdx
- packages/core/helper-plugin/lib/src/components/ContentBox/index.js
- packages/core/helper-plugin/lib/src/components/ContentBox/tests/index.test.js
- packages/core/helper-plugin/lib/src/index.js
ContentBox component needed in several views
Created in helper-plugin
+ test + storybook
> ContentBox helper-plugin

- packages/plugins/users-permissions/admin/src/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
Starts migrating the edit view of a role to Strapi Parts.
> [v4] Create users-permissions edit role page structure

- packages/plugins/users-permissions/admin/src/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
It migrates the Header component for the RolesList Page
> [v4] migrate roles page header

- packages/core/admin/server/controllers/__tests__/api-token.test.js
- packages/core/admin/server/controllers/api-token.js
- packages/core/admin/server/routes.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/tests/admin-api-token.test.e2e.js
- packages/core/admin/server/utils/index.d.ts
This PR add the possibility to get a single api token.
This endpoint is required to be able to fully implement the update feature.
The code is supported by both unit and e2e tests.
> Implement GET endpoint to get a single token

- packages/core/admin/package.json
- packages/core/helper-plugin/createBuildIndex.js
- packages/core/helper-plugin/package.json
- packages/core/helper-plugin/webpack.config.js
It adds a development bundle of the helper plugin.
> Add dev build in helper plugin

- packages/core/admin/index.js
- packages/core/strapi/lib/commands/build.js
- packages/core/strapi/lib/commands/watchAdmin.js
- packages/generators/app/lib/index.js
Use  `@strapi/strapi` to get enabled plugins to build the admin
> Use enabled plugins to build admin

- packages/plugins/i18n/admin/src/components/ModalDelete/index.js
Delete a locale in i18n settings using parts
> Delete locale with parts

- packages/core/admin/admin/src/pages/Admin/index.js
- packages/core/admin/admin/src/plugins.js
- packages/core/admin/index.js
- packages/core/admin/webpack.config.dev.js
- packages/core/admin/webpack.config.js
- packages/core/content-type-builder/admin/src/index.js
- packages/core/upload/admin/src/index.js
Builds admin plugins from node modules directly
> Fix admin build with node_modules paths

- packages/plugins/i18n/admin/src/components/LocaleList/LocaleTable.js
- packages/plugins/i18n/admin/src/components/LocaleList/index.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/index.js
- packages/plugins/i18n/admin/src/components/ModalCreate/index.js
- packages/plugins/i18n/admin/src/components/ModalEdit/AdvancedForm.js
- packages/plugins/i18n/admin/src/components/ModalEdit/BaseForm.js
- packages/plugins/i18n/admin/src/components/ModalEdit/index.js
> Update edit a locale with parts

- packages/core/admin/admin/src/content-manager/pages/App/index.js
- packages/core/admin/admin/src/content-manager/pages/NoPermissions/index.js
- packages/core/admin/admin/src/content-manager/pages/NoPermissions/tests/index.test.js
1. Create role with that has no permissions on any content type
2. Create a user with this role
3. Log in to the admin with this user and click on the content manager link.
> Add No permissions view to CM

- packages/plugins/i18n/admin/src/components/LocaleSelect/index.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/tests/LocaleSelect.test.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/tests/server.js
> Add tests for select locale

- packages/core/admin/admin/src/pages/HomePage/SocialLinks.js
- packages/core/admin/admin/src/pages/HomePage/index.js
- packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
> Fix homepage small a11y issues

- packages/core/admin/server/controllers/__tests__/api-token.test.js
- packages/core/admin/server/controllers/api-token.js
- packages/core/admin/server/routes/api-tokens.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/tests/admin-api-token.test.e2e.js
- packages/core/admin/server/validation/api-tokens.js
This PR introduce the PUT endpoint to update the name, description and type of an api token.
The endpoint will allow users to modify the details of their token.
The code is supported by e2e and unit tests.
> Implement PUT endpoint to update a token

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/Search/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/translations/en.json
Adds Search to the RolesListPage and EmptyStateLayout based on no roles, or no roles from search
> [v4] add search to roles list page

- packages/core/content-type-builder/admin/src/components/FormModal/attributes/types.js
It fixes the relation validator.
To prevent from creating an attribute that already in a target content type.
> Fix ctb relation taken attribute

- packages/plugins/users-permissions/admin/src/components/Permissions/index.js
- packages/plugins/users-permissions/admin/src/components/Permissions/init.js
- packages/plugins/users-permissions/admin/src/components/Permissions/tests/init.test.js
- packages/plugins/users-permissions/admin/src/components/Policies/index.js
- packages/plugins/users-permissions/admin/src/components/UsersPermissions/index.js
- packages/plugins/users-permissions/admin/src/hooks/usePlugins/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/server.js
- packages/plugins/users-permissions/admin/src/utils/formatPluginName.js
List plugins in an accordion view. The test is only a snapshot so far. But I'm planning to test the interactivity of the app once I have the next pieces of this page (the permission checkboxes, and list of routes in the sidebar)
Open `/admin/settings/users-permissions/roles/1`
> [v4] List plugins in users-permissions edit role view

- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/BaselineAlignment.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/components/TableBody.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/utils/api.js
Add delete action
Add some roles then try to delete them
> [v4] add delete roles

- packages/core/upload/admin/src/components/UploadAssetDialog/FromComputerForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/FromUrlForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
- packages/core/upload/admin/src/components/UploadAssetDialog/tests/UploadAssetDialog.test.js
- packages/core/upload/admin/src/pages/App/index.js
- packages/core/upload/admin/src/translations/en.json
> Init the upload asset dialog

- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/index.js
Fixed trad in advanced settings view
> Migration/ Advanced Settings trad

- packages/core/upload/admin/src/components/AssetCard/UnknownAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/tests/ImageAssetCard.test.js
- packages/core/upload/admin/src/components/AssetCard/tests/UnknownAssetCard.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromUrlForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromUrlForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/server.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/PendingAssetStep.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
- packages/core/upload/admin/src/constants.js
- packages/core/upload/admin/src/pages/App/components/ListView.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
- packages/core/upload/admin/src/utils/urlsToAssets.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/index.test.js
Add assets now fills the pending step of the add asset dialog
- Go to the ML
- Click Add new asset
- Select "From url"
- Add some url (one per line)
- Validate
- You should see a preview of the different files
> Make add URL work with pending step

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
- packages/core/admin/admin/src/translations/en.json
> Fix webhooks wording and button size

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/HeadersInput/index.js
Fixed missing label for TextInput in webhooks form headers component
> Migration/ Webhooks form label fix

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsButton/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/PluginsAndSettings/SubCategory/index.js
Button should be tertiary without style overrides.
> Fix button style on rbac

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/tests/index.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/WebhookForm/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/core/upload/admin/src/pages/SettingsPage/index.js
- packages/core/upload/admin/src/pages/SettingsPage/tests/__snapshots__/index.test.js.snap
- packages/plugins/i18n/admin/src/components/LocaleList/index.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/index.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/index.test.js
Fixed all headers button with size L + updated snapshots
> Migration/ Headers button size

- packages/core/admin/admin/src/components/UpgradePlanModal /index.js
Removed label close from close IconButton in upgrade plan modal component
> MigrationQA/ Upgrade plan modal fix

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js
Added saved notification on users edit view
> MigrationQA/ User save notification

- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/AddAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromUrlForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromComputerForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/PendingAssetStep.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
- packages/core/upload/admin/src/components/UploadAssetDialog/tests/UploadAssetDialog.test.js
- packages/core/upload/admin/src/translations/en.json
- packages/core/upload/admin/src/utils/tests/typeFromMime.test.js
- packages/core/upload/admin/src/utils/typeFromMime.js
- packages/core/upload/admin/src/utils/urlsToAssets.js
- Prepares the Upload from computer step in the ML
- Go to the ML
- Add a new asset
- Select from computer and browse a file
- Select one file
- Validate
- You should see a valid preview of the thing
> Add Upload from computer step

- .github/workflows/tests.yml
- docker-compose.dev.yml
- examples/getstarted/config/database.js
- packages/core/database/lib/dialects/sqlite/schema-inspector.js
- packages/core/database/lib/query/helpers/join.js
- packages/core/database/lib/query/helpers/order-by.js
- packages/core/database/lib/query/helpers/populate.js
- packages/core/database/lib/query/helpers/where.js
- packages/core/database/lib/query/query-builder.js
- packages/core/strapi/tests/components/single-required.test.e2e.js
> Use sub query on mysql to avoid alias issue & add mysql 5 tests

- packages/core/upload/admin/src/components/AssetCard/DocAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/UnknownAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/VideoAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/tests/ImageAssetCard.test.js
- packages/core/upload/admin/src/components/AssetCard/tests/UnknownAssetCard.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromComputerForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromUrlForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/PendingAssetStep.test.js
- packages/core/upload/admin/src/hooks/useUpload.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
- packages/core/upload/admin/src/pages/App/index.js
- packages/core/upload/admin/src/utils/urlsToAssets.js
Upload files from computer / URL
Next step: cancel and handle errors
> Upload pending selected

- packages/core/upload/admin/src/components/AssetCard/DocAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/UnknownAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/VideoAssetCard.js
- packages/core/upload/admin/src/components/AssetCard/VideoPreview.js
- packages/core/upload/admin/src/components/AssetCard/tests/DocAssetCard.test.js
- packages/core/upload/admin/src/components/AssetCard/tests/ImageAssetCard.test.js
- packages/core/upload/admin/src/components/AssetCard/tests/UnknownAssetCard.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromUrlForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/PendingAssetStep.test.js
- packages/core/upload/admin/src/hooks/useUpload.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
- packages/core/upload/admin/src/translations/en.json
- packages/core/upload/admin/src/utils/urlsToAssets.js
- Cancel
- Upload progress bar
- Resizing of cards in pending step
- Removing the "edit" in pending step
> ML iteration

- packages/core/content-manager/services/__tests__/entity-manager.test.js
- packages/core/content-manager/services/entity-manager.d.ts
- packages/core/content-manager/services/entity-manager.js
- packages/core/strapi/lib/core-api/__tests__/service.test.js
- packages/core/strapi/lib/core-api/controller/collection-type.js
- packages/core/strapi/lib/core-api/controller/single-type.js
- packages/core/strapi/lib/core-api/service/collection-type.js
- packages/core/strapi/lib/core-api/service/single-type.js
- packages/core/strapi/lib/index.d.ts
- packages/core/strapi/lib/services/entity-service/__tests__/entity-service.test.js
- packages/core/strapi/lib/services/entity-service/index.d.ts
- packages/core/strapi/lib/services/entity-service/index.js
- packages/core/strapi/lib/services/entity-service/params.js
- packages/plugins/i18n/server/controllers/validate-locale-creation.js
- packages/plugins/i18n/server/services/__tests__/entity-service-decorator.test.js
- packages/plugins/i18n/server/services/entity-service-decorator.js
Refactor EntityService API to make it more consistent and init some typings  to make it easier to use.
Make the API more consistent for our users
> Refacto entity service API to be more consistent with the DB layer

- packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
- packages/core/upload/admin/src/components/PaginationFooter/index.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/PendingAssetStep.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
- packages/core/upload/admin/src/hooks/useUpload.js
- packages/core/upload/admin/src/pages/App/components/ListView.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
- Files that are successfully uploaded are removed from the modal and added in the background
- Files that are in error shows with a red border
- Canceling an upload removes the asset from the modal
> Pending state, error state, uploads

- packages/core/admin/admin/src/content-manager/pages/ListViewLayoutManager/Permissions.js
It fixes the CM's LV multiple rerenders
> Fix multiple rerenders

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/tests/__snapshots__/index.test.js.snap
> Fix DZ errors

- packages/core/admin/server/bootstrap.js
- packages/core/admin/server/config/admin-actions.js
- packages/core/admin/server/config/api-token.js
- packages/core/admin/server/config/index.js
- packages/core/admin/server/content-types/api-token.js
- packages/core/admin/server/content-types/index.js
- packages/core/admin/server/controllers/__tests__/api-token.test.js
- packages/core/admin/server/controllers/api-token.js
- packages/core/admin/server/controllers/index.js
- packages/core/admin/server/register.js
- packages/core/admin/server/routes/api-tokens.js
- packages/core/admin/server/routes/index.js
- packages/core/admin/server/services/__tests__/api-token.test.js
- packages/core/admin/server/services/api-token.js
- packages/core/admin/server/services/constants.js
- packages/core/admin/server/services/index.js
- packages/core/admin/server/strategies/__tests__/admin.test.js
- packages/core/admin/server/strategies/__tests__/api-token.test.js
- packages/core/admin/server/strategies/admin.js
- packages/core/admin/server/strategies/api-token.js
- packages/core/admin/server/strategies/index.js
- packages/core/admin/server/tests/admin-api-token.test.e2e.js
- packages/core/admin/server/tests/admin-permission.test.e2e.js
- packages/core/admin/server/utils/index.d.ts
- packages/core/admin/server/validation/api-tokens.js
- packages/core/strapi/lib/services/auth/index.js
- packages/plugins/users-permissions/server/register.js
- packages/plugins/users-permissions/server/strategies/users-permissions.js
Add the backend for the API token feature
It's required to be able to implement the front-end.
The feature is supported by e2e and unit tests.
> API Token backend implementation

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/components/DynamicZone/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
> Fix baseline

- packages/core/admin/admin/src/core/utils/axiosInstance.js
- packages/core/content-type-builder/admin/src/utils/axiosInstance.js
- packages/core/upload/admin/src/utils/axiosInstance.js
- packages/plugins/i18n/admin/src/utils/axiosInstance.js
- packages/plugins/users-permissions/admin/src/utils/axiosInstance.js
Fixed 401 error with axiosInstance
> AxiosInstance Fix

- packages/core/email/server/bootstrap.js
- packages/core/upload/server/bootstrap.js
- Allow loading an email or upload provider from a custom package/path using require.resolve.
> V4 Providers resolve

- packages/core/admin/admin/src/pages/AuthPage/components/Login/BaseLogin.js
- packages/core/admin/admin/src/pages/AuthPage/components/Login/tests/BaseLogin.test.js
The `Text` element inside the `Link` one was overriding the style of the Link defined in the DS
> Fix the link component in login page

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
- packages/core/admin/admin/src/translations/en.json
> Fix webhook empty list button size

- packages/plugins/i18n/admin/src/components/LocalePicker/index.js
- packages/plugins/i18n/admin/src/translations/en.json
ℹ️ there's a small warning when switching locales that will be fixed in the DS
> Select for locale picker

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/ComponentCard/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/index.js
> Add a CSS grid in dynamic zones

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/Component/index.js
> Remove double border in DZ

- packages/core/admin/server/services/passport/local-strategy.js
> Lower email when login using local provider

- packages/plugins/i18n/admin/src/components/LocaleSelect/index.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/tests/LocaleSelect.test.js
Integrated Combobox in internationalization view
> MigrationQA/ Combobox in i18n

- packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/Wrapper.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/WysiwygExpand.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/WysiwygNav.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/WysiwygStyles.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/index.js
Fixed z-index inputJson conflict
Fixed scroll block when expand
Fixed Focustrap / tooltip issue (removed focus trap for now, we'll need time to find a better solution)
Fixed preview z-index
Fixed no preview mode button when expanded
> MigrationQA / Wysiwyg issues

- packages/core/admin/admin/src/content-manager/components/Inputs/ComingSoonInput.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
> Init relations

- packages/core/admin/admin/src/content-manager/components/FieldComponent/Label.js
- packages/core/admin/admin/src/content-manager/components/FieldComponent/index.js
- packages/core/admin/admin/src/content-manager/components/NonRepeatableComponent/index.js
- packages/plugins/i18n/admin/src/contentManagerHooks/mutateEditViewLayout.js
- packages/plugins/i18n/admin/src/contentManagerHooks/tests/mutateEditViewLayout.test.js
> Add border to nested compos

- packages/core/admin/server/tests/admin-api-token.test.e2e.js
Update the name of the API tokens in the e2e test to avoid having false negative tests.
> update tests to avoid false negative

- packages/core/admin/admin/src/content-manager/pages/EditView/Informations/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/Informations/tests/index.test.js
> Fix CM last update format

- packages/core/admin/admin/src/pages/InstalledPluginsPage/index.js
- packages/core/admin/admin/src/pages/MarketplacePage/index.js
- packages/core/admin/admin/src/translations/en.json
- packages/core/upload/admin/src/pages/App/index.js
- packages/plugins/documentation/admin/src/pages/App/index.js
- packages/plugins/documentation/admin/src/translations/en.json
Documentation coming soon view + other coming soon views translation fix
> Migration/ Documentation coming soon

- packages/core/admin/admin/src/content-manager/pages/EditView/DeleteLink/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/RoleForm/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/tests/__snapshots__/index.test.js.snap
> Fix some console error on Role edit view and the CM delete button variant

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ConditionsModal/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/RoleForm/index.js
> Fix Permissions secondary button

- examples/getstarted/src/plugins/myplugin/server/register.js
- packages/core/admin/server/register.js
- packages/core/content-type-builder/server/bootstrap.js
- packages/core/email/server/bootstrap.js
- packages/core/strapi/lib/Strapi.js
- packages/core/strapi/lib/core/bootstrap.js
- packages/core/strapi/lib/core/domain/module/index.js
- packages/core/strapi/lib/core/registries/modules.js
- packages/core/upload/server/__tests__/bootstrap.test.js
- packages/core/upload/server/bootstrap.js
- packages/core/upload/server/register.js
- packages/plugins/documentation/server/bootstrap.js
- packages/plugins/graphql/server/bootstrap.js
- packages/plugins/i18n/server/bootstrap.js
- packages/plugins/i18n/server/register.js
- packages/plugins/sentry/server/bootstrap.js
- packages/plugins/users-permissions/server/bootstrap/index.js
- packages/plugins/users-permissions/server/register.js
> Use { strapi } as params in all lifecycle functions

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/ContentTypeCollapse/Collapse/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/EditPage/components/RowLabelWithCheckbox/index.js
> Hover on rbac rows

- packages/core/admin/admin/src/pages/HomePage/ContentBlocks.js
- packages/core/admin/admin/src/pages/HomePage/SocialLinks.js
- packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
> Fix social links

- packages/plugins/i18n/admin/src/components/LocaleListCell/LocaleListCell.js
> Make the content available cell clickable

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/Media/FileWrapper.js
> MigrationQA/ CM table badge fix

- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.js
> Fix ctb menu

- packages/core/admin/admin/src/pages/HomePage/SocialLinks.js
- packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
Replaced medium by strapi blog link
Changed discord svg color
> QA/ Social links fix

- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Roles/ListPage/tests/index.test.js
> Fix admin role list view thead color

- packages/plugins/i18n/admin/src/components/LocaleSelect/index.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/tests/LocaleSelect.test.js
Temporary use the Select component instead of the Combobox
https://github.com/strapi/strapi/issues/11140
> Temporary replace the combobox by the Select component

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/PageSizeURLQuery/index.js
- packages/core/helper-plugin/lib/src/components/PageSizeURLQuery/tests/index.test.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
> Fix select size in pagination

- packages/core/strapi/tests/migrations/migration-draft-publish.test.e2e.js
- packages/core/strapi/tests/migrations/migration-required-attribute.test.e2e.js
- packages/core/strapi/tests/migrations/migration-unique-attribute.test.e2e.js
Some tests are skipped until the unique constraint is added back
> Add migration tests back

- packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js
- packages/core/upload/admin/src/components/EditAssetDialog/AssetMeta.js
- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox.js
- packages/core/upload/admin/src/components/EditAssetDialog/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/index.test.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/core/upload/admin/src/pages/App/components/ListView.js
- packages/core/upload/admin/src/pages/App/components/tests/ListView.test.js
- packages/core/upload/admin/src/translations/en.json
- Prepare the ML edit dialog layout
🙄 
- Go to the media library in the left side menu
- Add a new asset
- After going through the addition process and being back on the listview, click the edit pen on the media card
- Assert that the UI is valid
> Prepare ML Edit layout

- packages/core/admin/admin/src/pages/AuthPage/components/ForgotPassword/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ForgotPasswordSuccess/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Oops/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Oops/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
Fixed auth links style
👌
Check all Auth pages
> MigrationQA/ Auth links

- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DragPreview.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/Preview.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js
> Fix preview for repeatable components

- packages/core/admin/admin/src/content-manager/components/Inputs/utils/getStep.js
- packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js
Temporary set the Timepicker step to 1 in order to be able to set any values between 00:00 to 23:59.
Since the TimePicker is a Select, you cannot set a value that is not in the TimePicker list. If the step of the TimePicker isn't 1, you will not be able to set a value that is between to step.
> Temporary fix the Timepicker step

- packages/core/admin/admin/src/content-manager/pages/App/tests/index.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/tests/index.test.js
- packages/core/admin/admin/src/translations/en.json
Fixed wrong application page labels colors
Fixed community edition trad (was all caps)
> MigrationQA/ Fix application page

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ContentBox/index.js
Fix the notification for the copy paste. It was not showing before.
> fix copy paste notification

- packages/plugins/i18n/admin/src/components/LocaleSelect/index.js
- packages/plugins/i18n/admin/src/components/LocaleSelect/tests/LocaleSelect.test.js
It uses the combobox in the create modal of the i18n settings.
> [v4] Add combobox to i18n settings

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
Exactly what it says in the title
> [v4] Add explicit error when creating a user

- packages/core/admin/server/register.js
Enable API token auth strategy.
> enable API token strategy

- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/AccordionGroupCustom/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DragPreview.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/DragHandleWrapper.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/DraggingSibling.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/IconButtonCustoms.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/Preview.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js
Replaced repeatable components in CM create/edit view with custom AccordionGroup component
Go to CM listview of a collection type
Create or edit an entry with repeatable components in it
Add / Remove / Drag and drop a component inside a repeatable component
> QA/ CM Rep component

- packages/core/strapi/lib/middlewares/security.js
Lighten the security config for /document and /graphql playgrounds
Swagger and graphql-playground use external resources to work (cdns). To keep the app as secure as possible I lightened the config instead of disabling it for those routes. Eventually we should integrate those in the admin itself and not relly on external cdns if those dependencies can allow it
> Lighten the security config for /document and /graphql playgrounds

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/Component/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/index.js
Fixed overflow necessary for react-select but that broked UI
> Migration/ Fixed Accordion overflow

- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/PageSize.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/index.js
- packages/core/upload/admin/src/hooks/useModalAssets/index.js
- packages/core/upload/admin/src/hooks/useModalAssets/useModalQueryParams.js
> Add pagesize

- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/PaginationFooter/Pagination.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/PaginationFooter/PaginationContext.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/PaginationFooter/components.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/PaginationFooter/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/index.js
- packages/core/upload/admin/src/hooks/useModalAssets/useModalQueryParams.js
> [v4] ML Add pagination footer to cm ml

- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/index.js
- packages/core/upload/admin/src/components/SortPicker/index.js
- packages/core/upload/admin/src/hooks/useModalAssets/useModalQueryParams.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
> [v4] Add sort to ML compo in CM

- packages/core/content-type-builder/server/services/builder.js
Add a list of reserved names.
I've tested the values we had in v3 and removed the ones that were no longer breaking Strapi. I might have missed edge cases thought. I tried some MySQL reserved words as well to see if we needed to add them to the list, but we are good on that side.
> Add static list of reserved names

- examples/getstarted/src/components/basic/simple.json
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/DynamicZoneList.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
- packages/core/content-type-builder/admin/src/components/ComponentCard/index.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/index.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/__snapshots__/index.test.js.snap
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/tests/index.test.js
- packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.js
- packages/core/content-type-builder/admin/src/components/DataManagerProvider/reducer.js
- packages/core/content-type-builder/admin/src/components/DataManagerProvider/tests/reducer_basic_actions.test.js
- packages/core/content-type-builder/admin/src/components/FormModal/component/createComponentSchema.js
- packages/core/content-type-builder/admin/src/components/FormModal/component/form.js
- packages/core/content-type-builder/admin/src/components/FormModal/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/reducer.js
- packages/core/content-type-builder/admin/src/components/FormModal/tests/reducer.test.js
- packages/core/content-type-builder/admin/src/components/FormModalHeader/index.js
- packages/core/content-type-builder/admin/src/components/SelectComponent/index.js
- packages/core/content-type-builder/admin/src/components/SelectComponents/index.js
- packages/core/content-type-builder/admin/src/pages/ListView/index.js
- packages/core/content-type-builder/admin/src/pages/ListView/tests/__snapshots__/index.test.js.snap
It uses the displayName instead of the name for the components.
> [V4] Rename component name by displayName

- packages/core/content-type-builder/admin/src/components/ListRow/index.js
> [V4] CTB Fix relation display

- packages/core/admin/server/controllers/admin.js
- packages/core/content-manager/package.json
- packages/core/content-type-builder/package.json
- packages/core/email/package.json
- packages/core/strapi/lib/core/loaders/plugins/get-enabled-plugins.js
- packages/core/strapi/lib/core/loaders/plugins/index.js
- packages/core/upload/package.json
- packages/plugins/documentation/package.json
- packages/plugins/graphql/package.json
- packages/plugins/i18n/package.json
- packages/plugins/sentry/package.json
- packages/plugins/users-permissions/package.json
Add /plugins list api and update description to be plain english for now
> Add /plugins list api and update description to be plain english for now

- packages/core/admin/admin/src/content-manager/pages/EditView/Header/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssetActions.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssets.js
- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
It removes the file from the entry when deleting a file from the media library modal
> [v4] Media Library: fix file deletion in CM

- packages/core/admin/admin/src/content-manager/pages/App/LeftMenu/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/advancedForm.js
> Fix CM leftmenu sorting and remove options for medias and relations

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
Update Search component with SearchURLQuery integrated in:
- Settings / Users
- EE / Settings / Roles
- ML plugin
- User&Permissions Roles (+ fix add role button size)
> QA/ SearchURLQuery update in views

- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/Relation/PopoverContent.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/TableRows/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/Component/index.js
It fixes the relation preview in the LV.
> [v4] CM: fix multiple relations

- packages/core/admin/admin/src/components/LeftMenu/index.js
- packages/core/admin/admin/src/hooks/useMenu/reducer.js
- packages/core/content-type-builder/admin/src/components/PluginIcon/index.js
- packages/core/upload/admin/src/components/PluginIcon/index.js
- packages/generators/generators/lib/files/plugin/admin/src/components/PluginIcon/index.js
- packages/plugins/documentation/admin/src/components/PluginIcon/index.js
> [v4] Remove fontawesome icon for plugins link

- packages/core/upload/admin/src/components/AssetCard/AssetCard.js
- packages/core/upload/admin/src/components/AssetList/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/utils/getAllowedFiles.js
- packages/core/upload/admin/src/components/MediaLibraryInput/utils/tests/getAllowedFiles.test.js
- packages/core/upload/admin/src/utils/tests/toSingularTypes.test.js
- packages/core/upload/admin/src/utils/toSingularTypes.js
It allos the user to add only specific mime type to a media entry in the CM
> [V4] ML in CM: Add allowed types to input media

- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/upload/admin/src/index.js
> Fix media fields register

- examples/getstarted/src/api/category/content-types/category/schema.json
- packages/core/admin/admin/src/content-manager/components/Inputs/index.js
- packages/core/helper-plugin/lib/src/components/DateTimePicker/DateTimePicker.stories.mdx
- packages/core/helper-plugin/lib/src/components/DateTimePicker/index.js
- packages/core/helper-plugin/lib/src/components/DateTimePicker/parseDate.js
- packages/core/helper-plugin/lib/src/components/DateTimePicker/tests/__snapshots__/index.test.js.snap
- packages/core/helper-plugin/lib/src/components/DateTimePicker/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/DateTimePicker/tests/parseDate.test.js
- packages/core/helper-plugin/lib/src/components/GenericInput/index.js
- packages/core/helper-plugin/lib/src/index.js
- yarn.lock
- Add the DateTimePicker component 
- Implement the DateTimePicker on the CM edit view)
> Add DateTimePicker (Implementation on the CM edit view)

- examples/getstarted/src/api/address/policies/address.js
- examples/getstarted/src/api/address/routes/address.js
- examples/getstarted/src/middlewares/test-middleware.js
- examples/getstarted/src/policies/test-policy.js
- packages/core/admin/server/policies/hasPermissions.js
- packages/core/admin/server/policies/isAuthenticatedAdmin.js
- packages/core/content-manager/server/policies/__tests__/has-draft-and-publish.test.js
- packages/core/content-manager/server/policies/has-draft-and-publish.js
- packages/core/content-manager/server/policies/hasPermissions.js
- packages/core/strapi/lib/services/server/compose-endpoint.js
- packages/core/strapi/lib/services/server/policy.js
- packages/core/utils/lib/policy.js
- packages/generators/generators/lib/templates/policy.js.hbs
- packages/plugins/graphql/server/services/content-api/policy.js
Refactor policies to have a consistent factory API like middlewares
This fixes an issue with policy optionally having configs that could create bugs if misused. Now all policies are created through a factory and have the same factory signature as middlewares for ease of use and consistency.
ping @pwizla for the doc :)
> Refactor policies to avoid unintended usage bugs

- packages/core/admin/admin/src/content-manager/components/AttributeFilter/Filters.js
- packages/core/upload/admin/src/pages/App/components/Filters.js
Small temporary fix to prevent filters popover to close when opening select date
> QA/ Filters popover with Date

- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssetActions.js
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/CarouselAssets.js
- packages/core/upload/admin/src/hooks/useEditAsset.js
- packages/core/upload/admin/src/hooks/useUpload.js
- packages/core/upload/server/controllers/validation/upload.js
This should fix:
- Asset uploading / Editing
- Cropping preview
- Carousel that changes its slides when using the keyboard in a dialog appearing over the carousel
> Fix ML feebacks from QA

- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/tests/__snapshots__/MediaLibraryInput.test.js.snap
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
- packages/core/upload/admin/src/pages/App/tests/MediaLibrary.test.js
- packages/core/upload/admin/src/translations/en.json
> Add missing empty states for the ML

- packages/core/content-type-builder/admin/src/components/CheckboxWithNumberField/index.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/baseForm.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/types.js
- packages/core/content-type-builder/admin/src/components/FormModal/attributes/validation/common.js
- packages/core/content-type-builder/admin/src/components/FormModal/index.js
- packages/core/content-type-builder/admin/src/components/SelectNumber/index.js
- packages/core/content-type-builder/admin/src/translations/en.json
> [v4] CTB: Fix field validations

- yarn.lock
> Yarn.lock update

- packages/core/admin/admin/src/content-manager/components/AttributeFilter/Filters.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/Filters/index.js
- packages/core/upload/admin/src/pages/App/components/Filters.js
- yarn.lock
Removed onBlur event for Filters URL Query because it was causing functionals issues.
To add onBlur again we will need to update the popover to not be a portal directly in the DS
> Filters onblur event removed

- packages/core/admin/index.js
- packages/core/admin/package.json
- packages/core/admin/webpack.config.dev.js
- yarn.lock
It upgrades the webpack-dev-server package to the latest version, and also the mini-css-extract-plugin.
Fixes #11508
> [v4] Bump webpack dev server

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
- packages/core/admin/admin/src/content-manager/components/SelectMany/ListItem.js
- packages/core/admin/admin/src/content-manager/components/SelectMany/index.js
- packages/core/admin/admin/src/content-manager/components/SelectWrapper/Option.js
- packages/core/admin/admin/src/content-manager/pages/EditView/DraftAndPublishBadge/index.js
- packages/core/admin/admin/src/content-manager/pages/EditView/DraftAndPublishBadge/tests/index.test.js
- Fixes the biginteger regex
- Fixes the color of the bullet in the D&P badge
- Fixes the relations Minus component
> Fix some ui issues in the relations component

- packages/core/admin/admin/src/content-manager/components/DynamicTable/TableRows/index.js
> Fix CM list view clone url

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/tests/index.test.js
Replaced all Text components by Typography component in Application page
> [DS] Typography Application page

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/DynamicTable/TableRows/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/utils/tableHeaders.js
Replaced all Text components with Typography component in Settings/Users
> [DS] Typography Settings-Users

- packages/core/admin/admin/src/content-manager/components/SelectMany/ListItem.js
> Fix spacing for multiple relations

- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/AssetDialog/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/index.js
It allows to select of type of files when the allowedTypes is undefined.
> [v4] Fix allowedTypes when it is undefined

- examples/getstarted/src/api/category/content-types/category/schema.json
- packages/core/helper-plugin/lib/src/components/DateTimePicker/index.js
- packages/core/helper-plugin/lib/src/components/FilterPopoverURLQuery/Inputs.js
- packages/core/helper-plugin/lib/src/components/FilterPopoverURLQuery/index.js
- packages/core/helper-plugin/lib/src/components/FilterPopoverURLQuery/utils/getFilterList.js
- packages/core/upload/admin/src/components/FilterPopover/FilterValueInput.js
- packages/core/upload/admin/src/components/FilterPopover/index.js
- packages/core/upload/admin/src/components/FilterPopover/utils/getFilterList.js
> Fix filters (CM + Media Library)

- packages/plugins/graphql/server/services/utils/mappers/graphql-filters-to-strapi-query.js
Fix filtering on dates (eg: createdAt, updatedAt) by not treating date instances as operators groups (objects)
Filtering on datetime is actually broken in GraphQL
> [V4] Fix datetime filtering on GraphQL

- packages/core/helper-plugin/lib/src/components/GenericInput/index.js
null-coalescing-operator instead of pipe operator
> Fix falsy check in generic input

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApplicationInfosPage/tests/index.test.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
Fixed headings with as="h2" as="h3" where needed in Users and Application page views
> Fix headings / Users + Application page

- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/AssetDialog/index.js
- packages/core/upload/admin/src/components/EmptyAssets/EmptyAssetGrid.js
- packages/core/upload/admin/src/components/EmptyAssets/index.js
- packages/core/upload/admin/src/pages/App/MediaLibrary.js
> Add tile empty state in ML

- packages/core/admin/admin/src/content-manager/components/DragLayer/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/DisplayedFields.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/FieldButton.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/RelationalFields.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/tests/index.test.js
Add DnD to the relational fields in the CM edit view configuration
1. Edit/Create an entry
2. Configure the view
3. Reorder the relational fields
> Reorder relational fields in the CM edit configuration view

- packages/core/email/admin/src/pages/Settings/components/Configuration.js
- packages/core/email/admin/src/pages/Settings/index.js
- packages/core/email/admin/src/pages/Settings/tests/index.test.js
Replaced Text components with Typography
Fixed envelop icon
Fixed default message for Configuration subtitle
Updated tests
> [DS] Typography in Settings/Email

- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/CroppingActions.js
- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/index.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/UploadAssetDialog.js
- packages/core/upload/admin/src/utils/createAssetUrl.js
- packages/core/upload/admin/src/utils/rawFileToAsset.js
Should allow to edit locale files before uploading
> Allow to edit local file before uploading

- packages/plugins/users-permissions/admin/src/pages/EmailTemplates/components/EmailTable.js
- packages/plugins/users-permissions/admin/src/pages/EmailTemplates/tests/index.test.js
Replaced all Text components with Typography in U&P Email templates
> [DS] Typography in Users&Permissions/Email templates

- packages/plugins/users-permissions/admin/src/components/BoundRoute/index.js
- packages/plugins/users-permissions/admin/src/components/Permissions/PermissionRow/SubCategory.js
- packages/plugins/users-permissions/admin/src/components/Policies/index.js
- packages/plugins/users-permissions/admin/src/components/UsersPermissions/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/components/TableBody.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
Replaced all Text components with Typography component in U&P/Roles views
> [DS] Typography Users&Permissions/Roles

- packages/core/admin/server/strategies/api-token.js
- packages/plugins/users-permissions/server/services/jwt.js
- packages/plugins/users-permissions/server/strategies/users-permissions.js
Allow `access_token` query param for auth
> Allow access_token query param for auth

- packages/core/admin/admin/src/content-manager/components/AttributeFilter/hooks/useAllowedAttributes.js
- packages/core/admin/admin/src/content-manager/pages/ListView/FieldPicker/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
It allows to filter on the createdAt and upatedAt fields.
Because we want to filter!
> [v4] CM: Add timestamps to filters

- packages/plugins/documentation/admin/src/pages/PluginPage/tests/index.test.js
- packages/plugins/documentation/admin/src/pages/SettingsPage/index.js
- packages/plugins/documentation/admin/src/pages/SettingsPage/tests/index.test.js
- packages/plugins/documentation/admin/src/pages/SettingsPage/tests/server.js
Replaced Text components with Typography in Settings/Documentation
Fixed snapshots for plugin and settings documentation views not waiting for data to be loaded
> [DS] Typography in Settings/Documentation

- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/index.js
- packages/plugins/users-permissions/admin/src/pages/AdvancedSettings/tests/index.test.js
Replaced Text components with Typography in U&P / Advanced settings
> [DS] Typography in Users&Permissions/ Advanced settings

- packages/plugins/users-permissions/admin/src/pages/Providers/index.js
Replaced all Text components with Typography in U&P Providers
> [DS] Typography in Users&Permissions/Providers

- examples/getstarted/config/database.js
- packages/core/database/lib/dialects/mysql/schema-inspector.js
- packages/core/database/lib/dialects/postgresql/schema-inspector.js
- packages/core/database/lib/index.js
- packages/core/database/lib/migrations/index.js
- packages/core/database/lib/migrations/storage.js
- packages/core/database/lib/query/helpers/join.js
- packages/core/database/lib/query/query-builder.js
- packages/core/database/lib/schema/builder.js
- packages/core/database/lib/schema/storage.js
- packages/core/strapi/lib/Strapi.js
Support schema option and add forceMigration options
Support `postgres` database schemas & disabling column & table deletion
Fixes https://github.com/strapi/strapi/issues/11367
> Support schema option and add forceMigration options

- packages/core/strapi/lib/middlewares/security.js
- packages/plugins/documentation/server/routes/index.js
- Fix wrong policies used in routes
- Fix CSP config for the documentation view
Fixes https://github.com/strapi/strapi/issues/11556
> Fix documentation plugin access

- packages/core/admin/admin/src/content-manager/components/AttributeFilter/hooks/useAllowedAttributes.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/FieldPicker/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/admin/src/content-manager/pages/ListViewLayoutManager/index.js
- packages/core/content-manager/package.json
- packages/core/content-manager/server/services/data-mapper.js
- packages/core/content-manager/server/services/utils/configuration/attributes.js
- packages/core/content-manager/server/tests/index.test.e2e.js
- packages/core/content-manager/server/tests/single-type.test.e2e.js
- packages/core/utils/lib/__tests__/content-types.test.js
- packages/core/utils/lib/content-types.js
Add createdAt and updatedAt back into the CM layouts and metas.
Fixes https://github.com/strapi/strapi/issues/11151
> Add createdAt and updatedAt back into the CM layouts and metas

- packages/core/admin/admin/src/pages/AuthPage/index.js
This PR differentiates first admins in our analytics.
> Differentiate first admin

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/EventInput/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/HeadersInput/Combobox.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/EditView/components/TriggerContainer/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/tests/index.test.js
Integrated Typography in Webhooks views
Fixed snapshots previously not waiting for data to be loaded 
Fixed Combobox HeadersInput not accepting newly created value as ComboboxOption
> [DS] Typography in webhooks

- packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/AssetPreview.js
Fix showing pdf / doc icon in the good place
> Fix asset types img

- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/Filters.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/index.js
- packages/core/upload/admin/src/components/AssetDialog/index.js
- packages/core/upload/admin/src/components/FilterPopover/index.js
- packages/core/upload/admin/src/hooks/useModalAssets/useModalQueryParams.js
- packages/core/upload/admin/src/utils/displayedFilters.js
> [v4] Add filters to ML modal

- packages/core/admin/admin/src/content-manager/pages/ListView/PaginationFooter/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
It reduces the padding of the footer in the list views
> [v4] Fix list footer padding

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/PaginationFooter/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/GenericInput/index.js
- packages/core/upload/admin/src/components/MediaLibraryInput/tests/__snapshots__/MediaLibraryInput.test.js.snap
- packages/plugins/users-permissions/admin/src/pages/Roles/CreatePage/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/Roles/EditPage/tests/index.test.js
> [v4] Fix password icon color

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/pages/EditView/index.js
- packages/core/admin/admin/src/content-manager/pages/ListView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/tests/index.test.js
- packages/core/helper-plugin/lib/src/components/SearchURLQuery/index.js
- packages/core/helper-plugin/lib/src/components/SearchURLQuery/tests/index.test.js
- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/tests/index.test.js
It fixes some UI bugs in the CM.
> [v4] CM: fix some ui bugs

- packages/core/admin/admin/src/translations/en.json
- packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/tests/index.test.js
- packages/core/admin/ee/admin/pages/SettingsPage/SingleSignOn/tests/server.js
Added Settings title with Typography in Admin/SSO
Fixed tests: now it waits for data to be loaded before snapshotting + aria disabled save button test uncommented
> [DS] Typography in SSO

- packages/core/admin/admin/src/pages/HomePage/HomeHeader.js
- packages/core/admin/admin/src/pages/HomePage/SocialLinks.js
- packages/core/admin/admin/src/pages/HomePage/tests/index.test.js
Replaced all Text components with Typography in Homepage view
> [DS] Typography in Homepage

- packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/PageSize.js
- packages/core/upload/admin/src/components/AssetDialog/BrowseStep/PaginationFooter/components.js
- packages/core/upload/admin/src/components/AssetDialog/DialogTitle.js
- packages/core/upload/admin/src/components/AssetDialog/SelectedStep/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/AssetMeta.js
- packages/core/upload/admin/src/components/EditAssetDialog/index.js
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/EditAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/EditAssetDialog/tests/__snapshots__/index.test.js.snap
- packages/core/upload/admin/src/components/MediaLibraryInput/Carousel/EmptyStateAsset.js
- packages/core/upload/admin/src/components/MediaLibraryInput/tests/__snapshots__/MediaLibraryInput.test.js.snap
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/AddAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/FromComputerForm.js
- packages/core/upload/admin/src/components/UploadAssetDialog/AddAssetStep/tests/FromComputerForm.test.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/PendingAssetStep.js
- packages/core/upload/admin/src/components/UploadAssetDialog/PendingAssetStep/tests/__snapshots__/PendingAssetStep.test.js.snap
- packages/core/upload/admin/src/components/UploadAssetDialog/tests/__snapshots__/UploadAssetDialog.test.js.snap
- packages/core/upload/admin/src/components/UploadProgress/index.js
- packages/core/upload/admin/src/components/UploadProgress/tests/index.test.js
- packages/core/upload/admin/src/pages/App/components/BulkDeleteButton.js
- packages/core/upload/admin/src/pages/SettingsPage/index.js
Integrated Typography in Media Library
> [DS] Typography in Media Library

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/tests/__snapshots__/index.test.js.snap
> [v4] CM: Fix Dz label padding

- packages/core/content-type-builder/admin/src/components/FormModal/index.js
> [v4] CTB: Clear modal state when closing it

- packages/core/admin/admin/src/pages/SettingsPage/pages/Webhooks/ListView/index.js
- packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewCopyLocale/index.js
- packages/plugins/i18n/admin/src/components/CMEditViewInjectedComponents/CMEditViewLocalePicker/index.js
- packages/plugins/i18n/admin/src/components/CMListViewInjectedComponents/DeleteModalAdditionalInfos/index.js
- packages/plugins/i18n/admin/src/components/CheckboxConfirmation/index.js
- packages/plugins/i18n/admin/src/components/LocaleList/LocaleTable.js
- packages/plugins/i18n/admin/src/components/LocaleListCell/LocaleListCell.js
- packages/plugins/i18n/admin/src/components/ModalCreate/index.js
- packages/plugins/i18n/admin/src/components/ModalEdit/index.js
Replaced all Text components with Typography in all i18n settings + CM components
Removed a log in webhooks edit/create view left from a previous PR 😬
> [DS] Typography i18n settings

- packages/core/admin/admin/src/content-manager/components/ComponentInitializer/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/Media/FileWrapper.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/Relation/PopoverContent.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/Relation/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/ConfirmDialogDelete/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicTable/ConfirmDialogDeleteAll/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/AddComponentButton/tests/__snapshots__/index.test.js.snap
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/ComponentCard/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/index.js
- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/DzLabel/index.js
- packages/core/admin/admin/src/content-manager/components/FieldComponent/Label.js
- packages/core/admin/admin/src/content-manager/components/Hint/index.js
- packages/core/admin/admin/src/content-manager/components/InputJSON/FieldError.js
- packages/core/admin/admin/src/content-manager/components/InputJSON/Label.js
- packages/core/admin/admin/src/content-manager/components/InputUID/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/AccordionGroupCustom/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/AddFieldButton.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DragPreview.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/DraggedItem/DraggingSibling.js
Replaced Text components with Typography in CM - part 1
> [DS] Typography CM / Part 1

- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/ListPage/ModalForm/index.js
It unlocks the app when there's an error when creating a user.
> [V4] Unlock app when there is an error when creating a user

- packages/core/admin/admin/src/components/AutoReloadOverlayBlockerProvider/Blocker.js
- packages/core/admin/admin/src/components/LeftMenu/index.js
- packages/core/admin/admin/src/components/UpgradePlanModal /index.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/DisplayedFields.js
- packages/core/admin/admin/src/content-manager/pages/EditSettingsView/components/RelationalFields.js
- packages/core/admin/admin/src/pages/Admin/Onboarding/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ForgotPassword/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ForgotPasswordSuccess/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Login/BaseLogin.js
- packages/core/admin/admin/src/pages/AuthPage/components/Login/tests/BaseLogin.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/Oops/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Oops/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/Register/tests/index.test.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/index.js
- packages/core/admin/admin/src/pages/AuthPage/components/ResetPassword/tests/index.test.js
- packages/core/admin/admin/src/pages/ProfilePage/index.js
- packages/core/admin/admin/src/pages/ProfilePage/tests/index.test.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Login/index.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Providers/SSOProviders.js
- packages/core/admin/ee/admin/pages/AuthPage/components/Providers/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/index.js
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/CreatePage/tests/__snapshots__/index.test.js.snap
- packages/core/admin/ee/admin/pages/SettingsPage/pages/Roles/ListPage/index.js
- packages/plugins/documentation/admin/src/pages/PluginPage/index.js
- packages/plugins/documentation/admin/src/pages/PluginPage/tests/index.test.js
Replaced all Text components with Typography in last views:
- Auth
- Profile page
- Admin components
- Settings Roles (some left)
- CM (for 2 commented code) 
- Documentation plugin page
> [DS] Typography last fixes

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/Component/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/AccordionGroupCustom/index.js
- packages/core/admin/admin/src/content-manager/components/RepeatableComponent/index.js
Small UI fix:
- DZ action icons now become primary600 when accordion expanded
- Repeatable component footer and accordion toggle border-radius fix
> [QA] DZ + Rep Components fixes

- packages/core/strapi/lib/Strapi.js
Check app and admin are defined in destroy
Fixes https://github.com/strapi/strapi/issues/11472
> Check app and admin are defined in destroy

- packages/core/content-manager/server/controllers/__tests__/single-types.test.js
- packages/core/content-manager/server/controllers/collection-types.js
- packages/core/content-manager/server/controllers/single-types.js
- packages/core/content-manager/server/services/__tests__/entity-manager.test.js
- packages/core/content-manager/server/services/entity-manager.js
Update updatedBy on publish / unpublish actions in the CM
Fixes https://github.com/strapi/strapi/issues/11498 for v4 only.
> Update updatedBy on publish / unpublish actions in the CM

- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/components/ContentBox/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/EditView/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/DynamicTable/DeleteButton/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/DynamicTable/index.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js
Add telemetry to the API token
> add usage tracking in the api token

- packages/core/content-type-builder/server/services/constants.js
- packages/core/content-type-builder/server/services/content-types.js
- packages/plugins/users-permissions/server/content-types/permission/index.js
- packages/plugins/users-permissions/server/content-types/role/index.js
Prevent relation to be made for the API token and the locale.
> Prevent relation to api token and locale

- packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorStylesContainer.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js
Fixed WYSIWYG placeholder font
> [QA] Wysiwyg placeholder

- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/utils/validations/users/edit.js
- packages/core/admin/admin/src/pages/SettingsPage/pages/Users/utils/validations/users/profile.js
> Fix some bugs (User edit & CM validations)

- packages/core/admin/admin/src/content-manager/components/Wysiwyg/Editor.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/EditorStylesContainer.js
- packages/core/admin/admin/src/content-manager/components/Wysiwyg/tests/index.test.js
Fixed WYSIWYG placeholder color
Added codemirror placeholder addon
Added style to placeholder
> [QA] WYSIWYG placeholder color

- packages/core/admin/admin/src/content-manager/components/DynamicZone/components/ComponentPicker/Category/index.js
QA issue: 
Added fixed width to component card in DZ to avoid having card stretched out
> [QA] Dz components fixed width

- packages/core/upload/server/graphql.js
- packages/plugins/graphql/server/services/builders/type.js
Allow to query media attributes without getting forbidden errors
> [V4] GraphQL fix media attributes queries

- examples/getstarted/src/api/restaurant/content-types/restaurant/schema.json
- packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/utils/schema.js
Removed !isDraft condition for checking min errors on DZ and Repeatable components when saving an entry with Draft&Publish
> [QA] Form validation when D&P for DZ and Rep component

- packages/plugins/users-permissions/admin/src/pages/Roles/ListPage/index.js
Added useFocusWhenNavigate in U&P Roles
> Fixed focus in U&P Roles

- packages/plugins/documentation/admin/src/pages/PluginPage/index.js
- packages/plugins/documentation/admin/src/translations/en.json
Fixed typo in documentation plugin
> [QA] Fixed typo in Documentation plugin

- packages/core/content-type-builder/admin/src/components/FormModal/index.js
- packages/core/content-type-builder/admin/src/components/Relation/RelationField/RelationTargetPicker/index.js
> Fix target relation field (CTB)

- packages/core/admin/package.json
Delete the admin build before rebuilding
On each publish it adds files in the build folder but doesn't remove old ones. the folder is growing endlessly
> Delete the admin build before rebuilding

- packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js
Fix the Single type locale delete
> Fix single type locale delete
